#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list23_unit1 = VocabularyList([Word('sermon', "",
                                   [TestWay('n',
                                            '布道, 说教',
                                            'public speech usually by a member of the clergy for the purpose of giving moral guidance or uplift',
                                            ["sermon whose message was that we should love our neighbors as much as we love ourselves 主题是教导我们要像爱自己一样爱邻居的一次布道"],
                                            'homily')]),
                              Word('serpentine', "",
                                   [TestWay('adj',
                                            '弯曲的',
                                            'winding or turning one way and another',
                                            ["the country inn lies at the end of a rather serpentine road 乡村小酒吧坐落在一条非常蜿蜒的道路的尽头"],
                                            'curvy, devious, sinuous, tortuous, twisted, winding',
                                            'direct, straight, straightaway')]),
                              Word('serrate', "",
                                   [TestWay('adj',
                                            '锯齿状的',
                                            'notched or toothed on the edge',
                                            ["a serrate leaf 锯齿状的叶片"],
                                            antonyms = 'without notches, smooth')]),
                              Word('serried', "",
                                   [TestWay('adj',
                                            '密集的',
                                            'having little space between items or parts',
                                            ["Flowers came up every spring in their serried ranks. 大量的鲜花在春季盛开。"],
                                            'compact, dense',
                                            'widely separated, airy, loose, open, uncrowded')]),
                              Word('servile', "",
                                   [TestWay('adj',
                                            '低下的, 卑屈的',
                                            'meanly or cravenly submissive: abject',
                                            ["had always maintained a servile attitude around people with money 对有钱人卑躬屈膝"],
                                            'base, humble, menial, slavish')]),
                              Word('severe', "",
                                   [TestWay('adj',
                                            '严厉的, 要求严格的',
                                            'given to exacting standards of discipline and self-restraint',
                                            ["a severe, uncompromising teacher 一位严厉、不妥协的老师"],
                                            'austere, harsh, ramrod, rigid, rigorous, stern',
                                            'clement, forbearing, gentle, indulgent, lax, lenient, tolerant'),
                                    TestWay('adj',
                                            '难以承受的, 艰难的',
                                            'difficult to endure',
                                            ["a severe winter that was among the coldest on record 有记录的最寒冷的冬天之一"],
                                            'brutal, excruciating, grievous, onerous, oppressive, tough, trying',
                                            'easy, light, soft')]),
                              Word('shackle', "",
                                   [TestWay('vt',
                                            '束缚',
                                            'to deprive of freedom especially of action by means of restrictions or handicaps',
                                            ["unwilling to shackle the dogs to the wall of the house 不愿意把狗拴在墙边"],
                                            'chain, enchain, enfetter, fetter, gyve, handcuff, manacle, pinion, trammel',
                                            'loose, emancipate, unbind, unfetter, unshackle'),
                                    TestWay('v',
                                            '限制, 阻碍',
                                            'to create difficulty for the work or activity of',
                                            ["shackled by poverty and ignorance 被贫穷和无知所阻碍"],
                                            'clog, cramp, encumber, fetter, hinder, impede, inhibit, interfere with, manacle, obstruct, short-circuit, stymie, tie up, trammel',
                                            'aid, assist, facilitate, help')]),
                              Word('shadow', "",
                                   [TestWay('vt',
                                            '偷偷尾随',
                                            'to follow especially secretly: trail',
                                            ["shadowing the suspect to see what he was up to 尾随嫌犯行踪"],
                                            'chase, course, pursue, trace, track, trail',
                                            'shadowy 模糊的: faintly perceptible: indistinct 【例】He had only a shadowy idea of what they wanted him to do. 他对要做的事只有一个模糊的想法。')]),
                              Word('shallow', "",
                                   [TestWay('adj',
                                            '浅显的, 浅薄的',
                                            'having or showing a lack of depth of understanding or character',
                                            ["shallow generalizations 一个浅显的概览"],
                                            'facile, one-dimensional, skin-deep',
                                            'profound')]),
                              Word('sham', "",
                                   [TestWay('n',
                                            '欺瞒',
                                            'the quality of deceitfulness; empty pretense',
                                            ["condemned the rigged election as a total sham 指责这次有作弊的选举是彻头彻尾的骗局"],
                                            antonyms = 'debunk'),
                                    TestWay('v',
                                            '掩饰, 假装',
                                            'to present a false appearance of',
                                            ["shammed a most unconvincing limp just to get sympathy 非常拙劣地假装自己腿脚不便, 以博得同情"],
                                            synonyms = 'affect, bluff, counterfeit, dissemble, fake, simulate, pretend, profess, put on, pass for'),
                                    TestWay('adj',
                                            '虚假的',
                                            'not genuine; fake',
                                            ["street vendors selling sham designer handbags to gullible tourists 街头小贩向易上当的游客兜售山寨的设计师手包"],
                                            'bogus, forged, phony, spurious, unauthentic',
                                            'genuine, authentic, bona fide, real, unfaked')])])

list23_unit2 = VocabularyList([Word('shiftless', "",
                                   [TestWay('adj',
                                            '胸无大志, 懒惰的',
                                            'lacking in ambition or incentive: lazy',
                                            ["shiftless spongers who never thought to do anything for themselves 无志气的弃民们, 从来没有想过改变自己"],
                                            'idle, indolent, slothful',
                                            'industrious')]),
                              Word('shipshape', "",
                                   [TestWay('adj',
                                            '井然有序的',
                                            'marked by meticulous order and neatness',
                                            ["I like to keep my car shipshape. 我喜欢打理我的车。"],
                                            'antiseptic, kempt, orderly, prim, uncluttered, well-groomed',
                                            'disheveled, disordered, disorderly, messy, sloven, unkempt, untidy')]),
                              Word('shirk', "",
                                   [TestWay('vi',
                                            '逃避, 规避',
                                            'to get or keep away from (as a responsibility) through cleverness or trickery',
                                            ["shirk one’s duty 逃避责任"],
                                            'avoid, dodge, elude, eschew, evade, shun, weasel out of')]),
                              Word('shoal', "",
                                   [TestWay('adj',
                                            '浅的',
                                            'having little depth ; shallow',
                                            ["shoal waters of the bay 海湾附近的浅水区"],
                                            antonyms = 'deep')]),
                              Word('shopworn', "",
                                   [TestWay('adj',
                                            '陈旧的',
                                            'worn-out, as from overuse; trite',
                                            ["the shopworn suggestion to job applicants to “just be yourself” 老掉牙的让应征者“做你自己”的提议"],
                                            'banal, cliché, commonplace, hackneyed, trite, well-worn',
                                            'new, fresh, novel, original, unclichéd, unhackneyed')]),
                              Word('shred', "",
                                   [TestWay('n',
                                            '少量',
                                            'a small amount; a particle',
                                            ["He struggled to retain a shred of his dignity. 他勉强挽救了一点尊严。"],
                                            'crumb, driblet, mite, scintilla, spark, speck, sprinkling, tad')]),
                              Word('shrewd', "",
                                   [TestWay('adj',
                                            '精明的, 机敏的',
                                            'having or showing a practical cleverness or judgment',
                                            ["He's shrewd about his investments. 他是个精明的投资人。"],
                                            'crafty, cunning, devious, sly, subtle, wily, astute, savvy, sharp',
                                            'foolish, naïve, unknowing'),
                                    TestWay('adj',
                                            '刺骨的, 强烈的',
                                            "causing intense discomfort to one's skin",
                                            ["She pulled her coat tighter against the shrewd breeze whipping down the alley. 巷子里挂着刺骨的风, 她拉紧了大衣。"],
                                            'biting, bitter, keen, penetrating, piercing, raw, sharp, stinging')]),
                              Word('shrink', "",
                                   [TestWay('v',
                                            '在数量或价值方面变低; 减小',
                                            'to become reduced in amount or value; dwindle',
                                            ["His savings quickly shrank. 他的存款急剧减少。"],
                                            'compress, condense, constrict',
                                            'balloon, expand, snowball, swell'),
                                    TestWay('v',
                                            '本能性地退却(如因遇到使人惊恐的􁸀物); 退缩',
                                            'to draw back instinctively, as from something alarming; recoil',
                                            ["shrinking back from the approaching flames 对着燃烧的火焰望而却步"],
                                            'blench, cringe, quail, recoil, squinch, wince'),
                                    TestWay('v',
                                            '表示出不情愿; 犹豫',
                                            'to show reluctance; hesitate',
                                            ["shrink from making such a sacrifice 对做出这样的牺牲犹豫不决"])]),
                              Word('shroud', "",
                                   [TestWay('n',
                                            '隐蔽物, 可起隐藏、保护或屏护作用的某物',
                                            'something that conceals, protects, or screens:',
                                            ["under a shroud of fog 在迷雾的掩护下"]),
                                    TestWay('v',
                                            '将…从视线中隔离, 遮蔽',
                                            'to shut off from sight; screen',
                                            ["shrouded the fact that the child had been adopted 将孩子是领养的这个事实隐藏起来"],
                                            'belie, blanket, cloak, conceal, cover, curtain, disguise, mask, occult, screen, veil, blot out, paper over',
                                            'bare, disclose, display, divulge, expose, reveal, show')]),
                              Word('shrug', "",
                                   [TestWay('v',
                                            '轻视, 忽略',
                                            'to dismiss as of little importance',
                                            ["The administration was willing to shrug off the problem. 当局有意忽略这个问题"],
                                            'disregard, gloss, ignore, minimize, overlook, overpass, slight, slur, wink',
                                            'attend, heed, mind'),
                                    TestWay('v',
                                            '脱下(衣物等)',
                                            'to rid oneself of (a garment)',
                                            ["She shrugged off her coat and hung it up neatly. 她脱下了她的大衣, 将其整齐地挂好。"],
                                            'doff, douse, put off, take off',
                                            'don, put on')])])

list23_unit3 = VocabularyList([Word('shun', "",
                                   [TestWay('vt',
                                            '避开, 避免',
                                            'to avoid deliberately; keep away from',
                                            ["After his divorce he found himself being shunned by many of his former friends. 自从他离婚以来, 他发现许多曾经的朋友都刻意躲着他。"],
                                            'avoid, dodge, duck, elude, eschew, evade, finesse, scape, shirk',
                                            'accept, embrace, welcome, pursue, seek')]),
                              Word('sidestep', "",
                                   [TestWay('vt',
                                            '(通过逃避而)不遵守',
                                            'to avoid having to comply with (something) especially through cleverness',
                                            ["The eager enlistee sidestepped the regulations by lying about his age. 急切的应募者通过谎报自己的年龄躲过了规定的限制。"],
                                            'beat, bypass, dodge, shortcut, skirt',
                                            'comply, follow, keep, obey, observe')]),
                              Word('signal', "",
                                   [TestWay('adj',
                                            '(在重要性、成就方面)非同寻常的',
                                            'standing above others in rank, importance, or achievement',
                                            ["The Louisiana Purchase is cited by many historians as one of the most signal events in American history. 从法国手中购买路易斯安那被许多历史学家认为是美国历史上最重要的事件之一。", "a signal feat 一项非同寻常伟业"],
                                            'distinguished, illustrious, luminous, notable, noteworthy, outstanding, preeminent, prestigious, redoubtable',
                                            'average, inferior, mediocre, insignificant, minor, unimportant'),
                                    TestWay('v',
                                            '给出信号',
                                            'to direct or notify by a movement or gesture',
                                            ["They signaled at me to come over to their table. 他们向我打招呼要我到他们那桌去。", "A lock on the suitcase might signal that there's something of value inside. 手􁨀箱上的锁可能意味着其中有贵重物品。"],
                                            'beckon, flag, gesture, wave')]),
                              Word('simpleton', "",
                                   [TestWay('n',
                                            '(缺乏常识的)笨蛋',
                                            'a person lacking in common sense; a stupid person',
                                            ["His silly antics at office parties have earned him a reputation as a simpleton. 他在办公室聚会上愚蠢的古怪行为让他被人认为是个蠢货。"],
                                            'airhead, dolt, donkey, dullard, fool, idiot, moron',
                                            'intellectual, sage, wit, genius, prodigy')]),
                              Word('simulate', "",
                                   [TestWay('v',
                                            '假装, 模仿',
                                            'to have or take on the appearance, form, or sound of; imitate',
                                            ["cosmetics that simulate a suntan 用来模仿晒黑效果的化妆品"],
                                            'act, affect, assume, counterfeit, dissemble, fake, imitate, pretend, profess, sham'),
                                    TestWay('v',
                                            '模拟',
                                            'to create a representation or model of (a physical system or particular situation)',
                                            ["carrying out an experiment to simulate weightlessness 进行了模拟失重状态的实验"])]),
                              Word('sin', "",
                                   [TestWay('n',
                                            '罪恶的事',
                                            'an action that is or is felt to be highly reprehensible; morally unacceptable',
                                            ["It's a sin to waste food when people are starving. 当有人还在挨饿时浪费食物是一种罪过。"],
                                            'bad, evildoing, ill, immorality, iniquity, villainy, wrong',
                                            'good, morality, right, virtue',
                                            'sinful adj. 罪恶的, 有罪的')]),
                              Word('sincere', "",
                                   [TestWay('adj',
                                            '真诚的, 不做作的',
                                            'being without hypocrisy or pretense; true',
                                            ["She offered a sincere apology for her angry outburst. 她为她先前的盛怒表示诚挚的歉意。"],
                                            'artless, genuine, heartfelt, honest, ingenuous, innocent, natural, real, true, unaffected, unfeigned',
                                            'affected, artful, artificial, assuming, dissembling, fake, guileful, insincere, phony, pretentious')]),
                              Word('sinecure', "",
                                   [TestWay('n',
                                            '美差',
                                            'an office or position that requires little or no work and that usually provides an income',
                                            ["a lucrative sinecure in a big law firm 在大法律公司高报酬的美差"],
                                            antonyms = 'drudge, drudgery, moil, sweat, toil, travail')]),
                              Word('sinew', "",
                                   [TestWay('n',
                                            '活力, 力量',
                                            'vigorous strength; muscular power',
                                            ["Money is the sinew of love as well as war. 爱情和战争都要用金钱来保证。"],
                                            'energy, firepower, force, horsepower, might, muscle, potency, power, puissance, strength, vigor',
                                            'impotence, impotency, powerlessness, weakness')]),
                              Word('singe', "",
                                   [TestWay('vt',
                                            '轻微烧焦',
                                            'to burn superficially or lightly',
                                            ["The iron is too hot, and you'll singe the nightdress. 熨斗太烫了, 你会把睡衣烫坏的。", "The marshmallows got a bit singed over the campfire, but we like them that way. 棉花糖因为营火而有些许烧焦, 但我们还是很喜欢它的味道。"],
                                            'char, scorch, sear',
                                            'incinerate')])])

list23_unit4 = VocabularyList([Word('sinuous', "",
                                   [TestWay('adj',
                                            '蜿蜒的, 迂回的',
                                            'marked by a long series of irregular curves; not direct',
                                            ["The river flowed in a sinuous path through the lush valley. 蜿蜒曲折的河流流过茂密的山谷。", "Thirty-year-old men are novel, rich in content and sinuous in plots. 三十岁的男人是小说, 内容丰富, 情节曲折。"],
                                            'bending, curling, curved, curving, devious, serpentine, tortuous, twisted, winding, windy',
                                            'straight, straightaway')]),
                              Word('sip', "",
                                   [TestWay('vt',
                                            '(尤指小口地)喝',
                                            'to swallow in liquid form, especially in small quantities',
                                            ["slowly sipping the hot soup 慢慢地喝着热汤‖She sipped her coffee while she watched the sun rise. 她一边看着日出, 一边喝着她的咖啡。"],
                                            'gulp, guzzle, hoist, imbibe, quaff, swill',
                                            'vomit, throw up')]),
                              Word('skeleton', "",
                                   [TestWay('n',
                                            '骨架, 框架',
                                            'something forming a structural framework',
                                            ["Only the charred skeleton of the house remained after the fire. 大火过后整个房子只剩下被烧焦的骨架了。", "We saw a skeleton of the report before it was published. 在报告发表之前, 我们看到了他的整体框架。"],
                                            'architecture, configuration, edifice, fabric, framework, framing, infrastructure, shell, structure')]),
                              Word('skeptic', "",
                                   [TestWay('n',
                                            '怀疑者',
                                            'one who instinctively or habitually doubts, questions, or disagrees with assertions or generally accepted conclusions',
                                            ["You can either be a skeptic or not, but I believe it anyway. 至于你信不信, 我反正信了。"],
                                            'disbeliever, doubter, questioner, unbeliever',
                                            'dupe, gull, pigeon',
                                            'skeptical adj. 持怀疑态度的; skepticism n. 怀疑论')]),
                              Word('skimp', "",
                                   [TestWay('adj',
                                            '缺乏的, 不足的',
                                            'less plentiful than what is normal, necessary, or desirable',
                                            ["The dieter complained about skimp meals that were served at the fat farm. 这个节食者抱怨说减肥疗养地的伙食少得可怜。"],
                                            'exiguous, meager, niggardly, poor, scant, scanty, scarce, skimpy, slender, slim, sparing, sparse, stingy',
                                            'abundant, ample, bountiful, copious, generous, liberal, plenteous, plentiful'),
                                    TestWay('vt',
                                            '节省花费, 吝啬',
                                            'to give insufficient or barely sufficient attention or effort to or funds for',
                                            ["We must skimp and save if we are going to afford a vacation this summer. 要是我们这个夏天要出去旅行, 那么就得开始节省出一些钱了。"],
                                            'pinch, save, scrimp, spare, stint',
                                            'dissipate, lavish, prodigalize, squander, waste')]),
                              Word('skirmish', "",
                                   [TestWay('n',
                                            '小冲突, 争论',
                                            'a minor or preliminary conflict or dispute',
                                            ["They had a skirmish over the rules before the debate began. 在辩论开始之前他们就规则而吵了起来。"],
                                            'altercation, controversy, disagreement, dispute, hassle, imbroglio, quarrel, spat, squabble, tiff, wrangle',
                                            'amity, concord, harmony, rapport, rapprochement')]),
                              Word('skirt', "",
                                   [TestWay('n',
                                            '界限, 边界',
                                            'the line or relatively narrow space that marks the outer limit of something',
                                            ["an old shack on the skirts of the town 城镇边界上的一座老房子"],
                                            'borderline, boundary, circumference, compass, confines, edge, frame, fringe, margin, perimeter, periphery, verge',
                                            'center, core, kernel'),
                                    TestWay('vt',
                                            '绕行, 避开',
                                            'to go around or keep away from in order to avoid danger or discovery',
                                            ["skirted the construction zone 绕开建筑工地", "The new bill would make it harder for companies toskirt environmental regulations. 新的规定会增加公司逃脱环境监管的难度。"],
                                            'bypass, circumvent, detour, shortcut, sidestep',
                                            'pursue, seek')]),
                              Word('slack', "",
                                   [TestWay('adj',
                                            '松弛的',
                                            'not tightly fastened, tied, or stretched',
                                            ["The rope is too slack. 绳子太松了"],
                                            'insecure, lax, loosened, relaxed, slackened, unsecured',
                                            'taut, tense, tight'),
                                    TestWay('adj',
                                            '疏忽的, 大意的',
                                            'failing to give proper care and attention',
                                            ["This building contractor is known mainly for his firm's slack workmanship and slipshod construction. 这个建筑承包商因其手下公司不负责任的粗糙做工和马虎建造的建筑物而闻名。"],
                                            'careless, derelict, disregardful, lax, lazy, neglectful, neglecting, negligent, remiss',
                                            'attentive, careful, conscientious, alert, heedful, mindful, observant, regardful, vigilant, wary, watchful')]),
                              Word('slake', "",
                                   [TestWay('vt',
                                            '使满足',
                                            'to satisfy (a craving); quench',
                                            ["Mountain climbing has largely slaked my desire for adventure. 登山很大程度上满足了我对探险的渴望。"],
                                            'assuage, quench, sate, satiate, satisfy',
                                            'tantalize, tease, arouse, excite, pique, stimulate')]),
                              Word('slant', "",
                                   [TestWay('n',
                                            '(看待问题、思考的)角度, 看法',
                                            'a way of looking at or thinking about something',
                                            ["an interesting slant on the problem of underage drinking 在青少年饮酒这个问题上一个有趣的视角"],
                                            'angle, outlook, perspective, standpoint, viewpoint'),
                                    TestWay('adj',
                                            '倾斜的',
                                            'running in a slanting direction',
                                            ["The computer keyboard has a slightly slant surface so that typing is more comfortable for the wrists. 电脑键盘有一个微小的倾斜角, 因此打字不会使手腕感到不适。"],
                                            'canted, graded, inclined, leaning, listing, oblique, pitched, raked, slanted, sloping, tilting',
                                            'perpendicular, plumb, vertical, horizontal, level'),
                                    TestWay('vt',
                                            '歪曲(事实等)',
                                            'to change so much as to create a wrong impression or alter the meaning of',
                                            ["Reporters slanted the truth in order to push a political agenda. 为了推动政治进程, 记者们歪曲了事实。"],
                                            'bend, color, distort, falsify, misinterpret, misrelate, misrepresent, misstate, pervert, twist, warp',
                                            'clarify, clear, elucidate, illuminate, illustrate')])])

list23_unit5 = VocabularyList([Word('slate', "",
                                   [TestWay('vt',
                                            '列入名单, 计划, 安排',
                                            'to put (someone or something) on a list',
                                            ["You've been slated for a three o'clock interview. 你的面试被安排在三点。"],
                                            'catalog, enroll, enter, index, inscribe, record, register, schedule',
                                            'delete, erase')]),
                              Word('slew', "",
                                   [TestWay('n',
                                            '大量, 许多',
                                            'a large amount or number',
                                            ["donate a slew of books to the university library 向大学图书馆捐赠了大量的书籍"],
                                            'abundance,bundle, dozen, multiplicity, myriad, plentitude, profusion, scad, shipload, volume, wealth',
                                            'ace, bit, driblet, glimmer, handful, hint, mite, mouthful, nip, ounce, pittance, sprinkle, trace')]),
                              Word('slight', "",
                                   [TestWay('adj',
                                            '不重要的',
                                            'deficient in weight, importance',
                                            ["a slight comedy that did nothing to further her career 一个并没有帮助她事业发展的小喜剧"],
                                            'fiddling, frivolous, inconsequential, inconsiderable, insignificant, little, minor, minute, nugatory, trifling, trivial',
                                            'consequential, eventful, important, meaningful, momentous, significant, substantial, weighty'),
                                    TestWay('adj',
                                            '轻微的',
                                            'small in degree',
                                            ["only a slight chance of success 只有很小的成功概率", "If you have even the slightest doubt, then don't do it. 只要你有一点点疑惑, 那就不要去做了。"],
                                            'fragile, frail, negligible, outside, slim, small, tiny',
                                            'distinct'),
                                    TestWay('vt',
                                            '轻蔑, 看不起',
                                            'to treat with disdain or indifference',
                                            ["Those snobbish music critics slight any style of music that doesn't fit their personal taste. 那帮自命不凡的音乐评论家看不起所有不符合他们个人口味的音乐。"],
                                            'contemn, disdain, disrespect, snub, look down',
                                            'esteem, honor, respect, revere, venerate'),
                                    TestWay('vt',
                                            '忽略, 疏忽',
                                            'to fail to give proper attention to',
                                            ["She slighted several major authors in her survey of 20th-century fiction. 她在调查20世纪幻想文学时中忽略了几个重要的作家。"],
                                            'bypass, disregard, forget, ignore, overlook, overpass, slur',
                                            'attend, heed, mind')]),
                              Word('sling', "",
                                   [TestWay('vi',
                                            '投掷',
                                            'to send through the air especially with a quick forward motion of the arm',
                                            ["slinging stones at the checkpoint 朝着检查站扔石头"],
                                            'cast, chuck, dash, fire, fling, heave, hurl, hurtle, launch, lob, loft, pelt, pitch, toss',
                                            'catch')]),
                              Word('slippery', "",
                                   [TestWay('adj',
                                            '光滑的',
                                            'causing or tending to cause something to slide or fall',
                                            ["The road is slippery after rain, so drive cautiously. 雨后路滑, 谨慎驾驶。"],
                                            'greased, greasy, lubricated, oiled, slicked, slithery',
                                            'coarse, rough'),
                                    TestWay('adj',
                                            '隐秘的',
                                            "given to acting in secret and to concealing one's intentions",
                                            ["a bar where a lot of slippery characters were known to hang out 一个有许多秘密人物出没的酒吧"],
                                            'furtive, shady, shifty, sly, sneaking, stealthy',
                                            'aboveboard'),
                                    TestWay('adj',
                                            '意义不明确的',
                                            'not precise or fixed in meaning, elusive or tricky',
                                            ["a slippery concept that we had trouble understanding 一个难以理解的模糊概念"],
                                            'ambiguous, elusive, equivocal, evasive, fugitive, obscure, unintelligible, vague',
                                            'apparent, clear, distinct, evident, manifest, obvious, palpable, patent, plain, unambiguous, unequivocal')]),
                              Word('slipshod', "",
                                   [TestWay('adj',
                                            '粗心的, 随意的',
                                            'marked by carelessness or indifference to exactness, precision, and accuracy',
                                            ["a slipshod piece of research 一项随意的研究", "The hotel had always been run in a slipshod way. 酒店总是在以一种随意的状态运营。"],
                                            'botchy, careless, messy, slapdash, sloppy, slovenly, untidy',
                                            'fastidious, meticulous, accurate, exact, precise')]),
                              Word('sloppy', "",
                                   [TestWay('adj',
                                            '邋遢的, 不整洁的',
                                            'lacking neatness in dress or person',
                                            ["a sloppy child who always seems to have spilled something on his clothes 一个外表邋遢的小孩子, 他的衣服似乎总被沾上了什么东西"],
                                            'blowsy, dowdy, frowsy, slovenly, unkempt, untidy',
                                            'dapper, dashing, sharp, smart, spruce'),
                                    TestWay('adj',
                                            '混乱的',
                                            'lacking in order, neatness, and often cleanliness',
                                            ["dumped the papers in a sloppy pile on the desk 把纸张随意地叠放在书桌上"],
                                            'chaotic, disarranged, disarrayed, disheveled, disorderly, jumbled, littered, rumpled, tousled, tumbled',
                                            'bandbox, crisp, kempt, neat, orderly, organized, shipshape, snug, tidy, trim')]),
                              Word('sloth', "",
                                   [TestWay('n',
                                            '怠惰, 懒惰',
                                            'disinclination to action or labor: indolence',
                                            ["Sloth is the mother of poverty. 懒惰是贫穷的原因。"],
                                            'idleness, indolence, inertia, languor, laziness, lethargy, shiftlessness, sluggishness, torpor',
                                            'assiduity, diligence, industry',
                                            'slothful adj. 懒惰的')]),
                              Word('slouch', "",
                                   [TestWay('n',
                                            '懒人',
                                            'a lazy person',
                                            ["is no slouch when it comes to cooking 做起饭来可一点也不懒"],
                                            'deadbeat, drone, idler, loafer, slug, sluggard',
                                            'doer, hummer, hustler, rustler'),
                                    TestWay('vt',
                                            '缓慢行走',
                                            'to go or move slowly or reluctantly',
                                            ["He slouched towards the church as if going to his own funeral. 他缓缓地向教堂走去, 仿佛是要去参加自己的葬礼一般。"],
                                            'creep, drag, inch, limp, nose, ooze, plod, poke, snail',
                                            'fly, race, speed, whiz, zip')]),
                              Word('slovenly', "",
                                   [TestWay('adj',
                                            '邋遢的, 不整洁的',
                                            'lacking neatness in dress or person',
                                            ["For the sake of their image, the band members transformed themselves from clean-cut lads to slovenly rockers. 为了他们自身的形象, 乐队成员从健康向上的青年变成了邋遢的摇滚乐手。"],
                                            'blowsy, dowdy, frowsy, sloppy, unkempt, untidy',
                                            'dapper, dashing, neat, sharp, smart, spruce, trim')])])

list23_unit6 = VocabularyList([Word('sluggard', "",
                                   [TestWay('n',
                                            '懒人',
                                            'an habitually lazy person',
                                            ["The teacher tried to wake up the sluggards who were still sleeping at that late hour. 老师尝试去叫醒那些还在睡觉的懒鬼们。"],
                                            'deadbeat, drone, idler, loafer, slouch, slug',
                                            'doer, hummer, hustler, rustler')]),
                              Word('sluggish', "",
                                   [TestWay('adj',
                                            '缓慢的, 迟缓的',
                                            'markedly slow in movement, flow, or growth',
                                            ["The sluggish pace of the project is worrisome. 项目进展缓慢让人担忧。"],
                                            'crawling, creeping, dallying, dilatory, dragging, lagging, languid, leisurely, snaillike, tardy, unhurried',
                                            'bolting, brisk, fast, fleet, hasty, lightning, meteoric, quick, racing, rapid, rocketing, speedy, swift'),
                                    TestWay('adj',
                                            '迟钝的, 反应慢的',
                                            'slow to respond (as to stimulation or treatment)',
                                            ["Reptiles are naturally sluggish at low temperatures. 在低温下爬行动物的生理机能自然会趋于迟缓。"],
                                            'dull, indolent, inert, lethargic, quiescent, sleepy, torpid',
                                            'active, animated, bouncing, dynamic, energetic, kinetic, spirited, vigorous, vital, vivacious')]),
                              Word('slumber', "",
                                   [TestWay('vt',
                                            '睡着',
                                            'to be in a state of sleep',
                                            ["She slumbered for hours while the train rolled on. 她在火车行进过程中睡了四个小时。"],
                                            'catnap, doze, nap, rest, sleep, snooze',
                                            'arouse, awake, waken')]),
                              Word('slur', "",
                                   [TestWay('n',
                                            '耻辱',
                                            'a mark of guilt or disgrace',
                                            ["Your drunken behavior at the wedding has cast a slur on this family. 你在婚礼上醉酒后的行为给整个家族都带来了耻辱。"],
                                            'blot, brand, onus, smirch, smudge, spot, stigma, taint',
                                            'award, credit, glory, honor'),
                                    TestWay('vt',
                                            '含糊地发音',
                                            'to pronounce indistinctly',
                                            ["If you slur your words, the visa officer will have a hard time following you. 如果你说话含糊不清, 签证官就很难听懂你的话。"],
                                            'mumble, murmur,mutter',
                                            'articulate, enunciate'),
                                    TestWay('v',
                                            '疏忽, 忽略',
                                            'to slide or slip over without due mention, consideration, or emphasis',
                                            ["This documentary slurs over certain important facts as it offers a very biased case for a conspiracy theory. 这部纪录片忽略了许多重要的客观事实, 而只给出了带有偏见的阴谋论解释。"],
                                            'bypass, disregard, forget, ignore, overlook, overpass, slight',
                                            'attend, heed, mind')]),
                              Word('sly', "",
                                   [TestWay('adj',
                                            '狡猾的',
                                            'clever or cunning, especially in the practice of deceit.',
                                            ["The movie pairs a sly, dissembling ex-con with an upstanding, straight-arrow cop. 电影把一个狡猾、善于骗人的出狱犯和正直、坦率的警察搭配在了一起。"],
                                            'beguiling, cagey, crafty, cunning, designing, devious, foxy, guileful, scheming, shrewd, subtle, tricky, wily',
                                            'artless, guileless, ingenuous, innocent, undesigning'),
                                    TestWay('adj',
                                            '隐秘的, 偷偷的',
                                            "given to acting in secret and to concealing one's intentions",
                                            ["took a sly look at the letter on the table 偷偷地看了一眼桌上的信"],
                                            'furtive, shady, shifty, slippery, sneaking, stealthy',
                                            'aboveboard')]),
                              Word('smarmy', "",
                                   [TestWay('adj',
                                            '虚情假意的, 过分恭维的',
                                            'hypocritically, complacently, or effusively earnest',
                                            ["He is slightly smarmy and eager to impress. 他有点虚伪, 急于给人留下印象。"],
                                            'fulsome, oily, slick, soapy, unctuous',
                                            'artless, earnest, genuine, heartfelt, sincere, unaffected')]),
                              Word('smart', "",
                                   [TestWay('adj',
                                            '反应敏捷的, 聪颖的',
                                            'characterized by sharp quick thought',
                                            ["a smart child who could do well in school 一个能在学校取得良好成绩的聪明孩子"],
                                            'alert, brainy, bright, brilliant, clever, exceptional, fast, intelligent, keen, nimble, quick, sharp',
                                            'airheaded, brainless, doltish, dumb, fatuous, mindless, obtuse, senseless, simple, stupid, vacuous, witless'),
                                    TestWay('adj',
                                            '整洁的',
                                            'being strikingly neat and trim in style or appearance',
                                            ["Dressed in their smart new uniforms, the cadets proudly paraded around the grounds of the military school. 穿着整洁的制服, 军校的学员们骄傲地在训练场上游行。"],
                                            'dapper, natty, neat, sharp, snappy, spruce, trim',
                                            'disheveled, frowsy, sloppy, slovenly, unkempt'),
                                    TestWay('vi',
                                            '感到疼痛, 感到痛苦',
                                            'to suffer acutely, as from mental distress, wounded feelings, or remorse',
                                            ["The injection only smarted for a moment. 打针只会痛一小会儿。", "He is still smarting over criticism of his clumsy performance. 那些对他笨拙表演的批评仍然让他感到痛苦。"],
                                            'ache, hurt, pain, suffer',
                                            'allay, alleviate, assuage, ease, mitigate, mollify, palliate, relieve, soothe')]),
                              Word('smattering', "",
                                   [TestWay('n',
                                            '浅薄的知识',
                                            'superficialor piecemeal knowledge',
                                            antonyms = 'erudition, insight'),
                                    TestWay('n',
                                            '少量',
                                            'a small scattered number or amount',
                                            ["Only a smattering of spectators presented. 只有少数几个观看者出席了。"],
                                            'ace, bit,driblet, glimmer, handful, hint, mite, mouthful, nip, ounce, pittance,sprinkle, trace',
                                            'abundance,bundle, dozen, multiplicity, myriad, plentitude, profusion, scad, shipload, slew, volume, wealth')]),
                              Word('smirk', "",
                                   [TestWay('vi',
                                            '(自鸣得意地)笑',
                                            'to smile in an affected, often offensively self-satisfied manner',
                                            ["She tried not to smirk when they announced the winner. 当他们宣布她获得了胜利时, 她尽可能地保持不露出笑容。"],
                                            'grin, simper',
                                            'cry, weep, groan, moan, sigh')]),
                              Word('smother', "",
                                   [TestWay('vt',
                                            '使窒息',
                                            'to be or cause to be killed by lack of breathable air',
                                            ["Children should never be leftin cars alone because they could become trapped and smothered. 小孩子不应该被单独留在车中, 因为他们很容易因而被困并且窒息死亡。"],
                                            'asphyxiate, choke, smother, stifle, strangle, suffocate'),
                                    TestWay('vt',
                                            '抑制(表达、说出), 压制',
                                            'to refrain from openly showing or uttering',
                                            ["He quickly smothered his inappropriate laughter at the funeral ceremony. 他很快就控制住了自己在葬礼上不适当的笑声。", "Management smothered the true facts of the case. 管理层隐瞒了案件的真相。"],
                                            'bridle, check, choke, control, curb, muffle, quash, quell, repress, squelch, suppress',
                                            'unleash, vent (感情的)爆发, 宣泄; express')])])

list23_unit7 = VocabularyList([Word('smug', "",
                                   [TestWay('adj',
                                            '自大的, 自鸣得意的',
                                            'having too high an opinion of oneself',
                                            ["The winner was so smug that he lost the support of the crowd. 胜利者过于自大, 以至于失去了群众的支持。"],
                                            'complacent, egoistic, overweening, pompous, proud, self-satisfied, vain',
                                            'egoless, humble, modest'),
                                    TestWay('adj',
                                            '整洁的, 有序的',
                                            'being clean and in good order',
                                            ["The suburb's smug lawns and tree-lined streets bespeak a comfortable affluence. 郊区整齐有序的草坪和种满树木的街道, 代表着其间的舒适和财富。"],
                                            'dapper, kempt, orderly, shipshape, spruce, tidy, trim, uncluttered, well-groomed',
                                            'disheveled, disordered, messy, slovenly, unkempt, untidy')]),
                               Word('smuggling', "",
                                   [TestWay('n',
                                            '走私, 私运',
                                            'secret importation or exportation contrary to the law and especially without paying duties imposed by law',
                                            ["He was arrested for smuggling drugs into the country. 他因为向境内走私毒品而被逮捕。"],
                                            'bootlegging, contraband')]),
                              Word('snare', "",
                                   [TestWay('n',
                                            '无法逃脱的困境',
                                            'something that catches and holds',
                                            ["Someday you'll find that your lies are a snare from which you can't escape. 总有一天你会发现, 你所说过的谎话都会变成你无法逃脱的困境。", "caught in the snare of drug addiction 处于吸毒上瘾的困境之中"],
                                            'entanglement, mesh, morass, net, noose, quagmire, quicksand, toil, trap'),
                                    TestWay('vt',
                                            '捕捉',
                                            'to capture by or as if by use of a snare',
                                            ["They snared a rabbit earlier in the day. 今天的早些时候他们捕获了一只兔子。", "The car salesman successfully snared three potential customers. 汽车销售员成功地让三个潜在的客户上钩了。"],
                                            'catch, enmesh, ensnare, ensnarl, entrap, tangle',
                                            'disentangle, free, liberate')]),
                              Word('snarl', "",
                                   [TestWay('v',
                                            '纠缠, 纠结',
                                            'to twist together into a usually confused mass',
                                            ["You'll be awfully sorry if you snarl your fishing line. 要是你把渔网给缠在一起, 你肯定会非常后悔的。", "The new regulation has succeeded in nothing but snarling up rush-hour traffic throughout the city. 新的政策只将全城高峰时期的交通变得更为复杂难解。"],
                                            'entangle, ensnarl, interlace, intertwine, intertwist, interweave, knot, ravel, tangle',
                                            'disentangle, extricate, unravel, unsnarl, untwine, untwist'),
                                    TestWay('v',
                                            '咆哮, 怒吼',
                                            'to give vent to anger in surly language',
                                            ["She snarled at me after I kept badgering her with questions. 在我不断用问题骚扰她之后, 她终于忍不住爆发了。"],
                                            'bark, fulminate, rant, roar, scream, shout, storm, vent',
                                            'calm')]),
                              Word('sneer', "",
                                   [TestWay('vt',
                                            '(轻蔑地)嘲笑',
                                            'to speak in a scornful, contemptuous, or derisive manner',
                                            ["They would invariably sneer every time they passed the hapless nerds. 每次经过那个不幸的书呆子身边时, 他们总是会报以不变的嘲笑。"],
                                            'deride, gibe, laugh, jeer, jibe, mock, ridicule',
                                            'esteem, honor, respect, revere, venerate')]),
                              Word('snobbish', "",
                                   [TestWay('adj',
                                            '谄上傲下的, 自大的',
                                            'being or characteristic of a person who has an offensive air of superiority and tends to ignore or disdain anyone regarded as inferior',
                                            ["I expected her to be snobbish but she was warm and friendly. 我本以为她会是个自大的人, 结果她非常热心和友好。"],
                                            'aristocratic, bumptious, elitist, haughty, imperious, persnickety, pompous, presumptuous, supercilious',
                                            'egoless, humble, modest')]),
                              Word('snub', "",
                                   [TestWay('v',
                                            '轻视, 不理睬',
                                            'to treat with contempt or neglect',
                                            ["The snob in town always snubbed anyone she thought was beneath her. 镇上那个自命不凡的人总是对那些她认为不如她的人不屑一顾。"],
                                            'contemn, disdain, disrespect, slight, look down',
                                            'esteem, honor, respect, revere, venerate')]),
                              Word('soak', "",
                                   [TestWay('vt',
                                            '使…湿透',
                                            'to make thoroughly wet or saturated by or as if by placing in liquid',
                                            ["That downpour soaked my hair, and now I look like a sight. 那场大雨把我的头发淋湿了, 所以我现在看起来格外滑稽。", "We ran for home as soon as the rain started, but our clothes still ended up soaked. 我们一发觉下雨就开始往家里跑, 但我们的衣服还是湿透了。"],
                                            'douse, drench, drown, impregnate, macerate, saturate, sodden, sop, souse, steep',
                                            'dehydrate, dry, desiccate, parch, sear, scorch, wring')]),
                              Word('sober', "",
                                   [TestWay('adj',
                                            '严肃的',
                                            'marked by seriousness, gravity, or solemnity of conduct or character',
                                            ["She made a sober reply to what was only a teasing comment. 她很严肃地回复了那个恶搞的评论。", "Illness is a sober reminder of our mortality. 疾病是死亡给我们发出的严肃警告。"],
                                            'earnest, grave, humorless, sedate, severe, sober, solemn, staid, weighty',
                                            'facetious, flip, flippant, humorous, jesting, jocular, joking, playful'),
                                    TestWay('adj',
                                            '节制的',
                                            "given to or marked by restraint in the satisfaction of one's appetites",
                                            ["decided to live a sober life after bankruptcy 破产以后决定过有节制的生活"],
                                            'abstentious, abstinent, continent, self-denying, temperate',
                                            'hedonistic, licentious, self-indulgent, sensual, sybaritic, voluptuary'),
                                    TestWay('adj',
                                            '有理有据的',
                                            'based on sound reasoning or information',
                                            ["a sober assessment of the situation 关于局势有理有据的分析"],
                                            'firm, informed, justified, levelheaded, logical, rational, reasonable, sensible, solid, valid, well-founded',
                                            'groundless, illogical, invalid, unfounded, uninformed, unjustified, unreasonable, unsound')]),
                              Word('sodden', "",
                                   [TestWay('adj',
                                            '湿透的',
                                            'containing, covered with, or thoroughly penetrated by water',
                                            ["We stripped off our sodden clothes and wrung them dry. 我们脱下湿透了的衣服并将它们拧干。"],
                                            'awash, bathed, doused, drenched, logged, saturated, soaked, watered, waterlogged',
                                            'arid, dry'),
                                    TestWay('vt',
                                            '使…湿透',
                                            'to wet thoroughly with liquid',
                                            ["Soldiers' boots were soddened by endless hours in muddy trenches. 长时间身处泥泞的战壕使得士兵的靴子湿透了。"],
                                            'douse, drench, drown, impregnate, macerate, saturate, soak, sop, souse, steep',
                                            'dehydrate, dry, desiccate, parch, sear, scorch, wring')])])

list23_unit8 = VocabularyList([Word('solace', "",
                                   [TestWay('n',
                                            '安慰',
                                            'comfort in sorrow, misfortune, or distress',
                                            ["The kind words brought a little solace to the grieving widow. 这些同情的话语给痛苦的寡妇带来了些许安慰。"],
                                            'consolation, relief'),
                                    TestWay('vt',
                                            '安慰, 安抚',
                                            'to comfort, cheer, or console, as in trouble or sorrow',
                                            ["I did their my to solace those bereaved children. 我尽力去安抚那些失去双亲的孩子们。"],
                                            'cheer, comfort, console, soothe',
                                            'agonize, distress, harrow, torment, torture, trouble')]),
                              Word('solder', "",
                                   [TestWay('v',
                                            '连接, 联合',
                                            'to join or unite',
                                            ["Wires are soldered onto the circuit board. 电线被焊接在电路板上。", "The agreement soldered the factions into an alliance. 两个派系因这份协议而结成同盟。"],
                                            'associate, coalesce, combine, conjoin, conjugate, connect, couple, fuse, interfuse, join, link, marry, unify',
                                            'disassociate, disconnect, disjoin, divide, sever, split, sunder')]),
                              Word('solemnity', "",
                                   [TestWay('n',
                                            '严肃',
                                            'the quality or condition of being solemn',
                                            ["Solemnity is a trick of the body to hide the fault of the mind. 一本正经的态度, 是肉体为了掩饰精神上的缺陷而耍的花招。", "The coronation ceremony requires absolute solemnity. 加冕典礼需要绝对的庄严肃穆。"],
                                            'earnest, graveness, gravity, intentness, seriousness, sobriety, solemnness, staidness',
                                            'facetiousness, flightiness, flippancy, frivolity, frivolousness, levity, lightheartedness, play')]),
                              Word('solicitous', "",
                                   [TestWay('adj',
                                            '为他人操心的, 体谅他人的',
                                            'given to or made with heedful anticipation of the needs and happiness of others',
                                            ["The solicitous husband had already cleaned the house and cooked dinner by the time his wife returned home from work. 这个十分体谅妻子的好丈夫在他妻子回家之前就把家里清理干净, 还把晚餐都做好了。"],
                                            'attentive, considerate, kind',
                                            'heedless, inconsiderate, thoughtless, unthinking'),
                                    TestWay('adj',
                                            '迫切的, 渴望的',
                                            'showing urgent desire or interest',
                                            ["The family is solicitous to put this whole unfortunate affair behind them and to move on with their lives. 这个家庭迫切希望能忘记那些不幸的事情, 开始崭新的生活。"],
                                            'agog, anxious, ardent, avid, desirous, eager, enthusiastic, greedy, hungry, keen, thirsty, voracious, wild',
                                            'apathetic, indifferent, uneager, unenthusiastic',
                                            'solicitude n. 关切, 挂念')]),
                              Word('solid', "",
                                   [TestWay('adj',
                                            '固态的, 坚固的',
                                            'having a consistency that does not easily yield to pressure',
                                            ["The ice cream is too solid to scoop right now. 冰淇淋现在太硬了, 根本舀不动。"],
                                            'compact, hard, rigid, stiff, unyielding',
                                            'flabby, soft, spongy, squashy, squishy'),
                                    TestWay('adj',
                                            '有理有据的',
                                            'based on sound reasoning or information',
                                            ["the only solid conclusion that the jury could have reached 陪审团唯一可能做出的合理结论"],
                                            'firm, informed, justified, levelheaded, logical, rational, reasonable, sensible, sober, valid, well-founded',
                                            'groundless, illogical, invalid, unfounded, uninformed, unjustified, unreasonable, unsound'),
                                    TestWay('adj',
                                            '坚定的, 不迟疑的',
                                            'not showing weakness or uncertainty',
                                            ["Some people see a solid handshake as a sign of strong character. 有人认为握手毫不迟疑的人有着很强势的性格"],
                                            'forceful, hearty, iron, lusty, robust, stout, strong, sturdy, vigorous',
                                            'uncertain, weak',
                                            'solidify vt. 使固化')]),
                              Word('soliloquy', "",
                                   [TestWay('n',
                                            '(尤指自言自语的)独白',
                                            'a dramatic or literary form of discourse in which a character talks to himself or herself or reveals his or her thoughts without addressing a listener',
                                            ["A soliloquy always reveals the character’s thoughts and feeling. 一段独白经常反映出人物的思想和感情。"],
                                            'monologue',
                                            'chorus, ensemble')]),
                              Word('solitude', "",
                                   [TestWay('n',
                                            '孤独, 避世',
                                            'the quality or state of being alone or remote from society',
                                            ["He sought the kind of solitude where his thoughts would be his only companions. 他在寻找一种孤独感, 只有他的思想陪伴着他。", "She wished to work on her novel in solitude. 她想一个人安静地完成小说。"],
                                            'aloneness, insulation, privacy, seclusion, segregation, separateness, sequestration, solitariness',
                                            'camaraderie, companionship, company, comradeship, fellowship, society')]),
                              Word('solvent', "",
                                   [TestWay('adj',
                                            '有偿付能力的',
                                            'able to pay all legal debts',
                                            ["They're going to have to prove that the company is now solvent. 接下来他们必须要证明公司的偿贷能力。"],
                                            'bankrupt'),
                                    TestWay('n',
                                            '溶剂',
                                            'a substance in which another substance is dissolved, forming a solution',
                                            ["Some organic solvents, such as benzene, pyridine, furan, are poisonous to human’s reproductive system. 一些有机溶剂(比如苯、吡啶、呋喃)对人体的生殖系统有毒性。"],
                                            antonyms = 'solute')]),
                              Word('somatic', "",
                                   [TestWay('adj',
                                            '肉体的',
                                            'of the body, especially as distinguished from a body part, the mind, or the environment',
                                            ["a somatic disorder that was once thought to be “all in the patient’s head” 曾被认为“全是病人头脑中的问题”的生理机能紊乱"],
                                            'animal, bodily, carnal, corporal, corporeal, fleshly, material, physical',
                                            'mental, spiritual, nonmaterial, nonphysical')]),
                              Word('somber', "",
                                   [TestWay('adj',
                                            '昏暗的, 无光的',
                                            'so shaded as to be dark and gloomy',
                                            ["The prison's somber interrogation room has the desired effect of striking fear and despair into the prisoner. 牢房中阴暗的问讯间有着能让囚犯感到恐惧和绝望的效果。"],
                                            'black, caliginous, dark, dim, gloomy, lightless, murky, obscure, pitch-dark, rayless, stygian',
                                            'bright, brilliant, illuminated, lit, lightsome, lucent, lucid, luminous'),
                                    TestWay('adj',
                                            '悲伤的, 不愉快的',
                                            'causing or marked by an atmosphere lacking in cheer',
                                            ["Her death put us in a somber mood. 她的死让我们陷入了悲伤沮丧的情绪之中。"],
                                            'depressing, dire, dismal, funereal, lugubrious, melancholy, miserable, morbid, morose, saturnine, sullen',
                                            'cheerful, delighted, festive, gay, jocund, jovial')])])

list23_unit9 = VocabularyList([Word('somnolence', "",
                                   [TestWay('n',
                                            '瞌睡, 嗜睡',
                                            'the quality or state of desiring or needing sleep',
                                            ["Somnolence is likely to be the most typical reaction to this novel. 读这部小说最典型的感受就是想睡觉。"],
                                            'doziness, drowsiness',
                                            'insomnia, sleeplessness, wakefulness')]),
                              Word('sonnet', "",
                                   [TestWay('n',
                                            '十四行诗',
                                            'a 14-line verse form usually having one of several conventional rhyme schemes',
                                            ["a sonnet that celebrates love 一首歌颂爱情的十四行诗"],
                                            antonyms = 'doggerel')]),
                              Word('soothe', "",
                                   [TestWay('vt',
                                            '带来慰藉, 安慰',
                                            'to bring comfort, solace, or reassurance to',
                                            ["There seemed to be no words sufficient to soothethe widow. 任何话语好像都不足以安慰这个寡妇。"],
                                            'cheer, comfort, console, solace',
                                            'agonize, distress, harrow, torment, torture, trouble'),
                                    TestWay('vt',
                                            '使镇静, 使安心',
                                            'to free from distress or disturbance',
                                            ["He took her in his arms and soothed her. 他把她抱在怀中以让她镇静下来。"],
                                            'becalm, compose, lull, lullaby, quiet, quieten, salve, settle, still, tranquilize',
                                            'agitate, discompose, disquiet, disturb, perturb, upset, vex'),
                                    TestWay('vt',
                                            'agitate, discompose, disquiet, disturb, perturb, upset, ve',
                                            'to make more bearable or less severe',
                                            ["Hot tea with honey will soothe a sore throat. 加了蜂蜜的热茶可以缓解喉咙的酸痛。"],
                                            'abate, allay, alleviate, assuage, ease, mitigate, mollify, palliate, relieve, soften',
                                            'aggravate, exacerbate, intensify')]),
                              Word('sop', "",
                                   [TestWay('n',
                                            '安慰物',
                                            'something yielded to placate or soothe',
                                            ["to provide with the salary raise as a sop 提高工资作为安慰"],
                                            'balm, emollient, placebo,salve, unguent',
                                            'irritant, stimulant'),
                                    TestWay('n',
                                            '贿赂, 回扣',
                                            "something given or promised in order to improperly influence a person's conduct or decision",
                                            ["As a sop to the teachers' union for supporting his reelection campaign, the mayor promised to push for the abolition of the residency requirement. 市长答应推动废除获得绿卡的限制条件, 以此作为换取选举中教师联盟支持的条件。"],
                                            synonyms = 'backhander, boodle, cumshaw, fix'),
                                    TestWay('vt',
                                            '浸湿, 湿透',
                                            'to wet thoroughly',
                                            ["My book fell in the swimming pool and was thoroughly sopped before I could fish it out. 我的书掉进了游泳池, 在我把它捞出来之前已经彻底湿透了。"],
                                            'douse, drench, drown, impregnate, macerate, saturate, soak, sodden, souse, steep',
                                            'dehydrate, dry, desiccate, parch, sear, scorch, wring')]),
                              Word('sophism', "",
                                   [TestWay('n',
                                            '假推理, 诡辩',
                                            'deceptive or fallacious argumentation',
                                            ["Political selection is more dependent on sophism and less on economic literacy. 政治选举更多的是依靠诡辩, 而非简练的文笔。"],
                                            'sophistry')]),
                              Word('sophisticated', "",
                                   [TestWay('adj',
                                            '精明的, 老于世故的',
                                            'having acquired worldly knowledge or refinement; lacking natural simplicity or naiveté',
                                            ["On the train I met a surprisingly sophisticated and widely traveled child. 在火车上我见到了一个老练得让人惊讶的、见多识广的孩子。"],
                                            'cosmopolitan, debonair, knowing, smart, suave, urbane, worldly',
                                            'guileless, ingenuous, innocent, naïve'),
                                    TestWay('adj',
                                            '复杂的',
                                            'very complex or complicated',
                                            ["a very sophisticated machine that is a marvel of modern design 一个十分复杂的机器, 是现代设计的最高成就"],
                                            'baroque, byzantine, complicated, convoluted, elaborate, intricate, involved, knotty, labyrinthine, tangled',
                                            'plain, simple',
                                            'sophistication n. 精明; 复杂')]),
                              Word('soporific', "",
                                   [TestWay('n',
                                            '安眠药',
                                            'a drug or other substance that induces sleep',
                                            ["Alcohol is a poor hypnotic because it disturbs sleep patterns, and so can worsen sleep disorders. 酒精是一种欠佳的安眠药, 因为它会干扰睡眠的固定模式, 从而恶化睡眠紊乱的情况。"],
                                            'hypnotic',
                                            'stimulant'),
                                    TestWay('adj',
                                            '催眠的',
                                            'causing or tending to cause sleep',
                                            ["This medication is soporific, so do not drive after taking it. 这种药物是催眠的, 服用之后切忌开车。", "the soporific heat of summer 夏日里催人欲睡的阳光"],
                                            'narcotic, opiate, slumberous, somniferous, somnolent',
                                            'arousing, waking, invigorating, stimulating'),
                                    TestWay('adj',
                                            '慵懒的, 困倦的',
                                            'of, relating to, or marked by sleepiness or lethargy',
                                            ["A big lunch always makes me soporific in the afternoon. 中午一顿大餐总是让我下午感到困倦。"],
                                            'dozy, drowsy, sleepy',
                                            'awake, conscious, wakeful, alert, sleepless, insomniac')]),
                              Word('sordid', "",
                                   [TestWay('adj',
                                            '肮脏的, 不干净的',
                                            'not clean',
                                            ["I will not let my children grow up in such a sordid environment. 我绝不会让我的孩子在这样一个肮脏的环境之中成长。"],
                                            'besmirched, dirty, dusty, filthy, foul, grubby, muddy, nasty, smudged, soiled, stained, sullied, unclean',
                                            'clean, immaculate, spotless, stainless, unsoiled, unstained, unsullied'),
                                    TestWay('adj',
                                            '卑鄙的',
                                            'marked by baseness or grossness',
                                            ["Behind his generous donation were sordid motives. 在他慷慨捐资的背后有着卑鄙的动机。"],
                                            'base, contemptible, despicable, detestable, dishonorable, execrable, ignominious, mean, vile, wretched',
                                            'honorable, lofty, noble, straight, upright, venerable, virtuous')]),
                              Word('sound', "",
                                   [TestWay('adj',
                                            '牢固的, 不可动摇的',
                                            'marked by the ability to withstand stress without structural damage or distortion',
                                            ["The bridge is structurally sound. 这座大桥在结构上是稳固的。"],
                                            'bombproof, fast, firm, stalwart, strong, sturdy',
                                            'ramshackle, rickety, unstable, unsteady'),
                                    TestWay('adj',
                                            '健康的, 强壮的',
                                            'free from injury or disease: exhibiting normal health',
                                            ["The horse is getting old, but still perfectly sound. 虽然在变老, 但这匹马依然相当健康。"],
                                            'bouncing, fit, hale, healthy, hearty, robust, well, well-conditioned, wholesome',
                                            'ailing, diseased, ill, sick, decrepit, enfeebled, feeble, infirm'),
                                    TestWay('adj',
                                            '(逻辑上)严谨的',
                                            'based on valid reasoning',
                                            ["Sound reasoning alone should tell you that the result is invalid. 从纯粹严谨的逻辑演绎出发, 这个结论是不正确的"],
                                            'analytic, coherent, consequent, rational, reasonable, sensible, valid, well-founded, well-grounded',
                                            'illegitimate, illogical, incoherent, inconsequent, invalid, irrational, unreasonable, unsound, weak',
                                            'soundness n. (逻辑上的)无疵')]),
                              Word('sparse', "",
                                   [TestWay('adj',
                                            '稀疏的, 稀少的',
                                            'less plentiful than what is normal, necessary, or desirable',
                                            ["Many slopes are rock fields with sparse vegetation. 许多山坡都是不长植物的石坡。"],
                                            'exiguous, meager, niggardly, poor, scant, scanty, scarce, skimpy, slender, slim, sparing, stingy',
                                            'abundant, ample, bountiful, copious, generous, liberal, plenteous, plentiful')])])

list23_unit10 = VocabularyList([Word('spartan', "",
                                   [TestWay('adj',
                                            '简朴的, 节约的',
                                            'marked by simplicity, frugality, or avoidance of luxury and comfort',
                                            ["Accommodations on the windjammer are spartan but clean and comfortable nevertheless. 帆船上的装饰十分朴素, 但还是很干净和舒适。"],
                                            'austere, plain, simple, stark',
                                            'deluxe, luxurious, plush')]),
                              Word('spat', "",
                                   [TestWay('n',
                                            '(小的)争吵',
                                            'a brief petty quarrel or angry outburst',
                                            ["Like any couple, they have their spats. 像其他夫妻一样, 他们也会有争执。", "They were typical sisters, spatting one minute, playing together the next. 她们是典型的姐妹: 上一分钟还在吵架, 下一分钟又玩在一起了。"],
                                            'altercation, controversy, disagreement, dispute, imbroglio, quarrel, squabble, tiff, wrangle',
                                            'amity, concord, harmony, rapport, rapprochement')]),
                              Word('spate', "",
                                   [TestWay('n',
                                            '突发的洪水',
                                            'sudden flood',
                                            synonyms = 'bath, deluge, flood, inundation, overflow, torrent',
                                            antonyms = 'drought'),
                                    TestWay('n',
                                            '大量',
                                            'a large number or amount',
                                            ["a spate of books about GRE 很多关于GRE 的书"],
                                            'abundance,bundle, dozen, multiplicity, myriad, plentitude, profusion, scad, shipload, slew, volume, wealth',
                                            'ace, bit, driblet, glimmer, handful, hint, mite, mouthful, nip, ounce, pittance, sprinkle, trace')]),
                              Word('specific', "",
                                   [TestWay('adj',
                                            '特有的, 独特的',
                                            'of a particular or exact sort',
                                            ["We need a specific type of pen to sign the diplomas. 我们需要一种特制的笔来签署学位证书。"],
                                            'concrete, distinct, especial, peculiar, precise, special, unique',
                                            'general, generic, universal'),
                                    TestWay('adj',
                                            '明确的',
                                            'so clearly expressed as to leave no doubt about the meaning',
                                            ["specific instructions regarding the interrogation of prisoners 有关如何审问犯人的明确指示"],
                                            'clear, definite, definitive, explicit, express, unambiguous, unequivocal, univocal',
                                            'ambiguous, equivocal, implicit, indefinite, inexplicit, unspecific, vague')]),
                              Word('specious', "",
                                   [TestWay('adj',
                                            '似是而非的, 欺骗性的',
                                            'having a false look of truth or genuineness',
                                            ["a specious argument that really does not stand up under close examination 一段经不起仔细推敲的论证"],
                                            'beguiling, deceitful, deceiving, deluding, delusive, delusory, fallacious, false, misleading',
                                            'aboveboard, forthright, straightforward')]),
                              Word('speck', "",
                                   [TestWay('n',
                                            '小点, 少量',
                                            'a very small amount: bit',
                                            ["She writes without even a speck of humor. 她字里行间一点幽默感也没有。"],
                                            'ace, bit, driblet, glimmer, handful, hint, mite, mouthful, nip, ounce, pittance, sprinkle, trace',
                                            'abundance,bundle, dozen, multiplicity, myriad, plentitude, profusion, scad, shipload, slew, volume, wealth')]),
                              Word('spectator', "",
                                   [TestWay('n',
                                            '观众, 目击者, 旁观者',
                                            'one who looks on or watches',
                                            ["join the organization as temporary spectator 作为短期观察员加入该组织", "The accident attracted a large crowd of spectators. 事故引来了大量的围观群众。"],
                                            'bystander, observer, onlooker, viewer, watcher',
                                            'actor, performer, player')]),
                              Word('spectrum', "",
                                   [TestWay('n',
                                            '范围, 系列',
                                            'a broad sequence or range of related qualities, ideas, or activities',
                                            ["the whole spectrum of 20th-century thought 20 世纪所有不同的思潮", "A political spectrum is a way of modeling different political positions by placing them upon one or more geometric axes symbolizing independent political dimensions. 所谓的政治光谱是一种将不同的政治立场可视化的模型, 它通过一根或者多根几何坐标轴来定位不同的政治态度。"],
                                            'diapason, gamut, scale, spread, stretch')]),
                              Word('speculate', "",
                                   [TestWay('vt',
                                            '推测, 揣测',
                                            'to take to be true on the basis of insufficient evidence',
                                            ["I speculate that someone has been using this cabin as a trysting place. 我猜测有情侣把这个小屋当做他们幽会的地方"],
                                            'assume, conjecture, daresay, imagine, presume, speculate, suppose, surmise, suspect',
                                            'prove, substantiate, validate'),
                                    TestWay('vt',
                                            '投机倒卖',
                                            'to buy or sell in expectation of profiting from market fluctuations',
                                            ["speculating on the oil market 在石油市场上投机倒卖"])]),
                              Word('spendthrift', "",
                                   [TestWay('n',
                                            '挥霍者, 败家子',
                                            'a person who spends improvidently or wastefully',
                                            ["The spendthrift managed to blow all of his inheritance in a single year. 这个败家子只用了一年就把自己继承的遗产挥霍一空。"],
                                            'fritterer, profligate, spender, squanderer, waster, wastrel',
                                            'economizer, penny-pincher, hoarder, miser, niggard'),
                                    TestWay('adj',
                                            '挥霍的, 不节俭的',
                                            'given to spending money freely or foolishly',
                                            ["Spendthrift consumers amassed a mountain of debt on their credit cards. 那些爱挥霍财富的消费者们在他们的信用卡上累积了一大笔债务。"],
                                            'extravagant, improvident, squandering, thriftless, unthrifty, wasteful',
                                            'conserving, economical, frugal, penny-pinching, provident, scrimping, skimping, thrifty')])])

LIST23 = VocabularyList(list23_unit1.words+list23_unit2.words+list23_unit3.words+list23_unit4.words+list23_unit5.words+list23_unit6.words+list23_unit7.words+list23_unit8.words+list23_unit9.words+list23_unit10.words)