#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list8_unit1 = VocabularyList([Word('doff', "",
                                   [TestWay('vt',
                                            '脱下',
                                            'to take off; remove',
                                            ["The blazing sun soon had the men doffing their jackets. 炙热的太阳很快就让男人们脱掉了夹克。"],
                                            ['put off', 'take off'],
                                            ['don', 'put on'])]),
                              Word('dogged', "",
                                   [TestWay('adj',
                                            '坚持的，坚决的',
                                            "continuing despite difficulties, opposition, or discouragement；showing no signs of slackening or yielding in one's purpose",
                                            ["gain respect through sheer dogged determination 凭借单纯的坚决赢得了尊重", "A madman who spent his life in dogged pursuit of power 一个一生都坚持追求权力的疯子"],
                                            ['insistent', 'persevering', 'pertinacious', 'tenacious', 'determined'],
                                            ['easily discouraged', 'yielded']),
                                    TestWay('adj',
                                            '固执的，任性的',
                                            'sticking to an opinion, purpose, or course of action in spite of reason, arguments, or persuasion',
                                            ["Your dogged adherence to a really lame argument is embarrassing. 你固执的坚持一个站不住脚的观点令人很尴尬。"],
                                            ['adamant', 'hardheaded', 'headstrong', 'inflexible', 'intransigent', 'mulish', 'obdurate' 'opinionated', 'ossified', 'pertinacious', 'self-opinionated', 'self-willed stubborn', 'unbending', 'uncompromising', 'unrelenting', 'unyielding', 'willful'],
                                            ['acquiescent', 'amenable', 'compliant', 'complying', 'flexible', 'pliable', 'pliant', 'relenting', 'yielding'])]),
                              Word('dogma', "",
                                   [TestWay('n',
                                            '教条，信条',
                                            'a doctrine or body of doctrines concerning faith or morals formally stated and authoritatively proclaimed by a church',
                                            ["People are beginning to question the old dogmas. 人们开始质疑旧的信条。", "The newspaper seeks to be independent of political dogma. 这份报纸力求不受政治信条影响。"],
                                            ['credo', 'doctrine', 'gospel'],
                                            ['heresy', 'heterodoxy'],
                                            'dogmatic 独断的，武断的： characterized by an authoritative, arrogant assertion of unproved principles 【例】a dogmatic critic 独断的评论家 【近】dictatorial, dictative, authoritarian, authoritative, magisterial')]),
                              Word('doldrums', "",
                                   [TestWay('n',
                                            '低迷，中断',
                                            'a state or period of inactivity, stagnation, or slump',
                                            ["August is a time of doldrums for many enterprises. 对于许多企业来说八月是一个低迷期", "The economy is in the doldrums. 经济低迷"],
                                            ['abeyance', 'dormancy', 'latency', 'quiescence', 'moratorium'],
                                            ['continuation']),
                                    TestWay('n',
                                            '情绪不佳',
                                            'a state or spell of low spirits',
                                            ["The team had been in the doldrums ever since losing the championship. 整个队伍自从输了锦标赛以来一直情绪不佳"],
                                            ['dejection', 'depression', 'desolation', 'despondence', 'dolefulness', 'gloom', 'melancholy', 'unhappiness'],
                                            ['bliss', 'ecstasy', 'elation', 'exhilaration', 'exuberance', 'exultation', 'jubilation', 'rapture', 'felicity'])]),
                              Word('dolorous', "",
                                   [TestWay('adj',
                                            '忧伤的',
                                            'causing, marked by, or expressing misery or grief',
                                            ["He lifted a pair of sapphire, dolorous eyes. 他抬起了一双忧郁的蓝宝石般的眼睛"],
                                            ['agonized', 'bemoaning', 'bewailing', 'deplorable', 'grievous', 'miserable', 'plaintive', 'rueful', 'sorrowful', 'woeful'],
                                            ['happy', 'joyful', 'jovial', 'jubilant'])]),
                              Word('dolt', "",
                                   [TestWay('n',
                                            '笨蛋',
                                            'a stupid person',
                                            ["What a dolt I have been! 我是多么的愚蠢啊！"],
                                            ['idiot', 'fool', 'moron', 'simpleton', 'dullard'],
                                            ['illuminati', 'intellectual'],
                                            'doltish adj. 愚笨的')]),
                              Word('domicile', "",
                                   [TestWay('n',
                                            '住所，住宅',
                                            'a residence; a home',
                                            ["an alternate domicile in emergency 紧急情况下的住所"],
                                            ['home', 'dwelling', 'habitation', 'abode', 'house', 'lodging']),
                                    TestWay('v',
                                            '提供住处',
                                            'to establish in or provide with a domicile',
                                            ["The university domiciles students in a variety of buildings in and around its urban campus. 大学在校园周围为学生提供了多样化的宿舍"],
                                            ['accommodate', 'bestow lodge', 'harbor', 'put up'],
                                            ['banish', 'expel'])]),
                              Word('dominant', "",
                                   [TestWay('adj',
                                            '起支配地位的',
                                            'commanding, controlling, or prevailing over all others',
                                            ["the dominant culture 主流文化"],
                                            ['ascendant', 'leading', 'outweighing', 'paramount', 'prevalent', 'principal', 'supreme'],
                                            ['subordinate']),
                                    TestWay('adj',
                                            '（基因）显性的',
                                            'of, relating to, or exerting ecological or genetic dominance',
                                            antonyms = ['recessive'],
                                            other_form = 'dominate v. 占主导地位，统治; dominance n. 主导, 主流; （基因的）显性')]),
                              Word('don', "",
                                   [TestWay('vt',
                                            '穿上',
                                            'to put on (an article of clothing)',
                                            ["donned a raincoat for his trip 为出行穿上雨衣"],
                                            ['assume', 'wear', 'put on'],
                                            ['doff'])]),
                              Word('donor', "",
                                   [TestWay('n',
                                            '捐赠人',
                                            'one that gives, donates, or presents something',
                                            ["donors of funds to research foundations 研究基金的捐赠人"],
                                            ['donator', 'presenter', 'contributor', 'subscriber', 'patron', 'sugar daddy'],
                                            ['acceptor'])])])

list8_unit2 = VocabularyList([Word('doodle', "",
                                   [TestWay('vi',
                                            '（无目的地）乱画',
                                            'to scribble aimlessly, especially when preoccupied',
                                            ["I often doodle when I'm on the phone. 打电话时我经常乱写乱画"],
                                            ['mess around']),
                                    TestWay('vi',
                                            '漫无目的地打发时光',
                                            'to spend time in aimless activity',
                                            ["I plan to spend the entire vacation just doodling. 我打算整个假期就随便做点事打发时间"],
                                            ['dawdle', 'trifle'])]),
                              Word('dormant', "",
                                   [TestWay('adj',
                                            '静止的，不活跃的',
                                            'in a state of rest or inactivity; inoperative; in abeyance',
                                            ["volcanoes which have been dormant for thousand years 休眠了上千年的火山"],
                                            ['dead', 'latent', 'lurking', 'abeyant', 'quiescent', 'inert'],
                                            ['active', 'busy', 'operating']),
                                    TestWay('adj',
                                            '（动物）冬眠的',
                                            'having biological activity suspended',
                                            ["The bears lay dormant in their den during the winter. 在冬季，熊在他们的穴里冬眠"],
                                            ['asleep', 'resting', 'napping', 'slumbering'],
                                            ['awake'],
                                            'dormancy n. 不活跃；冬眠')]),
                              Word('dour', "",
                                   [TestWay('adj',
                                            '闷闷不乐的,死气沉沉的',
                                            'sullen, gloomy',
                                            ["The captain’s dour look depressed us all. 船长闷闷不乐的脸色使我们倍感低落"],
                                            ['morose', 'sulky', 'surly', 'moody'],
                                            ['gay']),
                                    TestWay('adj',
                                            '严厉的',
                                            'harsh and threatening in manner or appearance',
                                            ["His dour criticism made us regret having undertaken the job. 他严厉的批评让我们后悔接下这活儿了"],
                                            ['strict', 'sharp', 'austere', 'exacting', 'fierce', 'gruff', 'intimidating', 'rough', 'stark', 'stern'],
                                            ['benign', 'gentle', 'mild', 'tender'])]),
                              Word('douse', "",
                                   [TestWay('vt',
                                            '熄灭',
                                            'to put out (a light or fire)',
                                            ["douse a fire with water 用水熄灭火焰"],
                                            ['quench', 'extinguish', 'put out'],
                                            ['kindle', 'ignite', 'inflame']),
                                    TestWay('n',
                                            '弄湿',
                                            'to make wet',
                                            ["The heavy rains thoroughly doused the tourists. 大雨把游客淋得透湿"],
                                            ['bathe', 'drench', 'soak', 'sodden', 'sop'],
                                            ['dehydrate', 'desiccate', 'parch', 'scorch', 'sear'])]),
                              Word('downplay', "",
                                   [TestWay('vt',
                                            '轻描淡写，不予重视',
                                            'to minimize the significance of, play down',
                                            ["downplay the bad news 对坏消息轻描淡写"],
                                            ['de-emphasize', 'disregard', 'ignore', 'overlook', 'neglect', 'understate', 'play down'],
                                            ['address', 'emphasize', 'underscore'])]),
                              Word('downpour', "",
                                   [TestWay('n',
                                            '倾盆大雨',
                                            'a heavy fall of rain',
                                            ["power failure due to the downpour 暴雨导致的电力中断"],
                                            ['deluge', 'downfall', 'cloudburst', 'rainstorm'],
                                            ['drizzle', 'sprinkle'])]),
                              Word('doyen', "",
                                   [TestWay('n',
                                            '有经验的人，资深人士',
                                            'a person considered to be knowledgeable or uniquely skilled as a result of long experience in some field of endeavor',
                                            ["a doyen in the industry 业界的元老"],
                                            ['authority', 'expert', 'master', 'maven', 'veteran', 'virtuoso'],
                                            ['amateur', 'layman', 'tyro', 'novice', 'neophyte', 'rookie', 'fledgling']),
                                    TestWay('n',
                                            '（加入时间较长的）高级会员',
                                            'the senior member of a group',
                                            ["He's the doyen of the admission committee, and his opinion has considerable weight. 他是招生委员会里的老人了，所以他的话往往格外有分量"],
                                            ['elder', 'senior'],
                                            ['junior'])]),
                              Word('doze', "",
                                   [TestWay('vi./n',
                                            '小憩',
                                            'to sleep lightly or briefly',
                                            ["He dozed off during the lecture. 他在讲座上睡着了"],
                                            ['drowse', 'nap', 'wink', 'slumber'],
                                            ['wake'])]),
                              Word('draconian', "",
                                   [TestWay('adj',
                                            '极其残酷的; 十分严厉的',
                                            'exceedingly harsh; very severe',
                                            ["abolish a draconian legal code 废除一部严酷的法典"],
                                            ['rigid', 'ironhanded', 'strict', 'stringent'],
                                            ['mild', 'genial', 'lenient'])]),
                              Word('drawl', "",
                                   [TestWay('v',
                                            '慢吞吞地说',
                                            'to speak slowly with vowels greatly prolonged',
                                            ["The old woman was drawling on and on. 老太太慢吞吞地说个没完"],
                                            ['extend', 'lengthen', 'prolong', 'protract', 'draw out'],
                                            ['drivel', 'gibber'])])])

list8_unit3 = VocabularyList([Word('dreary', "",
                                   [TestWay('adj',
                                            '单调乏味的',
                                            'having nothing likely to provide cheer, comfort, or interest',
                                            ["The day is cold, rainy, and dreary. 天气寒冷，阴暗而沉闷"],
                                            ['desolate', 'gloomy', 'sullen', 'dull', 'monotone', 'pedestrian', 'somber'],
                                            ['jocund']),
                                    TestWay('adj',
                                            '令人不悦的',
                                            'causing unhappiness',
                                            ["decided to see a professional counselor in order to save their dreary marriage 决定咨询专业人士以拯救他们悲剧式的婚姻"],
                                            ['depressing', 'dismal', 'heartbreaking', 'mournful', 'pathetic', 'melancholy'],
                                            ['cheering'],
                                            'drearily adv. 令人厌烦地')]),
                              Word('drench', "",
                                   [TestWay('vt',
                                            '湿透，浸透',
                                            'to wet thoroughly',
                                            ["The thunderstorm drenched us to the skin. 雷雨把我们浇了个透"],
                                            ['deluge', 'douse', 'soak', 'saturate', 'sodden', 'sop', 'wet'],
                                            ['dehydrate', 'desiccate', 'dry', 'parch', 'scorch', 'sear'])]),
                              Word('drivel', "",
                                   [TestWay('n',
                                            '胡言乱语',
                                            'unintelligible or meaningless talk',
                                            ["My roommate talks in her sleep, but it's just drivel. 我的室友会说梦话，但都是些没有意义的呓语"],
                                            ['abracadabra', 'nonsense', 'prattle', 'gabble', 'prattle']),
                                    TestWay('v',
                                            '胡言乱语，说傻话',
                                            'to talk stupidly and carelessly',
                                            ["He always drivel on about his “distinguished” family. 他总是痴痴地说着他所谓的“名门”出身"],
                                            ['babble', 'gabble', 'gibber', 'jabber'])]),
                              Word('drizzle', "",
                                   [TestWay('vi./n',
                                            '（下）细小、轻柔、似雾的雨，毛毛雨',
                                            'a fine misty rain',
                                            ["The intermittent drizzle was just heavy enough to spoil all of our outdoor activities. 断断续续的小雨恰好大岛让我们所有的户外活动都泡汤"],
                                            ['mist', 'sprinkle'],
                                            ['deluge', 'downpour'],
                                            'drizzling adj. （雨）细小的')]),
                              Word('droll', "",
                                   [TestWay('adj',
                                            '古怪有趣的，离奇可笑的',
                                            'amusingly odd or whimsically comical',
                                            ["a droll man with a strong dialect 带着浓郁口音的有意思的人"],
                                            ['antic', 'comic', 'farcical', 'funny', 'hilarious', 'laughable', 'humorous', 'ridiculous', 'ludicrous', 'uproarious', 'whimsical'],
                                            ['lame', 'unamusing', 'uncomic', 'unfunny', 'unhumorous', 'unhysterical'],
                                            'drollness n. 古怪')]),
                              Word('drone', "",
                                   [TestWay('vt',
                                            '单调地说',
                                            'to talk in a persistently dull or monotonous tone',
                                            ["droning bees 嗡嗡作响的蜜蜂"],
                                            ['hum', 'buzz', 'bumble']),
                                    TestWay('n',
                                            '（昆虫振翅般）单调的声音',
                                            'a monotonous sound like that of an insect in motion',
                                            ["heard the drone of an helicopter overhead 听到了头顶直升机单调的声音"],
                                            ['burr', 'whir']),
                                    TestWay('v',
                                            '混日子',
                                            'to spend time doing nothing',
                                            ["Instead of getting a job, he preferred to drone and live off his parents. 相对于找个工作来说，他更喜欢什么也不做，依靠他的父母过日子"],
                                            ['dally', 'dawdle', 'hang', 'laze', 'loll', 'lounge'])]),
                              Word('drudgery', "",
                                   [TestWay('n',
                                            '苦工; 单调、卑贱或无趣的工作',
                                            'tedious, menial, or unpleasant work',
                                            ["get away from the drudgery of their everyday lives 摆脱每日的单调无聊"],
                                            ['labor', 'slavery', 'toil', 'travail', 'grind'],
                                            ['sinecure', 'fun', 'play'])]),
                              Word('dubious', "",
                                   [TestWay('adj',
                                            '充满不定性的，值得怀疑的',
                                            'giving rise to uncertainty; questionable or suspect as to true nature or quality',
                                            ["a dubious assertion 一个值得怀疑的论调"],
                                            ['debatable', 'doubtful', 'disputable', 'equivocal', 'problematic', 'questionable', 'shaky'],
                                            ['certain', 'incontestable', 'undeniable', 'reliable']),
                                    TestWay('adj',
                                            '（对事实等）持怀疑态度的',
                                            'not feeling sure about the truth, wisdom, or trustworthiness of someone or something',
                                            ["dubious about a diet that claims I can eat all I want and still lose weight 对于一份声称可以一边随心所欲地吃和一边减肥的节食方案表示怀疑"],
                                            ['distrustful', 'skeptical', 'suspicious', 'unsure'],
                                            ['convinced', 'positive', 'sure']),
                                    TestWay('adj',
                                            '迟疑不决的，不愿行动的',
                                            'slow to begin or proceed with a course of action because of doubts or uncertainty',
                                            ["I'm dubious about our plan to go hang gliding without having had any training. 我对于不做任何训练就去玩滑翔感到很迟疑"],
                                            ['undecided', 'disinclined', 'loath', 'reluctant', 'reticent'],
                                            ['disposed', 'inclined'],
                                            'dubiety n. 可疑，怀疑')]),
                              Word('ductile', "",
                                   [TestWay('adj',
                                            '可塑的，有延展性的',
                                            'easily molded or shaped, malleable',
                                            ["Gold is a kind of ductile metal. 金是一种有延展性的金属"],
                                            ['malleable', 'moldable'],
                                            ['inflexible']),
                                    TestWay('adj',
                                            '易受影响的',
                                            'easily led or influenced',
                                            ["a ductile personality 易受他人影响的性格"],
                                            ['pliant', 'yielding', 'supple'],
                                            ['adamant', 'intractable', 'refractory', 'obdurate'])]),
                              Word('dulcet', "",
                                   [TestWay('adj',
                                            '悦耳的，令人愉悦的',
                                            'pleasing to the ear; melodious; generally pleasing or agreeable',
                                            ["dulcet tones from harps and flutes 竖琴和长笛发出的悦耳音调"],
                                            ['sweet', 'agreeable', 'delightful', 'euphonic', 'mellifluous', 'tuneful', 'winsome'],
                                            ['cacophonous', 'grating'])])])

list8_unit4 = VocabularyList([Word('dullard', "",
                                   [TestWay('n',
                                            '笨蛋',
                                            'a stupid or unimaginative person',
                                            synonyms = ['moron', 'simpleton', 'idiot', 'fool'],
                                            antonyms = ['wit', 'genius'],
                                            other_form = 'dull adj. 愚笨的')]),
                              Word('dupe', "",
                                   [TestWay('n',
                                            '复制品，复刻',
                                            'something that is made to look exactly like something else',
                                            ["He built a dupe of the original model, which is locked in a vault. 他做了个保险柜里模型的复刻品"],
                                            ['clone', 'duplicate', 'facsimile', 'imitation', 'mock', 'replica'],
                                            ['archetype', 'original', 'prototype']),
                                    TestWay('n',
                                            '易受骗的人',
                                            'one that is easily deceived or cheated',
                                            ["The swindler was able to escape with all of the dupe's money. 骗子成功带着受骗人的财产逃跑了"],
                                            ['fool', 'victim', 'gull'],
                                            ['connoisseur']),
                                    TestWay('vt',
                                            '欺骗',
                                            'to deceive (an unwary person)',
                                            ["The public is easily duped by extravagant claims in advertising. 大众极易被广告中夸大的介绍误导"],
                                            ['bamboozle', 'beguile', 'cheat', 'cozen', 'delude', 'gull', 'hoax', 'hoodwink'],
                                            other_form = 'dupable adj. 易受骗的')]),
                              Word('duplicity', "",
                                   [TestWay('n',
                                            '欺骗，口是心非',
                                            'deliberate deceptiveness in behavior or speech',
                                            ["accidentally reveal their duplicity 不经意间暴露了他们的口是心非"],
                                            ['artifice', 'deceit', 'craft', 'cunning', 'fraudulence', 'guile'],
                                            ['honesty', 'artlessness', 'forthrightness', 'guilelessness', 'ingenuousness', 'sincerity'])]),
                              Word('dwindle', "",
                                   [TestWay('vi',
                                            '逐渐减少',
                                            'to become gradually less until little remains',
                                            ["His vast fortune is dwindling away. 他的巨额财富正慢慢缩水"],
                                            ['abate', 'decrease', 'drop', 'diminish', 'reduce', 'shrink', 'taper', 'wane', 'knock down'],
                                            ['aggrandize', 'balloon', 'burgeon', 'increase', 'accumulate'],
                                            'dwindling adj. 减少的')]),
                              Word('dyspeptic', "",
                                   [TestWay('adj',
                                            '脾气坏的',
                                            'bad-tempered',
                                            ["The sultry day makes us dyspeptic. 闷热潮湿的天气让我们变得脾气暴躁"],
                                            ['cantankerous', 'disagreeable', 'irritable', 'fretful', 'irascible', 'peevish', 'splenetic', 'surly'],
                                            ['amiable', 'easygoing', 'genial', 'good-humored', 'good-natured', 'good-tempered']),
                                    TestWay('adj',
                                            '消化不良的',
                                            'pertaining to, subject to, or suffering from dyspepsia',
                                            other_form = 'dyspepsia n. 消化不良')]),
                              Word('earnest', "",
                                   [TestWay('adj',
                                            '严肃认真的',
                                            'characterized by or proceeding from an intense and serious state of mind, grave',
                                            ["an earnest machine operator 一丝不苟的机器操作员"],
                                            ['grave', 'serious', 'solemn', 'staid', 'sober'],
                                            ['facetious', 'frivolous', 'flip', 'flippant', 'playful'])]),
                              Word('earshot', "",
                                   [TestWay('n',
                                            '听力所及的范围',
                                            "the range within which one may hear a person's unaided voice",
                                            ["wait until he was out of earshot 等到他听不见的时候"],
                                            ['hail', 'hearing', 'sound'])]),
                              Word('earsplitting', "",
                                   [TestWay('adj',
                                            '震耳欲聋的',
                                            'distressingly loud or shrill',
                                            ["earsplitting noise of airplane engines 飞机引擎的巨大噪音"],
                                            ['blaring', 'blasting', 'deafening', 'loud', 'piercing', 'plangent', 'resounding', 'roaring', 'stentorian', 'thunderous'],
                                            ['gentle', 'soft'])]),
                              Word('eavesdrop', "",
                                   [TestWay('v',
                                            '偷听',
                                            'to listen secretly to the private conversation of others',
                                            ["eavesdropping on the conversation 偷听谈话"],
                                            ['overhear', 'wiretap'])]),
                              Word('ebullient', "",
                                   [TestWay('adj',
                                            '热情奔放的',
                                            'zestfully enthusiastic',
                                            ["The ebullient dancers left an enduring impression on us. 热情洋溢的舞者给我们留下了难以磨灭的印象"],
                                            ['boiling', 'exuberant', 'effervescent', 'vivacious', 'brash'],
                                            ['tepid', 'torpid'],
                                            'ebullience n. 热情洋溢')])])

list8_unit5 = VocabularyList([Word('eccentric', "",
                                   [TestWay('adj',
                                            '行为出格的，不循规蹈矩的',
                                            'deviating from conventional or accepted usage or conduct',
                                            ["an eccentric millionaire 行为怪异的百万富翁"],
                                            ['strange', 'bizarre', 'erratic', 'idiosyncratic', 'odd', 'offbeat', 'outlandish', 'quaint', 'weird'],
                                            ['ordinary', 'regular'],
                                            other_form = 'eccentricity n. 离心率; 古怪')]),
                              Word('éclat', "",
                                   [TestWay('n',
                                            '辉煌成就',
                                            'brilliant or conspicuous success',
                                            ["The premier of Mozart’s Le Nozze di Figaro enjoyed a great éclat in 1786. 莫扎特歌剧《费加罗的婚礼》于1786年的首演获得了极大的成功"],
                                            ['fame', 'renown', 'brilliance', 'triumph'],
                                            ['debacle', 'fiasco'])]),
                              Word('eclipse', "",
                                   [TestWay('n',
                                            '下降，衰退',
                                            'a change to a lower state or level',
                                            ["the eclipse of the town from a grand seaside resort to a tacky tourist trap 从壮丽辉煌的海边旅游圣地退化成了俗气的坑人景点"],
                                            ['decadence', 'degeneration', 'degradation', 'deterioration', 'ebb', 'fall'],
                                            ['ascent', 'rise', 'upswing']),
                                    TestWay('vt',
                                            '使声望下降，使黯然失色',
                                            'to obscure or diminish in importance, fame, or reputation',
                                            ["Her score eclipsed the old record. 她的分数使旧的纪录黯然失色"],
                                            ['adumbrate', 'obscure', 'overshadow']),
                                    TestWay('vt',
                                            '（在数量、品质上）超越',
                                            'to be greater, better, or stronger than',
                                            ["The brilliant young pianist now eclipsed even his own mentor in musical artistry. 极富天赋的小钢琴家如今甚至已超越了他的音乐导师"],
                                            ['beat', 'exceed', 'excel', 'outshine', 'outstrip', 'surpass', 'transcend'],
                                            ['fall behind'])]),
                              Word('ecstasy', "",
                                   [TestWay('n',
                                            '无法自控的情绪',
                                            'a state of being beyond reason and self-control',
                                            ["an ecstasy of rage 无法自控的愤怒"],
                                            ['mania', 'rhapsody'],
                                            ['self-control', 'composure', 'sangfroid']),
                                    TestWay('n',
                                            '狂喜',
                                            'intense joy or delight',
                                            ["be in ecstasy over the offer from Harvard University 因被哈佛的录取而欣喜如狂"],
                                            ['delight', 'elation', 'euphoria', 'exhilaration', 'rapture', 'transport'],
                                            ['depression', 'melancholy'])]),
                              Word('ecumenical', "",
                                   [TestWay('adj',
                                            '全球基督教会的',
                                            'of, relating to, or representing the whole of a body of churches',
                                            synonyms = ['catholic'],
                                            antonyms = ['diocesan']),
                                    TestWay('adj',
                                            '世界范围的，普遍性的',
                                            'worldwide or general in extent, influence, or application',
                                            ["an ecumenical scope 国际视野"],
                                            ['universal', 'cosmopolitan', 'global', 'planetary', 'worldwide'],
                                            ['provincial', 'insular'])]),
                              Word('edible', "",
                                   [TestWay('adj',
                                            '可食用的',
                                            'fit to be eaten',
                                            ["No chemicals in the laboratory is edible. 实验室中的任何化学试剂都不能食用"],
                                            ['eatable', 'comestible', 'consumable', 'digestible', 'esculent'],
                                            ['inedible'],
                                            'edibility n. 可食用')]),
                              Word('edifice', "",
                                   [TestWay('n',
                                            '大厦;大建筑物',
                                            'a large or massive structure',
                                            ["The Capitol is one of the most impressive edifices in the United States. 国会山是美国最令人印象深刻的建筑之一"],
                                            ['building', 'erection', 'palace'],
                                            ['cottage']),
                                    TestWay('n',
                                            '基础，基本构架',
                                            'the arrangement of parts that gives something its basic form',
                                            ["The edifice of the argument is quite simple, once you get past the fancy language. 只要你看透了表面花哨的语言，你会发现这段论证的基本构架是非常简单的"],
                                            ['architecture', 'configuration', 'framework', 'skeleton', 'structure'])]),
                              Word('efface', "",
                                   [TestWay('vt',
                                            '擦掉，抹去;使不明显',
                                            'to eliminate or make indistinct by or as if by wearing away a surface',
                                            ["efface those unpleasant memories 抹去那些不快的记忆"],
                                            ['eradicate', 'erase', 'expunge', 'exterminate', 'extirpate', 'liquidate', 'eclipse', 'obliterate', 'wipe', 'root out'],
                                            ['blazon', 'decorate', 'emboss'],
                                            'self-effacing adj. 谦卑、低调的')]),
                              Word('effervesce', "",
                                   [TestWay('vi',
                                            '冒泡',
                                            'to bubble, hiss, and foam as gas escapes',
                                            ["effervescing with bubbles 冒气泡"],
                                            ['bubble', 'foam', 'froth']),
                                    TestWay('vt',
                                            '兴奋，热情洋溢',
                                            'to show high spirits or animation',
                                            ["effervescing over the news of victory 因胜利的消息而兴奋"],
                                            ['rejoice', 'exult', 'jubilate', 'triumph'],
                                            ['grieve'],
                                            'effervescent adj. 热【】【】‘’情洋溢的;effervescence n. 热情洋溢')]),
                              Word('effete', "",
                                   [TestWay('adj',
                                            '衰弱的',
                                            'depleted of vitality, force, or effectiveness',
                                            ["an effete monarchy 奄奄一息的君主制"],
                                            ['consumed', 'debilitated', 'decadent', 'degenerate', 'depleted', 'drained', 'exhausted', 'feeble'],
                                            ['hale', 'sound', 'robust']),
                                    TestWay('adj',
                                            '缺乏信念的，懦弱的',
                                            '',
                                            ["The government is too effete to take out the powerful special interests that really ruin this state. 政府过于懦弱，不敢去摧毁那些祸害这个国家的特殊利益集团"],
                                            ['frail', 'invertebrate', 'nerveless', 'spineless'],
                                            ['backboned', 'firm', 'hard', 'strong', 'tough'],
                                            'effetely adv. 衰弱地')])])

list8_unit6 = VocabularyList([Word('effluvium', "",
                                   [TestWay('n',
                                            '难闻的气味',
                                            'an offensive exhalation or smell',
                                            ["Repulsive effluvia made us vomit. 这恶臭让我们作呕"],
                                            ['malodor', 'stink', 'stench'],
                                            ['fragrance', 'aroma']),
                                    TestWay('n',
                                            '没用的副产品，废品',
                                            'a by-product especially in the form of waste',
                                            ["With nothing but effluvia obtained, researchers decided to abandon this method. 由于得不到目标产物，研究者们决定放弃这种手段"],
                                            ['dross', 'refuse', 'rubbish', 'trash', 'waste'],
                                            other_form = 'effluvial adj. 恶臭的')]),
                              Word('effrontery', "",
                                   [TestWay('n',
                                            '厚颜无耻，放肆大胆',
                                            'flagrant disregard of courtesy or propriety and an arrogant assumption of privilege',
                                            ["had the effrontery to insult her father 胆敢辱骂她的父亲"],
                                            ['audacity', 'brashness', 'brazenness', 'insolence', 'nerve', 'presumption', 'temerity'],
                                            ['decorum', 'propriety', 'courtesy', 'grace', 'timidity'])]),
                              Word('effulgent', "",
                                   [TestWay('adj',
                                            '光辉灿烂的',
                                            'shining brilliantly; resplendent',
                                            ["an effulgent sunset on the Atlantic 大西洋上壮丽辉煌的日落"],
                                            ['bright', 'beaming', 'glorious', 'luminous', 'radiant', 'splendid'],
                                            ['dim', 'murky', 'dull'],
                                            'effulgence n. 光辉')]),
                              Word('effusive', "",
                                   [TestWay('adj',
                                            '感情泛滥溢于言表的;感情表达不节制和过度的;过分多情的',
                                            'unrestrained or excessive in emotional expression',
                                            ["The principal delivered an effusive address at the commencement ceremony. 校长在毕业典礼上做了充满感情的演讲"],
                                            ['emotional', 'expansive', 'demonstrative', 'gushy', 'passionate'],
                                            ['inhibited', 'reserved', 'restrained', 'undemonstrative', 'unemotional', 'numb', 'torpid'],
                                            'effusion n. 流出，溢出')]),
                              Word('egalitarian', "",
                                   [TestWay('adj',
                                            '平等主义的',
                                            ' affirming, promoting, or characterized by belief in equal political, economic, social, and civil rights for all people',
                                            ["the egalitarian principle guiding his endeavor 引导他奋斗的平等主义原则"],
                                            ['disinterested', 'impartial', 'unprejudiced', 'unbiased', 'objective'],
                                            ['inequitable', 'discriminating', 'unfair'],
                                            'egalitarianism n. 平等主义')]),
                              Word('egoistic', "",
                                   [TestWay('adj',
                                            '利己的，以自我为中心的',
                                            "being centered in or preoccupied with oneself and the gratification of one's own desires",
                                            ["egoisticbehaviorsothersdetest 令他人厌恶的利己行为"],
                                            ['egocentric', 'self-centered', 'individualistic', 'navel-gazing'],
                                            ['altruistic', 'selfless'],
                                            'ego n. 自大，自我;egoism n. 利己主义;egoist n. 以自我为中心的人')]),
                              Word('elaborate', "",
                                   [TestWay('adj',
                                            '详细的，复杂的',
                                            'marked by complexity, fullness of detail, or ornament',
                                            ["an elaborate manual 内容详尽的使用手册"],
                                            ['circumstantial', 'complex', 'complicated', 'intricate', 'knotty', 'minute', 'particular', 'particularized', 'sophisticated'],
                                            ['sketchy', 'brief', 'compendious', 'summary']),
                                    TestWay('vt',
                                            '详细阐述',
                                            'to expand something in detail',
                                            [" The defense committee asked the PhD candidate to elaborate one critical assumption in his thesis. 答辩委员会要求答辩的博士进一步说明他毕业论文中的一个关键假设"],
                                            ['develop', 'expand', 'amplify', 'explain'],
                                            ['abstract', 'abbreviate', 'condense', 'simplify', 'downplay', 'ignore', 'neglect', 'overlook'])]),
                              Word('elastic', "",
                                   [TestWay('adj',
                                            '有弹性的',
                                            'easily resuming original shape after being stretched or expanded',
                                            ["elastic rubber band 弹性橡胶圈"],
                                            ['bouncy', 'flexible', 'malleable', 'resilient', 'stretchable', 'supple'],
                                            ['rigid', 'stiff']),
                                    TestWay('adj',
                                            '能(迅速从伤痛中)恢复的',
                                            'capable of recovering quickly especially from depression or disappointment',
                                            ["owe her success to an elastic optimistic nature 将她的成功归因于能迅速走出悲伤的乐观品质"],
                                            ['adaptable', 'adjustable', 'buoyant', 'pliable', 'volatile'],
                                            ['established', 'fixed', 'immutable'],
                                            'inelastic adj. 无弹性的，非弹性的')]),
                              Word('elate', "",
                                   [TestWay('v',
                                            '使开心，使自豪',
                                            'to fill with joy or pride',
                                            ["The phenomenal sales record elated him.卓越的业绩让他高兴不已"],
                                            ['cheer', 'excite', 'exhilarate', 'inspire', 'stimulate'],
                                            ['depress', 'dishearten', 'sadden'],
                                            'elated adj. 高兴的;elation n. 高兴')]),
                              Word('eleemosynary', "",
                                   [TestWay('adj',
                                            '慈善的',
                                            'of, relating to, or supported by charity',
                                            ["an eleemosynary foundation funded by the Bill Gates 由比尔·盖茨夫妇资助的慈善基金"],
                                            ['benevolent', 'charitable', 'humane', 'humanitarian', 'philanthropic'],
                                            ['parsimonious'])])])

list8_unit7 = VocabularyList([Word('elegy', "",
                                   [TestWay('n',
                                            '哀歌(诗)，挽歌(诗)',
                                            'a song or poem expressing sorrow or lamentation',
                                            ["an moving elegy played at the funeral 葬礼上演奏的催人泪下的挽歌"],
                                            ['dirge', 'lamentation', 'requiem'],
                                            ['ode', '颂歌'])]),
                              Word('elephantine', "",
                                   [TestWay('adj',
                                            '巨大的',
                                            'having enormous size or strength',
                                            ["an elephantine meteor crate 巨大的陨石坑"],
                                            ['huge', 'colossal', 'enormous', 'gargantuan', 'gigantic', 'massive', 'prodigious', 'tremendous'],
                                            ['microscopic', 'minute', 'tiny', 'infinitesimal']),
                                    TestWay('adj',
                                            '笨拙的',
                                            'clumsy, ponderous',
                                            ["elephantine movements 笨拙的行动"],
                                            ['awkward', 'graceless', 'maladroit'],
                                            ['graceful'])]),
                              Word('elevate', "",
                                   [TestWay('vt',
                                            '道德、智力、文化水平的 升',
                                            'to improve morally, intellectually, or culturally',
                                            ["a novel that both entertains and elevates readers 一本寓教于乐的小说"],
                                            ['advance', 'boost', 'enhance', 'ennoble', 'raise', 'upgrade'],
                                            ['abase', 'debase', 'demote', 'degrade']),
                                    TestWay('vt',
                                            '使兴奋',
                                            'to raise the spirits of',
                                            ["one of the most elevating moments in their lives 生命中最让人兴奋的时刻之一"],
                                            ['elate', 'enrapture', 'exhilarate', 'intoxicate', 'transport'],
                                            ['depress'],
                                            'elevation n. 提升;喜悦')]),
                              Word('elicit', "",
                                   [TestWay('vt',
                                            '激起，唤起',
                                            'to draw forth or bring out',
                                            ["The king’s speech elicited lasting cheer and applause. 国王的演讲激起了持续的欢呼和掌声"],
                                            ['arouse', 'evoke', 'excite', 'inspire', 'provoke', 'raise'],
                                            ['appease', 'placate', 'mollify', 'pacify'])]),
                              Word('elliptical', "",
                                   [TestWay('adj',
                                            '含糊不清的',
                                            'of or relating to deliberate obscurity (as of literary or conversational style)',
                                            ["give an elliptical response to the inquiry 就问题给出一个含糊其辞的回答"],
                                            ['ambiguous', 'arcane', 'cryptic', 'enigmatic', 'equivocal', 'inscrutable', 'murky', 'nebulous', 'occult', 'opaque', 'vague'],
                                            ['clear', 'explicit', 'unambiguous', 'unequivocal']),
                                    TestWay('adj',
                                            '椭圆的',
                                            'of, relating to, or shaped like an ellipse',
                                            synonyms = ['oval', 'ovate'],
                                            antonyms = ['circular', 'round'])]),
                              Word('elucidate', "",
                                   [TestWay('v',
                                            '阐明',
                                            'to make lucid especially by explanation or analysis',
                                            ["elucidate an abstruse equation in quantum mechanics 阐明一个深奥难懂的量子力学方程"],
                                            ['clarify', 'clear', 'construe', 'explain', 'explicate', 'expound', 'illustrate'],
                                            ['confuse', 'obfuscate', 'obscure', 'garble'],
                                            'elucidation n. 阐释，阐明')]),
                              Word('emaciate', "",
                                   [TestWay('vt',
                                            '使变瘦',
                                            'to cause to lose flesh so as to become very thin',
                                            ["become emaciated by long illness 因长年累月的病痛而消瘦"],
                                            antonyms = ['fatten']),
                                    TestWay('vt',
                                            '使虚弱',
                                            'to make feeble',
                                            ["His hesitation emaciated the force of his argument. 他的迟疑削弱了他论证的力度"],
                                            ['droop', 'flag', 'sag', 'decay', 'enfeeble', 'enervate', 'languish', 'wane', 'wither'],
                                            ['invigorate'])]),
                              Word('emancipate', "",
                                   [TestWay('v',
                                            '解放，解除束缚',
                                            'to free from bondage, oppression, or restraint',
                                            ["emancipate students from excessive assignments 将学生从题海中解放出来"],
                                            ['discharge', 'enfranchise', 'free', 'liberate', 'loose', 'manumit', 'release'],
                                            ['bind', 'shackle', 'enslave', 'enthrall'],
                                            'emancipation n. 解放，获得自由')]),
                              Word('embargo', "",
                                   [TestWay('n',
                                            '贸易禁止令',
                                            'a legal prohibition on commerce',
                                            ['a trade embargo on luxuries 对奢侈品的禁运令'],
                                            ['ban', 'interdiction', 'proscription', 'sanction', 'veto'],
                                            ['approval', 'license', 'permission', 'prescription'])]),
                              Word('embark', "",
                                   [TestWay('vi',
                                            '上船',
                                            'to go aboard a vessel or aircraft, as at the start of a journey',
                                            ["With all cargos embarked, the ship weighed the anchor. 所有货物都上船了，货船拔锚起航"],
                                            ['board'],
                                            ['disembark']),
                                    TestWay('vi',
                                            '开始从事',
                                            'to make a start',
                                            ["embark on a world tour 开始了环游世界的旅程"],
                                            ['begin', 'commence', 'launch', 'initiate', 'start'],
                                            ['conclude', 'end', 'finish', 'terminate'])])])

list8_unit8 = VocabularyList([Word('embarrass', "",
                                   [TestWay('vt',
                                            '使尴尬',
                                            'to cause to experience a state of self-conscious distress',
                                            ["bawdy jokes that embarrassed her 让她尴尬的荤段子"],
                                            ['abash', 'discomfit', 'disconcert', 'faze', 'fluster', 'mortify', 'nonplus']),
                                    TestWay('vt',
                                            '阻挠，制造障碍',
                                            'to create difficulty for the work or activity of',
                                            ["A lot of this paperwork is unnecessary and just embarrasses the organization. 这些文案工作很多都是多余的，只会妨碍组织的工作"],
                                            ['encumber', 'handicap', 'hinder', 'impede', 'inhibit', 'obstruct', 'shackle', 'stymie', 'trammel'],
                                            ['aid', 'facilitate'],
                                            'embarrassing adj. 令人窘迫的;embarrassment n. 尴尬')]),
                              Word('embeds', "",
                                   [TestWay('vt',
                                            '嵌入',
                                            'to enclose closely in or as if in a matrix',
                                            ["The thorn was embedded in her thumb. 刺扎入了她的拇指"],
                                            ['entrench', 'fix', 'ingrain', 'root'],
                                            ['extract', 'dislodge', 'uproot'],
                                            'embedded adj. 嵌入式的')]),
                              Word('embezzle', "",
                                   [TestWay('vt',
                                            '盗用',
                                            "to appropriate (as property entrusted to one's care) fraudulently to one's own use",
                                            ["limitations on the right of the state to embezzle private property 限制政府挪用私人财产的权利"],
                                            ['appropriate', 'peculate'],
                                            ['confiscate'],
                                            'embezzlement n. 挪用，盗用')]),
                              Word('embolden', "",
                                   [TestWay('v',
                                            '鼓励，使大胆',
                                            'to instill with boldness or courage',
                                            ["be emboldened by the wine 借酒壮胆"],
                                            ['encourage', 'animate', 'cheer', 'hearten', 'strengthen'],
                                            ['daunt', 'discourage', 'dishearten', 'dispirit'])]),
                              Word('emboss', "",
                                   [TestWay('vt',
                                            '以浮雕效果妆点，装饰',
                                            'to raise the surface of into bosses; especially to ornament with raised work',
                                            ["embossed with a design of Shanghai skyline 刻有上海城市轮廓的浮雕图案"],
                                            ['adorn', 'beautify', 'bedeck', 'blazon', 'ornament', 'garnish'],
                                            ['flatten', 'efface' ])]),
                              Word('embrace', "",
                                   [TestWay('vt',
                                            '乐于接受',
                                            'to take up willingly or eagerly',
                                            ["embrace the opportunity to study further 乐于接受继续深造的机会"],
                                            ['accept', 'adopt', 'espouse', 'welcome'],
                                            ['abjure', 'abrogate', 'renounce', 'spurn']),
                                    TestWay('vt',
                                            '包围',
                                            'to surround or cover closely',
                                            ["The stone walls that embrace the monastery serve to symbolize its function as a retreat from an unquiet world. 包围着修道院的石墙是它远离喧嚣尘世的象征"],
                                            ['circle', 'encompass', 'envelop', 'wrap'])]),
                              Word('embroider', "",
                                   [TestWay('v',
                                            '(时常伴有夸张和想象内容)详细说明',
                                            ' to give an elaborate account of, often with florid language and fictitious details',
                                            ["embroider the story of his adventures in the army 细说他服役时惊险的经历"],
                                            ['elaborate', 'embellish', 'exaggerate', 'magnify', 'overstate', 'hyperbolize'],
                                            ['downplay', 'de-emphasize'])]),
                              Word('emigrate', "",
                                   [TestWay('vi',
                                            '移民，移居海外',
                                            "to leave one's place of residence or country to live elsewhere",
                                            ["have to emigrate to the United States due to political persecution 不得不因政治迫害而移民美国"],
                                            ['migrate'],
                                            ['immigrate', 'repatriate'],
                                            'emigrant n. (向外的)移民;emigration n. (向外)迁徙')]),
                              Word('eminent', "",
                                   [TestWay('adj',
                                            '杰出的',
                                            'exhibiting eminence especially in standing above others in some quality or position',
                                            ["an eminent young scientist 一名杰出的青年科学家"],
                                            ['famous', 'celebrated', 'distinguished', 'famed', 'notable', 'prominent', 'renowned'],
                                            ['mediocre', 'undistinguished'],
                                            'eminence n. 杰出，显赫')]),
                              Word('emollient', "",
                                   [TestWay('adj',
                                            '起缓和作用的',
                                            'making less intense or harsh',
                                            ["soothe us in our grieves with emollient words 用安慰的话语抚平我们的悲伤"],
                                            ['appeasing', 'assuaging', 'mollifying', 'mitigating', 'relieving'],
                                            ['aggravating', 'intensifying'])])])

list8_unit9 = VocabularyList([Word('emulate', "",
                                   [TestWay('vt',
                                            '仿效并努力超越',
                                            'to strive to equal or excel, especially through imitation',
                                            ["a role model worthy emulating 值得效仿的榜样"],
                                            ['copy', 'imitate', 'mimic', 'mime'],
                                            other_form = 'emulation n. 模仿')]),
                              Word('enact', "",
                                   [TestWay('vt',
                                            '制定颁布法律',
                                            'to establish by legal and authoritative act',
                                            ["Congress enacted the tax reform bill. 国会颁布了税法改革案"],
                                            ['constitute', 'establish', 'legislate', 'pass', 'ratify', 'ordain', 'lay down'],
                                            ['abolish', 'repeal', 'rescind', 'revoke'],
                                            'enactment n. 颁布')]),
                              Word('enamel', "",
                                   [TestWay('v',
                                            '涂亮漆;使具有光滑或亮泽的表面',
                                            'to give a glossy or brilliant surface to',
                                            synonyms = ['glaze', 'varnish'],
                                            antonyms = ['efface']),
                                    TestWay('v',
                                            '用亮丽的表面装饰',
                                            'to adorn with a brightly colored surface',
                                            synonyms = ['adorn', 'beautify', 'bedeck', 'decorate', 'embellish', 'garnish', 'ornament'],
                                            antonyms = ['disfigure'])]),
                              Word('encomium', "",
                                   [TestWay('n',
                                            '赞颂之词',
                                            'glowing and warmly enthusiastic praise',
                                            ["received encomiums from literary critics 受到文学评论家的好评"],
                                            ['accolade', 'applause', 'compliment', 'eulogy', 'laud', 'panegyric', 'salutation', 'tribute'],
                                            ['criticism', 'abuse', 'invective', 'vituperation'])]),
                              Word('encompass', "",
                                   [TestWay('v',
                                            '组成，包含',
                                            'to constitute or include',
                                            ["a plan that encompasses multiple aims 一项包含了多个目标的计划"],
                                            ['contain', 'comprehend', 'embody', 'entail', 'involve', 'subsume'],
                                            ['exclude']),
                                    TestWay('v',
                                            '包围',
                                            'envelop',
                                            ["Berlin had already been encompassed by the Red Army and all Soviet soldiers were patiently waiting for the order to put a final nail in Nazi Germany’s coffin.  柏林已被红军包围，苏联士兵们静静地等待着最后的命令，彻底消灭纳粹德国"],
                                            ['circle', 'embrace', 'enclose', 'environ', 'surround'])]),
                              Word('encumber', "",
                                   [TestWay('v',
                                            '阻碍;妨碍',
                                            'to impede or hamper the function or activity of',
                                            ["Negotiation between the two parties were encumbered by a lack of trust 两党间的谈判因缺乏信任而受到阻碍"],
                                            ['hamper', 'hinder', 'impede', 'obstruct', 'retard', 'stymie'],
                                            ['promote', 'further', 'aid', 'assist', 'facilitate', 'help']),
                                    TestWay('v',
                                            '增添负担',
                                            'to place a weight or burden on',
                                            ["Don't encumber your pack animal so much that it can hardly move. 别让你的牲畜驮这么多东西，它都走不动了"],
                                            ['burden', 'laden', 'lumber', 'saddle'],
                                            ['unload'])]),
                              Word('endemic', "",
                                   [TestWay('adj',
                                            '地方性的',
                                            'prevalent in or peculiar to a particular locality, region, or people',
                                            ["an endemic disease 地方性疾病"],
                                            ['aboriginal', 'indigenous', 'native', 'domestic'],
                                            ['exotic', 'foreign', 'nonindigenous', 'nonnative'])]),
                              Word('endorse', "",
                                   [TestWay('vt',
                                            '公开支持，推崇',
                                            'to express support or approval of publicly and definitely',
                                            ["endorse a presidential candidate 公开支持一名总统候选人"],
                                            ['advocate', 'back', 'approve', 'certify', 'champion', 'sanction', 'support', 'uphold'],
                                            ['deprecate', 'impugn', 'oppose'],
                                            'endorsement n. 支持;补充条款')]),
                              Word('enervate', "",
                                   [TestWay('vt',
                                            '使衰弱',
                                            'to weaken or destroy the strength or vitality of',
                                            ["His constitution was enervated by lustful lifestyle. 他荒淫无度的生活习惯已使他身体虚弱"],
                                            ['debilitate', 'disable', 'enfeeble', 'fatigue', 'sap'],
                                            ['fortify', 'strengthen', 'energize', 'invigorate', 'vitalize']),
                                    TestWay('vt',
                                            '使麻木',
                                            'to deprive of emotional or intellectual vitality',
                                            ["A lifetime of working in dreary jobs had enervated his very soul. 一生忙于无聊的工作让他变得无比麻木"],
                                            ['dampen', 'deaden', 'petrify'],
                                            ['brace', 'energize', 'enliven', 'invigorate', 'vitalize', 'vivify'],
                                            'enervation n. 虚弱')]),
                              Word('enfranchise', "",
                                   [TestWay('vt',
                                            '给予权利(例如选举权)',
                                            'to endow with the rights of citizenship, especially the right to vote',
                                            ["Slaves in US were emancipated in 1863 but were not enfranchised until the Fifteenth Amendment went into effect in 1870. 尽管在美国奴隶于1863年就获得了解放，但他们直到1870年《第五修正案》正式生效才获得选举权"],
                                            antonyms = ['disenfranchise', 'disempowe']),
                                    TestWay('vt',
                                            '解放',
                                            'to set free (as from slavery)',
                                            [" In a way, modern labor-saving appliances enfranchised people, giving them much more leisure time. 从某种意义上来说，那些节省劳动力的现代设备将人们解放出来，给予更多的休闲时间"],
                                            ['discharge', 'emancipate', 'free', 'liberate', 'manumit', 'rescue', 'unfetter'],
                                            ['bind', 'confine', 'enfetter', 'subjugate', 'subdue', 'enthrall'])])])

list8_unit10 = VocabularyList([Word('engender', "",
                                   [TestWay('vt',
                                            '引起，使发展',
                                            'to cause to exist or to develop',
                                            ["Her latest book has engendered a lot of controversy. 她的新书引发了很多争议"],
                                            ['beget', 'cause', 'catalyze', 'generate', 'induce', 'invoke', 'produce', 'spawn']),
                                    TestWay('vt',
                                            '产生，出现',
                                            'to come into existence',
                                            ["Feelings of confidence and independence that were only just beginning to engender within her. 她的自信和独立的感觉才刚刚产生"],
                                            ['actualize', 'appear', 'arise', 'form', 'materialize', 'spring'],
                                            ['cease', 'disappear', 'perish', 'eradicate', 'quash', 'terminate'])]),
                              Word('engross', "",
                                   [TestWay('vt',
                                            '使全神贯注',
                                            'to occupy exclusively',
                                            ["was completely engrossed in his work 全神贯注于他的工作之中"],
                                            ['absorb', 'engage', 'enthrall', 'fascinate', 'grip', 'immerse'],
                                            other_form = 'engrossed adj. 全神贯注的')]),
                              Word('enigma', "",
                                   [TestWay('n',
                                            '难以理解或解释的事物，谜',
                                            'something hard to understand or explain',
                                            ["The smile on Da Vinci’s masterpiece Mona Lisa has been an enigma for hundred years. 数百年来，达芬奇名作《蒙娜丽莎》上的微笑一直是个不解之谜"],
                                            ['mystery', 'conundrum', 'puzzle', 'riddle'],
                                            other_form = 'enigmatic adj. 谜一般的')]),
                              Word('enlighten', "",
                                   [TestWay('vt',
                                            '使知道',
                                            'to give information to; inform or instruct',
                                            ["enlightened us about the thorny problem 启发我们思考这个棘手的问题"],
                                            ['apprise', 'instruct'],
                                            ['bewilder', 'confuse', 'confound', 'perplex']),
                                    TestWay('vt',
                                            '(在道德上)进行教育',
                                            'to provide (someone) with moral or spiritual understanding',
                                            ["Many people around the world have been enlightened by the teachings of Gautama Buddha. 释迦摩尼的说教启迪了世界上许许多多的人的灵魂"],
                                            ['edify', 'educate', 'illuminate', 'nurture'],
                                            other_form = 'enlightening adj. 具有启发性的')]),
                              Word('enmity', "",
                                   [TestWay('n',
                                            '敌意',
                                            'positive, active, and typically mutual hatred or ill will',
                                            ["an unspoken enmity between two factions 两个派系间心照不宣的仇恨"],
                                            ['animosity', 'animus', 'antagonism', 'antipathy', 'feud', 'gall', 'hostility', 'rancor'],
                                            ['amity', 'comity', 'concord'])]),
                              Word('ennoble', "",
                                   [TestWay('vt',
                                            '使尊贵',
                                            'to make noble',
                                            ['Her skill and talent ennoble her profession. 技能和天赋使她成为业界领军人物。aggrandize, canonize, deify, dignify, glorify, magnify'],
                                            ['aggrandize', 'canonize', 'deify', 'dignify', 'glorify', 'magnify'],
                                            ['debase', 'abase', 'degrade', 'demean', 'humble', 'humiliate'])]),
                              Word('ennui', "",
                                   [TestWay('n',
                                            '倦怠;缺乏兴趣',
                                            'listlessness and dissatisfaction resulting from lack of interest',
                                            ["the kind of ennui that comes from having too much time on one's hands and too little will to find something productivetodo 倦怠来自于手上有大把时间却没有有益的事可做"],
                                            ['doldrums', 'listlessness', 'restlessness', 'tedium', 'weariness'],
                                            ['keen interest', 'energy', 'enthusiasm', 'exuberance'])]),
                              Word('ensemble', "",
                                   [TestWay('n',
                                            '合唱，合奏曲',
                                            'a work for two or more vocalists or instrumentalists',
                                            ["The actor performed an ensemble piece. 该演员参与了合唱。"],
                                            antonyms = ['solo'])]),
                              Word('ensconce', "",
                                   [TestWay('vt',
                                            '安置',
                                            'to settle (oneself) securely or comfortably',
                                            ['ensconce in a new job 在一个新职位安定下来'],
                                            ['install', 'lodge', 'nestle', 'perch', 'roost', 'settle'],
                                            ['unsettle', 'dislodge', 'displace']),
                                    TestWay('v',
                                            '隐藏',
                                            'to put in a hiding place',
                                            ["ensconced the spare house key in a place where no thief would think to look 把备用钥匙藏在小偷根本不会注意的地方"],
                                            ['bury', 'cache', 'conceal', 'secrete'],
                                            ['display', 'exhibit'])]),
                              Word('ensue', "",
                                   [TestWay('vi',
                                            '紧随其后',
                                            'take place afterward or as a result',
                                            ["A brief but embarrassing silence ensued. 一阵短暂且令人尴尬的沉默随之而来。"],
                                            ['anterior'])])])

LIST8 = VocabularyList(list8_unit1.words+list8_unit2.words+list8_unit3.words+list8_unit4.words+list8_unit5.words+list8_unit6.words+list8_unit7.words+list8_unit8.words+list8_unit9.words+list8_unit10.words)
