#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list11_unit1 = VocabularyList([Word('fussy', "",
                                   [TestWay('adj',
                                            '谨慎的',
                                            'taking, showing, or involving great care and effort',
                                            ["a fussy actuarial problem 需要谨慎处理的保险计算问题"],
                                            ['careful', 'exact', 'meticulous', 'punctilious'],
                                            ['careless']),
                                    TestWay('adj',
                                            '过分雕琢的',
                                            'elaborately and often excessively decorated',
                                            ["The room, with its rococo furniture and its overabundance of knickknacks, is just too fussy for my taste. 这房间里洛可可式的家具和过量的小饰品, 让我觉得装修得有点过分以至于无法接受"],
                                            ['bedizened', 'florid'],
                                            ['austere', 'plain', 'stark']),
                                    TestWay('adj',
                                            '挑剔的',
                                            'hard to please',
                                            ["It is widely known that cats are fussy eaters. 众所周知猫对食物很挑剔"],
                                            ['choosy', 'delicate', 'demanding', 'exacting', 'fastidious', 'nice', 'particular', 'persnickety', 'picky'],
                                            ['undemanding', 'unfussy'])]),
                              Word('fusty', "",
                                   [TestWay('adj',
                                            '过时的',
                                            'rigidly old-fashioned or reactionary',
                                            ["fusty old carpets 过时的旧地毯"],
                                            ['antiquated', 'archaic', 'bygone', 'moldy', 'outdated']),
                                    TestWay('adj',
                                            '腐臭的',
                                            'saturated with dust and stale odors',
                                            ["the fusty odor of a damp cellar 潮湿的地下室里的腐臭味道"],
                                            ['malodorous', 'fetid', 'musty', 'noisome', 'smelly', 'stale'],
                                            ['ambrosial', 'aromatic', 'fragrant', 'perfumed', 'redolent', 'savory', 'scented', 'sweet'])]),
                              Word('futile', "",
                                   [TestWay('adj',
                                            '无效的, 无用的',
                                            'serving no useful purpose; completely ineffective',
                                            ["It would be an undoubtedly futile effort to persuade him. 想说服他毫无疑问是徒劳的"],
                                            ['abortive', 'bootless', 'fruitless', 'ineffective', 'useless', 'vain'],
                                            ['effectual', 'efficacious']),
                                    TestWay('adj',
                                            '不严肃的',
                                            'lacking in seriousness or maturity',
                                            ["the futile chatter of gossip columnists about the comings and goings of Hollywood celebrities 八卦的专栏作家们对于好莱坞名人来来往往的随意闲谈"],
                                            ['flighty', 'frivolous', 'frothy'],
                                            ['earnest', 'serious'],
                                            'futility n. 徒劳, 无益')]),
                              Word('gadfly', "",
                                   [TestWay('n',
                                            '刺激物',
                                            'one that acts as a provocative stimulus',
                                            synonyms = ['goad', 'impetus', 'impulse', 'incentive', 'irritant', 'spur', 'stimulus'],
                                            antonyms = ['balm']),
                                    TestWay('n',
                                            '令人反感的人',
                                            'a person who stimulates or annoys especially by persistent criticism',
                                            ["a tactless gadfly during post-game interviews with the losing team 在赛后采访败北方时一个令人讨厌的不懂人情世故的人"],
                                            ['annoyer', 'bother', 'persecutor', 'teaser', 'pest'])]),
                              Word('gaffe', "",
                                   [TestWay('n',
                                            '(社交上)失礼, 失态',
                                            'a social or diplomatic blunder',
                                            ["A gaffe is when a politician tells the truth. —— Michael Kinsley 所谓出丑, 就是政治家说真话的时候(迈克·金斯利)"],
                                            ['impropriety', 'indecorum', 'indiscretion'],
                                            ['decency', 'decorum', 'propriety']),
                                    TestWay('n',
                                            '明显的错误, 错误判断',
                                            'a blatant mistake or misjudgment',
                                            ["so-called debates, which were mainly about seeing which candidate made the most gaffes 所谓的辩论, 其实主要就是看哪个选手犯了最多的错误"],
                                            ['blunder', 'lapse', 'misstep', 'oversight'])]),
                              Word('gainsay', "",
                                   [TestWay('v',
                                            '否认',
                                            'to declare false',
                                            synonyms = ['deny', 'contradict', 'contravene', 'naysay'],
                                            antonyms = ['acknowledge', 'admit', 'avow', 'concede', 'affirm']),
                                    TestWay('vt',
                                            '反对',
                                            'to oppose, especially by contradiction',
                                            ["No one dare to gainsay him. 没人敢反驳他"],
                                            ['disagree', 'refute', 'reject', 'repudiate'],
                                            ['concur'])]),
                              Word('gall', "",
                                   [TestWay('vt',
                                            '(使)焦躁, 激怒',
                                            'irritate, vex',
                                            ["The sarcastic applause from the audience galled her. 观众反讽的掌声激怒了她"],
                                            ['aggravate', 'exasperate', 'grate', 'inflame', 'provoke', 'pique', 'roil'],
                                            ['appease', 'assuage', 'calm', 'lull', 'pacify', 'placate']),
                                    TestWay('n',
                                            '深深的敌意',
                                            'a deep-seated ill will',
                                            ["Her kindly feelings turned to gall when she found out her nephew only wanted her money. 当她发现她的侄子只想要钱时, 她之前友好的感情变成了憎恨与厌恶"],
                                            ['animosity', 'animus', 'antagonism', 'antipathy', 'hostility', 'rancor'],
                                            ['amity']),
                                    TestWay('n',
                                            '大胆, 无耻',
                                            'shameless boldness',
                                            ["I can't believe he had the gall to ask me how much I weigh. 我不敢相信他居然胆敢问我有多重"],
                                            ['audacity', 'brass', 'nerve', 'presumptuousness', 'temerity', 'gallant'])]),
                              Word('gallant', "",
                                   [TestWay('adj',
                                            '英勇的',
                                            'brave, spirited; nobly chivalrous and often self-sacrificing',
                                            ["Gallant paratroopers jumped out of the plane without hesitation. 英勇的伞兵们毫不犹豫地跳出了飞机"],
                                            ['bold', 'courageous', 'dauntless', 'heroic', 'stouthearted', 'valorous'],
                                            ['craven', 'pusillanimous']),
                                    TestWay('adj',
                                            '高贵的, 慷慨的',
                                            'having, characterized by, or arising from a dignified and generous nature',
                                            ["The members of that service club are known for their gallant service to the community. 那个服务社的成员因为他们对社区的慷慨贡献而为人所知"],
                                            ['chivalrous', 'elevated', 'loft', 'magnanimous', 'sublime'],
                                            ['base', 'debased', 'degenerate', 'ignoble'],
                                            'gallantly adv. 英勇地')]),
                              Word('galvanize', "",
                                   [TestWay('vt',
                                            '(好似被用电击)刺激',
                                            'to stimulate or excite as if by an electric shock',
                                            ["an issue that would galvanize public opinion 激起大众评论的问题"],
                                            ['provoke', 'agitate', 'excite', 'intoxicate', 'motivate', 'stimulate', 'pump up'],
                                            ['allay', 'lull', 'pacify'],
                                            'galvanizing adj. 刺激的')]),
                              Word('gamble', "",
                                   [TestWay('vi',
                                            '赌博, 孤注一掷',
                                            'to bet on an uncertain outcome, as of a contest',
                                            ["gambled on the train being late 赌火车晚点"],
                                            ['bet', 'adventure', 'chance', 'risk', 'stake', 'venture']),
                                    TestWay('vi',
                                            '使受到威胁',
                                            'to place in danger',
                                            ["You don't want to gamble with your life, so buckle up. 你不会想拿命来开玩笑的, 所以系好安全带"],
                                            ['compromise', 'hazard', 'imperil', 'jeopardize', 'threaten'],
                                            other_form = 'gambling n. 赌博')])])

list11_unit2 = VocabularyList([Word('gambol', "",
                                   [TestWay('vi',
                                            '欢跳, 雀跃',
                                            'to leap about playfully',
                                            ["young lambs gamboling in the meadow 小羊羔在原野里欢快地跳跃"],
                                            ['frolic', 'caper', 'cavort'],
                                            ['plod', 'trudge'])]),
                              Word('gangly', "",
                                   [TestWay('adj',
                                            '身材瘦长的',
                                            'awkwardly tall or long-limbed',
                                            ["The suspect is a gangly high school boy. 嫌犯是一个瘦高的中学生"],
                                            ['gangling', 'lanky', 'rangy', 'spindling', 'spindly'],
                                            ['stalwart'])]),
                              Word('garble', "",
                                   [TestWay('vt',
                                            '曲解, 篡改, 混淆(以至使无法理解)',
                                            'to mix up or distort to such an extent as to make misleading or incomprehensible',
                                            ["The summary totally garbles the results of the investigation. 这份摘要完全曲解了调查的结果"],
                                            ['misrepresent', 'belie', 'color', 'distort', 'falsify', 'twist', 'warp'],
                                            ['clarify', 'elucidate']),
                                    TestWay('vt',
                                            '筛选, 除杂',
                                            'to remove usually visible impurities from',
                                            ["Garbled spices are less likely to contaminate a recipe. 经过筛选的香料应该就不会影响食谱了"],
                                            ['clear', 'distill', 'filter', 'purify'],
                                            ['adulterate', 'contaminate'])]),
                              Word('gargantuan', "",
                                   [TestWay('adj',
                                            '巨大的',
                                            'tremendous in size, volume, or degree',
                                            ["a gargantuan waterfall in the rainforest 热带雨林中的巨大瀑布"],
                                            ['huge', 'astronomical', 'colossal', 'elephantine', 'enormous', 'gigantic', 'immense', 'mammoth', 'monstrous', 'titanic'],
                                            ['infinitesimal', 'minuscule'])]),
                              Word('garish', "",
                                   [TestWay('adj',
                                            '过于鲜艳的, 过于张扬的',
                                            'marked by strident color or excessive ornamentation',
                                            ["With garish makeup on, she looks exceedingly frivolous. 浓妆艳抹之下的她显得格外轻佻"],
                                            ['gaudy', 'blatant', 'brazen', 'flamboyant', 'glaring', 'ostentatious'],
                                            ['dim', 'gloomy', 'murky', 'somber', 'conservative', 'quiet'])]),
                              Word('garment', "",
                                   [TestWay('n',
                                            '衣服',
                                            'an article of clothing',
                                            ["pack all garments 给所有衣服打包"],
                                            ['apparel', 'attire', 'costume', 'dress', 'suit'])]),
                              Word('garrulous', "",
                                   [TestWay('adj',
                                            '啰嗦的, 话多得令人厌烦的',
                                            'given to excessive and often trivial or rambling talk; tiresomely talkative',
                                            ["garrulous traveling companions 多话的旅伴"],
                                            ['talkative', 'chatty', 'loquacious', 'verbose', 'voluble'],
                                            ['laconic', 'reserved', 'reticent', 'taciturn'],
                                            'garrulity n. 啰嗦')]),
                              Word('gash', "",
                                   [TestWay('n',
                                            '砍得很深的伤口',
                                            'a long deep cut',
                                            ["got a gash in his knee that required four stitches 膝盖伤得很深, 需要缝针"],
                                            ['incision', 'laceration', 'rent', 'rip', 'tear']),
                                    TestWay('v',
                                            '砍',
                                            'to make a gash in',
                                            ["Her face had been gashed by the rocks as she tumbled down the embankment. 当她从堤岸上摔下来时脸上被刮了一道口"],
                                            ['cut', 'incision', 'piercing', 'slash', 'slice', 'slit'],
                                            ['sew', '缝合'])]),
                              Word('gasification', "",
                                   [TestWay('n',
                                            '气化',
                                            'conversion into gas',
                                            ["gasification of coals 煤的气化"],
                                            ['evaporation', 'sublimation'],
                                            ['solidification', 'liquefaction'],
                                            'gasify v. 气化')]),
                              Word('gauche', "",
                                   [TestWay('adj',
                                            '笨拙的, 缺乏社交经验的',
                                            'lacking social experience or grace',
                                            ["It would be gauche to mention the subject. 提到这个话题是很无礼的"],
                                            ['awkward', 'clumsy', 'crude', 'inept', 'maladroit', 'rustic', 'tactless'],
                                            ['graceful', 'polished', 'refined', 'urbane'],
                                            'gaucheness n. 笨拙')])])

list11_unit3 = VocabularyList([Word('gaudy', "",
                                   [TestWay('adj',
                                            '俗丽的',
                                            'ostentatiously or tastelessly ornamented, excessively showy',
                                            ["gaudy movie posters 俗丽的电影海报"],
                                            ['blatant', 'brazen', 'flashy', 'garish', 'glaring', 'meretricious', 'tawdry'],
                                            ['austere', 'homely', 'plain', 'conservative', 'understated', 'unflamboyant', 'unflashy'])]),
                              Word('gauge', "",
                                   [TestWay('n',
                                            '测量标准',
                                            'a measurement (as of linear dimension) according to some standard or system',
                                            ["polls as a gauge of voter satisfaction 用以衡量选民满意度的选票结果"],
                                            ['standard', 'benchmark', 'criterion', 'measure', 'touchstone', 'yardstick']),
                                    TestWay('vt',
                                            '判定',
                                            'to determine the capacity or contents of',
                                            ["It is hard to gauge his mood. 要判断他的情绪很困难"],
                                            ['assess', 'determine', 'evaluate', 'figure', 'measure', 'scale'])]),
                              Word('gear', "",
                                   [TestWay('v',
                                            '调整(以配合)',
                                            'to adjust or adapt so as to make suitable',
                                            ["geared the speech towards a conservative audience 调整演讲以适应保守的观众"],
                                            ['adapt', 'adjust', 'fit', 'suit', 'tailor'])]),
                              Word('genial', "",
                                   [TestWay('adj',
                                            '和蔼亲切的',
                                            'having an easygoing and pleasing manner especially in social situations',
                                            ["a genial host who makes a point of speaking personally to each and every guest 一个强调与每个客人私下交流的亲切的主人"],
                                            ['affable', 'agreeable', 'gracious', 'mellow', 'nice', 'pleasant', 'sweet'],
                                            ['caustic', 'mordant', 'truculent']),
                                    TestWay('adj',
                                            '友好的, 热心的',
                                            'having or showing kindly feeling and sincere interest',
                                            synonyms = ['amicable', 'companionable', 'cordial', 'warmhearted'],
                                            antonyms = ['antagonistic', 'hostile']),
                                    TestWay('adj',
                                            '温暖的',
                                            'marked by temperatures that are neither too high nor too low',
                                            ["genial sunshine in winter 冬日的暖阳"],
                                            ['balmy', 'equable', 'gentle', 'mild', 'moderate', 'soft', 'temperate'],
                                            ['harsh', 'inclement', 'intemperate', 'severe'],
                                            'geniality n. 和蔼')]),
                              Word('genteel', "",
                                   [TestWay('adj',
                                            '有教养的, 不粗俗的',
                                            'free from vulgarity or rudeness',
                                            ["Her genteel behaviors at the ball make others conjecture that she must come from a distinguished noble family. 舞会上她极有教养的举止让他人纷纷猜测她一定来自名门望族"],
                                            ['courteous', 'decent', 'decorous', 'mannerly', 'polite', 'polished', 'respectable', 'urbane', 'couth', 'cultured', 'refined'],
                                            ['churlish', 'loutish'])]),
                              Word('germane', "",
                                   [TestWay('adj',
                                            '有关的, 适当的',
                                            'being at once relevant and appropriate',
                                            ["details not germane to the discussion 与讨论无关的细节"],
                                            ['applicable', 'apropos', 'apposite', 'pertinent', 'relevant'],
                                            ['extraneous', 'irrelevant', 'inappropriate'])]),
                              Word('gibe', "",
                                   [TestWay('vt',
                                            '嘲弄',
                                            'to deride or tease with taunting words',
                                            ["gibe at the umpire 嘲弄裁判员"],
                                            ['deride', 'jeer', 'ridicule', 'mock', 'scoff', 'sneer', 'taunt'],
                                            ['respect', 'revere', 'venerate'])]),
                              Word('giddy', "",
                                   [TestWay('adj',
                                            '轻浮不严肃的',
                                            'lacking in seriousness or maturity',
                                            ["teach a bunch of giddy Girl Scouts how to make a fire 教一群漫不经心的女童子军如何生火"],
                                            ['flighty', 'frivolous', 'frothy'],
                                            ['grave', 'serious', 'earnest']),
                                    TestWay('adj',
                                            '喜悦的',
                                            'joyfully elated',
                                            ["He's clearly giddy at the news that his ailing grandfather will be fine. 听到他祖父的病将无大恙, 他的喜悦之情溢于言表"],
                                            ['elated', 'elevated', 'euphoric', 'exhilarated', 'exultant', 'intoxicated', 'rapturous'],
                                            ['depressed', 'melancholy'])]),
                              Word('gild', "",
                                   [TestWay('vt',
                                            '(带欺骗性地)修改, 润色',
                                            'to give an often deceptively attractive or improved appearance to',
                                            ["Any further retouch would be gilding the lily. 任何形式的润色都会是画蛇添足"],
                                            ['polish', 'refine', 'smooth'])]),
                              Word('gist', "",
                                   [TestWay('n',
                                            '要点',
                                            'the main point or part',
                                            ["the gist of the argument 论证的要点"],
                                            ['core', 'essence', 'kernel', 'pivot', 'quintessence', 'substance'],
                                            ['divergence'])])])

list11_unit4 = VocabularyList([Word('gladiator', "",
                                   [TestWay('n',
                                            '角斗士',
                                            'a person engaged in a fight to the death as public entertainment for ancient Romans',
                                            ["He comes to Rome as a gladiator to seek revenge. 他化成角斗士来到罗马寻求复仇"],
                                            ['fighter', 'belligerent', 'combatant']),
                                    TestWay('n',
                                            '参与打斗或辩论的人',
                                            'a person engaging in a public fight or controversy',
                                            synonyms = ['boxer'])]),
                              Word('glaze', "",
                                   [TestWay('vt',
                                            '给…上釉, 妆点',
                                            'to coat with or as if with a glaze',
                                            ["The storm glazed trees with ice. 暴风雨给树木镀上了一层冰装"],
                                            ['adorn', 'bedeck', 'decorate', 'embellish', 'garnish'],
                                            ['strip', 'uncover']),
                                    TestWay('vt',
                                            '使平滑',
                                            'to give a smooth glossy surface to',
                                            synonyms = ['polish', 'burnish', 'furbish', 'shine'],
                                            antonyms = ['rumple'])]),
                              Word('glib', "",
                                   [TestWay('adj',
                                            '流利圆滑的(常含有不真诚或欺诈的成分), 油腔滑调的',
                                            'marked by ease and fluency in speaking or writing often to the point of being insincere or deceitful',
                                            ["a glib politician 油嘴滑舌的政客"],
                                            ['nonchalant', 'oily'],
                                            ['taciturn', 'awkward']),
                                    TestWay('adj',
                                            '缺乏深度的, 肤浅的',
                                            'lacking depth and substance',
                                            ["glib solutions to the knotty problem 对复杂难解问题的肤浅的解决方案"],
                                            ['cursory', 'shallow', 'superficial'],
                                            ['abstruse', 'deep', 'profound'])]),
                              Word('glisten', "",
                                   [TestWay('vi',
                                            '闪光',
                                            'to shine by reflection with a sparkling luster',
                                            ["The calm sea glistened in the sunlight. 日光下平静的海面波光粼粼"],
                                            ['flash', 'scintillate', 'sparkle', 'twinkle', 'winkle'],
                                            ['dim'])]),
                              Word('glitch', "",
                                   [TestWay('n',
                                            '小故障',
                                            'a minor malfunction, mishap, or technical problem',
                                            ["postponement due to a glitch in a spacecraft's fuel cell 宇宙飞船燃料电池故障引起的推迟发射"],
                                            ['bug', 'defect', 'fault', 'lapse', 'imperfection', 'peccadillo'],
                                            ['fatal error'])]),
                              Word('gloat', "",
                                   [TestWay('vi',
                                            '自鸣得意',
                                            'a feeling of great, often malicious, pleasure or self-satisfaction',
                                            ["gloat over his enemy's misfortune 为敌人的不幸而自鸣得意"],
                                            ['crow', 'relish', 'triumph'],
                                            ['mourn'])]),
                              Word('gloomy', "",
                                   [TestWay('ad',
                                            '黯淡无光的',
                                            'being without light or without much light',
                                            synonyms = ['black', 'dark', 'dim', 'dimmed', 'murky', 'obscure', 'stygian', 'pitch-dark'],
                                            antonyms = ['bright', 'luminous', 'lucent', 'lucid']),
                                    TestWay('adj',
                                            '忧郁的',
                                            'low in spirits',
                                            ["feel gloomy about future career 就未来的职业生涯倍感忧心"],
                                            ['sullen', 'dejected', 'dour', 'melancholy', 'morose', 'saturnine', 'surly'],
                                            ['frothy', 'buoyant', 'cheerful', 'jubilant'])]),
                              Word('gloss', "",
                                   [TestWay('n',
                                            '简短解释',
                                            'a brief explanation of a difficult or obscure word or expression',
                                            synonyms = ['abstract', 'annotation', 'brief', 'epitome', 'synopsis'],
                                            antonyms = ['amplification']),
                                    TestWay('n',
                                            '(欺骗性的)光鲜外表',
                                            'a deceptively attractive external appearance',
                                            ["used a computer to give her astrological predictions the gloss of real science 用计算机来给他的占星预测结果套上科学的外衣"],
                                            ['façade', 'mask', 'veneer']),
                                    TestWay('v',
                                            '敷衍潦草做事(甚至忽略)',
                                            'to deal with (a subject or problem) too lightly or not at all',
                                            ["gloss over the problems 不怎么理会这些问题"],
                                            ['disregard', 'ignore', 'neglect', 'overlook'],
                                            ['scrutinize', '仔细研究']),
                                    TestWay('v',
                                            '开脱(罪名)',
                                            'to make (something) seem less bad by offering excuses',
                                            ["I don't want to gloss over her misbehavior, but keep in mind that she's been under a lot of stress lately. 我不想为她的行为辩护, 但是别忘了她最近压力很大"],
                                            ['excuse', 'extenuate'],
                                            other_form = 'glossary n. 术语表')]),
                              Word('glossy', "",
                                   [TestWay('adj',
                                            '平滑的, 有光泽的',
                                            'having a smooth, shiny, lustrous surface',
                                            ["glossy surface of the floor 平整光亮的地板"],
                                            ['lustrous', 'burnished', 'glistening', 'polished', 'shining'],
                                            ['coarse', 'dull', 'dim'])]),
                              Word('glut', "",
                                   [TestWay('v',
                                            '使过量, 使充满',
                                            'to fill beyond capacity, especially with food',
                                            ["glut himself with Sushi 吃寿司吃撑了"],
                                            ['cloy', 'cram', 'fill', 'satiate', 'surfeit', 'oversupply', 'sate'],
                                            ['lack'],
                                            'glutted adj. 饱和的')])])

list11_unit5 = VocabularyList([Word('glutinous', "",
                                   [TestWay('adj',
                                            '胶状的, 粘的',
                                            'of the nature of or resembling glue',
                                            ["glutinous liquid 胶状液体"],
                                            ['adherent', 'adhesive', 'cloggy', 'gluey', 'sticky', 'tenacious', 'viscid'],
                                            ['fluid'])]),
                              Word('glutton', "",
                                   [TestWay('n',
                                            '贪吃者',
                                            'a person who eats or consumes immoderate amounts of food and drink',
                                            ["a glutton for work 工作狂"],
                                            ['gorger', 'gourmand'],
                                            other_form = 'gluttony n. 暴饮暴食')]),
                              Word('goad', "",
                                   [TestWay('vt',
                                            '刺激驱使, 激发',
                                            'to incite or rouse as if with a goad',
                                            ["goad someone to do something 激励某人做某事"],
                                            ['urge', 'abet', 'exhort', 'instigate', 'prod', 'prompt', 'propel', 'spur', 'stimulate'],
                                            ['check', 'curb'])]),
                              Word('gobble', "",
                                   [TestWay('vt',
                                            '狼吞虎咽',
                                            'to swallow or eat greedily',
                                            ["Lions gobble their prey. 狮子狼吞虎咽地啃食它们的猎物"],
                                            ['devour', 'gorge', 'guzzle', 'quaff', 'raven', 'swill'],
                                            ['nibble', '小口咬'])]),
                              Word('goggle', "",
                                   [TestWay('v',
                                            '凝视',
                                            'to look long and hard in wonder or surprise',
                                            ["goggled at the characters on the stele 凝视碑文的字眼"],
                                            ['blink', 'gawk', 'gaze', 'peer', 'stare'],
                                            ['glance', 'glimpse'])]),
                              Word('goldbrick', "",
                                   [TestWay('vi',
                                            '逃避工作和责任',
                                            "to shirk one's assigned duties or responsibilities",
                                            ["goldbrick his duty as a citizen 逃避他作为公民的义务"],
                                            ['idle', 'parry', 'shirk', 'sidestep'],
                                            ['dedicate', 'devote'])]),
                              Word('gorge', "",
                                   [TestWay('n',
                                            '峡谷',
                                            'a narrow steep-walled canyon or part of a canyon',
                                            ["Wenchuan earthquake is said to have no detrimental effect on Three-Gorge dam. 汶川地震据称对三峡大坝没有破坏性影响"],
                                            ['gap', 'gulch', 'notch', 'ravine']),
                                    TestWay('',
                                            '狼吞虎咽',
                                            'to eat greedily or to repletion',
                                            ["gorge himself at the party 在聚会上狼吞虎咽"],
                                            ['cram', 'devour', 'gobble', 'guzzle', 'loaf', 'quaff', 'sate', 'swill'],
                                            ['nibble', '小口咬'],
                                            'gorgeous adj. 壮观的')]),
                              Word('gossamer', "",
                                   [TestWay('n',
                                            '虚无飘渺的东西',
                                            'something light, delicate, or insubstantial',
                                            ["the gossamer of youth's dreams 年少时飘渺的梦想"],
                                            ['ether', 'delicacy'],
                                            ['substance', 'entity']),
                                    TestWay('adj',
                                            '轻薄的',
                                            'extremely light, delicate, or tenuous',
                                            ["a gossamer explanation 站不住脚的解释"],
                                            ['diaphanous', 'ethereal', 'filmy', 'light', 'insubstantial', 'tenuous'],
                                            ['heavy', 'leaden', 'ponderous'])]),
                              Word('gourmand', "",
                                   [TestWay('n',
                                            '嗜食者, 大胃王',
                                            'one who is excessively fond of eating and drinking',
                                            ["the kind of gourmand who swallows food without even pausing to taste it 不尝味道就下咽的那种嗜食者"],
                                            ['gorger', 'glutton'])]),
                              Word('gourmet', "",
                                   [TestWay('n',
                                            '美食家',
                                            'a connoisseur of food and drink',
                                            ["a gourmet of Chinese food 中餐美食家"],
                                            ['bon vivant', 'connoisseur', 'epicure'],
                                            ['layman'])])])

list11_unit6 = VocabularyList([Word('grandeur', "",
                                   [TestWay('n',
                                            '高尚, 重要',
                                            'nobility or greatness of character',
                                            ["the glory that was Greece and the grandeur that was Rome 希腊的荣耀和罗马的辉煌"],
                                            ['magnificence', 'augustness', 'brilliance', 'glory', 'majesty', 'nobility', 'resplendence', 'splendor'],
                                            ['frivolousness'],
                                            'grand adj. 宏伟壮观的')]),
                              Word('grandiloquent', "",
                                   [TestWay('adj',
                                            '(语言等)浮夸的',
                                            'a lofty, extravagantly colorful, pompous, or bombastic style, manner, or quality especially in language',
                                            ["feel disgusted with his grandiloquent speech 对他浮夸的演讲表示厌恶"],
                                            ['rhetorical', 'bombastic', 'inflated', 'magniloquent', 'pretentious'],
                                            ['secretive', 'simple'],
                                            'grandiloquence n. 夸张的话语')]),
                              Word('grandiose', "",
                                   [TestWay('adj',
                                            '自命不凡的',
                                            'characterized by feigned or affected grandeur',
                                            ["grandiose words 自命不凡的话语"],
                                            ['extravagant', 'flamboyant', 'pompous', 'pretentious'],
                                            ['humble']),
                                    TestWay('adj',
                                            '宏大的',
                                            'characterized by greatness of scope or intent',
                                            ["a grandiose hydroelectric project 宏伟的水利工程"],
                                            ['august', 'glorious', 'grand', 'imposing', 'magnificent', 'monumental', 'splendid'],
                                            ['trivial', 'humble', 'unimposing', 'unimpressive'],
                                            'grandiosity n. 自命不凡')]),
                              Word('grandstand', "",
                                   [TestWay('vi',
                                            '为了给人留下印象而表演, 哗众取宠',
                                            'to play or act so as to impress onlookers',
                                            ["to grandstand on the stage 在舞台上哗众取宠"],
                                            ['act', 'perform', 'pretend'])]),
                              Word('grate', "",
                                   [TestWay('vt',
                                            '刮擦(以发出刺耳的声音)',
                                            'to make a rasping sound',
                                            ["The sled grated along the bare pavement. 雪橇与裸露的路面刮擦发出刺耳声"],
                                            ['abrade', 'rasp', 'scratch', 'scrape']),
                                    TestWay('vt',
                                            '骚扰, 惹恼',
                                            'to irritate or annoy persistently',
                                            ["a noise that grates on one's nerves 使人烦躁的噪音"],
                                            ['irritate', 'aggravate', 'gall', 'nettle', 'peeve', 'plague', 'provoke', 'vex'],
                                            ['soothe'],
                                            'grating adj. 刺耳的')]),
                              Word('gratify', "",
                                   [TestWay('vt',
                                            '使满足',
                                            'to give what is desired to, to please or satisfy',
                                            ["gratify her curiosity 满足她的好奇心‖Her praise will gratify all who worked so hard to earn it. 他的表扬会使所有辛勤工作的人们高兴"],
                                            ['appease', 'cater', 'content', 'satisfy'],
                                            ['displease', 'grieve'],
                                            'gratification n. 满意')]),
                              Word('gratuitous', "",
                                   [TestWay('adj',
                                            '无根据的, 无理由的',
                                            'unnecessary or unwarranted',
                                            ["a dubious request based on a gratuitous assumption 基于无根据假设的可疑要求"],
                                            ['unfounded', 'unjustified', 'unreasonable', 'baseless', 'groundless'],
                                            ['justified', 'warranted']),
                                    TestWay('adj',
                                            '无报酬的, 免费的',
                                            'given or granted without return or recompense',
                                            ["a gratuitous ticket 免费的门票"],
                                            ['free', 'complimentary', 'unearned', 'voluntary'],
                                            ['merited']),
                                    TestWay('adj',
                                            '多余的',
                                            'not needed by the circumstances or to accomplish an end',
                                            synonyms = ['dispensable', 'inessential', 'needless', 'redundant', 'superfluous', 'surplus'],
                                            antonyms = ['critical', 'essential', 'pivotal', 'vital'],
                                            other_form = 'gratuity n.报酬, 小费')]),
                              Word('green', "",
                                   [TestWay('adj',
                                            '无经验的',
                                            'deficient in training, knowledge, or experience',
                                            ["lead a squad of green recruits 带领一队没有经验的新兵"],
                                            ['inexperienced', 'callow', 'fresh', 'raw', 'unfledged', 'young'],
                                            ['experienced', 'versed'])]),
                              Word('gregarious', "",
                                   [TestWay('adj',
                                            '爱社交的',
                                            'likely to seek or enjoy the company of others',
                                            synonyms = ['convivial', 'extroverted', 'genial', 'sociable', 'outgoing'],
                                            antonyms = ['aloof', 'antisocial', 'introverted', 'reclusive']),
                                    TestWay('adj',
                                            '群居的',
                                            'likely to seek or enjoy the company of others',
                                            ["ecologically define human as gregarious carnivore 从生态学上将人类定义为群居类肉食动物"],
                                            ['social'],
                                            ['solitary'])]),
                              Word('grieve', "",
                                   [TestWay('vt',
                                            '感到悲伤',
                                            'to feel deep sadness or mental pain',
                                            ["we all grieved over the lost cat 看到他这副样子真让我痛苦"],
                                            ['agonize', 'anguish', 'suffer', 'bemoan', 'bewail', 'deplore'],
                                            ['delight', 'exult in', 'glory in', 'joy', 'rejoice in'])])])

list11_unit7 = VocabularyList([Word('grimace', "",
                                   [TestWay('n./v',
                                            '因痛苦而面部扭曲',
                                            'a sharp contortion of the face expressive of pain, disgust or disapproval',
                                            ["she made a grimace when she tasted the medicine 她尝了一口药然后面部扭曲了。"],
                                            ['frown', 'moue', 'pout', 'scowl'])]),
                              Word('grin', "",
                                   [TestWay('vi',
                                            '咧嘴笑',
                                            'to express an emotion (as amusement) by curving the lips upward',
                                            ["The boss grinned his approval. 老板咧嘴一笑表示赞许。"],
                                            ['beam'],
                                            ['pout', '噘嘴生气'])]),
                              Word('gripe', "",
                                   [TestWay('v',
                                            '抱怨',
                                            'to express dissatisfaction, pain, or resentment usually tiresomely',
                                            ["All workers were griping about the new regulations. 所有的工人都在抱怨新规章。"],
                                            ['carp', 'fuss', 'grouch', 'grouse', 'grumble', 'wail'],
                                            ['crow', 'delight', 'rejoice']),
                                    TestWay('v',
                                            '通过连续让人讨厌的举动激怒, 惹怒',
                                            'to disturb the peace of mind of (someone) especially by repeated disagreeable acts',
                                            ["constant complaints from the customers griped her to the point where she started snapping back 顾客持续的抱怨让她也到了爆点"],
                                            ['aggravate', 'annoy', 'bother', 'chafe', 'exasperate', 'nettle', 'peeve', 'pique', 'rile', 'ruffle', 'vex'])]),
                              Word('grisly', "",
                                   [TestWay('adj',
                                            '令人反感的, 令人恐惧的',
                                            'inspiring repugnance; gruesome',
                                            ["a series grisly murders 一系列令人恐惧的谋杀"],
                                            ['appalling', 'dreadful', 'ghastly', 'gruesome', 'hideous', 'horrifying', 'macabre'])]),
                              Word('groove', "",
                                   [TestWay('v',
                                            '享受, 极其满意, 过得快活',
                                            'to take pleasure in',
                                            ["thrill-seekers who groove on skiing will love snowboarding 那些乐在滑雪中的追求刺激的人们也会喜欢滑雪板的", "just sitting around, grooving on the music 随便坐坐, 在音乐中享受一下"],
                                            ['adore', 'fancy', 'savor', 'relish', 'get off on', 'rejoice in', 'revel in', 'delight in'])]),
                              Word('grotesque', "",
                                   [TestWay('adj',
                                            '难看的',
                                            'unpleasant to look at',
                                            ["that bloody Halloween mask is grotesque 那个血腥的万圣节面具丑死了"],
                                            ['hideous', 'homely', 'ill-favored', 'monstrous', 'unappealing', 'unattractive', 'uncomely', 'unsightly'],
                                            ['aesthetic', 'attractive', 'beautiful', 'bonny', 'comely', 'fetching', 'gorgeous', 'knockout', 'ravishing', 'seemly', 'sightly', 'stunning', 'taking', 'well-favored'])]),
                              Word('grovel', "",
                                   [TestWay('vi',
                                            '卑躬屈膝',
                                            'to draw back or crouch down in fearful submission',
                                            ["He made a groveling apology to the girl. 他放下身段, 给那姑娘道歉。"],
                                            ['cringe', 'creep', 'slither', 'wriggle'],
                                            other_form = 'groveler n. 卑躬屈膝者: the one who lies with the body prostrate in token of subservience or abasement')]),
                              Word('grueling', "",
                                   [TestWay('adj',
                                            '费时间花心思的',
                                            'requiring much time, effort, or careful attention',
                                            ["cutting diamonds can be grueling work 切割钻石是项劳神的活儿"],
                                            ['arduous', 'burdensome', 'laborious', 'onerous', 'taxing', 'toilsome'],
                                            ['effortless', 'light', 'unchallenging', 'undemanding', 'facile'])]),
                              Word('guile', "",
                                   [TestWay('n',
                                            '狡猾, 狡诈',
                                            'the inclination or practice of misleading others through lies or trickery',
                                            ["a person so full of guile he can't even be trusted to give you the correct time of day 他这个人狡诈成性, 说的话都不足为信"],
                                            ['artfulness', 'canniness', 'craft', 'cunningness', 'deviousness', 'slyness', 'subtleness', 'wiliness'],
                                            ['artlessness', 'forthrightness', 'ingenuousness', 'sincerity'],
                                            'guileless adj. 朴实的: free of guile; artless 【反】manipulative 操纵的')]),
                              Word('guilt', "",
                                   [TestWay('n',
                                            '自责, 悔恨',
                                            'a feeling of responsibility for wrongdoing',
                                            ["he was wracked with guilt after he accidentally broke his sister's antique grandfather clock"],
                                            ['contrition', 'penitence', 'remorse', 'repentance', 'self-reproach', 'shame'],
                                            ['impenitence', 'remorselessness'])])])

list11_unit8 = VocabularyList([Word('gull', "",
                                   [TestWay('v',
                                            '欺骗',
                                            'to cause to believe what is untrue',
                                            ["we were gulled into believing that if we answered the e-mail, we'd somehow become millionaires, but instead we just got put on a list for junk mail 我们误以为只要回复了那封邮件, 就能变身百万富翁, 后来发现我们只不过是群发的垃圾邮件名单上的一员而已"],
                                            ['bamboozle', 'beguile', 'cozen', 'delude', 'dupe', 'fake out', 'gaff', 'hoax', 'hoodwink', 'snooker', 'string along', 'take in'],
                                            ['undeceive'])]),
                              Word('gullible', "",
                                   [TestWay('adj',
                                            '易受骗的, 易被利用的',
                                            'easily duped or cheated, readily taken advantage of',
                                            ["They sell overpriced souvenirs to gullible tourists. 他们卖高价纪念品给易上当的旅客们。"],
                                            ['dewy-eyed', 'exploitable', 'naive', 'susceptible', 'unwary', 'wide-eyed'])]),
                              Word('gush', "",
                                   [TestWay('v',
                                            '大量涌出',
                                            'to flow forth suddenly in great volume',
                                            ["water gushing from the hydrant 水从消防栓中喷出"],
                                            ['exodus', 'outpour', 'outpouring', 'spout'],
                                            ['dribble', 'drip', 'drop', 'trickle']),
                                    TestWay('vi',
                                            '感情强烈外溢',
                                            'to make an exaggerated display of affection or enthusiasm',
                                            ["an aunt gushing over the baby 对着婴儿母爱泛滥的姑姑"],
                                            ['drool', 'effuse', 'enthuse', 'fuss', 'rave', 'slobber'])]),
                              Word('gust', "",
                                   [TestWay('n',
                                            '情感爆发',
                                            'a sudden intense expression of strong feeling',
                                            ["the stressed-out coworker cried out with a gust of emotion 压力巨大的同事开始嚎啕大哭"],
                                            ['burst', 'ebullition', 'eruption', 'explosion', 'flush', 'gush'])]),
                              Word('guzzle', "",
                                   [TestWay('v',
                                            '狂饮',
                                            'to drink especially liquor greedily, continually, or habitually',
                                            ["guzzle beer 狂饮啤酒"],
                                            ['gulp', 'quaff', 'swig', 'booze', 'soak', 'tipple'])]),
                              Word('hack', "",
                                   [TestWay('n',
                                            '雇佣文人',
                                            'a writer who aims solely for commercial success'),
                                    TestWay('v',
                                            '乱砍',
                                            'to cut or chop with repeated and irregular blows',
                                            ["hacking out new election districts 划分新的选区"]),
                                    TestWay('vt',
                                            '成功完成',
                                            'to deal with (something) usually skillfully or efficiently',
                                            ["just couldn't hack the new job 无法搞定新工作"],
                                            ['address', 'contend with', 'cope with', 'manage', 'maneuver', 'manipulate']),
                                    TestWay('v',
                                            '忍受',
                                            'to put up with (something painful or difficult)',
                                            ["she's not sure she can hack that miserable job much longer 她不知道还能忍受那项苦逼的工作多久"],
                                            ['abide', 'bide', 'brook', 'countenance', 'endure', 'handle', 'stand', 'stomach', 'sustain', 'tolerate'])]),
                              Word('hackneyed', "",
                                   [TestWay('adj',
                                            '陈腐的, 缺乏创新的',
                                            'lacking in freshness or originality',
                                            ["hackneyed slogans 老掉牙的口号"],
                                            ['banal', 'cliché', 'commonplace', 'hack', 'threadbare', 'trite', 'well-worn', 'stereotyped'],
                                            ['fresh', 'offbeat', 'original', 'novel'])]),
                              Word('halcyon', "",
                                   [TestWay('',
                                            '宁静的, 平静的',
                                            'free from storms or physical disturbance',
                                            synonyms = ['hushed', 'peaceful', 'placid', 'serene', 'tranquil', 'untroubled'],
                                            antonyms = ['tempestuous', 'stormy', 'agitated', 'inclement', 'restless', 'rough', 'turbulent', 'unquiet', 'unsettled']),
                                    TestWay('adj',
                                            '繁荣的, 丰富的',
                                            'prosperous, affluent, vigorous growth and well-being especially economically',
                                            ["halcyon years 丰年"],
                                            ['booming', 'flourishing', 'lush', 'palmy', 'prospering', 'roaring', 'thriving'],
                                            ['miserable', 'depressed', 'unprosperous'])]),
                              Word('hale', "",
                                   [TestWay('adj',
                                            '强壮的, 健壮的',
                                            'free from infirmity or illness; sound',
                                            ["a hale and hearty old lady 硬朗矍铄的老奶奶"],
                                            ['bouncing', 'fit', 'robust', 'sound', 'well-conditioned', 'wholesome'],
                                            ['effete', 'infirm', 'anemic', 'wan', 'decrepit', 'blighted']),
                                    TestWay('v',
                                            '拖, 拉',
                                            'to cause to follow by applying steady force on',
                                            ["the fishermen haled the huge net onto the deck of the ship 渔民们将巨大的渔网拖到渔船甲板上"],
                                            ['drag', 'draw', 'haul', 'lug', 'tow', 'tug'],
                                            ['drive', 'propel', 'push'])]),
                              Word('half-baked', "",
                                   [TestWay('adj',
                                            '不明智的',
                                            'showing or marked by a lack of good sense or judgment',
                                            ["a half-baked scheme 不明智的计划"],
                                            ['daffy', 'daft', 'dippy', 'harebrained', 'half-witted', 'preposterous'],
                                            ['judicious', 'prudent', 'sagacious', 'sapient', 'sensible', 'sound', 'wise'])])])

list11_unit9 = VocabularyList([Word('hallmark', "",
                                   [TestWay('n',
                                            '典型的特征',
                                            'a conspicuous feature or characteristic',
                                            ["the dramatic flourishes are the hallmark of the trial lawyer 一头夸张的假发是辩护律师的标志装扮"],
                                            ['ensign', 'impresa', 'logo', 'symbol', 'totem', 'trademark'],
                                            ['uncharacteristic feature'])]),
                              Word('hallow', "",
                                   [TestWay('vt',
                                            '尊敬, 把…视为神圣',
                                            'to respect or honor greatly; revere',
                                            synonyms = ['consecrate', 'sacralize', 'sanctify'],
                                            antonyms = ['desecrate', 'deconsecrate', 'desacralize', 'desanctify'])]),
                              Word('hallucination', "",
                                   [TestWay('n',
                                            '错觉',
                                            'a false idea or belief',
                                            ["the common hallucination that gluttony during the holiday season doesn't have consequences"],
                                            ['chimera', 'daydream', 'delusion', 'fancy', 'figment', 'illusion'],
                                            ['truth', 'verity'])]),
                              Word('ham-handed', "",
                                   [TestWay('adj',
                                            '笨手笨脚的',
                                            'lacking dexterity or grace',
                                            ["too ham-handed to use one of those tiny cell phones 手指太不灵活了, 用不了那种迷你型手机"],
                                            ['awkward', 'handless', 'heavy-handed', 'maladroit', 'unhandy'],
                                            ['deft', 'dexterous', 'handy', 'sure-handed', 'adroit'])]),
                              Word('hammer', "",
                                   [TestWay('v',
                                            '屡次重申',
                                            'to make repeated efforts especially: to reiterate an opinion or attitude.',
                                            ["the lectures all hammered away at the same points 整场讲座都是在阐述相同论点", "hammered the information into the students' heads 把这条信息反复向学生们强调"])]),
                              Word('hamper', "",
                                   [TestWay('vt',
                                            '阻碍',
                                            'to restrict the movement of by bonds or obstacles: impede',
                                            ["Construction is hampering traffic on the highway. 高速路上的建设阻碍了正常交通。"],
                                            ['cramp', 'encumber', 'fetter', 'handicap', 'hinder', 'impede', 'stymie', 'trammel'],
                                            ['facilitate', 'aid', 'assist', 'facilitate', 'help'])]),
                              Word('hamstring', "",
                                   [TestWay('vt',
                                            '使无效, 使无力',
                                            'to make ineffective or powerless',
                                            ["the downtown development committee claims that it's hamstrung by city ordinances 城镇发展委员会声称它受到了城市法令的阻碍"],
                                            ['cripple', 'immobilize', 'incapacitate', 'prostrate'])]),
                              Word('hangdog', "",
                                   [TestWay('adj',
                                            '伤心的, 沮丧的',
                                            'sad, dejected',
                                            ["She came home with a hangdog expression on her face. 她一脸沮丧地回到了家。"],
                                            ['crestfallen', 'dejected', 'despondent', 'disconsolate', 'doleful', 'melancholy', 'sorrowful'],
                                            ['buoyant', 'elated', 'sprightly', 'blissful', 'delighted', 'joyous', 'jubilant', 'upbeat'])]),
                              Word('hanker', "",
                                   [TestWay('v./n',
                                            '向往, 渴望',
                                            'to have a strong or persistent desire: yearn',
                                            ["hankering for adventure 渴望冒险"],
                                            ['appetite', 'craving', 'hunger', 'itch', 'longing', 'lust', 'passion', 'thirst', 'yearning'],
                                            ['odium', 'lack of desire'])]),
                              Word('haphazard', "",
                                   [TestWay('adj',
                                            '无秩序的, 无目标的',
                                            'marked by lack of plan, order, or direction',
                                            ["We were given a haphazard tour of the city. 我们进行了一次城市漫游。"],
                                            ['aimless', 'arbitrary', 'desultory', 'erratic', 'scattered', 'stray'],
                                            ['methodical', 'systematic', 'nonrandom', 'orderly', 'organized', 'regular'])])])

list11_unit10 = VocabularyList([Word('harangue', "",
                                   [TestWay('v',
                                            '发表长篇大论',
                                            'a long pompous speech, especially one delivered before a gathering',
                                            ["She harangued us for hours about the evils of popular culture. 她向我们絮叨了好几小时, 批判流行文化的堕落。"],
                                            ['diatribe', 'harangue', 'jeremiad', 'philippic', 'rant'],
                                            ['speak temperately'])]),
                              Word('harass', "",
                                   [TestWay('v',
                                            '烦扰',
                                            'to irritate or torment persistently',
                                            ["The troops harrassed the defeated army throughout its retreat. 战胜的队伍在撤退过程中还不忘突袭一下败北的队伍。"]),
                                    TestWay('v',
                                            '耗尽体力',
                                            'to use up all the physical energy of',
                                            ["had been visibly harassed by the demands of the presidency 总统被事务缠身, 筋疲力尽"],
                                            ['drain', 'fag', 'fatigue', 'outwear', 'tire', 'tucker out', 'wear out', 'knock out', 'burn out'])]),
                              Word('harbinger', "",
                                   [TestWay('n',
                                            '预言者',
                                            'one that presages or foreshadows what is to come',
                                            ["The October air stung my cheeks, a harbinger of winter. 十月的寒风凛冽地吹在脸上, 这是冬天的预兆。"],
                                            ['foregoer', 'herald', 'outrider', 'precursor'])]),
                              Word('harbor', "",
                                   [TestWay('vt',
                                            '提供住处, 隐匿',
                                            'to provide a place, home, or habitat for',
                                            ["harbor a fugitive 隐匿逃亡者"],
                                            ['accommodate', 'bestow', 'board', 'camp', 'chamber', 'domicile', 'lodge', 'quarter', 'take in', 'put up'],
                                            ['evict']),
                                    TestWay('v',
                                            '认为, 牢记',
                                            "to keep in one's mind or heart",
                                            ["he had long harbored a grudge against his old employer, who had fired him without cause 他对他的前老板一直耿耿于怀, 无缘无故炒了他"],
                                            ['bear', 'cherish', 'entertain', 'hold', 'nurse'])]),
                              Word('hard-bitten', "",
                                   [TestWay('adj',
                                            '顽强的, 经受的住困境、压力的',
                                            'able to withstand hardship, strain, or exposure',
                                            ["hard-bitten Chinese people could endure both the scorching heat and the freezing cold 坚强勇敢的中国人民既能受得住酷暑, 又能受得住严寒"],
                                            ['hardened', 'sturdy', 'tough', 'cast-iron', 'inured', 'rugged', 'stout', 'vigorous', 'hardy'],
                                            ['delicate', 'nonhardy', 'soft', 'tender', 'weak'])]),
                              Word('hardy', "",
                                   [TestWay('adj',
                                            '顽强的',
                                            'able to withstand hardship, strain, or exposure',
                                            ["chrysanthemums are hardy enough to survive a light frost 菊花能够经受霜打"],
                                            ['hardened', 'sturdy', 'tough', 'cast-iron', 'inured', 'rugged', 'stout', 'vigorous', 'hard-bitten'],
                                            ['delicate', 'nonhardy', 'soft', 'tender', 'weak']),
                                    TestWay('adj',
                                            '愿意冒风险的',
                                            'inclined or willing to take risks',
                                            ["hardy souls who pioneered new paths into outer space 那些愿意冒险探索外太空的先驱们"],
                                            ['adventurous', 'audacious', 'daring', 'dashing', 'emboldened', 'enterprising', 'gutsy', 'venturous'],
                                            ['unadventurous', 'unenterprising'])]),
                              Word('harmonious', "",
                                   [TestWay('adj',
                                            '和谐一致的',
                                            'having the parts agreeably related',
                                            ["a harmonious arrangement of archways and doorways in the palace courtyard 宫殿的庭院, 拱门和门廊排列有序协调"],
                                            ['balanced', 'congruous', 'consonant', 'eurythmic', 'harmonic', 'accordant', 'coherent', 'compatible', 'concordant', 'conformable', 'congruent', 'consonant', 'correspondent', 'nonconflicting'],
                                            ['disharmonic', 'disharmonious', 'incongruous', 'unbalanced', 'conflicting', 'incompatible', 'incongruous', 'inconsistent'])]),
                              Word('harness', "",
                                   [TestWay('vt',
                                            '利用',
                                            'utilize',
                                            ["harness the sun's rays as a source of energy 利用阳光作为一种能源"],
                                            ['apply', 'employ', 'exercise', 'exploit', 'operate', 'utilize'],
                                            ['fail to utilize'])]),
                              Word('harrow', "",
                                   [TestWay('vt',
                                            '折磨, 使苦恼',
                                            'to inflict great distress or torment on',
                                            ["the villagers were gaunt and sickly, harrowed by years of disease and starvation 村民们枯瘦如柴, 体弱多病, 都是被多年的疾病和饥饿折磨的"],
                                            ['agonize', 'beset', 'besiege', 'torment', 'torture', 'excruciate', 'plague'],
                                            ['assuage'])]),
                              Word('harry', "",
                                   [TestWay('v',
                                            '不断烦扰, 骚扰',
                                            'to disturb or distress by or as if by repeated attacks; harass',
                                            ["comfort, mollify"])])])

LIST11 = VocabularyList(list11_unit1.words+list11_unit2.words+list11_unit3.words+list11_unit4.words+list11_unit5.words+list11_unit6.words+list11_unit7.words+list11_unit8.words+list11_unit9.words+list11_unit10.words)
