#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list3_unit1 = VocabularyList([Word('barb', "",
                                   [TestWay('n',
                                            '尖锐而严厉的批评',
                                            'a biting or pointedly critical remark or comment',
                                            ['delivered one last barb to his ex-girlfriend as he stalked away 在他转身离去之前, 他前女友留下了最后一句尖锐的批评'],
                                            ['affront', 'criticism', 'offense', 'outrage', 'sarcasm', 'slight'],
                                            ['praise', 'applause', 'compliment'])]),
                              Word('barbarous', "",
                                   [TestWay('adj',
                                            '野蛮的, 凶残的',
                                            'mercilessly harsh or cruel',
                                            ['insulted by barbarous language 被粗暴的语言侵犯'],
                                            ['brutal', 'atrocious', 'fiendish', 'heartless', 'savage', 'truculent', 'vicious'],
                                            ['merciful', 'benevolent' , 'humane', 'sympathetic']),
                                    TestWay('adj',
                                            '未开化的',
                                            'uncivilized',
                                            ['some barbarous behaviors such as eating with your fingers 一些没有教养的举止, 比如直接用手拿东西吃'],
                                            ['wild', 'uncultivated'],
                                            ['civilized', 'decent', 'decorous'])]),
                              Word('barefaced', "",
                                   [TestWay('adj',
                                            '公然的, 厚颜无耻的',
                                            'undisguisedly bold; brazen',
                                            ['a barefaced lie 一个公然的谎言'],
                                            ['apparent', 'plain', 'bald', 'evident', 'manifest', 'obvious', 'perspicuous'],
                                            ['secret', 'furtive', 'clandestine', 'surreptitious'])]),
                              Word('bargain', "",
                                   [TestWay('n',
                                            '协议',
                                            'an agreement between parties settling what each gives or receives in a transaction',
                                            ['They made a bargain that one would help the other next week. 他们达成了一项协议:下周其中一人将帮助另外一人'],
                                            ['accord', 'compact', 'contract', 'covenant', 'deal', 'pact', 'settlement']),
                                    TestWay('vi',
                                            '讨价还价',
                                            'to negotiate over the terms of a purchase',
                                            ['bargain over the price 讨价还价'],
                                            ['haggle', 'negotiate'])]),
                              Word('baroque', "",
                                   [TestWay('adj',
                                            '华丽装饰的, 过分雕琢, 复杂的',
                                            'characterized by extravagance, complexity, or flamboyances',
                                            ['a baroque prose 一篇辞藻华丽的散文'],
                                            ['byzantine', 'complicated', 'convoluted', 'elaborate', 'fancy', 'intricate', 'knotty', 'labyrinthine', 'lavish', 'tangled'],
                                            ['austere', 'plain', 'simple']),
                                    TestWay('adj',
                                            '(程度)过分的',
                                            'going beyond a normal or acceptable limit in degree or amount',
                                            ['Eventually even the movie seems bored by its baroque violence. 到最后这电影也因为其中过度的暴力元素而显得让人厌烦'],
                                            ['exorbitant', 'extravagant', 'lavish', 'overdue'],
                                            ['moderate', 'modest', 'temperate'])]),
                              Word('barrage', "",
                                   [TestWay('n',
                                            '弹幕',
                                            'a heavy curtain of artillery fire directed in front of friendly troops to protect them',
                                            ['Troops are advancing under the shield of barrage. 部队在弹幕的掩护下前进'],
                                            ['bombardment', 'fusillade']),
                                    TestWay('n',
                                            '有压倒之势的、集中的倾泻(如言语)',
                                            'an overwhelming, concentrated outpouring, as of words',
                                            ['The announcement was met with a barrage of criticism and protests. 此公告一出, 批评和抗议的声音四起'],
                                            ['salvo', 'hail', 'cannonade', 'shower', 'storm', 'volley']),
                                    TestWay('v',
                                            '(同时)袭来',
                                            'to attack with a rapid or overwhelming outpouring of many things at once',
                                            [' The athlete was barraged with requests for an autograph. 请求运动员签名的呼声如排山倒海般袭来'],
                                            ['bomb'])]),
                              Word('barren', "",
                                   [TestWay('adj',
                                            '不育的',
                                            'incapable of producing offspring',
                                            ['a poor, barren woman 一名可怜的不孕女子'],
                                            ['fruitless', 'impotent', 'infertile', 'effete'],
                                            ['prolific', 'fecund']),
                                    TestWay('adj',
                                            '不产生结果的, 无效的',
                                            'producing no results; unproductive',
                                            [' That line of investigation proved barren, so the police tried other avenues. 那个方向的调查已经被证明是没有结果的了, 所以警察开始尝试其他的途径'],
                                            ['bootless', 'ineffective', 'inefficacious', 'unavailing', 'vain'],
                                            ['effective', 'successful', 'productive', 'virtuous']),
                                    TestWay('adj',
                                            '贫瘠的',
                                            'deficient in production of vegetation and especially crops',
                                            ['barren deserts and wastelands 贫瘠的沙漠和荒野'],
                                            ['desolate', 'impoverished', 'waste'],
                                            ['arable', 'fruitful', 'luxuriant', 'verdant']),
                                    TestWay('adj',
                                            '极度匮乏的',
                                            'utterly lacking in something needed, wanted, or expected',
                                            ['Their proposal for revitalizing the downtown business district is utterly barren of practical methods. 他们意图重振中心商业区的计划缺乏能够起效的方法'],
                                            ['bare', 'bereft', 'destitute', 'void'],
                                            ['filled', 'flush', 'fraught', 'full', 'replete', 'rife'])]),
                              Word('barricade', "",
                                   [TestWay('n',
                                            '障碍物',
                                            'an obstruction or rampart thrown up across a way or passage',
                                            ['Thepoliceputupbarricadestoblockofftheparaderoute. 警察设立了路障来阻挡游行的队伍'],
                                            ['fence', 'hedge', 'wall', 'barrier', 'obstacle', 'blockade', 'obstruction']),
                                    TestWay('v',
                                            '用障碍物阻止通过',
                                            'to prevent access to by means of a barricade',
                                            ['streets have been barricaded by authorities 街道被当局封锁了'],
                                            ['bar', 'check', 'hinder', 'impede', 'obstruct', 'wall off'],
                                            ['permit'])]),
                              Word('barter', "",
                                   [TestWay('v',
                                            '以物换物',
                                            'to trade (goods or services) without the exchange of money',
                                            ['barter wheat for cotton 以小麦换棉花'],
                                            ['swap', 'trade'])]),
                              Word('batch', "",
                                   [TestWay('n',
                                            '一批次的量',
                                            'a number of things considered as a unit',
                                            ['a batch of cookies 一批次烘烤的饼干'],
                                            ['array', 'collection', 'package', 'parcel', 'group']),
                                    TestWay('n',
                                            '一小群人',
                                            'a usually small number of persons considered as a unit',
                                            ['Show the next batch of applicants in, please. 请带下一批申请人进来'],
                                            ['band', 'body', 'cluster', 'party'])])])

list3_unit2 = VocabularyList([Word('bathetic', "",
                                   [TestWay('adj',
                                            '平凡的, 陈腐的',
                                            'characterized by exceptional commonplaceness',
                                            ['a bathetic funeral scene 平凡的葬礼场面'],
                                            ['rite', 'cliché', 'commonplace', 'hackneyed', 'stale', 'stereotyped'],
                                            ['offbeat', 'exceptional'],
                                            'bathos n. 平凡的事物')]),
                              Word('bawdy', "",
                                   [TestWay('adj',
                                            '下流的, 猥亵的',
                                            'boisterously or humorously indecent',
                                            ['a bawdy joke 黄色笑话; bawdy house 妓院'],
                                            ['obscene', 'lewd', 'ribald', 'vulgar'],
                                            ['decent', 'decorous', 'chaste', 'noble'])]),
                              Word('bedeck', "",
                                   [TestWay('vt',
                                            '装饰, 点缀',
                                            'to make more attractive by adding something that is beautiful or becoming',
                                            ['flag bedecking the balcony 在阳台上用以装饰的旗子; bedeck with jewels 用珠宝装饰'],
                                            ['adorn', 'beautify', 'decorate', 'dress', 'embellish', 'emblaze'],
                                            ['strip', 'blemish', 'deface', 'mar', 'spoil'])]),
                              Word('belabor', "",
                                   [TestWay('v',
                                            '(当众)严厉批评',
                                            'to criticize harshly and usually publicly',
                                            [" It’s not wise to belabor other people's flaws when you're hardly perfect yourself. 如果你自己还做不到完美, 去指责他人是不明智的"],
                                            ['beat', 'baste', 'batter', 'excoriate', 'lambaste', 'abuse', 'assail', 'vituperate', 'scathe'],
                                            ['applaud', 'extol', 'eulogize', 'endorse', 'acclaim']),
                                    TestWay('v',
                                            '就...作过度的说明, 喋喋不休',
                                            'to explain or insist on excessively',
                                            ['belabor the obvious 就显而易见的问题喋喋不休'],
                                            ['dwell on', 'harp on'],
                                            ['disregard', 'omit', 'ignore', 'neglect', 'slight', 'slur over'])]),
                              Word('beleaguer', "",
                                   [TestWay('vt',
                                            '包围, 围攻',
                                            'to surround (as a fortified place) with armed forces for the purpose of capturing or preventing commerce and communication',
                                            ['beleaguered the castle for months 围攻堡垒长达数月'],
                                            ['siege', 'besiege', 'invest', 'blockade'],
                                            ['retreat', 'withdraw']),
                                    TestWay('vt',
                                            '使困扰, 使烦恼, 使消沉',
                                            'trouble, harass, beset',
                                            ['We are still beleaguered by the very problem. 我们仍然就为这一个问题而感到困扰'],
                                            ['annoy', 'harass', 'pester', 'plague', 'tease'],
                                            ['delight'],
                                            'beleaguering adj. 扰人的')]),
                              Word('belie', "",
                                   [TestWay('v',
                                            '错误地描述;误述',
                                            'to picture falsely; misrepresent',
                                            ['The report belied the real severity of the aftermath. 这个报道错误地评价了后果的严重性'],
                                            ['misrepresent', 'falsify'],
                                            ['betray', 'reveal']),
                                    TestWay('v',
                                            '证明...为假',
                                            'to show (something) to be false or wrong',
                                            ['Practical experience belies this theory. 实践证明这个理论是错误的'],
                                            ['debunk', 'discredit', 'refute', 'shoot down'],
                                            ['attest', 'confirm', 'validate', 'verify']),
                                    TestWay('v',
                                            '掩饰',
                                            'to keep secret or shut off from view',
                                            ['Security Council issued false assurances that belied the true gravity of the situation. 安理会发布了不真实的承诺, 掩盖了局势的严重性'],
                                            ['conceal', 'curtain', 'disguise', 'mask'],
                                            ['disclose', 'expose']),
                                    TestWay('v',
                                            '与...相对立;与...相矛盾',
                                            'to be counter to; contradict',
                                            ['At first glance, life at the boarding school seemed to belie all the bad things I had heard about it. 乍看之下, 寄宿学校的生活似乎不同于我所听说的有关它的糟糕情形。'],
                                            ['contradict', 'contravene'],
                                            ['agree'])]),
                              Word('bellwether', "",
                                   [TestWay('n',
                                            '领导者, 带头人',
                                            'one that takes the lead or initiative',
                                            ['Paris is a bellwether of the fashion industry. 巴黎是一座引领时尚潮流的都市'],
                                            ['leader', 'pacemaker', 'pilot', 'trendsetter'],
                                            ['follower', 'disciple', 'imitator'])]),
                              Word('beneficent', "",
                                   [TestWay('adj',
                                            '仁慈的, 好慈善的',
                                            'characterized by or performing acts of kindness or charity',
                                            ['beneficent couple who are regular volunteers at an orphan 一对在孤儿院做义工的慈善的夫妇'],
                                            ['kind', 'altruistic', 'benevolent', 'philanthropic', 'benign', 'compassionate', 'sympathetic'],
                                            ['atrocious', 'barbarous', 'truculent', 'vicious']),
                                    TestWay('adj',
                                            '(对个人或社会)有益的',
                                            'promoting or contributing to personal or social well-being',
                                            ['the beneficent effect of sunshine 日光浴的益处'],
                                            ['helpful', 'advantageous', 'favorable', 'kindly', 'profitable', 'salutary'],
                                            ['detrimental', 'harmful', 'noxious', 'toxic'],
                                            'beneficently adv. 仁慈地')]),
                              Word('benign', "",
                                   [TestWay('adj',
                                            '好心的, 仁慈的',
                                            'showing kindness and gentleness',
                                            ['a benign coach 一名仁慈的教练'],
                                            ['beneficent', 'gentle', 'kind'],
                                            ['abrasive', 'caustic', 'coarse', 'hard', 'harsh', 'rough', 'scathing', 'stern']),
                                    TestWay('adj',
                                            '无害的',
                                            'not causing or being capable of causing injury or hurt',
                                            ["Don’t worry; his eccentricities are entirely benign. 别担心, 他那些古怪行为不会给人带来伤害"],
                                            ['harmless', 'innocent', 'innocuous', 'inoffensive'],
                                            ['baleful', 'deleterious', 'detrimental', 'harmful', 'injurious', 'pernicious'])]),
                              Word('berate', "",
                                   [TestWay('v',
                                            '(长时间)严厉指责',
                                            'to scold or condemn vehemently and at length',
                                            ['He berated them in public. 他公开谴责他们'],
                                            ['castigate', 'flay', 'lambaste', 'scold', 'rail', 'upbraid', 'reproach', 'reprimand'],
                                            ['commend', 'compliment', 'praise'])])])

list3_unit3 = VocabularyList([Word('beseech', "",
                                   [TestWay('v',
                                            '(急切地)恳求',
                                            'to beg for urgently or anxiously',
                                            ['They besought the military to act immediately. 他们恳求军方立即采取行动'],
                                            ['appeal', 'conjure', 'entreat', 'implore', 'petition', 'plead', 'supplicate'],
                                            ['demand', '(依据权力等)要求'])]),
                              Word('besmirch', "",
                                   [TestWay('v',
                                            '弄脏, 弄污',
                                            'to make dirty; soil',
                                            ['besmirched the white bed sheets with their dirty hands 用他们的脏手把白床单弄脏了'],
                                            ['foul', 'smirch', 'smudge', 'taint'],
                                            ['clean', 'cleanse']),
                                    TestWay('v',
                                            '诽谤, 玷污',
                                            'to detract from the honor or luster of',
                                            ['besmirch your reputation by fabricating scandals 通过捏造丑闻来玷污你的名声'],
                                            ['defile', 'smear', 'soil', 'stain'],
                                            ['honor'])]),
                              Word('bifurcate', "",
                                   [TestWay('vi./vt',
                                            '(使)分成两支',
                                            '(to cause) to divide into two branches or parts',
                                            ['Their visions of the company’s future slowly began to bifurcate. 我们关于公司未来的构想慢慢出现分歧'],
                                            ['divide', 'diverge', 'fork'],
                                            ['coalesce', 'converge'])]),
                              Word('bigot', "",
                                   [TestWay('n',
                                            '固执己见者, 有偏见的人',
                                            'a person obstinately devoted to his own opinions and prejudices',
                                            ['a bigot, or "a slave of dogma" 一个固执己见的人, 换而言之就是——教条主义的奴隶'],
                                            ['dogmatist', 'partisan'],
                                            ['depreciator', 'disparager'],
                                            'bigoted adj. 固执己见的')]),
                              Word('bland', "",
                                   [TestWay('adj',
                                            '味道平淡的',
                                            'not irritating or stimulating; soothing',
                                            ['stick to bland diet to lose weight 坚持清淡的饮食以减肥'],
                                            ['mild', 'light', 'soft', 'soothing', 'tender'],
                                            ['pungent', 'tangy', 'zesty']),
                                    TestWay('adj',
                                            '无趣的',
                                            'dull, insipid',
                                            ['a bland story with naïve plot一个情节幼稚的无聊故事'],
                                            ['banal', 'sapless', 'insipid'],
                                            ['riveting', 'enchanting']),
                                    TestWay('adj',
                                            '温和的, 和蔼的',
                                            'not harsh or stern especially in nature or effect',
                                            ['bland food that was good for babies and invalids 对婴儿和病患有益的温和的食物'],
                                            ['balmy', 'benign', 'bland', 'delicate', 'mellow', 'nonabrasive'],
                                            ['abrasive', 'caustic', 'coarse', 'hard', 'harsh', 'rough', 'scathing', 'stern'])]),
                              Word('blandishment', "",
                                   [TestWay('n',
                                            '甜言蜜语, 讨好某人的话',
                                            'something that tends to coax or cajole',
                                            ['Our blandishment left her unmoved. 纵使甜言蜜语她也无动于衷'],
                                            ['flattery', 'adulation'])]),
                              Word('blasé', "",
                                   [TestWay('adj',
                                            '(过度放纵之后)厌倦享乐的, 腻烦的',
                                            'apathetic to pleasure or excitement as a result of excessive indulgence or enjoyment',
                                            ['Years of extravagance has made him totally blasé. 长期的奢华生活已使他彻底麻木'],
                                            ['indifferent', 'jaded', 'unconcerned', 'world-weary'],
                                            ['zealous', 'fanatic', 'curious'])]),
                              Word('blast', "",
                                   [TestWay('n',
                                            '爆炸',
                                            'an explosion or violent detonation',
                                            ['blast wave of a nuclear bomb 原子弹的冲击波'],
                                            ['burst', 'detonation', 'eruption', 'outburst'],
                                            ['implosion']),
                                    TestWay('n',
                                            '一阵猛烈的强风',
                                            'a violent gust of wind',
                                            ['blasts of bleak air 阵阵阴风'],
                                            ['blow', 'flurry']),
                                    TestWay('n',
                                            '巨响',
                                            'a loud explosive sound',
                                            ['a sharp blast of the horn startled the other driver 一声尖锐刺耳的喇叭声惊吓到了另一名司机'],
                                            ['bang', 'boom', 'thunderclap'],
                                            ['murmur', 'whisper']),
                                    TestWay('vt',
                                            '炸裂, 爆破',
                                            'to cause to break open or into pieces by or as if by an explosive',
                                            ['The highway engineers will have to blast that hill in order to put a road through here. 为了建设一条公路, 道路工程师们必须对那座山进行爆破'],
                                            ['demolish', 'explode', 'smash', 'blow up']),
                                    TestWay('vt',
                                            '斥责, 抨击',
                                            'to criticize harshly and usually publicly',
                                            ['blasted the new governor for every little misstep 就每一个小的失误都要抨击新的执政官'],
                                            ['abuse', 'assail', 'belabor', 'castigate', 'lambaste', 'scathe', 'vituperate'])]),
                              Word('blatant', "",
                                   [TestWay('adj',
                                            '大声喧哗的',
                                            'noisy, especially in a vulgar or offensive manner',
                                            ['blatant radios 喧闹恼人的电台'],
                                            ['boisterous', 'clamant', 'clamorous', 'vociferous'],
                                            ['quiet', 'reticent', 'taciturn']),
                                    TestWay('adj',
                                            '(让人生厌地)惹人注目的',
                                            'very noticeable especially for being incorrect or bad',
                                            ['a blatant lie 明目张胆的谎言', 'a blatant error in simple addition 简单的加法运算中的一个明显错误'],
                                            ['conspicuous', 'flagrant', 'glaring', 'patent', 'striking', 'pronounced'],
                                            ['subtle', 'unimpressive'])]),
                              Word('blazon', "",
                                   [TestWay('vt',
                                            '使知名',
                                            'to make known openly or publicly',
                                            ['Their very public canoodling has pretty much blazoned the fact that they are having an affair. 他们彼此间公开的亲昵举动让他们之间的恋情大白于天下'],
                                            ['annunciate', 'broadcast', 'declare', 'publicize', 'proclaim'],
                                            ['withhold', '保留, 不透露']),
                                    TestWay('v',
                                            '修饰, 装扮',
                                            'to make more attractive by adding something that is beautiful or becoming',
                                            ['The university’s dormitory has been blazoned with banners celebrating graduation. 学校宿舍被那些庆祝毕业的横幅所装点'],
                                            ['adorn', 'bedeck', 'embellish', 'garnish'],
                                            ['blemish', 'deface', 'mar', 'spoil'])])])

list3_unit4 = VocabularyList([Word('blemish', "",
                                   [TestWay('n',
                                            '缺点, 污点',
                                            'a noticeable imperfection',
                                            ['The first LCD had several blemishes on its surface, so we took it back to the store. 第一块液晶显示屏有许多坏点, 所以我们拿回商场去退货了'],
                                            ['blotch', 'defect', 'fault', 'flaw', 'mar', 'spot', 'scar']),
                                    TestWay('v',
                                            '损害, 降低',
                                            'to reduce the soundness, effectiveness, or perfection of',
                                            ['A scratch blemished the finish on the car. 一道刮痕破坏了车子表面的涂层'],
                                            ['break', 'disfigure', 'harm', 'hurt', 'impair', 'injure', 'spoil', 'vitiate'],
                                            ['fix', 'renovate', 'repair', 'revamp'],
                                            'unblemished adj. 纯净的')]),
                              Word('blight', "",
                                   [TestWay('v',
                                            '(使)枯萎',
                                            'to affect (as a plant) with blight',
                                            synonyms = ['wither', 'shrivel'],
                                            antonyms = ['flourish']),
                                    TestWay('v',
                                            '损害',
                                            'to impair the quality or effect of',
                                            ['Illness blighted his career. 伤病毁了他的职业生涯', 'Cosmetics are often used to conceal facial blemishes. 化妆品常用来遮盖脸部色斑。'],
                                            ['damage', 'deteriorate', 'harm', 'impair', 'mar', 'ruin'],
                                            other_form = 'blighted adj. 枯萎的, 毁坏的')]),
                              Word('bliss', "",
                                   [TestWay('n',
                                            '极度快乐',
                                            ' extreme happiness; ecstasy',
                                            ['Ignorance is bliss ——The Matrix. 无知者, 幸也(电影《黑客帝国》)'],
                                            ['beatitude', 'joy', 'ecstasy', 'elation'],
                                            ['grief', 'misery']),
                                    TestWay('n',
                                            '极乐世界',
                                            'a dwelling place of perfect happiness for the soul after death',
                                            ['the road to eternal bliss通往永恒乐土的道路'],
                                            ['heaven', 'paradise'],
                                            ['hell'],
                                            'blissful adj. 带来幸运的')]),
                              Word('blithe', "",
                                   [TestWay('adj',
                                            '愉快高兴的',
                                            'of a happy lighthearted character or disposition',
                                            ['Everyone loved her for her blithe spirit. 所有人都喜欢她开朗的性格'],
                                            ['bright', 'buoyant', 'gay', 'jocular', 'jocund', 'jovial'],
                                            ['dour', 'gloomy', 'morose', 'saturnine', 'sulky', 'sullen']),
                                    TestWay('adj',
                                            '无忧无虑的',
                                            'having or showing freedom from worries or troubles',
                                            ["He has a blithe attitude about ever having to earn a living because he knows there's a trust fund in his future. 他对生活无忧无虑, 因为他知道他的未来有信托基金可以倚靠"],
                                            ['debonair', 'insouciant', 'lighthearted'],
                                            ['careworn'])]),
                              Word('blueprint', "",
                                   [TestWay('n',
                                            '蓝图, 详细计划',
                                            'a photographic print used especially for architects’ plans',
                                            ['a blueprint for the new library 新图书馆的建造蓝图'],
                                            ['arrangement', 'design', 'plan', 'scheme']),
                                    TestWay('v',
                                            '事先计划',
                                            'to work out the details of (something) in advance',
                                            ['blueprinted the schedule of events for the festival right down to the last detail 把节日的活动的每一个细节都事先安排好了'],
                                            ['arrange', 'budget', 'calculate', 'organize', 'frame', 'lay out'])]),
                              Word('blunder', "",
                                   [TestWay('n',
                                            '过失',
                                            'a gross error or mistake resulting usually from stupidity, ignorance, or carelessness',
                                            ["That's your second blunder today. 这是你今天犯的第二个低级错误了"],
                                            ['mistake', 'gaffe', 'lapse', 'error']),
                                    TestWay('v',
                                            '在...方面犯了很愚蠢且通常很严重的错误;糟蹋',
                                            'to make a stupid, usually serious error in; botch',
                                            synonyms = ['screw up', 'mess up']),
                                    TestWay('v',
                                            '蹒跚',
                                            'to move unsteadily or confusedly',
                                            ['Without my glasses I blundered into the wrong room. 因为没戴眼镜, 我蹒跚地走入了错误的房间'],
                                            ['stumble', 'falter', 'limp', 'plod'],
                                            other_form = 'blundering adj. 蹒跚行走的')]),
                              Word('blunt', "",
                                   [TestWay('vt',
                                            '使变钝',
                                            'to make less sharp or definite',
                                            synonyms = ['dull', 'deaden', 'hebetate', 'benumb', 'enfeeble', 'attenuate'],
                                            antonyms = ['whet', 'sharpen']),
                                    TestWay('vt',
                                            '减弱(力度等)',
                                            'to reduce or weaken in strength or feeling',
                                            ["The abrupt music blunted the effect of the movie's final tragic scene. 突兀的音乐让电影结束时悲剧场景的氛围大打折扣"],
                                            ['dampen', 'deaden']),
                                    TestWay('adj',
                                            '直率的',
                                            'being or characterized by direct, brief, and potentially rude speech or manner',
                                            ["Hevalueshonestyandisquitebluntabouttellingpeoplewhathedoesn'tlikeaboutthem. 他重视诚实, 经常直率地告诉别人他们何处使他不满"],
                                            ['abrupt', 'bluff', 'brusque', 'curt', 'gruff'],
                                            ['circuitous', 'mealy-mouthed'])]),
                              Word('blur', "",
                                   [TestWay('v',
                                            '(使)变得朦胧, (使)变得不清楚',
                                            'to (cause sth. to) become vague or indistinct',
                                            ['Sorrowful tears blurred her eyes. 悲伤的眼泪模糊了她的双眼'],
                                            ['shroud', 'becloud', 'befog', 'obscure'],
                                            ['clear']),
                                    TestWay('v',
                                            '使不易理解',
                                            'to make (something) unclear to the understanding',
                                            [' An article for the layman that blurs the distinction between the two kinds of cholesterol. 一篇针对业余读者的文章把两种胆固醇的区别弄得模糊不清'],
                                            ['obfuscate'],
                                            ['clarify', 'illuminate'],
                                            'blurring adj. 朦胧的')]),
                              Word('blurt', "",
                                   [TestWay('vt',
                                            '突然说出, 冲动地说',
                                            'to utter abruptly and impulsively',
                                            ['blurt out the secret 脱口说出了秘密'],
                                            ['burst', 'bolt', 'ejaculate', 'cry out'],
                                            ['muffle', 'mute'])]),
                              Word('bluster', "",
                                   [TestWay('v',
                                            '狂妄自大地大声说',
                                            'to speak in a loudly arrogant or bullying manner',
                                            ['He was blustering alone in the meeting, which triggered wide dissatisfaction. 他一人在会议上夸夸其谈, 引得众人不满。'],
                                            ['roar', 'clamor', 'bluster', 'rattle'],
                                            ['whisper']),
                                    TestWay('n',
                                            '大声吹嘘或恐吓',
                                            'loudly boastful or threatening speech',
                                            synonyms = ['grandiloquence', 'braggadocio']),
                                    TestWay('n',
                                            '喧闹的状态',
                                            'a state of noisy, confused activity',
                                            ['a mayor who got things done without a lot of bluster 一个能把事情低调解决的市长'],
                                            ['disturbance', 'pandemonium', 'tumult', 'turmoil'],
                                            other_form = 'blustering adj. 大吵大闹的')])])

list3_unit5 = VocabularyList([Word('boggle', "",
                                   [TestWay('v',
                                            '因为怀疑、恐惧而犹豫',
                                            'to hesitate because of doubt, fear, or scruples',
                                            ['boggle at the dilemma 身处困境而犹豫不决'],
                                            ['hesitate', 'falter', 'waver']),
                                    TestWay('v',
                                            '笨拙地做',
                                            'to make or do (something) in a clumsy or unskillful way',
                                            ['She boggled her first effort to make Christmas cookies. 她第一次尝试圣诞蛋糕做得笨手笨脚'],
                                            ['botch', 'bungle'])]),
                              Word('boisterous', "",
                                   [TestWay('adj',
                                            '喧嚷的, 吵闹的',
                                            'noisily turbulent',
                                            ['a boisterous queue in front of the pavilion 场馆前喧闹的队伍', 'boisterous mirth 喧闹的欢笑'],
                                            ['rowdy', 'vociferous', 'blatant', 'clamorous', 'raucous', 'rambunctious'],
                                            ['quiet', 'sedate'],
                                            'boisterousness n. 喧闹')]),
                              Word('bolster', "",
                                   [TestWay('n./v',
                                            '支持',
                                            'a structural part designed to eliminate friction or provide support or bearing',
                                            ['pillows that bolster the building 支撑房屋的柱子'],
                                            ['brace', 'buttress', 'bear', 'sustain', 'undergird', 'underpin', 'uphold', 'prop up']),
                                    TestWay('v',
                                            '鼓励, 使有精力',
                                            'to give a boost to',
                                            ['news that bolsters the morale of the troops 鼓舞军队士气的消息'],
                                            ['buoy', 'reinforce'],
                                            ['dampen'])]),
                              Word('bombast', "",
                                   [TestWay('n',
                                            '夸大的言辞',
                                            'grandiloquent, pompous speech or writing',
                                            ['Their eloquence is all bombast. 他们的雄辩是虚张声势'],
                                            ['braggadocio', 'grandiloquence', 'exaggeration'],
                                            ['understatement'],
                                            'bombastic adj. 夸大的')]),
                              Word('bonhomie', "",
                                   [TestWay('n',
                                            '温和, 和蔼',
                                            'a pleasant and affable disposition; geniality',
                                            synonyms = ['affability', 'amiability', 'geniality'],
                                            other_form = 'bonhomous adj. 和蔼的')]),
                              Word('boo', "",
                                   [TestWay('n./v',
                                            '嘘(以表示不满或嘲笑)',
                                            'a sound uttered to show contempt, scorn, or disapproval',
                                            ['boo the actor off the stage 把演员嘘下舞台'],
                                            ['jeer', 'scorn'],
                                            ['applaud'])]),
                              Word('boon', "",
                                   [TestWay('n',
                                            '恩惠, 福利',
                                            'benefit, favor',
                                            ['The new solar battery booster is a boon for photographers. 这个光伏充电器是摄影家的福音'],
                                            ['gift', 'benevolence', 'present', 'windfall'],
                                            ['misfortune', 'scourge']),
                                    TestWay('adj',
                                            '喜欢集体行动的',
                                            'likely to seek or enjoy the company of others',
                                            synonyms = ['convivial', 'extroverted', 'gregarious', 'social', 'outgoing'],
                                            antonyms = ['reclusive'])]),
                              Word('boor', "",
                                   [TestWay('n',
                                            '粗鲁的人, 不敏感的人',
                                            'a rude or insensitive person',
                                            ['acting like boor 表现得很粗鲁'],
                                            ['peasant', 'barbarian', 'buffoon'],
                                            ['sentimentalist'])]),
                              Word('bootless', "",
                                   [TestWay('adj',
                                            '无用的',
                                            'useless, unprofitable, futile',
                                            ['The meeting turns out to be a bootless attempt. 这个会议被证明是一次徒劳的尝试'],
                                            ['barren', 'ineffective', 'futile', 'abortive', 'fruitless', 'vain'],
                                            ['worthy', 'virtuous'])]),
                              Word('bound', "",
                                   [TestWay('n',
                                            '界限',
                                            'a real or imaginary point beyond which a person or thing cannot go',
                                            ['The language in the novel really is beyond the bounds of decency. 这本小说的语言实在太不得体了'],
                                            ['environs', 'limits', 'confines', 'perimeter'],
                                            ['unrestrainedness']),
                                    TestWay('vt',
                                            '给...设置限制',
                                            'to set limits or bounds to',
                                            ['The country is bounded by river. 这个国家的领土以河水为界'],
                                            ['limit', 'demarcate', 'delimit'],
                                            ['enfranchise', 'free', 'liberate']),
                                    TestWay('adj',
                                            '投入的, 坚定的',
                                            'fully committed to achieving a goal',
                                            ['I am bound and determined to write a novel before I turn 30. 我下定决心在30岁之前要写本小说'],
                                            ['resolute', 'determined', 'single-minded', 'bent on'],
                                            ['faltering', 'hesitant', 'vacillating', 'wavering', 'weak-kneed'],
                                            'boundless adj. 无边无际、无约束的')])])

list3_unit6 = VocabularyList([Word('boycott', "",
                                   [TestWay('vt',
                                            '联合抵制, 拒绝参与',
                                            'to engage in a concerted refusal to have dealings with (as a person, store, or organization) usually to express disapproval or to force acceptance of certain conditions',
                                            ['This brand is being boycotted for damaging environment. 因为破坏环境, 这个品牌正在被抵制'],
                                            ['refuse'],
                                            ['patronize'])]),
                              Word('bracing', "",
                                   [TestWay('adj',
                                            '令人振奋的, 给人带来活力的',
                                            'giving strength, vigor, or freshness',
                                            ['a bracing news from the frontline 来自前线的振奋人心的消息'],
                                            ['invigorating', 'rejuvenating', 'reviving', 'stimulating'],
                                            ['vapid'],
                                            'brace v. 支持, 使充满活力')]),
                              Word('brake', "",
                                   [TestWay('v',
                                            '刹车',
                                            'to cause to move or proceed at a less rapid pace',
                                            ['A seagull swooped down in front of her car, causing her to slam on the brakes. 一只海鸥飞到车窗前, 她猛踩刹车。'],
                                            ['decelerate', 'retard', 'slacken'],
                                            ['accelerate', 'hasten', 'rush', 'speed up'])]),
                              Word('brash', "",
                                   [TestWay('adj',
                                            '愚勇的, 鲁莽的',
                                            'foolishly adventurous or bold',
                                            ['that brash motorcyclist likes to show off by riding on only one wheel 那个鲁莽的摩托车手喜欢炫耀单轮骑车'],
                                            ['audacious', 'brassy', 'daredevil', 'madcap', 'reckless', 'temerarious'],
                                            ['circumspect', 'guarded', 'heedful', 'prudent', 'wary']),
                                    TestWay('adj',
                                            '缺乏判断力的, 不明智的',
                                            ' showing poor judgment especially in personal relationships or social situations',
                                            ["He was reprimanded for his brash comments to the media about the team's coaching staff. 他因对媒体说了一些有关教练组的不明智的评论被指责"],
                                            ['imprudent', 'injudicious', 'tactless', 'undiplomatic'],
                                            ['advisable', 'discreet', 'tactful'])]),
                              Word('brassy', "",
                                   [TestWay('adj',
                                            '厚脸皮的, 不知羞耻的',
                                            'displaying or marked by rude boldness',
                                            ['brassy reporters 厚颜无耻的记者'],
                                            ['audacious', 'bold-faced', 'brazen', 'impertinent', 'impudent', 'insolent'],
                                            ['diffident', 'unassertive', 'retiring', 'timid']),
                                    TestWay('adj',
                                            '华而不实地炫耀的',
                                            'cheap and showy; flashy',
                                            antonyms = ['furtive'])]),
                              Word('bravado', "",
                                   [TestWay('n',
                                            '假装勇敢',
                                            'a pretense of bravery',
                                            ['I remembered his youthful bravado. 我还记得他的年少鲁莽。']),
                                    TestWay('n',
                                            '虚张声势',
                                            'blustering swaggering conduct',
                                            [' strove to prevent our courage from turning into bravado 努力阻止我们的勇气蜕变成虚张声势'])]),
                              Word('bravura', "",
                                   [TestWay('adj./n',
                                            '优秀演技',
                                            'brilliant technique or style in performance',
                                            ['a truly bravura performance of the ballet 一场极其精彩的芭蕾舞演出'],
                                            ['adroit', 'artful', 'dexterous', 'masterful', 'virtuoso'],
                                            ['amateur', 'artless', 'unprofessional', 'unskillful'])]),
                              Word('brazen', "",
                                   [TestWay('adj',
                                            '蛮横大胆的, 厚颜无耻的',
                                            'marked by contemptuous boldness',
                                            ['a brazen disregard for the rules 蛮横大胆的对规则漠视'],
                                            ['bold-faced', 'impertinent', 'impudent', 'insolent'],
                                            ['modest', 'self-effacing', 'diffident', 'retiring', 'timid']),
                                    TestWay('v',
                                            '大胆自信地去面对或从事',
                                            'to face or undergo with bold self-assurance',
                                            ['brazened out the crisis 沉着面对危机', 'Some people prefer to brazen a thing out rather than admit defeat. 有的人不愿承认失败, 而是宁肯厚着脸皮干下去。'],
                                            ['confront', 'outface', 'defy'],
                                            ['dodge', 'duck', 'shirk', 'sidestep'])]),
                              Word('breach', "",
                                   [TestWay('n',
                                            '对伦理、法律准则的破坏',
                                            'a breaking of a moral or legal code',
                                            ["cheating on the exam was a serious breach of the military academy's honor code 考试作弊是对军校荣誉准则的严重破坏"],
                                            ['malefaction', 'transgression', 'trespass', 'violation', 'wrongdoing']),
                                    TestWay('v',
                                            '违背',
                                            'to fail to keep',
                                            ['a builder being sued by a homeowner for breaching a contract 建筑商因违约被房主起诉'],
                                            ['contravene', 'fracture', 'infringe', 'transgress'],
                                            ['obey', 'observe', 'comply with', 'conform to'])]),
                              Word('brevity', "",
                                   [TestWay('n',
                                            '简短, 简洁',
                                            'shortness of duration',
                                            ['the best quality a graduation speech can have is brevity 好的毕业演讲必须简洁'],
                                            ['briefness', 'conciseness', 'shortness'],
                                            ['lengthiness']),
                                    TestWay('n',
                                            '精炼',
                                            'the quality or state of being marked by or using only few words to convey much meaning',
                                            ["If brevity is the soul of wit, then that speech wasn't at all witty. 如果说精炼是智慧的灵魂, 那么演讲毫无智慧可言"],
                                            ['conciseness', 'pithiness', 'sententiousness', 'terseness'],
                                            ['diffuseness', 'long-windedness', 'prolixity', 'verbosity', 'wordiness'])])])

list3_unit7 = VocabularyList([Word('bribe', "",
                                   [TestWay('v',
                                            '贿赂, 收买',
                                            "to give something, such as money or a favor, offered or given to a person in a position of trust to influence that person's views or conduct",
                                            ['They bribed him to keep quiet about the incident. 他们收买他, 希望其保持缄默。'],
                                            ['corrupt', 'pay off', 'square'])]),
                              Word('bridle', "",
                                   [TestWay('v',
                                            '限制',
                                            'to keep from exceeding a desirable degree or level (as of expression)',
                                            ['try to bridle your criticism next time so that it is helpful and not hurtful 下回控制好批评的语气, 让其既顺耳又有益'],
                                            ['check', 'contain', 'curb', 'constrain', 'inhibit', 'regulate', 'restrain', 'tame', 'rein in'])]),
                              Word('brisk', "",
                                   [TestWay('adj',
                                            '充满生机, 有活力的',
                                            'marked by much life, movement, or activity',
                                            ['brisk and concise response 轻快而简洁的回答'],
                                            ['animated', 'bouncing', 'bustling', 'frisky', 'kinetic', 'sprightly', 'vibrant'],
                                            ['lackadaisical', 'languid', 'leaden', 'dead', 'inactive', 'lifeless']),
                                    TestWay('adj',
                                            '刻薄的, 言辞或方式尖刻辛辣的',
                                            'keen or sharp in speech or manner',
                                            ['a brisk greeting 尖刻的祝贺'])]),
                              Word('bristle', "",
                                   [TestWay('v',
                                            '怒不可遏, 咆哮',
                                            "to express one's anger usually violently",
                                            ['bristle at the suggestion of gay marriage 对同性婚姻怒不可遏'],
                                            ['bluster', 'fulminate', 'rampage', 'fume', 'storm'],
                                            ['cower']),
                                    TestWay('v',
                                            '供应充足',
                                            'to be copiously supplied',
                                            ['starting a new life in New York city bristling with possibilities 在有着无限机会的纽约开始新生活'],
                                            ['brim', 'overflow', 'swarm', 'teem'])]),
                              Word('brittle', "",
                                   [TestWay('adj',
                                            '易碎的, 脆弱的, 易坏的',
                                            'easily broken, cracked, or snapped',
                                            ['as brittle as glass 像玻璃一样脆弱'],
                                            ['crispy', 'crumbly', 'flaky', 'friable']),
                                    TestWay('adj',
                                            '不热心的, 不真心的',
                                            'lacking in friendliness or warmth of feeling',
                                            ['a brittle apology that was anything but heartfelt 一个毫不真诚的道歉'],
                                            ['chilly', 'frigid', 'frosty', 'glacial', 'unfriendly', 'unsympathetic'],
                                            ['cordial', 'genial', 'warmhearted'])]),
                              Word('broach', "",
                                   [TestWay('v',
                                            '开启, 启封',
                                            'to open for the first time',
                                            ['broach a keg of beer 开一小桶酒'],
                                            ['break'],
                                            ['close off']),
                                    TestWay('v',
                                            '提出讨论',
                                            'to present or bring forward for discussion',
                                            ["broached the topic of plans for next year's parade 将明年的游行活动计划摆上讨论日程"],
                                            ['moot', 'place', 'raise', 'bring up'])]),
                              Word('bromide', "",
                                   [TestWay('n',
                                            '陈词滥调',
                                            'a commonplace or hackneyed statement or notion',
                                            ['a newspaper editorial offering the timeworn bromide that people should settle their differences peacefully 报纸编辑又拿出那一套呼吁和平解决纷争的陈词滥调'],
                                            ['banality', 'cliché', 'platitude', 'homily', 'truism', 'chestnut', 'shibboleth'])]),
                              Word('brook', "",
                                   [TestWay('v',
                                            '忍受, 容许',
                                            'to stand for, tolerate',
                                            ['brook no inference with his plans 不能容忍别人对于他计划的干涉'],
                                            ['abide', 'countenance', 'endure', 'stomach']),
                                    TestWay('n',
                                            '小溪流',
                                            'a natural stream of water normally smaller than and often tributary to a river: creek',
                                            ['there are tiny fish and frogs in that brook 那条小溪里有小鱼还有小青蛙'],
                                            ['creek', 'rivulet'])]),
                              Word('browbeat', "",
                                   [TestWay('vt',
                                            '恐吓',
                                            'to intimidate by a stern manner or arrogant speech: bully',
                                            ['They would often browbeat the younger child until he cried. 他们总是把小朋友欺负到哭为止。'],
                                            ['blackjack', 'bulldoze', 'bully', 'cow', 'hector', 'intimidate'],
                                            [])]),
                              Word('bruit', "",
                                   [TestWay('vt',
                                            '(未经证实地)散播消息',
                                            ' to make (as a piece of information) the subject of common talk without any authority or confirmation of accuracy',
                                            ['It’s been bruited that... 到处传播……'],
                                            ['circulate', 'whisper', 'noise about'],
                                            ['keep secret'])])])
list3_unit8 = VocabularyList([Word('buck', "",
                                   [TestWay('v',
                                            '阻止, 反对',
                                            'to refuse assent, to refuse to give in to',
                                            ['buck the system 不遵守制度'],
                                            ['defy', 'fight', 'oppose', 'repel', 'withstand'],
                                            ['assent to', 'bow to', 'submit to', 'succumb to', 'surrender to', 'yield to']),
                                    TestWay('v',
                                            '转移, 交接',
                                            'to shift possession of (something) from one person to another',
                                            ['buck each box to the next person in line 将每一个盒子传给队伍中的后一人'],
                                            ['transfer', 'hand over'])]),
                              Word('budge', "",
                                   [TestWay('vi.',
                                            '改变立场或态度',
                                            'to alter a position or attitude',
                                            ['Nothingwouldbudgehim. 没有什么可以改变他的主意。']),
                                    TestWay('v',
                                            '停止抵抗, 屈服',
                                            'to cease resistance (as to another’s arguments, demands, or control)',
                                            ['despite hours of intense pressure, she refused to budge from her position 尽管被连续施压几小时, 她仍旧不肯改变立场'],
                                            ['concede', 'relent', 'submit', 'succumb', 'surrender'],
                                            ['resist'])]),
                              Word('bulge', "",
                                   [TestWay('n',
                                            '凸起',
                                            'a protuberant or swollen part or place',
                                            ['bulging eyes 暴鱼眼'],
                                            ['convexity', 'projection', 'protrusion', 'protuberance', 'swell'],
                                            ['depressed region', 'cavity', 'dent', 'indent', 'recess', 'pit']),
                                    TestWay('n',
                                            '比赛中的优势地位',
                                            'the more favorable condition or position in a competition',
                                            ['somehow she got the bulge on him in the race for the statehouse 她在州议员竞选中领先了他'],
                                            ['high ground', 'inside track', 'upper hand', 'whip hand'],
                                            ['disadvantage', 'drawback', 'handicap', 'liability']),
                                    TestWay('n',
                                            '暴涨, 突增, 在数目或数量上突然而且是临时性的增加',
                                            'a sudden, usually temporary increase in number or quantity',
                                            ['Thebabyboomcreatedabulgeinschoolenrollment. 生育高峰造成学校入学人数的暴涨。']),
                                    TestWay('v',
                                            '充满',
                                            'to be copiously supplied',
                                            ['this guidebook to San Francisco positively bulges with useful information 这本对旧金山的指南包含了很多有用信息'],
                                            ['brim', 'bristle', 'overflow', 'swarm', 'teem'])]),
                              Word('bully', "",
                                   [TestWay('n',
                                            '欺凌弱小者',
                                            'a person who habitually treats others in an overbearing or intimidating manner',
                                            ['they had to deal with the local bullies 他们要对付当地恶霸'],
                                            ['bullyboy', 'hector', 'intimidator'],
                                            ['underdog']),
                                    TestWay('adj',
                                            '最好的, 最棒的',
                                            'of the very best kind',
                                            ["that's a bully idea for reviving the town's retail center 真是个重整镇上零售中心的好主意"],
                                            ['awesome', 'fabulous', 'fantastic', 'superb', 'marvelous', 'unsurpassed', 'excellent'])]),
                              Word('bumptious', "",
                                   [TestWay('adj',
                                            '专横傲慢的, 自以为是的',
                                            'having a feeling of superiority that shows itself in an overbearing attitude',
                                            ['a bumptious young man whose family wealth gave him a sense of entitlement 一个傲慢的富二代', 'be bumptious over one’s inferiors 对下级态度傲慢'],
                                            ['assumptive', 'haughty', 'imperious', 'overweeing', 'peremptory', 'pompous', 'presuming', 'presumptuous', 'self-assertive', 'supercilious'],
                                            ['humble', 'modest', 'unarrogant', 'unpretentious'])]),
                              Word('bungle', "",
                                   [TestWay('v',
                                            '办糟, 失败',
                                            'to act or work clumsily and awkwardly',
                                            ['bungle a job 搞砸了一项工作'],
                                            ['boggle', 'bumble', 'fumble', 'mess up', 'screw up'],
                                            ['bring off'])]),
                              Word('buoy', "",
                                   [TestWay('vt',
                                            '使充满勇气和力量, 使振作',
                                            'to fill with courage or strength of purpose',
                                            ['the sudden improvement in his health buoyed him up 身体的突然好转让他很振奋'],
                                            ['embolden', 'hearten', 'inspire', 'bear up', 'buck up'],
                                            ['daunt', 'discourage', 'dishearten', 'dispirit'])]),
                              Word('buoyant', "",
                                   [TestWay('adj',
                                            '有浮力的',
                                            'capable of floating',
                                            ['a buoyant balloon 一个能浮起来的气球'],
                                            antonyms = ['leaden']),
                                    TestWay('adj',
                                            '心情好的',
                                            'having or showing a good mood or disposition',
                                            ['in a buoyant mood 轻松快乐的心情'],
                                            ['blithe', 'chipper', 'eupeptic', 'lightsome', 'upbeat', 'winsome', 'effervescent'],
                                            ['dour', 'gloomy', 'morose', 'saturnine', 'sullen'])]),
                              Word('burgeon', "",
                                   [TestWay('v',
                                            '迅速成长扩大, 蓬勃发展',
                                            'to grow and expand rapidly; flourish',
                                            ['My confidence began to burgeon. 我的信心开始迅速增强。'],
                                            ['accelerate', 'accumulate', 'balloon', 'boom', 'build up', 'escalate', 'mount', 'multiply', 'mushroom', 'proliferate', 'roll up', 'snowball', 'wax', 'flourish', 'prosper'],
                                            ['wane', 'wither', 'waste away', 'subside', 'subdue'])]),
                              Word('burlesque', "",
                                   [TestWay('v',
                                            '夸张滑稽地模仿以嘲弄他人的文学艺术作品, 恶搞',
                                            'to copy or exaggerate (someone or something) in order to make fun of',
                                            ["burlesquing the teacher's nervous tic isn't very nice 恶搞老师紧张的痉挛不是好的行为"],
                                            ['caricature', 'imitate', 'mock', 'parody', 'spoof', 'travesty'])])])
list3_unit9 = VocabularyList([Word('burnish', "",
                                   [TestWay('v',
                                            '擦亮, 磨光',
                                            'to make smooth or glossy usually by repeatedly applying surface pressure',
                                            ['burnish the knife 磨光刀'],
                                            ['buff', 'polish', 'furbish', 'grind', 'smoothen'])]),
                              Word('buttress', "",
                                   [TestWay('n',
                                            '扶墙',
                                            'a projecting structure for supporting or giving stability to a wall or building',
                                            ['anchor', 'mainstay', 'pillar', 'reliance', 'standby']),
                                    TestWay('vt',
                                            '提供支撑的证据或者信息',
                                            'to provide evidence or information for (as a claim or idea)',
                                            ["a mass of circumstantial evidence buttresses the prosecutor's case 大量支持起诉人案件的证据"],
                                            ['bolster', 'corroborate', 'reinforce', 'substantiate', 'shore up'],
                                            ['contravene', 'challenge'])]),
                              Word('byzantine', "",
                                   [TestWay('adj',
                                            '错综复杂的',
                                            'complicated or secretive, having many parts or aspects that are usually interrelated',
                                            ['a bill to simplify the byzantine tax structure 一项试图简化繁琐税收制度的提案'],
                                            ['convoluted', 'intricate', 'involved', 'labyrinthine', 'sophisticated', 'tangled'],
                                            ['straightforward', 'plain', 'simple', 'uncomplicated'])]),
                              Word('cache', "",
                                   [TestWay('n',
                                            '囤货, 藏货',
                                            'a supply stored up and often hidden away',
                                            ['maintain a cache of food in case of emergencies 保存着食物的隐藏处以防万一'],
                                            ['stash', 'stockpile', 'store', 'deposit', 'hoard', 'reserve']),
                                    TestWay('v',
                                            '隐藏',
                                            'to put into a hiding place',
                                            ['cached the fugitive slaves in their cellar until they could make their way to Canada 将奴隶们藏匿在房间的地下室直到他们能够顺利逃去加拿大'],
                                            ['conceal', 'ensconce', 'secrete', 'squirrel away'],
                                            ['display', 'exhibit'])]),
                              Word('cachet', "",
                                   [TestWay('n',
                                            '同意',
                                            'an indication of approval carrying great prestige',
                                            ['A Mercedes carries a certain cachet. 每一辆奔驰都有认证标志。']),
                                    TestWay('n',
                                            '声望',
                                            'prestige',
                                            ['being rich...doesn’t have the cachet it used to 富甲一方再也不像过去拥有那么高的声望了'])]),
                              Word('cacophony', "",
                                   [TestWay('n',
                                            '刺耳的声音',
                                            'loud, confused, and usually inharmonious sound',
                                            ['the cacophony of a pet store full of animals 宠物商店里各种动物叽叽呱呱的声音'],
                                            ['blare', 'bluster', 'clamor', 'decibel', 'din', 'discordance', 'racket'],
                                            ['quiet', 'silence', 'still', 'stillness'])]),
                              Word('cadge', "",
                                   [TestWay('v',
                                            '乞讨, 乞求',
                                            'beg, sponge',
                                            ['cadgeafreecupofcoffee 讨到一杯免费的咖啡'],
                                            antonyms = ['earn'])]),
                              Word('cajole', "",
                                   [TestWay('v',
                                            '哄骗',
                                            'to urge with gentle and repeated appeals, teasing, or flattery; wheedle',
                                            ['cajoled her into doing his laundry for him 哄骗她帮他洗衣服'],
                                            ['blandish', 'blarney', 'palaver', 'wheedle', 'soft-soap', 'sweet-talk'])]),
                              Word('calcify', "",
                                   [TestWay('vt',
                                            '使僵化',
                                            'to make inflexible or unchangeable',
                                            ['a leg that calcified 一条麻木僵直的腿'],
                                            ['harden', 'obdurate', 'ossify'],
                                            ['makemalleable', 'makepliant', 'makemoreflexible'])]),
                              Word('calibrate', "",
                                   [TestWay('vt',
                                            '调整, 标准化',
                                            'to standardize (as a measuring instrument) by determining the deviation from a standard so as to ascertain the proper correction factors',
                                            ['calibrate the polling procedures to ensure objectivity 为保证客观性而使投票过程标准化'],
                                            synonyms = ['unstandardize']),
                                    TestWay('vt',
                                            '(根据标准)精确测量',
                                            'to measure precisely especially: to measure against a standard')])])
list3_unit10 = VocabularyList([Word('calligraphy', "",
                                   [TestWay('n',
                                            '(优美的)书法',
                                            'artistic, stylized, or elegant handwriting or lettering',
                                            ['she specializes in scrollwork with beautiful calligraphy 她很擅长花体字'],
                                            ['longhand', 'manuscript', 'penmanship', 'script'])]),
                              Word('callous', "",
                                   [TestWay('adj',
                                            '无同情心的, 冷漠的',
                                            'emotionally hardened; unfeeling',
                                            ['a callous indifference to the suffering of others 对他人的痛苦的漠不关心'],
                                            ['affectless', 'uncharitable', 'unsparing', 'remorseless', 'indurate', 'ruthless'],
                                            ['sympathetic', 'compassionate', 'merciful', 'tender', 'warmhearted'])]),
                              Word('callow', "",
                                   [TestWay('adj',
                                            '缺乏老练、不成熟的',
                                            'lacking in adult experience or maturity',
                                            ['callow young man 未经世事的年轻人'],
                                            ['green', 'immature', 'inexperienced', 'juvenile', 'unfledged', 'unripened', 'puerile'],
                                            ['adult', 'experienced', 'grown-up', 'mature', 'ripe'])]),
                              Word('calumniate', "",
                                   [TestWay('v',
                                            '诽谤, 造谣, 中伤',
                                            'to utter maliciously false statements, charges, or imputations about',
                                            synonyms = ['asperse', 'blacken', 'defame', 'libel', 'malign', 'smear', 'traduce', 'vilify'],
                                            antonyms = ['vindicate'],
                                            other_form = "calumnious adj. 造谣的 flattering【反】谄媚的; calumny n. 诽谤、中伤: a false statement maliciously made to injure another's reputation【反】approbation 嘉许")]),
                              Word('camaraderie', "",
                                   [TestWay('n',
                                            '战友情, 同志情',
                                            'a spirit of friendly good-fellowship',
                                            ['There is great camaraderie among the teammates. 组员之间有着深厚的情谊。'],
                                            ['brotherhood', 'comradeship', 'fellowship'],
                                            ['enmity'])]),
                              Word('cameo', "",
                                   [TestWay('n',
                                            '栩栩如生的描绘: 一种简洁的、生动的描述或刻画',
                                            'a brief, vivid portrayal or depiction',
                                            ['a literary cameo 文学描写']), 
                                    TestWay('v',
                                            '客串',
                                            'to make a brief but dramatic appearance, as in a film',
                                            ['She cameoed as Anne Boleyn in A Man for All Seasons. 在所有季节的人中她客串安妮·波列思。'])]),
                              Word('camouflage', "",
                                   [TestWay('n',
                                            '伪装',
                                            'behavior or artifice designed to deceive or hide',
                                            ['the soldiers must wear protective jungle camouflage while on patrol 士兵们在巡逻的时候必须穿上迷彩服来保护自身安全'],
                                            ['costume', 'guise', 'cloak', 'dress up'],
                                            ['unmask'])]),
                              Word('canard', "",
                                   [TestWay('n',
                                            '谣传, 误传',
                                            'an unfounded or false, deliberately misleading story',
                                            ["it's a popular canard that the actress died under scandalous circumstances 有一种广泛的说法声称女演员死于绯闻的压力"],
                                            ['story', 'whisper'])]),
                              Word('candor', "",
                                   [TestWay('n',
                                            '坦白, 直率, 诚挚',
                                            'unreserved, honest, or sincere expression',
                                            ['the members of the rock band speak with candor about their recent squabbling 摇滚乐队成员对于他们最近的内讧直言不讳'],
                                            ['bluntness', 'forthrightness', 'frankness', 'unreservedness', 'straightforwardness'],
                                            ['artifice', 'mendacity', 'dissembling', 'dissimulation', 'indirection'])]),
                              Word('canon', "",
                                   [TestWay('n',
                                            '正教, 标准',
                                            'a basis for judgment; a standard or criterion',
                                            ['the canons of polite society 文明社会的法规'],
                                            ['dogma'])])])

LIST3 = VocabularyList(list3_unit1.words+list3_unit2.words+list3_unit3.words+list3_unit4.words+list3_unit5.words+list3_unit6.words+list3_unit7.words+list3_unit8.words+list3_unit9.words+list3_unit10.words)

