#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list6_unit1 = VocabularyList([Word('creep', "",
                                   [TestWay('vi./n',
                                            '缓慢地行进',
                                            'to go very slowly',
                                            ['creeping through the crowd 在人潮中缓慢前行'],
                                            ['drag', 'loiter', 'tarry'],
                                            ['scurry', 'run']),
                                    TestWay('vi',
                                            '匍匐前进',
                                            'to move slowly with the body close to the ground',
                                            ['The kitten crept silently across the floor before suddenly pouncing on the mouse. 小猫静静地匍匐穿过地板, 然后突然向老鼠发起猛扑'],
                                            ['crawl', 'grovel', 'slide', 'slither'],
                                            ['swagger'])]),
                              Word('crescendo', "",
                                   [TestWay('n./v',
                                            '(声音)渐强',
                                            'a gradual increase in volume of a musical passage',
                                            ['The movement begins with a crescendo of a clarinet. 乐章伴随着渐强的单簧管奏响'],
                                            antonyms = ['decrescendo', '(声音)渐弱']),
                                    TestWay('n',
                                            '(渐强之后到达的)顶峰',
                                            'the peak of a gradual increase',
                                            ['complaints about stifling smog conditions reach a crescendo 对于让人窒息的烟雾的抱怨到达了顶峰'],
                                            ['apex', 'acme', 'apogee', 'climax', 'peak', 'pinnacle', 'summit', 'zenith'],
                                            ['nadir'])]),
                              Word('crest', "",
                                   [TestWay('n',
                                            '顶部, 浪尖',
                                            'the top, as of a hill or wave',
                                            ['on the crest of a wave 如日中天, 非常成功'],
                                            ['apex', 'acme', 'apogee', 'climax', 'peak', 'pinnacle', 'summit', 'zenith'],
                                            ['bottom'])]),
                              Word('crestfallen', "",
                                   [TestWay('adj',
                                            '垂头丧气的, 沮丧的',
                                            'dispirited and depressed; dejected',
                                            ['be crestfallen at the failure 因失败而垂头丧气'],
                                            ['downcast', 'dispirited', 'low', 'gloomy', 'melancholic', 'sorrowful', 'woeful'],
                                            ['elated', 'buoyant', 'excited', 'exhilarated', 'exultant'])]),
                              Word('cronyism', "",
                                   [TestWay('n',
                                            '任人唯亲, 对好朋友的偏袒',
                                            'favoritism shown to old friends without regard for their qualifications',
                                            ['officials practicing cronyism 任人唯亲的官员'],
                                            ['favoritism'])]),
                              Word('crook', "",
                                   [TestWay('v',
                                            '使弯曲',
                                            'to cause to turn away from a straight line',
                                            ['crook your finger to pull the trigger 弯曲你的手指来扣动扳机'],
                                            ['arch', 'bow', 'crook', 'curve', 'hook', 'swerve'],
                                            ['straighten', 'unbend', 'uncurl'])]),
                              Word('croon', "",
                                   [TestWay('v',
                                            '低声歌唱或说话',
                                            'to sing or speak in a gentle murmuring manner',
                                            ['croon mellow tunes 低声唱柔和的调子'],
                                            ['whisper', 'grumble', 'mumble', 'murmur'],
                                            ['shout', 'yell'])]),
                              Word('crouch', "",
                                   [TestWay('v',
                                            '蹲伏',
                                            'to lower the body stance especially by bending the legs',
                                            ['crouched behind a rock and watched vigilantly 蹲伏石头后紧惕地观察'],
                                            ['huddle', 'squat'],
                                            ['arise', 'stand'])]),
                              Word('crucial', "",
                                   [TestWay('adj',
                                            '非常重要的, 决定性的',
                                            'extremely significant or important',
                                            ['a crucial step in his professional career 他职业生涯中具有决定性的一步'],
                                            ['critical', 'decisive', 'key', 'pivotal', 'vital'],
                                            ['inconsequential', 'insignificant', 'trivial'])]),
                              Word('crumple', "",
                                   [TestWay('',
                                            '',
                                            'to press, bend, or crush out of shape',
                                            ['crumple a piece of paper 弄皱一张纸'],
                                            ['rumple', 'crimple', 'crease', 'fold', 'wrinkle'],
                                            ['smooth']),
                                    TestWay('',
                                            '',
                                            'to fall down or in as a result of physical pressure',
                                            ['The box crumpled when I accidentally dropped a brick on it. 我不小心扔了块石头在箱子上, 它就倒塌了'],
                                            ['collapse', 'founder', 'implode', 'tumble', 'yield'])])])

list6_unit2 = VocabularyList([Word('crutch', "",
                                   [TestWay('n./v',
                                            '支撑, 支柱',
                                            'something that supports or sustains',
                                            ['a crutch for local economy 当地的经济支柱'],
                                            ['brace', 'buttress', 'column', 'stay', 'support', 'underpinning', 'underpropping'])]),
                              Word('crux', "",
                                   [TestWay('n',
                                            '中心, 关键点',
                                            'the basic, central, or critical point or feature',
                                            ['the crux of the problem 问题的核心所在'],
                                            ['core', 'substance', 'kernel', 'gist', 'pivot'],
                                            ['trifle', 'triviality'])]),
                              Word('cryptic', "",
                                   [TestWay('adj',
                                            '秘密的',
                                            'secret or occult',
                                            ['cryptic message 秘密的信息'],
                                            ['covert', 'furtive', 'secret', 'stealthy'],
                                            ['public', 'open']),
                                    TestWay('adj',
                                            '含义模糊的',
                                            'having or seeming to have a hidden or ambiguous meaning',
                                            ['The senator made some cryptic explanations about the military operations. 参议员就军事行动给出了含糊其辞的解释'],
                                            ['ambiguous', 'equivocal', 'nebulous', 'obscure', 'unclear', 'vague'],
                                            ['clear', 'explicit', 'obvious', 'plain']),
                                    TestWay('adj',
                                            '超出理解能力的',
                                            "being beyond one's powers to know, understand, or explain",
                                            ['puzzled by the cryptic e-mail message left on his computer 被他电脑里让人费解的电子邮件而迷惑'],
                                            ['arcane', 'enigmatic', 'impenetrable', 'inscrutable', 'mystic', 'occult', 'uncanny'],
                                            ['comprehendible', 'understandable'])]),
                              Word('culpable', "",
                                   [TestWay('adj',
                                            '该受谴责的, 有罪的',
                                            'deserving of blame or censure as being wrong, evil, improper, or injurious',
                                            ['culpable behaviors 值得谴责的行为'],
                                            ['blameworthy', 'censurable', 'guilty', 'reprehensible', 'sinful', 'reproachable'],
                                            ['inculpable', 'innocent'],
                                            'culpability n. 有罪')]),
                              Word('cultivate', "",
                                   [TestWay('v',
                                            '提升',
                                            'to improve by labor, care, or study',
                                            ['cultivate the mind 开化心智'],
                                            ['educate', 'instruct', 'illuminate', 'nurse'],
                                            ['degrade', 'deteriorate', 'impair']),
                                    TestWay('v',
                                            '促进成长, 培养',
                                            'to promote the growth of (a biological culture)',
                                            ['cultivate vegetables 种植蔬菜'],
                                            ['grow', 'breed', 'produce', 'raise', 'develop', 'nurture'],
                                            ['balk', 'frustrate', 'thwart'],
                                            'cultivation n. 栽培')]),
                              Word('cumbersome', "",
                                   [TestWay('adj',
                                            '笨重的, 难处理的',
                                            'difficult to handle because of weight or bulk',
                                            ['a cumbersome piece of machinery'],
                                            ['unhandy', 'ponderous', 'heavy', 'unwieldy', 'onerous' ,'thorny'],
                                            ['light', 'weightless'])]),
                              Word('cunning', "",
                                   [TestWay('adj',
                                            '狡猾的',
                                            'marked by or given to artful subtlety and deceptiveness',
                                            ['cunning tactics 狡猾的战术'],
                                            ['artful', 'crafty', 'devious', 'foxy', 'sly', 'tricky', 'wily'],
                                            ['artless', 'naïve', 'unsophisticated']),
                                    TestWay('adj',
                                            '(手工)灵巧的',
                                            'skillful with the hands',
                                            ['Only the most cunning cabinetmaker could have crafted such a beautifully proportioned chest of drawers. 只有手工超凡的家具工才能打造出如此精致协调的衣柜'],
                                            ['clever', 'deft', 'handy'],
                                            ['heavy-handed', 'ham-handed']),
                                    TestWay('n',
                                            '欺诈, 欺骗',
                                            'the inclination or practice of misleading others through lies or trickery',
                                            ['used cunning and subterfuge to work her way up the corporate ladder 通过欺骗在公司中步步攀升'],
                                            ['artifice', 'deception', 'fraud'],
                                            ['ingenuousness', 'sincerity'])]),
                              Word('curmudgeon', "",
                                   [TestWay('n',
                                            '脾气坏的爱抱怨的人',
                                            'an irritable and complaining person',
                                            ['a terrible old curmudgeon 一个坏脾气老头'],
                                            ['crosspatch', 'fusser', 'griper', 'grouser', 'growler', 'grumbler', 'whiner'],
                                            ['agreeable person'])]),
                              Word('cursory', "",
                                   [TestWay('adj',
                                            '匆忙的, 不注意细节的',
                                            'acting or done with excessive or careless speed',
                                            ['a cursory glance at the headline 匆匆地瞥了一眼标题'],
                                            ['headlong', 'overhasty', 'pell-mell', 'precipitate', 'precipitous', 'rash'],
                                            ['fastidious', 'thorough', 'deliberate', 'unhurried', 'unrushed'])]),
                              Word('curt', "",
                                   [TestWay('adj',
                                            '简单粗暴的',
                                            'being or characterized by direct, brief, and potentially rude speech or manner',
                                            ['his curt reply 简单粗暴的'],
                                            ['abrupt', 'bluff', 'brusque', 'downright', 'unceremonious'],
                                            ['circuitous', 'mealymouthed']),
                                    TestWay('adj',
                                            '言简意赅的',
                                            'marked by the use of few words to convey much information or meaning',
                                            ['on a daily basis she e-mailed to her commanders curt reports on the situation 她每天向长官做简短汇报'],
                                            ['aphoristic', 'compendious', 'elliptical', 'laconic', 'pithy', 'sententious', 'succinct', 'terse'],
                                            ['diffuse', 'long-winded', 'prolix', 'verbose'])])])

list6_unit3 = VocabularyList([Word('curtail', "",
                                   [TestWay('vt',
                                            '缩短, 削减',
                                            'to make less in extent or duration',
                                            ['curtail your holiday 缩短你的假期'],
                                            ['abbreviate', 'abridge', 'syncopate', 'truncate', 'cut back'],
                                            ['elongate', 'protract', 'prolong', 'extend', 'lengthen'])]),
                              Word('cynic', "",
                                   [TestWay('n',
                                            '愤世嫉俗者',
                                            'a person who believes all people are motivated by selfishness',
                                            ['A cynic might think that the governor visited the hospital just to gain votes. 一个愤青认为州长去医院探视仅仅是为了拉票。'],
                                            ['misanthrope', 'naysayer', 'pessimist'])]),
                              Word('dabble', "",
                                   [TestWay('v',
                                            '浅尝辄止',
                                            'to work or involve oneself superficially or intermittently especially in a secondary interest',
                                            ['dabble in arts 对艺术稍有涉猎'],
                                            antonyms = ['dedicate', 'specialize'],
                                            other_form = "dabbler vi. 涉猎者, 浅尝辙止者: one not deeply engaged in or concerned with something 【例】He's not a dedicated musician, just a dabbler. 他并不是专门的音乐家, 只不过是个业馀爱好者 【反】specialist 专家")]),
                              Word('daft', "",
                                   [TestWay('adj',
                                            '神经错乱的',
                                            'having or showing a very abnormal or sick state of mind',
                                            ['The king was clearly daft, talking to trees and rocks. 国王俨然已经疯了, 对着树和石头说话。'],
                                            ['bedlam', 'demented', 'deranged', 'lunatic', 'psychotic', 'unbalanced', 'unsound'],
                                            ['balanced', 'sane']),
                                    TestWay('adj',
                                            '不明智的',
                                            'showing or marked by a lack of good sense or judgment',
                                            ['a daft plan, doomed to wretched failure and merciless ridicule 一个不明智的决定, 最终难逃悲催的结局和无情的嘲讽的下场'],
                                            ['fatuous', 'featherheaded', 'nonsensical', 'preposterous', 'senseless'],
                                            ['judicious', 'prudent', 'sagacious', 'sapient', 'wise'])]),
                              Word('dais', "",
                                   [TestWay('n',
                                            '主席台, 嘉宾席',
                                            'a raised platform, as in a lecture hall, for speakers or honored guests',
                                            ['the speaker took his place at the front of the dais 演讲者在主席台就坐'],
                                            ['podium', 'rostrum', 'tribune'])]),
                              Word('dally', "",
                                   [TestWay('vt',
                                            '虚度时光',
                                            'to spend time doing nothing',
                                            ["I kept dallying at my desk until I couldn't put off doing my work any longer. 我一直浪费时间直到作业不能再拖了。"],
                                            ['dawdle', 'loll', 'lounge', 'hang around']),
                                    TestWay('v',
                                            '玩乐',
                                            'to engage in activity for amusement',
                                            ['he spent his college years dallying, seemingly determined to acquire as little knowledge as possible 他在大学里面尽情玩乐, 不学习'],
                                            ['disport', 'frolic', 'recreate', 'rollick', 'sport']),
                                    TestWay('v',
                                            '慢吞吞, 磨磨蹭蹭',
                                            'to move or act slowly',
                                            ["don't dally on the way to the interview 别在去面试的路上磨磨蹭蹭"],
                                            ['crawl', 'creep', 'dillydally', 'drag', 'lag', 'linger', 'loiter', 'tarry'],
                                            ['dash', 'hasten', 'scoot', 'scurry'])]),
                              Word('damper', "",
                                   [TestWay('n',
                                            '抑制因素',
                                            'one that deadens, restrains, or depresses',
                                            ['Rain put a damper on our picnic plans. 下雨打破了我们的野餐计划。'],
                                            antonyms = ['ameliorator'])]),
                              Word('dandy', "",
                                   [TestWay('n',
                                            '纨绔子弟, 爱打扮的人',
                                            'a man who gives exaggerated attention to personal appearance',
                                            ['That was a dandy of a game. 那是纨绔子弟的游戏。'],
                                            ['fop', 'gallant']),
                                    TestWay('',
                                            '最佳最好的',
                                            'of the very best kind',
                                            ["that's a dandy new racing bike 真是辆最好的比赛用自行车"],
                                            ['awesome', 'fabulous', 'superb', 'sensational', 'splendid', 'unsurpassed'],
                                            ['atrocious', 'awful', 'execrable', 'lousy', 'pathetic', 'wretched'])]),
                              Word('dank', "",
                                   [TestWay('adj',
                                            '阴湿的',
                                            'slightly or moderately wet',
                                            ['vegetables tended to go bad quickly in the dank cellar 蔬菜在潮湿的地下室很容易变坏'],
                                            ['damp', 'wettish'])]),
                              Word('dapper', "",
                                   [TestWay('adj',
                                            '衣冠整洁的',
                                            'being strikingly neat and trim in style or appearance',
                                            ['The students all looked very dapper in their uniforms. 学生们穿着校服显得非常整洁。'],
                                            ['natty', 'sharp', 'snappy', 'spruce'],
                                            ['frowsy', 'unkempt', 'slovenly', 'unkempt'])])])

list6_unit4 = VocabularyList([Word('dappled', "",
                                   [TestWay('adj',
                                            '有斑点的, 花的',
                                            'marked with small spots or contrasting with the background; mottled, spotted',
                                            ['a dappled fawn 一只小花鹿'],
                                            ['blotchy', 'mottled', 'specked', 'piebald', 'splotched', 'stippled'],
                                            ['unspotted']),
                                    TestWay('adj.',
                                            '色彩斑斓的',
                                            'having blotches of two or more colors',
                                            ['a forest that was vibrant with the dappled foliage of autumn 充满秋天的生机、色彩斑斓的森林'],
                                            ['marbled', 'mottled', 'piebald', 'pinto', 'splotched', 'spotted'])]),
                              Word('daredevil', "",
                                   [TestWay('adj./n',
                                            '大胆鲁莽的(人)',
                                            'foolishly adventurous or bold',
                                            ['His daredevil stunts are sure to end in disaster someday. 玩火者必自焚。'],
                                            ['audacious', 'brash', 'madcap', 'overbold', 'reckless', 'temerarious'],
                                            ['circumspect', 'guarded', 'heedful', 'prudent', 'wary']),
                                    TestWay('adj',
                                            '不考虑后果的',
                                            'having or showing a lack of concern for the consequences of one’s actions',
                                            ['a daredevil driver who thinks that racing on city streets is a harmless game 不计后果的司机认为在大街上飙车对人无害'],
                                            ['foolhardy', 'irresponsible', 'harum-scarum'],
                                            ['responsible'])]),
                              Word('dart', "",
                                   [TestWay('vi',
                                            '突然移动',
                                            'to move suddenly and rapidly',
                                            ['The dog darted across the street. 狗飞奔过马路。'],
                                            ['flicker', 'flitter', 'flutter']),
                                    TestWay('n',
                                            '公开侮辱',
                                            "an act or expression showing scorn and usually intended to hurt another's feelings",
                                            ['The darts flew fast and furiously when the two former lovers bumped into each other at the party. 旧情人在party 上偶遇, 立马开始激烈的人身攻击。'],
                                            ['affront', 'barb', 'offense', 'sarcasm', 'slight', 'slur'])]),
                              Word('daunt', "",
                                   [TestWay('vt',
                                            '使胆怯, 吓倒',
                                            'to lessen the courage or confidence of',
                                            ['She was not at all daunted by the size of the problem. 她根本没有被问题的大小给吓倒。'],
                                            ['demoralize', 'dishearten', 'dismay', 'dispirit', 'frustrate', 'unnerve'],
                                            ['embolden', 'make resolute', 'hearten'],
                                            'dauntless undaunted a. 无畏的, 大胆的 【反】pusillanimous, trepid, craven, easily discouraged, meek, timorous 胆怯的')]),
                              Word('dawdle', "",
                                   [TestWay('v',
                                            '闲荡, 虚度光阴',
                                            'to spend time idly',
                                            ['dawdle the day away 闲荡一天'],
                                            ['bum', 'dally', 'loll', 'loaf', 'lounge', 'hang about', 'kick around'],
                                            ['hie']),
                                    TestWay('v',
                                            '拖拖拉拉',
                                            'to move or act slowly',
                                            ["If you continue to dawdle, we'll be late for sure. 你要是再拖拉, 我们铁定要迟到了。"],
                                            ['crawl', 'creep', 'dally', 'dillydally', 'lag', 'linger', 'loiter', 'tarry'],
                                            ['bolt', 'hasten', 'course', 'dash', 'speed', 'scurry'])]),
                              Word('deadpan', "",
                                   [TestWay('n',
                                            '不动情的言行举止, 无动于衷',
                                            'impassively matter-of-fact, as in style, behavior, or expression',
                                            ['a deadpan comedy 一个没有笑点的喜剧'],
                                            ['catatonic', 'expressionless', 'impassive', 'inexpressive', 'stolid', 'vacant'],
                                            ['demonstrative', 'expressive'])]),
                              Word('dearth', "",
                                   [TestWay('n',
                                            '供应不足',
                                            'an inadequate supply',
                                            ['a dearth of evidence 证据不足'],
                                            ['want', 'deficit', 'insufficiency', 'paucity', 'pinch', 'scantiness', 'scarcity', 'undersupply'],
                                            ['plethora', 'spate', 'copiousness', 'abundance', 'adequacy', 'amplitude', 'opulence'])]),
                              Word('debacle', "",
                                   [TestWay('n',
                                            '溃败',
                                            'a complete failure; fiasco',
                                            ['the debacle of the war 战争的彻底失败'],
                                            ['bummer', 'calamity', 'catastrophe', 'cataclysm', 'fiasco', 'fizzle', 'flop', 'washout'],
                                            ['complete success', 'éclat', 'blockbuster'])]),
                              Word('debark', "",
                                   [TestWay('vt',
                                            '从船或者飞机上卸货',
                                            'to unload, as from a ship or an airplane',
                                            ['the seasick passengers debarked as soon as the ship dropped anchor 晕船的乘客等到轮船一靠岸抛锚就立即下船'],
                                            ['land'],
                                            ['embark'])]),
                              Word('debase', "",
                                   [TestWay('v',
                                            '贬低, 贬损',
                                            "to reduce to a lower standing in one's own eyes or in others' eyes",
                                            ['our failure to win a single game completely debased 我们一场未胜的战绩彻底让我们的形象一落千丈'],
                                            ['abase', 'debauch', 'degrade', 'demean', 'demoralize', 'deprave', 'deteriorate', 'profane', 'subvert', 'vitiate'],
                                            ['aggrandize', 'canonize', 'deify', 'elevate', 'exalt', 'ennoble'])])])
list6_unit5 = VocabularyList([Word('debilitate', "",
                                   [TestWay('vt',
                                            '使衰弱',
                                            'to impair the strength of; enfeeble',
                                            ["The virus debilitates the body's immune system. 病毒削弱了免疫系统。"],
                                            ['devitalize', 'enervate', 'enfeeble', 'prostrate', 'sap'],
                                            ['invigorate', 'fortify', 'strengthen', 'beef up'])]),
                              Word('debris', "",
                                   [TestWay('n',
                                            '废墟',
                                            'discarded or useless material',
                                            ['the unsightly debris left after mining operations had ceased 采煤工程中止后留下难看的废墟'],
                                            ['dross', 'dust', 'litter', 'offal', 'refuse', 'effluvium junk'])]),
                              Word('debunk', "",
                                   [TestWay('v',
                                            '揭穿真面目',
                                            'to reveal the true nature of',
                                            ['debunk a supposed miracle drug 揭穿所谓的灵丹妙药的真面目'],
                                            ['uncloak', 'uncover', 'undress', 'unmask', 'show up'],
                                            ['camouflage', 'cloak', 'disguise', 'mask']),
                                    TestWay('v',
                                            '证明为假',
                                            'to prove to be false',
                                            ['a Web site that assiduously debunks urban legends 一个不遗余力证明假传闻的网站'],
                                            ['belie', 'confound', 'confute', 'discredit', 'falsify', 'rebut', 'refute'],
                                            ['confirm', 'establish', 'validate', 'verify'])]),
                              Word('debut', "",
                                   [TestWay('n',
                                            '初次登台, 出道',
                                            'a first public appearance',
                                            ['made her single debut 完成了她的处女秀'],
                                            antonyms = ['farewell performance'])]),
                              Word('decadence', "",
                                   [TestWay('n',
                                            '衰落, 颓废',
                                            'a process, condition, or period of deterioration or decline, a change to a lower state or level',
                                            ['The book condemns the decadence of modern society. 该书批判了现代社会的堕落。'],
                                            ['degeneracy', 'degeneration', 'degradation', 'deterioration', 'downfall', 'eclipse'],
                                            ['ascent', 'rise', 'upswing'])]),
                              Word('decant', "",
                                   [TestWay('vt',
                                            '轻轻倒出',
                                            'to pour off (wine, for example) without disturbing the sediment',
                                            ['The bottles were uncorked and the wine was decanted an hour before the meal. 瓶塞被打开, 美酒在正餐前一小时倒出'])]),
                              Word('decipher', "",
                                   [TestWay('vt',
                                            '破译',
                                            'to read or interpret (ambiguous, obscure, or illegible matter)',
                                            ['we deciphered the hidden message to find out when we were supposed to meet 破解了暗语后, 发现我们要碰头'],
                                            ['break', 'crack', 'decrypt', 'decode'],
                                            ['cipher', 'encipher', 'encode', 'encrypt']),
                                    TestWay('v',
                                            '有清晰想法, 理解, 解读',
                                            'to have a clear idea of',
                                            ['a convoluted thriller, the plot of which I was never able to actually decipher 一部错综复杂的恐怖电影, 情节我一直没有理解'],
                                            ['apprehend', 'perceive', 'recognize', 'seize', 'sense', 'make out'])]),
                              Word('decode', "",
                                   [TestWay('vt',
                                            '解码',
                                            'to change (as a secret message) from code into ordinary language',
                                            ['the agents worked into the night to decode the intercepted message from the enemy spy 情报人员夜以继日地破解从敌方间谍拦截的信息'],
                                            ['break', 'crack', 'decipher', 'decrypt']),
                                    TestWay('v',
                                            '有清晰想法, 理解,解读',
                                            'to have a clear idea of',
                                            ['a convoluted thriller, the plot of which I was never able to actually decipher 一部错综复杂的恐怖电影, 情节我一直没有理解'],
                                            ['apprehend', 'perceive', 'recognize', 'seize', 'sense', 'make out'])]),
                              Word('decorum', "",
                                   [TestWay('n',
                                            '礼仪, 得体',
                                            'appropriateness of behavior or conduct; propriety',
                                            ['high standards of decorum are usually required when attending the opera 去听歌剧的时候需要遵守高标准的礼节'],
                                            ['form', 'propriety'],
                                            ['impropriety', 'indecency'],
                                            'decorous adj. 有礼貌的: marked by propriety and good taste 【例】decorous behavior 得体的举止 【反】mangy, unseemly 低贱的, 不得体的; 【派】indecorous 不合礼节的 【反】proper 适当的')]),
                              Word('decrepit', "",
                                   [TestWay('adj',
                                            '虚弱的, 衰老的, 破旧的',
                                            'weakened, worn out, impaired, or broken down by old age, illness',
                                            ['a decrepit old man 一个虚弱的老年人'],
                                            antonyms = ['vigorous', 'sturdy', 'sound', 'robust', 'hale'])])])
list6_unit6 = VocabularyList([Word('default', "",
                                   [TestWay('v',
                                            '拖欠(债务)',
                                            'to fail to pay financial debts, the nonperformance of an assigned or expected action',
                                            ['default on a loan 拖欠贷款'],
                                            ['delinquency', 'dereliction', 'misprision', 'nonfeasance', 'oversight'],
                                            ["pay one's debt"])]),
                              Word('defer', "",
                                   [TestWay('v',
                                            '推迟, 延',
                                            'to put off; postpone; defer',
                                            ['we agreed to defer a discussion of the issue 我们决定推迟问题的讨论'],
                                            ['delay', 'remit', 'shelve', 'hold off', 'hold over', 'lay over',' put off'],
                                            ['exigent']),
                                    TestWay('vi',
                                            '遵从',
                                            "to submit to another's wishes, opinion, or governance usually through deference or respect",
                                            ['defer to her father’s wishes 听从她父亲的意愿'])]),
                              Word('deference', "",
                                   [TestWay('n',
                                            '尊崇, 顺从',
                                            'a readiness or willingness to yield to the wishes of others',
                                            ['He is shown much deference by his colleagues. 他的同事很尊敬他。'],
                                            ['acquiescence', 'compliancy', 'docility', 'obedience', 'submissiveness'],
                                            ['contempt', 'defiance', 'disobedience', 'intractability', 'recalcitrance'],
                                            'deferential adj. 表示尊重的, 恭敬的: showing or expressing deference 【反】imperious, impudent 专横无礼的')]),
                              Word('deficiency', "",
                                   [TestWay('n',
                                            '缺乏, 不足',
                                            'the quality or state of being deficient: inadequate',
                                            ['there is a deficiency of fresh food in the diet of many of the working poor 很多劳工阶层的饮食都缺乏新鲜食物'],
                                            ['want', 'dearth', 'deficit', 'famine', 'paucity', 'scantiness', 'scarcity'],
                                            ['surfeit', 'abundance', 'adequacy', 'amplitude', 'opulence', 'sufficiency']),]),
                              Word('defile', "",
                                   [TestWay('n',
                                            '(山间)小道',
                                            'a narrow passage or gorge',
                                            ['They climbed up the mountain through a defile. 他们通过一条小路爬到山上。']),
                                    TestWay('v',
                                            '亵渎',
                                            'to treat (a sacred place or object) shamefully or with great disrespect',
                                            ['art conservators were careful not to do anything that might defile the holy relic 公物管理员要防止任何玷污圣迹的行为'],
                                            ['profane', 'violate']),
                                    TestWay('v',
                                            '不能被使用',
                                            'to make unfit for use by the addition of something harmful or undesirable',
                                            ['supplies of meat that had been defiled by maggots 肉已经生蛆了, 不能再食用了'],
                                            ['befoul', 'foul', 'pollute', 'taint'],
                                            ['decontaminate', 'purify'])]),
                              Word('deft', "",
                                   [TestWay('adj',
                                            '灵巧的, 熟练的',
                                            'characterized by facility and skill',
                                            ['He finished off the painting with a few deft strokes of the brush. 他简单熟练的几笔便完成了画作。'],
                                            ['cunning', 'adroit', 'dexterous', 'expert', 'masterful', 'virtuoso'],
                                            ['awkward', 'maladroit', 'ham-handed', 'amateur', 'artless', 'unprofessional', 'unskillful'])]),
                              Word('defuse', "",
                                   [TestWay('vt',
                                            '抚慰, 减轻',
                                            'to make less dangerous, tense, or hostile',
                                            ['defuse the crisis 平息危机'],
                                            antonyms = ['foment 煽动'])]),
                              Word('defy', "",
                                   [TestWay('vt',
                                            '反抗, 违抗',
                                            'to go against the commands, prohibitions, or rules of',
                                            ['defy the court 蔑视法庭'],
                                            ['mock', 'rebel', 'oppose', 'confront'],
                                            ['acquiesce', 'obey', 'comply with', 'conform to', 'capitulate to', 'submit to', 'succumb to', 'surrender to', 'yield to'])]),
                              Word('dehydrate', "",
                                   [TestWay('vt',
                                            '去除水分, (使)干燥',
                                            'to remove water from; make anhydrous',
                                            ['bought a dehumidifier in order to dehydrate the damp basement 买了一个减湿器来给地下室除湿'],
                                            ['dampen', 'desiccate', 'parch', 'scorch', 'sear'],
                                            ['hydrate', 'saturate with water', 'reconstitute']),
                                    TestWay('v',
                                            '使失去活力或者味道',
                                            'to deprive of vitality or savor',
                                            ['years of being trapped in a loveless marriage had dehydrated his spirit 多年不幸的婚姻消磨了他的活力'],
                                            ['deaden', 'devitalize', 'enervate', 'petrify', 'sap'],
                                            ['brace', 'energize', 'enliven', 'invigorate', 'vitalize', 'vivify'])]),
                              Word('deify', "",
                                   [TestWay('v',
                                            '把…当作神来崇拜',
                                            'to offer honor or respect to (someone) as a divine power',
                                            ['some ancient pagans deified such objects of nature as trees and rivers 很多古代的异教徒拿一些自然事物比如树木, 河流来崇拜'],
                                            ['glorify', 'revere', 'venerate']),
                                    TestWay('v',
                                            '过分喜爱',
                                            'to love or admire too much',
                                            ['materialistic people who deify money 那些眼里只有钱的物质之人'],
                                            ['adore', 'adulate', 'canonize', 'dote']),
                                    TestWay('v',
                                            '尊敬尊崇',
                                            'to assign a high status or value to',
                                            ['Valentino was virtually deified by legions of female fans. 瓦伦蒂诺被大批女粉丝崇拜。'],
                                            ['aggrandize', 'canonize', 'dignify', 'ennoble', 'glorify', 'magnify'],
                                            ['abase', 'degrade', 'demean', 'humble', 'humiliate'],
                                            'deification n. 崇拜')])])
list6_unit7 = VocabularyList([Word('deject', "",
                                   [TestWay('vt',
                                            '使沮丧',
                                            'to lower the spirits of; dishearten',
                                            ['nothing dejects a TV pundit more than the reality check that nobody cares what he thinks 没有什么比大家都漠不关心更让电视节目专家沮丧了'],
                                            ['oppress', 'sadden', 'weigh down', 'bum out'],
                                            ['brighten', 'buoy', 'lighten', 'rejoice', 'cheer up'])]),
                              Word('deleterious', "",
                                   [TestWay('adj',
                                            '有害的',
                                            'harmful often in a subtle or unexpected way',
                                            ['deleterious to health 对健康有害的'],
                                            ['adverse', 'baleful', 'baneful', 'detrimental', 'mischievous', 'nocuous', 'noxious', 'pernicious'],
                                            ['beneficial', 'salutary', 'salubrious', 'wholesome', 'benign', 'harmless', 'innocuous'])]),
                              Word('deliberate', "",
                                   [TestWay('adj',
                                            '深思熟虑的',
                                            'characterized by or resulting from careful and thorough consideration',
                                            ['a deliberate decision 一个慎重的决定'],
                                            ['calculated', 'considered', 'reasoned', 'thoughtful'],
                                            ['impetuous', 'haste', 'casual', 'unadvised', 'uncalculated', 'unconsidered', 'unstudied'])]),
                              Word('delicacy', "",
                                   [TestWay('n',
                                            '(外貌、建筑、表演)精致',
                                            'fineness of appearance, construction, or execution; elegance',
                                            ['lace of great delicacy 精致的蕾丝'],
                                            ['dainty', 'delectable', 'kickshaw', 'tidbit'],
                                            ['crudity', 'husk', 'coarseness', 'roughness'])]),
                              Word('delirium', "",
                                   [TestWay('n',
                                            '精神错乱',
                                            'an acute mental disturbance characterized by confused thinking and disrupted attention usually accompanied by disordered speech and hallucinations',
                                            ['shoppers running around in a delirium the day before Christmas 购物者在圣诞节前夕疯狂扫货'],
                                            ['agitation', 'distraction', 'hysteria', 'rage', 'rampage', 'uproar'])]),
                              Word('delusion', "",
                                   [TestWay('n',
                                            '错觉',
                                            'a false idea',
                                            ['This was not optimism, it was delusion. 那不是乐观主义, 那是错觉。'],
                                            ['hallucination', 'illusion', 'unreality', 'falsehood', 'misconception'],
                                            ['truth', 'verity'],
                                            'delusive adj. 欺骗的: false, deceptive 【反】transparent 坦诚的')]),
                              Word('deluge', "",
                                   [TestWay('n',
                                            '大暴雨',
                                            'a drenching rain',
                                            antonyms = ['drizzle', '毛毛雨'])]),
                              Word('delve', "",
                                   [TestWay('n',
                                            '大量',
                                            'a great flow of water or of something that overwhelms',
                                            ['received a deluge of offers 收到了一大堆 offer'],
                                            ['inundation', 'overflow', 'spate', 'torrent'])]),
                              Word('demagogue', "",
                                   [TestWay('vi./vt',
                                            '探究, 钻研',
                                            'to make a careful or detailed search for information',
                                            ['The book delves into the latest research. 这本书深入探究了最近的研究。'],
                                            ['probe', 'investigate', 'inquire into', 'look into', 'dig into'])]),
                              Word('demanding', "",
                                   [TestWay('n',
                                            '蛊惑民心的政客',
                                            'a leader who makes use of popular prejudices and false claims and promises in order to gain power',
                                            ["that politician is just a demagogue who preys upon people's fears and prejudices 那就是一个蛊惑民心的政客, 利用民众的害怕和偏见来欺骗"],
                                            ['firebrand', 'fomenter', 'incendiary', 'instigator', 'kindler', 'provocateur'])])])
list6_unit8 = VocabularyList([Word('demolition', "",
                                   [TestWay('n',
                                            '破坏, 毁坏',
                                            'the act or process of wrecking or destroying, especially destruction by explosives',
                                            ['the demolition of dangerous buildings 危楼的拆毁'],
                                            ['annihilation', 'decimation', 'devastation', 'havoc', 'wreckage'],
                                            ['building', 'construction', 'erection', 'raising'])]),
                              Word('demonstrate', "",
                                   [TestWay('v',
                                            '(通过证据)证明, 表明',
                                            'to show or make clear by using examples',
                                            ['the paleontologist hopes to demonstrate that dinosaurs once existed in central Peru by unearthing the fossil evidence 通过发掘化石, 古生物学家试图证明恐龙曾经在秘鲁中部生活过'],
                                            ['exemplify', 'instance'],
                                            ['unable to prove']),
                                    TestWay('v',
                                            '使明白易懂',
                                            'to make plain or understandable',
                                            ['a few striking facts should demonstrate the complex nature of our topic 一些显著的事实可以使我们话题的复杂本质变得好懂'],
                                            ['clarify', 'construe', 'demystify', 'elucidate', 'explicate', 'illuminate'],
                                            ['obscure']),
                                    TestWay('v',
                                            '表现, 表露',
                                            'to make known (something abstract) through outward signs',
                                            ["the babysitter's actions during the emergency demonstrate beyond doubt her general dependability 保姆在紧急情况下的表现毋庸置疑地展示了她一贯的可靠性"],
                                            ['bespeak', 'betray', 'display', 'evince', 'manifest', 'reveal'])]),
                              Word('demoralize', "",
                                   [TestWay('v',
                                            '使士气低落',
                                            'to undermine the confidence or morale of; dishearten',
                                            ['demoralize the staff 使员工士气低落'],
                                            ['daunt', 'dishearten', 'dismay', 'dispirit', 'unnerve'],
                                            ['invigorate', 'cheer']),
                                    TestWay('v',
                                            '贬低, 堕落',
                                            'to lower in character, dignity, or quality',
                                            ['we refused to be demoralized by our humiliating defeat 我们拒绝由于这场屈辱的战败而被贬低'],
                                            ['abase', 'corrupt', 'debauch', 'degrade', 'demean'],
                                            ['elevate', 'ennoble', 'uplift'])]),
                              Word('demotic', "",
                                   [TestWay('adj',
                                            '通俗的, 大众化的',
                                            'popular, common',
                                            ['demotic entertainments 大众化的娱乐'],
                                            ['profound'])]),
                              Word('demur', "",
                                   [TestWay('vi',
                                            '表示异议, 反对',
                                            'to voice opposition; object',
                                            ['demur at the suggestion 反对提议'],
                                            ['challenge', 'exception', 'expostulation', 'fuss', 'kick', 'protest', 'remonstrance', 'stink'],
                                            ['accept', 'accede']),
                                    TestWay('n',
                                            '犹豫',
                                            'hesitation (as in doing or accepting) usually based on doubt of the acceptability of something offered or proposed; qualm',
                                            ['we accepted his offer to pay for our dinners without demur 我们毫不犹豫地同意了他买单'])]),
                              Word('denigrate', "",
                                   [TestWay('vt',
                                            '诋毁, 污蔑',
                                            "to express scornfully one's low opinion of",
                                            ["denigrate one's opponents 诋毁某人的对手"],
                                            ['belittle', 'depreciate', 'derogate', 'dismiss', 'disparage'],
                                            ['honor', 'acclaim', 'applaud', 'exalt', 'extol', 'glorify', 'magnify'])]),
                              Word('denouement', "",
                                   [TestWay('n',
                                            '(小说的)结局',
                                            'the final resolution or clarification of a dramatic or narrative plot',
                                            ['a surprising/unexpected denouement 令人惊奇的、出人意料的结局'])]),
                              Word('denounce', "",
                                   [TestWay('v',
                                            '公开指责',
                                            'to express public or formal disapproval of',
                                            ["the governor has denounced the court's decision and vows to press for a constitutional amendment 州长公开指责法庭决定不公, 准备投票进行修宪"],
                                            ['condemn', 'objurgate', 'rebuke', 'reprimand', 'reproach', 'reprove'],
                                            ['cite', 'commend', 'endorse']),
                                    TestWay('v',
                                            '道德上错误、可耻的',
                                            'to declare to be morally wrong or evil',
                                            ["the church council denounced the bishop's teachings, officially declaring them to be heresy 该教理事会指责主教的布道可耻, 声称它们是异端学说"],
                                            ['anathematize', 'censure', 'execrate', 'reprehend', 'reprobate'],
                                            other_form = 'denunciation n. 谴责: an act of denouncing especially: a public condemnation 【反】panegyric, accolade, eulogy 颂词')]),
                              Word('dent', "",
                                   [TestWay('n',
                                            '凹陷, 凹痕',
                                            'a depression in a surface made by pressure or a blow',
                                            ['a dent in the side of a car 汽车侧面一处凹陷'],
                                            ['cavity', 'depression', 'hollow', 'indenture', 'recess'],
                                            ['bulge', 'convexity', 'projection', 'protrusion', 'protuberance']),
                                    TestWay('vt',
                                            '(数量、程度上)变小, 变弱',
                                            'to make smaller in amount, volume, or extent',
                                            ["hopefully this vacation won't dent our bank account too much 但愿这次旅行不会让我们银行存款缩水太多"],
                                            ['abate', 'downscale', 'downsize', 'dwindle'],
                                            ['aggrandize', 'amplify', 'augment', 'boost', 'enlarge', 'escalate'])]),
                              Word('denude', "",
                                   [TestWay('vt',
                                            '脱去, 使赤裸',
                                            'to divest of covering; make bare',
                                            ['Drought has completely denuded the hills of grass.干旱脱去了山上的草使山变得光秃秃的。'],
                                            antonyms = ['cover'])])])
list6_unit9 = VocabularyList([Word('deplete', "",
                                   [TestWay('vt',
                                            '耗尽, 使衰竭',
                                            'to decrease the fullness of; to make complete use of',
                                            ['miners depleted the vein of copper ore after only a few months 矿工们在短短几个月内就把一整片铜矿开采完了'],
                                            ['consume', 'devour', 'drain', 'exhaust', 'draw down', 'play out', 'use up'],
                                            ['enrich', 'renew', 'replace'])]),
                              Word('deplore', "",
                                   [TestWay('vt',
                                            '哀悼',
                                            'to feel or express sorrow for',
                                            ['a statement from the bishops deploring the loss of life in the war overseas 一份来自大主教的声明, 对海外战争中遇难的生命表示沉痛哀悼'],
                                            ['mourn', 'bewail', 'grieve for', 'wail for'],
                                            ['delight', 'exult in', 'glory in', 'rejoice in'])]),
                              Word('deploy', "",
                                   [TestWay('v',
                                            '(有目的地)展开; 调度',
                                            'to spread out, utilize, or arrange for a deliberate purpose',
                                            ['deploy a sales force 展开部署销售力量'],
                                            antonyms = ['concentrate'])]),
                              Word('deportation', "",
                                   [TestWay('n',
                                            '放逐',
                                            'the removal from a country of an alien whose presence is unlawful or prejudicial',
                                            ['deport all illegal immigrants 驱逐所有非法移民'],
                                            ['banishment', 'displacement', 'expatriation', 'expulsion', 'relegation'])]),
                              Word('depose', "",
                                   [TestWay('vt',
                                            '发誓作证',
                                            'to testify to under oath or by affidavit',
                                            ['he was nervous when the time to depose before the jury finally arrived 他很紧张, 在陪审团面前作证的时刻终于到来了'],
                                            ['attest', 'swear'],
                                            ['perjure', '作伪证']),
                                    TestWay('v',
                                            '废黜, 罢免',
                                            'to remove from a throne or other high position',
                                            ['a military junta deposed the dictator after he had bankrupted the country 军阀罢黜了将国家分崩离析的独裁者'],
                                            ['defrock', 'deprive', 'oust', 'uncrown'],
                                            ['crown', 'enthrone']),
                                    TestWay('v',
                                            '摆放',
                                            'to arrange something in a certain spot or position',
                                            ['deposed her fan and gloves on the dressing table 把她的扇子和手套放在梳妆台上'],
                                            ['deposit', 'dispose', 'emplace', 'situate'])]),
                              Word('deposit', "",
                                   [TestWay('n',
                                            '自然积累, 沉积',
                                            'a natural accumulation (as of iron ore, coal, or gas)',
                                            ['rich deposits of oil and natural gas 丰富的石油、天然气'],
                                            ['dregs', 'precipitate', 'sediment', 'settlings', 'hoard', 'reserve'],
                                            ['process of eroding']),
                                    TestWay('v',
                                            '存钱',
                                            'to put in an account',
                                            ['we quickly deposited the check in a bank account 我们火速把支票存入银行账户'],
                                            ['withdraw'])]),
                              Word('depravity', "",
                                   [TestWay('n',
                                            '道德败坏',
                                            'immoral conduct or practices harmful or offensive to society',
                                            ['He was sinking into a life of utter depravity. 他自甘堕落。'],
                                            ['debauchery', 'iniquitousness', 'licentiousness', 'perversion', 'turpitude', 'dissoluteness'],
                                            ['morality', 'virtue'])]),
                              Word('deprecate', "",
                                   [TestWay('vt',
                                            '表达不喜欢',
                                            'to hold an unfavorable opinion of',
                                            ['deprecates TV sitcoms as childish and simpleminded 批评电视情景喜剧既幼稚又脑残'],
                                            ['deprecate', 'discountenance', 'disesteem', 'disfavor', 'frown (on or upon)'],
                                            ['approve', 'favor']),
                                    TestWay('vt',
                                            '贬低, 轻视',
                                            "to express scornfully one's low opinion of",
                                            ['deprecate the comedy as the stupidest movie of the year 认为这部喜剧是年度最傻逼电影'],
                                            ['belittle', 'denigrate', 'dismiss', 'disparage', 'cry down'],
                                            ['acclaim', 'applaud', 'exalt', 'extol', 'glorify']),
                                    TestWay('vt',
                                            '降低重要性, 低调',
                                            'play down, to make little of',
                                            ['She deprecated her facility for languages 她不炫耀自己对于语言的天赋。'],
                                            antonyms = ['vaunt'])]),
                              Word('depreciate', "",
                                   [TestWay('vt',
                                            '贬低价值',
                                            'to lower the price or estimated value of',
                                            ['New cars start to depreciate as soon as they are on the road. 新车一上路便开始贬值。'],
                                            ['cheapen', 'depress', 'devalue', 'downgrade', 'mark down'],
                                            ['appreciate', 'enhance', 'upgrade', 'mark up']),
                                    TestWay('vt',
                                            '轻视',
                                            'to lower in estimation or esteem',
                                            ['dared to depreciate Shakespeare, saying his works have no relevance for modern audiences 胆敢贬低莎士比亚, 说他的作品对于现代观众来说没有意义'],
                                            ['denigrate', 'disparage', 'play down', 'talk down'],
                                            ['acclaim', 'exalt', 'extol', 'glorify', 'magnify'])]),
                              Word('depressed', "",
                                   [TestWay('adj',
                                            '不开心, 情绪不高的',
                                            'feeling unhappiness',
                                            ["I was depressed and didn't feel much like going to the party"],
                                            ['crestfallen', 'dejected', 'despondent', 'gloomy', 'low-spirited', 'wretched'],
                                            ['blissful', 'buoyant', 'gleeful', 'joyous', 'jubilant']),
                                    TestWay('adj',
                                            '生活境况悲催的',
                                            'kept from having the necessities of life or a healthful environment',
                                            ['a depressed class of people whose living conditions are abominable even by third world standards 境况悲惨的一群人, 即使用第三世界标准来看他们的生存条件也是很糟的'],
                                            ['disadvantaged', 'underprivileged'],
                                            ['advantaged', 'privileged'])])])
list6_unit10 = VocabularyList([Word('deprivation', "",
                                   [TestWay('n',
                                            '匮乏',
                                            'the condition of being deprived; privation',
                                            ['serious sleep deprivation caused by long work hours 由长时间工作导致的严重睡眠不足'],
                                            antonyms = ['fecundity'])]),
                              Word('deracinate', "",
                                   [TestWay('vt',
                                            '根除',
                                            'to pull out by the roots; uproot',
                                            antonyms = ['plant'])]),
                              Word('derelict', "",
                                   [TestWay('adj',
                                            '玩忽职守的, 不认真的',
                                            'lacking a sense of duty; marked by a carelessly easy manner',
                                            ['the guards were judged derelict in their duty 守卫们被判玩忽职守罪'],
                                            ['disregardful', 'lax', 'neglectful', 'neglecting', 'remiss', 'slack'],
                                            ['extremely careful', 'attentive', 'conscientious', 'nonnegligent']),
                                    TestWay('n',
                                            '被社会遗弃的人',
                                            'a destitute homeless social misfit',
                                            ['a section of the city that seemed to be frequented mostly by derelicts流浪汉的集中区'],
                                            ['deserted', 'desolate', 'disused', 'forgotten', 'forsaken', 'rejected'],
                                            ['pillar of society'])]),
                              Word('deride', "",
                                   [TestWay('vt',
                                            '嘲弄, 嘲笑',
                                            'to speak of or treat with contemptuous mirth',
                                            ['my brothers derided our efforts, but were forced to eat their words when we won first place 我的兄弟嘲笑我们的努力, 但是当我们得了第一名以后不得不收回那些话'],
                                            ['gibe', 'jeer', 'mock', 'scout', 'shoot down', 'laugh at'],
                                            ['praise'],
                                            'derision n. 嘲弄: contemptuous or jeering laughter; ridicule 【反】veneration 尊敬')]),
                              Word('derivative', "",
                                   [TestWay('adj',
                                            '非原创的',
                                            'lacking originality: banal',
                                            ['their dull, derivative debut album 他们毫无新义的首张专辑'],
                                            ['secondhand'],
                                            ['original', 'innovative', 'precursory'])]),
                              Word('descend', "",
                                   [TestWay('v',
                                            '下降',
                                            'to lead or extend downward',
                                            ['the pathway descends to the river bank 通道一直向下延伸到河岸'],
                                            ['dip', 'fall', 'plunge', 'sink'],
                                            ['arise', 'ascend', 'climb', 'mount', 'upsweep', 'upturn']),
                                    TestWay('v',
                                            '世代相传',
                                            'to originate or come from an ancestral stock or source, to pass by inheritance',
                                            ['The house has descended through four generations. 这座房子已经传了四代。a tradition descending from colonial days 殖民时期传递下来的一项传统'])]),
                              Word('descendant', "",
                                   [TestWay('n',
                                            '后代',
                                            'one deriving directly from a precursor or prototype',
                                            ['They are descendants of the original English and Scottish settlers. 他们是最早一批英格兰和苏格兰定居者的后裔。'],
                                            antonyms = ['forbears'])]),
                              Word('desecrate', "",
                                   [TestWay('vt',
                                            '亵渎, 玷污',
                                            'to treat (a sacred place or object) shamefully or with great disrespect',
                                            ['desecrate the shrine 玷污神龛'],
                                            ['defile', 'profane', 'violate'],
                                            ['sanctify', 'revere', 'hallow'])]),
                              Word('desiccate', "",
                                   [TestWay('v',
                                            '使(食物)脱水以保存, 使干燥',
                                            'to preserve (a food) by drying',
                                            ['add a cup of desiccated coconut to the mix 加一杯椰蓉进行搅拌'],
                                            ['dehydrate', 'parch', 'scorch', 'sear'],
                                            ['add water to', 'hydrate', 'drench'],
                                            'desiccant n. 干燥剂: a drying agent (as calcium chloride)'),
                                    TestWay('v',
                                            '缺乏活力',
                                            'to deprive of emotional or intellectual vitality',
                                            ["that historian's dryasdust prose desiccates what is actually an exciting period in European history 那位历史学家枯燥无味的散文让欧洲一段扣人心弦的历史变得乏味单调"],
                                            ['brace', 'castrate', 'dampen', 'deaden', 'devitalize', 'enervate'],
                                            ['energize', 'enliven', 'invigorate', 'stimulate', 'vitalize'])]),
                              Word('designate', "",
                                   [TestWay('v',
                                            '任命',
                                            "to pick (someone) by one's authority for a specific position or duty",
                                            ['he has yet to designate his successor as head of the firm 他还没有给公司选定接班人'],
                                            ['assign', 'commission', 'constitute', 'nominate', 'place'],
                                            ['discharge', 'dismiss', 'expel', 'fire']),
                                    TestWay('v',
                                            '命名',
                                            'to give a name to',
                                            ['he was designated Air Jordan by his fans 他被粉丝们称为飞人乔丹'],
                                            ['denominate', 'dub', 'entitle', 'label', 'style', 'term', 'title'])])])

LIST6 = VocabularyList(list6_unit1.words+list6_unit2.words+list6_unit3.words+list6_unit4.words+list6_unit5.words+list6_unit6.words+list6_unit7.words+list6_unit8.words+list6_unit9.words+list6_unit10.words)
