#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list2_unit1 = VocabularyList([Word('amorphous', "",
                                   [TestWay('adj',
                                            '无固定形状的',
                                            'having no definite form: shapeless',
                                            ['an amorphous cloud mass 一团无定形的云'],
                                            ['shapeless', 'unformed', 'unshaped']),
                                    TestWay('adj',
                                            '不可归类的',
                                            'being without definite character or nature: unclassifiable',
                                            ['an amorphous segment of society 不可归类的社会阶段'],
                                            ['unclassifiable'])]),
                              Word('analgesic', "",
                                   [TestWay('n',
                                            '镇痛剂',
                                            'a medication that reduces or eliminates pain',
                                            ['Aspirin is a kind of analgesic. 阿司匹林是一种止痛剂。'],
                                            ['anesthetic', 'anodyne'])]),
                              Word('anarchist', "",
                                   [TestWay('n',
                                            '反抗权威的人',
                                            'a person who rebels against any authority, established order, or ruling power',
                                            synonyms = ['rebel, insurgent'],
                                            other_form = 'anarchy n. 混乱: a state of lawlessness or political disorder due to the absence of governmental authority【近】chaos, disarray, topsy-turviness, commotion, turmoil【反】order 有序')]),
                              Word('anathema', "",
                                   [TestWay('n',
                                            '诅咒',
                                            'a ban or curse solemnly pronounced by ecclesiastical authority and accompanied by excommunication',
                                            synonyms = ['curse', 'execration', 'imprecation', 'malediction'],
                                            antonyms = ['benediction', 'benison', 'blessing'])]),
                              Word('ancillary', "",
                                   [TestWay('adj',
                                            '次要的',
                                            'of secondary importance',
                                            ['The company hopes to boost its sales through ancillary products. 公司想通过辅助产品来增加销量。'],
                                            ['subordinate', 'subsidiary'],
                                            ['main', 'paramount']),
                                    TestWay('adj',
                                            '辅助的, 补充的',
                                            'auxiliary, supplementary',
                                            ['the need for ancillary evidence 对补充证据的需要', 'Some practice in the deft use of words may well be ancillary to the study of natural science. 熟练使用文字的练习对于自然科学的研究也是有帮助的。'],
                                            ['auxiliary', 'supplementary'])]),
                              Word('anecdote', "",
                                   [TestWay('n',
                                            '短小有趣的故事',
                                            'a usually short narrative of an interesting, amusing, or biographical incident',
                                            ['He told us all sorts of humorous anecdotes about his childhood. 他告诉了我们所有关于他童年的奇闻趣事。', 'He is a master raconteur with endless anecdotes. 他是讲故事的超级高手, 总有讲不完的奇闻趣事。'])]),
                              Word('anemic', "",
                                   [TestWay('adj',
                                            '缺乏力量、活力、精神的',
                                            'lacking force, vitality, or spirit',
                                            ['an anemic economic recovery. 毫无活力的经济复苏', "Investors are worried about the stock's anemic performance. 投资者担心股市低迷的表现。"],
                                            ['sapless', 'infirm', 'feeble', 'decrepit', 'wan', 'pale', 'pallid', 'effete', 'lethargic'],
                                            ['vigorous', 'spirited', 'forceful'])]),
                              Word('anesthetic', "",
                                   [TestWay('n',
                                            '止痛剂',
                                            'something (as a drug) that relieves pain',
                                            ['The dentist waited until the anesthetic took effect. 牙医等止痛药生效。'],
                                            ['analgesic', 'anodyne']),
                                    TestWay('adj',
                                            '无感觉的, 麻木的',
                                            'lacking awareness or sensitivity',
                                            ['be anesthetic to their feelings 对他们的感受麻木不仁'],
                                            antonyms = ['sensate'])]),
                              Word('animate', "",
                                   [TestWay('adj',
                                            '活的',
                                            'having or showing life',
                                            ['The lecture was about ancient worship of animate and inanimate objects. 演讲是关于对生命体和非生命体的古代崇拜。'],
                                            ['breathing', 'live', 'living'],
                                            ['dead', 'expired', 'deceased', 'lifeless', 'nonliving']),
                                    TestWay('adj',
                                            '有活力的',
                                            'having much high-spirited energy and movement',
                                            ['Animate dance will get the blood pumping. 有活力的舞蹈会让人热血沸腾。'],
                                            ['bouncing', 'brisk', 'energetic', 'sprightly', 'vivacious'],
                                            ['inactive', 'lackadaisical', 'languid', 'listless', 'leaden']),
                                    TestWay('v',
                                            '使有活力, 支持',
                                            'to give spirit and support to',
                                            ["The writer's humor animates the novel. 作者的幽默使小说富有生命力。"],
                                            ['brace', 'energize', 'enliven', 'invigorate', 'ginger (up)', 'pep up', 'vitalize'],
                                            ['damp', 'dampen', 'deaden'],
                                            'animation 生命力, 活力: the quality or condition of being alive, active, spirited, or vigorous.【反】lassitude, lethargy 疲倦,疲乏'),
                                    TestWay('v',
                                            '使行动, 驱使',
                                            'to move to action',
                                            ['a criminal animated by greed 一个受贪婪驱使的罪犯'],
                                            ['goad', 'prod', 'spur', 'galvanize', 'stimulate']),
                                    TestWay('v',
                                            '使活灵活现, 使栩栩如生',
                                            'to make or design in such a way as to create apparently spontaneous lifelike movement',
                                            ["Kongfu Panda's very realistic panda was animated by CG. 《功夫熊猫》电影里面的熊猫是通过CG技术使熊猫变得活灵活现的。"])]),
                              Word('animus', "",
                                   [TestWay('n',
                                            '敌意',
                                            'a usually prejudiced and often spiteful or malevolent ill will, enmity',
                                            ['She felt no animus toward those who had wronged her. 她对那些冤枉了她的人没有敌意。'],
                                            ['animosity', 'antagonism', 'antipathy', 'hostility', 'rancor'],
                                            ['friendliness', 'amity', 'amenity'])])])
list2_unit2 = VocabularyList([Word('annoy', "",
                                   [TestWay('vt',
                                            '不断烦扰',
                                            'to disturb or irritate especially by repeated acts',
                                            ['Mosquitoes annoy us in the summer. 夏天蚊子总是不断烦扰我们。', 'The sound of footsteps on the bare floor annoyed the downstairs neighbors. 楼上地板的脚步声吵得楼下住户心烦。'],
                                            ['aggravate', 'bother', 'chafe', 'gall', 'grate', 'irk', 'nettle', 'peeve', 'pique', 'rile', 'ruffle', 'spite', 'vex'],
                                            ['soothe', 'defuse', 'allay', 'conciliate', 'propitiate', 'mitigate', 'assuage', 'appease', 'pacify', 'placate', 'calm', 'settle', 'subdue', 'solace', 'mollify'])]),
                              Word('annul', "",
                                   [TestWay('v',
                                            '宣告无效, 取消',
                                            'to declare or make legally invalid or void',
                                            ['The marriage was annulled last month. 婚约上个月取消了。'],
                                            ['disannul', 'cancel', 'invalidate', 'abrogate', 'nullify', 'repeal', 'rescind'],
                                            ['make legal', 'enact']),
                                    TestWay('v',
                                            '抵消',
                                            'to balance with an equal force so as to make ineffective',
                                            ['Unfortunately, his arrogant attitude annuls the many generous favors he does for people. 不幸的是, 他傲慢的态度抵消了他之前对人民的慷慨恩惠。'],
                                            ['counterbalance', 'neutralize'])]),
                              Word('anomalous', "",
                                   [TestWay('adj',
                                            '不普通的, 不平常的',
                                            'being out of the ordinary',
                                            ['He is in an anomalous position as the only part-time teacher in XDF. 他和别人不一样的是, 他是XDF唯一的兼职老师。'],
                                            ['aberrant', 'abnormal', 'atypical', 'phenomenal', 'singular', 'uncustomary', 'unwonted'],
                                            ['unexceptional', 'unextraordinary'],
                                            'anomaly n. 反常 deviation or departure from the normal or common order, form, or rule.'),
                                    TestWay('adj',
                                            '反常的, 不正常的',
                                            'departing from some accepted standard of what is normal',
                                            ['an anomalous burst of anger from this usually easygoing person 一个随和的人的一反常态的暴怒'],
                                            ['natural', 'standard'])]),
                              Word('anonymous', "",
                                   [TestWay('adj',
                                            '匿名的',
                                            'not named or identified',
                                            ['He made an anonymous phone call to the police. 他给警察打了一个匿名电话。', 'The donor wishes to remain anonymous. 捐赠者希望保持匿名身份。'],
                                            ['incognito', 'innominate', 'unnamed', 'unidentified', 'untitled'],
                                            ['dubbed', 'named', 'termed']),
                                    TestWay('adj',
                                            '无特色的',
                                            'lacking individuality, distinction, or recognizability',
                                            ['the anonymous faces in the crowd 大众脸'])]),
                              Word('antagonize', "",
                                   [TestWay('vt',
                                            '敌对,反对',
                                            'to act in opposition to: counteract',
                                            ['He did not mean to antagonize you. 他并没有要反对你。', 'antagonize a bill 反对一项议案'],
                                            ['counteract', 'disagree'],
                                            ['agree', 'concede', 'grant', 'win over']),
                                    TestWay('vt',
                                            '激起敌意',
                                            'to incur or provoke the hostility of',
                                            ['His remark antagonized his friends. 他的评述激怒了他的朋友。'],
                                            ['aggravate', 'exasperate', 'gall', 'inflame', 'nettle', 'provoke', 'peeve', 'pique', 'irritate', 'rile', 'roil', 'chafe', 'grate', 'ruffle', 'vex'],
                                            ['soothe', 'defuse', 'allay', 'conciliate', 'propitiate', 'mitigate', 'assuage', 'appease', 'pacify', 'placate', 'calm', 'settle', 'subdue', 'solace', 'mollify'])]),
                              Word('antediluvian', "",
                                   [TestWay('adj',
                                            '非常古老的, 过时的',
                                            'extremely old and antiquated',
                                            ['He has antediluvian notions about the role of women in the workplace. 他对职场女性抱有老掉牙的看法。', 'an antediluvian automobile 古董级的汽车'],
                                            ['aged', 'age-old', 'prehistoric', 'antique', 'aged', 'immemorial'],
                                            ['modern', 'new', 'recent']),
                                    TestWay('n',
                                            '保守的人',
                                            'a person with old-fashioned ideas',
                                            ['an antediluvian who thought a woman without talent is virtuous 一个认为“女子无才便是德”的保守的人'],
                                            ['reactionary'],
                                            ['modern', 'trendy'])]),
                              Word('anterior', "",
                                   [TestWay('adj',
                                            '前面的',
                                            'coming before in time or development',
                                            ['finish the work anterior to the schedule 提早完成任务', 'tests anterior to the college entrance examination 高考前的考试'],
                                            ['antecedent', 'foregoing', 'former', 'forward', 'precedent', 'preceding', 'prior'],
                                            ['after', 'ensuing', 'following', 'posterior', 'subsequent', 'succeeding'])]),
                              Word('antic', "",
                                   [TestWay('adj',
                                            '滑稽可笑的',
                                            'characterized by clownish extravagance or absurdity',
                                            ['The clown came on with many antic gestures. 小丑上场表演许多滑稽动作。'],
                                            ['chucklesome', 'comedic', 'comic', 'droll', 'farcical', 'laughable', 'ludicrous', 'hilarious'],
                                            ['humorless', 'unamusing', 'uncomic', 'unfunny', 'unhumorous', 'grave', 'serious', 'solemn', 'somber'])]),
                              Word('apathy', "",
                                   [TestWay('n',
                                            '冷漠, 缺乏情感',
                                            'lack of feeling or emotion',
                                            ['People have shown surprising apathy toward these important social problems. 人们对于这些重要的社会问题显示出了令人惊讶的冷漠。'],
                                            ['affectlessness', 'emotionlessness', 'impassiveness', 'impassivity', 'insensibility', 'numbness', 'phlegm'],
                                            ['emotion', 'feeling', 'sensibility']),
                                    TestWay('n',
                                            '缺乏兴趣, 不关心',
                                            'lack of interest or concern',
                                            ['She heard the story with apathy. 她毫无兴趣的听完了这个故事。', 'Her poor grades are proof enough of her apathy concerning all matters academic. 她可怜的分数足以证明她对所有学术问题都没兴趣。'],
                                            ['disinterestedness', 'disregard', 'incuriosity', 'insouciance', 'nonchalance', 'unconcern'],
                                            ['concern', 'interest', 'regard'])]),
                              Word('aphorism', "",
                                   [TestWay('n',
                                            '短小有智慧的格言',
                                            'a short witty sentence which expresses a general truth or comment',
                                            ['When decorating, remember the familiar aphorism, “less is more.” 装修时需要记住的一句格言是“少即是多”。'],
                                            ['adage', 'epigram', 'maxim', 'proverb'])])])
list2_unit3 = VocabularyList([Word('apocalyptic', "",
                                   [TestWay('adj',
                                            '预言的, 启示的',
                                            'of a revelatory or prophetic nature',
                                            ['No one listened to her apocalyptic predictions. 没有人听她的预言。'],
                                            ['prophetic', 'predictive', 'prognostic', 'farsighted']),
                                    TestWay('adj',
                                            '重要的, 转折点的',
                                            'of, relating to, or being a major turning point',
                                            ['the apocalyptic Battle of Stalingrad leading to the ultimate defeat of Nazi Germany 具有转折点意义的斯大林格勒战役导致了最后纳粹德国的战败'],
                                            antonyms = ['trivial', 'petty', 'minor', 'immaterial', 'inconsequential', 'insignificant']),
                                    TestWay('adj',
                                            '夸大的',
                                            'wildly unrestrained : grandiose',
                                            ['apocalyptic tone 夸大的语气'])]),
                              Word('apocryphal', "",
                                   [TestWay('adj',
                                            '假的',
                                            'of doubtful authenticity : spurious',
                                            ["an apocryphal story about the president's childhood 一个假的关于总统童年的故事"],
                                            ['spurious', 'unauthentic', 'ungenuine'],
                                            ['factual', 'true', 'truthful', 'authentic'])]),
                              Word('apoplectic', "",
                                   [TestWay('adj',
                                            '极度愤怒的',
                                            'extremely angry; furious',
                                            ['He became apoplectic about wasteful government spending. 他对于政府的浪费开销变得怒不可遏。', 'The coach was so apoplectic when the player missed the free throw that he threw his clipboard onto the court. 教练对球员罚篮不进非常气愤以至于把战术板扔到了球场上。'],
                                            ['choleric', 'enraged', 'furious', 'incensed', 'indignant', 'infuriated', 'irate', 'ireful', 'outraged'],
                                            ['angerless', 'delighted', 'pleased'])]),
                              Word('apostasy', "",
                                   [TestWay('n',
                                            '放弃宗教信仰',
                                            'renunciation of a religious faith',
                                            ['Some people completely abandon the faith after apostasy. 有些人在放弃自己的宗教信仰后就再也不相信任何其他宗教信仰了。']),
                                    TestWay('n',
                                            '变节, 背叛',
                                            'abandonment of a previous loyalty : defection',
                                            ['He was looked down upon for apostasy. 他因为背叛而受到鄙视。'],
                                            ['defection', 'perfidy', 'treacherousness', 'recreancy'],
                                            ['fidelity', 'allegiance', 'loyalty', 'piety'])]),
                              Word('appall', "",
                                   [TestWay('v',
                                            '使惊恐',
                                            'to overcome with consternation, shock, or dismay',
                                            ['He felt appalled by the whole idea of marriage so we broke up. 结婚使他恐惧, 因此我们分手了。'],
                                            ['dismay', 'terrify', 'intimidate', 'frighten', 'horrify', 'daunt', 'deter'],
                                            ['embolden', 'encourage', 'nerve'])]),
                              Word('appeal', "",
                                   [TestWay('n',
                                            '申请',
                                            'an application (as to a recognized authority) for corroboration, vindication, or decision',
                                            ['A piteous appeal for help. 虔诚的请求帮助。', 'to make an appeal to the public to donate needed blood 向公众提出献血请求'],
                                            ['adjuration', 'conjuration', 'entreaty', 'petition', 'pleading', 'supplication']),
                                    TestWay('n',
                                            '起诉',
                                            'to charge with a crime : accuse',
                                            ["My lawyer said the court's decision wasn't correct and that we should file for an appeal. 我的律师说法庭的判决不对, 我们应该起诉。"],
                                            ['charge', 'accuse', 'incriminate', 'inculpate', 'indict'],
                                            ['absolve', 'exonerate', 'exculpate', 'vindicate'])]),
                              Word('appealing', "",
                                   [TestWay('adj',
                                            '吸引人的',
                                            'attractive, inviting',
                                            ['The large salary made Goldman Sachs’s offer more appealing to him. 高薪使高盛的工作对他更有吸引力。'],
                                            ['alluring', 'captivating', 'charismatic', 'charming', 'enchanting', 'engaging', 'entrancing', 'luring', 'seductive'],
                                            ['repellent', 'repelling', 'repugnant', 'repulsive', 'unalluring'])]),
                              Word('applause', "",
                                   [TestWay('n',
                                            '鼓掌, 认可',
                                            'approval publicly expressed (as by clapping the hands)',
                                            ['Her appearance was greeted with applause. 她的表现赢得了认可。'],
                                            ['acclamation', 'cheer', 'cheering', 'ovation', 'plaudit', 'rave'],
                                            ['hissing', 'booing'])]),
                              Word('apposite', "",
                                   [TestWay('adj',
                                            '相关的, 合适的',
                                            'highly pertinent or appropriate: apt',
                                            ['to enrich his essay with some very apposite quotations from famous people 用名人名言来丰富他的文章'],
                                            ['applicable', 'apropos', 'germane', 'pointed', 'relative', 'relevant'],
                                            ['extraneous', 'irrelevant', 'impertinent', 'irrelative', 'pointless'])]),
                              Word('appreciable', "",
                                   [TestWay('adj',
                                            '可感知的, 明显的',
                                            'capable of being perceived or measured; perceptible',
                                            ["the appreciable changes in temperature 气温明显的变化", "There doesn't seem to be any appreciable difference between this piece and that one. 这个和那个看上去没什么差别。"],
                                            ['apprehensible', 'perceptible', 'detectable', 'discernible', 'palpable', 'distinguishable', 'sensible'],
                                            ['impalpable', 'imperceptible', 'inappreciable', 'indistinguishable', 'insensible', 'undetectable'])])])
list2_unit4 = VocabularyList([Word('apprehension', "",
                                   [TestWay('n',
                                            '忧虑, 恐惧',
                                            'suspicion or fear especially of future evil',
                                            ["She had a strong apprehension about her sister's health 她非常担心她姐姐的健康。"],
                                            ['dread', 'foreboding', 'misgiving', 'anxiousness', 'unease', 'uneasiness', 'worry'],
                                            ['composure', 'equanimity', 'unconcern']),
                                    TestWay('n',
                                            '逮捕',
                                            'seizure by legal process : arrestment',
                                            ['apprehension of the thief 逮捕小偷'],
                                            ['arrest'],
                                            ['discharge']),
                                    TestWay('n',
                                            '理解',
                                            'the knowledge gained from the process of coming to know or understand something',
                                            ['a good apprehension of how computer systems work 对计算机是如何工作的有很好的理解'],
                                            ['understanding', 'comprehension'],
                                            ['incomprehension'])]),
                              Word('apprise', "",
                                   [TestWay('v',
                                            '通知, 告知',
                                            'to give notice to; inform',
                                            ['apprise him of the danger that may be involved 告知他可能涉及的危险'],
                                            ['inform', 'acquaint', 'make known to'],
                                            ['withhold information'])]),
                              Word('approbation', "",
                                   [TestWay('n',
                                            '同意',
                                            'an expression of warm approval',
                                            ['The proposal met his approbation. 这项建议得到了他的'],
                                            ['approval', 'favor'],
                                            ['disapproval', 'disapprobation', 'disfavor'])]),
                              Word('appropriate', "",
                                   [TestWay('v',
                                            '私自挪用',
                                            'to take possession of or make use of exclusively for oneself, often without permission',
                                            ['to appropriate private property 盗用私人财产', "The economy has been weakened by corrupt officials who have appropriated the country's resources fortheir own use. 经济因为腐败的官员们私自挪用国家资源而被削弱了。"],
                                            ['purloin', 'pirate', 'embezzle', 'peculate', 'usurp']),
                                    TestWay('adj',
                                            '适当的',
                                            'especially suitable or compatible: fitting',
                                            ["Red wine is a more appropriate choice with the meal. 红酒更适合这顿饭。", "I don't think jeans and a T-shirt are appropriate attire for a wedding. 我觉得穿牛仔和T恤去婚礼不太得体。"],
                                            ['apt', 'becoming', 'felicitous', 'fitting', 'proper', 'meet', 'suitable', 'apposite', 'apropos'],
                                            ['improper', 'inapposite', 'inappropriate', 'inapt', 'unmeet', 'unseemly', 'unsuitable'])]),
                              Word('apropos', "",
                                   [TestWay('adj',
                                            '相关的',
                                            'being both relevant and opportune',
                                            ['The actor announced to reporters that he would only answer to apropos questions about the movie. 演员向记者表示, 他只回答那些和电影有关的问题。'],
                                            ['appliacable', 'apropos', 'germane', 'pointed', 'relative', 'relevant'],
                                            ['extraneous', 'irrelevant', 'impertinent', 'irrelative', 'pointless']),
                                    TestWay('prep',
                                            '关于, 有关',
                                            'having to do with',
                                            ['to make a number of telling observations apropos the current political situation 做了很多关于当前政治形势有力的观察'],
                                            ['apropos', 'apropos of', 'as far as', 'as for, as regards (also as respects)', 'as to', 'concerning', 'of', 'on', 'regarding', 'respecting', 'touching', 'toward (or towards)'])]),
                              Word('apt', "",
                                   [TestWay('adj',
                                            '恰当的,合适的',
                                            'exactly suitable; appropriate',
                                            ['apt remark/choice/description 恰当的评述、选择、描述'],
                                            ['apropos', 'germane', 'relative', 'relevant', 'appropirate'],
                                            ['extraneous', 'irrelevant', 'impertinent', 'irrelative', 'inappropriate', 'improper', 'unseemly']),
                                    TestWay('adj',
                                            '有…倾向的, 可能的',
                                            'having a tendency: likely',
                                            ['He is apt to fly out in rage. 他容易发脾气。'],
                                            ['likely', 'inclined', 'tending', 'given'],
                                            ['unlikely', 'disinclined']),
                                    TestWay('adj',
                                            '聪明的',
                                            'keenly intelligent and responsive',
                                            ['an apt pupil 一个聪明的小学生', 'He is apt at mathematics. 他擅长数学。'],
                                            ['brilliant', 'clever', 'quick-witted', 'ready-witted', 'smart'],
                                            ['foolish', 'dull', 'dumb', 'stupid', 'unintelligent'])]),
                              Word('archaic', "",
                                   [TestWay('adj',
                                            '过时的, 久远的',
                                            'no longer current or applicable; antiquated',
                                            ['archaic laws 过时的法律'],
                                            ['antiquated', 'outdated', 'outmoded', 'prehistoric', 'superannuated'],
                                            ['fashionable', 'up-to-date', 'fresh', 'modern', 'new', 'novel'],
                                            "archaism 古语: the use of archaic diction or style【反】modern diction 新语")]),
                              Word('archetype', "",
                                   [TestWay('n',
                                            '典范, 榜样',
                                            'an ideal example of a type',
                                            ['an archetype of the successful entrepreneur 成功企业家的典范'],
                                            ['ideal', 'a perfect example', 'quintessence']),
                                    TestWay('n',
                                            '先驱, 鼻祖',
                                            'something belonging to an earlier time from which something else was later developed',
                                            ['The abacus is sometimes cited as the archetype of the modern digital calculator 算盘是现代计算器的鼻祖'],
                                            ['antecedent, foregoer, forerunner, precursor, predecessor, prototype']),
                                    TestWay('n',
                                            '原型',
                                            'something from which copies are made',
                                            ['Frankenstein, Dracula, Dr. Jekyll and Mr. Hyde are the archetypes that have influenced all subsequent horror stories. 弗兰肯斯坦、德古拉、 杰基尔博士以及海德先生影响了所有继之而来的恐怖故事的原型。'],
                                            ['archetype', 'prototype'])]),
                              Word('ardor', "",
                                   [TestWay('n',
                                            '狂热',
                                            'strong enthusiasm or devotion; zeal',
                                            ['His ardor was damped. 他的热情被泼了冷水。'],
                                            ['avidity', 'zeal', 'fervor', 'fervency', 'fervidness', 'passion', 'passionateness', 'vehemence'],
                                            ['apathy', 'torpor', 'impassivity', 'insensitivity'])]),
                              Word('arduous', "",
                                   [TestWay('adj',
                                            '难以做到, 费劲的',
                                            'hard to accomplish or achieve: difficult',
                                            ['a long and arduous undertaking 一项长期艰苦的任务', 'an arduous journey across miles of desert 艰苦的沙漠之旅'],
                                            ['grueling', 'laborious', 'taxing', 'onerous', 'burdensome'],
                                            ['easy', 'simple', 'unchallenging', 'undemanding', 'facile', 'effortless'])])])
list2_unit5 = VocabularyList([Word('argot', "",
                                   [TestWay('n',
                                            '隐语, 黑话, 行话',
                                            'a specialized vocabulary or set of idioms used by a particular group',
                                            ['groups communicating in their own secret argots 用他们秘密的行话交流的团体'],
                                            ['argot', 'cant', 'jargon', 'shoptalk'],
                                            ['standard language', 'common verbalism'])]),
                              Word('arrest', "",
                                   [TestWay('vt',
                                            '使不活跃',
                                            'to make inactive',
                                            ['arrest the growth of the tumor 抑制肿瘤生长'],
                                            ['check', 'rein', 'curb', 'contain', 'hamper', 'thwart', 'bring to a halt'],
                                            ['vitalize', 'activate', 'animate', 'invigorate', 'prod, goad', 'spur', 'galvanize', 'provoke', 'stimulate']),
                                    TestWay('n./v',
                                            '停止',
                                            'the stopping of a process or activity; to bring to a standstill',
                                            ['Science cannot yet arrest the process of aging. 科学不能阻止衰老。'],
                                            ['cease', 'cessation', 'closure', 'conclusion', 'discontinuance', 'discontinuation', 'ending', 'halt', 'stop', 'termination', 'check', 'stop'],
                                            ['continuance', 'continuation']),
                                    TestWay('v',
                                            '逮捕',
                                            "to take or keep under one's control by authority of law",
                                            ['She was charged with resisting arrest. 她因为拘捕受到起诉。'],
                                            ['apprehend'],
                                            ['discharge']),
                                    TestWay('v',
                                            '吸引注意力',
                                            'to hold the attention of as if by a spell',
                                            ['The behavior of the daredevil arrested pedestrians. 冒失鬼的行为吸引了行人们的注意力。'],
                                            ['enchant', 'fascinate', 'bedazzle', 'grip', 'hypnotize', 'mesmerize'])]),
                              Word('arresting', "",
                                   [TestWay('adj',
                                            '吸引人的',
                                            'attracting and holding the attention; striking',
                                            ['an arresting spectacle 吸引人的奇观'],
                                            ['absorbing', 'engaging', 'engrossing', 'enthralling', 'fascinating', 'gripping', 'immersing', 'intriguing', 'riveting'],
                                            ['boring', 'drab', 'tedious', 'monotonous', 'uninteresting'])]),
                              Word('arrhythmic', "",
                                   [TestWay('adj',
                                            '不规律的',
                                            'lacking rhythm or regularity',
                                            ['arrhythmic pulse 不规律的脉搏'],
                                            ['irregular', 'disorderly'],
                                            ['regular', 'orderly'])]),
                              Word('arrogance', "",
                                   [TestWay('n',
                                            '傲慢, 自大',
                                            'overbearing pride',
                                            ['Her arrogance has earned her a lot of enemies. 她的傲慢给她带来了很多敌人。'],
                                            ['assumption', 'bumptiousness', 'haughtiness', 'hauteur', 'imperiousness', 'loftiness', 'peremptoriness', 'pomposity', 'pompousness', 'presumptuousness', 'superciliousness'],
                                            ['humility', 'modesty', 'humbleness', 'unassumingness'])]),
                              Word('articulate', "",
                                   [TestWay('v',
                                            '清晰地表达',
                                            'to utter clearly and distinctly',
                                            ['He cannot articulate his thoughts. 他不能清楚地表达他的想法。', 'a theory first articulated by ancient philosophers 被古时哲学家阐明的理论'],
                                            ['enunciate'],
                                            ['murmur', 'mumble', 'mutter', 'slur']),
                                    TestWay('adj',
                                            '表达清晰的',
                                            'able to express oneself clearly and well',
                                            ['The television crew covering the science fair were looking for photogenic and articulate students to explain their projects on the air'],
                                            ['eloquent', 'fluent', 'silver-tongued', 'well-spoken'],
                                            ['inarticulate', 'ineloquent', 'unvocal'])]),
                              Word('ascendant', "",
                                   [TestWay('adj',
                                            '有影响力的, 主宰的',
                                            'dominant in position or influence; superior.',
                                            ['This idea was in the ascendant. 这种思想处于主导地位。'],
                                            ['superior', 'dominant', 'sovereign'],
                                            ['having no influence/power']),
                                    TestWay('adj',
                                            '.上升的',
                                            'moving upward: rising',
                                            ['The teacher told the students to write even numbers in ascendant order. 老师让学生们按升序写出偶数。'],
                                            antonyms = ['declining'])]),
                              Word('ascetic', "",
                                   [TestWay('adj',
                                            '禁欲的',
                                            'practicing strict self-denial as a measure of personal and especially spiritual discipline',
                                            ['This is an ascetic diet of rice and beans. 这是一顿禁欲的隐私, 只有米饭和豌豆。'],
                                            ['abstemious', 'abstinent', 'self-denying'],
                                            ['sumptuous', 'luxurious', 'licentious', 'sybaritic', 'voluptuous']),
                                    TestWay('n',
                                            '禁欲者',
                                            'a person who renounces material comforts and leads a life of austere self-discipline, especially as an act of religious devotion',
                                            ['We normally see an ascetic meditating in a Yogic pose. 我们通常会看见一个苦行者以瑜伽的姿势来冥想。'],
                                            ['stoic', 'spartan'],
                                            ['sybarite', 'hedonist', 'voluptuary', '奢侈逸乐的', '人享乐主义者', '酒色之徒'])]),
                              Word('aseptic', "",
                                   [TestWay('adj',
                                            '消毒的, 无菌的',
                                            'preventing infection',
                                            ['Surgery must be in aseptic environments. 手术必须处在无菌环境下'],
                                            ['sterile, germfree'],
                                            ['germy', 'unsterile', 'contaminated', 'tainted']),
                                    TestWay('adj',
                                            '缺乏活力的',
                                            'lacking vitality',
                                            synonyms = ['inactive', 'lackadaisical', 'languid', 'listless', 'spiritless'],
                                            antonyms = ['active', 'animated', 'energetic', 'energetic', 'vivacious']),
                                    TestWay('adj',
                                            '冷漠的',
                                            'emotion, or warmth',
                                            ['aseptic essays 没有感情的文章', 'an aseptic smile 漠然的微笑'],
                                            ['affectlessness', 'emotionlessness', 'impassiveness', 'impassivity', 'insensibility', 'numbness', 'phlegm'],
                                            ['emotion', 'feeling', 'sensibility'])]),
                              Word('askew', "",
                                   [TestWay('adj',
                                            '不成直线, 歪的',
                                            'out of line, awry',
                                            ['The picture hung askew. 画挂歪了。', 'His tie was askew. 他的领带歪了。'],
                                            ['crooked', 'cockeyed', 'oblique', 'lopsided', 'skewed', 'aslant', 'slanted', 'slanting', 'listing', 'tilted', 'awry'],
                                            ['aligned', 'straight', 'erect'])])])
list2_unit6 = VocabularyList([Word('aspect', "",
                                   [TestWay('n',
                                            '外表, 容貌',
                                            'appearance to the eye or mind',
                                            ['His face had a frightening aspect. 他的脸很吓人。'],
                                            ['appearance', 'look', 'figure', 'presence', 'mien'])]),
                              Word('asperity', "",
                                   [TestWay('n',
                                            '(举止、性情)粗暴',
                                            'roughness of manner or of temper',
                                            ['She responded with such asperity that we knew she was offended by the question. 她如此粗鲁的回答问题以至于我们知道这个问题冒犯到了她。'],
                                            ['roughness', 'crudity', 'rudeness', 'poignancy', 'harshness'],
                                            ['softness', 'mildness']),
                                    TestWay('n',
                                            '(环境)艰苦',
                                            'rigor, severity',
                                            ['He has encountered more than his share of asperities on the road to success. 在成功的道路上他已经遇到过比他应该承受的更多的艰辛。'],
                                            ['severity', 'hardness', 'hardship', 'rigor'])]),
                              Word('aspersion', "",
                                   [TestWay('n',
                                            '诽谤, 中伤',
                                            "a false or misleading charge meant to harm someone's reputation",
                                            ['cast aspersions on my loyalty 诽谤我的忠诚'],
                                            ['defamation', 'besmirchment', 'calumny', 'calumniation', 'maligning', 'obloquy', 'vilification'],
                                            ['glowing tribute', 'eulogy', 'extolling', 'laudation', 'praise', 'commendation', 'compliment', 'flattery', 'adulation'])]),
                              Word('aspirant', "",
                                   [TestWay('n',
                                            '有抱负者, 有野心者',
                                            'one who aspires, as to advancement, honors, or a high position',
                                            ['a bevy of ever-smiling aspirants for the Miss America title 一群想当美国小姐的少女', 'Envy can make oneself backward, self-confidence can tells him to be a aspirant. 妒忌能使自己落后, 自信能使自己上进。'],
                                            ['seeker'],
                                            ['noncandidate']),
                                    TestWay('adj',
                                            '想成为…的',
                                            'seeking to attain a desired position or status',
                                            ['The pilot was an aspirant astronaut. 这个飞行员想成为航天员。'])]),
                              Word('assent', "",
                                   [TestWay('vi',
                                            '同意',
                                            'to agree to something especially after thoughtful consideration',
                                            ['The general proposed a detailed plan and the president assented. 将军提出了一个细节化的计划, 总统同意了该计划。'],
                                            ['accede', 'agree', 'assent', 'consent', 'subscribe', 'come round'],
                                            ['dissent', 'disagree'])]),
                              Word('assert', "",
                                   [TestWay('vt',
                                            '断言, 肯定地说出',
                                            'to state or declare positively and often forcefully or aggressively',
                                            ['asserted one’s innocence 坚称自己无罪', 'He asserted that there were corrupt officials in the government. 他断言道政府里面一定存在腐败的官员。'],
                                            ['aver', 'allege', 'avow', 'avouch', 'insist'],
                                            ['deny', 'gainsay'])]),
                              Word('assertive', "",
                                   [TestWay('adj',
                                            '武断的, 强烈自信的',
                                            'inclined to bold or confident assertion; aggressively self-assured',
                                            ['You will have to make many personal judgments when being assertive. 当武断的时候你不得不做出很多个人选择。'],
                                            ['assertory', 'self-assured', 'self-assertive', 'peremptory'],
                                            ['diffident'])]),
                              Word('assess', "",
                                   [TestWay('v',
                                            '评估重要性、尺寸、价值等',
                                            'to determine the importance, size, or value of',
                                            ['We need to assess whether or not the system is working. 我们需要评估这个系统是否工作。', 'Damage to the boat was assessed at $5,000. 船的损失是$5,000。'],
                                            ['evaluate', 'appraise', 'guesstimate']),
                                    TestWay('v',
                                            '征收费用(如罚款)',
                                            'to establish or apply as a charge or penalty',
                                            ['The utility company will assess a fee if your payment is late. 如果你付款晚了, 公共事业公司会罚款。'],
                                            ['assess', 'charge', 'exact', 'fine', 'lay', 'levy', 'put'],
                                            ['remit'])]),
                              Word('assiduous', "",
                                   [TestWay('adj',
                                            '勤勉的, 专心仔细的',
                                            'marked by careful unremitting attention or persistent application; busy',
                                            ['tended his garden with assiduous attention 专心仔细地照看他的花园', 'The project required some assiduous planning. 项目需要细心的规划。'],
                                            ['diligent', 'industrious', 'sedulous'],
                                            ['idle', 'inactive', 'unbusy', 'unemployed', 'unoccupied'],
                                            'assiduity n. 勤勉: persistent application or diligence; unflagging effort.')]),
                              Word('assuage', "",
                                   [TestWay('vt',
                                            '缓和, 减轻',
                                            'to lessen the intensity of',
                                            ["He couldn't assuage his guilt over the divorce. 他无法减轻自己在离婚中的罪行。"],
                                            antonyms = ['aggravate', 'exacerbate']),
                                    TestWay('vt',
                                            '平息, 抚慰',
                                            'to pacify or calm',
                                            ['Life contains sorrows that cannot be assuaged, and it is important to be honest in acknowledging this. 生活中存在着无法平息的悲伤, 诚实地承认这个事实才是重要的。'],
                                            ['compose', 'soothe', 'calm', 'pacify', 'placate', 'appease', 'lighten', 'relieve', 'alleviate', 'allay', 'mitigate', 'moderate', 'conciliate', 'propitiate'],
                                            ['aggravate', 'annoy', 'enrage', 'exasperate', 'incense', 'infuriate', 'ire', 'irk', 'irritate', 'madden', 'nettle', 'peeve', 'provoke', 'rile', 'roil', 'vex']),
                                    TestWay('vt',
                                            '使满足',
                                            'to put an end to by satisfying',
                                            ['assuage his thirst 消渴', 'That meal certainly assuaged my hunger. 那顿大餐满足了我的口腹之欲。'],
                                            ['satisfy', 'sate', 'satiate', 'quench'])])])
list2_unit7 = VocabularyList([Word('astounding', "",
                                   [TestWay('adj',
                                            '令人吃惊的, 出乎意料的',
                                            'causing astonishment or amazement',
                                            ['The richness and variety of the undersea environment are astounding．富饶而多样的海底环境是令人惊奇的。'],
                                            ['amazing', 'astonishing', 'blindsiding', 'dumbfounding', 'shocking', 'startling', 'stunning', 'stupefying'],
                                            ['unsurprising'])]),
                              Word('astute', "",
                                   [TestWay('adj',
                                            '机敏的, 有洞察力的',
                                            'having or showing shrewdness and perspicacity',
                                            ['Astute salesmen know how to invest emotionally. 精明的推销员知道如何进行感情投资。'],
                                            ['canny', 'smart', 'shrewd', 'perspicacious', 'clear-eyed', 'clear-sighted', 'savvy', 'hardheaded'],
                                            ['unknowing'])]),
                              Word('asunder', "",
                                   [TestWay('adv',
                                            '分离成多部分或多片',
                                            'into separate parts or pieces',
                                            ['broken asunder 打碎', 'Buildings were burst asunder. 建筑物已经被炸成碎片了。'],
                                            ['piecemeal'],
                                            ['in a piece', 'together']),
                                    TestWay('adv',
                                            '分离',
                                            'apart from each other in position',
                                            ['A quite conscience sleeps in thunder, but rest and guilt live far asunder. 平静的良心能在雷声中入睡, 而安宁和负罪则无法毗邻。'],
                                            ['apart'],
                                            ['together'])]),
                              Word('asylum', "",
                                   [TestWay('n',
                                            '收容所/ 保护所',
                                            'an inviolable place of refuge and protection giving shelter to criminals and debtors/something (as a building) that offers cover from the weather or protection from danger',
                                            ['an insane asylum 疯人院', "The embassy serves as an asylum for that country's nationals in need of help. 大使馆作为那国需要帮助的"],
                                            ['harbor', 'haven', 'refuge', 'sanctuary', 'sanctum'])]),
                              Word('asymmetrical', "",
                                   [TestWay('adj',
                                            '不平衡的,不对称的',
                                            'having no balance or symmetry',
                                            ['the asymmetrical construction 非对称的建筑'],
                                            ['asymmetric', 'nonsymmetrical', 'unsymmetrical', 'unbalanced'],
                                            ['symmetrical', 'balanced'])]),
                              Word('atone', "",
                                   [TestWay('v',
                                            '赎罪, 弥补',
                                            'to make amends, as for a sin or fault',
                                            ['Blood must atone for blood. 以命抵命。', 'Even death cannot atone for the offence. 罪不容诛。'],
                                            ['redeem'])]),
                              Word('atrocious', "",
                                   [TestWay('adj',
                                            '极坏的, 极其残忍的',
                                            'extremely wicked, brutal, or cruel',
                                            ['Murder is an atrocious crime.  谋杀是极其恶劣的犯罪活动'],
                                            ['heinous'],
                                            ['benign', 'kind', 'kindhearted', 'benignant', 'good-hearted', 'humane', 'sympathetic', 'tenderhearted']),
                                    TestWay('adj',
                                            '让人极为不满意的',
                                            'extremely unsatisfactory',
                                            ['The service on plane was atrocious.  机上的服务让人极为不满意。'],
                                            antonyms = ['satisfactory', 'wonderful'])]),
                              Word('attenuate', "",
                                   [TestWay('v',
                                            '使降低(数量, 力量, 价值)',
                                            'to lessen the amount, force, magnitude, or value of',
                                            ['an investment attenuated by inflation 一份因通货膨胀而贬值的投资.'],
                                            ['cheapen', 'devalue', 'downgrade', 'reduce', 'write down'],
                                            ['appreciate', 'enhance', 'upgrade', 'mark up'],
                                            'attenuation n. 弱化, 贬值')]),
                              Word('audacious', "",
                                   [TestWay('adj',
                                            '大胆的, (但往往)愚勇的',
                                            'fearlessly, often recklessly daring; bold',
                                            ['an audacious plan 一个冒进的计划'],
                                            ['bold', 'adventurous', 'brash', 'brassy', 'brazen', 'rash', 'reckless'],
                                            ['cautious', 'circumspect', 'guarded', 'wary']),
                                    TestWay('adj',
                                            '蔑视(法律、礼节)的, 无礼的',
                                            'contemptuous of law, religion, or decorum',
                                            synonyms = ['mpertinent', 'impudent', 'insolent'],
                                            antonyms = ['timid', 'meek']),
                                    TestWay('adj',
                                            '乐于冒险的',
                                            'inclined or willing to take risks',
                                            ['audacious adventurers risking everything they had for a shot at glory 为了荣誉而孤注一掷的冒险家们'],
                                            ['daring', 'emboldened', 'enterprising', 'nervy', 'venturesome']),
                                    TestWay('adj',
                                            '大胆创新的',
                                            'marked by originality and verve',
                                            ['an audacious interpretation of two dramas 对两部戏剧的创造性阐述'],
                                            other_form = 'audacity n. 胆量, 不敬')]),
                              Word('augur', "",
                                   [TestWay('n',
                                            '预言家',
                                            'one who predicts future events or developments',
                                            ['The ancient Roman augurs predicted the future by reading the flight of birds. 古罗马的预言家们通过鸟类的航线来预测未来'],
                                            ['forecaster', 'foreseer', 'diviner', 'foreteller', 'prophesier', 'visionary']),
                                    TestWay('v',
                                            '出现好兆头',
                                            'to show signs of a favorable or successful outcome',
                                            ['This augurs well for us. 这是一个好兆头'],
                                            ['forebode', 'promise'],),
                                    TestWay('vt',
                                            '预言',
                                            'to tell of or describe beforehand',
                                            ['The fortune-teller augured nothing but a series of calamities for me. 占卜人预言在我身上将会有一系列大灾难发生。'],
                                            ['forecast', 'predict', 'presage', 'prognosticate', 'prophesy'])])])
list2_unit8 = VocabularyList([Word('authentic', "",
                                   [TestWay('adj',
                                            '真实的, 非仿造的',
                                            'being exactly as appears or as claimed',
                                            ['found an authentic Native American arrowhead 发现了一支美洲土著的箭头'],
                                            ['bona fide', 'certified', 'genuine'],
                                            ['bogus', 'counterfeit', 'fake', 'mock', 'phony', 'spurious']),
                                    TestWay('adj',
                                            '准确的, 相符合的',
                                            'following an original exactly',
                                            ['an authentic reconstruction of the Parthenon 帕台农神殿的准确复刻'],
                                            ['accurate', 'exact', 'precise', 'right', 'veracious'],
                                            ['corrupt', 'false'],
                                            'authenticity n. 真实, 真实性')]),
                              Word('authority', "",
                                   [TestWay('n',
                                            '(某领域的)权威人士',
                                            'a person with a high level of knowledge or skill in a field',
                                            ['a leading authority on neural anatomy 一名神经解剖学领域的权威人士'],
                                            ['expert', 'connoisseur', 'maestro', 'master', 'virtuoso'],
                                            ['amateur', 'inexpert']),
                                    TestWay('n',
                                            '管辖权, 控制',
                                            'lawful control over the affairs of a political unit (as a nation)',
                                            ['The sheriff had authority over the whole county. 郡守对于整个郡都有管辖权'],
                                            ['administration', 'governance', 'regime', 'regimen']),
                                    TestWay('n',
                                            '影响力',
                                            'the power to direct the thinking or behavior of others usually indirectly',
                                            ['He speaks with a persuasive authority on matters of public health. 他就公共健康事务发表了带有影响力的、令人信服的评论'],
                                            ['clout', 'credit', 'leverage', 'weight']),
                                    TestWay('n',
                                            '(管束他人的)权力',
                                            'the right or means to command or control others',
                                            ['By the authority vested in me, I now pronounce you married. 依我所拥有的权力, 我宣布你们成为夫妻'],
                                            ['arm', 'command', 'control', 'dominion', 'reign'],
                                            ['impotence', 'powerlessness']),
                                    TestWay('n',
                                            '根据, 理由',
                                            'a warrant for action',
                                            ['On what authority do you make such a claim? 你的指控有何理由?'],
                                            ['grounds', 'justification'])]),
                              Word('autocracy', "",
                                   [TestWay('n',
                                            '独裁政府',
                                            'government in which a person possesses unlimited power',
                                            ['It signified the British rejection of autocracy by constituting the first formal restraining of the power of the monarch 英国对于独裁体制的反抗表现在它对君王权力进行的正式约束'],
                                            ['absolutism', 'dictatorship', 'totalitarianism', 'tyranny'],
                                            ['democracy'],
                                            'autocratic adj. 独裁的')]),
                              Word('autonomy', "",
                                   [TestWay('n',
                                            '政治上的独立',
                                            'the quality or state of being self-governing',
                                            ['The province has been granted autonomy. 这个省份被授予了自治权'],
                                            ['self-governance', 'sovereignty'],
                                            ['dependence', 'subjection']),
                                    TestWay('n',
                                            '自我主导的自由, 尤其是精神独立',
                                            'self-directing freedom and especially moral independence',
                                            ['a teacher who encourages individual autonomy 一个鼓励精神独立的老师'],
                                            ['independence', 'liberty', 'free will'],
                                            ['constraint', 'duress'],
                                            'autonomous adj. 自治的')]),
                              Word('avarice', "",
                                   [TestWay('n',
                                            '贪财, 贪婪',
                                            'excessive or insatiable desire for wealth or gain',
                                            ["The bank official's embezzlement was motivated by pure avarice. 银行官员盗用公款纯粹是出于贪婪"],
                                            ['acquisitiveness', 'avidity', 'covetousness', 'cupidity', 'greediness', 'rapacity'],
                                            ['generosity', 'magnanimity'],
                                            'avaricious adj. 贪婪的')]),
                              Word('aver', "",
                                   [TestWay('v',
                                            '声称为真',
                                            'to state as a fact usually forcefully',
                                            ['was tearfully averring his innocence 涕泪俱下地声明他的清白'],
                                            ['allege', 'assert', 'avouch', 'avow', 'declare', 'purport', 'warrant'],
                                            ['deny', 'gainsay']),
                                    TestWay('v',
                                            '(态度强硬而明确地)声明',
                                            'to state clearly and strongly',
                                            ["She averred that she didn't need any help choosing her own clothes. 她态度强硬地声明: 在买衣服的问题上不需要别人指手画脚"],
                                            ['affirm', 'insist', 'maintain', 'profess'])]),
                              Word('aversion', "",
                                   [TestWay('n',
                                            '非常讨厌, 极厌恶',
                                            'a dislike so strong as to cause stomach upset or queasiness',
                                            ['a natural aversion toward insects 天生对昆虫的反感'],
                                            ['distaste', 'horror', 'loathing', 'nausea', 'repugnance', 'repulsion', 'revulsion']),
                                    TestWay('n',
                                            '令人厌恶的事物',
                                            'something or someone that is hated',
                                            ['Clichés should be the aversion of every good writer. 陈词滥调应该是让每个优秀的作家都感到厌恶的。'],
                                            ['abhorrence', 'abomination', 'antipathy', 'detestation', 'execration'],
                                            ['love'])]),
                              Word('avid', "",
                                   [TestWay('adj',
                                            '急切渴望的',
                                            'marked by keen interest and enthusiasm',
                                            ['avid movie fans 急切的影迷'],
                                            ['agog', 'ardent', 'eager', 'keen', 'impatient', 'thirsty'],
                                            ['apathetic', 'indifferent']),
                                    TestWay('adj',
                                            '贪婪(钱财)的',
                                            'having or marked by an eager and often selfish desire especially for material possessions',
                                            ['She stared at the jewels with an avid glint in his eye. 她带着贪婪的目光注视着那些珠宝'],
                                            ['acquisitive', 'avaricious', 'covetous', 'greedy', 'rapacious'],
                                            other_form = 'avidity n. 贪婪')]),
                              Word('awash', "",
                                   [TestWay('adj',
                                            '被淹没的',
                                            'containing, covered with, or thoroughly penetrated by water',
                                            ['The streets were awash from the heavy rains. 街道因为大雨被水淹没了'],
                                            ['doused', 'drenched', 'saturated', 'sodden', 'soggy', 'soaked', 'afloat'],
                                            ['dry', 'arid', 'dehydrated', 'drained']),
                                    TestWay('adj',
                                            '(如洪水般)泛滥的',
                                            'filled, covered, or completely overrun as if by a flood',
                                            ['The program is currently awash in submissions and will not be accepting any more until next term. 该项目的申请人数过多, 因此下一轮之前不会再接受任何申请'],
                                            ['abounding', 'abundant', 'flush', 'fraught', 'replete', 'swarming', 'teeming', 'thronging'],
                                            ['dearth', 'insufficient', 'scant'])]),
                              Word('awe', "",
                                   [TestWay('n./v',
                                            '敬畏',
                                            'an emotion variously combining dread, veneration, and wonder that is inspired by authority or by the sacred or sublime',
                                            ['She gazed in awe at the great stone. 她敬畏地凝视着那块巨石'],
                                            ['admiration', 'reverence', 'respect', 'veneration'],
                                            ['irreverence', 'insolence', 'scorn', 'superciliousness'])])])
list2_unit9 = VocabularyList([Word('awkward', "",
                                   [TestWay('adj',
                                            '缺乏灵活性和技巧的',
                                            'lacking dexterity or skill',
                                            ['awkward with a needle and thread 缺乏灵巧的针线活技术'],
                                            ['handless', 'maladroit'],
                                            ['adroit', 'deft', 'dexterous', 'proficient', 'skilled']),
                                    TestWay('adj',
                                            '(处理问题)缺乏手段和智谋的',
                                            'showing or marked by a lack of skill and tact (as in dealing with a situation)',
                                            ['Her awkward handling of the seating arrangements resulted in many hurt feelings. 她那缺乏智谋的座次安排伤害了许多人的感情'],
                                            ['botched', 'bungling', 'fumbled', 'inept', 'inexpert', 'maladroit']),
                                    TestWay('adj',
                                            '臃肿笨拙的, 不优雅的',
                                            'lacking ease or grace (as of movement or expression)',
                                            ['an awkward design 一份粗劣的设计'],
                                            ['clumsy', 'gauche', 'graceless', 'gawkish'],
                                            ['elegant', 'graceful', 'polished', 'lithe', 'coordinated']),
                                    TestWay('adj',
                                            '令人尴尬的',
                                            'causing embarrassment',
                                            ['the awkward situation of having to listen as your host and hostess quarrel loudly in the next room 不得不听着你的主人和她太太在隔壁大声争吵的尴尬境地'],
                                            ['discomfiting', 'disturbing', 'disconcerting', 'embarrassing', 'flustering']),
                                    TestWay('adj',
                                            '(因过大过重或设计问题)难以操作的',
                                            'difficult to use or operate especially because of size, weight, or design',
                                            ['The manual can opener is too awkward to hold. 那个手动启瓶器太难握了'],
                                            ['ponderous', 'ungainly', 'unhandy', 'unwieldy', 'bunglesome', 'cranky'],
                                            ['handy'])]),
                              Word('awning', "",
                                   [TestWay('n',
                                            '雨棚, 遮阳棚',
                                            'a piece of material attached to a caravan or building which provides shelter from the run or sun',
                                            ['stayed under the awning outside the Starbucks during the rainstorm 在星巴克外面的遮阳棚里躲雨'],
                                            ['awning', 'ceiling', 'cover', 'roof', 'tent'])]),
                              Word('awry', "",
                                   [TestWay('adj',
                                            '弯曲或扭曲的',
                                            'in a turned or twisted position or direction',
                                            ['Her sunglass is awry. 她墨镜戴歪了'],
                                            ['askew', 'aslant', 'lopsided', 'slanted'],
                                            ['aligned', 'direct', 'even', 'straight']),
                                    TestWay('adj./adv',
                                            '走样的(地), 出差错的(地)',
                                            'off the correct or expected course',
                                            ['Operation Redwing was initially launched by US special-operation troops in hopes of capturing or killing a Taliban leader but went awry. 由美军特种部队发起、代号为“红翼”的军事行动的起初目的是捕获或击杀一名塔利班头目, 然而行动在执行过程中出现了差错。'],
                                            ['amiss', 'aside', 'astray', 'erroneous'],
                                            ['right', 'well'])]),
                              Word('axiomatic', "",
                                   [TestWay('adj',
                                            '公理的',
                                            'based on or involving an axiom or system of axioms',
                                            ['Euclidean geometry is based on five axiomatic principles. 欧几里得几何学是在五条公理的基础上建立的。'],
                                            ['dictum', 'fundamental', 'maxim']),
                                    TestWay('adj',
                                            '不言自明的',
                                            'taken for granted, self-evident',
                                            ['an axiomatic truth 一个不言而明的真理'],
                                            ['self-evident', 'prima facie'],
                                            ['controversial'],
                                            'axiom n. 公理')]),
                              Word('babble', "",
                                   [TestWay('v',
                                            '发出含糊无意义的嘟囔声, 胡乱说',
                                            'to utter a meaningless confusion of words or sounds',
                                            ['Babies babble before they can talk. 婴儿在会说话以前含糊不清地发音'],
                                            ['drivel', 'gabble', 'gibber', 'jabber', 'prattle', 'abracadabra'],
                                            ['articulate']),
                                    TestWay('v',
                                            '闲聊',
                                            'to engage in casual or rambling conversation',
                                            ['The little girls babbled contentedly for the whole ride home. 两个小姑娘在回家的路上高兴地闲聊。'],
                                            ['chatter', 'prate'])]),
                              Word('backhanded', "",
                                   [TestWay('adj',
                                            '间接的, 含沙射影的, 虚情假意的',
                                            'indirect, devious, especially sarcastic',
                                            ['a backhanded compliment 虚情假意的恭维话'],
                                            ['feigned', 'roundabout', 'sarcastic', 'hypocritical', 'two-faced', 'double-faced', 'left-handed'],
                                            ['forthright', 'artless', 'candid', 'genuine', 'honest', 'sincere'])]),
                              Word('badger', "",
                                   [TestWay('vt',
                                            '不断纠缠或骚扰',
                                            'to harass or annoy persistently',
                                            ['badger him into purchasing 不断地骚扰劝说他购买'],
                                            ['bait', 'plague'])]),
                              Word('badinage', "",
                                   [TestWay('n',
                                            '打趣, 善意的玩笑',
                                            'playful repartee, banter',
                                            ['the sophisticated badinage of the characters in plays by Oscar Wilde 奥斯卡·王尔德作品中意味深长的玩笑话'],
                                            ['banter', 'persiflage', 'repartee'])]),
                              Word('bait', "",
                                   [TestWay('v',
                                            '逗弄, 激怒',
                                            'to persecute or exasperate with unjust, malicious, or persistent attacks',
                                            ['bait him with gibes about his humble origin 取笑他的平凡出身以烦扰他'],
                                            ['badger', 'annoy', 'harass', 'heckle'],
                                            ['appease', 'pacify', 'mollify', 'disarm']),
                                    TestWay('v',
                                            '引诱',
                                            'to lead away from a usual or proper course by offering some pleasure or advantage',
                                            ['the investment scheme baits the greedy and the unscrupulous 这份投资计划吸引贪婪者和轻信者上钩'],
                                            ['allure', 'decoy', 'entice', 'seduce']),
                                    TestWay('n',
                                            '诱饵',
                                            'something (as food) used in luring especially to a hook or trap',
                                            ['The squad leader has finally realized that his team was a bait. 队长终于意识到他的队伍是一个诱饵。'],
                                            ['allurement', 'snare', 'trap', 'temptation'])]),
                              Word('bale', "",
                                   [TestWay('n',
                                            '痛苦, 悲哀',
                                            'woe, sorrow',
                                            ['relieve spirit from the bale 从悲痛中解脱'],
                                            ['misery', 'suffering', 'anguish', 'grief'],
                                            ['joy'])])])
list2_unit10 = VocabularyList([Word('baleful', "",
                                   [TestWay('adj',
                                            '有害的',
                                            'harmful or malignant in intent or effects',
                                            ['a policy with baleful effects 一个带来不良后果的政策'],
                                            ['harmful', 'pernicious', 'detrimental'],
                                            []),
                                    TestWay('adj',
                                            '凶兆的',
                                            'foreboding or threatening evil',
                                            ['a baleful look 面露凶色'],
                                            ['direful', 'doomy', 'ominous', 'ill-boding', 'minatory', 'portentous', 'sinister'],
                                            ['unthreatening']),
                                    TestWay('',
                                            '致命的',
                                            'likely to cause or capable of causing death',
                                            ['a medicine that is beneficial in small doses but baleful in large 是药三分毒'],
                                            ['deadly', 'fatal', 'lethal'],
                                            ['healthy', 'wholesome'])]),
                              Word('balk', "",
                                   [TestWay('v',
                                            '阻碍',
                                            'to check or stop by or as if by an obstacle',
                                            synonyms = ['circumvent', 'frustrate', 'foil', 'thwart'],
                                            antonyms = ['advance', 'forward', 'foster', 'nurture', 'promote']),
                                    TestWay('v',
                                            '不愿接受, 拒绝',
                                            'to show unwillingness to accept, do, engage in, or agree to',
                                            ['She balked at the very idea of compromise. 她固执地拒绝妥协的想法。'],
                                            ['decline', 'refuse', 'spurn', 'repudiate', 'turn down'],
                                            ['accept', 'approve'],
                                            'balky adj. 倔强的')]),
                              Word('balky', "",
                                   [TestWay('adj',
                                            '不服管束的, 倔强的',
                                            'refusing or likely to refuse to proceed, act, or function as directed or expected',
                                            ['a balky mule 犟骡子'],
                                            ['contumacious', 'defiant', 'perverse', 'intractable', 'obstreperous', 'refractory', 'unruly', 'untoward', 'wayward', 'willful'],
                                            ['compliant', 'docile', 'subdued', 'submissive', 'tractable'])]),
                              Word('ballad', "",
                                   [TestWay('n',
                                            '由简单诗节和叠句组成的民歌',
                                            'a narrative poem, often of folk origin and intended to be sung, consisting of simple stanzas and usually having a refrain',
                                            ['a haunting ballad about loneliness 一段有关寂寞的缭绕于心的民谣'],
                                            ['ditty', 'jingle', 'lyric', 'vocal'])]),
                              Word('balloon', "",
                                   [TestWay('v',
                                            '迅速增加',
                                            'to increase rapidly',
                                            ['The use of computers has ballooned. 电脑的使用量迅速增长。'],
                                            ['inflate', 'escalate', 'expand', 'burgeon', 'mushroom', 'snowball'],
                                            ['decrease', 'taper', 'dwindle', 'diminish', 'recede', 'wane'])]),
                              Word('balm', "",
                                   [TestWay('n',
                                            '香油, 止痛膏, 安慰物',
                                            'a sweet-smelling oil that heals wounds or reduce pain',
                                            ["Friendship is the finest balm in need. 危难关头, 友情是最好的安慰。"],
                                            antonyms = ['irritant'],
                                            other_form = 'balmy adj. 柔和的'),
                                    TestWay('n',
                                            '香气',
                                            'a sweet or pleasant smell',
                                            ["The balm of the restaurant's backyard garden enhances the aura of romance. 餐馆后院传来的阵阵芳香增加了浪漫的情调。"],
                                            ['aroma', 'fragrance', 'incense', 'perfume', 'redolence'],
                                            ['fetor', 'malodor', 'stench', 'stink'])]),
                              Word('banal', "",
                                   [TestWay('adj',
                                            '非原创的, 陈腐的',
                                            'lacking originality, freshness, or novelty; trite',
                                            ['The slogan is too banal. 这口号已是陈词滥调了'],
                                            [ 'cliché', 'hackneyed', 'stereotyped', 'threadbare', 'trite', 'timeworn', 'shopworn', 'stale', 'moth-eaten'],
                                            ['novel', 'innovative', 'arresting'],
                                            'banality n. 陈腐')]),
                              Word('bane', "",
                                   [TestWay('n',
                                            '祸根',
                                            'a source of harm or ruin',
                                            ['Drinking was the bane of his life. 饮酒是他一生的祸根。'],
                                            ['affliction', 'curse', 'nemesis', 'scourge'],
                                            ['blessing', 'boon', 'felicity', 'windfall']),
                                    TestWay('n',
                                            '有害的物质',
                                            'a substance that by chemical action can kill or injure a living thing',
                                            ['a plant that is believed to be the bane of the wolf 一种被认为对狼有毒害作用的植物'],
                                            ['toxic', 'toxin', 'venom'],
                                            other_form = 'baneful adj. 有害的')]),
                              Word('banish', "",
                                   [TestWay('vt',
                                            '驱逐出境',
                                            'to require by authority to leave a country',
                                            ['Since the diplomatic relation between the two nations has been broken, diplomats were all banished. 随着两国外交关系的断裂, 所有的外交人员都被驱逐出境'],
                                            ['deport', 'exile', 'expatriate', 'expel'],
                                            ['repatriate']),
                                    TestWay('vt',
                                            '赶出',
                                            'to drive or force out',
                                            ['permanently banished the troublemakers from the youth recreational center 永久剥夺肇事者进入青年娱乐中心的权力'],
                                            other_form = 'banishment n. 驱逐')]),
                              Word('banter', "",
                                   [TestWay('n./v',
                                            '幽默、打趣的(地)谈话',
                                            'good-humored, playful conversation',
                                            ['banter with someone 和某人调侃'],
                                            ['badinage', 'persiflage', 'repartee'])])])

LIST2 = VocabularyList(list2_unit1.words+list2_unit2.words+list2_unit3.words+list2_unit4.words+list2_unit5.words+list2_unit6.words+list2_unit7.words+list2_unit8.words+list2_unit9.words+list2_unit10.words)
