#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list16_unit1 = VocabularyList([Word('mingle', "",
                                   [TestWay('vi',
                                            '参加社交活动',
                                            'to take part in social activities',
                                            ["mingling at a cocktail party 在鸡尾酒会上与他人交往"],
                                            'associate, fraternize, socialize'),
                                    TestWay('vt',
                                            '混合, 结合',
                                            'to mix so that the components become united',
                                            ["mingle the ingredients 将调料混合", "mingle fact and fiction 糅杂了现实与幻想"],
                                            'mix, amalgamate, blend, commingle, immingle, intermix, merge',
                                            'divide, separate, sunder')]),
                              Word('minimize', "",
                                   [TestWay('vt',
                                            '将…减到最少',
                                            'to reduce to the smallest possible amount, extent, size, or degree',
                                            ["All striking forces are told to minimize civilian casualties. 所有攻击部队被要求尽可能减少平民伤亡"],
                                            'deprecate, diminish, discount, reduce',
                                            'inflate, magnify, maximize'),
                                    TestWay('vt',
                                            '刻意低估',
                                            'to underestimate intentionally',
                                            ["minimize losses in our own company while maximize those of the rival 低估我方损失而高估对手损失"],
                                            'underestimate, underrate, undervalue',
                                            'overestimate, exaggerate'),
                                    TestWay('vt',
                                            '表示鄙夷',
                                            "to express scornfully one's low opinion of",
                                            ["Sore losers minimized the other team's victory. 愤愤不平的失败者对获胜方的胜利表现出鄙夷"],
                                            'belittle, denigrate, deprecate, depreciate, derogate, diminish, disparage, trash, vilipend',
                                            'acclaim, applaud, exalt, extol, glorify, laud, magnify, praise',
                                            'minimum adj. 最小的')]),
                              Word('mint', "",
                                   [TestWay('n',
                                            '巨额',
                                            'an abundant amount, especially of money',
                                            ["worth a mint 价值连城"],
                                            'bomb, boodle, bundle, fortune, pile, wad',
                                            'mite, modicum'),
                                    TestWay('adj',
                                            '无损坏的',
                                            'unmarred as if fresh from a mint',
                                            ["a second-handed laptop in mint condition 一台几乎全新的二手笔记本电脑"],
                                            'intact, original, perfect, pristine, unmarred, virginal',
                                            'impaired, damaged, stale')]),
                              Word('miniscule', "",
                                   [TestWay('adj',
                                            '极小的',
                                            'very small',
                                            ["a miniscule progress 极小的进步"],
                                            'atomic, infinitesimal, microscopic, miniature, minute, tiny',
                                            'colossal, elephantine, enormous, gargantuan, gigantic, huge, immense, mammoth, prodigious')]),
                              Word('minute', "",
                                   [TestWay('adj',
                                            '仔细的, 谨小慎微的',
                                            'characterized by careful scrutiny and close examination',
                                            ["a minute description of the setting of the story 故事背景的详细介绍"],
                                            'circumstantial, elaborate, full, particular, particularized, thorough',
                                            'brief, compendious, concise, succinct, summary, terse'),
                                    TestWay('adj',
                                            '小的, 不重要的',
                                            'very small or of small importance',
                                            ["It is not sagacious to invest excessively in minute details. 过分投入于不重要的细枝末节上是不明智的"],
                                            'frivolous, incidental, inconsiderable, insignificant, little, minor, negligible, nugatory, slight, trifling, trivial',
                                            'consequential, critical, crucial, momentous, significant, vital, weighty',
                                            'minutes n. 会议记录')]),
                              Word('minutia', "",
                                   [TestWay('n',
                                            '次要的细节, 小事',
                                            'a minute or minor detail',
                                            ["plagued by minutiae 被不重要的细节困扰"],
                                            'triviality',
                                            'gist')]),
                              Word('mirage', "",
                                   [TestWay('n',
                                            '海市蜃楼, 幻想',
                                            'something illusory and unattainable like a mirage',
                                            ["Reunion with her husband has become a mirage. 与他丈夫重逢已是可望而不可及的幻象", "A peaceful solution proved to be a mirage. 和平解决问题是不可能的了"],
                                            'chimera, delusion, hallucination, illusion, phantom, vision',
                                            'reality')]),
                              Word('mire', "",
                                   [TestWay('n',
                                            '困境',
                                            'a difficult, puzzling, or embarrassing situation from which there is no easy escape',
                                            ["stuck in a mire of emotional dependency 陷于感情依赖的困境中"],
                                            'dilemma, hole, impasse, jam, pickle, quagmire, rattrap, swamp'),
                                    TestWay('vt',
                                            '使陷入困境, 拖后腿',
                                            'to hamper or hold back as if by mire',
                                            ["be mired in the past 陷于过去的回忆不能自拔"],
                                            'bog, broil, delay, detain, entangle, entrap, retard',
                                            'enfranchise, extricate, free, liberate, rescue')]),
                              Word('mirth', "",
                                   [TestWay('n',
                                            '欢乐, 欢笑',
                                            'gladness or gaiety as shown by or accompanied with laughter',
                                            ["a man of little mirth 不苟言笑之人"],
                                            'cheer, festivity, gaiety, glee, happiness, hilarity, jocundity, joviality, lightheartedness',
                                            'dejection, depression, desolation, despondence, doldrums, melancholy, oppression',
                                            'mirthful adj. 高兴的')]),
                              Word('misanthropic', "",
                                   [TestWay('adj',
                                            '反人类的',
                                            'having or showing a deep distrust of human beings and their motives',
                                            ["a solitary and misanthropic artist 一个孤立的反人类艺术家"],
                                            'antisocial, cynical, pessimistic',
                                            'philanthropic, uncynical',
                                            'misanthrope n. 反人类份子')])])

list16_unit2 = VocabularyList([Word('misbehaving', "",
                                   [TestWay('adj',
                                            '调皮的, 行为不端的',
                                            'engaging in or marked by childish misbehavior',
                                            ["a new approach for disciplining a chronically misbehaving child 一个教育调皮小孩的新方法"],
                                            'annoying, devious, errant, impish, mischievous, naughty, playful, wicked',
                                            'decorous, urbane')]),
                              Word('mischievous', "",
                                   [TestWay('adj',
                                            '调皮的, 调皮的',
                                            'playful in a naughty or teasing way',
                                            ["The mischievous child broke the vase. 调皮的孩子打碎了花瓶"],
                                            'annoying, devious, errant, impish, misbehaving, naughty, playful, wicked',
                                            'decorous, urbane'),
                                    TestWay('adj',
                                            '有害的',
                                            'causing harm or trouble',
                                            ["mischievous rumors that defame him 恶意中伤他的谣言"],
                                            'adverse, baleful, baneful, deleterious, detrimental, evil, hurtful, injurious, nocuous, noxious, pernicious',
                                            'beneficial, anodyne, benign, harmless, innocent, innocuous, inoffensive, safe')]),
                              Word('misconstrue', "",
                                   [TestWay('vt',
                                            '误解, 曲解',
                                            'to mistake the meaning of',
                                            ["An outsider might misconstrue the nature of the phenomenon. 局外者可能会曲解这个现象的本质"],
                                            'garble, misapprehend, misinterpret, misperceive, misread, misrepresent, mistake',
                                            'appreciate, apprehend, catch, comprehend, fathom, grasp, perceive, savvy, seize, understand')]),
                              Word('miscreant', "",
                                   [TestWay('n',
                                            '恶棍, 罪犯',
                                            'one who behaves criminally or viciously',
                                            ["robbed by a bunch of miscreants 遭到了一伙歹徒的抢劫"],
                                            'brute, culprit, devil, felon, fiend, offender, rascal, reprobate, villain',
                                            'cavalier, chevalier')]),
                              Word('misdemeanor', "",
                                   [TestWay('n',
                                            '轻罪',
                                            'a crime less serious than a felony',
                                            ["charged with several misdemeanors"],
                                            'infraction, infringement, offense, peccadillo, violation',
                                            'felony')]),
                              Word('miserly', "",
                                   [TestWay('adj',
                                            '吝啬的',
                                            'marked by grasping meanness and penuriousness',
                                            ["a miserly couple devoid of social conscience and responsibility 一对没有社会良心和责任感的吝啬夫妻"],
                                            'closefisted, mean, niggard, parsimonious, penurious, stingy, tightfisted',
                                            'lavish, prodigal, spendthrift, squandering, generous, liberal, munificent, openhanded',
                                            'miser n. 守财奴')]),
                              Word('misfortune', "",
                                   [TestWay('n',
                                            '不幸',
                                            'bad fortune or ill luck',
                                            ["unable to grasp why he had been struck by such a misfortune 无法理解他为何会遇上如此不幸之事"],
                                            'adversity, calamity, cataclysm, catastrophe, disaster, ill, mischance, mishap, tragedy',
                                            'fortune, luck, serendipity')]),
                              Word('misgiving', "",
                                   [TestWay('n',
                                            '担忧, 疑虑',
                                            'a feeling of doubt or suspicion especially concerning a future event',
                                            ["No one can dispel his misgiving. 没有人能打消他的疑虑"],
                                            'apprehension, distrust, doubt, dread, fear, foreboding, incertitude, skepticism, suspicion',
                                            'assurance, belief, certainty, certitude, confidence, conviction, sureness, surety, trust')]),
                              Word('mishap', "",
                                   [TestWay('n',
                                            '不幸之事',
                                            'an unfortunate accident',
                                            ["Mishap followed wherever he went. 不论他走到哪里, 厄运总是形影相随"],
                                            'adversity, calamity, cataclysm, catastrophe, disaster, ill, mischance, misfortune, tragedy',
                                            'fortune, luck, serendipity')]),
                              Word('misrepresent', "",
                                   [TestWay('vt',
                                            '误传, 篡改',
                                            'to give an incorrect or misleading representation of',
                                            ["misrepresent the facts 篡改事实真相"],
                                            'belie, color, distort, falsify, garble, misinterpret, misrelate, misstate, pervert',
                                            'clarify, explain, illuminate, illustrate',
                                            'misrepresentation n. 篡改')])])

list16_unit3 = VocabularyList([Word('mite', "",
                                   [TestWay('n',
                                            '微小的东西, 很少的钱',
                                            'a very small object, creature, or particle, a very small sum of money',
                                            ["I have only a mite left to buy lunch for the rest of the week. 我只剩下一点钱来买剩下一周几天的午饭了"],
                                            'atom, bit, hint, iota, molecule, particle, pittance, trace',
                                            'boodle, bundle, fortune, colossus')]),
                              Word('mitigate', "",
                                   [TestWay('vt',
                                            '减轻痛苦, 使缓和',
                                            'to make less severe or painful',
                                            ["powerful drugs that mitigate pains 强力的镇痛剂"],
                                            'allay, alleviate, assuage, ease, mitigate, mollify, palliate, relieve, soothe',
                                            'aggravate, exacerbate, intensify',
                                            'mitigation n. 缓和')]),
                              Word('mobile', "",
                                   [TestWay('adj',
                                            '可移动的',
                                            'capable of moving or being moved',
                                            ["a mobile missile launcher 可移动导弹发射装置"],
                                            'motile, movable, portable, transportable',
                                            'immobile, immovable'),
                                    TestWay('adj',
                                            '可变的',
                                            'changeable in appearance, mood, or purpose',
                                            ["a highly mobile face 善变的面孔"],
                                            'adaptable, fluid, inconstant, mercurial, mutable, protean, unstable, unsteady, variable, versatile',
                                            'fixed, steadfast, stable',
                                            'mobility n. 可移动性; mobilize v. 动员')]),
                              Word('mockery', "",
                                   [TestWay('n',
                                            '鄙视, 嘲弄',
                                            'scornfully contemptuous ridicule',
                                            ["Her deliberate mockery triggered a fierce fight. 她的蓄意嘲弄引起了一场激烈的打斗"],
                                            'derision, joke, mock, ridicule, scoffing',
                                            'respect, reverence, veneration'),
                                    TestWay('n',
                                            '以嘲笑为目的的模仿',
                                            'a false, derisive, or impudent imitation',
                                            ["arbitrary methods that make a mockery of justice 嘲讽司法公正的仲裁体系"],
                                            'burlesque, caricature, farce, parody, sham, travesty',
                                            'mock v. 愚弄, 嘲弄')]),
                              Word('moderate', "",
                                   [TestWay('vt',
                                            '使缓和',
                                            'to lessen the intensity or extremeness of',
                                            ["Sopranos and tenors moderates their voices to fit the size of the theater. 女高音和男高音们根据剧场的大小调节他们的声音以创造合适的效果"],
                                            'abate, diminish, dwindle, ease, lessen, lower, modulate, subside, taper, temper, wane',
                                            'escalate, enhance, expand, heighten, intensify'),
                                    TestWay('adj',
                                            '适度的, 中庸的',
                                            'being within reasonable limits; not excessive or extreme',
                                            ["The new proposals regarding defense budget were met with only moderate enthusiasm. 关于国防预算的新提案只得到了平淡的回应"],
                                            'average, conservative, fair, intermediate, mediocre, modest, reasonable, temperate',
                                            'exorbitant, excessive, extreme, radical',
                                            'immoderate adj. 不适度的')]),
                              Word('modicum', "",
                                   [TestWay('n',
                                            '少量',
                                            'a small portion; a limited quantity',
                                            ["a modicum of food quota 极少量的食物配额"],
                                            'atom, iota, mite, molecule, particle',
                                            'abundance, affluence')]),
                              Word('mollify', "",
                                   [TestWay('vt',
                                            '平息抚慰, 缓和',
                                            'to calm in temper or feeling',
                                            ["mollify the angry customer 平息消费者的怒气"],
                                            'allay, alleviate, appease, assuage, conciliate, mitigate, placate, propitiate, soothe',
                                            'aggravate, enrage, exasperate, incense, inflame, infuriate, ire, rankle, vex, antagonize',
                                            'mollification n. 安抚')]),
                              Word('mollycoddle', "",
                                   [TestWay('vt',
                                            '溺爱',
                                            'to treat with an excessive or absurd degree of indulgence and attention',
                                            ["mollycoddle his only grandson 溺爱他唯一的孙子"],
                                            'coddle, cosset, indulge, pamper, spoil',
                                            'abuse, ill-treat')]),
                              Word('molt', "",
                                   [TestWay('vi',
                                            '脱(羽、皮等)',
                                            'to shed hair, feathers, shell, horns, or an outer layer periodically',
                                            ["Snakes molt as they grow, shedding the old skin and growing a larger new skin. 随着年龄的增长, 蛇会脱去老皮, 长出新皮"],
                                            'exfoliate, exuviate, shed',
                                            'fledge')]),
                              Word('momentous', "",
                                   [TestWay('adj',
                                            '极重要的',
                                            'of utmost importance; of outstanding significance or consequence',
                                            ["Battle of Stalingrad is a momentous campaign in World War 2. 斯大林格勒之战是第二次世界大战中具有重大意义的一次战役"],
                                            'consequential, considerable, crucial, eventful, important, monumental, pivotal, significant, vital, weighty',
                                            'inconsequential, negligible, slight, trifling, trivial')])])

list16_unit4 = VocabularyList([Word('momentum', "",
                                   [TestWay('n',
                                            '动力',
                                            'impetus of a physical object in motion',
                                            ["Their luck began to pick up momentum. 他们的运气开始转旺"],
                                            'boost, encouragement, goad, impetus, incentive, incitation, instigation, motivation, spur, stimulus',
                                            'deterrent, obstruction, resistance')]),
                              Word('mongrel', "",
                                   [TestWay('adj',
                                            '杂种的, 混血儿的',
                                            'of mixed origin or character',
                                            ["homeless mongrel dogs on the streets 街上的流浪杂种狗"],
                                            'crossbred, hybrid',
                                            'purebred')]),
                              Word('monochromatic', "",
                                   [TestWay('adj',
                                            '单色的',
                                            'having or consisting of one color or hue',
                                            ["monochromatic filter 单色滤光片"],
                                            'colorless, monochrome',
                                            'chromatic, colorful, iridescent, motley, rainbow, variegated'),
                                    TestWay('adj',
                                            '单调无聊的',
                                            'lacking variety, creativity, or excitement',
                                            ["a monochromatic article eulogizing a hero 一个无聊的赞颂英雄的文章"],
                                            'arid, dreary, drudging, dull, jejune, monotonous, pedestrian, ponderous, stale, stodgy, tiresome',
                                            'absorbing, engaging, engrossing, gripping, interesting, intriguing, involving, riveting',
                                            'monochromatism n. 全色盲')]),
                              Word('monologue', "",
                                   [TestWay('n',
                                            '独白',
                                            'a dramatic sketch performed by one actor',
                                            ["deliver a tedious monologue 做了一个冗长的独白"],
                                            'soliloquy, solo, speech',
                                            'dialogue')]),
                              Word('monotonous', "",
                                   [TestWay('adj',
                                            '(声音)单调的',
                                            'uttered or sounded in one unvarying tone',
                                            ["a monotonous apathetic voice 单调而冷漠的声音"],
                                            antonyms = 'vociferous'),
                                    TestWay('adj',
                                            '清一色的, 无聊的',
                                            'tediously uniform or unvarying',
                                            ["a sparkle in the monotonous background 单调背景中的一个亮点"],
                                            'arid, dreary, drudging, dull, jejune, monochromatic, pedestrian, ponderous, stale, stodgy, tiresome',
                                            'absorbing, engaging, engrossing, gripping, interesting, intriguing, involving, riveting')]),
                              Word('montage', "",
                                   [TestWay('n',
                                            '大杂烩',
                                            'an unorganized collection or mixture of various things',
                                            ["My memories of the childhood trip are a montage of the sights of two rivers, smells of hotpots, and sounds of light railway of Chongqing. 我孩提时代旅行的记忆就是由两江风光、火锅的香味以及重庆的轻轨声杂糅而成的"],
                                            'agglomerate, collage, hodgepodge, medley, motley, salad, variety')]),
                              Word('moratorium', "",
                                   [TestWay('n',
                                            '延期, 暂缓施行',
                                            'a suspension of activity',
                                            ["a moratorium on nuclear tests 暂缓核试验"],
                                            'abeyance, delay, doldrums, dormancy, latency, quiescence, postponement, suspension',
                                            'resumption')]),
                              Word('morbid', "",
                                   [TestWay('adj',
                                            '病态的',
                                            'affected with or induced by disease',
                                            ["exhibit a morbid fascination 展现出一种病态的迷恋"],
                                            'diseased, pathological',
                                            'verdant'),
                                    TestWay('adj',
                                            '思想性格变态的',
                                            'characterized by preoccupation with unwholesome thoughts or feelings',
                                            ["read the account of the murder with a morbid interest 怀着病态的心态读谋杀报告"],
                                            'brainsick, crazy, deranged, lunatic, psychotic',
                                            'hale, salubrious, wholesome',
                                            'morbidity n. 病态')]),
                              Word('mordant', "",
                                   [TestWay('adj',
                                            '尖酸刻薄的',
                                            'biting and caustic in thought, manner, or style',
                                            ["feel embarrassed about the mordant satire of the critics 对评论家刻薄的讽刺感到尴尬"],
                                            'acerbic, acid, acrid, barbed, caustic, corrosive, pungent, sardonic, satiric, scalding, scathing, tart',
                                            'congenial, genial')]),
                              Word('moribund', "",
                                   [TestWay('adj',
                                            '即将结束的, 垂死的',
                                            'approaching death; about to die',
                                            ["The nation’s banking industry was moribund. 这个国家的银行业危在旦夕"],
                                            'decadent, deteriorating, dying, expiring, fading',
                                            'beginning, nascent, lively, thriving, vigorous, vital'),
                                    TestWay('adj',
                                            '即将过时的',
                                            'on the verge of becoming obsolete',
                                            ["Some social conventions have been rendered moribund in face of modernization. 不少传统习俗在现代化的影响下变得岌岌可危"],
                                            'antiquated, archaic, dated, fossilized, moth-eaten, outdated, outworn, rusty',
                                            'fresh, new, promising')])])

list16_unit5 = VocabularyList([Word('morose', "",
                                   [TestWay('adj',
                                            '忧郁的',
                                            'having a sullen and gloomy disposition',
                                            ["morose job seekers who are inured to rejection 习惯了被拒的郁郁寡欢的求职者"],
                                            'bleak, chill, dark, depressed, dire, dour, gloomy, lugubrious, saturnine, solemn, sulky, sullen, surly',
                                            'bright, cheerful, festive, jovial, jocund, sanguine, lighthearted, rejoiced')]),
                              Word('mosaic', "",
                                   [TestWay('n',
                                            '综合物, 马赛克般的东西',
                                            'an unorganized collection or mixture of various things',
                                            ["a mosaic of testimony from various witnesses 从不同证人中得来的综合证词"],
                                            'agglomerate, collage, hodgepodge, jumble, montage, motley, muddle, salad, shuffle, variety, welter')]),
                              Word('mosque', "",
                                   [TestWay('n',
                                            '清真寺',
                                            'a building used for public worship by Muslim',
                                            ["a deadly suicide attack at the mosque 在清真寺发生的致命自杀性袭击"],
                                            'cathedral, chapel, church, temple')]),
                              Word('moth-eaten', "",
                                   [TestWay('adj',
                                            '过时的',
                                            'having passed its time of use or usefulness',
                                            ["dressed in a moth-eaten style 过时的衣着"],
                                            'antiquated, archaic, dated, fossilized, moribund, outdated, outworn, rusty',
                                            'fresh, new, promising')]),
                              Word('motile', "",
                                   [TestWay('adj',
                                            '能动的',
                                            'exhibiting or capable of movement',
                                            ["Aircraft carriers are recognized as a motile combat platform. 航空母舰是一种移动作战平台"],
                                            'mobile, movable, portable, transportable',
                                            'immobile',
                                            'motility n. 可运动性')]),
                              Word('motivate', "",
                                   [TestWay('vt',
                                            '刺激, 激发',
                                            'to provide with an incentive; move to action',
                                            ["questions that excite and motivate youth 激发青年人的问题"],
                                            'excite, galvanize, impel, innervate, provoke, rouse, stimulate',
                                            'discourage, dishearten',
                                            'motivation n. 动机; motivated adj. 被激励的')]),
                              Word('motley', "",
                                   [TestWay('adj',
                                            '混杂的, 富于变化的',
                                            '(especially of colors) having elements of great variety or incongruity',
                                            ["an arrangement of motley flowers 多种不同花束的组合"],
                                            'assorted, chromatic, kaleidoscopic, heterogeneous, indiscriminate, magpie, piebald, variegated',
                                            'homogeneous, monochromatic, monotonous, unvaried')]),
                              Word('mottle', "",
                                   [TestWay('vt',
                                            '标记上杂色斑点',
                                            'to mark with spots or blotches of different shades or colors',
                                            ["a black horse mottled with white 身上带有白色斑点的黑马"],
                                            'blotch, dapple, dot, marble, splotch, spot, stain',
                                            'blanch',
                                            'mottled adj. 斑驳的')]),
                              Word('motto', "",
                                   [TestWay('n',
                                            '座右铭',
                                            'a short expression of a guiding principle',
                                            ["“Semper fidelis” is the motto of US Marine Corps. “永远忠诚”是美国海军陆战队的格言"],
                                            'catchword, doctrine, dogma, idiom, slogan')]),
                              Word('mournful', "",
                                   [TestWay('adj',
                                            '悲伤的',
                                            'feeling or expressing sorrow or grief',
                                            ["The mournful survivors of the disaster were faced with the grim task of burying the dead. 悲伤的幸存者面临着掩埋灾难中死者尸体的可怕任务", "Mrs. Murphy fainted at the mournful news of her son’s death. Murphy 太太听到她儿子的死讯后晕了过去"],
                                            'aching, agonized, anguished, doleful, dolorous, grievous, lamentable, lugubrious, melancholy, sad, woeful',
                                            'cheerful, delighted, jocund, jovial, jubilant',
                                            'mournfulness n. 悲伤')])])

list16_unit6 = VocabularyList([Word('movement', "",
                                   [TestWay('n',
                                            '运动',
                                            'the act or process of moving',
                                            ["There appears to be some movement in the bush. 树丛中似乎有动静"],
                                            'action, motion, operation, shifting, stir',
                                            'motionlessness, stasis')]),
                              Word('muddy', "",
                                   [TestWay('adj',
                                            '不干净的',
                                            'not clean',
                                            ["got muddy after playing outside 在外面玩弄得很脏"],
                                            'besmirched, dingy, draggled, dusty, filthy, foul, nasty, smudged, smutty, soiled, sordid, stained, sullied',
                                            'clean, immaculate, spotless, stainless, unsoiled, unstained, unsullied'),
                                    TestWay('adj',
                                            '浑浊的, 不清晰的',
                                            'lacking in clarity or brightness',
                                            ["a muddy recording 嘈杂不清的纪录"],
                                            'cloudy, foul, murky, obscure, turbid',
                                            'clear'),
                                    TestWay('v',
                                            '使难以理解',
                                            'to make (something) unclear to the understanding',
                                            ["That point is irrelevant and will just muddy the issue we're trying to resolve. 那个观点和讨论我们的问题毫不相干, 它只会妨碍我们对于问题的理解"],
                                            'becloud, befog, blur, cloud, fog, obfuscate',
                                            'clarify, illuminate')]),
                              Word('muffle', "",
                                   [TestWay('vt',
                                            '使消声',
                                            'to wrap or pad in order to deaden the sound',
                                            ["close the window to muffle the outside noises 关上窗户以减少外界的噪音"],
                                            'attenuate, dampen, deaden, mute, soften, stifle, suppress',
                                            'amplify, enhance, magnify',
                                            'muffler n. 围巾; 消音器')]),
                              Word('mulish', "",
                                   [TestWay('adj',
                                            '固执的',
                                            'unreasonably and inflexibly obstinate',
                                            ["a mulish determination to act on his own 铁了心要单打独斗"],
                                            'adamant, headstrong, immovable, intractable, obstinate, pertinacious, perverse, refractory, stubborn',
                                            'flexible, pliable, pliant, yielding',
                                            'mulishly adv. 固执地')]),
                              Word('mumble', "",
                                   [TestWay('v',
                                            '说话含糊',
                                            'to utter words in a low confused indistinct manner',
                                            ["He mumbled an apology reluctantly. 他不情愿地咕哝了句抱歉"],
                                            'grunt, murmur, mutter, whisper',
                                            'articulate, enunciate')]),
                              Word('mundane', "",
                                   [TestWay('adj',
                                            '尘世的, 世俗化的',
                                            'of, relating to, or typical of this world',
                                            ["As for opera, I prefer mundane to religious themes. 与宗教主题相比, 我更喜欢世俗主题的歌剧"],
                                            'carnal, earthly, materialistic, secular, sensual, worldly',
                                            'spiritual, ethereal'),
                                    TestWay('adj',
                                            '平凡的',
                                            'relating to, characteristic of, or concerned with commonplaces',
                                            ["mundane concerns of day-to-day life 关于日常生活的一般顾虑"],
                                            'common, ordinary, prosaic',
                                            'extraordinary')]),
                              Word('munificent', "",
                                   [TestWay('adj',
                                            '慷慨的',
                                            'very liberal in giving',
                                            ["The university received a munificent foundation grant. 大学收到了一笔慷慨的基金资助"],
                                            'bountiful, charitable, generous, liberal, openhanded, unsparing',
                                            'closefisted, mean, miserly, niggardly, parsimonious, penurious, stingy, tightfisted',
                                            'munificence n. 慷慨')]),
                              Word('murky', "",
                                   [TestWay('adj',
                                            '黯淡的, 昏暗的',
                                            'being without light or without much light',
                                            ["I didn't like walking around the murky campground without a flashlight. 我不喜欢在没有手电的情况下在营地里走动"],
                                            'black, caliginous, darkened, dim, gloomy, stygian',
                                            'bright, brightened, brilliant, illuminated, illumined, lucent, lucid, luminous'),
                                    TestWay('adj',
                                            '模糊的, 晦涩的',
                                            'lacking clarity or distinctness',
                                            ["He felt lost in the murky bureaucratic rhetoric. 他感觉自己被官僚主义的晦涩说辞弄晕了"],
                                            'ambiguous, arcane, cloudy, equivocal, muddy, nebulous, obscure, occult, vague',
                                            'clear, limpid, pellucid, plain')]),
                              Word('murmur', "",
                                   [TestWay('n',
                                            '小声的话语',
                                            'a low, indistinct, continuous sound',
                                            ["We could hear the murmur of the audience throughout the entire performance. 我们在整个演出当中都能听到观众的窃窃私语"],
                                            'grunt, mumble, mutter, undertone, whisper',
                                            'roar'),
                                    TestWay('v',
                                            '低声抱怨, 发牢骚',
                                            'to complain in low mumbling tones; grumble',
                                            ["We could hear the murmur of the audience throughout the entire performance. 我们在整个演出当中都能听到观众的窃窃私语"],
                                            'carp, fuss, gripe, grizzle, grouch, grouse, grumble, moan, repine, whine',
                                            'crow, delight, rejoice')]),
                              Word('mutate', "",
                                   [TestWay('v',
                                            '(使)改变, (使)变异',
                                            'to undergo or cause to undergo mutation',
                                            ["Some chromosomes started to mutate after exposure to X-Ray. 经X光照射之后部分染色体发生了变异"],
                                            'alter, change, fluctuate, modify, shift, transfigure, transform, vary',
                                            'remain, plateau, stabilize',
                                            'mutation n. 改变; 变异')])])

list16_unit7 = VocabularyList([Word('mute', "",
                                   [TestWay('adj',
                                            '不说话的, 缄默的',
                                            'deliberately refraining from speech',
                                            ["He always remained mute no matter how much we pleaded for an answer 不论我们怎么恳求回答, 他总是保持沉默"],
                                            'dumb, inarticulate, speechless, uncommunicative, voiceless, wordless',
                                            'communicative, expansive, loquacious, talkative'),
                                    TestWay('vt',
                                            '使颜色、音调等柔和',
                                            'to soften the tone, color, shade, or hue of',
                                            ["mute a color 对颜色进行柔化"],
                                            'attenuate, soften, subdue',
                                            'sharpen'),
                                    TestWay('vt',
                                            '减弱声音',
                                            'to soften or muffle the sound of',
                                            synonyms = 'dampen, deaden, muffle, stifle',
                                            antonyms = 'amplify, magnify',
                                            other_form = 'muted adj. 消声的, 静音的')]),
                              Word('mutter', "",
                                   [TestWay('vi',
                                            '低声抱怨',
                                            'to murmur complainingly or angrily',
                                            ["mutter about the difficult assignment 抱怨作业太难"],
                                            'carp, fuss, gripe, grizzle, grouch, grouse, grumble, moan, murmur, repine, whine',
                                            'crow, delight, rejoice')]),
                              Word('myopic', "",
                                   [TestWay('adj',
                                            '缺乏远见的, 缺乏辨别能力的',
                                            'a lack of foresight or discernment',
                                            ["a myopic view on climate change 关于气候变化缺乏远见的观点"],
                                            'shortsighted, narrow-minded',
                                            'far-sighted, foreseeing, improvident, discerning',
                                            'myopia n. 近视; 鼠目寸光')]),
                              Word('myriad', "",
                                   [TestWay('adj',
                                            '无限的, 大量的',
                                            'constituting a very large, indefinite number',
                                            ["the myriad stars of a summer night 夏日夜空中的无尽繁星"],
                                            'innumerable, numerous, uncountable, untold',
                                            'few, scarce, scanty, countable, enumerable')]),
                              Word('nadir', "",
                                   [TestWay('n',
                                            '最低点',
                                            'the lowest point',
                                            ["the nadir on the curve 曲线上的最低点"],
                                            'base, bottom, foot',
                                            'acme, apex, climax, meridian, peak, pinnacle, summit, top, zenith')]),
                              Word('naïve', "",
                                   [TestWay('adj',
                                            '天真纯朴的',
                                            'lacking worldly experience and understanding, simple and guileless',
                                            ["a child with a naïve charm 天真无邪的孩子"],
                                            'artless, guileless, ingenuous, innocent, natural, simple, unaffected, unsophisticated',
                                            'sophisticated, worldly, affected, artful, assuming, dishonest, dissembling, guileful',
                                            'naivety n. 天真')]),
                              Word('narcissism', "",
                                   [TestWay('n',
                                            '自恋',
                                            'excessive love or admiration of oneself',
                                            ["In his narcissism, he just assumed that everyone else wanted to hear the tiny details of his day. 在他自恋的眼中, 所有人仿佛都想要听他日常生活里的细枝末节"],
                                            'egocentricity, egotism, self-absorption',
                                            'self-hatred',
                                            'narcissistic adj. 自恋的')]),
                              Word('nascent', "",
                                   [TestWay('adj',
                                            '新生的',
                                            'coming or having recently come into existence',
                                            ["The rise of the nascent middle class catalyzed a new economic boom. 新生中产阶级的崛起催生了一场新的经济繁荣"],
                                            'beginning, emerging, inceptive, inchoate, incipient, initial, introductory',
                                            'full-blown, full-fledged, mature, ripe, moribund',
                                            'nascence n. 新生的状态')]),
                              Word('natty', "",
                                   [TestWay('adj',
                                            '整洁的, 时髦的',
                                            'trimly neat and tidy',
                                            ["a natty young woman 整洁漂亮的年轻女子"],
                                            'dapper, smart, spruce',
                                            'frowsy, sloppy, slovenly')]),
                              Word('nauseate', "",
                                   [TestWay('v',
                                            '(使)厌恶, (使)作呕',
                                            'to feel or cause to feel loathing or disgust',
                                            ["The malodor of the rotten meat made us nauseate. 腐肉的恶臭让我们恶心"],
                                            'disgust, repel, repulse, revolt, sicken',
                                            'delight',
                                            'nausea n. 恶心反胃')])])

list16_unit8 = VocabularyList([Word('nautical', "",
                                   [TestWay('adj',
                                            '航海的',
                                            'of, relating to, or characteristic of ships, shipping, sailors, or navigation on a body of water',
                                            ["nautical mile 海里"],
                                            'marine, maritime, navigational',
                                            'aeronautic, astronautic')]),
                              Word('naysay', "",
                                   [TestWay('vt',
                                            '拒绝, 否认',
                                            'to oppose, deny, or take a pessimistic or negative view of',
                                            synonyms = 'decline, deny, deject, disallow, gainsay, oppose, refuse, reject',
                                            antonyms = 'accede, agree, concur, consent',
                                            other_form = 'naysayer n. 反对者')]),
                              Word('nebulous', "",
                                   [TestWay('adj',
                                            '模糊的',
                                            'indistinct, vague',
                                            ["a nebulous description of the topic 对于主题的模糊描述"],
                                            'ambiguous, arcane, equivocal, hazy, indistinct, muddy, murky, obscure, occult, vague',
                                            'distinct, clear, definite, unambiguous, unequivocal',
                                            'nebula n. 星云')]),
                              Word('needy', "",
                                   [TestWay('adj',
                                            '贫困的',
                                            'being in need; impoverished, poor',
                                            ["As a child, she was extremely needy and had no self-confidence. 她是一个非常贫穷的小孩, 因此缺乏自信"],
                                            'destitute, impecunious, impoverished, indigent, penurious, poor, threadbare',
                                            'affluent, opulent, wealthy')]),
                              Word('nefarious', "",
                                   [TestWay('adj',
                                            '极坏的, 邪恶的',
                                            'flagrantly wicked or impious',
                                            ["a nefarious scheme to assassinate the archbishop 企图刺杀大主教的邪恶阴谋"],
                                            'atrocious, degenerate, devious, evil, heinous, infamous, miscreant, vicious, villainous, wicked',
                                            'ethical, righteous, upright, virtuous, beneficial, exemplary')]),
                              Word('negation', "",
                                   [TestWay('n',
                                            '否定',
                                            'the opposite or absence of something regarded as actual, positive, or affirmative',
                                            ["issued specific negations of all of the charges against her 发表了明确的声明, 否定了所有对她的指控"],
                                            'contradiction, denegation, denial, gainsaying, rejection, repudiation',
                                            'acknowledgement, affirmation, avowal',
                                            'negative adj. 否定的; 负面的')]),
                              Word('negligent', "",
                                   [TestWay('adj',
                                            '疏忽大意的',
                                            'failing to give proper attention or care',
                                            ["negligent in taking care of the children 粗心大意地照顾孩子"],
                                            'careless, derelict, heedless, neglectful, remiss',
                                            'attentive, careful, cautious, heedfu',
                                            'negligence n. 疏忽')]),
                              Word('negotiate', "",
                                   [TestWay('vi',
                                            '商量, 谈判',
                                            'to arrange or settle by discussion and mutual agreement',
                                            ["negotiate the term of truce 共商停战事宜"],
                                            'arrange, bargain, concert, settle',
                                            'break down'),
                                    TestWay('vi',
                                            '谋划',
                                            'plan out usually with subtle skill or care',
                                            ["The prisoners negotiated their escape by using Morse code to tap messages to each other through the walls. 犯人们通过敲击墙壁来传达莫尔斯电码, 从而密谋了他们的逃跑计划"],
                                            'contrive, finesse, frame, machinate, maneuver, manipulate, mastermind, wangle',
                                            other_form = 'negotiable adj. 可商量的; negotiation n. 谈判')]),
                              Word('neophyte', "",
                                   [TestWay('n',
                                            '初学者, 新手',
                                            'a beginner or novice',
                                            ["a novice in the theater who had never even had a walk-on role 一个连龙套都没跑过的新演员"],
                                            'abecedarian, apprentice, fledgling, freshman, novice, recruit, rookie, tyro',
                                            'veteran')]),
                              Word('nerve', "",
                                   [TestWay('n',
                                            '(坚强的)意志, 勇气',
                                            'power of endurance or control; strength of mind to carry on in spite of danger',
                                            ["nerves of steel 钢铁般的意志"],
                                            'bravery, fortitude, guts, intrepidity, resolution, stamina',
                                            'cowardice, pusillanimity'),
                                    TestWay('vt',
                                            '给予勇气, 鼓励',
                                            'to give strength or courage to',
                                            ["needs to nerve himself for the big game tomorrow 需要为明天的大赛给自己加油鼓劲"],
                                            'animate, brace, cheer, embolden, encourage, inspirit, steel, strengthen',
                                            'appall, discourage, dishearten',
                                            'nervy adj. 有勇气的')])])

list16_unit9 = VocabularyList([Word('nettle', "",
                                   [TestWay('vt',
                                            '惹怒',
                                            'to arouse to sharp but transitory annoyance or anger',
                                            ["His pompous attitude nettled several people. 他自大的性格得罪了不少人"],
                                            'aggravate, annoy, exasperate, inflame, infuriate, irritate, peeve, pique, provoke, roil, ruffle, vex',
                                            'appease, assuage, conciliate, mollify, placate, propitiate')]),
                              Word('neutralize', "",
                                   [TestWay('vt',
                                            '中和',
                                            'to cause (an acid or base) to undergo neutralization',
                                            ["industrial exhaust neutralized by lime 被石灰中和的工业废气"],
                                            antonyms = 'acidify'),
                                    TestWay('vt',
                                            '破坏, 使无效',
                                            'to make inoperative or ineffective usually by means of an opposite force, influence, or effect',
                                            ["influenced by the kind of propaganda that is difficult to neutralize 被一种难以消除的宣传攻势所影响"],
                                            'annul, cancel, counteract, frustrate, negate, nullify',
                                            'activate, vitalize',
                                            'neutralization n. 中和; 消除')]),
                              Word('nicety', "",
                                   [TestWay('n',
                                            '准确, 精确',
                                            'careful attention to details; delicate exactness',
                                            ["There's a nicety of detail in his meticulously painted landscapes. 在他精心绘制的景观图中, 有着十分精准翔实的细节"],
                                            'accuracy, delicacy, exactness, fineness, precision, veracity',
                                            'coarseness, imprecision, inaccuracy, roughness'),
                                    TestWay('n',
                                            '细微之处',
                                            'a fine point or distinction',
                                            ["the niceties of table manner 餐桌礼仪的细微之处‖niceties of diplomatic protocol 外交礼节中的细节"],
                                            'detail, particular, nuance, subtlety')]),
                              Word('nexus', "",
                                   [TestWay('n',
                                            '连结',
                                            'a means of connection',
                                            ["Correlativity does not sufficiently lead to causal nexus. 相关性不是因果关联的充分条件"],
                                            'bond, connection, link, tie'),
                                    TestWay('n',
                                            '核心, 最重要的地带',
                                            'a thing or place that is of greatest importance to an activity or interest',
                                            ["As the nexus for three great religions, Jerusalem has had a troubled as well as illustrious history. 作为三大宗教的圣城, 耶路撒冷有着动荡而辉煌的历史"],
                                            'base, capital, center, core, focus, kernel, heart, hub, nucleus',
                                            'margin, periphery')]),
                              Word('nibble', "",
                                   [TestWay('vt',
                                            '小口咬',
                                            'to eat with small, quick bites or in small morsels',
                                            ["waves nibbling the shore 缓慢侵蚀海岸的浪"],
                                            'bite, nip, peck, sip, tipple',
                                            'gobble')]),
                              Word('nil', "",
                                   [TestWay('n',
                                            '不存在, 零',
                                            'nothing; zero',
                                            ["reduced to nil 消逝殆尽"],
                                            'nothing, nonentity, nullity, zip',
                                            'existence')]),
                              Word('nip', "",
                                   [TestWay('n',
                                            '少量',
                                            'a very small amount',
                                            ["I'll have just a nip of your sandwich. 我只吃一点点你的三明治"],
                                            'bit, hint, little, mite, ounce, snap, trace',
                                            'abundance, affluence, avalanche'),
                                    TestWay('vi',
                                            '小口吃喝',
                                            'to sip (alcoholic liquor) in small amounts',
                                            synonyms = 'nibble, sip, tipple',
                                            antonyms = 'guzzle, quaff, swill')]),
                              Word('nitpick', "",
                                   [TestWay('v',
                                            '吹毛求疵',
                                            'to criticize by nit-picking',
                                            ["a peevish critic always ready to quibble 一个总是吹毛求疵的古怪评论家"],
                                            'carp, cavil, fuss, niggle, quibble, pick nits',
                                            other_form = 'nitpicker n. 吹毛求疵的人')]),
                              Word('nocturnal', "",
                                   [TestWay('adj',
                                            '夜间的',
                                            'of, relating to, or occurring in the night',
                                            ["a nocturnal raid 夜间突袭"],
                                            'nightly, nighttime',
                                            'daily, diurnal'),
                                    TestWay('adj',
                                            '夜间活动的',
                                            'active at night',
                                            ["a nocturnal predator 夜间活动的捕食者"],
                                            other_form = 'nocturne n. 夜曲')]),
                              Word('noisome', "",
                                   [TestWay('adj',
                                            '有害的, 有毒的',
                                            'noxious, harmful',
                                            ["noisome chemical fumes 有害的化学烟雾"],
                                            'deleterious, detrimental, insalubrious, noxious, unhealthy, unwholesome',
                                            'beneficial, healthy, salubrious, wholesome'),
                                    TestWay('adj',
                                            '恶臭的',
                                            'offensive to the senses and especially to the sense of smell',
                                            ["noisome garbage 恶臭的垃圾"],
                                            'fetid, foul, malodorous, smelly, stinky',
                                            'ambrosial, aromatic, fragrant, perfumed, redolent, savory, scented, sweet'),
                                    TestWay('adj',
                                            '非常令人厌恶的',
                                            'highly obnoxious or objectionable',
                                            ["noisome habits of littering 让人反感的随地乱扔垃圾的坏习惯"],
                                            'abhorrent, appalling, disgusting, hideous, loathsome, nauseating, offensive, repugnant, repulsive',
                                            'appealing, captivating, enchanting, fascinating, agreeable, pleasant')])])

list16_unit10 = VocabularyList([Word('nomad', "",
                                   [TestWay('adj./n',
                                            '游牧的; 居无定所的人',
                                            'a member of a people who have no fixed residence but move from place to place usually seasonally and within a well-defined territory',
                                            ["after college she became quite the nomad, backpacking through Europe with no particular destination 大学毕业后她开始漂泊, 漫无目的地游遍欧洲"],
                                            'ambulant, fugitive, gallivanting, perambulatory, peripatetic, ranging, roaming, vagabond, vagrant, wandering, wayfaring',
                                            'settled')]),
                              Word('nominal', "",
                                   [TestWay('adj',
                                            '不重要的',
                                            'so small or unimportant as to warrant little or no attention',
                                            ["His involvement was nominal. 他的参与不太重要。"],
                                            'inconsequential, inconsiderable, paltry, trifling, trivial',
                                            'big, consequential, considerable, important, material, significant'),
                                    TestWay('adj',
                                            '名义上的',
                                            'existing or being something in name or form only',
                                            ["nominal head of the party 党派的名义首领"],
                                            'formal, paper, titular')]),
                              Word('nonchalant', "",
                                   [TestWay('adj',
                                            '冷漠的',
                                            'having an air of easy unconcern or indifference',
                                            ["She was surprisingly nonchalant about winning the award. 她竟然对得奖很淡然。"],
                                            'apathetic, disinterested, insensible, insouciant, perfunctory, unconcerned',
                                            'concerned, interested')]),
                              Word('nondescript', "",
                                   [TestWay('adj',
                                            '平凡的, 不吸引人的',
                                            'lacking distinctive or interesting qualities',
                                            ["Their performance was disappointingly nondescript. 他们的演出令人失望, 味同嚼蜡。"],
                                            'beige, characterless, featureless, indistinctive, vanilla',
                                            'conspicuous, remarkable, striking')]),
                              Word('nonentity', "",
                                   [TestWay('n',
                                            '不重要的人',
                                            'a person or thing of little consequence or significance',
                                            ["she was so quiet she was almost a nonentity at the meeting 她非常沉默, 在会议上是个边缘人物"],
                                            'cipher, half-pint, insignificancy, lightweight, nullity, snippersnapper, twerp, whippersnapper, zero, zilch',
                                            'mogul, big shot, big wheel, bigwig, eminence, figure, magnate, personage, somebody'),
                                    TestWay('n',
                                            '虚构的东西',
                                            'a conception or image created by the imagination and having no objective reality',
                                            ["the arctic circle is a nonentity—you won't see it on the way to the north pole 北极圈是虚构的概念, 去北极的路上你不会见到那么一个圈"],
                                            'chimera, conceit, daydream, delusion, fancy, figment, hallucination, illusion, phantasm, unreality, vision')]),
                              Word('nonplus', "",
                                   [TestWay('vt',
                                            '迷惑, 困惑',
                                            'use to be at a loss as to what to say, think, or do: perplex',
                                            ["I was nonplussed by his openly expressed admiration of me. 我被她公开表现的仰慕弄得很窘迫。"],
                                            'confound, confuse, discomfit, disconcert, discountenance, mortify, abash, faze, fluster')]),
                              Word('nonsense', "",
                                   [TestWay('n',
                                            '无意义的话, 废话',
                                            'words or language having no meaning or conveying no intelligible ideas',
                                            ["Many of the words in the poem are nonsense. 这首诗歌当中很多词都是废话。"],
                                            'babble, blabber, drivel, prattle, mumbo jumbo')]),
                              Word('notch', "",
                                   [TestWay('n',
                                            '刻痕',
                                            'a V-shaped cut. Such a cut used for keeping a record',
                                            antonyms = 'unserrated 没有刻痕的'),
                                    TestWay('v',
                                            '通过努力获得',
                                            'to obtain (as a goal) through effort',
                                            ["a stunning performance that notched up a second Academy Award for the actor 出色的表演为该演员拿到了第二座小金人"],
                                            'attain, bag, chalk up, clock up, gain, hit, log, make, rack up, ring up, score, win')]),
                              Word('novel', "",
                                   [TestWay('adj',
                                            '新奇的',
                                            'strikingly new, unusual, or different',
                                            ["a novel scheme to collect money 一种新颖的筹钱手段"],
                                            'original, unaccustomed, unfamiliar, unheard-of, unknown, unprecedented',
                                            'banal, timeworn, familiar, hackneyed, time-honored, tired, warmed-over')]),
                              Word('noxious', "",
                                   [TestWay('adj',
                                            '有害的, 有毒的',
                                            'harmful to living things; injurious to health',
                                            ["noxious waste 有害的废弃物"],
                                            'unwholesome, baneful, deleterious, detrimental, nocuous, pernicious, wicked',
                                            'beneficial, salubrious, anodyne, benign, harmless, hurtless, innocent, innocuous, inoffensive, safe')])])

LIST16 = VocabularyList(list16_unit1.words+list16_unit2.words+list16_unit3.words+list16_unit4.words+list16_unit5.words+list16_unit6.words+list16_unit7.words+list16_unit8.words+list16_unit9.words+list16_unit10.words)
