#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list2_unit1 = VocabularyList([Word('amorphous', "",
                                   [TestWay('adj',
                                            '无固定形状的',
                                            'having no definite form: shapeless',
                                            ['an amorphous cloud mass 一团无定形的云'],
                                            ['shapeless', 'unformed', 'unshaped']),
                                    TestWay('adj',
                                            '不可归类的',
                                            'being without definite character or nature: unclassifiable',
                                            ['an amorphous segment of society 不可归类的社会阶段'],
                                            ['unclassifiable'])]),
                              Word('analgesic', "",
                                   [TestWay('n',
                                            '镇痛剂',
                                            'a medication that reduces or eliminates pain',
                                            ['Aspirin is a kind of analgesic. 阿司匹林是一种止痛剂。'],
                                            ['anesthetic', 'anodyne'])]),
                              Word('anarchist', "",
                                   [TestWay('n',
                                            '反抗权威的人',
                                            'a person who rebels against any authority, established order, or ruling power',
                                            synonyms = ['rebel, insurgent'],
                                            other_form = 'anarchy n. 混乱：a state of lawlessness or political disorder due to the absence of governmental authority【近】chaos, disarray, topsy-turviness, commotion, turmoil【反】order 有序')]),
                              Word('anathema', "",
                                   [TestWay('n',
                                            '诅咒',
                                            'a ban or curse solemnly pronounced by ecclesiastical authority and accompanied by excommunication',
                                            synonyms = ['curse', 'execration', 'imprecation', 'malediction'],
                                            antonyms = ['benediction', 'benison', 'blessing'])]),
                              Word('ancillary', "",
                                   [TestWay('adj',
                                            '次要的',
                                            'of secondary importance',
                                            ['The company hopes to boost its sales through ancillary products. 公司想通过辅助产品来增加销量。'],
                                            ['subordinate', 'subsidiary'],
                                            ['main', 'paramount']),
                                    TestWay('adj',
                                            '辅助的, 补充的',
                                            'auxiliary, supplementary',
                                            ['the need for ancillary evidence 对补充证据的需要', 'Some practice in the deft use of words may well be ancillary to the study of natural science. 熟练使用文字的练习对于自然科学的研究也是有帮助的。'],
                                            ['auxiliary', 'supplementary'])]),
                              Word('anecdote', "",
                                   [TestWay('n',
                                            '短小有趣的故事',
                                            'a usually short narrative of an interesting, amusing, or biographical incident',
                                            ['He told us all sorts of humorous anecdotes about his childhood. 他告诉了我们所有关于他童年的奇闻趣事。', 'He is a master raconteur with endless anecdotes. 他是讲故事的超级高手, 总有讲不完的奇闻趣事。'])]),
                              Word('anemic', "",
                                   [TestWay('adj',
                                            '缺乏力量、活力、精神的',
                                            'lacking force, vitality, or spirit',
                                            ['an anemic economic recovery. 毫无活力的经济复苏', "Investors are worried about the stock's anemic performance. 投资者担心股市低迷的表现。"],
                                            ['sapless', 'infirm', 'feeble', 'decrepit', 'wan', 'pale', 'pallid', 'effete', 'lethargic'],
                                            ['vigorous', 'spirited', 'forceful'])]),
                              Word('anesthetic', "",
                                   [TestWay('n',
                                            '止痛剂',
                                            'something (as a drug) that relieves pain',
                                            ['The dentist waited until the anesthetic took effect. 牙医等止痛药生效。'],
                                            ['analgesic', 'anodyne']),
                                    TestWay('adj',
                                            '无感觉的, 麻木的',
                                            'lacking awareness or sensitivity',
                                            ['be anesthetic to their feelings 对他们的感受麻木不仁'],
                                            antonyms = ['sensate'])]),
                              Word('animate', "",
                                   [TestWay('adj',
                                            '活的',
                                            'having or showing life',
                                            ['The lecture was about ancient worship of animate and inanimate objects. 演讲是关于对生命体和非生命体的古代崇拜。'],
                                            ['breathing', 'live', 'living'],
                                            ['dead', 'expired', 'deceased', 'lifeless', 'nonliving']),
                                    TestWay('adj',
                                            '有活力的',
                                            'having much high-spirited energy and movement',
                                            ['Animate dance will get the blood pumping. 有活力的舞蹈会让人热血沸腾。'],
                                            ['bouncing', 'brisk', 'energetic', 'sprightly', 'vivacious'],
                                            ['inactive', 'lackadaisical', 'languid', 'listless', 'leaden']),
                                    TestWay('v',
                                            '使有活力, 支持',
                                            'to give spirit and support to',
                                            ["The writer's humor animates the novel. 作者的幽默使小说富有生命力。"],
                                            ['brace', 'energize', 'enliven', 'invigorate', 'ginger (up)', 'pep up', 'vitalize'],
                                            ['damp', 'dampen', 'deaden'],
                                            'animation 生命力, 活力：the quality or condition of being alive, active, spirited, or vigorous.【反】lassitude, lethargy 疲倦,疲乏'),
                                    TestWay('v',
                                            '使行动, 驱使',
                                            'to move to action',
                                            ['a criminal animated by greed 一个受贪婪驱使的罪犯'],
                                            ['goad', 'prod', 'spur', 'galvanize', 'stimulate']),
                                    TestWay('v',
                                            '使活灵活现, 使栩栩如生',
                                            'to make or design in such a way as to create apparently spontaneous lifelike movement',
                                            ["Kongfu Panda's very realistic panda was animated by CG. 《功夫熊猫》电影里面的熊猫是通过CG技术使熊猫变得活灵活现的。"])]),
                              Word('animus', "",
                                   [TestWay('n',
                                            '敌意',
                                            'a usually prejudiced and often spiteful or malevolent ill will, enmity',
                                            ['She felt no animus toward those who had wronged her. 她对那些冤枉了她的人没有敌意。'],
                                            ['animosity', 'antagonism', 'antipathy', 'hostility', 'rancor'],
                                            ['friendliness', 'amity', 'amenity'])])])
list2_unit2 = VocabularyList([Word('annoy', "",
                                   [TestWay('vt',
                                            '不断烦扰',
                                            'to disturb or irritate especially by repeated acts',
                                            ['Mosquitoes annoy us in the summer. 夏天蚊子总是不断烦扰我们。', 'The sound of footsteps on the bare floor annoyed the downstairs neighbors. 楼上地板的脚步声吵得楼下住户心烦。'],
                                            ['aggravate', 'bother', 'chafe', 'gall', 'grate', 'irk', 'nettle', 'peeve', 'pique', 'rile', 'ruffle', 'spite', 'vex'],
                                            ['soothe', 'defuse', 'allay', 'conciliate', 'propitiate', 'mitigate', 'assuage', 'appease', 'pacify', 'placate', 'calm', 'settle', 'subdue', 'solace', 'mollify'])]),
                              Word('annul', "",
                                   [TestWay('v',
                                            '宣告无效, 取消',
                                            'to declare or make legally invalid or void',
                                            ['The marriage was annulled last month. 婚约上个月取消了。'],
                                            ['disannul', 'cancel', 'invalidate', 'abrogate', 'nullify', 'repeal', 'rescind'],
                                            ['make legal', 'enact']),
                                    TestWay('v',
                                            '抵消',
                                            'to balance with an equal force so as to make ineffective',
                                            ['Unfortunately, his arrogant attitude annuls the many generous favors he does for people. 不幸的是, 他傲慢的态度抵消了他之前对人民的慷慨恩惠。'],
                                            ['counterbalance', 'neutralize'])]),
                              Word('anomalous', "",
                                   [TestWay('adj',
                                            '不普通的, 不平常的',
                                            'being out of the ordinary',
                                            ['He is in an anomalous position as the only part-time teacher in XDF. 他和别人不一样的是, 他是XDF唯一的兼职老师。'],
                                            ['aberrant', 'abnormal', 'atypical', 'phenomenal', 'singular', 'uncustomary', 'unwonted'],
                                            ['unexceptional', 'unextraordinary'],
                                            'anomaly n. 反常 deviation or departure from the normal or common order, form, or rule.'),
                                    TestWay('adj',
                                            '反常的, 不正常的',
                                            'departing from some accepted standard of what is normal',
                                            ['an anomalous burst of anger from this usually easygoing person 一个随和的人的一反常态的暴怒'],
                                            ['natural', 'standard'])]),
                              Word('anonymous', "",
                                   [TestWay('adj',
                                            '匿名的',
                                            'not named or identified',
                                            ['He made an anonymous phone call to the police. 他给警察打了一个匿名电话。', 'The donor wishes to remain anonymous. 捐赠者希望保持匿名身份。'],
                                            ['incognito', 'innominate', 'unnamed', 'unidentified', 'untitled'],
                                            ['dubbed', 'named', 'termed']),
                                    TestWay('adj',
                                            '无特色的',
                                            'lacking individuality, distinction, or recognizability',
                                            ['the anonymous faces in the crowd 大众脸'])]),
                              Word('antagonize', "",
                                   [TestWay('vt',
                                            '敌对,反对',
                                            'to act in opposition to: counteract',
                                            ['He did not mean to antagonize you. 他并没有要反对你。', 'antagonize a bill 反对一项议案'],
                                            ['counteract', 'disagree'],
                                            ['agree', 'concede', 'grant', 'win over']),
                                    TestWay('vt',
                                            '激起敌意',
                                            'to incur or provoke the hostility of',
                                            ['His remark antagonized his friends. 他的评述激怒了他的朋友。'],
                                            ['aggravate', 'exasperate', 'gall', 'inflame', 'nettle', 'provoke', 'peeve', 'pique', 'irritate', 'rile', 'roil', 'chafe', 'grate', 'ruffle', 'vex'],
                                            ['soothe', 'defuse', 'allay', 'conciliate', 'propitiate', 'mitigate', 'assuage', 'appease', 'pacify', 'placate', 'calm', 'settle', 'subdue', 'solace', 'mollify'])]),
                              Word('antediluvian', "",
                                   [TestWay('adj',
                                            '非常古老的, 过时的',
                                            'extremely old and antiquated',
                                            ['He has antediluvian notions about the role of women in the workplace. 他对职场女性抱有老掉牙的看法。', 'an antediluvian automobile 古董级的汽车'],
                                            ['aged', 'age-old', 'prehistoric', 'antique', 'aged', 'immemorial'],
                                            ['modern', 'new', 'recent']),
                                    TestWay('n',
                                            '保守的人',
                                            'a person with old-fashioned ideas',
                                            ['an antediluvian who thought a woman without talent is virtuous 一个认为“女子无才便是德”的保守的人'],
                                            ['reactionary'],
                                            ['modern', 'trendy'])]),
                              Word('anterior', "",
                                   [TestWay('adj',
                                            '前面的',
                                            'coming before in time or development',
                                            ['finish the work anterior to the schedule 提早完成任务', 'tests anterior to the college entrance examination 高考前的考试'],
                                            ['antecedent', 'foregoing', 'former', 'forward', 'precedent', 'preceding', 'prior'],
                                            ['after', 'ensuing', 'following', 'posterior', 'subsequent', 'succeeding'])]),
                              Word('antic', "",
                                   [TestWay('adj',
                                            '滑稽可笑的',
                                            'characterized by clownish extravagance or absurdity',
                                            ['The clown came on with many antic gestures. 小丑上场表演许多滑稽动作。'],
                                            ['chucklesome', 'comedic', 'comic', 'droll', 'farcical', 'laughable', 'ludicrous', 'hilarious'],
                                            ['humorless', 'unamusing', 'uncomic', 'unfunny', 'unhumorous', 'grave', 'serious', 'solemn', 'somber'])]),
                              Word('apathy', "",
                                   [TestWay('n',
                                            '冷漠, 缺乏情感',
                                            'lack of feeling or emotion',
                                            ['People have shown surprising apathy toward these important social problems. 人们对于这些重要的社会问题显示出了令人惊讶的冷漠。'],
                                            ['affectlessness', 'emotionlessness', 'impassiveness', 'impassivity', 'insensibility', 'numbness', 'phlegm'],
                                            ['emotion', 'feeling', 'sensibility']),
                                    TestWay('n',
                                            '缺乏兴趣, 不关心',
                                            'lack of interest or concern',
                                            ['She heard the story with apathy. 她毫无兴趣的听完了这个故事。', 'Her poor grades are proof enough of her apathy concerning all matters academic. 她可怜的分数足以证明她对所有学术问题都没兴趣。'],
                                            ['disinterestedness', 'disregard', 'incuriosity', 'insouciance', 'nonchalance', 'unconcern'],
                                            ['concern', 'interest', 'regard'])]),
                              Word('aphorism', "",
                                   [TestWay('n',
                                            '短小有智慧的格言',
                                            'a short witty sentence which expresses a general truth or comment',
                                            ['When decorating, remember the familiar aphorism, “less is more.” 装修时需要记住的一句格言是“少即是多”。'],
                                            ['adage', 'epigram', 'maxim', 'proverb'])])])
list2_unit3 = VocabularyList([Word('apocalyptic', "",
                                   [TestWay('adj',
                                            '预言的, 启示的',
                                            'of a revelatory or prophetic nature',
                                            ['No one listened to her apocalyptic predictions. 没有人听她的预言。'],
                                            ['prophetic', 'predictive', 'prognostic', 'farsighted']),
                                    TestWay('adj',
                                            '重要的, 转折点的',
                                            'of, relating to, or being a major turning point',
                                            ['the apocalyptic Battle of Stalingrad leading to the ultimate defeat of Nazi Germany 具有转折点意义的斯大林格勒战役导致了最后纳粹德国的战败'],
                                            antonyms = ['trivial', 'petty', 'minor', 'immaterial', 'inconsequential', 'insignificant']),
                                    TestWay('adj',
                                            '夸大的',
                                            'wildly unrestrained : grandiose',
                                            ['apocalyptic tone 夸大的语气'])]),
                              Word('apocryphal', "",
                                   [TestWay('adj',
                                            '假的',
                                            'of doubtful authenticity : spurious',
                                            ["an apocryphal story about the president's childhood 一个假的关于总统童年的故事"],
                                            ['spurious', 'unauthentic', 'ungenuine'],
                                            ['factual', 'true', 'truthful', 'authentic'])]),
                              Word('apoplectic', "",
                                   [TestWay('adj',
                                            '极度愤怒的',
                                            'extremely angry; furious',
                                            ['He became apoplectic about wasteful government spending. 他对于政府的浪费开销变得怒不可遏。', 'The coach was so apoplectic when the player missed the free throw that he threw his clipboard onto the court. 教练对球员罚篮不进非常气愤以至于把战术板扔到了球场上。'],
                                            ['choleric', 'enraged', 'furious', 'incensed', 'indignant', 'infuriated', 'irate', 'ireful', 'outraged'],
                                            ['angerless', 'delighted', 'pleased'])]),
                              Word('apostasy', "",
                                   [TestWay('n',
                                            '放弃宗教信仰',
                                            'renunciation of a religious faith',
                                            ['Some people completely abandon the faith after apostasy. 有些人在放弃自己的宗教信仰后就再也不相信任何其他宗教信仰了。']),
                                    TestWay('n',
                                            '变节, 背叛',
                                            'abandonment of a previous loyalty : defection',
                                            ['He was looked down upon for apostasy. 他因为背叛而受到鄙视。'],
                                            ['defection', 'perfidy', 'treacherousness', 'recreancy'],
                                            ['fidelity', 'allegiance', 'loyalty', 'piety'])]),
                              Word('appall', "",
                                   [TestWay('v',
                                            '使惊恐',
                                            'to overcome with consternation, shock, or dismay',
                                            ['He felt appalled by the whole idea of marriage so we broke up. 结婚使他恐惧, 因此我们分手了。'],
                                            ['dismay', 'terrify', 'intimidate', 'frighten', 'horrify', 'daunt', 'deter'],
                                            ['embolden', 'encourage', 'nerve'])]),
                              Word('appeal', "",
                                   [TestWay('n',
                                            '申请',
                                            'an application (as to a recognized authority) for corroboration, vindication, or decision',
                                            ['A piteous appeal for help. 虔诚的请求帮助。', 'to make an appeal to the public to donate needed blood 向公众提出献血请求'],
                                            ['adjuration', 'conjuration', 'entreaty', 'petition', 'pleading', 'supplication']),
                                    TestWay('n',
                                            '起诉',
                                            'to charge with a crime : accuse',
                                            ["My lawyer said the court's decision wasn't correct and that we should file for an appeal. 我的律师说法庭的判决不对, 我们应该起诉。"],
                                            ['charge', 'accuse', 'incriminate', 'inculpate', 'indict'],
                                            ['absolve', 'exonerate', 'exculpate', 'vindicate'])]),
                              Word('appealing', "",
                                   [TestWay('adj',
                                            '吸引人的',
                                            'attractive, inviting',
                                            ['The large salary made Goldman Sachs’s offer more appealing to him. 高薪使高盛的工作对他更有吸引力。'],
                                            ['alluring', 'captivating', 'charismatic', 'charming', 'enchanting', 'engaging', 'entrancing', 'luring', 'seductive'],
                                            ['repellent', 'repelling', 'repugnant', 'repulsive', 'unalluring'])]),
                              Word('applause', "",
                                   [TestWay('n',
                                            '鼓掌, 认可',
                                            'approval publicly expressed (as by clapping the hands)',
                                            ['Her appearance was greeted with applause. 她的表现赢得了认可。'],
                                            ['acclamation', 'cheer', 'cheering', 'ovation', 'plaudit', 'rave'],
                                            ['hissing', 'booing'])]),
                              Word('apposite', "",
                                   [TestWay('adj',
                                            '相关的, 合适的',
                                            'highly pertinent or appropriate: apt',
                                            ['to enrich his essay with some very apposite quotations from famous people 用名人名言来丰富他的文章'],
                                            ['applicable', 'apropos', 'germane', 'pointed', 'relative', 'relevant'],
                                            ['extraneous', 'irrelevant', 'impertinent', 'irrelative', 'pointless'])]),
                              Word('appreciable', "",
                                   [TestWay('adj',
                                            '可感知的, 明显的',
                                            'capable of being perceived or measured; perceptible',
                                            ["the appreciable changes in temperature 气温明显的变化", "There doesn't seem to be any appreciable difference between this piece and that one. 这个和那个看上去没什么差别。"],
                                            ['apprehensible', 'perceptible', 'detectable', 'discernible', 'palpable', 'distinguishable', 'sensible'],
                                            ['impalpable', 'imperceptible', 'inappreciable', 'indistinguishable', 'insensible', 'undetectable'])])])
list2_unit4 = VocabularyList([Word('apprehension', "",
                                   [TestWay('n',
                                            '忧虑, 恐惧',
                                            'suspicion or fear especially of future evil',
                                            ["She had a strong apprehension about her sister's health 她非常担心她姐姐的健康。"],
                                            ['dread', 'foreboding', 'misgiving', 'anxiousness', 'unease', 'uneasiness', 'worry'],
                                            ['composure', 'equanimity', 'unconcern']),
                                    TestWay('n',
                                            '逮捕',
                                            'seizure by legal process : arrestment',
                                            ['apprehension of the thief 逮捕小偷'],
                                            ['arrest'],
                                            ['discharge']),
                                    TestWay('n',
                                            '理解',
                                            'the knowledge gained from the process of coming to know or understand something',
                                            ['a good apprehension of how computer systems work 对计算机是如何工作的有很好的理解'],
                                            ['understanding', 'comprehension'],
                                            ['incomprehension'])]),
                              Word('apprise', "",
                                   [TestWay('v',
                                            '通知, 告知',
                                            'to give notice to; inform',
                                            ['apprise him of the danger that may be involved 告知他可能涉及的危险'],
                                            ['inform', 'acquaint', 'make known to'],
                                            ['withhold information'])]),
                              Word('approbation', "",
                                   [TestWay('n',
                                            '同意',
                                            'an expression of warm approval',
                                            ['The proposal met his approbation. 这项建议得到了他的'],
                                            ['approval', 'favor'],
                                            ['disapproval', 'disapprobation', 'disfavor'])]),
                              Word('appropriate', "",
                                   [TestWay('v',
                                            '私自挪用',
                                            'to take possession of or make use of exclusively for oneself, often without permission',
                                            ['to appropriate private property 盗用私人财产', "The economy has been weakened by corrupt officials who have appropriated the country's resources fortheir own use. 经济因为腐败的官员们私自挪用国家资源而被削弱了。"],
                                            ['purloin', 'pirate', 'embezzle', 'peculate', 'usurp']),
                                    TestWay('adj',
                                            '适当的',
                                            'especially suitable or compatible: fitting',
                                            ["Red wine is a more appropriate choice with the meal. 红酒更适合这顿饭。", "I don't think jeans and a T-shirt are appropriate attire for a wedding. 我觉得穿牛仔和T恤去婚礼不太得体。"],
                                            ['apt', 'becoming', 'felicitous', 'fitting', 'proper', 'meet', 'suitable', 'apposite', 'apropos'],
                                            ['improper', 'inapposite', 'inappropriate', 'inapt', 'unmeet', 'unseemly', 'unsuitable'])]),
                              Word('apropos', "",
                                   [TestWay('adj',
                                            '相关的',
                                            'being both relevant and opportune',
                                            ['The actor announced to reporters that he would only answer to apropos questions about the movie. 演员向记者表示, 他只回答那些和电影有关的问题。'],
                                            ['appliacable', 'apropos', 'germane', 'pointed', 'relative', 'relevant'],
                                            ['extraneous', 'irrelevant', 'impertinent', 'irrelative', 'pointless']),
                                    TestWay('prep',
                                            '关于, 有关',
                                            'having to do with',
                                            ['to make a number of telling observations apropos the current political situation 做了很多关于当前政治形势有力的观察'],
                                            ['apropos', 'apropos of', 'as far as', 'as for, as regards (also as respects)', 'as to', 'concerning', 'of', 'on', 'regarding', 'respecting', 'touching', 'toward (or towards)'])]),
                              Word('apt', "",
                                   [TestWay('adj',
                                            '恰当的,合适的',
                                            'exactly suitable; appropriate',
                                            ['apt remark/choice/description 恰当的评述、选择、描述'],
                                            ['apropos', 'germane', 'relative', 'relevant', 'appropirate'],
                                            ['extraneous', 'irrelevant', 'impertinent', 'irrelative', 'inappropriate', 'improper', 'unseemly']),
                                    TestWay('adj',
                                            '有…倾向的, 可能的',
                                            'having a tendency: likely',
                                            ['He is apt to fly out in rage. 他容易发脾气。'],
                                            ['likely', 'inclined', 'tending', 'given'],
                                            ['unlikely', 'disinclined']),
                                    TestWay('adj',
                                            '聪明的',
                                            'keenly intelligent and responsive',
                                            ['an apt pupil 一个聪明的小学生', 'He is apt at mathematics. 他擅长数学。'],
                                            ['brilliant', 'clever', 'quick-witted', 'ready-witted', 'smart'],
                                            ['foolish', 'dull', 'dumb', 'stupid', 'unintelligent'])]),
                              Word('archaic', "",
                                   [TestWay('adj',
                                            '过时的, 久远的',
                                            'no longer current or applicable; antiquated',
                                            ['archaic laws 过时的法律'],
                                            ['antiquated', 'outdated', 'outmoded', 'prehistoric', 'superannuated'],
                                            ['fashionable', 'up-to-date', 'fresh', 'modern', 'new', 'novel'],
                                            "archaism 古语: the use of archaic diction or style【反】modern diction 新语")]),
                              Word('archetype', "",
                                   [TestWay('n',
                                            '典范, 榜样',
                                            'an ideal example of a type',
                                            ['an archetype of the successful entrepreneur 成功企业家的典范'],
                                            ['ideal', 'a perfect example', 'quintessence']),
                                    TestWay('n',
                                            '先驱, 鼻祖',
                                            'something belonging to an earlier time from which something else was later developed',
                                            ['The abacus is sometimes cited as the archetype of the modern digital calculator 算盘是现代计算器的鼻祖'],
                                            ['antecedent, foregoer, forerunner, precursor, predecessor, prototype']),
                                    TestWay('n',
                                            '原型',
                                            'something from which copies are made',
                                            ['Frankenstein, Dracula, Dr. Jekyll and Mr. Hyde are the archetypes that have influenced all subsequent horror stories. 弗兰肯斯坦、德古拉、 杰基尔博士以及海德先生影响了所有继之而来的恐怖故事的原型。'],
                                            ['archetype', 'prototype'])]),
                              Word('ardor', "",
                                   [TestWay('n',
                                            '狂热',
                                            'strong enthusiasm or devotion; zeal',
                                            ['His ardor was damped. 他的热情被泼了冷水。'],
                                            ['avidity', 'zeal', 'fervor', 'fervency', 'fervidness', 'passion', 'passionateness', 'vehemence'],
                                            ['apathy', 'torpor', 'impassivity', 'insensitivity'])]),
                              Word('arduous', "",
                                   [TestWay('adj',
                                            '难以做到, 费劲的',
                                            'hard to accomplish or achieve: difficult',
                                            ['a long and arduous undertaking 一项长期艰苦的任务', 'an arduous journey across miles of desert 艰苦的沙漠之旅'],
                                            ['grueling', 'laborious', 'taxing', 'onerous', 'burdensome'],
                                            ['easy', 'simple', 'unchallenging', 'undemanding', 'facile', 'effortless'])])])
list2_unit5 = VocabularyList([Word('argot', "",
                                   [TestWay('n',
                                            '隐语, 黑话, 行话',
                                            'a specialized vocabulary or set of idioms used by a particular group',
                                            ['groups communicating in their own secret argots 用他们秘密的行话交流的团体'],
                                            ['argot', 'cant', 'jargon', 'shoptalk'],
                                            ['standard language', 'common verbalism'])]),
                              Word('arrest', "",
                                   [TestWay('vt',
                                            '使不活跃',
                                            'to make inactive',
                                            ['arrest the growth of the tumor 抑制肿瘤生长'],
                                            ['check', 'rein', 'curb', 'contain', 'hamper', 'thwart', 'bring to a halt'],
                                            ['vitalize', 'activate', 'animate', 'invigorate', 'prod, goad', 'spur', 'galvanize', 'provoke', 'stimulate']),
                                    TestWay('n./v',
                                            '停止',
                                            'the stopping of a process or activity; to bring to a standstill',
                                            ['Science cannot yet arrest the process of aging. 科学不能阻止衰老。'],
                                            ['cease', 'cessation', 'closure', 'conclusion', 'discontinuance', 'discontinuation', 'ending', 'halt', 'stop', 'termination', 'check', 'stop'],
                                            ['continuance', 'continuation']),
                                    TestWay('v',
                                            '逮捕',
                                            "to take or keep under one's control by authority of law",
                                            ['She was charged with resisting arrest. 她因为拘捕受到起诉。'],
                                            ['apprehend'],
                                            ['discharge']),
                                    TestWay('v',
                                            '吸引注意力',
                                            'to hold the attention of as if by a spell',
                                            ['The behavior of the daredevil arrested pedestrians. 冒失鬼的行为吸引了行人们的注意力。'],
                                            ['enchant', 'fascinate', 'bedazzle', 'grip', 'hypnotize', 'mesmerize'])]),
                              Word('arresting', "",
                                   [TestWay('adj',
                                            '吸引人的',
                                            'attracting and holding the attention; striking',
                                            ['an arresting spectacle 吸引人的奇观'],
                                            ['absorbing', 'engaging', 'engrossing', 'enthralling', 'fascinating', 'gripping', 'immersing', 'intriguing', 'riveting'],
                                            ['boring', 'drab', 'tedious', 'monotonous', 'uninteresting'])]),
                              Word('arrhythmic', "",
                                   [TestWay('adj',
                                            '不规律的',
                                            'lacking rhythm or regularity',
                                            ['arrhythmic pulse 不规律的脉搏'],
                                            ['irregular', 'disorderly'],
                                            ['regular', 'orderly'])]),
                              Word('arrogance', "",
                                   [TestWay('n',
                                            '傲慢, 自大',
                                            'overbearing pride',
                                            ['Her arrogance has earned her a lot of enemies. 她的傲慢给她带来了很多敌人。'],
                                            ['assumption', 'bumptiousness', 'haughtiness', 'hauteur', 'imperiousness', 'loftiness', 'peremptoriness', 'pomposity', 'pompousness', 'presumptuousness', 'superciliousness'],
                                            ['humility', 'modesty', 'humbleness', 'unassumingness'])]),
                              Word('articulate', "",
                                   [TestWay('v',
                                            '清晰地表达',
                                            'to utter clearly and distinctly',
                                            ['He cannot articulate his thoughts. 他不能清楚地表达他的想法。', 'a theory first articulated by ancient philosophers 被古时哲学家阐明的理论'],
                                            ['enunciate'],
                                            ['murmur', 'mumble', 'mutter', 'slur']),
                                    TestWay('adj',
                                            '表达清晰的',
                                            'able to express oneself clearly and well',
                                            ['The television crew covering the science fair were looking for photogenic and articulate students to explain their projects on the air'],
                                            ['eloquent', 'fluent', 'silver-tongued', 'well-spoken'],
                                            ['inarticulate', 'ineloquent', 'unvocal'])]),
                              Word('ascendant', "",
                                   [TestWay('adj',
                                            '有影响力的, 主宰的',
                                            'dominant in position or influence; superior.',
                                            ['This idea was in the ascendant. 这种思想处于主导地位。'],
                                            ['superior', 'dominant', 'sovereign'],
                                            ['having no influence/power']),
                                    TestWay('adj',
                                            '.上升的',
                                            'moving upward: rising',
                                            ['The teacher told the students to write even numbers in ascendant order. 老师让学生们按升序写出偶数。'],
                                            antonyms = ['declining'])]),
                              Word('ascetic', "",
                                   [TestWay('adj',
                                            '禁欲的',
                                            'practicing strict self-denial as a measure of personal and especially spiritual discipline',
                                            ['This is an ascetic diet of rice and beans. 这是一顿禁欲的隐私, 只有米饭和豌豆。'],
                                            ['abstemious', 'abstinent', 'self-denying'],
                                            ['sumptuous', 'luxurious', 'licentious', 'sybaritic', 'voluptuous']),
                                    TestWay('n',
                                            '禁欲者',
                                            'a person who renounces material comforts and leads a life of austere self-discipline, especially as an act of religious devotion',
                                            ['We normally see an ascetic meditating in a Yogic pose. 我们通常会看见一个苦行者以瑜伽的姿势来冥想。'],
                                            ['stoic', 'spartan'],
                                            ['sybarite', 'hedonist', 'voluptuary', '奢侈逸乐的', '人享乐主义者', '酒色之徒'])]),
                              Word('aseptic', "",
                                   [TestWay('adj',
                                            '消毒的, 无菌的',
                                            'preventing infection',
                                            ['Surgery must be in aseptic environments. 手术必须处在无菌环境下'],
                                            ['sterile, germfree'],
                                            ['germy', 'unsterile', 'contaminated', 'tainted']),
                                    TestWay('adj',
                                            '缺乏活力的',
                                            'lacking vitality',
                                            synonyms = ['inactive', 'lackadaisical', 'languid', 'listless', 'spiritless'],
                                            antonyms = ['active', 'animated', 'energetic', 'energetic', 'vivacious']),
                                    TestWay('adj',
                                            '冷漠的',
                                            'emotion, or warmth',
                                            ['aseptic essays 没有感情的文章', 'an aseptic smile 漠然的微笑'],
                                            ['affectlessness', 'emotionlessness', 'impassiveness', 'impassivity', 'insensibility', 'numbness', 'phlegm'],
                                            ['emotion', 'feeling', 'sensibility'])]),
                              Word('askew', "",
                                   [TestWay('adj',
                                            '不成直线, 歪的',
                                            'out of line, awry',
                                            ['The picture hung askew. 画挂歪了。', 'His tie was askew. 他的领带歪了。'],
                                            ['crooked', 'cockeyed', 'oblique', 'lopsided', 'skewed', 'aslant', 'slanted', 'slanting', 'listing', 'tilted', 'awry'],
                                            ['aligned', 'straight', 'erect'])])])
list2_unit6 = VocabularyList([Word('aspect', "",
                                   [TestWay('n',
                                            '外表, 容貌',
                                            'appearance to the eye or mind',
                                            ['His face had a frightening aspect. 他的脸很吓人。'],
                                            ['appearance', 'look', 'figure', 'presence', 'mien'])]),
                              Word('asperity', "",
                                   [TestWay('n',
                                            '（举止、性情）粗暴',
                                            'roughness of manner or of temper',
                                            ['She responded with such asperity that we knew she was offended by the question. 她如此粗鲁的回答问题以至于我们知道这个问题冒犯到了她。'],
                                            ['roughness', 'crudity', 'rudeness', 'poignancy', 'harshness'],
                                            ['softness', 'mildness']),
                                    TestWay('n',
                                            '（环境）艰苦',
                                            'rigor, severity',
                                            ['He has encountered more than his share of asperities on the road to success. 在成功的道路上他已经遇到过比他应该承受的更多的艰辛。'],
                                            ['severity', 'hardness', 'hardship', 'rigor'])]),
                              Word('aspersion', "",
                                   [TestWay('n',
                                            '诽谤, 中伤',
                                            "a false or misleading charge meant to harm someone's reputation",
                                            ['cast aspersions on my loyalty 诽谤我的忠诚'],
                                            ['defamation', 'besmirchment', 'calumny', 'calumniation', 'maligning', 'obloquy', 'vilification'],
                                            ['glowing tribute', 'eulogy', 'extolling', 'laudation', 'praise', 'commendation', 'compliment', 'flattery', 'adulation'])]),
                              Word('aspirant', "",
                                   [TestWay('n',
                                            '有抱负者, 有野心者',
                                            'one who aspires, as to advancement, honors, or a high position',
                                            ['a bevy of ever-smiling aspirants for the Miss America title 一群想当美国小姐的少女', 'Envy can make oneself backward, self-confidence can tells him to be a aspirant. 妒忌能使自己落后, 自信能使自己上进。'],
                                            ['seeker'],
                                            ['noncandidate']),
                                    TestWay('adj',
                                            '想成为…的',
                                            'seeking to attain a desired position or status',
                                            ['The pilot was an aspirant astronaut. 这个飞行员想成为航天员。'])]),
                              Word('assent', "",
                                   [TestWay('vi',
                                            '同意',
                                            'to agree to something especially after thoughtful consideration',
                                            ['The general proposed a detailed plan and the president assented. 将军提出了一个细节化的计划, 总统同意了该计划。'],
                                            ['accede', 'agree', 'assent', 'consent', 'subscribe', 'come round'],
                                            ['dissent', 'disagree'])]),
                              Word('assert', "",
                                   [TestWay('vt',
                                            '断言, 肯定地说出',
                                            'to state or declare positively and often forcefully or aggressively',
                                            ['asserted one’s innocence 坚称自己无罪', 'He asserted that there were corrupt officials in the government. 他断言道政府里面一定存在腐败的官员。'],
                                            ['aver', 'allege', 'avow', 'avouch', 'insist'],
                                            ['deny', 'gainsay'])]),
                              Word('assertive', "",
                                   [TestWay('adj',
                                            '武断的, 强烈自信的',
                                            'inclined to bold or confident assertion; aggressively self-assured',
                                            ['You will have to make many personal judgments when being assertive. 当武断的时候你不得不做出很多个人选择。'],
                                            ['assertory', 'self-assured', 'self-assertive', 'peremptory'],
                                            ['diffident'])]),
                              Word('assess', "",
                                   [TestWay('v',
                                            '评估重要性、尺寸、价值等',
                                            'to determine the importance, size, or value of',
                                            ['We need to assess whether or not the system is working. 我们需要评估这个系统是否工作。', 'Damage to the boat was assessed at $5,000. 船的损失是$5,000。'],
                                            ['evaluate', 'appraise', 'guesstimate']),
                                    TestWay('v',
                                            '征收费用（如罚款）',
                                            'to establish or apply as a charge or penalty',
                                            ['The utility company will assess a fee if your payment is late. 如果你付款晚了, 公共事业公司会罚款。'],
                                            ['assess', 'charge', 'exact', 'fine', 'lay', 'levy', 'put'],
                                            ['remit'])]),
                              Word('assiduous', "",
                                   [TestWay('adj',
                                            '勤勉的, 专心仔细的',
                                            'marked by careful unremitting attention or persistent application; busy',
                                            ['tended his garden with assiduous attention 专心仔细地照看他的花园', 'The project required some assiduous planning. 项目需要细心的规划。'],
                                            ['diligent', 'industrious', 'sedulous'],
                                            ['idle', 'inactive', 'unbusy', 'unemployed', 'unoccupied'].
                                            'assiduity n. 勤勉: persistent application or diligence; unflagging effort.')]),
                              Word('assuage', "",
                                   [TestWay('vt',
                                            '缓和, 减轻',
                                            'to lessen the intensity of',
                                            ["He couldn't assuage his guilt over the divorce. 他无法减轻自己在离婚中的罪行。"],
                                            antonyms = ['aggravate', 'exacerbate']),
                                    TestWay('vt',
                                            '平息，抚慰',
                                            'to pacify or calm',
                                            ['Life contains sorrows that cannot be assuaged, and it is important to be honest in acknowledging this. 生活中存在着无法平息的悲伤，诚实地承认这个事实才是重要的。'],
                                            ['compose', 'soothe', 'calm', 'pacify', 'placate', 'appease', 'lighten', 'relieve', 'alleviate', 'allay', 'mitigate', 'moderate', 'conciliate', 'propitiate'],
                                            ['aggravate', 'annoy', 'enrage', 'exasperate', 'incense', 'infuriate', 'ire', 'irk', 'irritate', 'madden', 'nettle', 'peeve', 'provoke', 'rile', 'roil', 'vex']),
                                    TestWay('vt',
                                            '使满足',
                                            'to put an end to by satisfying',
                                            ['assuage his thirst 消渴', 'That meal certainly assuaged my hunger. 那顿大餐满足了我的口腹之欲。'],
                                            ['satisfy', 'sate', 'satiate', 'quench'])])])
list2_unit7 = VocabularyList([Word('astounding', "",
                                   [TestWay('adj',
                                            '令人吃惊的，出乎意料的',
                                            'causing astonishment or amazement',
                                            ['The richness and variety of the undersea environment are astounding．富饶而多样的海底环境是令人惊奇的。'],
                                            ['amazing', 'astonishing', 'blindsiding', 'dumbfounding', 'shocking', 'startling', 'stunning', 'stupefying'],
                                            ['unsurprising'])]),
                              Word('astute', "",
                                   [TestWay('adj',
                                            '机敏的，有洞察力的',
                                            'having or showing shrewdness and perspicacity',
                                            ['Astute salesmen know how to invest emotionally. 精明的推销员知道如何进行感情投资。'],
                                            ['canny', 'smart', 'shrewd', 'perspicacious', 'clear-eyed', 'clear-sighted', 'savvy', 'hardheaded'],
                                            ['unknowing'])]),
                              Word('asunder', "",
                                   [TestWay('adv',
                                            '分离成多部分或多片',
                                            'into separate parts or pieces',
                                            ['broken asunder 打碎', 'Buildings were burst asunder. 建筑物已经被炸成碎片了。'],
                                            ['piecemeal'],
                                            ['in a piece', 'together']),
                                    TestWay('adv',
                                            '分离',
                                            'apart from each other in position',
                                            ['A quite conscience sleeps in thunder, but rest and guilt live far asunder. 平静的良心能在雷声中入睡，而安宁和负罪则无法毗邻。'],
                                            ['apart'],
                                            ['together'])]),
                              Word('asylum', "",
                                   [TestWay('n',
                                            '收容所/ 保护所',
                                            'an inviolable place of refuge and protection giving shelter to criminals and debtors/something (as a building) that offers cover from the weather or protection from danger',
                                            ['an insane asylum 疯人院', "The embassy serves as an asylum for that country's nationals in need of help. 大使馆作为那国需要帮助的"],
                                            ['harbor', 'haven', 'refuge', 'sanctuary', 'sanctum'])]),
                              Word('asymmetrical', "",
                                   [TestWay('adj',
                                            '不平衡的,不对称的',
                                            'having no balance or symmetry',
                                            ['the asymmetrical construction 非对称的建筑'],
                                            ['asymmetric', 'nonsymmetrical', 'unsymmetrical', 'unbalanced'],
                                            ['symmetrical', 'balanced'])]),
                              Word('atone', "",
                                   [TestWay('v',
                                            '赎罪，弥补',
                                            'to make amends, as for a sin or fault',
                                            ['Blood must atone for blood. 以命抵命。', 'Even death cannot atone for the offence. 罪不容诛。'],
                                            ['redeem'])]),
                              Word('atrocious', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('attenuate', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('audacious', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('augur', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])])])
list2_unit8 = VocabularyList([Word('authentic', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('authority', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('autocracy', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('autonomy', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('avarice', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('aver', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('aversion', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('avid', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('awash', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('awe', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])])])
list2_unit9 = VocabularyList([Word('awkward', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('awning', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('awry', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('axiomatic', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('babble', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('backhanded', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('badger', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('badinage', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('bait', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('bale', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])])])
list2_unit10 = VocabularyList([Word('baleful', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('balk', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('balky', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('ballad', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('balloon', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('balm', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('banal', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('bane', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('banish', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])]),
                              Word('banter', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [''],
                                            [''],
                                            [''])])])

LIST2 = VocabularyList(list2_unit1.words+list2_unit2.words+list2_unit3.words+list2_unit4.words+list2_unit5.words+list2_unit6.words+list2_unit7.words+list2_unit8.words+list2_unit9.words+list2_unit10.words)


if __name__ == '__main__':
    print list2_unit1
