#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list22_unit1 = VocabularyList([Word('riveting', "",
                                   [TestWay('adj',
                                            '吸引人的, 极迷人的',
                                            "wholly absorbing or engrossing one's attention",
                                            ["The riveting novel has, as previously expected, become a national best-seller. 正如先前所预料的, 这本引人入胜的小说成为了畅销书"],
                                            'absorbing, arresting, engaging, engrossing, enthralling, fascinating, immersing, intriguing, involving',
                                            'insipid, vapid, boring, dull, monotonous, tedious')]),
                              Word('rivulet', "",
                                   [TestWay('n',
                                            '小河, 小溪',
                                            'a small stream',
                                            ["Dream Rivulet Diary 《梦溪笔谈》"],
                                            'brook, brooklet, creek, streamlet')]),
                              Word('robust', "",
                                   [TestWay('adj',
                                            '精力充沛的, 强壮的, 健康的',
                                            'full of health and strength',
                                            ["a robust older man who still bicycles 10 miles a day 一个每天骑行10英里的充满活力的老人"],
                                            'bouncing, dynamic, energetic, gingerly, hale, potent, strong, sound, vigorous, vital, wholesome',
                                            'delicate, frail, weak, ailing, diseased, ill, sick, unfit, unhealthy, unsound',
                                            'robustness n. 健壮, 活力四射')]),
                              Word('roil', "",
                                   [TestWay('vt',
                                            '搅浑, 使混乱',
                                            'to stir up; disorder',
                                            ["He roiled the brook with his wood stick. 他用他的木棍将溪水搅浑。", "Financial markets have been roiled by the banking crisis. 银行业的危机搅乱了金融市场的秩序。"],
                                            'disarray, disorder, disrupt, disturb, mess, muddle, rile',
                                            'arrange, array, order, organize, regulate'),
                                    TestWay('vt',
                                            '激怒',
                                            'to displease or disturb',
                                            ["Some of his roommate’s habits began to roil him. 他室友的􁸀些习惯开始让他恼火。"],
                                            'aggravate, enrage, exasperate, incense, inflame, infuriate, irritate, provoke, rile, vex',
                                            'delight, gratify, please')]),
                              Word('roisterer', "",
                                   [TestWay('n',
                                            '喝酒喧闹的人',
                                            'one who engages in merrymaking especially in honor of a special occasion',
                                            ["the rowdy roisterers who fill the streets of New Orleans during Mardi Gras 四旬斋前最后一天遍布新奥尔良各条街道的喧闹人群"],
                                            'celebrator, merrymaker, partyer (also partier), partygoer, reveler',
                                            'killjoy')]),
                              Word('rookie', "",
                                   [TestWay('n',
                                            '新兵; 新手; 菜鸟',
                                            'recruit; novice',
                                            ["The rookie replaced the injured regular at first base. 这个新手代替了受伤的一垒手。"],
                                            'apprentice, fledgling, freshman, greenhorn, neophyte, novice, recruit, tyro',
                                            'veteran')]),
                              Word('roster', "",
                                   [TestWay('n',
                                            '值勤表, 花名册',
                                            'a roll or list of personnel',
                                            ["the roster of subscribers to the journal 杂质订阅者名册"],
                                            'catalog, checklist, list, menu, roll, schedule')]),
                              Word('rostrum', "",
                                   [TestWay('n',
                                            '讲坛, 演讲坛',
                                            'a stage for public speaking',
                                            ["He finally stood on the winner's rostrum. 他终于站在了胜利者的领奖台上。"],
                                            'dais, lectern, podium, stage, stand, tribune')]),
                              Word('rouse', "",
                                   [TestWay('v',
                                            '激起, 煽动',
                                            'to stir up',
                                            ["He was roused to fury. 他大为光火。"],
                                            'agitate, excite, motivate, provoke, stimulate',
                                            'allay, alleviate, assuage, ease, mitigate, mollify, palliate, relieve, soothe'),
                                    TestWay('v',
                                            '唤醒',
                                            'to cause to stop sleeping',
                                            ["The piercing siren roused her from a deep sleep 刺耳的警笛声将她从沉睡中唤醒。"],
                                            'arouse, awake, awaken, waken',
                                            'lull')]),
                              Word('royalty', "",
                                   [TestWay('n',
                                            '皇家身份',
                                            'regal character or bearing',
                                            synonyms = 'aristocracy, nobility'),
                                    TestWay('n',
                                            '版税',
                                            'a payment to an author or composer for each copy of a work sold or to an inventor for each item sold under a patent',
                                            ["charge KTV owners royalty fee 向KTV 索取版权费"])])])

list22_unit2 = VocabularyList([Word('rubicund', "",
                                   [TestWay('adj',
                                            '红润的, 健康的',
                                            'inclined to a healthy rosiness',
                                            ["A rubicund complexion indicates good health. 红润的气色意味着健康的身体。"],
                                            'blooming, florid, flush, rosy, ruddy, sanguine',
                                            'ashen, pale, pallid, wan')]),
                              Word('rudimentary', "",
                                   [TestWay('adj',
                                            '初始的, 未发展的',
                                            'being in the earliest stages of development',
                                            ["The equipment of these past empire-builders was rudimentary. 过去这些帝国的建造者们使用的都是极其原始的工具。"],
                                            'incipient, nascent, primitive, primordial',
                                            'developed, full-blown, mature, ripe'),
                                    TestWay('adj',
                                            '最根本的, 基础的',
                                            'consisting in first principles: fundamental',
                                            ["The dropout had only a rudimentary knowledge of science. 这个辍学的孩子对科学知识只有最基本的一些了解。"],
                                            'basic, elemental, essential, fundamental, rudimental, underlying',
                                            'advanced, higher')]),
                              Word('rue', "",
                                   [TestWay('n',
                                            '后悔, 遗憾',
                                            'the feeling of regret, remorse, or sorrow for',
                                            ["With rue my heart is laden. 我的内心充满了遗憾。"],
                                            'contriteness, contrition, penitence, regret, remorse, remorsefulness, repentance',
                                            'impenitence, remorselessness',
                                            'rueful adj. 后悔的')]),
                              Word('ruffle', "",
                                   [TestWay('n',
                                            '皱褶, 褶裥花边',
                                            'a strip of fabric gathered or pleated on one edge',
                                            synonyms = 'rumple, wrinkle',
                                            other_form = 'ruffled adj. 有褶裥边修饰的'),
                                    TestWay('vt',
                                            '使粗糙',
                                            'to destroy the smoothness or evenness of',
                                            ["The acid ruffled the surface of the catalyst. 酸使得催化剂的表面变得粗糙。"],
                                            'abrade, chafe, erode, roughen, rub, wear',
                                            'glaze, smooth'),
                                    TestWay('vt',
                                            '扰乱, 打扰',
                                            'to disturb the peace of mind of (someone) especially by repeated disagreeable acts',
                                            ["The stream of minor complaints finally ruffled him into snapping, “If you don’t like the way I’m doing it, do it yourself!” 一系列的抱怨终于让他爆发: “如果你不喜欢我做事的方法, 你就自己去做！”"],
                                            'annoy, bother, chafe, frost, gall, grate, itch, nettle, peeve, persecute, pique, rasp, rile, vex',
                                            'allay, alleviate, assuage, ease, mitigate, mollify, palliate, relieve, soothe')]),
                              Word('ruminate', "",
                                   [TestWay('vt',
                                            '沉思',
                                            'to go over in the mind repeatedly and often casually or slowly',
                                            ["ruminated the reason past failures 沉思以往失败的原因"],
                                            'cogitate, contemplate, deliberate, meditate, perpend, ponder, weigh',
                                            'ignore, neglect, overlook',
                                            'ruminative adj. 沉思的')]),
                              Word('rumple', "",
                                   [TestWay('vt',
                                            '使皱, 弄皱',
                                            'to wrinkle or form into folds or creases',
                                            ["The guest rumpled the antique bedspread by sitting on it. 客人坐在古董床单上把它弄皱了。"],
                                            'crinkle, crumple, ruffle, scrunch, wrinkle',
                                            'flatten, smooth, preen'),
                                    TestWay('vt',
                                            '打乱, 使不整齐',
                                            'to undo the proper order or arrangement of',
                                            ["The aunt would invariably rumple the little boy's hair whenever she came to visit. 不论小男孩的姨妈何时摆放, 她总要弄乱他的头发。"],
                                            'disarray, disorder, disorganize, disrupt, disturb, mess, muddle, upset',
                                            'arrange, array, order, organize, regulate',
                                            'rumpled adj. 褶皱的')]),
                              Word('run', "",
                                   [TestWay('n',
                                            '(不间断的)连续演出',
                                            'an unbroken course of performances or showings',
                                            ["The play had a long run. 此剧一口气演了很长时间"],
                                            'continuance, duration, persistence')]),
                              Word('runic', "",
                                   [TestWay('adj',
                                            '神秘的',
                                            'having some secret or mysterious meaning',
                                            ["painstaking efforts to decipher the runic inscriptions 为破解神秘的碑文付出的辛勤劳动"],
                                            'arcane, enigmatic, impenetrable, inscrutable, mysterious, mystic, occult, uncanny',
                                            'comprehendible, fathomable')]),
                              Word('rupture', "",
                                   [TestWay('v',
                                            '打破; 打碎',
                                            'to part by violence',
                                            ["Jealousy ruptured our friendly relationship. 嫉妒心破坏了我们的友谊。"],
                                            'breach, burst, disjoin, dissect, fracture, separate, split, sunder, tear',
                                            'associate, coalesce, combine, conjoin, conjugate, connect, fuse, interfuse, join, link, unify')]),
                              Word('ruse', "",
                                   [TestWay('n',
                                            '诡计',
                                            'a wily subterfuge',
                                            ["This was a ruse to divide them. 这是一招反间计。"],
                                            'artifice, maneuver, stratagem, trick, wile')])])

list22_unit3 = VocabularyList([Word('rustic', "",
                                   [TestWay('n',
                                            '乡下人, 头脑简单的人',
                                            'an awkward or simple person especially from a small town or the country',
                                            ["a rustic who was awed by the prices that city dwellers had to pay 一个被大城市房价所吓到的乡里人"],
                                            'bumpkin, churl, countryman, provincial, rube, yokel',
                                            'cosmopolitan, cosmopolite, sophisticate'),
                                    TestWay('adj',
                                            '乡村的',
                                            'of, relating to, associated with, or typical of open areas with few buildings or people',
                                            ["We went to a rustic area that is devoid of skyscrapers and shopping malls. 我们去了一个没有摩天大楼和购物中心的乡村原野。"],
                                            'bucolic, country, pastoral',
                                            'urban'),
                                    TestWay('adj',
                                            '粗俗的',
                                            'lacking in social graces or polish',
                                            ["clumsy, discourteous, gauche, impertinent, impolite, inelegant, rude, stiff"],
                                            'graceful, polished, urbane',
                                            'rustically adv. 粗俗地')]),
                              Word('rustle', "",
                                   [TestWay('v',
                                            '快速地行动',
                                            'to move or act energetically or with speed; to proceed or move quickly',
                                            ["The little boy rustled around enthusiastically on the first morning of the trip. 旅行的第一个早晨, 小男孩充满热情地在那活蹦乱跳。"],
                                            'bolt, breeze, careen, career, hasten, hustle, jump, run, rush, scurry',
                                            'crawl, creep')]),
                              Word('sabotage', "",
                                   [TestWay('n',
                                            '妨害, 破坏',
                                            'treacherous action to defeat or hinder a cause or an endeavor; deliberate subversion',
                                            ["sabotage of the project by government officials 被政府官员阻止的项目"],
                                            'damage, impairment, subversion, undermining',
                                            'assistance'),
                                    TestWay('vt',
                                            '从事破坏活动, 阻止',
                                            'to practice sabotage on',
                                            ["He sabotaged his opponent's campaign with rumors. 他用谣言来破坏对手的竞选活动。", "My ex-wife deliberately sabotages my access to the children. 我的前妻故意想方设法阻止我和我的孩子们见面。"],
                                            'disrupt, foil, frustrate, obstruct, undermine',
                                            'assist, support, advance, cultivate, forward, foster, further, nurture, promote')]),
                              Word('saccharine', "",
                                   [TestWay('adj',
                                            '像糖一样的, 有甜味的',
                                            'of, relating to, or resembling that of sugar',
                                            ["a powdery substance with a saccharine taste 有甜味的粉状物质"],
                                            'cloying, sugary',
                                            'bitter'),
                                    TestWay('adj',
                                            '做作的, 矫情的',
                                            'appealing to the emotions in an obvious and tiresome way',
                                            ["The movie was funny, but it had a saccharine ending in which everyone lives happily ever after. 电影还是很有意思的, 但是结局太做作了——所有人从此都幸福地生活在了一起。"],
                                            'fruity, maudlin, mawkish, mushy, sentimental, sugarcoated',
                                            'unsentimental')]),
                              Word('sacrilege', "",
                                   [TestWay('n',
                                            '亵渎圣物',
                                            'desecration, profanation, misuse, or theft of something sacred',
                                            ["To play Mozart's music on a kazoo is sacrilege. 用小木笛演奏莫扎特的音乐是对它的一种亵渎。"],
                                            'blasphemy, defilement, desecration, irreverence, impiety, profanation, violation',
                                            'adoration, glorification, respect, reverence',
                                            'sacrilegious adj. 不敬的, 亵渎神明的')]),
                              Word('saddle', "",
                                   [TestWay('vt',
                                            '使某人负担',
                                            'to load or burden',
                                            ["He has saddled himself with a houseful of impecunious relatives. 一屋子的穷亲戚成了他的负担"],
                                            'burden, encumber, freight, lade, lumber, impose, inflict, tax, weight',
                                            'disburden, discharge, disencumber, unburden, unlade, unload')]),
                              Word('safeguard', "",
                                   [TestWay('n',
                                            '保护措施',
                                            'a technical contrivance to prevent accident',
                                            ["legal safeguards against fraud 防止欺诈的法律措施"],
                                            'aegis, caution, defense, fail-safe, guard, palladium, precaution, preventive, security'),
                                    TestWay('v',
                                            '保护',
                                            'to make safe: protect',
                                            ["sheepdogs safeguard the flock from attacks by wolves 保护兽群免受狼群攻击的牧羊犬"],
                                            'bulwark, cover, defend, fence, fend, guard, keep, protect, screen, secure, shield, ward',
                                            'assail, assault, attack')]),
                              Word('sage', "",
                                   [TestWay('n',
                                            '智者',
                                            'one (as a profound philosopher) distinguished for wisdom',
                                            ["The young prince made a pilgrimage to the sage, hoping to learn the meaning of life. 年轻的王子走上了向智者取经的道路, 希望能领悟到生命的真谛。"],
                                            'expert, illuminati, master, mentor, savant, scholar',
                                            'dolt, fool, idiot, simpleton',
                                            'sagacious adj. 睿智的; sagacity n. 聪慧')]),
                              Word('salient', "",
                                   [TestWay('adj',
                                            '显著的, 最突出的',
                                            'standing out conspicuously',
                                            ["The most salient feature of the book is its papyrus cover. 该书最明显的特点就是莎草纸的封面。"],
                                            'conspicuous, noticeable, outstanding, prominent, remarkable, striking',
                                            'inconspicuous, unnoticeable',
                                            'salience n. 突出, 特点')]),
                              Word('salubrious', "",
                                   [TestWay('adj',
                                            '有益健康的',
                                            'favorable to or promoting health or well-being',
                                            ["Every year I go to Kunming to enjoy its cool and salubrious climate. 每年我都会去昆明享受它那凉爽宜人的气候。"],
                                            'good, healthy, restorative, salutary, tonic, wholesome',
                                            'debilitating, deleterious, noxious, virulent')])])

list22_unit4 = VocabularyList([Word('salutary', "",
                                   [TestWay('adj',
                                            '有益健康的',
                                            'beneficial, promoting health',
                                            ["a salutary warning 善意的警告"],
                                            'good, healthy, restorative, salubrious, tonic, wholesome',
                                            'debilitating, deleterious, noxious, virulent'),
                                    TestWay('adj',
                                            '有利的, 利好的',
                                            'promoting or contributing to personal or social well-being',
                                            ["The low interest rates should have a salutary effect on business. 低利率对于商业而言应该是有利的。"],
                                            'advantageous, benefic, beneficent, benignant, favorable, friendly, helpful, kindly, profitable',
                                            'bad, disadvantageous, unfavorable, unfriendly, unhelpful, unprofitable')]),
                              Word('salutation', "",
                                   [TestWay('n',
                                            '致敬, 打招呼(表示欢迎和礼貌)',
                                            'a polite expression of greeting or goodwill',
                                            ["The veteran stepped forward, raising his hand in salutation. 老兵向前一步, 举起手致敬。"],
                                            'greeting, regards, salute',
                                            'farewell, bon voyage'),
                                    TestWay('n',
                                            '表扬',
                                            'a formal expression praise',
                                            ["The speaker introduced the evening's honored guest with a lavish salutation. 主持人用大量表扬的话介绍了今晚的嘉宾。"],
                                            'accolade, citation, commendation, eulogium, eulogy, homage, hymn, paean, panegyric, tribute',
                                            'salute v. 敬礼, 致敬')]),
                              Word('salvage', "",
                                   [TestWay('v',
                                            '(从灾难中)抢救',
                                            'to save from loss or destruction',
                                            ["salvaged the torpedoed vessel 拯救被鱼雷击中的舰艇"],
                                            'rescue, retrieve, save',
                                            'abandon, desert, forsake',
                                            'salvageable adj. 可以挽回的')]),
                              Word('salve', "",
                                   [TestWay('v',
                                            '减轻, 缓解',
                                            'quiet, assuage',
                                            ["The company give him a raise in salary to salve his feelings. 公司决定给他加薪以安抚他的感情"],
                                            'allay, balm, becalm, compose, lull, lullaby, quiet, settle, soothe, still, tranquilize',
                                            'agitate, discompose, disquiet, disturb, perturb, upset, vex')]),
                              Word('sanctify', "",
                                   [TestWay('vt',
                                            '使神圣, 敬为神',
                                            'to make holy',
                                            ["The Constitution sanctified the rights of the people. 宪法认为人权是至高无上的。"],
                                            'consecrate, hallow',
                                            'desecrate, profane',
                                            'sanctification n. 敬为神明')]),
                              Word('sanctimonious', "",
                                   [TestWay('adj',
                                            '假装虔诚的',
                                            'hypocritically pious or devout',
                                            ["a sickening sanctimonious smile 令人厌恶的伪善的笑容"],
                                            'canting, deceiving, hypocritical',
                                            'devout, religious, pious')]),
                              Word('sanction', "",
                                   [TestWay('v',
                                            '批准, 同意, 认可',
                                            'to make valid or binding usually by a formal procedure (as ratification)',
                                            ["The President sanctioned covert operations. 总统批准了秘密行动", "The administration will sanction almost any field trip with educational value. 基本上任何有教育意义的实地考察都可以得到批准。"],
                                            'accredit, approbate, authorize, certify, confirm, finalize, formalize, license, ratify, warrant',
                                            'interdict, prohibit, proscribe, decline, deny, disallow, disapprove, negative, reject, veto'),
                                    TestWay('n',
                                            '制裁',
                                            'an economic or military coercive measure adopted usually by several nations in concert for forcing a nation violating international law to desist or yield to adjudication',
                                            ["Another trade sanction is in effect. 又一项贸易制裁生效了。"],
                                            'penalty, punishment')]),
                              Word('sanctuary', "",
                                   [TestWay('n',
                                            '避难所',
                                            'a place of refuge and protection',
                                            ["In earlier times a criminal could use a church as a sanctuary. 在早期, 犯罪分子可以将教堂当作避难所。"],
                                            'asylum, cover, harbor, haven, port, refuge, shelter')]),
                              Word('sand', "",
                                   [TestWay('vt',
                                            '磨光',
                                            'to make smooth by friction',
                                            ["Be sure to sand before you paint the shelf. 在上漆之前一定要先磨光。"],
                                            antonyms = 'buff, file, hone, rasp, rub')]),
                              Word('sanguine', "",
                                   [TestWay('adj',
                                            '乐观的, 确信的',
                                            'having or showing a mind free from doubt',
                                            ["I'm reasonably sanguine about the adoption of the latest proposal. 我非常看好最新的那项提议获得通过。"],
                                            'assured, confident, doubtless, implicit, positive',
                                            'doubtful, dubious, uncertain, unsure'),
                                    TestWay('adj',
                                            '面色红润的',
                                            'having a healthy reddish skin tone',
                                            ["a baby with a sanguine complexion is more likely to leave the hospital early than a sickly-looking one 面色红润的新生儿比病怏怏的能更早出院"],
                                            'blooming, florid, flush, glowing, rosy, rubicund',
                                            'ashy, doughy, livid, lurid, mealy, pale, pallid, pasty, peaky, sallow, wan')])])

list22_unit5 = VocabularyList([Word('sanitary', "",
                                   [TestWay('adj',
                                            '健康的, 清洁的',
                                            'of or relating to health',
                                            ["sanitary measures 保健的手段"],
                                            'aseptic, germfree, hygienic, sterile',
                                            'noxious')]),
                              Word('sap', "",
                                   [TestWay('vt',
                                            '削弱',
                                            'to weaken or exhaust the energy or vitality of',
                                            ["Weeks of hard work had sapped hum and left him exhausted. 连续几周辛苦工作让他筋疲力尽。"],
                                            'debilitate, devitalize, enervate, enfeeble, etiolate, prostrate',
                                            'bolster, fortify, invigorate, beef up'),
                                    TestWay('n',
                                            '健康, 活力',
                                            'active strength of body or mind',
                                            ["a child full of sap and vivacity 活力满满的孩子"],
                                            'dynamism, energy, esprit, get-up-and-go, gusto, verve, vim, vitality',
                                            'lethargy, listlessness, sluggishness, torpidity')]),
                              Word('sapient', "",
                                   [TestWay('adj',
                                            '聪明的, 有洞察力的',
                                            'having or showing deep understanding and intelligent application of knowledge',
                                            ["a man who is always good for valuable insights and some sapient advice 一个以见解深刻、建议明智著称的男人"],
                                            'discerning, insightful, perceptive, prudent, sagacious, sage',
                                            'foolish, unperceptive, unwise')]),
                              Word('sarcasm', "",
                                   [TestWay('n',
                                            '讽刺, 轻蔑',
                                            'a sharp and often satirical or ironic utterance designed to cut or give pain',
                                            ["a voice full of sarcasm 充满轻蔑的言论"],
                                            'affront, barb, indignity, offense, slap, slight, slur',
                                            'praise')]),
                              Word('sartorial', "",
                                   [TestWay('adj',
                                            '裁缝匠的, 裁缝的',
                                            'of or relating to a tailor or tailored clothes',
                                            ["poor sartorial taste 很烂的穿衣品位"])]),
                              Word('sate', "",
                                   [TestWay('vt',
                                            '使饱足, 充分满足',
                                            'to glut; to satisfy (an appetite) fully',
                                            ["The information sated her curiosity. 这个消息满足了她的好奇心。"],
                                            'cram, glut, stuff, surfeit, satiate',
                                            'starve')]),
                              Word('satiate', "",
                                   [TestWay('v./adj',
                                            '饱足, 过分满足',
                                            'to satisfy fully or to excess',
                                            ["A long drink of water satiated my thirst. 一顿痛饮之后我的口渴得到了缓解"],
                                            'replete, sate, stuff, surfeit',
                                            'tantalize')]),
                              Word('satire', "",
                                   [TestWay('n',
                                            '讽刺诗, 讽剌文学',
                                            'a literary work holding up human vices and follies to ridicule or scorn',
                                            ["a satire about the music industry in which a handsome but untalented youth is turned into a rock star 一部关于一个长得帅却没才华的年轻人如何被打造成一个摇滚巨星的讽刺文学作品"],
                                            'lampoon, pasquinade')]),
                              Word('satirize', "",
                                   [TestWay('vt',
                                            '讽刺',
                                            'to ridicule or attack by means of satire',
                                            ["The movie satirizes contemporary life. 这部电影讽刺当下生活。"])]),
                              Word('saturate', "",
                                   [TestWay('v./adj',
                                            '使饱和, 浸透',
                                            'to wet thoroughly with liquid',
                                            ["Saturate the sponge with water. 将海绵浸透"],
                                            'bathe, douse, drench, soak, souse, bedraggle',
                                            'wring out')])])

list22_unit6 = VocabularyList([Word('saturnine', "",
                                   [TestWay('adj',
                                            '忧郁的, 阴沉的',
                                            'causing or marked by an atmosphere lacking in cheer',
                                            ["The men awaiting interrogation by the police shared a saturnine silence. 等待警察审问的人们脸色阴沉, 沉默不语。"],
                                            'bleak, depressive, dismal, dreary, miserable, solemn',
                                            'jovial, bright, cheerful, comforting, cordial, festive, heartwarming, sunshiny'),
                                    TestWay('adj',
                                            '讥讽的',
                                            'having a sardonic aspect',
                                            ["a saturnine smile 讥讽的笑容"],
                                            antonyms = 'genial')]),
                              Word('saunter', "",
                                   [TestWay('vi',
                                            '闲逛, 漫步',
                                            'to travel by foot for exercise or pleasure',
                                            ["sauntered slowly down the street 在街上闲逛"],
                                            'amble, ramble, range, stroll, wander, perambulate')]),
                              Word('savant', "",
                                   [TestWay('n',
                                            '博学之士, 学者',
                                            'a person of learning',
                                            ["a savant in the field of medical ethics 医学伦理方面的专家"],
                                            'pundit, scholar',
                                            'unlearned person')]),
                              Word('savory', "",
                                   [TestWay('adj',
                                            '口感好的, 味道好的',
                                            'appetizing to the taste or smell',
                                            ["cedar is one of the most savory of all woods 雪松是所有树木中味道最好闻的"],
                                            'ambrosial, appetizing, dainty, palatable, scrumptious',
                                            'noisome, fetid, foul, malodorous, putrid, rancid, reeking, smelly, stenchy, stinky'),
                                    TestWay('adj',
                                            '令人愉悦的',
                                            'giving pleasure or contentment to the mind or senses',
                                            ["having to fire someone was not a task that the manager found at all savory 经理发现不得不开除某人是件非常不讨好的事"],
                                            'agreeable, blessed, congenial, delectable, delicious, delightful, dulcet, enjoyable, felicitous, grateful, gratifying, heavenly, jolly, luscious, palatable, pleasurable, satisfying, tasty, welcome',
                                            'disagreeable, pleasureless, unpalatable, unpleasant, unwelcome')]),
                              Word('savvy', "",
                                   [TestWay('n',
                                            '老练, 机智',
                                            'knowledge gained by actually doing or living through something',
                                            ["political savvy 政治上的老脸精明"],
                                            'chops, expertise, proficiency, know-how',
                                            'simplicity, tactlessness, inexperience'),
                                    TestWay('v',
                                            '明确了解',
                                            'to have a clear idea of',
                                            ["The man growled, “Don't ever date my daughter again—you savvy?” 那男人咆哮道, “你丫以后不准再见我女儿, 你的明白？”"],
                                            'appreciate, apprehend, assimilate, behold, catch on, cognize, compass, conceive, decipher, decode, discern, grasp, perceive, recognize, register, seize, tumble to',
                                            'miss'),
                                    TestWay('adj',
                                            '有见识, 精明能干的',
                                            'having or showing a practical cleverness or judgment',
                                            ["a particularly savvy investor, he was among the first to see the potential in tech stocks 一个有卓识远见的投资者, 是第一批看到科技类股票升值潜力的人"],
                                            'astute, canny, clear-eyed, clear-sighted, hard-boiled, hardheaded, heady, sharp, sharp-witted, smart',
                                            'unknowing')]),
                              Word('scads', "",
                                   [TestWay('n',
                                            '许多, 大量',
                                            'a large number or quantity',
                                            ["scads of people showed up for the party 参加派对的人们蜂拥而至"],
                                            'abundance, plenitude, profusion, slew, spate, wealth',
                                            'paucity')]),
                              Word('scant', "",
                                   [TestWay('adj',
                                            '不足的, 缺乏的',
                                            'barely or scarcely sufficient',
                                            ["jobs for teenagers were scant that summer 那年暑假适合青少年们做的工作很少"],
                                            'exiguous, niggardly, scarce, sparse, stingy',
                                            'considerable, copious, voluminous, profuse, myriad')]),
                              Word('scathing', "",
                                   [TestWay('adj',
                                            '尖酸刻薄的',
                                            'marked by the use of wit that is intended to cause hurt feelings',
                                            ["a scathing review of the book 尖刻的书评"],
                                            'acerbic, acid, acrid, pungent, scalding, snarky, tart',
                                            'polite, calm compliment')]),
                              Word('schism', "",
                                   [TestWay('n',
                                            '不一致',
                                            'a lack of agreement or harmony',
                                            ["a schism between political parties 党派间的冲突"],
                                            'conflict, discordance, disharmony, dissidence, dissonance, disunion, friction, strife',
                                            'accord, agreement, concord, harmony, peace')]),
                              Word('scintillate', "",
                                   [TestWay('vi',
                                            '闪耀',
                                            'to emit sparks',
                                            ["diamond ring scintillated in the sunlight 钻戒在阳光下闪闪发光"],
                                            'gleam, glimmer, glisten, glister, luster, sparkle, winkle',
                                            other_form = 'scintillating 才气横溢的: brilliantly lively, stimulating, or witty 【例】a scintillating conversation 【反】dull, foolly 迟钝的')])])

list22_unit7 = VocabularyList([Word('scion', "",
                                   [TestWay('n',
                                            '子孙',
                                            'descendant, child',
                                            ["scion of a railroad empire 铁路大王的后代"],
                                            antonyms = 'ancestor')]),
                              Word('scission', "",
                                   [TestWay('n',
                                            '切断, 分离, 分裂',
                                            'a division or split in a group or union: schism',
                                            ["The scission of the labor union will compromise the workers' bargaining power 工会内部的分裂会削弱工人讨价的力量"],
                                            'bifurcation, cleavage, dissolution, division, partition, schism, sundering',
                                            'unification, union')]),
                              Word('scoff', "",
                                   [TestWay('vt',
                                            '嘲笑',
                                            'to treat or address with derision: mock',
                                            ["scoffed at the idea 对这个提议不屑一顾"]),
                                    TestWay('v',
                                            '狼吞虎咽',
                                            'to swallow or eat greedily',
                                            ["scoffed dinner before running off to the basketball game 风卷残云般把晚饭消灭了, 就直奔向篮球场"],
                                            'cram, devour, glut, gorge, gormandize, gulp, ingurgitate, inhale, raven')]),
                              Word('scorch', "",
                                   [TestWay('vt',
                                            '炙烤, 烘干',
                                            'to burn on the surface; to make dry',
                                            ["scorching sun 火辣辣的太阳"],
                                            'dehydrate, desiccate, parch, sear, singe',
                                            'dampen, hydrate, wash, water, wet')]),
                              Word('scorn', "",
                                   [TestWay('vt',
                                            '轻蔑, 鄙视, 不屑',
                                            'reject or dismiss as contemptible or unworthy',
                                            ["They were scorned as fanatics. 他们被指责为狂热分子。"],
                                            'despise, disregard, flout, contemn, disdain, slight, look down (on or upon)',
                                            'adulate, venerate, honor, respect, revere')]),
                              Word('scotch', "",
                                   [TestWay('vt',
                                            '停止',
                                            'to put an abrupt end to',
                                            ["The prime minister scotched the rumors of her illness. 首相出面澄清了关于她死亡的谣言。"],
                                            'hinder, thwart')]),
                              Word('scour', "",
                                   [TestWay('vt',
                                            '用力擦洗',
                                            'to clean, polish, or wash by scrubbing vigorously'),
                                    TestWay('vt',
                                            '搜查',
                                            'to look through (as a place) carefully or thoroughly in an effort to find or discover something',
                                            ["the police scoured the city for the criminal 警方全城搜索罪犯"],
                                            'comb, dig through, dredge, hunt through, rake, ransack, rifle, rummage, sort through, troll')]),
                              Word('scowl', "",
                                   [TestWay('vi',
                                            '皱眉(表现出不高兴)',
                                            'to contract the brow in an expression of displeasure',
                                            ["scowled down at the misbehaving child 对淘气的孩子皱起了眉"],
                                            'frown, pout, glare, gloom, glower, lower',
                                            'beam, grin, smile')]),
                              Word('scrappy', "",
                                   [TestWay('adj',
                                            '好斗的, 好吵架的',
                                            'having an aggressive and determined spirit, quarrelsome',
                                            ["She was a scrappy girl despite—or, perhaps, because of—her small size.这个妹子好打斗, 但是身材娇小, 不过这很可能是原因"],
                                            'aggressive, assaultive, combative, militant, pugnacious, truculent',
                                            'nonaggressive, nonbelligerent, pacific, peaceful, unbelligerent, uncombative,, timorous')]),
                              Word('scrap', "",
                                   [TestWay('n',
                                            '废料, 废物',
                                            'discarded or useless material',
                                            ["The rest of this stuff is just scrap, so sweep it up and throw it away. 剩下的这堆东西都是没用的, 把它们打扫一下就扔了吧。"],
                                            'chaff, debris, dreck, dross, dust, effluvium, junk, litter, offal, offscouring, raffle, refuse, riffraff, rubbish, waste'),
                                    TestWay('vt',
                                            '抛弃',
                                            'to get rid of as useless or unwanted',
                                            ["We've decided to scrap the first car. 我们决定丢弃第一辆车。"],
                                            'ditch, dump, jettison, junk, toss, throw away',
                                            'retrieve'),
                                    TestWay('v',
                                            '终止, 放弃原计划',
                                            'to put an end to (something planned or previously agreed to)',
                                            ["We scrapped our plans to go to Paris, and set out the next day for Prague. 我们取消了去巴黎的计划, 第二天启程奔赴布拉格。"],
                                            'abandon, abort, drop, recall, repeal, rescind, revoke, call off, cry off',
                                            'continue, keep')])])

list22_unit8 = VocabularyList([Word('scrawl', "",
                                   [TestWay('vt',
                                            '乱涂, 潦草地写',
                                            'to write or draw awkwardly, hastily, or carelessly',
                                            ["scrawled a quick note, stuck it in their mailbox, and hurried off 草草写了张便条, 塞进他们的信箱然后匆匆跑了"],
                                            'scratch, squiggle',
                                            'write carefully')]),
                              Word('scribble', "",
                                   [TestWay('vt',
                                            '潦草地书写, 乱写',
                                            'to cover with scribbles, doodles, or meaningless marks',
                                            ["Students scribbled furiously as the teacher lectured. 老师一边讲, 学生们一边狂抄笔记。"],
                                            'scratch, scrawl, squiggle')]),
                              Word('scrupulous', "",
                                   [TestWay('adj',
                                            '正直的',
                                            "guided by or in accordance with one's sense of right and wrong; principled",
                                            ["Less scrupulous companies find ways to evade the law. 道德程度略低的公司钻法律的空子。"],
                                            'conscionable, ethical, honest, honorable, moral, principled',
                                            'cutthroat, dishonest, dishonorable, immoral, unconscionable, unethical, unjust, unprincipled'),
                                    TestWay('adj',
                                            '一丝不苟的',
                                            'taking, showing, or involving great care and effort',
                                            ["The task requires scrupulous attention to detail. 这项任务需要对细节一丝不苟。"],
                                            'careful, conscientious, fussy, meticulous')]),
                              Word('scrutable', "",
                                   [TestWay('adj',
                                            '可以理解的',
                                            'capable of being understood through study and observation; comprehensible',
                                            ["Her machinations and motives are all too scrutable to us who know her. 她的阴谋和动机对于了解她的我们来说非常昭然若揭"],
                                            'accessible, apprehensible, comprehensible, fathomable, legible',
                                            'mysterious, incoherent, incomprehensible, inscrutable, insensible')]),
                              Word('scrutinize', "",
                                   [TestWay('vt',
                                            '仔细检查',
                                            'to examine or observe with great care',
                                            ["I closely scrutinized my opponent's every move. 我仔细注意着对手的每一个举动。"],
                                            'examine, review, scan, survey, plumb, check (out)',
                                            'casually glance, gloss over')]),
                              Word('scuff', "",
                                   [TestWay('vt',
                                            '磨损',
                                            'to become scratched, chipped, or roughened by wear',
                                            ["a countertop that won't scuff 一块不易磨损的厨房台面"],
                                            'abrade, graze, scratch'),
                                    TestWay('v',
                                            '脚步拖沓',
                                            'to move heavily or clumsily',
                                            ["The miners scuffed past in heavy boots. 矿工们脚着厚重的靴子, 步履蹒跚。"],
                                            'barge, clomp, clump, flog, flounder, lump, plod, pound, shamble, slog, slough, stamp, stomp, stumble, stump, tramp, tromp, trudge',
                                            'breeze, coast, glide, slide, whisk')]),
                              Word('scurrilous', "",
                                   [TestWay('adj',
                                            '说粗话的',
                                            'given to the use of vulgar, coarse, or abusive language',
                                            ["scurrilous attacks on the senator 对参议院粗俗的攻击"],
                                            'contumelious, invective, opprobrious, truculent, vitriolic, vituperative')]),
                              Word('scurvy', "",
                                   [TestWay('adj',
                                            '下流, 让人鄙视的',
                                            'mean; contemptible',
                                            ["She was beset by a whole scurvy swarm of con artists. 她被一群下流的骗子艺术家蜂拥围攻。"],
                                            'deplorable, despicable, grubby, lousy, scummy, wretched',
                                            'admirable, commendable, creditable, laudable, meritorious, praiseworthy')]),
                              Word('seamy', "",
                                   [TestWay('adj',
                                            '肮脏的, 堕落的',
                                            'sordid; base',
                                            ["the seamy side of urban life 城市生活的肮脏面"],
                                            'sordid, base',
                                            'decent and respectable 适当而值得尊敬的')]),
                              Word('secluded', "",
                                   [TestWay('adj',
                                            '隐僻的, 隐蔽的',
                                            'screened or hidden from view',
                                            ["secluded monks 隐居的僧人"],
                                            'cloistered, covert, isolated, remote, retired, sheltered')])])

list22_unit9 = VocabularyList([Word('secrete', "",
                                   [TestWay('vt',
                                            '隐藏',
                                            'to conceal in a hiding place; cache',
                                            ["The police found the weapon secreted under the driver's seat of the getaway car. 警方在逃逸车辆驾驶座下发现了隐藏的武器。"],
                                            'bury, cache, conceal, ensconce',
                                            'divulge, display, exhibit'),
                                    TestWay('vt',
                                            '分泌',
                                            'to generate and separate (a substance) from cells or bodily fluids',
                                            antonyms = 'absorb')]),
                              Word('sedate', "",
                                   [TestWay('adj',
                                            '淡定的, 安静的',
                                            'free from emotional or mental agitation',
                                            ["She remained sedate under pressure. 她在压力下仍保持镇静。"],
                                            'collected, composed, self-possessed, serene, tranquil, undisturbed, unperturbed, unruffled',
                                            'agitated, discomposed, disturbed, flustered, perturbed, upset')]),
                              Word('sedentary', "",
                                   [TestWay('adj',
                                            '固定不动的',
                                            'not migratory: settled',
                                            ["a sedentary lifestyle 很宅的生活方式"],
                                            antonyms = 'migratory, peripatetic')]),
                              Word('seduce', "",
                                   [TestWay('vt',
                                            '劝说(使不忠, 使不服从), 诱…误入歧途',
                                            'to attract or persuade to disobedience or disloyaltys',
                                            ["The other firm seduced him with a better offer. 另一家公司用更高的待遇想挖他墙脚。"],
                                            'allure, decoy, entice, solicit, tempt, lead on',
                                            'repulse, ward off')]),
                              Word('sedulous', "",
                                   [TestWay('adj',
                                            '勤奋认真的',
                                            'involving or accomplished with careful perseverance',
                                            ["a sedulous student 一个勤奋地学生"],
                                            'assiduous, diligent, industrious, laborious, occupied, tied-up',
                                            'idle, inactive, unbusy, unemployed, unoccupied')]),
                              Word('seemly', "",
                                   [TestWay('adv',
                                            '得体的, 遵守礼节的',
                                            'following the established traditions of refined society and good taste',
                                            ["a young lady of seemly appearance, robust health, and keen intelligence 一个打扮得体、身体健康、头脑敏锐的姑娘"],
                                            'befitting, decent, decorous, genteel, respectable',
                                            'uncouth, ribald, indecorous, improper, inappropriate, indecent, indelicate, unbecoming, ungenteel, unseemly')]),
                              Word('segment', "",
                                   [TestWay('vt./n',
                                            '分割, 部分',
                                            'to separate into segments',
                                            ["I think I lost one segment of this model kit. 这套模型的一个零件我找不到了。"],
                                            'member, partition, portion, section')]),
                              Word('self-abasement', "",
                                   [TestWay('n',
                                            '自卑, 自谦',
                                            'degradation or humiliation of oneself',
                                            antonyms = 'self-asserting')]),
                              Word('self-absorbed', "",
                                   [TestWay('adj',
                                            '自恋的, 自私的',
                                            "absorbed in one's own thoughts, activities, or interests",
                                            ["a self-absorbed man who seems utterly oblivious to the social problems of his own urban neighborhood 一个超级自私的人, 对于街坊的事情完全视而不见"],
                                            'narcissistic, self-centered, self-infatuated, self-obsessed, self-oriented, self-preoccupied',
                                            'self-forgetting, selfless, unselfish')]),
                              Word('seminal', "",
                                   [TestWay('adj',
                                            '有发展性的',
                                            'containing or contributing the seeds of later development',
                                            antonyms = 'hampering further development'),
                                    TestWay('adj',
                                            '创新的',
                                            'of, relating to, or having the power to originate; creative',
                                            ["a seminal novel 新颖的小说"],
                                            antonyms = 'derivative')])])

list22_unit10 = VocabularyList([Word('sensation', "",
                                   [TestWay('n',
                                            '感觉, 知觉',
                                            'a perception associated with stimulation of a sense organ or with a specific body condition',
                                            ["We felt just the smallest sensation of warmth when we leaned against the radiator. 当我们靠着取暖器的时候, 我们也仅仅感到了一点点的温度。"],
                                            antonyms = 'anesthesia, numbness'),
                                    TestWay('n',
                                            '轰动事件',
                                            'a state of intense public interest and excitement',
                                            ["the rookie hitting sensation of the American League 这个菜鸟的表现轰动了整个全美大联盟"],
                                            'flash, marvel, miracle, phenomenon, portent, prodigy, splendor',
                                            'unnoticed event')]),
                              Word('sensitive', "",
                                   [TestWay('adj',
                                            '敏感的',
                                            'susceptible to the attitudes, feelings, or circumstances of others',
                                            ["he's very sensitive to the sun and will burn if he's outside for any amount of time 他的皮肤对日光非常敏感, 在外时间长了就会烧灼"],
                                            'susceptible, vulnerable, subject (to)',
                                            'numb')]),
                              Word('sentinel', "",
                                   [TestWay('n',
                                            '哨兵, 看守',
                                            'a person or group that watches over someone or something',
                                            ["a lone sentinel kept watch over the fort 一个哨兵看守着碉堡"],
                                            'custodian, guardian, keeper, lookout, minder, sentry, warden, watchman')]),
                              Word('sepulchral', "",
                                   [TestWay('adj',
                                            '阴沉的, 丧葬的',
                                            'causing or marked by an atmosphere lacking in cheer; funereal',
                                            ["the decrepit mansion had a sepulchral tone that gave everybody a chill 破旧的公馆有着一种坟墓的气息, 让人皆为之一颤"],
                                            'depressing, desolate, dismal, dreary, morose, sullen, tenebrous',
                                            'merry, bright, cheery, comforting, cordial, festive, heartwarming, sunshiny')]),
                              Word('septic', "",
                                   [TestWay('adj',
                                            '腐败的, 感染的',
                                            'of, relating to, or causing putrefaction',
                                            antonyms = 'free of infection')]),
                              Word('sequela', "",
                                   [TestWay('n',
                                            '结果',
                                            'a secondary consequence or result',
                                            antonyms = 'precursor')]),
                              Word('sequester', "",
                                   [TestWay('vt',
                                            '使隔绝, 分离',
                                            'to set apart: segregate',
                                            ["sequester a jury 让陪审团分开讨论"],
                                            'insulate, seclude, segregate, separate, cut off',
                                            'permit to mingle, desegregate, integrate, reintegrate'),
                                    TestWay('vt',
                                            '使隐退',
                                            'to cause to withdraw into seclusion',
                                            ["She was sequestered in her room. 她深居简出。"])]),
                              Word('sere', "",
                                   [TestWay('adj',
                                            '干枯的, 凋萎的',
                                            'being dried and withered',
                                            ["a sere region that can't support agriculture 一片贫瘠不能发展农业的地区"],
                                            'arid, droughty, thirsty, waterless',
                                            'lush, damp, dank, humid, moist, wet')]),
                              Word('serendipity', "",
                                   [TestWay('n',
                                            '意外发现珍奇(或称心)事物的本领',
                                            'the faculty of making fortunate discoveries by accident',
                                            ["They found each other by pure serendipity. 他俩的相识属于缘分天注定"])]),
                              Word('serene', "",
                                   [TestWay('adj',
                                            '安静的',
                                            'free from disturbing noise or uproar',
                                            ["a serene vacation spot 一处宁谧的度假胜地"],
                                            'arcadian, calm, hushed, peaceful, placid, restful, still, tranquil',
                                            'boisterous, clamorous, clattery, deafening, raucous, roistering, romping, rowdy, tumultuous, unquiet, uproarious'),
                                    TestWay('adj',
                                            '稳重的, 镇静的',
                                            'unaffected by disturbance; calm and unruffled',
                                            ["a serene man who was everyone's source of support 一个沉着镇静的男人, 他是所有人的精神支柱"],
                                            'collected, composed, possessed, recollected, undisturbed, unperturbed, unruffled',
                                            'agitated, discomposed, disturbed, flustered, perturbed, unhinged, unstrung, upset',
                                            'serenity n. 平静 the quality or state of being serene 【反】havoc, pandemonium, tumult, bedlam, riot, furor 混乱, 骚动')])])

LIST22 = VocabularyList(list22_unit1.words+list22_unit2.words+list22_unit3.words+list22_unit4.words+list22_unit5.words+list22_unit6.words+list22_unit7.words+list22_unit8.words+list22_unit9.words+list22_unit10.words)
