#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list31_unit1 = VocabularyList([Word('fervent', "",
                                   [TestWay('adj',
                                            '充满感情的, 热情洋溢的',
                                            'exhibiting or marked by great intensity of feeling',
                                            ["a fervent speech that called for tolerance and compassion for those who are physically challenged 一个充满感情的演说, 它呼吁人们对残疾人持有一颗包容和同情的心"],
                                            'ardent, demonstrative, fervid, flaming, glowing, impassioned, incandescent, passionate, perfervid, torrid, vehement, zealous',
                                            'cold, cool, dispassionate, emotionless, impassive, unemotional')]),
                              Word('figment', "",
                                   [TestWay('n',
                                            '虚构的事物, 幻觉',
                                            'something made up or contrived',
                                            ["Unable to find any tracks in the snow the next morning, I was forced to conclude that the shadowy figure had been a figment of my imagination. 第二天一早, 我没有在雪地上发现任何足迹, 由此我不得不相信昨晚幽灵一样的物体只是我的空想。", "Thus far, the invisible human being has been nothing more than a figment of fantasy writers. 到目前为止, 隐形人还仅仅只是玄幻小说笔下的构想。"],
                                            'chimera, conceit, daydream, delusion, dream, fancy, fantasy, hallucination, illusion, phantasm, vision',
                                            'fact, materiality, reality')]),
                              Word('forebode', "",
                                   [TestWay('vi',
                                            '预示, 预兆',
                                            'to show signs of a favorable or successful outcome',
                                            ["That police car parked outside the house doesn’t forebode well. 门外停着的那辆警车可不是什么好兆头。"],
                                            'augur, predict, promise',
                                            'foreboding n. 预感, 预兆')]),
                              Word('forfeit', "",
                                   [TestWay('n',
                                            '罚金',
                                            'a sum of money to be paid as a punishment',
                                            ["The forfeit for each baseball player involved in the brawl was $5,000. 参加打架的篮球运动员都受到了五千美元的罚款。"],
                                            'damages, fine, forfeiture, mulct, penalty',
                                            'bonus, premium, prize')]),
                              Word('forsake', "",
                                   [TestWay('vt',
                                            '彻底放弃, 抛弃',
                                            'to renounce or turn away from entirely',
                                            ["Forsaking most of our possessions, we evacuated just before the hurricane struck. 我们抛下了绝大多数的财产, 终于在海啸来袭之前撤离了。", "Her boyfriend has forsaken her. 她的男朋友将她抛弃。"],
                                            'abandon, desert, maroon, quit, renounce, strand',
                                            'reclaim, hold, keep, retain, withhold',
                                            'forsaken adj. 被抛弃的')]),
                              Word('germinate', "",
                                   [TestWay('vi',
                                            '发芽',
                                            'to begin to grow',
                                            ["Some seed varieties germinate very quickly. 有一些种子的变异体能够迅速发芽。"],
                                            'burgeon, shoot, sprout',
                                            'fade, flag, wilt, wither'),
                                    TestWay('vi',
                                            '出现',
                                            'to come into being',
                                            ["A truly marvelous proof of this theorem germinated in his mind. 这个定理的一种绝妙证明方法浮现在他的脑海之中。"],
                                            'develop, evolve, grow',
                                            'disappear, vanish',
                                            'germination n. 萌芽')]),
                              Word('grudge', "",
                                   [TestWay('n',
                                            '怨恨, 仇恨',
                                            'a feeling of deep-seated resentment or ill will',
                                            ["There has been a grudge between the two families for years. 两家之间积怨已深。", "He has had a deep grudge against her ever since she snubbed him at the dance. 自从她在舞会上对他不理不睬之后, 他就对她怀有深深的怨念。"],
                                            'animosity, animus, antagonism, antipathy, bitterness, gall, hostility, jaundice, malice, rancor, resentment',
                                            'amity')]),
                              Word('halfhearted', "",
                                   [TestWay('adj',
                                            '不感兴趣的, 不热情的',
                                            'lacking heart, spirit, or interest',
                                            ["a halfhearted attempt to clean the house before the arrival of the in-laws 在亲家到来前草草地收拾房间了事"],
                                            'lukewarm, tepid, uneager, unenthusiastic',
                                            'eager, enthusiastic, keen, passionate, warm, hearty, wholehearted')]),
                              Word('humdrum', "",
                                   [TestWay('n',
                                            '千篇一律, 单调',
                                            'a tedious lack of variety',
                                            ["She has been loathing the humdrum of daily life in a small town for a long time. 一直以来她很反感于小城镇里一成不变的生活。"],
                                            'monotone, monotonousness, sameness',
                                            'diversity, variety'),
                                    TestWay('adj',
                                            '无聊的, 乏味的',
                                            'lacking variety or excitement',
                                            ["trapped in a humdrum but well-paid job 陷于无聊但是收入可观的工作之中"],
                                            'arid, drab, dreary, drudging, jading, jejune, monochromatic, monotonous, pedestrian, ponderous, stale, stodgy, tedious, tiresome, wearisome',
                                            'absorbing, engaging, engrossing, gripping, interesting, intriguing, involving, riveting')]),
                              Word('humiliate', "",
                                   [TestWay('vt',
                                            '羞辱, 使丧失尊严',
                                            'to reduce to a lower position in one’s own eyes or others’ eyes',
                                            ["No student feels humiliated for not having the “right” clothes because everyone is wearing a school uniform. 因为所有学生都统一穿着学校的校服, 所以没有人会因为“不正确”的衣着而感觉尊严扫地。", "He humiliated me in front of my parents and I swear to retaliate. 他在我的父母面前让我难堪, 我发誓要报复他。"],
                                            'abase, chasten, cheapen, debase, degrade, demean, discredit, disgrace, dishonor, shame, sink, smirch',
                                            'aggrandize, canonize, deify, elevate, exalt',
                                            'humiliation n. 羞辱, 蒙羞')])])

list31_unit2 = VocabularyList([Word('hypothetical', "",
                                   [TestWay('n',
                                            '假设, 前提条件',
                                            'something taken as being true or factual and used as a starting point for a course of action or reasoning',
                                            ["He believes that predictions of the extinction of certain species as the result of global warming are based upon too many hypotheticals. 他认为所谓全球变暖会导致某些物种灭绝的说法基于过多的假设。"],
                                            'assumption, given, postulate, premise, presumption, presupposition, supposition',
                                            'conclusion, consequence, deduction, induction, inference'),
                                    TestWay('adj',
                                            '假定的',
                                            'existing only as an assumption or speculation',
                                            ["We talked about what we would do in various hypothetical emergencies. 我们讨论了在假定的各种紧急情况下的对策。"],
                                            'conjectural, speculative, supposed, suppositional',
                                            'actual, factual, real')]),
                              Word('impunity', "",
                                   [TestWay('n',
                                            '免责, 免受处罚',
                                            'exemption or freedom from punishment, harm, or loss',
                                            ["She mistakenly believed that she could insult people with impunity. 她错误地认为她可以肆无忌惮地羞辱他人。"],
                                            'exemption, immunity',
                                            'liability')]),
                              Word('incentive', "",
                                   [TestWay('n',
                                            '刺激, 诱因',
                                            'something that incites or has a tendency to incite to determination or action',
                                            ["The handsome reward for the missing wallet was an incentive for me to start looking. 找到丢失钱包的可观报酬激励我展开搜寻。", "A little bonus will give employees an incentive to work harder. 一点点奖金就可以刺激雇员更加努力地工作。"],
                                            'boost, goad, impetus, incitement, instigation, momentum, motivation, motive, provocation, spur, stimulant, stimulus, yeast',
                                            'deterrent, disincentive')]),
                              Word('justify', "",
                                   [TestWay('vt',
                                            '证明…的合理性, 辩解',
                                            'to prove or show to be just, right, or reasonable',
                                            ["failed to justify the need for a new expressway at this time 没能证明修建新的高速公路的合理性", "The storm warning justified his leaving early. 他的早退因为风暴预警而显得理所当然。"],
                                            'excuse, rationalize, warrant',
                                            other_form = 'justification n. (正当的)理由')]),
                              Word('license', "",
                                   [TestWay('n',
                                            '许可, 认可',
                                            'the approval by someone in authority for the doing of something',
                                            ["The company is seeking license to operate several more power plants in the state. 公司正在寻求在国内建造更多电厂的许可。", "A restaurant owner has to get a license to serve food and drink. 餐厅营业者必须要获得食物和饮品的销售许可。"],
                                            'allowance, authorization, clearance, concurrence, consent, empowerment, granting, sanction, warrant',
                                            'interdiction, prohibition, proscription'),
                                    TestWay('n',
                                            '自由',
                                            'the right to act or move freely',
                                            ["Military commanders on the ground must be granted considerable license, as wars cannot be micromanaged by people back in Washington. 战地指挥官应该被赋予相当大的自由, 因为一场战争只靠华盛顿的人是不可能打赢的。"],
                                            'freedom, latitude, liberty',
                                            'confinement, custody, imprisonment'),
                                    TestWay('n',
                                            '放荡',
                                            'disregard for standards of personal conduct',
                                            ["a night of drinking and license at the nightclub 夜店里放纵饮酒取乐的一夜"],
                                            'debauchery, hedonism, libertinage, libertinism, licentiousness, profligacy, voluptuousness',
                                            'abstinence, asceticism, sobriety, temperance'),
                                    TestWay('vt',
                                            '准许, 授权使用',
                                            'to permit or authorize especially by formal license',
                                            ["A state statute licenses county sheriffs to choose their own deputies. 法律允许郡上的司法长官选择自己的副手。", "licensed to use deadly force 获准使用致命火力"],
                                            'accredit, certify, commission, empower, enable, invest, qualify, vest, warrant',
                                            'disqualify, forbid, interdict, prohibit, proscribe, veto')]),
                              Word('ludicrous', "",
                                   [TestWay('adj',
                                            '荒唐的, 可笑的',
                                            'meriting derisive laughter or scorn as absurdly inept, false, or foolish',
                                            ["He made a ludicrous and easily detected attempt to forge his father’s signature on a note to school. 他试图在要上交学校的纸条上伪造父亲的签名, 这实在是既可笑又容易被发现的花招。"],
                                            'absurd, comical, derisive, derisory, farcical, laughable, ridiculous, pathetic, preposterous, risible, silly',
                                            'logical, rational, reasonable, sensible')]),
                              Word('luminous', "",
                                   [TestWay('adj',
                                            '发光的, 有光泽的',
                                            'emitting or reflecting usually steady, suffused, or glowing light',
                                            ["The luminous moon bathed the snow-covered fields with a pearly glow. 在明亮的月光下, 雪地仿佛被罩上了一层珍珠般的光晕。"],
                                            'beaming, bright, candescent, dazzling, effulgent, glowing, incandescent, lambent, lucent, lucid, lustrous, radiant, refulgent, shiny, splendid',
                                            'dim, dull, lackluster'),
                                    TestWay('adj',
                                            '杰出的, 重要的',
                                            'standing above others in rank, importance, or achievement',
                                            ["some of the most luminous writers in the nation’s history 该国历史上最杰出的一批作家"],
                                            'astral, brilliant, distinguished, illustrious, notable, noteworthy, preeminent, prestigious, redoubtable, signal',
                                            'average, inferior, mediocre',
                                            'luminosity n. 发光; 亮度')]),
                              Word('malevolent', "",
                                   [TestWay('adj',
                                            '恶意的, 恶毒的',
                                            'having, showing, or arising from intense often vicious ill will, spite, or hatred',
                                            ["The novel grossly oversimplified the conflict as a struggle between relentlessly malevolent villains on one side and faultless saints on the other. 小说把这场斗争彻底简化成凶残恶毒的坏人和完美无暇的圣人间的纠纷。"],
                                            'cruel, despiteful, evil, malicious, malign, malignant, mean, nasty, spiteful, vicious, virulent',
                                            'benevolent, benign, benignant',
                                            'malevolence n. 恶意, 恶毒')]),
                              Word('meditate', "",
                                   [TestWay('vt',
                                            '思索, 沉思',
                                            'to focus one’s thoughts on',
                                            ["meditated a visit to her professor 思索着去拜访她的导师", "I have been meditating a career change for months. 我花了几个月的时间在考虑换一个工作。"],
                                            'cogitate, consider, contemplate, deliberate, mull, perpend, ponder, ruminate, study, weigh, wrestle',
                                            'disregard, ignore, overlook, slight',
                                            'meditation n. 沉思')]),
                              Word('meretricious', "",
                                   [TestWay('adj',
                                            '艳俗的, 俗气的',
                                            'attracting attention in a vulgar manner',
                                            ["The paradise they found was no more than a meretricious wasteland of casinos and bars. 他们所发现的所谓“天堂”只不过是一块有着赌场和酒吧的俗气不堪的荒漠罢了。"],
                                            'flamboyant, flaring, flashy, garish, gaudy, glaring, loud, ostentatious, tawdry',
                                            'conservative, quiet, understated, unflamboyant')])])

list31_unit3 = VocabularyList([Word('milieu', "",
                                   [TestWay('n',
                                            '环境, 氛围',
                                            'the physical or social setting in which something occurs or develops',
                                            ["Young, innovative artists thrive in the freewheeling milieu that a big city offers. 在那个大都市所提供的自由氛围中, 年轻而富有创造力的艺术家们的事业蓬勃发展。", "ahistorical milieu conducive to democracy 有助于民主制度的历史背景"],
                                            'ambient, atmosphere, climate, context, environment, environs, medium, setting, surroundings, terrain')]),
                              Word('military', "",
                                   [TestWay('adj',
                                            '军事的, 军用的',
                                            'of or relating to soldiers, arms, or war',
                                            ["NATO struggles with how to proceed military operation against Libya. 北约就如何延续针对利比亚的军事行动出现了内部分歧。", "an encyclopedia of modern military aircraft 现代军用飞行器百科全书"],
                                            'martial, service',
                                            'civilian')]),
                              Word('nostalgia', "",
                                   [TestWay('n',
                                            '思乡之情',
                                            'the state of being homesick',
                                            ["Overwhelmed by nostalgia, she started to cry. 被思乡之情淹没的她开始啜泣。"],
                                            'homesickness'),
                                    TestWay('n',
                                            '怀旧, 怀念',
                                            'a wistful or excessively sentimental yearning for return to or of some past period or irrecoverable condition',
                                            ["He felt a wave of nostalgia for the life he had left behind him. 他开始怀念往昔的时光。"],
                                            'reminiscence',
                                            'oblivion',
                                            'nostalgic adj. 怀旧的')]),
                              Word('numb', "",
                                   [TestWay('adj',
                                            '失去感觉的',
                                            'devoid of sensation especially as a result of cold or anesthesia',
                                            ["I have been sitting in the same position for too long and now my feet are numb. 我一个姿势坐得太久, 以至于双腿都发麻了。"],
                                            'asleep, benumbed, dead, insensitive, numbed, torpid, unfeeling',
                                            'feeling, sensible, sensitive'),
                                    TestWay('adj',
                                            '麻木的, 无感情的',
                                            'devoid of emotion',
                                            ["Apparently in shock, he answered the police officer’s questions with a numb expression on his face. 她显然是受到了惊吓, 以至于在回答警官的问题时一脸茫然。", "Years of physical and emotional abuse had rendered the woman numb and withdrawn. 常年累月的肉体和精神上的折磨已让她麻木而寡言。"],
                                            'affectless, apathetic, catatonic, deadpan, emotionless, impassible, passionless, phlegmatic, stoic, stolid',
                                            'demonstrative, emotional, fervent, fervid, impassioned, passionate, vehement')]),
                              Word('ordeal', "",
                                   [TestWay('n',
                                            '严峻的考验',
                                            'a severe trial or experience',
                                            ["The hikers were finally rescued after a three-day ordeal in the wilderness. 在野外度过了三天的严峻考验之后, 登山者终于获救了。"],
                                            'calvary, crucible, fire, gauntlet',
                                            'delight, enjoyment, pleasure')]),
                              Word('ostensible', "",
                                   [TestWay('adj',
                                            '表面上的, 佯装的',
                                            'appearing to be true on the basis of evidence that may or may not be confirmed',
                                            ["It must be the ostensible reason for their visit while their actual motives may be malignant 这肯定只是他们上门拜访的表面原因, 他们背后的动机说不定恶劣至极。"],
                                            'apparent, assumed, evident, ostensive, presumed, putative, reputed, seeming, supposed, prima facie',
                                            'actual, real',
                                            'ostensibly adv. 表面上地')]),
                              Word('outgrowth', "",
                                   [TestWay('n',
                                            '结果, 后果',
                                            'a condition or occurrence traceable to a cause',
                                            ["Crime is often an outgrowth of poverty. 犯罪往往可以归因于贫穷。", "A predictable outgrowth of the suburb’s ever growing population will be the need for more schools. 郊区人口攀升所导致的一个可以预见的后果就是需要更多的学校。"],
                                            'aftereffect, aftermath, consequence, fate, fruit, outcome, precipitate, product, result, sequel, sequence',
                                            'antecedent, cause, occasion, reason, origin, root, source')]),
                              Word('outmoded', "",
                                   [TestWay('adj',
                                            '过时的, 废弃的',
                                            'no longer acceptable, current, or usable',
                                            ["outmoded computers that can be recycled 可供回收的废旧电脑"],
                                            'antiquated, archaic, demoded, fossilized, moribund, moth-eaten, obsolete, outworn, prehistoric , rusty',
                                            'contemporary, current, modern')]),
                              Word('override', "",
                                   [TestWay('vt',
                                            '不顾',
                                            'to set aside',
                                            ["The Congress overrode the President’s veto and passed the law. 国会不顾总统的否决, 强行通过了那项法令。", "He overrode all opposition to his plans. 他对所有的反对意见不闻不问。"],
                                            'disregard, ignore, neglect, overlook, overpass, pass over',
                                            'comply, observe')]),
                              Word('overwhelm', "",
                                   [TestWay('vt',
                                            '淹没',
                                            'to cover with or as if with a flood',
                                            ["That spring the massive runoff from melting snows overwhelmed the valley. 那个春天, 整个村庄被融雪形成的洪流吞没了。"],
                                            'deluge, drown, engulf, inundate, overflow, submerge, submerse, swamp',
                                            'drain'),
                                    TestWay('vt',
                                            '(感情上、精神上)使无所适从, 使难以承受',
                                            'to subject to incapacitating emotional or mental stress',
                                            ["Just the thought of how much work there is to do overwhelms me. 仅仅是想想还有多少工作没完成就几乎让我喘不过气了。"],
                                            'devastate, oppress, overcome, overmaster, overpower, prostrate, whelm',
                                            'relieve',
                                            'overwhelming adj. 势不可挡的, 无法抗拒的')])])

list31_unit4 = VocabularyList([Word('panacea', "",
                                   [TestWay('n',
                                            '万能药, 万灵药',
                                            'a remedy for all ills or difficulties',
                                            ["a woman who seems to believe that chicken soup is a panacea for nearly everything 一个相信鸡汤是万能灵药的妇女", "Bicycles are not a panacea for the traffic problem. 自行车并不是解决交通问题的万能药。"],
                                            'catholicon, cure-all, elixir, nostrum')]),
                              Word('perquisite', "",
                                   [TestWay('n',
                                            '额外的好处',
                                            'something given in addition to what is ordinarily expected or owed',
                                            ["give the movers a perquisite if they do a good job 如果搬家工人做得好就会获得一定的小费", "The use of a company car is one perquisite of the job. 能使用公司的汽车是这项工作的附加好处之一。"],
                                            'cumshaw, dividend, donative, extra, gratuity, gravy, lagniappe, perk, tip')]),
                              Word('petulant', "",
                                   [TestWay('adj',
                                            '易怒的, 爱发脾气的',
                                            'easily irritated or annoyed',
                                            ["He is a petulant and fussy man who is always blaming everyone else for his problems. 他是一个对细节非常在意而又容易生气的人, 还总是把自己的问题怪罪到别人的头上。"],
                                            'choleric, grouchy, grumpy, irascible, irritable, peevish, perverse, pettish, prickly, raspy, ratty, stuffy, testy',
                                            'forbearing, obliging, patient, stoic , tolerant',
                                            'petulance n. 易怒, 坏脾气')]),
                              Word('pitfall', "",
                                   [TestWay('n',
                                            '陷阱',
                                            'a pit flimsily covered or camouflaged and used to capture and hold animals or men',
                                            ["caught in a pitfall 掉下了陷阱", "Renting a house can be full of pitfalls for the unwary. 对于那些不注意的人来说租房也是危机四伏的。"],
                                            'catch, gimmick, gotcha, hitch, joker, snag, snare, trap'),
                                    TestWay('n',
                                            '(不易察觉的)危害',
                                            'a hidden or not easily recognized danger or difficulty',
                                            ["One of the pitfalls of ignorance is that people will also assume you are stupid. 无知的一个危害就是, 人们总会假设你一无所知。"],
                                            'hazard, imminence, menace, peril, risk, threat, trouble')]),
                              Word('placid', "",
                                   [TestWay('adj',
                                            '宁静的, 风平浪静的',
                                            'free from storms or physical disturbance',
                                            ["a vacation in the placid lake community 在宁静的湖区度过的假日"],
                                            'calm, halcyon, hushed, peaceful, quiet, serene, still, stilly, tranquil, untroubled',
                                            'boisterous, clamorous, noisy, raucous, roistering, rowdy, tumultuous, uproarious'),
                                    TestWay('adj',
                                            '冷静的, 淡定的',
                                            'free from emotional or mental agitation',
                                            ["I know an exceptionally placid mother who was rarely upset by her six children 我认识一个异常淡定的母亲, 她几乎从未因为自己的六个孩子而烦恼过。"],
                                            'collected, composed, coolheaded, level, limpid, possessed, recollected, sedate, undisturbed, unperturbed',
                                            'agitated, discomposed, disturbed, flustered, perturbed, upset',
                                            'placidity n.宁静, 安宁')]),
                              Word('playful', "",
                                   [TestWay('adj',
                                            '爱开玩笑的, 好打闹的',
                                            'given to good-natured joking or teasing',
                                            ["The little girl was lighthearted and playful. 小女孩性格很轻松愉快, 喜欢和别人打闹。"],
                                            'antic, coltish, elfish, fay, frisky, frolicsome, larky, rollicking, sportive',
                                            'earnest, grave, serious, sober, solemn, somber')]),
                              Word('prerequisite', "",
                                   [TestWay('n',
                                            '先决条件, 前提',
                                            'something that is necessary to an end or to the carrying out of a function',
                                            ["Competence is prerequisite to promotion. 能力是􁨀升的必要条件。", "I don’t think a large dwelling place is a prerequisite for a happy life. 我并不认为大的住所就能带来幸福的生活。"],
                                            'condition, essential, must, necessity, precondition, requirement, requisite, sine qua non')]),
                              Word('prerogative', "",
                                   [TestWay('n',
                                            '特权, 权力',
                                            'an exclusive or special right, power, or privilege',
                                            ["It is your prerogative to refuse to attend religious services. 你有权力不参加宗教活动。"],
                                            'appanage, birthright, entitlement, privilege, right')]),
                              Word('proclaim', "",
                                   [TestWay('vt',
                                            '宣告, 使…公之于众',
                                            'to declare publicly, typically insistently, proudly, or defiantly and in either speech or writing',
                                            ["wearing a button that proclaimed my choice for president 身上挂着一个纽扣, 它能够彰显我支持谁当总统", "He launched a coup and proclaimed himself president. 他发动了一场政变, 然后宣称自己已成为总统。"],
                                            'advertise, announce, blare, blazon, broadcast, declare, enunciate, herald, promulgate, publicize, publish, release, trumpet',
                                            'conceal, hide, silence, suppress')]),
                              Word('project', "",
                                   [TestWay('n',
                                            '方案, 计划',
                                            'a specific plan or design',
                                            ["an ambitious project to develop the city’s underground transport 一项开发城市地下交通系统的雄心勃勃的计划"],
                                            'arrangement, blueprint, design, plan, program, scheme, strategy, system, road map'),
                                    TestWay('vi',
                                            '凸出',
                                            'to extend outward beyond a usual point',
                                            ["Some boulders projected dangerously out above the trail. 一些巨石非常危险地在道路上凸了出来。"],
                                            'balloon, beetle, billow, bunch, jut, overhang, poke, pouch, pout, protrude, swell'),
                                    TestWay('vt',
                                            '预测, 预计',
                                            'to calculate, estimate, or predict (something in the future), based on present data or trends',
                                            ["projecting next year’s expenses"],
                                            'augur, estimate, extrapolate, forecast, predict, predetermine, presage',
                                            other_form = 'projected adj. 计划的; projection n. 凸起物; 投影')])])

list31_unit5 = VocabularyList([Word('proprietary', "",
                                   [TestWay('n',
                                            '所有权',
                                            'ownership',
                                            synonyms = 'dominion, ownership, possession, property, proprietorship'),
                                    TestWay('adj',
                                            '私营的',
                                            'privately owned and managed and run as a profit-making organization',
                                            ["a proprietary hospital 私人医院"],
                                            'private',
                                            'public, state-owned')]),
                              Word('prototype', "",
                                   [TestWay('n',
                                            '原型',
                                            'an original model on which something is patterned',
                                            ["The manufacturer exhaustively tested the prototype of the vehicle before approving production. 生产商在将该车型投入生产之前对其原型进行了详细的测试。"],
                                            'archetype',
                                            'copy, imitation, replica, reproduction')]),
                              Word('redeem', "",
                                   [TestWay('vt',
                                            '实践, 履行(诺言等)',
                                            'to do what is required by the terms of',
                                            ["The coach redeemed his promise to take the players out for ice cream if they improved their fielding over the season. 教练履行了他的诺言, 那就是如果球员们能够在赛季中提升防守能力的话, 他就请他们吃冰淇淋。"],
                                            'answer, complete, comply, fill, fulfill, keep, meet, satisfy',
                                            'breach, break, transgress, violate'),
                                    TestWay('vt',
                                            '改过自新',
                                            'to make better in behavior or character',
                                            ["The unfaithful husband made a determined effort to redeem himself in the eyes of his wife and children. 在妻子和孩子的监督下, 不忠的丈夫下定决心要改过自新。"],
                                            'habilitate, reclaim, redeem, regenerate, rehabilitate',
                                            other_form = 'redeemable adj. 可赎回的, 可挽救的')]),
                              Word('replicate', "",
                                   [TestWay('vt',
                                            '复制, 复刻',
                                            'to make an exact likeness of',
                                            ["replicated the famous painting in our art class 在艺术课上复刻一幅名画"],
                                            'clone, copy, copycat, duplicate, imitate, reduplicate, render, reproduce',
                                            'originate'),
                                    TestWay('vt',
                                            '重复, 反复',
                                            'to make or do again',
                                            ["I cannot replicate your results when I do the experiment myself. 我自己的实验里无法重复你的结果。"],
                                            'redo, reiterate, renew, repeat',
                                            other_form = 'replicable adj. 可复制的, 能复现的')]),
                              Word('restitution', "",
                                   [TestWay('n',
                                            '补偿, 赔偿',
                                            'a making good of or giving an equivalent for some injury',
                                            ["The victims are demanding full restitution. 受害者要求全额补偿。"],
                                            'damages, indemnity, quittance, recompense, recoupment, redress, remuneration, reparation, reprisal, resurrectrequital')]),
                              Word('resurrect', "",
                                   [TestWay('vt',
                                            '使重生, 使复苏',
                                            'to bring back to life, practice, or activity',
                                            ["believed that his body would be resurrected 相信他的身体将会复活", "Attempts are being made by both parties to resurrect the stalled arms negotiations. 双方正在努力重启受阻的武装谈判。"],
                                            'reanimate, recharge, regenerate, rejuvenate, rekindle, renew, resuscitate, revitalize, revive, revivify',
                                            'kill',
                                            'resurrection n. 重生, 复苏')]),
                              Word('retrieve', "",
                                   [TestWay('vt',
                                            '寻回, 找回',
                                            'to get back again',
                                            ["I needed to retrieve the book from my friend so I could return it to the library. 我需要先把书从朋友那里拿回来才能还给图书馆。"],
                                            'reacquire, recapture, reclaim, re-collect, recoup, recover, regain, repossess, retake',
                                            'lose, mislay, misplace')]),
                              Word('reverberate', "",
                                   [TestWay('vi',
                                            '回荡, 回响',
                                            'to continue or be repeated in a series of reflected sound waves',
                                            ["The sound of thunder reverberated from one end of the mountain pass to the other. 打雷的声音在山间不断回荡。"],
                                            'echo, reecho, resonate, resound',
                                            other_form = 'reverberation n. 回响, 回音')]),
                              Word('ruthless', "",
                                   [TestWay('adj',
                                            '没有怜悯心的, 残忍的',
                                            'having no pity',
                                            ["an office supervisor with a ruthless disregard for others' feelings 一个从不顾及他人感情的无情领导"],
                                            'cruel, heartless, inhumane, ironfisted, iron-hearted, pitiless, merciless, mortal, relentless, remorseless',
                                            'charitable, compassionate, humane, kindhearted, merciful, sympathetic, tender')]),
                              Word('scourge', "",
                                   [TestWay('n',
                                            '祸害',
                                            'a source of harm or misfortune',
                                            ["The sheer ubiquity of food seems to be the scourge of humanity, as evidenced by the obesity epidemic. 无所不在的食品似乎要成为人类的罪恶之源了, 这一点可以从肥胖病的泛滥得以佐证。"],
                                            'affliction, bane, curse, nemesis',
                                            'benefit, blessing, boon, felicity, godsend, manna, windfall')])])

list31_unit6 = VocabularyList([Word('scruple', "",
                                   [TestWay('n',
                                            '(良心上的)不安',
                                            'an uneasy feeling about the rightness of what one is doing or going to do',
                                            ["The survey showed that many students had few scruples about cheating on papers or exams. 调查显示很多学生对于在考试时作弊没有丝毫的愧疚。"],
                                            'compunction, misgiving',
                                            'assurance, certainty, certitude, confidence, conviction, sureness')]),
                              Word('sectarianism', "",
                                   [TestWay('n',
                                            '宗派主义, 顽固',
                                            "stubborn or intolerant adherence to one's opinions or prejudices",
                                            ["An ideological sectarianism prevented the political party from ever being anything more than a fringe group. 意识形态上的顽固和保守使得这个政党只能成为一个边缘团体。"],
                                            'dogmatism, illiberalism, intolerance, narrow-mindedness, partisanship, small-mindedness',
                                            'broad-mindedness, liberalism, open-mindedness, tolerance')]),
                              Word('secular', "",
                                   [TestWay('adj',
                                            '世俗的, 尘世的',
                                            'of or relating to the worldly or temporal',
                                            ["That’s an issue for the secular authorities, not the church. 这个问题和宗教无关, 是一个世俗事务。"],
                                            'carnal, earthborn, earthbound, fleshly, material, mundane, sublunary, temporal, terrene, terrestrial, worldly',
                                            'heavenly, unearthly, unworldly, spiritual, religious')]),
                              Word('sparing', "",
                                   [TestWay('adj',
                                            '节俭的, 节约的',
                                            'marked by or practicing careful restraint (as in the use of resources)',
                                            ["The sparing couple are trying to save up enough for a house. 节俭的夫妻希望能够攒钱买套房。"],
                                            'economical, economizing, provident, scrimping, thrifty',
                                            'prodigal, profligate, spendthrift, squandering, wasteful'),
                                    TestWay('adj',
                                            '不足的, 缺乏的',
                                            'less plentiful than what is normal, necessary, or desirable',
                                            ["Unfortunately, the explanation of the health insurance plan was somewhat sparing on details. 不幸的是, 健康保险上的说明似乎不够详细。", "The map is sparing of information. 这张地图的信息量太少了。"],
                                            'exiguous, niggardly, poor, scant, scanty, scarce, skimp, skimpy, slender, slim, spare, sparse, stingy',
                                            'abundant, ample, bountiful, copious, generous, liberal, plenteous, plentiful')]),
                              Word('stereotype', "",
                                   [TestWay('n',
                                            '成见, 老套的理念',
                                            'a conventional, formulaic, and oversimplified conception, opinion, or image',
                                            ["The noble savage was a stereotype that appealed to 18th-century intellectuals, who viewed European civilization as decadent and corrupt. “高贵的野蛮人”这一概念是为了迎合十八世纪的文人而提出的, 他们将欧洲视作一支正在堕落和腐化的文明。"],
                                            'concept, conception, generality, notion')]),
                              Word('substitute', "",
                                   [TestWay('n',
                                            '取代者, 替代品',
                                            'a person or thing that takes the place or function of another',
                                            ["If you like, you can use nuts as a substitute for coconut in that recipe. 如果您不反对, 我们可以将菜单里的椰子换成坚果。"],
                                            'backup, cover, fill-in, relief, replacement, reserve, stand-in, surrogate'),
                                    TestWay('vt',
                                            '取代, 替代',
                                            'to take the place of',
                                            ["substituting moral power for physical force 将暴力用道德的力量代替", "BFR molecules have some atoms substituted by bromide atoms, which makes it fire-resistant. 在溴化阻燃剂的分子中, 一部分原子被溴原子取代, 从而使它不易燃烧。"],
                                            'displace, relieve, replace, supersede, supplant, cut out',
                                            other_form = 'substitution n. 取代')]),
                              Word('succumb', "",
                                   [TestWay('vi',
                                            '屈服',
                                            'to yield to superior strength or force or overpowering appeal or desire',
                                            ["refused to succumb to her fears and defiantly walked through the dark cemetery 拒绝向自己的恐惧屈服, 而是倔强地走过了幽暗的墓地"],
                                            'bow, capitulate, concede, submit, surrender, give in',
                                            'resist'),
                                    TestWay('vi',
                                            '死亡',
                                            'to be brought to an end (as death) by the effect of destructive or disruptive forces',
                                            ["The patient lay so still and pale that everyone thought he had succumbed, and then he opened his eyes. 面色惨白的病人静静地躺在床上, 正当所有人都怀疑他已经过逝时, 他突然睁开了眼睛。", "The doctor worked tirelessly until finally he, too, succumbed to the plague. 医生不知劳累地工作, 直至最后, 他也死于瘟疫。"],
                                            'decease, demise, expire, perish, pass away',
                                            'endure, stand, breathe, live, survive')]),
                              Word('supersede', "",
                                   [TestWay('vt',
                                            '取代, 替代',
                                            'to displace in favor of another',
                                            ["That edition of the dictionary that you have has been superseded by a more recent one. 你买的那一版的字典已经被最近新出的版本取代了。"],
                                            'displace, relieve, replace, substitute, supplant, cut out')]),
                              Word('surly', "",
                                   [TestWay('adj',
                                            '脾气不好的',
                                            'irritably sullen and churlish in mood or manner',
                                            ["The surly receptionist told us we would have to wait outside in the rain. 态度粗暴的服务员说我们必须在外面等——哪怕是在下雨。"],
                                            'acid, bearish, bilious, cantankerous, disagreeable, dyspeptic, ill-humored, ill-natured, ornery, splenetic',
                                            'amiable, good-humored, good-natured, good-tempered')]),
                              Word('surmise', "",
                                   [TestWay('n',
                                            '(根据不足的)推测, 揣测',
                                            'a thought or idea based on scanty evidence',
                                            ["My surmise is that the couple’s “good news” is the announcement that they are going to have a baby. 我猜那对夫妻说的“好消息”就是他们要有小孩了。"],
                                            'guess, hypothesis, shot, supposition, theory',
                                            'fact'),
                                    TestWay('vt',
                                            '推测',
                                            'to form a notion of from scanty evidence',
                                            ["From his tone I surmised that he was unhappy. 从他的语气中我猜测他并不高兴。"],
                                            'assume, conjecture, daresay, imagine, infer, presume, speculate, suppose, suspect',
                                            'demonstrate, prove, substantiate, validate')])])

list31_unit7 = VocabularyList([Word('surmount', "",
                                   [TestWay('vt',
                                            '战胜, 获得胜利',
                                            'to achieve a victory over',
                                            ["an Olympic swimmer who surmounted endless obstacles to achieve her goals 一个克服重重困难最终实现目标的奥运游泳运动员"],
                                            'conquer, defeat, overbear, overcome, overmatch, prevail, subdue, triumph, win',
                                            'lose')]),
                              Word('surrogate', "",
                                   [TestWay('n',
                                            '替代品',
                                            'one that takes the place of another',
                                            ["For some people, Google Earth is never a justified surrogate for actual travel. 对于一部分人而言, 谷歌地球决不是旅行的合理替代品。"],
                                            'backup, cover, fill-in, relief, replacement, reserve, stand-in, substitute')]),
                              Word('tame', "",
                                   [TestWay('adj',
                                            '被驯化的',
                                            'reduced from a state of native wildness especially so as to be tractable and useful to humans',
                                            ["Every evening, a wild Canada goose is at the food trough with our tame geese. 每天傍晚的食槽边总会出现一只野生加拿大鹅和我们的饲养家鹅一起进食。"],
                                            'domestic, domesticated, tamed',
                                            'feral, savage, undomesticated, untamed, wild'),
                                    TestWay('adj',
                                            '无聊的, 乏味的',
                                            'lacking spirit, zest, interest, or the capacity to excite',
                                            ["That action movie was so tame I fell asleep about 20 minutes into it. 那部动作片实在是太无聊了, 我刚开场二十分钟就睡着了。"],
                                            'arid, drab, dreary, drudging, humdrum, insipid, jading, jejune, monochromatic, monotonous, pedestrian, ponderous, stale, stodgy, tedious, tiresome, wearisome',
                                            'absorbing, engaging, engrossing, gripping, interesting, intriguing, involving, riveting'),
                                    TestWay('vt',
                                            '控制, 抑制',
                                            'to keep from exceeding a desirable degree or level (as of expression)',
                                            ["Try to tame your language when you are in front of the kids. 在孩子面前注意一下你的措辞。"],
                                            'bridle, check, constrain, contain, curb, govern, hold, inhibit, keep, measure, regulate, rein, restrain, rule',
                                            'unleash')]),
                              Word('tangle', "",
                                   [TestWay('n',
                                            '困惑, 不解',
                                            'a state of perplexity or complete bewilderment',
                                            ["My mind has been in a tangle ever since I learned some information about an old, deceased acquaintance. 自从我获知一些关于已故的老熟人的消息之后我就陷入了困惑之中。"],
                                            'bafflement, befuddlement, bemusement, bewilderment, confusedness, distraction, muddle, mystification, perplexity, puzzlement, whirl',
                                            'assurance, certainty, certitude, confidence, conviction, sureness'),
                                    TestWay('vt',
                                            '纠缠, 使…纠结',
                                            'to seize and hold in or as if in a snare',
                                            ["was at last tangled in the web of lies that he had told to everyone 最终被自己所编织的谎言缠住了"],
                                            'enmesh, ensnare, ensnarl, entrap, mesh, net, snare, trap',
                                            'disentangle')]),
                              Word('teeming', "",
                                   [TestWay('adj',
                                            '大量的',
                                            'possessing or covered with great numbers or amounts of something specified',
                                            ["oceans teeming with life 孕育着无穷生命的海洋"],
                                            'abundant, ample, awash, cornucopian, flush, fraught, lousy, replete, swarming, thick, thronging',
                                            'bare, barren, blank, devoid, empty, stark, vacant, void')]),
                              Word('temporal', "",
                                   [TestWay('adj',
                                            '世俗的, 尘世的',
                                            'of or relating to earthly life',
                                            ["The master told his disciples not to worry about temporal concerns, but instead focus on spiritual matters. 大师要弟子们不要为尘世间的纷争而苦恼, 而是将精神集中于灵魂上的思考。"],
                                            'carnal, earthborn, earthbound, fleshly, material, mundane, secular, sublunary, terrene, terrestrial, worldly',
                                            'heavenly, unearthly, unworldly, spiritual, religious')]),
                              Word('tentative', "",
                                   [TestWay('adj.',
                                            '暂时性的, 尝试的',
                                            'not fully worked out or developed',
                                            ["Our plans are only tentative at this point and will depend on whether you can come. 我们的计划只是暂时性的, 具体还要看你能否前来。"],
                                            'ad interim, impermanent, interim, provisional, provisionary, provisory, short-term, temporary, trial',
                                            'final, ceaseless, endless, eternal, immortal, permanent, perpetual, undying')]),
                              Word('tyrant', "",
                                   [TestWay('n',
                                            '暴君',
                                            'a ruler who exercises absolute power oppressively or brutally',
                                            ["The people universally feared the tyrant, who was notorious for his frequent use of torture. 人们非常恐惧这个暴君, 因为他有着经常折磨犯人的臭名。"],
                                            'dictator, oppressor, pharaoh, strongman',
                                            other_form = 'tyranny n. 暴政, 苛政')]),
                              Word('unanimous', "",
                                   [TestWay('adj',
                                            '一致同意的',
                                            'having the agreement and consent of all',
                                            ["a unanimous vote to upgrade the school’s computer facilities 一致同意对学校的计算机设备进行升级"],
                                            'consentaneous, uncontested',
                                            other_form = 'unanimity n. 一致同意')]),
                              Word('unremitting', "",
                                   [TestWay('adj',
                                            '连续不断的',
                                            'going on and on without any interruptions',
                                            ["Unremitting rain lasted for six days. 连续下了六天的雨。"],
                                            'ceaseless, continual, continuing, incessant, nonstop, perpetual, unbroken, uninterrupted',
                                            'discontinuous, intermittent')])])

list31_unit8 = VocabularyList([Word('versed', "",
                                   [TestWay('adj',
                                            '熟知的',
                                            'having information especially as a result of study or experience',
                                            ["versed in the latest developments in aeronautics 熟知当今航空业的发展情况"],
                                            'abreast, acquainted, conversant, informed, knowledgeable, well-informed',
                                            'ignorant, unacquainted, unfamiliar, uninformed, unknowledgeable'),
                                    TestWay('adj',
                                            '精通的',
                                            'having or showing exceptional knowledge, experience, or skill in a field of endeavor',
                                            ["well versed in the techniques of laser surgery 精通激光手术方面的技术"],
                                            'accomplished, adept, complete, consummate, experienced, expert, master, practiced, professed, skilled, veteran, virtuoso',
                                            'amateur, inexperienced, inexpert, jackleg, unprofessional, unseasoned, unskilled')]),
                              Word('vocation', "",
                                   [TestWay('n',
                                            '职业',
                                            'the work in which a person is regularly employed',
                                            ["finally made soccer her vocation instead of just a hobby 终于将足球从爱好升级为谋生的职业"],
                                            'calling, employment, occupation, profession, trade, work',
                                            'hobby',
                                            'vocational adj. 职业的, 为职业做准备的')]),
                              Word('voyeur', "",
                                   [TestWay('n',
                                            '淫窥狂',
                                            'one obtaining sexual gratification from observing unsuspecting individuals who are partly undressed, naked, or engaged in sexual acts',
                                            ["They accidentally found out that their ostensibly benign neighbor is actually a voyeur. 他们偶然间发现那个表面和善的邻居居然是一个偷窥狂。"],
                                            'peeper',
                                            other_form = 'voyeurism n. 偷窥癖')]),
                              Word('willful', "",
                                   [TestWay('adj',
                                            '固执的, 倔强的',
                                            'obstinately and often perversely self-willed',
                                            ["Finally the parents sought professional counseling for the willful child. 最终家长不得不为倔强的小孩寻求专业咨询。"],
                                            'adamant, headstrong, immovable, implacable, inconvincible, inflexible, intransigent, mulish, obdurate, pertinacious, perverse, stubborn, unyielding, wrongheaded',
                                            'acquiescent, agreeable, amenable, compliant, flexible, pliable, pliant, relenting, yielding'),
                                    TestWay('adj',
                                            '故意的',
                                            'done deliberately',
                                            ["a willful attempt to cheat her siblings out of their rightful inheritance 一个想将继承权从她的姊妹手里骗过来的故意企图"],
                                            'conscious, deliberate, intended, intentional, knowing, purposeful, voluntary, willed, witting',
                                            'accidental, chance, haphazard, inadvertent, incidental, random')]),
                              Word('wistful', "",
                                   [TestWay('adj',
                                            '(带着忧伤而)渴望的, 怀念的',
                                            'full of yearning or desire tinged with melancholy',
                                            ["There was a wistful look in his eyes when he spoke of his childhood. 当他谈起他的童年时, 眼眶中不禁流露出一种带有忧伤的怀念之情。"],
                                            'longing, nostalgic, reminiscent, yearning',
                                            'apathetic, indifferent, insouciant, nonchalant, perfunctory, unconcerned')]),
                              Word('wrongheaded', "",
                                   [TestWay('adj',
                                            '固执己见的, 坚持(错误观点)的',
                                            'stubborn in adherence to wrong opinion or principles',
                                            ["In spite of other’s objections, he is always wrongheaded in his opinions. 他总是不管他人的反对而坚持自己哪怕是错误的观点。"],
                                            'adamant, headstrong, immovable, implacable, inconvincible, inflexible, intransigent, mulish, obdurate, pertinacious, perverse, stubborn, unyielding, willful',
                                            'acquiescent, agreeable, amenable, compliant, flexible, pliable, pliant')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')])])

list31_unit9 = VocabularyList([Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')])])

list31_unit10 = VocabularyList([Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')])])

LIST31 = VocabularyList(list31_unit1.words+list31_unit2.words+list31_unit3.words+list31_unit4.words+list31_unit5.words+list31_unit6.words+list31_unit7.words+list31_unit8.words+list31_unit9.words+list31_unit10.words)
