#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list18_unit1 = VocabularyList([Word('patrician', "",
                                   [TestWay('n',
                                            '贵族, 名门望族',
                                            'a man or woman of high birth or social position',
                                            ["the rank of a patrician 贵族等级"],
                                            'aristocrat, noble, blue blood',
                                            'plebeian'),
                                    TestWay('adj',
                                            '贵族的, 地位高的',
                                            'of high birth, rank, or station',
                                            ["came from a patrician family 出身贵族世家"],
                                            'aristocratic, genteel, gentle, grand, great, highborn, highbred, upper-class, wellborn',
                                            'baseborn, common, humble, ignoble, low, lower-class, mean')]),
                              Word('patriot', "",
                                   [TestWay('n',
                                            '爱国者',
                                            'one who loves his or her country and supports its authority and interests',
                                            ["The USA PATRIOT Act has generated a great deal of controversy since its enactment. 自实施之日起, 美国的《爱国者法案》就产生了大量的争议", "a fanatical patriot 狂热的爱国者"],
                                            'loyalist, nationalist, partisan',
                                            'apostate, recreant, renegade, traitor, turncoat 叛徒; insurgent, mutineer, rebel',
                                            'patriotism n. 爱国主义')]),
                              Word('patronize', "",
                                   [TestWay('vt',
                                            '赞助',
                                            'provide aid or support for',
                                            ["a company that loyally patronizes the arts 一个一直以来坚持赞助艺术界的公司"],
                                            'advocate, back, champion, endorse, support, uphold',
                                            'baffle, foil, frustrate, sabotage'),
                                    TestWay('v',
                                            '以高人一等的态度对待',
                                            'to adopt an air of condescension toward: treat haughtily or coolly',
                                            ["a director with an unpleasant habit of patronizing even his most gifted actors 一个有着令人讨厌习惯的导演, 他即便是对手下最有才华的演员也傲慢地对待"],
                                            'condescend',
                                            other_form = 'patron n. 赞助人')]),
                              Word('paucity', "",
                                   [TestWay('n',
                                            '少量, 缺乏',
                                            'smallness of number; dearth',
                                            ["an extreme paucity of natural resources 极度缺乏自然资源"],
                                            'dearth, deficit, drought, inadequacy, insufficiency, lack, scantiness, scarcity, shortage, undersupply, want',
                                            'abundance, adequacy, amplitude, opulence, plenitude, sufficiency, wealth')]),
                              Word('paunchy', "",
                                   [TestWay('adj',
                                            '大腹便便, 大肚子的',
                                            'having a potbelly',
                                            ["a paunchy middle-aged man 一个大腹便便的中年男子"],
                                            'corpulent, fat, potbellied',
                                            'slender, slim, svelte, thin')]),
                              Word('peck', "",
                                   [TestWay('n',
                                            '大量',
                                            'a considerable amount',
                                            ["Now you're in a peck of trouble. 现在你有一堆麻烦了"],
                                            'abundance, bunch, bundle, dozen, mass, mountain, much, multiplicity, myriad, pile, plenitude, profusion, ton, volume, wealth',
                                            'bit, glimmer, handful, hint, little, mite, nip, ounce, peanuts, pittance, spot, sprinkle, trace'),
                                    TestWay('v',
                                            '(不情愿地)小口咬',
                                            'to eat reluctantly and in small bites',
                                            ["Fashion models never really eat: they just peck at small meals in expensive restaurants. 时装模特们几乎不吃东西——他们只是随便咬一口昂贵餐厅里的食物"],
                                            'bite, nibble, sip, tipple',
                                            'devour, gobble, gorge, guzzle, quaff, swill')]),
                              Word('pedagogue', "",
                                   [TestWay('n',
                                            '教育者, 老师',
                                            'a person whose occupation is to give formal instruction in a school',
                                            ["a boring pedagogue who is called “PPT reader” 一个被戏称为“幻灯片朗读机”的无聊老师"],
                                            'educator, instructor, preceptor, teacher',
                                            'disciple, pupil, student')]),
                              Word('pedant', "",
                                   [TestWay('n',
                                            '书呆子, 墨守成规之人',
                                            'one who pays undue attention to book learning and formal rules',
                                            ["He is a perfect type of pedant. 他是个十足的书呆子"],
                                            'doctrinaire, dogmatist')]),
                              Word('predestine', "",
                                   [TestWay('vt',
                                            '预先注定',
                                            'to determine the fate of in advance',
                                            ["Our victory in the tournament was seemingly predestined. 我们在锦标赛中的胜利似乎是注定好了的"],
                                            'doom, fate, foredoom, foreordain, ordain, predestine, predetermine, preordain',
                                            'predestination n. 命中注定')]),
                              Word('pedestrian', "",
                                   [TestWay('n',
                                            '行人',
                                            'a person traveling on foot',
                                            ["a lane reserved for pedestrians 行人专用道"],
                                            'footer, walker',
                                            'rider'),
                                    TestWay('adj',
                                            '平庸无奇的, 令人厌倦的',
                                            'causing weariness, restlessness, or lack of interest',
                                            ["His style is so pedestrian that the book becomes a real bore. 他的风格是如此平庸以至于整本书显得非常无聊"],
                                            'arid, dreary, dull, flat, jading, jejune, monochromatic, monotonous, stale, stodgy, tedious, wearisome',
                                            'absorbing, engaging, engrossing, gripping, interesting, intriguing, involving, riveting')])])

list18_unit2 = VocabularyList([Word('peep', "",
                                   [TestWay('n',
                                            '一瞥',
                                            'a brief and sometimes furtive look',
                                            ["take a peep at the new neighbors 偷偷瞄了我们的新邻居一眼"],
                                            'gander, glance, glimpse, peek'),
                                    TestWay('n',
                                            '轻声',
                                            'a slight sound or utterance',
                                            ["I haven't heard a peep out of the children for an hour.我已经一个小时没听到孩子们的声音了"],
                                            'mumble, murmur, mutter, twitter, whisper',
                                            'clamor, noise, outcry, roar')]),
                              Word('peer', "",
                                   [TestWay('n',
                                            '同等地位的人, 同辈',
                                            'a person who has equal standing with others',
                                            ["stand out among peers 在同辈当中很出众"],
                                            'coequal, compeer, coordinate, counterpart, equivalent, fellow, match, parallel',
                                            'inferior, superior'),
                                    TestWay('v',
                                            '好奇地凝视',
                                            'to look narrowly or curiously',
                                            ["peer at the variety of marine life in the aquarium's huge tank 好奇地注视着巨大水族箱中丰富多样的海洋生物"],
                                            'blink, gape, gawk, gaze, goggle, rubberneck, stare',
                                            'glance, glimpse',
                                            'peerless adj. 无与伦比的, 不可比拟的')]),
                              Word('peeve', "",
                                   [TestWay('vt',
                                            '打扰, 惹恼',
                                            'to disturb the peace of mind of (someone) especially by repeated disagreeable acts',
                                            ["be constantly peeved by his affected flattery 总是被他做作的谄媚所惹恼"],
                                            'aggravate, annoy, bother, exasperate, frost, gall, irk, nettle, pique, rile, ruffle, vex',
                                            'becalm, compose, lull, lullaby, quiet, salve, settle, soothe, still, tranquilize',
                                            'peevish adj. 易怒的, 脾气不好的')]),
                              Word('pejorative', "",
                                   [TestWay('adj',
                                            '轻蔑的, 贬低的',
                                            'disparaging; belittling',
                                            ["I agree that I am ambitious, and I don't see it as a pejorative term. 我承认我“雄心勃勃”, 但我并不认为这是一个贬义词"],
                                            'belittling, contemptuous, degrading, deprecatory, depreciative, derogative, disdainful, disparaging, scornful',
                                            'commendatory, complimentary, laudatory')]),
                              Word('pellucid', "",
                                   [TestWay('adj',
                                            '透明的',
                                            'admitting the passage of light',
                                            ["pellucid spring water 清澈透明的泉水"],
                                            'crystal, crystalline, limpid, liquid, lucent, transparent',
                                            'opaque'),
                                    TestWay('adj',
                                            '清晰明确的, 易懂的',
                                            'transparently clear in style or meaning',
                                            ["Her poetry has a pellucid simplicity that betrays none of the sweat that went into writing it. 她的诗歌风格十分清新简约, 丝毫没有体现出她为此付出的汗水"],
                                            'apparent, distinct, evident, lucid, manifest, obvious, palpable, patent, perspicuous, plain, straightforward',
                                            'clouded, cryptic, enigmatic, indistinct, mysterious, obfuscated, obscure')]),
                              Word('pen', "",
                                   [TestWay('n',
                                            '监狱',
                                            'a place of confinement for persons held in lawful custody',
                                            ["spent six years in a federal pen 在联邦监狱中度过了六年"],
                                            'bastille, coop, jail, prison, stockade'),
                                    TestWay('v',
                                            '关押, 监禁',
                                            'to close or shut in by or as if by barriers',
                                            ["remember to pen up the dogs when visitors come over 客人来的时候别忘了把狗给关起来"],
                                            'box, encage, encase, envelop, fence, hedge, immure, include, wall',
                                            'release, enfranchise, free, liberate, set free')]),
                              Word('penalty', "",
                                   [TestWay('n',
                                            '(对罪行的)处罚',
                                            'a punishment established by law or authority for a crime or offense',
                                            ["The maximum penalty is 7 years’ imprisonment. 最为严厉的惩罚是七年的有期徒刑"],
                                            'fine, forfeit, punishment, retribution',
                                            'honor, reward',
                                            'penalize v. 处以惩罚')]),
                              Word('penchant', "",
                                   [TestWay('n',
                                            '强烈嗜好, 迷恋',
                                            'a strong and continued inclination',
                                            ["a penchant for Champaign 非常喜爱香槟"],
                                            'affection, bias, disposition, leaning, partiality, predilection, predisposition, proclivity, propensity, tendency',
                                            'aversion, disfavor, disinclination, dislike, distaste, loathing, repugnance, repulsion')]),
                              Word('penitent', "",
                                   [TestWay('adj',
                                            '悔过的',
                                            'feeling or expressing humble or regretful pain or sorrow for sins or offenses',
                                            ["a penitentbusinessman who had come to ask for forgiveness 一个来寻求宽恕的决定悔过自新的商人"],
                                            'apologetic, compunctious, regretful, remorseful, repentant, rueful, sorry',
                                            'impenitent, remorseless, unapologetic, unrepentant')]),
                              Word('pensive', "",
                                   [TestWay('adj',
                                            '沉思的, (尤指)哀思的',
                                            'given to or marked by long, quiet and often musingly sadthinking',
                                            ["Rainy days often put her in a pensive mood. 雨天总是让她陷入深深的思考之中"],
                                            'broody, cogitative, meditative, melancholy, musing, reflective, ruminant, ruminative, thoughtful',
                                            'mindless, thoughtless, unreflective')])])

list18_unit3 = VocabularyList([Word('penury', "",
                                   [TestWay('n',
                                            '贫穷',
                                            'extreme dearth; barrenness or insufficiency',
                                            ["Some have pessimistically regarded the higher education in China as an invisible and irresistible path to penury. 有人悲观地把中国的高等教育看作是一条通往贫穷的通道——无形但不可抗拒"],
                                            'destitution, impecuniosity, impoverishment, indigence, neediness, poorness, poverty, want',
                                            'affluence, opulence, richness, wealth'),
                                    TestWay('n',
                                            '吝啬, 节俭',
                                            'extreme and often niggardly frugality',
                                            ["They bitterly complained about their father's penury. 他们哀怨地抱怨父亲的节俭"],
                                            'closeness, miserliness, niggardliness, parsimony, penuriousness, stinginess, tightfistedness, tightness',
                                            'generosity, largesse, munificence, openhandedness, philanthropy',
                                            'penurious adj. 贫穷的; 吝啬的')]),
                              Word('perambulate', "",
                                   [TestWay('v',
                                            '徒步穿越, 走过',
                                            'to travel over or through especially on foot for exercise or pleasure',
                                            ["We decided to lazily perambulate the entire length of the esplanade and enjoy the fresh air. 我们决定悠哉地徒步走过滨海大道, 享受清新的空气"],
                                            'amble, cross, go, navigate, pass, peregrinate, proceed, ramble, transit, travel, traverse')]),
                              Word('perceptible', "",
                                   [TestWay('adj',
                                            '可察觉的',
                                            'capable of being perceived especially by the senses',
                                            ["You should be able to note a perceptible temperature change when you add the second reagents. 当你加入第二种试剂的时候, 你应该能够察觉到明显的温度变化"],
                                            'appreciable, apprehensible, detectable, discernible, distinguishable, palpable, sensible',
                                            'impalpable, imperceptible, inappreciable, indistinguishable, insensible, undetectable')]),
                              Word('peremptory', "",
                                   [TestWay('adj',
                                            '不容反抗的',
                                            'not allowing contradiction or refusal; imperative',
                                            ["a peremptory order from the general 将军下达的不容反抗的命令"],
                                            'compulsory, forced, imperative, incumbent, involuntary, obligatory, required',
                                            'elective, optional, voluntary'),
                                    TestWay('adj',
                                            '爱发号施令的',
                                            'fond of ordering people around',
                                            ["The peremptory secretary began telling the crowd of reporters and photographers exactly where they had to stand. 爱发号施令的秘书开始部署记者和摄影师们应该站在哪里了"],
                                            'authoritarian, despotic, dictatorial, domineering, imperious, masterful, overbearing, tyrannical, tyrannous'),
                                    TestWay('adj',
                                            '傲慢的',
                                            'having a feeling of superiority that shows itself in an overbearing attitude',
                                            ["She had such a peremptory approach to running the club that people started to avoid her. 她用一种如此傲慢自大的方式来管理俱乐部, 以至于大家纷纷开始躲避她"],
                                            'assumptive, bumptious, haughty, imperious, lofty, pompous, presumptuous, pretentious, supercilious',
                                            'humble, lowly, modest')]),
                              Word('perfervid', "",
                                   [TestWay('adj',
                                            '非常热情的',
                                            'marked by overwrought or exaggerated emotion: excessively fervent',
                                            ["perfervid love letter 热情洋溢的情书"],
                                            'ardent, demonstrative, emotional, fervid, feverish, impassioned, passionate, torrid, vehement, warm',
                                            'cold, cool, detached, dispassionate, emotionless, impassive, unemotional')]),
                              Word('perfidy', "",
                                   [TestWay('n',
                                            '不忠, 背信弃义',
                                            'an act or an instance of disloyalty',
                                            ["As loyalty unites lovers, so perfidy estranges friends. 忠诚是爱情的纽带, 欺诈是友谊的敌人"],
                                            'backstabbing, disloyalty, infidelity, sellout, treachery, unfaithfulness, double cross',
                                            'allegiance, devotion, faithfulness, fidelity, loyalty, staunchness, steadfastness',
                                            'perfidious adj. 不忠诚的')]),
                              Word('perforate', "",
                                   [TestWay('v',
                                            '打孔, 穿透',
                                            'to make a hole through',
                                            ["to perforate with a pin 用针穿孔"],
                                            'bore, drill, hole, pierce, punch, puncture, riddle')]),
                              Word('perfunctory', "",
                                   [TestWay('adj',
                                            '例行公事的, 敷衍的',
                                            'characterized by routine or superficiality and often done merely as a duty',
                                            ["gave his usual perfunctory nod 例行公事地随便点了个头"],
                                            'automatic, cursory, mechanical, superficial'),
                                    TestWay('adj',
                                            '不感兴趣的',
                                            'lacking in interest or enthusiasm',
                                            ["She gave the list only a perfunctory glance. 她无所谓地随便瞅了名单一眼"],
                                            'apathetic, casual, disinterested, incurious, indifferent, insouciant, nonchalant, pococurante, unconcerned',
                                            'concerned, interested')]),
                              Word('perimeter', "",
                                   [TestWay('n',
                                            '边界, 界限',
                                            'the line or relatively narrow space that marks the outer limit of something',
                                            ["soldiers guarding the perimeter of the camp 守卫者营地边界的士兵"],
                                            'borderline, bound, boundary, circumference, confines, edge, frame, fringe, margin, periphery, skirt, verge',
                                            'center, core, heart, kernel')]),
                              Word('periodical', "",
                                   [TestWay('n',
                                            '期刊',
                                            'a publication that appears at regular intervals',
                                            ["subscribed to three new periodicals 订阅了三份新的期刊"],
                                            'book, magazine, newspaper, paper, review, serial'),
                                    TestWay('adj',
                                            '周期性的, 有固定间隔的',
                                            'occurring or recurring at regular intervals',
                                            ["periodical announcements from airline personnel concerning the delay 航空公司工作人员关于延误所进行的一遍又一遍的广播"],
                                            'continual, periodic, recurrent, recurring',
                                            'constant, continuous, incessant, unceasing')])])

list18_unit4 = VocabularyList([Word('peripatetic', "",
                                   [TestWay('adj',
                                            '巡游的, 四处游历的',
                                            'walking about or from place to place',
                                            ["peripatetic preachers 四处游历的传教士"],
                                            'ambulant, errant, nomadic, perambulatory, peregrine, vagabond, wandering',
                                            'sedentary, settled')]),
                              Word('peripheral', "",
                                   [TestWay('adj',
                                            '外围的',
                                            'related to, located in, or constituting an outer boundary or periphery',
                                            ["development in the peripheral areas of megacities 大城市边缘地区的发展"],
                                            'circumferential, marginal',
                                            'central, interior'),
                                    TestWay('adj',
                                            '辅助性的',
                                            'available to supply something extra when needed',
                                            ["The IT consultant suggested that we update the drivers for all of the computer's peripheral devices. IT咨询师建议我们更新电脑所有外围辅助设备的驱动程序"],
                                            'accessorial, accessory, appurtenant, supplemental, supplementary',
                                            'chief, main, principal')]),
                              Word('perish', "",
                                   [TestWay('vi',
                                            '死亡, 消亡',
                                            'to become destroyed or ruined: cease to exist',
                                            ["thrive in calamity and perish in soft living 生于忧患, 死于安乐", "adapt or perish 适应或是消亡"],
                                            'decease, demise, die, end, expire, succumb, pass away',
                                            'breathe, live, survive')]),
                              Word('permanent', "",
                                   [TestWay('adj',
                                            '永恒的',
                                            'continuing or enduring without fundamental or marked change; lasting forever',
                                            ["A temporary compromise has been accepted until a more permanent solution can be agreed upon. 在更为持久的决案被通过之前, 一个暂时性的妥协方案被接受了"],
                                            'ceaseless, dateless, deathless, endless, eternal, immortal, perpetual, undying, unending',
                                            'ephemeral, evanescent, transient, transitory, provisional, temporary',
                                            'permanence n. 永恒')]),
                              Word('permeable', "",
                                   [TestWay('adj',
                                            '可渗透的',
                                            'capable of being permeated or penetrated, especially by liquids or gases',
                                            ["a permeable fabric that allows your body heat to escape 一种能使身体热量耗散的透气纤维"],
                                            'passable, penetrable, pervious, porous',
                                            'waterproof, impassable, impenetrable, impervious, impermeable')]),
                              Word('pernicious', "",
                                   [TestWay('adj',
                                            '有害的',
                                            'highly injurious or destructive',
                                            ["Business may be troublesome but idleness is pernicious. 工作烦人, 懒散害人"],
                                            'adverse, baleful, damaging, deleterious, detrimental, hurtful, injurious, mischievous, nocuous, noxious',
                                            'anodyne, benign, harmless, innocent, innocuous, inoffensive, safe')]),
                              Word('peroration', "",
                                   [TestWay('n',
                                            '(演讲的)结束语',
                                            'the concluding part of a discourse and especially an oration',
                                            ["He summarized his main points in his peroration. 他在结束语中总结了自己的主要观点"],
                                            'coda, conclusion, denouement, epilogue, finale',
                                            'foreword, prelude, preface, prologue, overture'),
                                    TestWay('n',
                                            '(正式的)演讲, 致辞',
                                            'a usually formal discourse delivered to an audience',
                                            ["a peroration celebrating the nation's long tradition of religious tolerance and pluralism 为庆祝该国长期以来对于宗教的容忍态度和宗教多元化所做的一个演讲"],
                                            'address, declamation, harangue, oration, speech, talk')]),
                              Word('perpetual', "",
                                   [TestWay('adj',
                                            '永恒的, 不断的',
                                            'continuing forever: everlasting',
                                            ["perpetual motion machine 永动机"],
                                            'ceaseless, dateless, deathless, endless, eternal, immortal, perpetual, undying, unending',
                                            'ephemeral, evanescent, transient, transitory, provisional, temporary',
                                            'perpetuate v. 使永恒')]),
                              Word('persecute', "",
                                   [TestWay('vt',
                                            '迫害, 折磨',
                                            'to cause persistent suffering to',
                                            ["people who were persecuted simply for practicing their religious faith 因为实践宗教信仰而惨遭迫害的人"],
                                            'agonize, anguish, curse, excruciate, harrow, plague, rack, torment, torture',
                                            other_form = 'persecution n. 迫害')]),
                              Word('persevere', "",
                                   [TestWay('vi',
                                            '坚持不懈, 不屈不挠',
                                            'to persist in or remain constant to a purpose, idea, or task in the face of obstacles or discouragement',
                                            ["Although he was frustrated by the lack of financial resources and support, hepersevered in his scientific research. 尽管因为资金不足而受阻, 但他仍坚持进行科学研究"],
                                            'carry on, endure, persist',
                                            'renounce, succumb, surrender, yield',
                                            'perseverance n. 坚持不懈')])])

list18_unit5 = VocabularyList([Word('persiflage', "",
                                   [TestWay('n',
                                            '打趣',
                                            'good-natured teasing or exchanging of clever remarks',
                                            ["Their tongue-in-cheek persiflage is sometimes mistaken for an exchange of insults by people who don't know them. 他们半开玩笑的打趣有时候被不认识他们的人误认为是在互相对骂"],
                                            'backchat, badinage, chaff, jesting, joshing, raillery, repartee')]),
                              Word('persistence', "",
                                   [TestWay('n',
                                            '坚持, 持续',
                                            'uninterrupted or lasting existence',
                                            ["The persistenceof the fever for a week caused me great worry. 持续一周的发烧让我很不安"],
                                            'ceaselessness, continuance, continuity, durability, endurance, subsistence',
                                            'cessation, close, end, expiration, finish, stoppage, surcease, termination',
                                            'persistent adj. 持续不断的')]),
                              Word('personable', "",
                                   [TestWay('adj',
                                            '风度翩翩的, 吸引人的',
                                            'pleasing in personality or appearance; attractive',
                                            ["apparently be attracted by a personable young man 明显被一位风度翩翩的少年迷住了"],
                                            'alluring, appealing, attractive, captivating, charismatic, charming, comely, enchanting, handsome, pretty',
                                            'grotesque, hideous, ugly')]),
                              Word('perspicacious', "",
                                   [TestWay('adj',
                                            '极敏锐的, 有洞察力的',
                                            'having or showing penetrating mental discernment; clear-sighted',
                                            ["an impartial and perspicacious judge 一个明镜高悬的法官"],
                                            'astute, savvy, sharp, sharp-witted, shrewd, smart',
                                            'ignorant, oblivious, unknowing',
                                            'perspicacity n. 敏锐, 洞察力')]),
                              Word('perspicuity', "",
                                   [TestWay('n',
                                            '清晰明了',
                                            'the quality of being perspicuous; clearness and lucidity',
                                            ["The key of modern enterprise system is the prespicuity of property right. 现代企业制度的核心是产权的明晰"],
                                            'clarity, clearness, explicitness, lucidity, lucidness, perspicuousness',
                                            'obscureness, obscurity, unclarity, ambiguity')]),
                              Word('pertain', "",
                                   [TestWay('v',
                                            '有关联',
                                            'to have a relation or connection; relate',
                                            ["new evidence that pertains to the accident 与事故相关的新证据"],
                                            'appertain, bear, concern, refer, relate',
                                            other_form = 'pertaining adj. 有关系的')]),
                              Word('pertinacious', "",
                                   [TestWay('adj',
                                            '顽固的, 固执地坚持的',
                                            'sticking to an opinion, purpose, or course of action in spite of reason, arguments, or persuasion',
                                            ["The pertinacious boy won’t stop crying unless his desire is satisfied. 这个固执的男孩在愿望没有满足的情况下是不会停止哭泣的"],
                                            'adamant, headstrong, implacable, inflexible, intransigent, mulish, obdurate, perverse, stubborn, willful',
                                            'compliant, flexible, pliable, pliant, yielding')]),
                              Word('pertinent', "",
                                   [TestWay('adj',
                                            '相关的, 恰当的',
                                            'having a clear decisive relevance to the matter in hand',
                                            ["He impressed the jury with his concise, pertinent answers to the attorney's questions. 他对律师提出的问题的简洁而恰当的回答给陪审团留下了深刻的印象"],
                                            'applicable, apposite, apropos, germane, material, pointed, relative, relevant',
                                            'extraneous, immaterial, impertinent, inapplicable, inapposite, irrelevant, pointless',
                                            'pertinence n. 相关, 恰当')]),
                              Word('perturb', "",
                                   [TestWay('vt',
                                            '扰乱, 使烦躁不安',
                                            'to trouble the mind of; to make uneasy',
                                            ["perturbed me enough to keep me awake that night 让我烦躁到当晚失眠"],
                                            'agitate, ail, bother, discomfort, discompose, distress, unsettle, upset',
                                            'calm, compose, quiet, settle, soothe, tranquilize',
                                            'perturbation n. 打扰, 扰乱')]),
                              Word('peruse', "",
                                   [TestWay('v',
                                            '细读',
                                            'to read or examine, typically with great care',
                                            ["perused the manuscript to check for grammatical errors 细读手稿以检查语法错误"],
                                            'examine, scrutinize',
                                            'glance, glimpse, scan, skim')])])

list18_unit6 = VocabularyList([Word('pervade', "",
                                   [TestWay('vt',
                                            '弥漫, 充满',
                                            'to be present throughout; permeate',
                                            ["The mixed smell of sawdust and glue pervaded the whole factory. 锯末与胶水的味道弥漫了整个工厂", "the corruption that pervades every stratum of society 充斥在社会每个阶层中的腐败"],
                                            'interpenetrate, percolate, riddle, suffuse, transfuse',
                                            other_form = 'pervasive adj.弥漫的')]),
                              Word('pessimistic', "",
                                   [TestWay('adj',
                                            '悲观的',
                                            'tending to stress the negative or unfavorable or to take the gloomiest possible view',
                                            ["With that pessimistic attitude, it's no wonder you're depressed. 你的人生观如此悲观, 难怪你会感到压抑"],
                                            'bearish, defeatist, despairing, downbeat, hopeless',
                                            'optimistic',
                                            'pessimism n. 悲观主义')]),
                              Word('petition', "",
                                   [TestWay('n',
                                            '请愿, 正式的申请',
                                            'a solemn supplication or request to a superior authority; an entreaty',
                                            ["a petition for divorce 离婚申请书"],
                                            'appeal, cry, entreaty, pleading, solicitation, supplication'),
                                    TestWay('v',
                                            '(尤指正式地)请求',
                                            'to make a request, especially a formal written one',
                                            ["She is petitioning to regain custody of the child. 为了重新获得孩子的监护权, 她提出了正式申请"],
                                            'adjure, beseech, conjure, entreat, impetrate, implore, importune, plead, solicit, supplicate',
                                            other_form = 'petitioner n. 申请人, 请愿者')]),
                              Word('petrify', "",
                                   [TestWay('v',
                                            '使僵化, 失去活力',
                                            'to cause to become stiff or stone-like; deaden',
                                            ["Pressure from family has petrified his once innovative mind. 家庭的压力使他的头脑失去了往日的创造力"],
                                            'damp, dampen, deaden, devitalize, enervate, lobotomize, ossify',
                                            'brace, energize, enliven, invigorate, quicken, stimulate, vitalize, vivify',
                                            'petrification n. 石化, 僵化')]),
                              Word('petty', "",
                                   [TestWay('adj',
                                            '细微的, 不重要的',
                                            'of small importance; trivial',
                                            ["play petty tricks 耍小聪明"],
                                            'inconsequential, inconsiderable, insignificant, measly, minute, paltry, peanut, slight, trifling, trivial',
                                            'consequential, considerable, important, material, momentous, significant')]),
                              Word('phenomenal', "",
                                   [TestWay('adj',
                                            '不寻常的, 非凡的',
                                            'being out of the ordinary; extraordinary; outstanding',
                                            ["the phenomenal growth that the suburb has experienced over the last decade 过去几十年间郊区所经历的令人称奇的快速发展"],
                                            'especial, exceptional, extraordinary, peculiar, preternatural, rare, singular, uncommon, unusual',
                                            'common, normal, ordinary, typical')]),
                              Word('philanthropic', "",
                                   [TestWay('adj',
                                            '博爱的, 为他人着想的',
                                            'having or showing a concern for the welfare of others',
                                            ["the philanthropic aims of the organization 这个机构的博爱、利他的目标"],
                                            'altruistic, beneficent, benevolent, eleemosynary, good, humanitarian',
                                            'misanthropic',
                                            'philanthropist n. 博爱的人')]),
                              Word('philistine', "",
                                   [TestWay('n',
                                            '市侩(注重物质而鄙视智慧或艺术的人)',
                                            'a person who is guided by materialism and is usually disdainful of intellectual or artistic values',
                                            ["The philistine's critics sometime limit artists’ imagine. 市侩之人的批评有时会限制艺术家的想象力"],
                                            'lowbrow, materialisthighbrow',
                                            'highbrow')]),
                              Word('phlegmatic', "",
                                   [TestWay('adj',
                                            '冷静的, 无感情的, 淡漠的',
                                            'having or suggesting a calm, sluggish temperament; unemotional',
                                            ["a strangely phlegmatic response to what should have been happy news 对本该是一个让人开心的新闻的冷漠回复"],
                                            'affectless, apathetic, cold-blooded, emotionless, impassible, numb, stoic, stolid',
                                            'demonstrative, emotional, fervent, fervid, impassioned, passionate, vehement')]),
                              Word('piddling', "",
                                   [TestWay('adj',
                                            '微不足道的',
                                            "so trifling or trivial as to be beneath one's consideration",
                                            ["raised a piddling objection to the plan 对计划提出了一个微不足道的反对"],
                                            'inconsequential, inconsiderable, insignificant, measly, minute, paltry, peanut, slight, trifling, trivial',
                                            'consequential, considerable, important, material, momentous, significant')])])

list18_unit7 = VocabularyList([Word('piebald', "",
                                   [TestWay('adj',
                                            '杂色的',
                                            'of different colors',
                                            ["a piebald horse 一匹杂色马"],
                                            'blotched, dappled, marbled, mottled, splotched, spotted',
                                            'monochromatic'),
                                    TestWay('adj',
                                            '混合的, 杂糅而成的',
                                            'consisting of many things of different sorts',
                                            ["his piebald ethnic background 他身为混血儿的背景"],
                                            'assorted, eclectic, heterogeneous, hybrid, magpie, mixed, motley, promiscuous, varied',
                                            'homogeneous')]),
                              Word('pigment', "",
                                   [TestWay('n',
                                            '颜料',
                                            'a substance that imparts black or white or a color to other materials',
                                            ["natural red pigment 天然红色染料"],
                                            'colorant, dye, stain'),
                                    TestWay('vt',
                                            '给…上颜色',
                                            'to color with or as if with pigment',
                                            ["pigmented silk 染过色的丝绸"],
                                            'paint, stain, tincture, tinge, tint',
                                            'blanch, decolorize')]),
                              Word('pilfer', "",
                                   [TestWay('v',
                                            '偷窃',
                                            'to steal stealthily in small amounts',
                                            ["pilfer the commercial document 偷窃商业文件"],
                                            'appropriate, filch, hook, lift, pinch, purloin, steal, thieve')]),
                              Word('pillar', "",
                                   [TestWay('n',
                                            '柱子',
                                            'a firm upright support for a superstructure',
                                            ["stone pillars that supported the hall 支撑大厅的石柱"],
                                            'column, pier, pilaster'),
                                    TestWay('n',
                                            '(物质、精神等方面的)支柱',
                                            'something or someone to which one looks for support',
                                            ["My father has been my pillar throughout this crisis. 整场危机之中我父亲都是我的支柱。"],
                                            'anchor, buttress, mainstay, reliance, standby')]),
                              Word('pillory', "",
                                   [TestWay('vt',
                                            '被示众嘲弄',
                                            'to expose to public contempt, ridicule, or scorn',
                                            ["The candidate mercilessly pilloried his opponent. 候选人在大众面前无情地羞辱他的对手。", "He resigned after being pilloried by the press. 在遭到媒体嘲弄之后他愤然辞职。"],
                                            'abase, debase, degrade, denounce, humiliate, ridicule',
                                            'carol, eulogize, exalt, extol, laud')]),
                              Word('pilot', "",
                                   [TestWay('n',
                                            '领航员, 飞行员',
                                            'one employed to steer a ship',
                                            ["a jet pilot 喷气式飞机飞行员"],
                                            'aviator, bellwether, captain, guide, helmsman, leader, navigator'),
                                    TestWay('adj',
                                            '初步的, 试验性的',
                                            'serving as a tentative model for future experiment or development',
                                            ["They carried out a pilot study before the larger, more expensive project was started 在更大规模、更为昂贵的项目开始之前, 他们进行了初步研究。"],
                                            'developmental, experimental, model, test, trial',
                                            'eventual, final, ultimate'),
                                    TestWay('vt',
                                            '带领通过',
                                            'lead or conduct over a usually difficult course',
                                            ["The lobbyists piloted the bill through the Senate. 游说集团使法案得到参议院的批准。"],
                                            'conduct, direct, guide, lead, route, show, steer',
                                            'follow')]),
                              Word('pine', "",
                                   [TestWay('vi',
                                            '渴望, 奢望',
                                            'to yearn intensely and persistently especially for something unattainable',
                                            ["pine for a lost love 渴望那段逝去的爱情"],
                                            'ache, crave, dream, hunger, itch, long, lust, repine, thirst, yearn',
                                            'abhor, detest, loathe'),
                                    TestWay('vi',
                                            '因渴望而憔悴',
                                            'to lose vigor, health, or flesh (as through grief)',
                                            ["Separated by their families, the lovers pined away. 这对恋人因为被家人拆散而日益憔悴。"],
                                            'decline, dwindle, fade, flag, languish, waste')]),
                              Word('pinnacle', "",
                                   [TestWay('n',
                                            '顶峰',
                                            'the highest point of development or achievement',
                                            ["a singer who has reached the pinnacle of career 已到达事业巅峰的歌手"],
                                            'acme, apex, climax, culmination, meridian, peak, summit, top, zenith',
                                            'bottom, nadir')]),
                              Word('pinpoint', "",
                                   [TestWay('adj',
                                            '非常精确的',
                                            'located, fixed, or directed with extreme precision',
                                            ["The commander demanded the pinpoint location of artillery fire. 指挥官需要火炮攻击的精确位置。"],
                                            'accurate, close, delicate, exact, fine, hairline, mathematical, precise, refined, rigorous',
                                            'coarse, cursory, rough, imprecise, inaccurate, inexact'),
                                    TestWay('v',
                                            '精确定位或确认',
                                            'to locate, fix, determine, or identify with precision',
                                            ["pinpoint the target by tracking calls from his cellphone 通过跟踪手机信号精确定位了目标", "pinpoint the cause of failure 准确找出失败的原因"],
                                            'determine, distinguish, locate, identify, recognize, spot',
                                            'estimate')]),
                              Word('piquant', "",
                                   [TestWay('adj',
                                            '辛辣开胃的',
                                            'pleasantly pungent or tart in taste',
                                            ["a piquant sauce 开胃的酱汁"],
                                            'peppery, poignant, salty, savory, spicy, zesty',
                                            'insipid, vapid, zestless'),
                                    TestWay('adj',
                                            '令人振奋的',
                                            'appealingly provocative',
                                            ["a piquant glance 充满挑逗的一瞥"],
                                            'exciting, pungent, racy, stimulating',
                                            'flat, pallid')])])

list18_unit8 = VocabularyList([Word('pique', "",
                                   [TestWay('vt',
                                            '使愤怒',
                                            'to arouse anger or resentment in',
                                            ["She was greatly piqued when they refused her invitation. 他们拒绝她的邀请让她很生气。"],
                                            'aggravate, annoy, exasperate, infuriate, irritate, peeve, provoke, rile, roil, ruffle, vex',
                                            'delight, gratify, rejoice'),
                                    TestWay('vt',
                                            '激起, 刺激',
                                            'to excite or arouse especially by a provocation, challenge, or rebuff',
                                            ["radical remarks that pique their curiosity 引起他们兴趣的激进评论"],
                                            'arouse, encourage, excite, fire, impassion, incite, instigate, move, stimulate, stir',
                                            'allay, alleviate, assuage, ease, mitigate, mollify, palliate, relieve, soothe')]),
                              Word('pirate', "",
                                   [TestWay('vt',
                                            '盗版, 盗用',
                                            'to take or make use of under a guise of authority but without actual right',
                                            ["a pirated version of the software 盗版软件"],
                                            'arrogate, commandeer, convert, expropriate, preempt, press, seize, usurp'),
                                    TestWay('n',
                                            '海盗',
                                            'a robber on the high seas',
                                            ["little boys dreaming of sailing as pirates 梦想成为海盗的小男孩"],
                                            'corsair, freebooter, rover')]),
                              Word('pithy', "",
                                   [TestWay('adj',
                                            '精练的, 简洁的',
                                            'precisely meaningful; forceful and brief',
                                            ["The professor gave a pithy introduction to this course. 教授就这门课程做了简短的介绍。"],
                                            'apothegmatic, brief, capsule, compact, compendious, concise, laconic, succinct, telegraphic, terse',
                                            'circuitous, circumlocutory, diffuse, rambling, prolix, verbose, windy, wordy',
                                            'pithiness n. 简洁, 犀利')]),
                              Word('pitiless', "",
                                   [TestWay('adj',
                                            '没有同情心的',
                                            'devoid of or unmoved by pity',
                                            ["a pitiless humiliation 毫不留情的羞辱"],
                                            'affectless, callous, coldhearted, cruel, harsh, indurate, merciless',
                                            'charitable, clement, compassionate, humane, merciful, sympathetic, tender')]),
                              Word('pittance', "",
                                   [TestWay('n',
                                            '少量津贴',
                                            'a small portion, amount, or allowance',
                                            ["The internship offers only a pittance for a salary, but it is a great opportunity to gain experience. 实习所能挣到的报酬是很少的, 但是它提供了获得经验的绝佳机会。"],
                                            'bit, mite, modicum, peanuts, trace',
                                            'cornucopia, opulence, boodle, bundle, fortune')]),
                              Word('placate', "",
                                   [TestWay('vt',
                                            '(通过让步以)平息抚慰',
                                            'to lessen the anger or agitation of',
                                            ["The colonists implemented a new policy to placate local opposition 殖民者采取新政策以缓和当地的反抗情绪"],
                                            'appease, assuage, conciliate, mollify, pacify, propitiate, tranquilize',
                                            'anger, enrage, foment, gall, incense, inflame, infuriate, peeve, rile',
                                            'placation n. 安抚')]),
                              Word('placebo', "",
                                   [TestWay('n',
                                            '安慰性的事物',
                                            'something of no intrinsic remedial value that is used to appease or reassure another',
                                            ["Candies are often adopted as the placebo for the dying patients. 糖果通常作为安慰剂给重症患者服用。"])]),
                              Word('plagiarize', "",
                                   [TestWay('v',
                                            '剽窃, 抄袭',
                                            "to steal and pass off (the ideas or words of another) as one's own",
                                            ["In scientific community, plagiarizing other’s paper is a felony. 在学术界, 剽窃他人的论文是一项重罪。"],
                                            'steal',
                                            'plagiarism n. 剽窃')]),
                              Word('plangent', "",
                                   [TestWay('adj',
                                            '轰鸣的',
                                            'having a loud reverberating sound',
                                            ["The camera man was stunned by the plangent roar of wild animals. 摄影师被野生动物发出的怒号吓得不知所措。"],
                                            'blaring, blasting, clamorous, deafening, earsplitting, resonant, resounding, sonorous, thunderous, vibrant',
                                            'muffled, muted, gentle, low, soft'),
                                    TestWay('adj',
                                            '凄凉的, 哀伤的',
                                            'having an expressive and especially plaintive quality',
                                            ["a plangent song about a long-ago love 一首关于往日爱情的凄凉歌曲"],
                                            'doleful, dolorous, funeral, grieving, lamentable, lugubrious, plaintive, rueful, sorrowful, woeful',
                                            'agreeable, cheerful, delightful, enjoyable, jolly, pleasing')]),
                              Word('plastic', "",
                                   [TestWay('adj',
                                            '可塑的',
                                            'susceptible of being modified in form or nature',
                                            ["the plastic quality of modeling clay 模型泥的可塑性质"],
                                            'adaptable, ductile, flexible, malleable, pliable, pliant, resilient, supple',
                                            'inflexible, rigid, stiff'),
                                    TestWay('adj',
                                            '虚假的, 做作的',
                                            'lacking in natural or spontaneous quality',
                                            ["There's usually a plastic cordiality at these corporate events. 通常在公司的活动上都有一种虚假的热情和友好。"],
                                            'affected, assumed, bogus, factitious, fake, false, feigned, mock, phony, pretended, pseudo, spurious',
                                            'artless, genuine, natural, spontaneous, unaffected, uncontrived, unfeigned',
                                            'plasticity n. 可塑性')])])

list18_unit9 = VocabularyList([Word('plateau', "",
                                   [TestWay('n',
                                            '高原',
                                            'a usually extensive level land area raised sharply above adjacent land on at least one side',
                                            ["Qinghai-Tibetan Plateau 青藏高原"],
                                            'highland, mesa, tableland, upland',
                                            'lowland, basin'),
                                    TestWay('n',
                                            '稳定时期, 平台期',
                                            'a relatively stable level, period, or state',
                                            ["reached a plateau of development 达到了发展的稳定期"],
                                            'equilibrium, stage, stasis')]),
                              Word('platitude', "",
                                   [TestWay('n',
                                            '陈词滥调',
                                            'a trite or banal remark or statement, especially one expressed as if it were original or significant',
                                            ["the platitude of most political oratory 政治说辞里的陈词滥调"],
                                            'banality, bromide, cliché, commonplace, homily, shibboleth, truism'),
                                    TestWay('n',
                                            '缺乏原创性',
                                            'lack of originality',
                                            'triteness, staleness',
                                            'novelty, originality')]),
                              Word('plausible', "",
                                   [TestWay('adj',
                                            '看似有理的',
                                            'superficially fair, reasonable, or valuable but often specious',
                                            ["a plausible argument 看起来头头是道的说理"],
                                            'believable, credible, likely, possible, presumable, probable',
                                            'paradoxical, implausible, improbable, incredible, unbelievable, unlikely',
                                            'plausibility n. 看似有理')]),
                              Word('pleat', "",
                                   [TestWay('n./vt',
                                            '打褶',
                                            'fold',
                                            synonyms = 'corrugate, crease, furrow, ruffle, wrinkle',
                                            antonyms = 'flatten, smooth')]),
                              Word('plentitude', "",
                                   [TestWay('n',
                                            '大量',
                                            'an ample amount or quantity; an abundance',
                                            ["a plentitude of lumber for the current housing market 充足的家具木材供给"],
                                            'abundance, affluence, cornucopia, myriad, plenty, profusion, stack, wealth',
                                            'dearth, deficiency, inadequacy, insufficiency, mite, peanuts, pinch, pittance, trace')]),
                              Word('plethora', "",
                                   [TestWay('n',
                                            '过量, 过剩',
                                            'excess, superfluity',
                                            ["a plethora of advice and a paucity of assistance 给出大量建议而鲜有实质性援助"],
                                            'abundance, cornucopia, feast, overabundance, overflow, plentitude, profusion, surfeit, surplus',
                                            'dearth, inadequacy, insufficiency, paucity, scarcity, undersupply',
                                            'plethoric adj. 过量的')]),
                              Word('pliable', "",
                                   [TestWay('adj',
                                            '易弯曲的, 柔软的',
                                            'supple enough to bend freely or repeatedly without breaking',
                                            ["pliable optical fiber 柔软的光纤"],
                                            'adaptable, ductile, flexible, limber, plastic, supple',
                                            'inflexible, rigid, stiff, unbending'),
                                    TestWay('adj',
                                            '易受影响的, 温顺的',
                                            'easily influenced, persuaded, or swayed',
                                            ["He took advantage of the pliable mind of youth. 他利用了年轻人容易受他人教唆的特点。"],
                                            'compliant, docile, obedient, pliant, tractable, subdued',
                                            'contumacious, insubordinate, intractable, obstreperous, recalcitrant, refractory, unruly')]),
                              Word('pliant', "",
                                   [TestWay('adj',
                                            '易弯曲的',
                                            'easily bent or flexed',
                                            ["a pliant young tree 易弯曲的小树"],
                                            'adaptable, ductile, flexible, limber, plastic, supple',
                                            'inflexible, rigid, stiff, unbending'),
                                    TestWay('adj',
                                            '顺从的',
                                            'yielding readily to influence or domination',
                                            ["She’s proud and stubborn, you know, under that pliant exterior. 你知道在温顺的外表下, 她骄傲而固执。"],
                                            'compliant, docile, obedient, pliant, tractable, subdued',
                                            'contumacious, insubordinate, intractable, obstreperous, recalcitrant, refractory, unruly')]),
                              Word('plight', "",
                                   [TestWay('n',
                                            '困境',
                                            'a situation, especially a bad or unfortunate one',
                                            ["He was in a plight, trying to decide whether or not to take the job. 他处在不知道是否应该接受这份工作的困境之中。"],
                                            'dilemma, jam, predicament, quandary')]),
                              Word('plod', "",
                                   [TestWay('v',
                                            '沉重缓慢地走',
                                            'to walk heavily or slowly',
                                            ["The soldiers slowly plodded across the marsh. 士兵们慢慢走过沼泽地。"],
                                            'tramp, trudge',
                                            'flit, gambol',
                                            'plodding adj. 走路沉重缓慢的')])])

list18_unit10 = VocabularyList([Word('pluck', "",
                                   [TestWay('n',
                                            '敢于面对困难的勇气',
                                            'resourceful courage and daring in the face of difficulties',
                                            ["full of pluck 充满了勇气"],
                                            'backbone, courage, dauntlessness, grit, guts, resolution, spirit, spunk',
                                            'cowardice, coward, spinelessness'),
                                    TestWay('v',
                                            '弹奏(弦乐)',
                                            'to sound (the strings of an instrument) by pulling and releasing them with the fingers or a plectrum',
                                            ["pluck the harp 弹奏竖琴"],
                                            'play',
                                            other_form = 'plucky adj. 勇敢的')]),
                              Word('plumb', "",
                                   [TestWay('vt',
                                            '测深度',
                                            'to measure the depth of (as a body of water) typically with a weighted line',
                                            ["We will plumb the bay to make sure it was deep enough for the huge vessel. 为了确证水深足够容纳这艘巨轮, 我们将会测量海湾的深度。", "questions that plumb the depths of stupidity 测量智商下限的问题"],
                                            'fathom'),
                                    TestWay('adj',
                                            '垂直的',
                                            'exactly vertical',
                                            synonyms = 'perpendicular, upright, vertical',
                                            antonyms = 'horizontal'),
                                    TestWay('adj',
                                            '完全的, 绝对的',
                                            'having no exceptions or restrictions',
                                            ["Such a movie is plumb trash and further evidence of the deterioration of popular culture. 这样的电影就是彻头彻尾的垃圾, 它进一步证明了大众文化的堕落和腐化。"],
                                            'absolute, categorical, complete, consummate, definite, pure, sheer, thorough, utter, very',
                                            'doubtful, dubious, equivocal, questionable, uncertain'),
                                    TestWay('v',
                                            '仔细深入地检查',
                                            'to examine closely or deeply',
                                            ["plumbing the book's complexities 审阅这本书的复杂度"],
                                            'explore, delve, inquire, investigate, probe')]),
                              Word('plummet', "",
                                   [TestWay('v',
                                            '突然下降',
                                            'to decline suddenly and steeply',
                                            ["Overall GPA plummeted 0.5 points. 平均学分绩骤降0.5。"],
                                            'crash, decline, descend, dip, dive, fall, plunge, sink, tumble',
                                            'skyrocket, soar')]),
                              Word('plump', "",
                                   [TestWay('adj',
                                            '丰满的',
                                            'well-rounded and full in form',
                                            ["In Tang Dynasty, being plump was a sign of ultimate beauty. 在唐代, 身材丰满是最美丽的象征。"],
                                            'chubby, fleshy, fat, gross, obese, rotund, round',
                                            'lean, slender, svelte, thin'),
                                    TestWay('vi',
                                            '鼎力支持, 赞口不绝',
                                            'to give full support or praise',
                                            ["We will plump for any candidate who supports stem cell research. 我们会鼎力支持那些拥护干细胞研究的候选人。"],
                                            'advocate, back, champion, endorse, patronize',
                                            'baffle, foil, frustrate, sabotage')]),
                              Word('plunge', "",
                                   [TestWay('vi',
                                            '突然下降',
                                            'to descend or dip suddenly',
                                            ["stock’s value plunged 股票价值骤然下降"],
                                            'crash, decline, descend, dip, dive, fall, plummet, plunge, sink, tumble',
                                            'skyrocket, soar'),
                                    TestWay('vt',
                                            '插入, 刺入',
                                            'to cause to penetrate or enter quickly and forcibly into something',
                                            ["plunged the dagger into his chest 把匕首刺入他的胸膛"],
                                            'drive, stab, stick, thrust',
                                            'extract')]),
                              Word('polarize', "",
                                   [TestWay('vt',
                                            '使分开对立, 两极分化',
                                            'to break up into opposing factions or groupings',
                                            ["The controversy has polarized voters into pro-abortion and anti-abortion groups. 这个问题使得选民分化成支持堕胎和反对堕胎两个群体。"],
                                            'bifurcate, diverge, divide',
                                            'coalesce, unite',
                                            'polarization n. 两极分化; 极化')]),
                              Word('polemic', "",
                                   [TestWay('n',
                                            '争执',
                                            'a controversial argument',
                                            ["The polemic between science and religion has never ceased. 科学和宗教之间的争论从未停息。"],
                                            'contention, controversy, disagreement, disputation',
                                            'agreement',
                                            'polemical adj. 好争论的')]),
                              Word('polished', "",
                                   [TestWay('adj',
                                            '有教养的',
                                            'showing a high degree of refinement and the assurance that comes from wide social experience',
                                            ["He maintained a very polished tone in his correspondences. 他在通信中保持着一种极有教养的口吻。"],
                                            'cultivated, cultured, genteel, refined, urbane',
                                            'gauche, rustic, philistine, uncivilized, untutored'),
                                    TestWay('adj',
                                            '擦亮的',
                                            'having a shiny surface or finish',
                                            ["She could see her face reflected in the polished hood of the car. 她可以通过引擎盖光亮的表面看到自己的脸。"],
                                            'buffed, burnished, glistening, lustrous, rubbed, satiny, sleek',
                                            'dim, dull, flat, lusterless',
                                            'polish v. 擦亮')]),
                              Word('politic', "",
                                   [TestWay('adj',
                                            '精明能干的',
                                            'characterized by shrewdness in managing, contriving, or dealing',
                                            ["a politic secretary 能干的秘书"],
                                            'diplomatic, judicious, perspicacious, sagacious, tactful, wise',
                                            'tactless, unsophisticated'),
                                    TestWay('adj',
                                            '合时宜的, 明智的',
                                            'suitable for bringing about a desired result under the circumstances',
                                            ["It probably would not be politic to tell your boss that his latest idea is the worst thing you've ever heard. 不要现在去告诉你老板说他的想法是你听过的最糟的, 这不是一个合时宜的做法。"],
                                            'advisable, desirable, prudent, tactical',
                                            'imprudent, inadvisable, injudicious, unwise')]),
                              Word('pompous', "",
                                   [TestWay('adj',
                                            '浮夸的',
                                            'excessively elevated or ornate',
                                            ["The candidate was given to windy rhetorical speeches. 听众们听了一场冗长而浮夸的演讲。"],
                                            'affected, bombastic, flowery, grandiloquent, magniloquent, rhetorical, sonorous',
                                            'homely'),
                                    TestWay('adj',
                                            '傲慢的',
                                            'having or exhibiting self-importance',
                                            ["a pompous politician who insisted on boarding the plane first 一个坚持要求优先登机的傲慢政客"],
                                            'arrogant, egocentric, haughty, pontifical, presumptuous, supercilious',
                                            'humble, modest, unpretentious')])])

LIST18 = VocabularyList(list18_unit1.words+list18_unit2.words+list18_unit3.words+list18_unit4.words+list18_unit5.words+list18_unit6.words+list18_unit7.words+list18_unit8.words+list18_unit9.words+list18_unit10.words)
