#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list15_unit1 = VocabularyList([Word('liberal', "",
                                   [TestWay('adj',
                                            '思想前卫的',
                                            'not bound by traditional ways or beliefs',
                                            ["parents who take a very liberal attitude toward letting their children stay out late 思想开放, 同意让他们的小孩晚归的家长们"],
                                            'nonconventional, nonorthodox, nontraditional, open-minded, progressive, radical',
                                            'conservative, conventional, hidebound, old-fashioned, stodgy, traditional'),
                                    TestWay('adj',
                                            '慷慨的, 大方的',
                                            'marked by generosity',
                                            ["a doctor who has been very liberal in dispensing low-cost care to patients who could not otherwise afford it 一个慷慨的医生, 愿意帮助无法支付低额药费的病人"],
                                            'charitable, munificent, unselfish, unsparing, unstinting',
                                            'closefisted, miserly, niggardly, parsimonious, stingy, tightfisted')]),
                              Word('libertine', "",
                                   [TestWay('n',
                                            '放荡不羁者',
                                            'one who acts without moral restraint; a dissolute person',
                                            ["The legend of Don Juan depicts him as a playboy and libertine. 有关唐璜的传说把他描绘成一个放荡不羁的花花公子"],
                                            'backslider, debaucher, decadent, deviate, pervert, profligate',
                                            'ascetic')]),
                              Word('licentious', "",
                                   [TestWay('adj',
                                            '放荡的, 性欲强的',
                                            'lacking legal or moral restraints ; having a strong sexual desire',
                                            ["a moralist who decried what she regarded as the licentious and corrupt culture of the entertainment industry 一个公开谴责在她看来无比堕落和放荡的娱乐圈文化的道德家"],
                                            'concupiscent, horny, lascivious, lecherous, libidinous, lubricious, salacious, wanton',
                                            'frigid, undersex',
                                            'licentiousness n. 放荡')]),
                              Word('liken', "",
                                   [TestWay('vt',
                                            '显示相似, 比较',
                                            'to see, mention, or show as similar; compare',
                                            ["Life is often likened to a journey. 生活经常被比作一次旅行"],
                                            'analogize, bracket, equate, equalize',
                                            'contrast')]),
                              Word('limber', "",
                                   [TestWay('adj',
                                            '可塑的, 柔软的',
                                            'capable of being shaped: flexible',
                                            ["She shaped the basket out of limber branches. 她用柔软的树枝编了一个筐"],
                                            'flexible, lissome, lithesome, pliable, pliant, supple',
                                            'inflexible, rigid, stiff, stiffened')]),
                              Word('limp', "",
                                   [TestWay('adj',
                                            '柔软的, 松散的',
                                            'lacking firm texture, substance, or structure',
                                            ["Her hair hung limp about her shoulders. 她的头发软沓沓地垂在肩上"],
                                            'droopy, flaccid, floppy, lank, yielding',
                                            'firm, stiff, sturdy, tense, resilient'),
                                    TestWay('adj',
                                            '软弱的, 没有精神的',
                                            'lacking strength or firmness; weak or spiritless',
                                            ["The team's limp performance has many people calling for the head coach's resignation. 队伍不给力的表现让许多人呼吁教练下课"],
                                            'enervated, lackadaisical, languid, languishing, languorous, spiritless',
                                            'ambitious, enterprising, animated, energetic, motivated'),
                                    TestWay('vi',
                                            '跛行, 艰难地行走',
                                            'to move or proceed haltingly or unsteadily',
                                            ["The project limped along with half its previous funding. 项目靠着之前一半的资金艰难地进展"],
                                            'blunder, bumble, lumber, plod, struggle, stumble, trudge')]),
                              Word('limpid', "",
                                   [TestWay('adj',
                                            '透明清澈的',
                                            'characterized by transparent clearness',
                                            ["limpid streams 清澈的小溪"],
                                            'crystal, clear, lucent, pellucid, transparent',
                                            'cloudy, murky, opaque, unclear, turbid'),
                                    TestWay('adj',
                                            '镇定的, 淡定的',
                                            'free from emotional or mental agitation',
                                            ["the limpid outlook of a man who is at peace with himself as he awaits death 一个人在平静等待死亡的过程当中所体现出来的淡然的世界观"],
                                            'collected, composed, cool, level, peaceful, placid, possessed, sedate, serene, smooth, tranquil',
                                            'agitated, discomposed, disturbed, flustered, perturbed')]),
                              Word('linger', "",
                                   [TestWay('vi',
                                            '磨蹭, 闲荡',
                                            'to proceed slowly; saunter',
                                            ["fans lingered outside the door 粉丝们在门外徘徊"],
                                            'crawl, creep, dally, dawdle, lag, loiter',
                                            'hurry, run, rush',
                                            'lingering adj. 闲荡的')]),
                              Word('lissome', "",
                                   [TestWay('adj',
                                            '柔软的',
                                            'easily bent; supple',
                                            ["Rattan is such a lissome material that it can be used for all manner of furniture and baskets. 藤是一种非常柔软而有韧性的材料, 因此可以被用于形形色色的家具和篮子之中"],
                                            'flexible, limber, lithe, pliable, pliant, supple',
                                            'solid, inflexible, rigid, stiff, stiffened'),
                                    TestWay('adj',
                                            '敏捷的, 轻盈的',
                                            'having the ability to move with ease; limber',
                                            ["a lissome ballerina 身姿矫捷的女芭蕾舞演员"],
                                            'agile, featly, feline, gracile, lithesome, nimble',
                                            'awkward, clumsy, graceless, ungainly')]),
                              Word('list', "",
                                   [TestWay('v',
                                            '倾斜',
                                            'to set or cause to be at an angle',
                                            ["The sudden lift of the load on the deck listed the ship badly. 甲板上货物被突然提angle, cant, heel, incline, pitch, slant, slope, tilt, tip起, 船陡然倾斜"],
                                            'angle, cant, heel, incline, pitch, slant, slope, tilt, tip',
                                            'erect')])])

list15_unit2 = VocabularyList([Word('lithe', "",
                                   [TestWay('adj',
                                            '敏捷的, 轻盈的',
                                            'characterized by easy flexibility and grace',
                                            ["lithe dancers 灵活优雅的舞者"],
                                            'agile, featly, feline, gracile, lightsome, nimble',
                                            'awkward, clumsy, graceless, ungainly'),
                                    TestWay('adj',
                                            '柔软的',
                                            'easily bent or flexed',
                                            ["lithe branches 柔软的枝条"],
                                            'flexible, limber, lithe, pliable, pliant, supple',
                                            'solid, inflexible, rigid, stiff, stiffened')]),
                              Word('loath', "",
                                   [TestWay('adj',
                                            '不情愿的, 讨厌的',
                                            'unwilling or reluctant; disinclined',
                                            ["I was loath to accept the fact that he had been killed in a terrorist attack. 我很不情愿地接受了他在一场恐怖袭击中丧生的事实"],
                                            'disinclined, indisposed, reluctant, reticent',
                                            'eager, disposed, inclined')]),
                              Word('loathe', "",
                                   [TestWay('vt',
                                            '厌恶',
                                            'to dislike someone or something greatly; abhor',
                                            ["I loathe having to do this. 我鄙视不得不这样做。"],
                                            'abhor, abominate, despise, detest, execrate',
                                            'adore, love',
                                            'loathsome adj. 令人讨厌的')]),
                              Word('lofty', "",
                                   [TestWay('adj',
                                            '崇高的',
                                            'elevated in character and spirit, noble',
                                            ["lofty ideals 崇高的理想"],
                                            'chivalrous, elevated, greathearted, high-minded, magnanimous, sublime',
                                            'base, debased, ignominious, mean'),
                                    TestWay('adj',
                                            '高的',
                                            'rising to a great height',
                                            ["lofty mountains 高耸的山峰", "the ever-increasing lofty heights of the world's skyscrapers 不断攀升的摩天大楼的高度"],
                                            'altitudinous, tall, towering',
                                            'low'),
                                    TestWay('adj',
                                            '自大的',
                                            'having a feeling of superiority that shows itself in an overbearing attitude',
                                            ["She acts all lofty and superior just because she went to Stanford University. 她之所以表现得这么自大和不可一世, 就因为她考进了斯坦福"],
                                            'assumptive, bumptious, haughty, lordly, peremptory, pompous, presumptuous, supercilious, superior',
                                            'humble, lowly, modest')]),
                              Word('loll', "",
                                   [TestWay('vi',
                                            '懒洋洋地行动',
                                            'to act or move in a lax, lazy, or indolent manner',
                                            ["He lolled back in his comfortable chair. 他懒洋洋地倚在他舒适的椅子上"],
                                            'slouch, lounge'),
                                    TestWay('vi',
                                            '偷懒, 打发时间',
                                            'to spend time doing nothing',
                                            ["Some members of the decorating committee were hard at work, and others were just lolling about. 装修队的一部分人在很努力的工作, 另一些则在偷懒"],
                                            'dally, dawdle, drone, laze')]),
                              Word('lopsided', "",
                                   [TestWay('adj',
                                            '歪的, 倾斜的',
                                            'leaning to one side',
                                            ["The portrait in the foyer was lopsided. 门厅里的画像挂歪了"],
                                            'askew, aslant, crazy, listing, oblique, pitched, skewed, slanted, tipping, uneven',
                                            'even, level, straight'),
                                    TestWay('adj',
                                            '不平衡的, 不协调的',
                                            'lacking in balance, symmetry, or proportion',
                                            ["The arrangement of the furniture was lopsided. 家具的摆放太不协调了", "a lopsided score of 4-0 四比零的压倒比分"],
                                            'asymmetric, disproportional, irregular, off-balance, unbalanced, unequal',
                                            'balanced, symmetrical')]),
                              Word('loquacious', "",
                                   [TestWay('adj',
                                            '话多的',
                                            'given to fluent or excessive talk',
                                            ["Sometimes the loquacious talk show host barely lets her guests get a word in. 有时候多话的脱口秀主持人让她的客人一句话都插不进来"],
                                            'chatty, conservational, gabby, garrulous, talkative, voluble',
                                            'laconic, reserved, reticent, taciturn, uncommunicative',
                                            'loquaciousness, loquacity n.话多')]),
                              Word('loutish', "",
                                   [TestWay('adj',
                                            '粗鲁的',
                                            'having the characteristics of a lout; awkward, stupid, and boorish',
                                            ["a boy with a loutish air 一个举止粗鲁的男孩"],
                                            'boorish, churlish, clumsy, crude, discourteous, uncouth, uncivilized, uncultured, unrefined',
                                            'courteous, civilized, genteel, graceful, polished, refined, urbane',
                                            'lout n. 举止粗鲁的人')]),
                              Word('lubricate', "",
                                   [TestWay('vt',
                                            '使润滑',
                                            'to coat (something) with a slippery substance in order to reduce friction',
                                            ["lubricate the gears 给齿轮打润滑油"],
                                            'grease, oil, slick, smooth, wax',
                                            'lubricant n.润滑剂')]),
                              Word('lucid', "",
                                   [TestWay('adj',
                                            '有光亮的',
                                            'suffused with light',
                                            ["Those lucid bands that spread across the arctic sky are known as aurora borealis, or the northern lights. 那些蔓延在北极的天空中光带就是北极光"],
                                            'beaming, brilliant, dazzling, glowing, incandescent, lucent, luminous, lustrous, radiant, refulgent, splendid',
                                            'dim, dull, lackluster'),
                                    TestWay('adj',
                                            '神志清醒的',
                                            "having full use of one's mind and control over one's actions",
                                            ["decided to make out her will while she was still lucid 决定趁着她神志还清醒, 列出她的遗愿"],
                                            'balanced, clearheaded, normal, right, sane, stable',
                                            'brainsick, crazy, insane, lunatic, mad, maniac'),
                                    TestWay('adj',
                                            '表达清晰的, 简单易懂的',
                                            'easily understood',
                                            ["The teaching assistant tried to make his instructions as lucid as possible so that everyone would understand what to do. 助教努力使自己的指令容易理解, 从而让所有人都知道应该要干什么"],
                                            'apprehensible, clear, comprehensible, intelligible, palpable, patent, pellucid, plain, understandable',
                                            'ambiguous, enigmatic, equivocal, indistinct, obfuscated, obscure, unclear')])])

list15_unit3 = VocabularyList([Word('lug', "",
                                   [TestWay('vt',
                                            '拖动, 拉动',
                                            'to cause to follow by applying steady force on',
                                            ["lugged the lawn mower out into the backyard 把割草机拖进院子"],
                                            'drag, draw, hale, pull, tow, tug',
                                            'drive, propel, push'),
                                    TestWay('vt',
                                            '费力搬运',
                                            'to carry laboriously',
                                            ["I don't understand why he's always lugging all of his books around when his locker is right over there. 我真搞不懂为什么他总是明明在有锁柜的情况下还随身扛着所有的书"],
                                            'bear, cart, convey, ferry, haul, lug, pack, tote, transport')]),
                              Word('lugubrious', "",
                                   [TestWay('adj',
                                            '(故作夸张的)悲哀的',
                                            'mournful, dismal, or gloomy, especially to an exaggerated or ludicrous degree',
                                            ["his lugubrious tear-stained face 他忧郁而带着泪痕的脸庞"],
                                            'deploring, doleful, dolorous, lamentable, melancholy, morose, plaintive, rueful, saturnine, sullen, woeful',
                                            'cheerful, delighted, jocund, jovial')]),
                              Word('lull', "",
                                   [TestWay('n',
                                            '相对平静时期, 间隙',
                                            'a momentary halt in an activity',
                                            ["the lull before the storm 暴风雨前的平静"],
                                            'break, breath, interruption, recess'),
                                    TestWay('vt',
                                            '使镇静, 使安心',
                                            'to free from distress or disturbance',
                                            ["The absence of attacks for such an extended period had lulled the nation into a false sense of security. 长期以来没有遭受攻击让这个国家产生了一种错误的安全感"],
                                            'allay, balm, becalm, compose, lullaby, quiet, salve, settle, soothe, still, tranquilizeagitate, discompose, disquiet, disturb, perturb, upset, vex',
                                            'agitate, discompose, disquiet, disturb, perturb, upset, vex')]),
                              Word('lullaby', "",
                                   [TestWay('n',
                                            '催眠曲',
                                            'a song to quiet children or lull them to sleep',
                                            ["sang a lullaby to the baby every night 每晚都给孩子唱摇篮曲"],
                                            'berceuse, cradlesong'),
                                    TestWay('vt',
                                            '使镇静, 使安心',
                                            'to free from distress or disturbance',
                                            ["reclining peacefully on the deck, lullabied by the gentle motion of the ship 躺卧在甲板上, 随着船轻轻的颠簸放松下来"],
                                            'allay, balm, becalm, compose, lull, quiet, salve, settle, soothe, still, tranquilize',
                                            'agitate, discompose, disquiet, disturb, perturb, upset, vex')]),
                              Word('lumber', "",
                                   [TestWay('n',
                                            '木材',
                                            'tree logs as prepared for human use',
                                            ["A huge amount of lumber will be needed to build the house. 建这栋房子需要大量的木材"],
                                            'timber, wood'),
                                    TestWay('vi',
                                            '笨拙地行动',
                                            'to walk or move with heavy clumsiness',
                                            ["The elephant lumbered through the jungle. 大象缓缓地穿越丛林"],
                                            'flounder, plod, stumble, trudge',
                                            'glide, slide'),
                                    TestWay('vt',
                                            '使负担(从而拖累)',
                                            'to place a weight or burden on',
                                            ["lumber the expedition with unnecessary equipment and supplies 不必要的仪器和补给品给此次远征徒增了许多负担"],
                                            'burden, encumber, freight, lade, laden, saddle, weight',
                                            'disburden, discharge, disencumber, unlade, unload')]),
                              Word('luminary', "",
                                   [TestWay('n',
                                            '杰出人物',
                                            'a person who has achieved eminence in a specific field',
                                            ["Buddhist luminary 佛学大师‖Luminaries from the worlds of sports, entertainment, and politics were at the gala. 全球体育界、娱乐圈和政界的名人都出席了此次盛会"],
                                            'celebrity, eminence, figure, icon, notability, star, superstar',
                                            'nobody, nonentity')]),
                              Word('lurch', "",
                                   [TestWay('v',
                                            '蹒跚',
                                            'to move forward while swaying from side to side',
                                            ["The ship lurched in the storm. 船在风暴中摇摆前行"],
                                            'careen, dodder, falter, reel, stagger, stumble, teeter, totter, waddle',
                                            'progress smoothly, march, stride, swagger')]),
                              Word('lurk', "",
                                   [TestWay('vi',
                                            '潜伏',
                                            'to lie in wait in a place of concealment especially for an evil purpose',
                                            ["Dangers lurk in the path of wilderness. 在这条荒野的小路上隐伏着危险"],
                                            'ambush, snake, steal',
                                            'appear, come out')]),
                              Word('lush', "",
                                   [TestWay('adj',
                                            '茂盛的',
                                            'growing vigorously especially with luxuriant foliage',
                                            ["lush grass 茂盛的草"],
                                            'booming, exuberant, flourishing, lively, luxuriant, rampant, thriving, verdant, vivacious',
                                            'blighted, faded, sere, withered'),
                                    TestWay('adj',
                                            '多产的',
                                            'producing abundantly',
                                            ["His lush fields were the envy of neighboring farmers. 他富饶多产的土地让邻居羡慕嫉妒恨"],
                                            'cornucopian, fecund, fruitful, productive, prolific, rich',
                                            'barren, dead, infertile, sterile, unproductive'),
                                    TestWay('adj',
                                            '(声音、味道)优美的, 令人愉悦的',
                                            'appealing to the senses',
                                            ["the lush sounds of the orchestra 管弦乐队奏出的悦耳声音"],
                                            'ambrosial, luscious, palatable, savory, sensuous, tasteful, tasty, voluptuous',
                                            'flat, flavorless, insipid, stale, tasteless')]),
                              Word('lustrous', "",
                                   [TestWay('adj',
                                            '有光泽的',
                                            'having a shiny surface or finish',
                                            ["lustrous black hair 乌黑光亮的头发"],
                                            'brilliant, burnished, gleaming, glistening, glossy, polished, refulgent, rubbed, shining, sleek, splendid',
                                            'dim, dull, lackluster, lusterless')])])

list15_unit4 = VocabularyList([Word('luxurious', "",
                                   [TestWay('adj',
                                            '豪华的',
                                            'showing obvious signs of wealth and comforts',
                                            ["The luxurious apartment was filled with the latest electronic gadgets and fine works of art. 豪华的公寓里充斥着最新式的电子产品和精美的艺术作品"],
                                            'deluxe, lavish, luxuriant, luxury, opulent, palatial, plushy, silken, sumptuous',
                                            'ascetic, austere, spartan'),
                                    TestWay('adj',
                                            '奢侈的',
                                            "given to or marked by excessive gratification of one's desires",
                                            ["squandered his family fortune in the relentless satisfaction of his luxurious tastes 为满足他奢侈的品味而挥霍家族的财产"],
                                            'decadent, indulgent, overindulgent, self-indulgent, sybaritic',
                                            'abstemious, abstinent',
                                            'luxury n. 豪华; 奢侈, 奢侈品')]),
                              Word('lyric', "",
                                   [TestWay('n',
                                            '(可以哼唱的)小曲',
                                            'a short musical composition for the human voice often with instrumental accompaniment',
                                            ["The guitarist improvised and sang a gentle lyric while playing. 吉他手在弹奏的过程中即兴创作并哼唱了一首小曲"],
                                            'ballad, ditty, jingle, vocal'),
                                    TestWay('adj',
                                            '如诗歌般流畅甜美的',
                                            'having a pleasantly flowing quality suggestive of poetry or musics',
                                            ["The film's lyric photography really enhanced its romantic mood. 电影中如诗歌般的图像效果着实增强了浪漫的氛围"],
                                            'euphonious, lyrical, mellifluous, mellow, melodious, musical, poetical',
                                            'prosaic, prose',
                                            'lyrics n. 歌词')]),
                              Word('macabre', "",
                                   [TestWay('adj',
                                            '恐怖的',
                                            'suggesting the horror of death and decay; gruesome',
                                            ["Impressively, Plants vs. Zombies presented a supposedly macabre themeinsuch anenjoyableway. 令人难忘的是, 《植物大战僵尸》将一个本应该十分恐怖的主题用一种如此欢乐的方式呈现出来"],
                                            'appalling, atrocious, dreadful, ghastly, gruesome, hideous, horrific, nightmarish, terrific',
                                            'agreeable, delightful, enjoyable, pleasant')]),
                              Word('macerate', "",
                                   [TestWay('vt',
                                            '浸泡(以软化)',
                                            'to make soft by soaking or steeping in a liquid',
                                            ["macerate the sample in ethanol 用乙醇浸软试样"],
                                            'drench, drown, impregnate, saturate, sodden, sop, souse, steep',
                                            'wring, dehydrate, desiccate, parch, sorch, sear')]),
                              Word('maculate', "",
                                   [TestWay('v',
                                            '使有斑点, 弄脏',
                                            'to spot, blemish',
                                            ["Her reputation was maculated after the affair with a married man. 自从被指与一个已婚男士有染之后, 她的名声受到了影响"],
                                            'besmirch, dot, dirty,soil, spot,stain',
                                            'clean, cleanse, purify, wash',
                                            'maculated adj. 有斑点的')]),
                              Word('maelstrom', "",
                                   [TestWay('n',
                                            '漩涡',
                                            'a powerful often violent whirlpool sucking in objects within a given radius',
                                            ["Their raft got caught in a maelstrom. 他们的筏被一个漩涡卷住了"],
                                            'gulf, vortex, whirlpool'),
                                    TestWay('n',
                                            '混乱、动荡的局势',
                                            'a violent or turbulent situation',
                                            ["the maelstrom of war 战争带来的乱世"],
                                            'chaos, disorder, pandemonium, tulmult, turmoil, upheaval, uproar',
                                            'calm')]),
                              Word('magnificent', "",
                                   [TestWay('adj',
                                            '壮丽的',
                                            'strikingly beautiful or impressive',
                                            ["a magnificent cathedral 宏伟壮观的大教堂"],
                                            'august, epic, glorious, grand, imperial, imposing, massive, monumental, noble, regal, splendid',
                                            'humble, unimpressive',
                                            'magnificence n. 壮丽, 壮观')]),
                              Word('maladroit', "",
                                   [TestWay('adj',
                                            '笨拙的',
                                            "lacking or showing a lack of nimbleness in using one's hands",
                                            ["a maladroit movement 笨拙的动作"],
                                            'awkward, bumbling, clumsy, fumbled, gauche, graceless, heavy-handed, inept, unhandy',
                                            'adroit,ambidexterous, deft, dexterous, handy')]),
                              Word('malaise', "",
                                   [TestWay('n',
                                            '不舒服',
                                            'a vague feeling of bodily discomfort, as at the beginning of an illness',
                                            ["He complained of depression, headaches and malaise. 他抱怨说感到沮丧、头痛和身体不适"],
                                            'debility, decrepitude, disease, feebleness, infirmity, infirmness, sickliness, unhealthiness')]),
                              Word('malcontent', "",
                                   [TestWay('n',
                                            '不满分子',
                                            'one who is in active opposition to an established order or government',
                                            ["The chaos was caused by a handful of malcontents. 混乱是由一小撮不满分子引起的"],
                                            'complainer, faultfinder, grouch, rebel'),
                                    TestWay('adj',
                                            '不满的',
                                            'dissatisfied with the existing state of affairs',
                                            ["The film follows three malcontent teenagers around Paris. 电影围绕着三个不满现实的青少年在巴黎展开"],
                                            'discontented, discontent, disgruntled, displeased, dissatisfied, ungratified',
                                            'contented, fulfilled, gratified, pleased, satisfied')])])

list15_unit5 = VocabularyList([Word('malicious', "",
                                   [TestWay('adj',
                                            '恶意的',
                                            'given to, marked by, or arising from malice; deliberately harmful',
                                            ["spread malicious gossips 散播恶意的流言蜚语"],
                                            'bad, cruel, despiteful, evil, malevolent, malign, mean, nasty, spiteful, vicious, virulent, wicked',
                                            'benevolent, benign, benignant, charitable, kind, kindly')]),
                              Word('malign', "",
                                   [TestWay('adj',
                                            '恶意的',
                                            'having or showing a desire to cause someone pain or suffering for the sheer enjoyment of it',
                                            ["Both parties to the divorce showed a malign desire to make each other's future life utterly miserable. 离婚双方都表露出了恶毒的愿望, 希望对方未来的生活陷入彻底的悲剧之中"],
                                            'bad, cruel, despiteful, evil, malevolent, malicious, mean, nasty, spiteful, vicious, virulent, wicked',
                                            'benevolent, benign, benignant, charitable, kind, kindly'),
                                    TestWay('vt',
                                            '诽谤',
                                            'to utter injuriously misleading or false reports about: speak evil of',
                                            ["the belief that it is possible to win an election without maligning anyone 一种信念, 那就是要赢得一场选举就不得不诽谤他人"],
                                            'asperse, blacken, calumniate, defame, libel, smear, traduce, vilify',
                                            'acclaim, applaud, eulogize, extol, laud, praise, defend, vindicate')]),
                              Word('malinger', "",
                                   [TestWay('vi',
                                            '装病以逃避工作',
                                            'to pretend or exaggerate incapacity or illness (as to avoid duty or work)',
                                            ["He claims he's ill, but I think he's just malingering. 他声称他病了, 但我觉得他是装的"],
                                            'goldbrick, shirk',
                                            'confront, face, meet',
                                            'malingerer n. 装病以逃避工作的人')]),
                              Word('malleable', "",
                                   [TestWay('adj',
                                            '可塑的',
                                            'capable of being extended or shaped by beating with a hammer or by the pressure of rollers',
                                            ["a malleable metal 有延展性的金属"],
                                            'moldable, waxy'),
                                    TestWay('adj',
                                            '易控制的',
                                            'capable of being altered or controlled by outside forces or influences',
                                            ["The cult leader took advantage of the malleable, compliant personalities of his followers. 这个头目利用了他的信徒们容易被控制和顺从的特征"],
                                            'ductile, elastic, fluid, modifiable, plastic, pliable, pliant, supple, variable',
                                            'adamant, intractable, recalcitrant, refractory, ungovernable, unmanageable, unruly')]),
                              Word('malodorous', "",
                                   [TestWay('adj',
                                            '恶臭的',
                                            'having an unpleasant smell',
                                            ["American musteline will eject amalodorous fluid when startled. 美洲鼬科动物受惊吓时会喷出有恶臭味的液体"],
                                            'fetid, foul, frowsy, funky, fusty, musty, noisome, rank, reeky, smelly, stinking, stinky',
                                            'ambrosial, aromatic, fragrant, perfumed, redolent, savory, scented, sweet',
                                            'malodorn. 恶臭')]),
                              Word('mandatory', "",
                                   [TestWay('adj',
                                            '强制的',
                                            "forcing one's compliance or participation",
                                            ["GRE test is mandatory for all students, regardless of their nationality, who wish to apply for graduate schools in the United States. GRE 是每个申请美国研究生院的学生(无论国籍)所必须参加的考试"],
                                            'compulsory, forced, imperative, incumbent, involuntary, necessary, obligatory, peremptory, required',
                                            'elective, optional, voluntary')]),
                              Word('mangle', "",
                                   [TestWay('vt',
                                            '损毁, 使伤残',
                                            'to injure with deep disfiguring wounds by cutting, tearing, or crushing',
                                            ["His body was mangled beyond recognition. 他的尸体已经被损毁到无法辨认的程度了"],
                                            'batter, deform, disfigure, distort, lacerate, mutilate, rend, wreck',
                                            'cure, heal, rehabilitate'),
                                    TestWay('vt',
                                            '弄砸',
                                            'to ruin or spoil through ineptitude or ignorance',
                                            ["The orchestra had completely mangled Bach’s music. 乐队彻底演砸了巴赫的音乐"],
                                            'blow, bumble, bungle, butcher, fumble , mar, mess, ruin, foul up, screw up')]),
                              Word('mangy', "",
                                   [TestWay('adj',
                                            '卑劣的',
                                            'mean; contemptible',
                                            ["a mangy trick 卑鄙的手段"],
                                            'base, contemptible, debased, despicable, detestable, execrable, mean, sordid, squalid',
                                            'lofty, noble, upright, venerable, virtuous')]),
                              Word('mania', "",
                                   [TestWay('n',
                                            '热衷, 狂热',
                                            'an excessively intense enthusiasm, interest, or desire; a craze',
                                            ["a mania for neatness 强烈的洁癖"],
                                            'ardor, craze, enthusiasm, fervor, obsession, passion, preoccupation, prepossession, zeal',
                                            'apathy, indifference, nonchalance, torpor',
                                            'manic adj.疯狂的')]),
                              Word('manifest', "",
                                   [TestWay('adj',
                                            '显然的, 明显易懂的',
                                            'clearly apparent to the sight or understanding; obvious',
                                            ["He is a manifest poseur. 他显然是个装模作样的人"],
                                            'apparent, clear, distinct, evident, lucid, obvious, palpable, patent, perspicuous, plain, transparent',
                                            'cryptic, enigmatic, indistinct, mysterious, obfuscated, obscure, unclear'),
                                    TestWay('v',
                                            '显现, 显露',
                                            'to make evident or certain by showing or displaying',
                                            ["His frustration is often manifested by a minor facial tic. 他的沮丧通常会从脸部的细微抽搐中表现出来"],
                                            'bespeak, betray, demonstrate, display, evince, expose, reveal',
                                            'conceal, hide',
                                            'manifesto n. 宣言, 声明')])])

list15_unit6 = VocabularyList([Word('manipulate', "",
                                   [TestWay('vt',
                                            '巧妙操作',
                                            'to move, arrange, operate, or control by the hands or by mechanical means, especially in a skillful manner',
                                            ["manipulate a foreign language 熟练地掌握外语"],
                                            'handle, finesse, manage',
                                            'bungle, fumble'),
                                    TestWay('vt',
                                            '暗中操控',
                                            'to influence or manage shrewdly or deviously',
                                            ["He manipulated public opinion in his favor. 他巧妙地将大众观点导向了有利于他的一边"],
                                            'machinate, maneuver',
                                            'manipulation n.操纵, 控制')]),
                              Word('mannered', "",
                                   [TestWay('adj',
                                            '不自然的, 做作的',
                                            'having an artificial or stilted character',
                                            ["a mannered speech 做作的演讲"],
                                            'affected, artificial, assumed, factitious, fake, feigned, pretended, pseudo, sham, spurious',
                                            'natural, artless, genuine, unfeigned')]),
                              Word('manumit', "",
                                   [TestWay('v',
                                            '解放(奴隶)',
                                            'to release from slavery or bondage',
                                            ["Though he was an outspoken defender of liberty, this son of Virginia did not manumit his own slaves until he was on his deathbed. 尽管这位维吉尼亚之子公开地支持自由, 但他直到临死才释放自己的奴隶"],
                                            'free, emancipate, enfranchise, liberate, loose, release, unbind, unchain, unshackle',
                                            'detain, enchain, enfetter, enslave')]),
                              Word('manuscript', "",
                                   [TestWay('n',
                                            '手稿',
                                            'a book, document, or other composition written by hand',
                                            ["beautiful Latin manuscript on the school's diplomas 学校毕业证书上美丽的手写拉丁文"],
                                            'calligraphy, penmanship, script',
                                            'print, type, typewriting')]),
                              Word('mar', "",
                                   [TestWay('n',
                                            '污点, 坏点',
                                            'something that spoils the appearance or completeness of a thing',
                                            ["mars on the furniture 家具上的污点"],
                                            'blight, blotch, defect, deformity, disfigurement, fault, flaw, imperfection, mark, pockmark, scar'),
                                    TestWay('vt',
                                            '破坏, 削弱',
                                            'to impair the soundness, perfection, or integrity of; spoil',
                                            ["The once flatroad surface is now marred by numerous potholes. 曾经平整的路面如今被坑洞所破坏", "an election marred by sexual scandal 被性丑闻蒙上阴影的选举 election marred by sexual scandal 被性丑闻蒙上阴影的选举"],
                                            'blemish, compromise, cripple, damage, deface, disfigure, harm, hurt, impair, injure, spoil, vitiate',
                                            'doctor, fix, mend, patch, renovate, repair, adorn, beautify, bedeck, embellish, garnish')]),
                              Word('marsh', "",
                                   [TestWay('n',
                                            '沼泽, 湿地',
                                            'an area of soft, wet, low-lying land',
                                            ["The marshes along the coast support a remarkable profusion of plants and animals. 沿着海岸线一带的沼泽为大量的动植物提供了栖息所"],
                                            'bog, fen, marshland, mire, moor, morass, quagmire, slough, swamp, wetland',
                                            'marshy adj.潮湿的')]),
                              Word('martinet', "",
                                   [TestWay('n',
                                            '纪律严明之人',
                                            'a strict disciplinarian',
                                            ["He's a retired lieutenant and a bit of a martinet. 他是一个退役的中尉, 并且是一个有点纪律严明的人"],
                                            'disciplinarian, purist, stickler',
                                            'reprobate')]),
                              Word('marvel', "",
                                   [TestWay('n',
                                            '令人惊奇的事物',
                                            'one that evokes surprise, admiration, or wonder',
                                            ["The robot is a marvel of modern engineering. 机器人是工程领域的奇迹"],
                                            'flash, miracle, phenomenon, prodigy, splendor'),
                                    TestWay('v',
                                            '(因为壮观、美丽等而)表示惊讶',
                                            'to feel amazement or bewilderment at or about',
                                            ["marvel at the tranquility of Chopin’s nocturne 惊叹于肖邦夜曲中体现出来的宁静和祥"],
                                            'gape, gaze, goggle, wonder',
                                            other_form = 'marvelous adj.令人惊奇的')]),
                              Word('masquerade', "",
                                   [TestWay('n',
                                            '面具, 伪装: ',
                                            'a display of emotion or behavior that is insincere or intended to deceive',
                                            ["Although she was deeply bored, she maintained a masquerade of polite interest as her guest droned on. 尽管她早已对客人滔滔不绝的话感到厌倦, 但她还是装出了一幅饶有兴致的样子以示礼貌"],
                                            'facade, guise, mask, pretense, semblance, show, veil'),
                                    TestWay('v',
                                            '伪装, 掩饰',
                                            'to disguise oneself',
                                            ["masquerade as a policeman 化装成警察"],
                                            'act, disguise, pose, pretend',
                                            'betray, disclose, reveal, unmask')]),
                              Word('mash', "",
                                   [TestWay('v',
                                            '捣碎',
                                            'to cause to become a pulpy mass',
                                            ["mash potatoesbefore adding it to the mixture 在混合之前捣碎土豆"],
                                            'crush, grind, smash, squeeze',
                                            'agglomerate')])])

list15_unit7 = VocabularyList([Word('mastery', "",
                                   [TestWay('n',
                                            '技艺超群, 精通',
                                            'possession or display of great skill or technique',
                                            ["She has mastery of several languages. 她熟练掌握多种语言"],
                                            'deftness, dexterity, finesse, prowess, virtuosity',
                                            'amateurishness',
                                            'masterful adj. 精通的matriculate')]),
                              Word('matriculate', "",
                                   [TestWay('vt',
                                            '入学, 录取',
                                            'to admit or be admitted into a group, especially a college or university',
                                            ["matriculate at Princeton 在普林斯顿入学"],
                                            'admit, enroll, inscribe, recruit, register',
                                            'commence, graduate, delist',
                                            'matriculation n. 录取')]),
                              Word('maudlin', "",
                                   [TestWay('adj',
                                            '过于感伤的',
                                            'effusively or tearfully sentimental',
                                            ["Some naive students display an almost maudlin concern for the welfare of animals while ignoring basic social inequity. 一些幼稚的学生忽视根本的社会不公平问题, 而对动物的权益表现出一种多愁善感的忧虑"],
                                            'lachrymose, mawkish, mushy, overemotional, sentimental, tearful',
                                            'blithe,cheerful, jocund, jovial, jubilant, apathetic,impassive, indifferent')]),
                              Word('maven', "",
                                   [TestWay('n',
                                            '专家',
                                            'one who is experienced or knowledgeable: expert',
                                            ["As an investment maven, he was doing well even when the market was doing poorly. 作为一名投资高手, 他在市场不景气的时候也能赚钱"],
                                            'ace, adept, connoisseur, expert, maestro, master, professional, proficient, virtuoso',
                                            'amateur, dabbler, dilettante')]),
                              Word('maverick', "",
                                   [TestWay('n',
                                            '特立独行之人',
                                            'a person who does not conform to generally accepted standards or customs',
                                            ["Some mavericks believe that both gravity and light are electromagnetic forces. 一些特立独行的人认为, 重力和光都是电磁力"],
                                            'bohemian, deviant, heretic, iconoclast, nonconformist',
                                            'conformer, conformist, conventionalist'),
                                    TestWay('adj',
                                            '标新立异的, 不合常规的',
                                            'deviating from commonly accepted beliefs or practices',
                                            ["a maverick view on marriage 关于婚姻的非传统看法"],
                                            'dissentient, dissenting, dissident, heterodox, iconoclastic, unorthodox',
                                            'conforming, conventional, orthodox')]),
                              Word('mawkish', "",
                                   [TestWay('adj',
                                            '过度伤感的',
                                            'excessively and objectionably sentimental',
                                            ["a mawkish love story 令人伤感的爱情故事"],
                                            'lachrymose, maudlin, mushy, overemotional, sentimental, tearful',
                                            'blithe,cheerful, jocund, jovial, jubilant, apathetic, impassive, indifferent')]),
                              Word('meager', "",
                                   [TestWay('adj',
                                            '贫乏的',
                                            'deficient in quantity, fullness, or extent; scanty',
                                            ["meager cultural resources 贫乏的文化资源"],
                                            'exiguous, niggardly, poor, scanty, scarce, skimpy, slender, slim, sparing, sparse, stingy',
                                            'abundant, ample, bountiful, copious, generous, liberal, plenteous, plentiful')]),
                              Word('mean', "",
                                   [TestWay('adj',
                                            '卑贱的',
                                            'ignoble; base',
                                            ["a mean trick to play on a credulous person 耍在一个轻信别人的人身上的卑劣诡计"],
                                            'base, contemptible, despicable, detestable, dirty, dishonorable, execrable, ignominious, sordid',
                                            'lofty, noble, venerable, virtuous'),
                                    TestWay('adj',
                                            '吝啬的',
                                            'giving or sharing as little as possible',
                                            ["a mean child who hoarded all her toys 一个把她所有的玩具都藏了起来的小气孩子"],
                                            'closefisted, mingy, miserly, niggardly, parsimonious, penurious, tightfisted, ungenerous',
                                            'generous, liberal, munificent, extravagant, lavish, prodigal, profligate, spendthrift'),
                                    TestWay('v',
                                            '打算, 怀有目的',
                                            'to have in mind as a purpose or goal',
                                            ["I mean to win this race. 我一定要赢这场比赛"],
                                            'aim, aspire, calculate, contemplate, design, intend, meditate, plan'),
                                    TestWay('v',
                                            '意味着',
                                            'to serve or intend to convey, show, or indicate',
                                            ["The national anthem means various things to various people. 对于不同的人来说, 国歌的意义不尽相同"],
                                            'connote, denote, express, import, signify, spell',
                                            other_form = 'meaningful adj. 有意义的')]),
                              Word('meander', "",
                                   [TestWay('vi',
                                            '闲逛, 漫步',
                                            'to move aimlessly and idly without fixed direction',
                                            ["meander along the river 沿着河闲逛", "vagabonds meandering through life 漂泊一生的浪子"],
                                            'amble, cruise, drift, float, ramble, roam, saunter,stroll, wander')]),
                              Word('measly', "",
                                   [TestWay('adj',
                                            '少得可怜的, 微不足道的',
                                            'so small or unimportant as to warrant little or no attention',
                                            ["gave the parking attendant a measly tip 给了停车保安少得可怜的小费"],
                                            'inconsequential, inconsiderable, insignificant, minute, paltry, peanut, petty, slight, trifling, trivial',
                                            'big, consequential, considerable, significant')])])

list15_unit8 = VocabularyList([Word('measured', "",
                                   [TestWay('adj',
                                            '深思熟虑的, 审慎的',
                                            'deliberated, calculated',
                                            ["a measured response to the terrorist attack 就恐怖袭击做出的深思熟虑的反应"],
                                            'advised, calculated, considered, knowing, reasoned, studied, thoughtful, weighed',
                                            'casual, uncalculated, unconsidered, unstudied')]),
                              Word('meddle', "",
                                   [TestWay('vi',
                                            '干涉, 管闲事',
                                            "to intrude into other people's affairs or business; interfere",
                                            ["Please stop meddling in my marriage. 请不要来干涉我的婚姻"],
                                            'interfere, interlope, intermeddle, intrude, obtrude, poke, pry, snoop',
                                            'disregard, ignore, neglect, omit, overlook',
                                            'meddlesome adj. 爱管闲事的')]),
                              Word('mediate', "",
                                   [TestWay('vt',
                                            '调解, 调停',
                                            'to intervene between two or more disputants in order to bring about an agreement, a settlement, or a compromise',
                                            ["mediate a labor-management dispute 调解劳工纠纷"],
                                            'conciliate, intercede, intermediate, interpose',
                                            'arouse, encourage, excite, foment, incite, inflame, instigate, pique, spark, stimulate, stir',
                                            'mediator n. 调停人')]),
                              Word('mediocre', "",
                                   [TestWay('adj',
                                            '平庸的, 质量中等偏下的',
                                            'moderate to inferior in quality; ordinary',
                                            ["Without a desire for success, life is at best mediocre. 没有对成功的强烈渴望, 人生最多也就是碌碌无为"],
                                            'average, common, commonplace, fair, indifferent, medium, ordinary',
                                            'outstanding, excellent, exceptional, extraordinary, impressive, superior',
                                            'mediocrity n. 平庸者; 平庸')]),
                              Word('medley', "",
                                   [TestWay('adj',
                                            '大杂烩, 混合物',
                                            'an unorganized collection or mixture of various things',
                                            ["a medley of snack foods available on the buffet table 自助餐桌上供应着各式各样的小吃"],
                                            'agglomerate, collage, hodgepodge, jumble, montage, motley, muddle, salad, shuffle, variety, welter')]),
                              Word('meek', "",
                                   [TestWay('adj',
                                            '谦恭的',
                                            'showing patience and humility; gentle',
                                            ["He was a meek, mild-mannered fellow. 他是个谦逊、温文尔雅的的人"],
                                            'humble, modest, unassuming, unpretentious',
                                            'arrogant, bumptious, haughty, imperious, pompous, presumptuous, supercilious'),
                                    TestWay('adj',
                                            '顺从的',
                                            'easily imposed on; submissive',
                                            ["He may be self-effacing, but he certainly isn't meek. 他可能是个很低调的人, 但他绝非软骨头"],
                                            'compliant, docile, manageable, obedient, submissive, tractable',
                                            'adamant, headstrong, intractable, obstinate, refractory, stubborn, unruly, unyielding')]),
                              Word('meet', "",
                                   [TestWay('adj',
                                            '合适的: ',
                                            'precisely adapted to a particular situation, need, or circumstance: very proper',
                                            ["In this case, splitting the winnings of the contested lottery ticket seems like a meetsolution. 在这种情况下, 平分有争议的彩票奖金或许是个合适的解决方案"],
                                            'applicable, appropriate, apt, becoming, befitting, felicitous, fitting, proper, right, suitable',
                                            'improper, inapplicable, inapposite, inappropriate, inapt, infelicitous, malapropos')]),
                              Word('mellifluous', "",
                                   [TestWay('adj',
                                            '(曲调)优美的',
                                            'smooth and sweet',
                                            ["a mellifluous voice 甜美的嗓音"],
                                            'dulcet, euphonious, mellifluent, mellow, melodious',
                                            'cacophonous, raspy')]),
                              Word('melodramatic', "",
                                   [TestWay('adj',
                                            '感情夸张的, 伤感的',
                                            'exaggeratedly emotional or sentimental; histrionic',
                                            ["Our office drama queen yet again made the melodramatic declaration that she was contemplating suicide. 我们办公室的“影后”又一次在危言耸听了: 这回她说她准备自杀"],
                                            'dramatic, hammy, histrionic, mannered, pretentious, stagy',
                                            'nondramatic, nontheatrical')]),
                              Word('menace', "",
                                   [TestWay('vt',
                                            '威胁, 使处于危险',
                                            'to make a show of intention to harm; to place in danger',
                                            ["Stockpiles of nuclear weapons that continue to menace the inhabitants of this planet. 大量的核武器持续地威胁着这个行星上的居民"],
                                            'compromise, hazard, imperil, jeopardize, peril, risk, threaten',
                                            'rescue, save',
                                            'menacing adj. 带有威胁的')])])

list15_unit9 = VocabularyList([Word('mendacious', "",
                                   [TestWay('adj',
                                            '撒谎的, 虚假的',
                                            'telling or containing lies',
                                            ["mendacious tales about his adventures 关于他冒险的虚假传说"],
                                            'dishonest, deceitful, fallacious, lying, spurious, untruthful',
                                            'authentic, honest, truthful, veracious')]),
                              Word('mentor', "",
                                   [TestWay('n',
                                            '导师',
                                            'a trusted counselor or guide',
                                            ["not only an lecturer but also a spirit mentor 不仅是授课者, 还是精神导师"],
                                            'advisor, coach, counselor, guide, instructor, teacher',
                                            'disciple, pupil, apprentice'),
                                    TestWay('vt',
                                            '教导, 指导',
                                            'to give advice and instruction regarding the course or process to be followed',
                                            ["We're looking for volunteers to mentor students in career planning. 我们在寻找能指导学生职业规划的志愿者"],
                                            'coach, counsel, lead, pilot, shepherd, show, tutor',
                                            'comply, follow, observe')]),
                              Word('mercenary', "",
                                   [TestWay('n',
                                            '雇佣军',
                                            'a professional soldier hired for service in a foreign army',
                                            ["hire a mercenary army to protect the VIP 雇佣了一支佣兵来保护重要人物"],
                                            'hack'),
                                    TestWay('adj',
                                            '唯利是图的, 贪婪的',
                                            'motivated solely by a desire for monetary or material gain',
                                            ["Virtue flies from the heart of a mercenary man. 唯利是图的人没有美德可言"],
                                            'acquisitive, avaricious, avid, covetous, grasping, greedy, moneygrubbing, rapacious',
                                            'benevolent, generous, liberal, philanthropic, munificent')]),
                              Word('mercurial', "",
                                   [TestWay('adj',
                                            '(情绪)善变的',
                                            'characterized by rapid and unpredictable changeableness of mood',
                                            ["his mercurial temperament 他善变的脾气"],
                                            'capricious, changeful, fluctuating, fluid, mutable, temperamental, uncertain, variable, volatile',
                                            'certain, constant, immutable, invariable, settled, stable, steady, unvarying')]),
                              Word('merited', "",
                                   [TestWay('adj',
                                            '应得的, 理所当然的',
                                            'being what is called for by accepted standards of right and wrong',
                                            ["a merited bonus 应得的奖金", "The punishment, although harsh, was entirely merited. 虽然惩罚很严厉, 但的确是应得的"],
                                            'condign, deserved, due, fair, justified, right, warranted',
                                            'undeserved, undue, gratuitous, unjustified, unwarranted')]),
                              Word('mesh', "",
                                   [TestWay('v',
                                            '诱捕',
                                            'to catch or hold as if in a net',
                                            ["Dolphins sometimes become meshed in fishnets. 有时海豚也会被渔网缠住"],
                                            'enmesh, ensnare, ensnarl, entoil, entrap, net, snare, tangle, trap',
                                            'disentangle, untangle 解开, 使解脱')]),
                              Word('mesmeric', "",
                                   [TestWay('adj',
                                            '催眠的, 催眠术的',
                                            'of, relating to, or induced by mesmerism',
                                            synonyms = 'hynoptic',
                                            antonyms = 'awaking'),
                                    TestWay('adj',
                                            '令人着迷的, 难以抗拒的',
                                            'attracting and holding interest as if by a spell',
                                            ["the mesmeric recital 迷人的独奏"],
                                            'attractive, alluring, captivating, charming, drawing, enchanting, riveting',
                                            'disgusting, loathesome, repellent, repulsive, unappealing, unattractive',
                                            'mesmerism n. 催眠术, 难以抗拒的魅力; mesmerize v. 催眠')]),
                              Word('metamorphose', "",
                                   [TestWay('vt',
                                            '变形',
                                            'to change into a different physical form especially by supernatural means',
                                            ["a science fiction story in which radiation metamorphoses people into giant bugs 一个描绘辐射将人变成了巨大虫子的科幻小说"],
                                            'alchemize, transfigure, transform, transmute, transpose, transubstantiate',
                                            'remain')]),
                              Word('metaphysical', "",
                                   [TestWay('adj',
                                            '哲学上的, 理论上的',
                                            'dealing with or expressing a quality or idea',
                                            ["a work that deals with such metaphysical questions as the very nature of knowledge 一部探讨诸如“知识的本性是什么”的理论问题的著作"],
                                            'conceptual, ideal, ideational, notional, theoretical',
                                            'concrete'),
                                    TestWay('adj',
                                            '非尘世的',
                                            'of, relating to, or being part of a reality beyond the observable physical universe',
                                            ["a metaphysical world beyond the one in which we live 在我们居住的世界之上的“超然世界”"],
                                            'ethereal, heavenly, otherworldly, paranormal, preternatural, transcendental, unearthly, unworldly',
                                            'mundane, natural')]),
                              Word('meteoric', "",
                                   [TestWay('adj',
                                            '流星般迅速而短暂的',
                                            'similar to a meteor in speed, brilliance, or brevity',
                                            ["a meteoric rise to fame 一夜成名"],
                                            'ephemeral, evanescent, fleeting, momentary, rapid, transient, transitory',
                                            'enduring, lasting, permanent, prolonged')])])

list15_unit10 = VocabularyList([Word('methodical', "",
                                   [TestWay('adj',
                                            '井然有序的, 有条理的',
                                            'arranged or proceeding in regular, systematic order',
                                            ["a methodical summary that included lists of points to memorize 一份包含了记忆重点的有条理的总结"],
                                            'neat, orderly, organized, regular, systematic, systematized',
                                            'disorganized, haphazard, irregular, unsystematic')]),
                              Word('meticulous', "",
                                   [TestWay('adj',
                                            '极为谨慎的',
                                            'marked by extreme or excessive care in the consideration or treatment of details',
                                            ["He was so meticulous about everything. 他对所有事都一丝不苟"],
                                            'careful, conscientious, exact, fussy, heedful, painstaking, punctilious, scrupulous',
                                            'careless, feckless, heedless, thoughtless')]),
                              Word('mettle', "",
                                   [TestWay('n',
                                            '勇气',
                                            'vigor and strength of spirit or temperament',
                                            ["troops who showed their mettle in combat 在战场上表现出坚强勇气的部队"],
                                            'bravery, courage, dauntlessness, fortitude, guts, nerve, pluck, spirit, spunk, valor',
                                            'cowardice, cravenness, gutlessness, pusillanimity, spinelessness'),
                                    TestWay('n',
                                            '毅力, 耐力',
                                            'staying quality: stamina',
                                            ["Those trucks had proved their mettle in army transport. 那些卡车通过在军队运输中的表现证明了它们的耐用性"],
                                            'durability, endurance, stamina, persistence, resolution',
                                            'mettlesome adj. 有毅力的')]),
                              Word('miff', "",
                                   [TestWay('vt',
                                            '使恼怒',
                                            'to cause to become offended or annoyed',
                                            ["be miffed by her son’s disobedience 被她儿子的叛逆惹恼"],
                                            'aggravate, annoy, enrage, exasperate, incense, infuriate, ire, madden, nettle, peeve, umbrage, vex',
                                            'appease, assuage, mollify, placate, propitiate, delight, gratify, please')]),
                              Word('migratory', "",
                                   [TestWay('adj',
                                            '迁移的',
                                            'having a way of life that involves moving from one region to another typically on a seasonal bas',
                                            ["migratory birds heading south for the winter 为了越冬而往南飞的候鸟"],
                                            'migrant, mobile, nomad, nomadic, traveling',
                                            'nonmigrant, resident, sedentary')]),
                              Word('milk', "",
                                   [TestWay('vt',
                                            '榨取(财富、信息等)',
                                            'to draw or coerce profit or advantage from illicitly or to an extreme degree',
                                            ["milk the workers 从工人身上榨取好处", "The interrogators milked the arrested spy, but he was dry. 审问者想尽办法套被捕间谍的话, 但是无功而返"],
                                            'drain, exploit')]),
                              Word('mime', "",
                                   [TestWay('v',
                                            '模仿',
                                            "to use (someone or something) as the model for one's speech, mannerisms, or behavior",
                                            ["miming a dog begging for food 模仿小狗乞食"],
                                            'ape, copy, copycat, emulate, mimic, simulate')]),
                              Word('mimic', "",
                                   [TestWay('adj',
                                            '仿真的, 仿造的',
                                            'being such in appearance only and made with or manufactured from usually cheaper materia',
                                            ["Police were concerned that the mimic gun, although intended only as a toy, might be confused with the real thing in certain situations. 尽管仿真枪只是玩具, 但警方担忧在某些情况下它会被误认为是真枪"],
                                            'artificial, bogus, factitious, fake, false, imitative, mock, sham, simulated, substitute, synthetic',
                                            'genuine, natural, real'),
                                    TestWay('v',
                                            '做滑稽的模仿(以取笑)',
                                            'to copy or exaggerate (someone or something) in order to make fun of',
                                            ["The comedian was famous for mimicking the President's distinctive lisp. 这个演员因能滑稽地模仿总统特有的口齿不清而闻名"],
                                            'burlesque, caricature, do, imitate, mock, parody, send up, spoof, travesty'),
                                    TestWay('v',
                                            '模仿',
                                            "to use (someone or something) as the model for one's speech, mannerisms, or behavior",
                                            ["began to learn their language by mimicking the sounds they made 通过模仿发音来学习语言"],
                                            'ape, copy, copycat, emulate, mimic, simulate',
                                            'mimicry n. 模仿')]),
                              Word('minatory', "",
                                   [TestWay('adj',
                                            '带来威胁的, 有凶兆的',
                                            'being or showing a sign of evil or calamity to come',
                                            ["The novel's protagonist is haunted by a minatory black specter. 小说的主人公被不详的黑色幽灵所骚扰"],
                                            'baleful, direful, doomy, foreboding, ill-boding, inauspicious, menacing, portentous, sinister, threatening',
                                            'unthreatening, reassuring')]),
                              Word('mince', "",
                                   [TestWay('vt',
                                            '切碎',
                                            'to cut or chop into very small pieces',
                                            ["I'll buy some lean meat and mince it myself. 我会买一些瘦肉然后自己切好的"],
                                            'cut, dice, grind, hash'),
                                    TestWay('vt',
                                            '小步走',
                                            'to walk with very short steps or with exaggerated primness',
                                            ["The bride minced through the cathedral. 新娘踏着细小的步伐穿过教堂"],
                                            antonyms = 'stride')])])

LIST15 = VocabularyList(list15_unit1.words+list15_unit2.words+list15_unit3.words+list15_unit4.words+list15_unit5.words+list15_unit6.words+list15_unit7.words+list15_unit8.words+list15_unit9.words+list15_unit10.words)
