#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list13_unit1 = VocabularyList([Word('impugn', "",
                                   [TestWay('v',
                                            '责难，攻击抨击',
                                            'to attack as false or questionable; challenge in argument',
                                            ["impugn a political opponent's character 就政治对手的人品发难"],
                                            'attack, assail, contradict, contravene, cross, disaffirm, deny, gainsay, negate, negative, traverse',
                                            'advocate, back, support, uphold, authenticate')]),
                              Word('impuissance', "",
                                   [TestWay('n',
                                            '无权，虚弱',
                                            'lack of power or effectivenes',
                                            ["In spite of their impuissance the group remains highly active. 尽管手中无权，但这个组织仍然十分活跃"],
                                            'impotence, powerlessness, weakness',
                                            'clout, potency, power, puissance',
                                            'impuissant adj. 无权无势的，无能的')]),
                              Word('inadvertent', "",
                                   [TestWay('adj',
                                            '偶然发生的',
                                            'happening by chance',
                                            ["an inadvertent encounter with a rattlesnake 偶遇响尾蛇"],
                                            'casual, fluky, incidental, unintentional, unplanned, unpremeditated, unwitting',
                                            'calculated, deliberate, intended, intentional, planned, premeditated'),
                                    TestWay('adj',
                                            '疏忽的，不留意的',
                                            'marked by unintentional lack of care',
                                            ["The military has said it was an inadvertent error. 军方表示这是个疏忽大意的错误"],
                                            'careless, feckless, heedless, irreflective, thoughtless, uncaring',
                                            'advertent, careful, heedful, mindful')]),
                              Word('inalienable', "",
                                   [TestWay('adj',
                                            '不可剥夺的，不能让与的',
                                            'cannot be transferred to another or others',
                                            ["inalienable rights of the citizen 公民不可予夺的权利"],
                                            'untransferable',
                                            'alienable')]),
                              Word('inane', "",
                                   [TestWay('adj',
                                            '空洞的',
                                            'lacking significance, meaning, or point',
                                            ["inane comments 空洞的评论"],
                                            'empty, insubstantial, pointless, senseless',
                                            'meaningful, significant, deep, profound')]),
                              Word('inanimate', "",
                                   [TestWay('adj',
                                            '无生命的',
                                            'not having the qualities associated with active, living organisms',
                                            ["He thinks that inanimate objects have a life of their own. 他认为无生命的事物其实也是有生命的"],
                                            'dead, lifeless, insensible, insentient, senseless, unfeeling',
                                            'animate, living')]),
                              Word('inaugurate', "",
                                   [TestWay('vt',
                                            '使就职',
                                            'to induct into an office by a formal ceremony',
                                            ["A new leader will be inaugurated soon. 新的领导即将就职"],
                                            'induct, initiate, install, instate, invest, seat',
                                            'abdicate, resign'),
                                    TestWay('vt',
                                            '开始',
                                            'to cause to begin, especially officially or formally',
                                            ["inaugurate a new immigration policy 实施新的移民政策"],
                                            'begin, commence, establish, institute, introduce, launch, open, plant, start',
                                            'cease, close, end, terminate',
                                            'inauguration n. 就职，开始')]),
                              Word('incandescent', "",
                                   [TestWay('adj',
                                            '明亮灿烂的',
                                            'strikingly bright, radiant, or clear',
                                            ["incandescent light bulbs 明亮的灯泡"],
                                            'beaming, brilliant, dazzling, effulgent, glowing, lucent, luminous, lustrous, radiant, refulgent, shining',
                                            'dim, dull, lackluster'),
                                    TestWay('adj',
                                            '热情饱满的',
                                            'characterized by glowing zeal',
                                            ["It makes me incandescent with fury. 它让我愤怒不已"],
                                            'ardent, demonstrative, emotional, fervid, impassioned, passionate, torrid, vehement',
                                            'cold, cool, dispassionate, emotionless, impassive, unemotional')]),
                              Word('incantation', "",
                                   [TestWay('n',
                                            '咒语',
                                            'a spoken word or set of words believed to have magic power',
                                            ["Hovering over the sick child, the witch doctor muttered mysterious incantations. 巫医在生病的小孩子身边走来走去，嘴里念着神秘的咒语"],
                                            'abracadabra, bewitchment, charm, conjuration, enchantment, glamour, hex, invocation')]),
                              Word('incarnate', "",
                                   [TestWay('adj',
                                            '化身的，人体化的',
                                            'invested with bodily nature and form',
                                            ["He referred to her as devil incarnate. 他把她视作恶魔的化身"],
                                            'embodied, materialized, personified, typified'),
                                    TestWay('v',
                                            '（思想、理论的）具化，体现',
                                            'to constitute an embodiment or type of',
                                            ["the general view that Hitler incarnated extreme egotism 通常认为希特勒代表了极端的以自我为中心"],
                                            'epitomize, incorporate, manifest, materialize, personalize, personify, substantiate, symbolize',
                                            'disembody',
                                            'incarnation n. 化身')])])

list13_unit2 = VocabularyList([Word('incendiary', "",
                                   [TestWay('n',
                                            '煽动者',
                                            'a person who stirs up public feelings especially of discontent',
                                            ["behind-the-scenes incendiaries who were intending to overthrow the government 企图推翻政府的幕后煽动者"],
                                            'demagogue, exciter, firebrand, fomenter, inciter, instigator, kindler, provocateur'),
                                    TestWay('adj',
                                            '煽动性的',
                                            'tending to inflame',
                                            ["an incendiary speech 煽动性的演说"],
                                            'agitational, instigative, provocative, seditious',
                                            'conciliatory, pacific')]),
                              Word('incense', "",
                                   [TestWay('n',
                                            '芳香',
                                            'a sweet or pleasant smell',
                                            ["the heavenly incense of spring flowers 春天花朵发出的美妙芳香"],
                                            'aroma, balm, bouquet, fragrancy, perfume, redolence, scent, spice',
                                            'fetor, malodor, reek, stench, stink'),
                                    TestWay('vt',
                                            '激怒',
                                            'to cause to be extremely angry',
                                            ["This proposal will certainly incense female activists. 这个提案肯定会激怒女权主义者"],
                                            'aggravate, enrage, exasperate,inflame, infuriate, ire, madden, outrage, rankle, rile, roil',
                                            'delight, gratify, please, appease, conciliate, mollify, pacify, placate, propitiate, soothe')]),
                              Word('inception', "",
                                   [TestWay('n',
                                            '开端，开始',
                                            'an act, process, or instance of beginning',
                                            ["This seemed like a good program at its inception, but it isn't working out as planned. 一开始这像是个不错的项目，但是它没有按照我们的预期发展"],
                                            'beginning, birth, commencement, dawn, genesis, kickoff, launch, nascence, onset, outset, start, threshold',
                                            'close, conclusion, end, termination, omega',
                                            'inceptive adj. 开端的，初生的')]),
                              Word('incessant', "",
                                   [TestWay('adj',
                                            '无间断的',
                                            'continuing or following without interruption',
                                            ["The incessant noise from an outside repair crew was a real distraction during the test. 窗外维修工发出的持续不断的噪音着实让人在考试里分心"],
                                            'ceaseless, continual, nonstop, perpetual, running, unbroken, unceasing, uninterrupted, unremitting',
                                            'interrupted, discontinuous, intermittent')]),
                              Word('inch', "",
                                   [TestWay('n',
                                            '少量，很短的距离',
                                            'a very small distance or degree',
                                            ["give them aninch, and they'll take a mile 得寸进尺‖Inch by inch, we're making progress toward our fund-raising goal. 我们在慢慢地接近筹款的目标"],
                                            'ace, hairbreadth, skip, neck, step'),
                                    TestWay('v',
                                            '慢慢移动',
                                            'to move or cause to move slowly or by small degrees',
                                            ["The car inched carefully across the snow-covered bridge. 汽车慢慢地通过被大雪覆盖的桥梁"],
                                            'crawl, creak, creep, limp, plod, slouch, snail',
                                            'dart, fleet, flit, scurry')]),
                              Word('inchoate', "",
                                   [TestWay('adj',
                                            '新生的',
                                            'in an initial or early stage',
                                            ["inchoate feelings of affection for a man 刚刚产生的好感"],
                                            'aborning, beginning, inceptive, incipient, initial, nascent',
                                            'adult, full-blown, full-fledged, mature, ripe, moribund'),
                                    TestWay('adj',
                                            '未完全成型的',
                                            'imperfectly formed or developed',
                                            ["a vague, inchoate notion 模糊而不成形的想法"],
                                            'amorphous, formless, shapeless, undeveloped, unformed, unshaped')]),
                              Word('incinerate', "",
                                   [TestWay('vi',
                                            '烧成灰烬',
                                            'to cause to burn to ashes',
                                            ["The government is trying to stop farmers incinerating their own waste. 政府开始阻止农民们焚烧垃圾的行为"],
                                            'burn, carbonize',
                                            'douse, extinguish, quench, put out',
                                            'incineration n. 焚化')]),
                              Word('incipient', "",
                                   [TestWay('adj',
                                            '起初的，初现的',
                                            'beginning to come into being or to become apparent',
                                            ["an incipient economic recovery 刚刚出现的经济复苏"],
                                            'aborning, beginning, inceptive, inchoate,initial, nascent',
                                            'adult, full-blown, full-fledged, mature, ripe, moribund')]),
                              Word('incite', "",
                                   [TestWay('vt',
                                            '煽动，激起',
                                            'to provoke and urge on',
                                            ["inciting workers to strike 煽动工人罢工"],
                                            'arouse, abet, foment, instigate, pick, provoke, raise, stir',
                                            'dampen, deter, discourage, dishearten, dissuade')]),
                              Word('inclement', "",
                                   [TestWay('adj',
                                            '（天气等）恶劣的',
                                            'lacking mildness',
                                            ["inclement weather conditions 恶劣的气象条件"],
                                            'bleak, harsh, severe, stormy, tempestuous',
                                            'bright, clear, cloudless, fair, sunny, sunshiny, unclouded'),
                                    TestWay('adj',
                                            '无情的，严酷的',
                                            'showing no clemency; unmerciful',
                                            synonyms = 'bitter, brutal, intemperate, rigorous',
                                            antonyms = 'charitable, clement, lenient, merciful',
                                            other_form = 'inclemency n. 严酷无情')])])

list13_unit3 = VocabularyList([Word('incogitant', "",
                                   [TestWay('adj',
                                            '考虑不周的，不体谅的',
                                            'thoughtless; inconsiderate',
                                            ["an incogitant litterbug 不体谅人的乱扔垃圾者"],
                                            'discourteous, disrespectful, ill-mannered, impertinent, inconsiderate, rude, thoughtless, ungracious',
                                            'civil, considerate, courteous, genteel, gracious, thoughtful')]),
                              Word('incongruent', "",
                                   [TestWay('adj',
                                            '不一致的',
                                            'not conforming to the circumstances or requirements of a situation',
                                            ["Two triangles are incongruent. 两个三角形不全等。"],
                                            'conflicting, discordant, discrepant, dissonant, incompatible, incongruous, inconsonant',
                                            'congruent, congruous, consistent')]),
                              Word('inconsequential', "",
                                   [TestWay('adj',
                                            '不合逻辑的',
                                            'not using or following good reasoning',
                                            ["an inconsequential line of argument 不合逻辑的论述"],
                                            'fallacious, illogical, invalid, irrational, unreasonable, unsound, weak',
                                            'logical, rational, reasonable, sound, valid, well-founded, well-grounded'),
                                    TestWay('adj',
                                            '不重要的',
                                            'of no significance',
                                            ["That's an inconsequential problem compared to the other issues. 和其他问题相比，这就是个无关痛痒的小事"],
                                            'fiddling, frivolous, inconsiderable, insignificant, minor, minute, negligible, nugatory, petty, slight, trivial',
                                            'consequential, eventful, important, meaningful, momentous, significant, substantial, weighty')]),
                              Word('incontrovertible', "",
                                   [TestWay('adj',
                                            '无可争议的',
                                            'not open to question',
                                            ["incontrovertible facts 无可非议的事实"],
                                            'certain, inarguable, incontestable, indisputable, indubitable, positive, sure, undeniable, unquestionable',
                                            'arguable, controversial, debatable, disputable, problematic, questionable, refutable',
                                            'incontrovertibility n. 无可争议')]),
                              Word('incorrigible', "",
                                   [TestWay('adj',
                                            '不可救药的，积习难改的',
                                            'incapable of being corrected or amended',
                                            ["an incorrigible criminal deserving death penalty 一个应该被判死刑的恶习难改的罪犯"],
                                            'incurable, irrecoverable, irredeemable, irremediable, irretrievable, unrecoverable, unredeemable',
                                            'curable, reclaimable, recoverable, redeemable, remediable, retrievable, savable'),
                                    TestWay('adj',
                                            '无法管制的',
                                            'difficult or impossible to control or manage',
                                            ["an incorrigible, spoiled child 被宠坏了的难管的孩子"],
                                            'headstrong, intractable, obstinate, refractory, stubborn, unmanageable, unruly, willful',
                                            'compliant, docile, manageable, obedient, submissive, tractable')]),
                              Word('incriminate', "",
                                   [TestWay('vt',
                                            '归罪于',
                                            'to accuse of a crime or other wrongful act',
                                            ["incriminate innocent people 诬陷好人"],
                                            'charge, criminate ,impeach, indict',
                                            'absolve, acquit, exculpate, exonerate, vindicate')]),
                              Word('incubate', "",
                                   [TestWay('vt',
                                            '孵化',
                                            'to cover and warm eggs as the young inside develop',
                                            ["The hen incubated her eggs for two weeks. 母鸡孵蛋两周"],
                                            'brood, hatch, sit'),
                                    TestWay('vt',
                                            '帮助，培养，促进',
                                            'to cause or aid the development of',
                                            ["Hopefully, these youthful visits to the museum will incubate an enduring love of art. 我们希望年轻时参观博物馆能够培养他们对于艺术的持久热爱"],
                                            'advance, cultivate, encourage, forward, further, nourish, nurse, nurture, promote',
                                            'check, discourage, frustrate, hinder, impede, inhibit, obstruct, retard, shackle',
                                            'incubator n. 恒温箱; incubation n. 孵化，孵卵')]),
                              Word('inculpate', "",
                                   [TestWay('vt',
                                            '归罪于',
                                            'incriminate',
                                            synonyms = 'charge, criminate, inculpate, indict, incriminate',
                                            antonyms = 'absolve, acquit, exculpate, exonerate, vindicate')]),
                              Word('incursion', "",
                                   [TestWay('n',
                                            '入侵',
                                            'a hostile entrance into a territory',
                                            ["homes damaged by the incursion of floodwater 被洪水入侵破坏的房屋"],
                                            'foray, inroad, invasion, irruption, raid',
                                            'retreat, withdrawal')]),
                              Word('indelible', "",
                                   [TestWay('adj',
                                            '（印记等）无法擦除的',
                                            'impossible to remove, erase, or wash away',
                                            ["indelible ink 难以擦拭的墨水"],
                                            'ineffaceable, ineradicable, inerasable, ingrained',
                                            'eradicable, erasable, removable, washable'),
                                    TestWay('adj',
                                            '无法忘怀的',
                                            'not easily forgotten',
                                            ["most indelible experiences 最难以磨灭的经历"],
                                            'impressive, memorable, unforgettable',
                                            'forgettable')])])

list13_unit4 = VocabularyList([Word('indemnity', "",
                                   [TestWay('n',
                                            '（损害、伤害等的）保险补偿',
                                            'compensation for damage, loss, or injury suffered',
                                            ["The widow now lives on a pension and an indemnity from her late husband's company. 这个寡妇如今依靠社保和前夫公司的保险赔偿过日"],
                                            'compensation, indemnification, quittance, recompense, redress, remuneration, reparation, requital')]),
                              Word('indict', "",
                                   [TestWay('vt',
                                            '起诉，控告',
                                            'to accuse of wrongdoing; charge',
                                            ["indict the mayor for fraud and embezzlement. 起诉市长受贿和挪用公款"],
                                            'charge, criminate, impeach, incriminate',
                                            'absolve, acquit, exculpate, exonerate, vindicate')]),
                              Word('indifferent', "",
                                   [TestWay('adj',
                                            '公平的',
                                            'marked by impartiality',
                                            ["They believed their art teacher could offer an indifferent judgment on their works' merits. 他们相信艺术老师会对他们作品的价值做出公正的评价"],
                                            'disinterested, equal, impartial, just, nonpartisan, objective, unbiased, unprejudiced',
                                            'biased, one-sided, partial, prejudiced, unjust'),
                                    TestWay('adj',
                                            '（质量、档次等）中规中矩的，一般的',
                                            'of average to below average quality',
                                            ["an indifferent but drinkable cup of coffee 一杯尚可入口的咖啡"],
                                            'average, common, fair, intermediate, mediocre, medium, moderate, ordinary, passable, so-so',
                                            'exceptional, extraordinary, inferior, poor'),
                                    TestWay('adj',
                                            '不感兴趣的，冷漠的',
                                            'marked by a lack of interest, enthusiasm, or concern for something',
                                            ["indifferent about the result of CET-4 对四级成绩不感兴趣"],
                                            'aloof, apathetic, detached, incurious, nonchalant, numb, pococurante, remote, unconcerned, uninterested',
                                            'attentive, concerned, interested',
                                            'indifference n. 漠然')]),
                              Word('indigenous', "",
                                   [TestWay('adj',
                                            '土产的，本地的',
                                            'originating and living or occurring naturally in an area or environment',
                                            ["the culture of the indigenous people of that country 那个国家原著民的文化"],
                                            'aboriginal, endemic, native',
                                            'exotic, extraneous, foreign, nonnative'),
                                    TestWay('adj',
                                            '与生俱来的，先天的',
                                            'being a part of the innermost nature of a person or thing',
                                            ["The drive to create is indigenous to humanity. 人类创造的动力是与生俱来的"],
                                            'constitutional, essential, immanent, inborn, inbred, ingrained, innate, integral, intrinsic, natural',
                                            'adventitious, extrinsic, acquired, studied')]),
                              Word('indigent', "",
                                   [TestWay('adj',
                                            '贫穷的',
                                            'lacking money or material possessions',
                                            ["indigent people who require some outside assistance 需要外来援助的贫苦人民"],
                                            'beggared, destitute, impecunious, impoverished, necessitous, needy, penniless, penurious, threadbare',
                                            'affluent, opulent, rich, wealthy',
                                            'indigence n. 贫穷')]),
                              Word('indispensable', "",
                                   [TestWay('adj',
                                            '必不可少的，不可或缺的',
                                            'impossible to do without',
                                            ["She was becoming indispensible to him. 对他而言她逐渐变得不可替代"],
                                            'critical, crucial, imperative, necessary, necessitous, needed, required, requisite, vital',
                                            'dispensable, redundant, superfluous, surplus')]),
                              Word('indoctrinate', "",
                                   [TestWay('vt',
                                            '教育，灌输思想',
                                            'to instruct especially in fundamentals or rudiments',
                                            ["indoctrinate students with the notion of egalitarianism 向学生灌输平等主义的思想"],
                                            'educate, instruct, lesson, teach, train, tutorlearn, study',
                                            'learn, study')]),
                              Word('indolent', "",
                                   [TestWay('adj',
                                            '懒惰的',
                                            'averse to activity, effort, or movement',
                                            ["The sweltering afternoon made us indolent. 炎热的午后使我们懒散不愿行动"],
                                            'lazy, idle, shiftless, slothful, sluggish',
                                            'diligent, industrious 勤奋的',
                                            'indolence n. 懒惰')]),
                              Word('inducement', "",
                                   [TestWay('n',
                                            '动机，刺激源',
                                            'a motive or consideration that leads one to action',
                                            ["offered an expensive watch as an inducement to ratify the proposal 赠送名贵手表以求计划得到批准"],
                                            'goad, impulse, incentive, motive, spur, stimulus',
                                            'deterrent'),
                                    TestWay('n',
                                            '劝说，游说',
                                            'the act of reasoning or pleading with someone to accept a belief or course of action',
                                            ["He gave up smoking only after a prolonged inducement by all the other family members. 在所有家庭成员坚持不懈的劝说之下，他终于愿意戒烟了"],
                                            'conversion, convincing, persuading, suasion',
                                            other_form = 'induce v. 导致，产生')]),
                              Word('indulgent', "",
                                   [TestWay('adj',
                                            '（对己）放纵的，（对他人）纵容的',
                                            'showing, characterized by, or given to indulgence',
                                            ["indulgent aristocrats 生活放纵的贵族"],
                                            'decadent, forbearing, lenient, luxurious, tolerant, sybaritic',
                                            'ascetic, draconian',
                                            'indulgence n. 放纵')])])

list13_unit5 = VocabularyList([Word('indurate', "",
                                   [TestWay('adj',
                                            '铁石心肠的，冷酷无情的',
                                            'having or showing a lack of sympathy or tender feelings',
                                            ["an indurate heart that admits no love or mercy 一颗不认可爱或仁慈的冷酷心灵"],
                                            'affectless, callous, heartless, inhumane, merciless, obdurate, pitiless, ruthless, unsparing, cold-blooded',
                                            'charitable, compassionate, humane, kindhearted, merciful, tender'),
                                    TestWay('vt',
                                            '使变硬',
                                            'to become physically firm or solid',
                                            ["Great heat indurates clay. 高温使黏土变硬"],
                                            'concrete, congeal, firm, freeze, set, solidify',
                                            'liquefy, soften'),
                                    TestWay('vt',
                                            '使习惯于：使习惯于，如艰苦或尴尬之境况',
                                            'to make able to withstand physical hardship, strain, or exposure',
                                            ["Such a brutal upbringing could only callous his soul and indurate his heart to the suffering of others. 这样一种残暴的培养方式只会让他的灵魂变得麻木，让他的心灵对于他人所受的折磨无动于衷"],
                                            'fortify, inure, season, steel, strengthen, toughen',
                                            'enfeeble, weaken, undermine')]),
                              Word('industrious', "",
                                   [TestWay('adj',
                                            '勤勉的',
                                            'constantly, regularly, or habitually occupied, diligent',
                                            ["The industrious PhD spends all his summer holiday in the laboratory. 勤奋的博士整个暑假都在做实验"],
                                            'assiduous, busy, diligent, sedulous',
                                            'indolent, lazy, slothful',
                                            'industriousness n. 勤奋')]),
                              Word('ineffable', "",
                                   [TestWay('adj',
                                            '难以表达的',
                                            'incapable of being expressed',
                                            ["ineffable ecstasy 无法用语言表达的狂喜"],
                                            'indefinable, indescribable, inexpressible, unspeakable, unutterable',
                                            'communicable, expressible',
                                            'ineffability n. 不可描述性')]),
                              Word('ineluctable', "",
                                   [TestWay('adj',
                                            '无法逃避的，必然的',
                                            'not to be avoided, changed, or resisted',
                                            ["Although death is an ineluctable fate for any and every individual organism, it lays the foundation of the metabolism that perpetuates the planetary ecosystem. 尽管死亡对于任何单个的有机体而言是不可避免的宿命，但它奠定了能使整个行星生态系统永不衰竭的新陈代谢的基础"],
                                            'certain, inescapable, inevasible, inevitable, unavoidable',
                                            'avoidable, evadable, uncertain, unsure',
                                            'ineluctability n. 不可避免')]),
                              Word('inept', "",
                                   [TestWay('adj',
                                            '愚笨的，荒谬的',
                                            'displaying a lack of judgment, sense, or reason',
                                            ["an inept and irresponsible remark on his paper 对他文章的荒谬而不负责任的评论"],
                                            'absurd, foolish, fatuous, preposterous, stupid, witless, unwise',
                                            'judicious, prudent sagacious, sapient, smart, wise'),
                                    TestWay('adj',
                                            '不恰当的，不合时宜的',
                                            'not appropriate for a particular occasion or situation',
                                            synonyms = 'amiss, graceless, improper, inapposite, infelicitous, malapropos, perverse, unseemly, unsuitable',
                                            antonyms = 'appropriate, becoming, felicitous, fitting, genteel, proper, seemly, suitable'),
                                    TestWay('adj',
                                            '不称职的，无能力的',
                                            'generally incompetent',
                                            ["a hopelessly inept defense attorney 严重不靠谱的辩护律师"],
                                            'incapable, inexpert, unfitted, unskillful, unqualified',
                                            'capable, competent, proficient, masterful',
                                            'ineptitude n. 不合适')]),
                              Word('inert', "",
                                   [TestWay('adj',
                                            '（人）懒惰缺乏活力的；（物品）惰性的',
                                            'sluggish in action or motion; deficient in active properties',
                                            ["inert ingredients in drugs 药品中的惰性成分"],
                                            'dead, dormant, lethargic, idle, inactive, passive, torpid',
                                            'active, dynamic, passionate',
                                            'inertia n. 惰性')]),
                              Word('inevitable', "",
                                   [TestWay('adj',
                                            '不可避免的，必然的',
                                            'incapable of being avoided or evaded',
                                            ["The impact of the scandal on the election was inevitable. 丑闻对于选举的冲击是不可避免的"],
                                            'certain, ineluctable, inescapable, inevasible, sure, unalterable, unavoidable',
                                            'evitable, avoidable, uncertain, unsure',
                                            'inevitability n. 必然性')]),
                              Word('inexorable', "",
                                   [TestWay('adj',
                                            '无法劝阻的，不为所动的',
                                            'not to be persuaded, moved, or stopped',
                                            ["the seemingly inexorable rise in unemployment 看起来无法阻止其高攀的失业率"],
                                            'inflexible, adamant, obdurate, relentless, rigid, unyielding',
                                            'flexible, yielding',
                                            'inexorably adv. 势不可挡地')]),
                              Word('infamous', "",
                                   [TestWay('adj',
                                            '臭名昭著的',
                                            'having an extremely and deservedly bad reputation',
                                            ["an infamous city for smuggling and prostitution 因走私而和卖淫而臭名昭著的城市"],
                                            'notorious, opprobrious',
                                            'distinguished, esteemed, prestigious, reputable',
                                            'infamy n. 声名狼藉')]),
                              Word('infatuate', "",
                                   [TestWay('vt',
                                            '使迷恋',
                                            'to inspire with unreasoning love or attachment',
                                            ["a naïve girl infatuated by cajolery 被甜言蜜语冲昏头脑的天真女孩"],
                                            'allure, captivate, bewitch, enchant, fascinate',
                                            'disgust',
                                            'infatuation n. 迷恋')])])

list13_unit6 = VocabularyList([Word('inferno', "",
                                   [TestWay('n',
                                            '大火',
                                            'an intense fire',
                                            ["A raging inferno posed a serious threat to the downwind villages. 肆虐的大火给下风向的村庄带来了严重的威胁"],
                                            'conflagration, holocaust'),
                                    TestWay('n',
                                            '地狱',
                                            'a place or a state that resembles or suggests hell',
                                            ["the inferno of war 地狱般的战场"],
                                            'hell, underworld',
                                            'paradise, heaven, nirvana')]),
                              Word('infiltrate', "",
                                   [TestWay('vt',
                                            '秘密潜入',
                                            'to enter or take up positions in gradually or surreptitiously, as for purposes of espionage or takeover',
                                            ["The intelligence staff had been infiltrated by spies. 情报工作人员已经被间谍渗透了"],
                                            'creep, insinuate, penetrate, sneak, slip',
                                            'abscond',
                                            'infiltration n. 潜入，渗透')]),
                              Word('infinite', "",
                                   [TestWay('adj',
                                            '无尽的，无限的',
                                            'having no boundaries or limits',
                                            ["the idea of an infinite universe 无限宇宙的概念"],
                                            'endless, boundless, limitless, immeasurable, unfathomable',
                                            'finite, bounded, circumscribed, confined, definite, limited, restricted',
                                            'infinity n. 无限')]),
                              Word('infirm', "",
                                   [TestWay('adj',
                                            '虚弱的',
                                            'weak in body, especially from old age or disease',
                                            ["her aging, infirm husband 她上了年纪、身体虚弱的丈夫"],
                                            'debilitated, effete, enervated, feeble, frail, languid, sapped, unsubstantial',
                                            'hale, mighty, powerful, rugged, stalwart, stout, strong'),
                                    TestWay('adj',
                                            '不果断的，优柔寡断的',
                                            'lacking firmness of will, character, or purpose',
                                            ["She has little patience with the “infirm of purpose”. 她对那些优柔寡断的人没什么耐心"],
                                            'faltering, irresolute, vacillating, wavering',
                                            'resolute')]),
                              Word('inflame', "",
                                   [TestWay('v',
                                            '点燃',
                                            'to set on fire',
                                            ["A carelessly tossed cigarette inflamed the papers in the trash can. 一只被随意丢弃的香烟点燃了垃圾桶中的纸"],
                                            'enflame, enkindle, fire, ignite, kindle, light, torch',
                                            'douse, extinguish, quench, put out'),
                                    TestWay('v',
                                            '使加剧',
                                            'to make more violent',
                                            ["Retaliation served only to inflame the feud. 冤冤相报何时了"],
                                            'aggravate, enrage, exacerbate, intensify, ire, irritate, provoke, rile, vex',
                                            'assuage, mitigate, mollify, pacify, placate, subdue')]),
                              Word('infelicitous', "",
                                   [TestWay('adj',
                                            '不愉快的，不幸的',
                                            'not happy; unfortunate',
                                            ["an infelicitous moment 不幸的时刻"],
                                            'hapless, ill-fated, luckless, unfortunate, unhappy',
                                            'happy'),
                                    TestWay('adj',
                                            '不适当的，不合时宜的',
                                            'not appropriate or well-timed',
                                            ["made a very infelicitous remark 做出极不恰当的评价"],
                                            'inappropriate, indecorous, inept, malapropos, unfit, unseemly',
                                            'apt, appropriate, becoming, proper',
                                            'infelicity n. 不恰当')]),
                              Word('influx', "",
                                   [TestWay('n',
                                            '涌入',
                                            'a coming in',
                                            ["They anticipated an influx of tourists next month. 他们预期下个月会有大批游客涌入"],
                                            'affluence, flux, income, inflow, inpouring, inrush',
                                            'exodus, outflow, outpouring')]),
                              Word('infuse', "",
                                   [TestWay('vt',
                                            '灌输，使…充满',
                                            'to fill or cause to be filled with something',
                                            ["New members infused enthusiasm into the club. 新队员为俱乐部注入了激情"],
                                            'endue, imbue, implant, ingrain, instill, permeate, suffuse, steep',
                                            'extract'),
                                    TestWay('vt',
                                            '鼓舞',
                                            'inspire, animate',
                                            ["a sense of purpose that infuses scientific researchers 给科学研究者打鸡血一般的使命感"],
                                            'animate, exalt, motivate, stimulate',
                                            other_form = 'infusion n. 注入')]),
                              Word('infuriate', "",
                                   [TestWay('vt',
                                            '激怒',
                                            'to make furious',
                                            ["be infuriated by the deliberate insults 被蓄意的中伤激怒"],
                                            'aggravate, enrage, exasperate, incense, ire, madden, umbrage',
                                            'appease, assuage, pacify, placate, propitiate, delight, gratify, please',
                                            'infuriated adj. 被激怒的')]),
                              Word('ingenious', "",
                                   [TestWay('adj',
                                            '聪明的，有创造才能的',
                                            'marked by originality, resourcefulness, and cleverness in conception or execution',
                                            ["Ingenious designers soon came up with a solution to the battery problem. 聪明的设计者们很快便提出了电池问题的解决方案"],
                                            'artful, clever, imaginative, innovative, inventive, original',
                                            'awkward, uncreative, unimaginative')])])

list13_unit7 = VocabularyList([Word('ingenuity', "",
                                   [TestWay('n',
                                            '独创性，创新性',
                                            'inventive skill or imagination',
                                            ["There is little ingenuity in his articles. 他的文章鲜有独创性"],
                                            'creativeness, innovativeness, inventiveness, originality',
                                            'banality, cliché',
                                            'ingenuous adj. 真挚的')]),
                              Word('ingenuous', "",
                                   [TestWay('adj',
                                            '天真淳朴的',
                                            'lacking in cunning, guile, or worldliness',
                                            ["Photographs captured the ingenuous smiles of young children at play. 摄影家捕捉到了演出中孩子们天真无邪的笑脸"],
                                            'artless, innocent, guileless, naïve, simple, unaffected, unpretending, unsophisticated',
                                            'artful, cunning, sly 狡猾的；assuming, hypocritical, sophisticated, worldly'),
                                    TestWay('adj',
                                            '坦白的',
                                            'openly straightforward or frank',
                                            ["her ingenuous thirst for knowledge 她对知识毫不掩饰的渴望"],
                                            'candid, frank, open, plain, unconcealed',
                                            'ambiguous, equivocal, evasive')]),
                              Word('ingest', "",
                                   [TestWay('vt',
                                            '摄入，咽下',
                                            'to take into the body by the mouth for digestion or absorption',
                                            ["claims that the average person ingests considerably more calories than is necessary or desirable 宣称每个人平均摄取的卡路里大大超出了所需或者适当的范围"],
                                            'eat, consume, devour, intake',
                                            'evacuate, expel 排出；vomit 呕吐',
                                            'ingestion n. 摄取')]),
                              Word('ingrained', "",
                                   [TestWay('adj',
                                            '本质的，根深蒂固的',
                                            'forming a part of the essence or inmost being; firmly established',
                                            ["ingrained prejudice against foreigners 对外国人根深蒂固的偏见"],
                                            'constitutional, immanent, inborn, indigenous, inherent, innate, intrinsic',
                                            'adventitious, extraneous, extrinsic',
                                            'ingrain v. 灌输，使根深蒂固')]),
                              Word('ingratiating', "",
                                   [TestWay('adj',
                                            '讨人喜欢的',
                                            'capable of winning favor',
                                            ["They adopted the orphan who had a most ingratiating smile. 他们收养了那名有着最惹人喜欢的笑容的孤儿"],
                                            'disarming, endearing, insinuating, winsome',
                                            'disagreeable'),
                                    TestWay('adj',
                                            '逢迎的，意在奉承的',
                                            'intended or adopted in order to gain favor',
                                            ["an repulsive ingratiating smile 令人反感的阿谀奉承的微笑"],
                                            'adulatory, deferential, fawning, flattering, toady',
                                            'ingratiate v. 讨好')]),
                              Word('inherent', "",
                                   [TestWay('adj',
                                            '内在的，本质的',
                                            'involved in the constitution or essential character of something',
                                            ["a disposition inherent in human nature 人性内在的倾向"],
                                            'constitutional, elemental, essential, inborn, ingrained, innate, intrinsic',
                                            'adventitious, extraneous, extrinsic',
                                            'inherently adv. 内在地')]),
                              Word('inimical', "",
                                   [TestWay('adj',
                                            '带有敌意的',
                                            'reflecting or indicating hostility',
                                            ["a cold, inimical voice 冰冷而不友好的声音"],
                                            'antagonistic, hostile, opposing, unfriendly',
                                            'amiable, amicable, friendly, hospitable, amenable'),
                                    TestWay('adj',
                                            '危及某人利益的，不利的',
                                            "opposed to one's interests",
                                            ["Laws were designed to enhance national security but some regard as inimical to cherished freedoms. 法律旨在维护国家安全，但有人认为它危及了人们最为珍贵的权力——自由"],
                                            'counter, disadvantageous, negative, prejudicial, unfavorable',
                                            'advantageous, favorable, positive, supportive, well-disposed')]),
                              Word('inimitable', "",
                                   [TestWay('adj',
                                            '无法仿效的，独特的',
                                            'not capable of being imitated',
                                            ["her own inimitable style 她特立独行的作风"],
                                            'incomparable, matchless, peerless, unique, unparalleled',
                                            'commonplace, ordinary',
                                            'inimitability n. 独特性')]),
                              Word('iniquity', "",
                                   [TestWay('n',
                                            '邪恶，不公正',
                                            'gross immorality or injustice',
                                            ["The use of illegal narcotics is not only a destroyer of personal health but also an iniquity that undermines our society. 非法的毒品不仅仅摧残着个人健康，还是一颗危害社会的毒瘤"],
                                            'corruption, depravity, debauchery, evil, infamy, sin, unfairness, wickedness',
                                            'integrity, rectitude, virtue, disinterestedness')]),
                              Word('initiate', "",
                                   [TestWay('vt',
                                            '创始，发动促进',
                                            'to cause or facilitate the beginning of',
                                            ["a chain reaction initiated by UV irradiation 紫外光激发引起的连锁反应"],
                                            'begin, start, commence, inaugurate, introduce, launch',
                                            'terminate'),
                                    TestWay('n',
                                            '刚入门的新手',
                                            'a person who is undergoing or has undergone an initiation',
                                            synonyms = 'apprentice, beginner, novice, rookie, tyro',
                                            antonyms = 'veteran',
                                            other_form = 'initiative n./adj. 主动性，首创精神')])])

list13_unit8 = VocabularyList([Word('inkling', "",
                                   [TestWay('n',
                                            '轻微暗示，小提示',
                                            'a slight indication or suggestion',
                                            ["They hadn't given us an inkling of what was going to happen. 他们不给我们任何暗示将会发生什么"],
                                            'clue, cue, hint'),
                                    TestWay('n',
                                            '略知',
                                            'a slight knowledge or vague notion',
                                            ["not have even the faintest inkling of what the project was all about 对这个项目与什么有关毫不知情"],
                                            'glimmer, 略知',
                                            'insight, 深刻理解')]),
                              Word('innocuous', "",
                                   [TestWay('adj',
                                            '无害的',
                                            'producing no injury',
                                            ["The government enacted a more strict regulation on innocuous preservatives. 政府对无害防腐剂制定了更为严格的规定"],
                                            'anodyne, benign, harmless, inoffensive, nontoxic, safe',
                                            'damaging, detrimental, harmful, injurious, noxious, pernicious'),
                                    TestWay('adj',
                                            '乏味的，不会引起敌意的',
                                            'not likely to give offense or to arouse strong feelings or hostility',
                                            ["He made an innocuous remark to avoid conflict. 为了避免冲突，他做了一个中庸的评价"],
                                            'bland, inoffensive, insipid, neutral, sapless',
                                            'provoking')]),
                              Word('innovative', "",
                                   [TestWay('adj',
                                            '创新性的',
                                            'characterized by, tending to, or introducing innovations',
                                            ["an innovative macro-economic strategy 创新性的宏观经济战略"],
                                            'creative, ingenious, inventive, original',
                                            'conservative, hidebound',
                                            'innovation n. 创新')]),
                              Word('inquisitive', "",
                                   [TestWay('adj',
                                            '过分好奇的',
                                            'inordinately or improperly curious about the affairs of others',
                                            ["big sunglasses to frustrate inquisitive journalists 让狗仔队企图无法得逞的大墨镜"],
                                            'curious, inquiring, investigative, prying',
                                            'indifferent , unconcerned, uninterested, incurious',
                                            'inquisitiveness n. 好奇')]),
                              Word('insensible', "",
                                   [TestWay('adj',
                                            '无知觉的',
                                            'having lost consciousness, especially temporarily',
                                            ["The security guard was knocked insensible by a sudden blow. 保安被突如其来的一击敲晕了"],
                                            'anesthetic, insensate, senseless, unfeeling, unconscious',
                                            'conscious'),
                                    TestWay('adj',
                                            '漠不关心的',
                                            'not emotionally responsive',
                                            ["insensible to workers’ requests 对工人的要求无动于衷"],
                                            'apathetic, bloodless, callous, dull, impassive, indifferent, nonchalant, phlegmatic',
                                            'concerned'),
                                    TestWay('adj',
                                            '粗俗的，没品味的',
                                            'lacking in refinement or good taste',
                                            ["She married an insensible brute upon whom the niceties of life were completely lost. 她嫁给了一个毫无品味的凡夫俗子，从此她的生活再无任何情趣"],
                                            'crass, crude, incult, lowbred, tasteless, uncouth, uncultivated, uncultured, unpolished, unrefined, vulgar',
                                            'civilized, cultivated, cultured, genteel, polished, refined, smooth, tasteful')]),
                              Word('insensitive', "",
                                   [TestWay('adj',
                                            '缺乏机智圆滑的，缺乏社交技巧的',
                                            'lacking tact',
                                            ["so insensitive as to laugh at someone in pain 如此缺乏社交技巧以至于嘲笑处于悲痛中的人"],
                                            'gauche, impolite, insensible, tactless',
                                            'considerate'),
                                    TestWay('adj',
                                            '不敏感的，麻木的',
                                            'not responsive or susceptible',
                                            ["insensitive to either criticism or commendation 对批评和表扬都不在乎"],
                                            'anesthetized, dead, numb, senseless, unfeeling',
                                            'sensitive, tender')]),
                              Word('insentient', "",
                                   [TestWay('adj',
                                            '无感觉，无知觉的',
                                            'lacking perception, consciousness, or animation',
                                            ["He refused to believe that the universe as we know it evolved from the random interactions of insentient particles of matter. 他拒绝相信我们所知的宇宙是经由无生命的粒子间的相互作用演化而来的"],
                                            'impassive, insensate, insensible, senseless, unresponsive',
                                            'perceiving, sensible, sensitive'),
                                    TestWay('adj',
                                            '一知半解的，略懂的',
                                            'not having or showing a deep understanding of something',
                                            ["an insentient therapist who failed to see what the teenager's real problem was 一个对这名青少年的真正问题所在一知半解的医生"],
                                            'impercipient, unwise',
                                            'discerning, insightful, sagacious, sage, sapient')]),
                              Word('insight', "",
                                   [TestWay('n',
                                            '深刻的理解',
                                            'an instance of apprehending the true nature of a thing, especially through intuitive understanding',
                                            ["an insight into the global-scale environmental problems 对于全球性环境问题的深刻理解"],
                                            'discernment, insight, perception, sagacity, sapience',
                                            'glimmer, inkling',
                                            'insightful adj. 有洞察力的')]),
                              Word('insipid', "",
                                   [TestWay('adj',
                                            '（食品）清淡无味的',
                                            'lacking flavor or zest; not tasty',
                                            ["a rather insipid soup 味道清淡的汤"],
                                            'flat, flavorless, mild, sapless, savorless, tasteless',
                                            'piquant'),
                                    TestWay('adj',
                                            '平淡的，无聊的',
                                            'lacking in qualities that interest, stimulate, or challenge',
                                            ["an insipid story of the prince and the princess 一个关于王子和公主的无聊故事"],
                                            'banal, bland, driveling, prosaic, tedious, uninteresting, vapid',
                                            'enchanting')]),
                              Word('insolent', "",
                                   [TestWay('adj',
                                            '粗野的，无礼的',
                                            'audaciously rude or disrespectful',
                                            ["an insolent child with no respect or regard for anyone 对他人不敬的无礼的小孩"],
                                            'arrogant, audacious, bold, haughty, supercilious, impertinent, impudent',
                                            'courteous, polite, respectful, meek, mousy, timid',
                                            'insolence n. 无礼')])])

list13_unit9 = VocabularyList([Word('insouciant', "",
                                   [TestWay('adj',
                                            'insouciant',
                                            'free from concern, worry, or anxiety',
                                            ["an insouciant shrug 无所谓地耸耸肩"],
                                            'carefree, casual, indifferent, nonchalant, unconcerned',
                                            'anxious, careworn, concerned, worried',
                                            'insouciance n. 不在乎')]),
                              Word('instate', "",
                                   [TestWay('vt',
                                            '任命',
                                            'to set or establish in a rank or office',
                                            ["The new Secretary of the Treasury was instated on Monday. 新的财政部长于星期一被任命"],
                                            'appoint, designate, inaugurate, induct, install, nominate',
                                            ['dismiss', 'oust'])]),
                              Word('instigate', "",
                                   [TestWay('vt',
                                            '煽动, 激起',
                                            'to goad or urge forward; to stir up',
                                            ["This incident is instigated by a small group of people with ulterior motives. 此次事件是被少数别有用心的人煽动起来的"],
                                            'abet, arouse, excite, foment, goad, incite, inflame, provoke, stir',
                                            'assuage, allay, mitigate, mollify, pacify, soothe',
                                            'nstigation n. 煽动')]),
                              Word('instill', "",
                                   [TestWay('v',
                                            '慢慢滴入',
                                            'to cause to enter drop by drop',
                                            ["instill medication into the infected eye 将药物滴入患者受感染的眼中"],
                                            ['inject'],
                                            ['extract']),
                                    TestWay('v',
                                            '灌输',
                                            'to impart gradually',
                                            ["instill a sense of responsibility to the young 向年轻人灌输一种责任感"],
                                            'breed, enroot, implant, inculcate, infix, infuse, ingrain, plant, sow',
                                            ['remove'],
                                            'instillation n. 滴入')]),
                              Word('institute', "",
                                   [TestWay('vt',
                                            '创立, 制定',
                                            'to establish, organize, and set in operation',
                                            ["institute a new department 创建一个新的部门"],
                                            'begin, constitute, create, found, inaugurate, launch, start, set up',
                                            'abrogate, efface, rescind, close, shut, phase out'),
                                    TestWay('n',
                                            '机构',
                                            'an organization for the promotion of a cause',
                                            ["a research institute 研究机构"],
                                            'association, institution, society',
                                            other_form = 'institution n. 习俗, 制度')]),
                              Word('insubordinate', "",
                                   [TestWay('adj',
                                            '不服从权威的',
                                            'not submissiveto authority',
                                            ["Insubordinate soldiers are court-martialed. 抗命的士兵被送上了军事法庭"],
                                            'balky, contumacious, intractable, mutinous, recalcitrant, rebellious, refractory',
                                            'amenable, docile, obedient, ruly, submissive, tractable')]),
                              Word('insular', "",
                                   [TestWay('adj',
                                            '（观念、想法等）孤立狭隘的',
                                            'being, having, or reflecting a narrow provincial viewpoint',
                                            ["the insular thinking of peasant communities 农民阶级的狭隘思想"],
                                            'confined, local, narrow, parochial, provincial, regional, restricted',
                                            ['cosmopolitan', 'ecumenical', '有国际视野的', 'catholic', '（兴趣等）广泛的', 'receptive', '善于接受的'])]),
                              Word('insulate', "",
                                   [TestWay('vt',
                                            '使绝缘, 使隔离',
                                            'to place in a detached situation',
                                            ["greenhouse gas that insulates ground infrared radiation 能阻碍地表红外辐射的温室气体"],
                                            'block, insolate, quarantine, seclude, segregate, separate, sequester',
                                            'connect, link, unite, integrate',
                                            'insulation n. 隔绝, 绝热')]),
                              Word('insurgent', "",
                                   [TestWay('n',
                                            '叛乱分子: ',
                                            'one who breaks with or opposes constituted authority or the established order',
                                            ["Insurgents armed with assault rifles and grenades ambushed a US convoy, resulting in heavy casualties. 持有突击步枪和手榴弹的叛乱分子偷袭了美军车队, 造成重大伤亡"],
                                            'rebel, anarchist, antagonist, malcontent, mutineer',
                                            other_form = 'insurgency n. 叛乱')]),
                              Word('intangible', "",
                                   [TestWay('adj',
                                            '无法感知的, 无形的',
                                            'incapable of being perceived by the senses',
                                            ["intangible value of a good reputation 良好声誉的无形价值"],
                                            'impalpable, imperceptible, imponderable, inappreciable, indiscernible, insensible, invisible',
                                            'corporeal, palpable, tactile, tangible, touchable')])])

list13_unit10 = VocabularyList([Word('integral', "",
                                   [TestWay('adj',
                                            '构成整体所必需的',
                                            'essential to completeness',
                                            ["an integral part of the undergraduate curriculum 本科生课程的必修部分"],
                                            'critical, essential, indispensable, necessary, requisite, vital',
                                            'redundant, superfluous, surplus'),
                                    TestWay('adj',
                                            '完整的',
                                            'not lacking any part or member that properly belongs to it',
                                            ["the belief that athletics are essential to an integral life 坚信运动是完整的人生所不可或缺的一部分"],
                                            'comprehensive, entire, full, grand, intact, perfect, plenary, total, whole',
                                            'imperfect, incomplete, partial')]),
                              Word('integrity', "",
                                   [TestWay('n',
                                            '正直',
                                            'steadfast adherence to a strict moral or ethical code, devotion to telling the truth',
                                            ["After a thorough investigation into “Climategate”, the panel concluded that the integrity of scientific community is still sound. 经过对“气候门事件”的彻底调查, 专家组认为学术界的信誉和道德仍然是值得信赖的"],
                                            'conscience, honesty, incorruptibility, rectitude, righteousness, scrupulousness',
                                            'baseness, deceit, deceitfulness, dishonesty, lying, mendacity, untruthfulness'),
                                    TestWay('n',
                                            '完整性',
                                            'the quality or condition of being whole or undivided',
                                            ["trying to maintain the integrity of the falling empire 尽力维持日趋西山的帝国的统一"],
                                            'completeness, entireness, perfection, wholeness')]),
                              Word('intelligible', "",
                                   [TestWay('adj',
                                            '可理解的',
                                            'capable of being understood',
                                            ["military codenames intelligible only to those high-rank commanding officers 只有高级指挥官才能理解的军事暗号"],
                                            'accessible, apprehensible, comprehensible, fathomable, lucid, understandable',
                                            'abstruse, recondite, inscrutable, insensible',
                                            'intelligibility n. 可理解性')]),
                              Word('intemperate', "",
                                   [TestWay('adj',
                                            '无节制的, 极端的, 不温和的',
                                            'not temperate or moderate',
                                            ["The tone of the article is very intemperate. 文章的论调很极端"],
                                            'excessive, extreme, immoderate, inordinate, overindulgent, unrestrained',
                                            'equable, bridled, checked, constrained, controlled, curbed, governed, hampered, hindered, trammeled')]),
                              Word('intensify', "",
                                   [TestWay('vt',
                                            '加强, 激化',
                                            'to make intense or more intensive',
                                            ["Both companies intensified their efforts to win the contract. 为了获得这份合同, 两家公司都加大了投入"],
                                            'accentuate, aggravate, amplify, deepen, enhance, magnify, redouble, strengthen',
                                            'abate, assuage, attenuate, mitigate, moderate',
                                            'intensity n. 强度')]),
                              Word('inter', "",
                                   [TestWay('vt',
                                            '埋葬',
                                            'to place in a grave or tomb',
                                            ["The infamous terrorist leader Bin Laden was interred at sea. 臭名昭著的恐怖分子本拉登被葬于海中"],
                                            'bury, entomb, inhume',
                                            'dig, disinter, excavate, exhume, unearth')]),
                              Word('intercessor', "",
                                   [TestWay('n',
                                            '调停者',
                                            'one that mediates',
                                            ["attend the meeting as the intercessor 作为调停人出席会议"],
                                            'broker, buffer, conciliator, intermediate, mediator, peacemaker',
                                            ['flame-fanner', '煽风点火的人'],
                                            'intercession n. 调停, 斡旋')]),
                              Word('interdict', "",
                                   [TestWay('vt',
                                            '禁止',
                                            'to forbid in a usually formal or authoritative manner',
                                            ["Though not interdicted by law, such an action is morally wrong. 尽管这种行为不被法律所禁止, 但是道德上来说是不对的"],
                                            'ban, forbid, prohibit, proscribe',
                                            'authorize, allow, permit, suffer, approve, endorse, ratify, sanction'),
                                    TestWay('vt',
                                            '阻止',
                                            'to stop, seize, or interrupt while in progress or on course',
                                            ["Federal agents are able to interdict only a small percentage of the narcotic shipments into the country. 联邦调查员们只能阻止一小部分流入国内的毒品"],
                                            'bar, block, check, hinder, intercept, impede, obstruct',
                                            ['expedite'],
                                            'interdiction n. 禁止, 封锁')]),
                              Word('interim', "",
                                   [TestWay('n',
                                            '中间过渡时期, 间隔',
                                            'an interval of time between one event, process, or period and another',
                                            ["Richard Wagner’s operas usually require an interim of more than 30 minutes for performers to have a break. 理查德·瓦格纳的歌剧通常需要长达30 多分钟的幕间休息时间以供演员调整"],
                                            'breach, break, gap, interruption, interval, interlude, parenthesis',
                                            'continuation, continuity'),
                                    TestWay('adj',
                                            '暂时的',
                                            'serving in a position for the time being',
                                            ["an interim government to maintain social stability 维持社会稳定的临时政府"],
                                            'acting, provisional, temporary',
                                            'eternal, permanent')]),
                              Word('interlock', "",
                                   [TestWay('vi',
                                            '连锁',
                                            'to become united or joined closely, as by hooking or dovetailing',
                                            ["The branches of the trees interlock to form a natural archway. 树枝相互缠绕在一起, 形成了天然的拱门"],
                                            'associate, connect, join, link, unite',
                                            ['sunder'],
                                            'interlocking adj. 连锁的')])])

LIST13 = VocabularyList(list13_unit1.words+list13_unit2.words+list13_unit3.words+list13_unit4.words+list13_unit5.words+list13_unit6.words+list13_unit7.words+list13_unit8.words+list13_unit9.words+list13_unit10.words)
