#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list26_unit1 = VocabularyList([Word('topsy-turvy', "",
                                   [TestWay('adj',
                                            '混乱的',
                                            'lacking in order, neatness, and often cleanliness',
                                            ["He left his room topsy-turvy. 他把他的房间弄的很乱。"],
                                            'disordered, chaotic, messy, anarchic, jumbled',
                                            'kempt, neat, orderly, organized, shipshape, tidy, trim, uncluttered, well-ordered')]),
                              Word('torpid', "",
                                   [TestWay('adj',
                                            '麻木的, 没有知觉的',
                                            'lacking in sensation or feeling',
                                            ["My tongue and throat remained torpid for a time following the endoscopy. 胃镜检查之后, 我的舌头和喉咙一直是麻木的。"],
                                            'asleep, benumbed, dead, insensitive, numbed, unfeeling',
                                            'feeling, sensible, sensitive'),
                                    TestWay('adj',
                                            '迟钝的, 行动迟缓的',
                                            'slow to move or act',
                                            ["a torpid sloth that refused to budge off its tree branch 趴在树枝上一动不动的树獭"],
                                            'dull, inert, lethargic, quiescent, sleepy, sluggish, torpid',
                                            'active')]),
                              Word('torpor', "",
                                   [TestWay('n',
                                            '缺乏兴趣',
                                            'lack of interest or concern',
                                            ["After a lifetime of setbacks, defeats, and failures, he could only greet the latest bad news with a resigned fatalism and dull torpor. 一生都充满了挫折、失败, 他只能用宿命论和麻木不仁来迎接又一次的坏消息。"],
                                            'apathy, casualness, complacence, disinterestedness, disregard, incuriosity, insouciance, nonchalance',
                                            'concern, interest, regard'),
                                    TestWay('n',
                                            '(肉体或精神上的)迟钝',
                                            'physical or mental inertness',
                                            ["Following Thanksgiving dinner, we spent the rest of the day lounging about in a contented torpor. 吃完感恩节晚餐后, 我们慵懒地靠在沙发上打发剩下的时间。"],
                                            'languor, lassitude, listlessness, stupor',
                                            'vigor, vim, vitality, vivacity')]),
                              Word('torrential', "",
                                   [TestWay('adj',
                                            '急流的',
                                            'caused by or resulting from action of rapid streams',
                                            ["a torrential rain 倾盆大雨"],
                                            antonyms = 'trickling')]),
                              Word('torrid', "",
                                   [TestWay('adj',
                                            '酷热的',
                                            'intensely hot',
                                            ["the dry, torrid summers in southern Arizona 南亚利桑那州干燥、炎热的夏天"],
                                            'hot, scalding, scorching, sweltering',
                                            'arctic, bone-chilling, freezing, frigid, frozen, glacial, icy'),
                                    TestWay('adj',
                                            '热情的, 情感深厚的',
                                            'having or expressing great depth of feeling',
                                            ["torrid love affair 炙热的爱"],
                                            'ardent, burning, fervid, flaming, glowing, impassioned, incandescent, intense, passionate, vehement',
                                            'dispassionate, emotionless, impassive, unemotional')]),
                              Word('tortuous', "",
                                   [TestWay('adj',
                                            '转弯抹角的',
                                            'marked by devious or indirect tactics: crooked, tricky',
                                            ["a tortuous path 一条蜿蜒的道路"],
                                            'bending, curling, curvy, devious, serpentine, sinuous, twisted, windy',
                                            'direct, straightforward')]),
                              Word('tout', "",
                                   [TestWay('vt',
                                            '极力赞扬',
                                            'to promote or praise energetically; publicize',
                                            ["to tout victory in the war 鼓吹战果"],
                                            'acclaim, laud, praise, ballyhoo, tout',
                                            'asperse, censure, denounce, berate, rate, revile, vituperate')]),
                              Word('toy', "",
                                   [TestWay('vi',
                                            '草率或不认真地对待',
                                            'to handle thoughtlessly, ignorantly, or mischievously',
                                            ["That microscope is a delicate instrument, not something to be toyed with. 那个显微镜是精密仪器, 不是随随便便的一个玩具。"],
                                            'diddle with, fiddle with, fool with, mess with, monkey with, tinker with, twiddle with')]),
                              Word('tractable', "",
                                   [TestWay('adj',
                                            '易驾驭的, 温顺的',
                                            'readily giving in to the command or authority of another',
                                            ["a tractable horse 一匹温顺的马"],
                                            'obedient, amenable, docile, flexible, manageable, compliant, submissive, tame',
                                            'balky, contumacious, defiant, disobedient, incompliant, insubordinate, obstreperous, rebellious, recalcitrant, refractory, restive, unamenable, ungovernable, unruly, untoward, wayward, willful')]),
                              Word('tranquility', "",
                                   [TestWay('n',
                                            '宁静, 淡定',
                                            'a state of freedom from storm or disturbance',
                                            ["enjoyed the tranquillity of the snow-covered field at dusk 享受傍晚时分被雪覆盖的田野的静谧"],
                                            'calm, quiet, silence, serenity',
                                            'bustle, commotion, hubbub, pandemonium, tumult, turmoil, unquietness, unrest, uproar')])])

list26_unit2 = VocabularyList([Word('transcend', "",
                                   [TestWay('vt',
                                            '超越, 超过极限',
                                            'to rise above or go beyond the limits of',
                                            ["a person who believes that any true understanding of God transcends human intelligence 认为对上帝的真正理解是超越人类智商极限的人"],
                                            'break, outreach, outrun, overpass, overreach, overrun, overshoot, overstep, surpass')]),
                              Word('transfigure', "",
                                   [TestWay('vt',
                                            '改变外观',
                                            'to alter the outward appearance of; transform',
                                            ["transfigure the AutoCAD drawings with elegant symbols 用优美的符号使AutoCAD图变得美观"],
                                            'alchemize, metamorphose, transform, transmute, transpose, transubstantiate, make over')]),
                              Word('transgress', "",
                                   [TestWay('vt',
                                            '违背, 犯错',
                                            'to fail to keep; to commit an offense',
                                            ["don't even think about transgressing the drug laws of that Asian country, for punishments are severe and there's nothing that our government can do to intervene 别指望违背亚洲国家的药品相关法, 因为惩罚非常严厉, 政府会尽全力干涉"],
                                            'breach, break, contravene, fracture, infringe, offend, traduce',
                                            'follow, mind, obey, observe, comply with, conform to')]),
                              Word('transient', "",
                                   [TestWay('adj',
                                            '短暂的, 瞬时的',
                                            'passing with time; transitory',
                                            ["transient pleasure 短暂的快乐"],
                                            'transitory, ephemeral, evanescent, fleeting, temporary',
                                            'ceaseless, dateless, deathless, endless, enduring, eternal, everlasting, immortal, lasting, long-lived, permanent, perpetual, timeless, undying, unending')]),
                              Word('transitory', "",
                                   [TestWay('adj',
                                            '短暂的',
                                            'existing or lasting only a short time; short-lived or temporary',
                                            ["most of life’s joys are transitory 尘世间的欢乐都是过眼烟云, 转瞬即逝"],
                                            'transient, ephemeral, evanescent, fleeting, temporary',
                                            'ceaseless, dateless, deathless, endless, enduring, eternal, everlasting, immortal, lasting, long-lived, permanent, perpetual, timeless, undying, unending')]),
                              Word('translucent', "",
                                   [TestWay('adj',
                                            '透明的',
                                            'permitting the passage of light: clear, transparent',
                                            ["translucent dewdrop 透明的露珠"],
                                            'transparent, limpid, pellucid, lucent, lucid, transpicuous',
                                            'opaque')]),
                              Word('transparent', "",
                                   [TestWay('adj',
                                            '透明的',
                                            'capable of transmitting light',
                                            synonyms = 'translucent, limpid, pellucid, lucent, lucid, transpicuous',
                                            antonyms = 'cloudy, opaque'),
                                    TestWay('adj',
                                            '没有歧义, 清晰易懂的',
                                            'not subject to misinterpretation or more than one interpretation',
                                            ["His meaning in leaving the conversation is transparent: he doesn't want to talk about his combat experiences. 他结束这个话题的意图很明显: 不想谈论当年参战的事。"],
                                            'obvious, clear, apparent, patent, understandable, apprehensible, comprehendible, fathomable',
                                            'ambiguous, clouded, cryptic, enigmatic, equivocal, indistinct, mysterious, obfuscated, obscure, unapparent, unclarified, unclear, unclouded')]),
                              Word('travail', "",
                                   [TestWay('n./v.',
                                            '辛苦劳动',
                                            'work, especially when arduous or involving painful effort',
                                            ["writer’s literary travail 作家辛勤的文学创作", "Labor Day is the day on which we recognize those men and women who daily travail with little appreciation or compensation. 劳动节是我们向那些平日辛勤劳作但是很少受到大家关注和补偿的工人致敬的日子。"],
                                            'drudgery, fatigue, grind')]),
                              Word('traverse', "",
                                   [TestWay('vt',
                                            '横穿',
                                            'to travel or pass across, over, or through',
                                            ["The spider traversed the wall from end to end. 蜘蛛侠攀岩走壁"],
                                            'course, cover, cross, cut across, navigate, pass over, perambulate, peregrinate, proceed along, transit, travel')]),
                              Word('travesty', "",
                                   [TestWay('n./v',
                                            '拙劣的、嘲弄性模仿',
                                            'an exaggerated or grotesque imitation, such as a parody of a literary work',
                                            ["a travesty of his classmate’s manner 滑稽的模仿其他同学的举止"],
                                            'caricature, burlesque, parody, spoof, mock',
                                            'paragon')])])

list26_unit3 = VocabularyList([Word('treacherous', "",
                                   [TestWay('adj',
                                            '背叛的',
                                            'marked by betrayal of fidelity, confidence, or trust',
                                            ["a treacherous ally 不忠的盟友"],
                                            'faithless, disloyal, perfidious, recreant, traitorous, unfaithful, unloyal, betraying',
                                            'constant, dedicated, devoted, staunch, down-the-line, faithful, fast, loyal, steadfast, steady, true')]),
                              Word('trenchant', "",
                                   [TestWay('adj',
                                            '锐利的',
                                            'keen, sharp',
                                            ["Even the most trenchant sword could not sever the bonds of loyalty between them. 即使最锋利的刀剑也不能切断他们的忠诚。"],
                                            'keen, sharp',
                                            'blunt, blunted, dull, obtuse'),
                                    TestWay('adj',
                                            '(言辞)一针见血的',
                                            'vigorously effective and articulate',
                                            ["trenchant criticisms 一针见血的批评"],
                                            'incisive',
                                            'vague')]),
                              Word('trepidation', "",
                                   [TestWay('n',
                                            '恐惧, 战栗',
                                            'the emotion experienced in the presence or threat of danger; apprehension',
                                            ["trepidation about starting a new career 对开创一项新事业而感到恐惧"],
                                            'fear, fright, horror, apprehension',
                                            'boldness, bravery, dauntlessness, intrepidity')]),
                              Word('trespass', "",
                                   [TestWay('vi',
                                            '非法侵入, 违反',
                                            'to commit an offense',
                                            ["I consider him to be trespassing against all of us when he trespasses against any one of us. 当他冒犯我们当中一个人的时候, 他就冒犯了我们全部"],
                                            'transgress, invade, intrude',
                                            'withdraw, retreat')]),
                              Word('tribute', "",
                                   [TestWay('n',
                                            '颂词',
                                            'a gift, payment, declaration, or other acknowledgment of gratitude, respect, or admiration',
                                            ["pay a high tribute to… 赞颂"],
                                            'accolade, eulogy, encomium, panegyric, tribute',
                                            'denunciation, condemnation, criticism, censure, reproof, reprobation')]),
                              Word('trickle', "",
                                   [TestWay('vi',
                                            '一滴滴地流, 徐徐地流',
                                            'to issue or fall in drops',
                                            ["Tears trickled down her cheeks. 眼泪从她的脸上一滴一滴地流下。"],
                                            'pour, roll, stream, gush')]),
                              Word('trite', "",
                                   [TestWay('adj',
                                            '陈腐的, 陈词滥调的',
                                            'hackneyed or boring from much use, not fresh or original',
                                            ["“You win some, you lose some” is a trite expression. “有得必有失”是老生常谈了。"],
                                            'bathetic, cliché, hackneyed, threadbare, timeworn, banal',
                                            'fresh, new, novel, original, unclichéd, unhackneyed')]),
                              Word('trivial', "",
                                   [TestWay('adj',
                                            '琐碎的, 无足轻重的',
                                            'of little worth or importance',
                                            ["why spend so much time on trivial decisions, like whether the cola should be regular or diet? 为什么花这么多时间在这种琐碎的决定上, 比如可乐要喝一般的还是健怡？"],
                                            'inconsiderable, insignificant, minor, petty, inconsequential, paltry, trifling',
                                            'consequential, material, momentous, weighty, indispensable, substantive, grandiose, massive')]),
                              Word('truant', "",
                                   [TestWay('adj./n./vi',
                                            '逃避责任的',
                                            'shirking responsibility; one who shirks duty',
                                            ["play truant 逃学"],
                                            'shirk, malinger, goldbrick, avoid, escape, evade, parry, sidestep, circumvent, fence, hedge, avert, elude, shun, skirt, dodge, bilk, eschew',
                                            'dutiful')]),
                              Word('truce', "",
                                   [TestWay('n',
                                            '休战, 休战协定',
                                            'a suspension of fighting especially of considerable duration by agreement of opposing forces',
                                            ["truce agreement 休战协议"],
                                            'armistice, cease-fire, peace')])])

list26_unit4 = VocabularyList([Word('truculent', "",
                                   [TestWay('adj',
                                            '尖酸刻薄的',
                                            'marked by harsh insulting language',
                                            ["a theater critic who was notorious for his titanically truculent reviews 一个以超大量尖酸刻薄言论著称的话剧评论家"],
                                            'contumelious, invective, opprobrious, scurrilous, vitriolic, vituperative'),
                                    TestWay('adj',
                                            '好战的',
                                            'feeling or displaying eagerness to fight',
                                            ["in an aggressively truculent manner 以好战的, 进攻性的方式"],
                                            'belligerent, bellicose, combative, militant, aggressive, feisty',
                                            'nonaggressive, nonbelligerent, pacific, peaceable, peaceful, uncombative, uncontentious')]),
                              Word('trudge', "",
                                   [TestWay('vi',
                                            '吃力而笨拙地走',
                                            'to move heavily or clumsily',
                                            ["trudge over hill 翻山越岭"],
                                            'plod, lug, slog, flounder',
                                            'breeze, glide, slide, waltz, whisk, flit')]),
                              Word('trumpet', "",
                                   [TestWay('v',
                                            '大声说出或宣告',
                                            'to make known openly or publicly',
                                            ["The losing party lost no time in trumpeting allegations of election fraud. 落败的政党马不停蹄地开始公开宣称选举存在作假。"],
                                            'advertise, annunciate, blare, broadcast, declare, proclaim, promulgate, release, give out')]),
                              Word('truncate', "",
                                   [TestWay('v',
                                            '截短(时间, 程度)',
                                            'to shorten by or as if by cutting off',
                                            ["a truncated version of the 11 o'clock newscast followed the awards show, which ran over its time slot 颁奖典礼之后缩短版的11点新闻节目, 已经超出了预定时长"],
                                            'abbreviate, abridge, curtail, retrench',
                                            'elongate, extend, lengthen, prolong, protract')]),
                              Word('truss', "",
                                   [TestWay('v',
                                            '系紧, 扎紧',
                                            'to gather into a tight mass by means of a line or cord',
                                            ["After stuffing the turkey, the chef quickly trussed it so the forcemeat wouldn't fall out during roasting. 把填料塞进火鸡后, 大厨迅速把它扎紧防止在烘烤过程中肉馅掉出来。"],
                                            'band, bind',
                                            'unbind, untie')]),
                              Word('tumult', "",
                                   [TestWay('n',
                                            '骚动, 暴动',
                                            'a disorderly commotion or disturbance, a riot',
                                            ["His mind was in a tumult. 他心烦意乱。"],
                                            'disorder, disturbance, commotion, convulsion, ferment, turmoil, pandemonium, uproar',
                                            'quietude, quiescence, serenity, tranquility')]),
                              Word('turbid', "",
                                   [TestWay('adj',
                                            '混浊的',
                                            'deficient in clarity or purity',
                                            ["a turbid stream 一条混浊的河"],
                                            'muddy, murky, obscure',
                                            'clear , limpid, lucid, pellucid, , crystalline')]),
                              Word('turbulent', "",
                                   [TestWay('adj',
                                            '动荡的',
                                            'marked by sudden or violent disturbance',
                                            ["a turbulent period in history 历史上动荡时期"],
                                            'cataclysmal, stormy, tempestuous, tumultuous'),
                                    TestWay('adj',
                                            '湍急的, 汹涌的',
                                            'marked by turmoil or disturbance especially of natural elements',
                                            ["the turbulent rapids of the river were certainly daunting to those of us who were new to river rafting 湍急的流水必定让那些初玩漂流的人们吓得不轻"],
                                            'rough, rugged, stormy, tempestuous')]),
                              Word('turgid', "",
                                   [TestWay('adj',
                                            '浮夸的, 过分装饰的',
                                            'excessively embellished in style or language',
                                            ["turgid prose 浮华的散文"],
                                            'flatulent, bombastic, pompous',
                                            'simple, austere, unadorned, undecorated, unembellished')]),
                              Word('turmoil', "",
                                   [TestWay('n',
                                            '骚动, 混乱',
                                            'a state or condition of extreme confusion, agitation, or commotion',
                                            ["My mind is in a turmoil. 我心里很乱。"],
                                            'commotion, agitation, tumult, turbulence, disorder, ferment, clamor',
                                            'calm, ease, peace, peacefulness, quiet, tranquility, silence, serenity')])])

list26_unit5 = VocabularyList([Word('turncoat', "",
                                   [TestWay('n',
                                            '叛徒',
                                            'one who switches to an opposing side or party; specifically: traitor',
                                            ["He was labeled as a turncoat. 他是一个叛徒。"],
                                            'renegade, traitor, apostate, recreant, betrayer, quisling',
                                            'loyalist, partisan, adherent, supporter')]),
                              Word('turpitude', "",
                                   [TestWay('n',
                                            '卑鄙',
                                            'inherent baseness: depravity',
                                            ["moral turpitude 道德上的卑鄙行为"],
                                            'abjection, corruptness, debasement, debauchery, decadency, degeneration, degradation, demoralization, depravity, dissipatedness, dissoluteness, libertinism, perversion, rakishness',
                                            'probity')]),
                              Word('twig', "",
                                   [TestWay('v',
                                            '了解',
                                            'to have a clear idea of',
                                            ["It took me a while to twig the true nature of the relationship between the two women. 我花了很久时间才搞清楚这俩女人之间的关系。"],
                                            'appreciate, apprehend, cognize, compass, conceive, decipher, decode, dig, discern, perceive, recognize, savvy, seize, sense, tumble to, catch on to, make out')]),
                              Word('typo', "",
                                   [TestWay('n',
                                            '打字错误',
                                            'an error in typed or typeset material',
                                            ["make one typo on the memo 在样张上打错一个字"],
                                            'misprint, bug')]),
                              Word('tyro', "",
                                   [TestWay('n',
                                            '新手, 业余爱好者',
                                            'a beginner in learning: novice',
                                            ["a tyro in the art of piano 钢琴界的新手"],
                                            'novice, apprentice, neophyte, rookie, amateur, dabbler, dilettante, fledgling, recruit',
                                            'old hand, old-timer, vet, expert, professional, veteran')]),
                              Word('ubiquitous', "",
                                   [TestWay('adj',
                                            '无所不在的, 普通的',
                                            'being everywhere at the same time; often observed or encountered',
                                            ["The conflict between opposites is ubiquitous. 对立的冲突无所不在。"],
                                            'omnipresent, universal, general, common',
                                            'extraordinary, infrequent, rare, seldom, uncommon, unfamiliar, unusual, unique, particular')]),
                              Word('unassailable', "",
                                   [TestWay('adj',
                                            '无可争辩的, 无法否认的, 不可亵渎的',
                                            'not to be violated, criticized, or tampered with',
                                            ["an unassailable article 无可争辩的文章"],
                                            'undeniable, inviolable, sacrosanct , irrefutable, indisputable, unexceptionable, unimpeachable',
                                            'controversial')]),
                              Word('uncanny', "",
                                   [TestWay('adj',
                                            '离奇的, 奇异的',
                                            'being so extraordinary or abnormal as to suggest powers which violate the laws of nature',
                                            ["The silence was uncanny. 静得出奇"],
                                            'magical, miraculous, phenomenal, preternatural, superhuman, supernormal, transcendent, transcendental, uncanny, unearthly',
                                            'ordinary, commonplace, normal')]),
                              Word('uncouth', "",
                                   [TestWay('adj',
                                            '粗俗的, 没有品位的',
                                            'lacking in refinement or good taste',
                                            ["the movie's uncouth humor seemed to be purposely offensive 电影里一些恶俗的幽默貌似是故意的"],
                                            'crass, rude, discourteous, disgracious, ungraceful, crude, ill-bred, ill-mannered, uncivil, unrefined',
                                            'genteel, cultivated, cultured, polished, urbane, seemly')]),
                              Word('unctuous', "",
                                   [TestWay('adj',
                                            '油嘴滑舌的, 谄媚的',
                                            'overly or insincerely flattering',
                                            ["an unctuous appraisal of the musical talent shown by the boss's daughter 拍老板马屁, 说他女儿音乐剧的才能非常卓越"],
                                            'adulatory, gushing, hagiographic, oily, oleaginous, soapy'),
                                    TestWay('adj',
                                            '夸张的, 做作的',
                                            'characterized by affected, exaggerated, or insincere earnestness',
                                            ["an unctuous effort to appear religious to the voters 过分做作想在选民面前表现地虔诚"],
                                            'artificial, backhanded, counterfeit, fake, feigned, hypocritical, phony, pretended',
                                            'artless, candid, genuine, heartfelt, honest, sincere, undesigning, unfeigned')])])

list26_unit6 = VocabularyList([Word('underdog', "",
                                   [TestWay('n',
                                            '受害者, 输家',
                                            'a loser/ victim or predicted loser in a struggle or contest',
                                            ["She always supports for the underdog. 她经常支持受害者。"],
                                            'loser, victim',
                                            'bully')]),
                              Word('undergird', "",
                                   [TestWay('vt',
                                            '加强, 巩固…的底部',
                                            'to support or strengthen from beneath',
                                            ["facts and statistics undergird his commentary 事实和数据支持了他的评论"],
                                            'strengthen, support, fortify, reinforce, bear, bolster, brace, buttress, carry, stay, sustain, underpin, uphold, prop up, shore up',
                                            'undermine, weaken, debilitate, enfeeble, enervate')]),
                              Word('undermine', "",
                                   [TestWay('vt',
                                            '削弱, 破坏',
                                            'to weaken, injure, or impair, often by degrees or imperceptibly',
                                            ["undermine a fortress 挖地道破坏堡垒"],
                                            'undermine, weaken, debilitate, enfeeble, enervate',
                                            'strengthen, support, fortify, reinforce')]),
                              Word('underscore', "",
                                   [TestWay('vt',
                                            '强调',
                                            'to emphasize; stress',
                                            ["underscore the value of education 强调教育的重要性"],
                                            'accentuate, italicize, stress, underline, bring out',
                                            'deemphasize, downplay')]),
                              Word('understate', "",
                                   [TestWay('vt',
                                            '保守陈述',
                                            'to state or present with restraint especially for effect',
                                            ["understate a problem 低调处理问题"],
                                            'downplay',
                                            'vaunt, exaggerate, overstate',
                                            'understated adj. 朴素的: avoiding obvious emphasis or embellishment 【近】conservative, low-key, muted, repressed, restrained, sober, subdued, unflashy, unpretentious 【反】flamboyant, flaring, flashy, garish, gaudy, glitzy, ostentatious, splashy 夸张的, 华丽的')]),
                              Word('understudy', "",
                                   [TestWay('n',
                                            '替补演员',
                                            "one who is prepared to act another's part or take over another's duties",
                                            ["be an understudy to sb 作为某人的替补"],
                                            'deputy')]),
                              Word('unexceptionable', "",
                                   [TestWay('adj',
                                            '无懈可击的',
                                            'not open to objection or criticism, beyond reproach',
                                            synonyms = 'unassailable, undeniable, irrefutable, indisputable, unexceptionable, unimpeachable',
                                            antonyms = 'assailable, controversial')]),
                              Word('unflappable', "",
                                   [TestWay('adj',
                                            '镇定的, 从容不迫的',
                                            'not easily upset or excited',
                                            ["a unflappable general 一个镇定的将军"],
                                            'collected, composed, disimpassioned, imperturbable',
                                            'perturbable, shakable, disturbed, nervous')]),
                              Word('ungainly', "",
                                   [TestWay('adj',
                                            '笨拙的, 不雅的',
                                            'having or showing an inability to move in a graceful manner',
                                            ["ungainly movements 笨拙的动作"],
                                            'clumsy, awkward, blundering, maladroit',
                                            'coordinated, graceful, adroit, dexterous, lissome')]),
                              Word('unimpeachable', "",
                                   [TestWay('adj',
                                            '无可置疑的',
                                            'beyond doubt; unquestionable',
                                            ["An unimpeachable evidence 无可置疑的证据"],
                                            'unassailable, undeniable, irrefutable, indisputable, unexceptionable, unimpeachable',
                                            'assailable, controversial, open to question')])])

list26_unit7 = VocabularyList([Word('unkempt', "",
                                   [TestWay('adj',
                                            '凌乱的, 无序的',
                                            'lacking in order, neatness, and often cleanliness',
                                            ["unkempt hotel rooms 凌乱的酒店房间"],
                                            'slovenly, slipshod, sloppy, unneat, untidy, topsy-turvy, jumbled',
                                            'bandbox, neat, orderly, organized, shipshape, tidy, trim, uncluttered, well-ordered')]),
                              Word('unlettered', "",
                                   [TestWay('adj',
                                            '未受教育的, 文盲的',
                                            'not adept at reading and writing; deficient in the knowledge that can be acquired from books. illiterate',
                                            ["unlettered sector of society 未受教育的地区"],
                                            'ignorant, illiterate, uneducated, untutored',
                                            'educated, knowledgeable, erudite, literate, schooled, well-informed, well-read')]),
                              Word('unpretentious', "",
                                   [TestWay('adj',
                                            '低调的, 谦逊的',
                                            'lacking pretension or affectation; modest',
                                            ["an unpretentious virtuoso 一位谦虚的大师"],
                                            'demure, down-to-earth, lowly, meek, unassuming, humble, modest, unostentatious',
                                            'arrogant, bumptious, conceited, egotistic, fastuous, haughty, imperious, lordly, overweening, peremptory, pompous, presuming, presumptuous, self-asserting, supercilious, superior, toplofty, uppish, flamboyant, ostentatious'),
                                    TestWay('adj',
                                            '坦诚的, 自然的',
                                            'free from any intent to deceive or impress others',
                                            ["a simple and unpretentious account about growing up in the rural South 一段简单坦率的关于在南部乡村成长经历的叙述"],
                                            'artless, genuine, honest, ingenuous, innocent, naive, simple, sincere, true, unpretending',
                                            'affected, artful, artificial, assuming, dissembling, dissimulating, fake, guileful, insincere, phony')]),
                              Word('unproductive', "",
                                   [TestWay('adj',
                                            '徒然的, 无效的',
                                            'not productive; idle',
                                            ["her attempts to write a novel have been unproductive 她一直想写本小说的努力只是徒然"],
                                            'abortive, barren, fruitless, otiose, profitless, unavailing, unprofitable, unsuccessful, useless, vain',
                                            'deadly, effective, effectual, efficacious, efficient, potent, productive, profitable, successful, virtuous, telling')]),
                              Word('unrequited', "",
                                   [TestWay('adj',
                                            '无报答的, 无报酬的',
                                            'not reciprocated or returned in kind',
                                            ["unrequited love 无报答的爱"],
                                            'unreciprocated',
                                            'remunerative, gainful, lucrative, profitable')]),
                              Word('unruly', "",
                                   [TestWay('adj',
                                            '难驾驭的, 不守规矩的',
                                            'difficult or impossible to discipline, control, or rule.',
                                            ["an unruly child 一个不听话的孩子"],
                                            'indocile, indomitable, intractable, recalcitrant, uncontrollable, undisciplined, ungovernable, unmanageable, insubordinate',
                                            'amenable, biddable, compliant, conformable, docile, obedient, submissive, tractable, subdued, mild, manageable, disciplined')]),
                              Word('untenable', "",
                                   [TestWay('adj',
                                            '防守不住的, 站不住脚的',
                                            'not able to be defended',
                                            ["an untenable position 一个站不住脚的立场"],
                                            'assailable, controversial, open to question',
                                            'unassailable, undeniable, irrefutable, indisputable, unexceptionable, unimpeachable')]),
                              Word('untold', "",
                                   [TestWay('adj',
                                            '数不清的, 无数的',
                                            'too great or numerous to count',
                                            ["untold wealth 不知其数的财富"],
                                            'incalculable, innumerable, countless, innumerous, uncountable, uncounted',
                                            'countable, enumerable, numberable, quantifiable, calculable')]),
                              Word('untoward', "",
                                   [TestWay('adj',
                                            '倒霉的, 不吉利的',
                                            'not favorable, unpropitious',
                                            ["an untoward incident 不幸的事故"],
                                            'unpropitious, unlucky, misfortunate, unfortunate',
                                            'auspicious, propitious, favorable, fortunate'),
                                    TestWay('adj',
                                            '难以驯服的, 难以驾驭的',
                                            'given to resisting control or discipline by others',
                                            ["a program for untoward teenagers that is designed to give them the kind of discipline that their parents were unable or unwilling to administer 一个以任性、桀骜不驯青少年为对象的项目, 旨在弥补家长管教不周之处"],
                                            'froward, headstrong, intractable, recalcitrant, refractory, unruly, wayward, willful',
                                            'controllable, governable, manageable, tractable')]),
                              Word('unwitting', "",
                                   [TestWay('adj',
                                            '不知道的, 未觉察的',
                                            'not knowing, unaware',
                                            ["Please forgive my unwitting interruption of your conversation. 请原谅我无意间打断了你们的谈话。"],
                                            'unaware, ignorant',
                                            'acquainted, aware, cognizant, conscious, conversant, grounded, informed, knowing, mindful'),
                                    TestWay('adj',
                                            '偶然的, 并非有意的',
                                            'happening by chance; not intended',
                                            ["an unwitting mistake made in copying the material 在打印过程中一个无心的过失"],
                                            'casual, chance, fluky, fortuitous, inadvertent, incidental, unintentional',
                                            'calculated, deliberate, intended, intentional, planned, premeditated, prepense')])])

list26_unit8 = VocabularyList([Word('unwonted', "",
                                   [TestWay('adj',
                                            '不习惯的, 不寻常的',
                                            'not habitual or ordinary; unusual',
                                            ["honored for the unwonted courage he showed in battle 因在战争中表现出的过人的勇气受到嘉奖"],
                                            'uncommon, unordinary, unusual',
                                            'wonted, usual, routine, habitual, accustomed, customary')]),
                              Word('upbraid', "",
                                   [TestWay('vt',
                                            '(严厉地)谴责, 责骂',
                                            'to reproach severely',
                                            ["upbraid sb. with his ingratitude 责备某人忘恩负义"],
                                            'baste, scold, revile, berate, vituperate',
                                            'laud, extol, glorify, hymn, magnify, panegyrize, flatter, fawn, cringe, adulate')]),
                              Word('uphold', "",
                                   [TestWay('vt',
                                            '支持, 赞成',
                                            'to give support to',
                                            ["determined to uphold her views in the face of all challenges 下定决心支持她的观点, 尽管全世界都反对她"],
                                            'support, bolster, advocate, champion, endorse, espouse')]),
                              Word('urbane', "",
                                   [TestWay('adj',
                                            '彬彬有礼的, 文雅的',
                                            'notably polite or finished in manner',
                                            ["a gentlemanly and urbane host of elegant dinner parties 优雅晚宴的主人有绅士风度, 彬彬有礼"],
                                            'debonair, civilized, genteel, cultivated, cultured, polished, refined, well-bred, courteous, gracious',
                                            'boorish, churlish, classless, clownish, loutish, uncouth')]),
                              Word('usurp', "",
                                   [TestWay('vt',
                                            '篡夺, 篡位',
                                            'to seize and hold (the power or rights of another, for example) by force and without legal authority',
                                            ["usurp the throne 篡夺王位"],
                                            'arrogate, commandeer, convert, expropriate, pirate, preempt, press, seize, take over',
                                            'abdicate, crown')]),
                              Word('utter', "",
                                   [TestWay('vt',
                                            '出声, 说话',
                                            'to articulate (words); pronounce or speak',
                                            ["She tried not to utter a sound as the doctor gave her a flu shot. 她克制自己不在打针的时候喊出来。"],
                                            'articulate, bring out, enunciate, verbalize, vocalize'),
                                    TestWay('adj',
                                            '完全的, 绝对的',
                                            'complete; absolute; entire',
                                            ["be at an utter loss what to do 完全不知道怎样才好"],
                                            'entire, total, stark, sheer, unqualified',
                                            'partial')]),
                              Word('vaccinate', "",
                                   [TestWay('v',
                                            '预防接种',
                                            'to inoculate with a vaccine in order to produce immunity to an infectious disease, such as diphtheria or typhus',
                                            ["vaccinate sb. for smallpox 为某人接种牛痘疫苗以防天花"],
                                            'immunize')]),
                              Word('vacillate', "",
                                   [TestWay('vi',
                                            '犹豫不决',
                                            'to waver in mind, will, or feeling: hesitate in choice of opinions or courses',
                                            ["Parents vacillate between saying no and yes, but actually neither response seems satisfactory to their children. 父母总是犹豫不定, 不知道是该同意还是该反对, 但是事实上哪种答案对他们的孩子都不理想。"],
                                            'hesitate, dither, waver, teeter, falter',
                                            'resolute, decide, dive in, plunge in'),
                                    TestWay('vi',
                                            '摇动, 摇摆',
                                            'to sway from one side to the other; oscillate',
                                            synonyms = 'oscillate, fluctuate',
                                            antonyms = 'equipoise')]),
                              Word('vacuous', "",
                                   [TestWay('adj',
                                            '茫然的, 愚蠢的',
                                            'marked by lack of ideas or intelligence',
                                            ["a movie that was derided for its vacuous dialogue 一部因为对白十分愚蠢而被嘲讽的电影"],
                                            'airhead, brainless, dull, dumb, fatuous, foolish, inane, moronic, obtuse, simple, stupid, witless',
                                            'apt, bright, brilliant, clever, intelligent, keen, sharp, smart',
                                            'vacuity n. 空虚, 空白')]),
                              Word('vagary', "",
                                   [TestWay('n',
                                            '不可预测的思想或行为',
                                            'an erratic, unpredictable, or extravagant manifestation, action, or notion',
                                            ["Recently he had been prone to strange vagaries. 最近他逐渐变得行为古怪起来。"],
                                            'caprice, fancy, freak, humor, vagrancy, whimsy')])])

list26_unit9 = VocabularyList([Word('vague', "",
                                   [TestWay('adj',
                                            '表达不清的',
                                            'not clearly expressed',
                                            ["The diplomat gave as vague a reply as he could at the press conference. 外交官在记者招待会上尽其所能来含糊其辞。"],
                                            'ambiguous, enigmatic, equivocal, indefinite, inexplicit, unclear',
                                            'clear, definite, express, explicit, specific'),
                                    TestWay('adj',
                                            '轮廓不清晰的',
                                            'lacking definite shape, form, or character',
                                            ["the vague outline of a building through the dense fog 浓雾中建筑物模糊的轮廓"],
                                            'dim, faint, foggy, hazy, indistinct, indistinguishable, misty, murky, nebulous, obscure, opaque',
                                            'pellucid')]),
                              Word('valediction', "",
                                   [TestWay('n',
                                            '告别',
                                            'an act of bidding farewell',
                                            synonyms = 'farewell, goodbye',
                                            antonyms = 'greeting, debut'),
                                    TestWay('n',
                                            '告别词',
                                            'an address or statement of farewell or leave-taking',
                                            ["a valediction given by the college president upon his retirement 大学校长退休时的告别演说"],
                                            other_form = 'valedictory adj. 告别的')]),
                              Word('valiant', "",
                                   [TestWay('adj',
                                            '勇敢的, 英勇的',
                                            'possessing or acting with bravery or boldness',
                                            ["a valiant and moral knight 一个勇敢和有道德感的骑士", "Despite their valiant efforts, they lost the game. 尽管他们英勇奋战, 但还是输掉了比赛。"],
                                            'audacious, bold, brave, courageous, dauntless, fearless, gallant, intrepid, stalwart, stout, valorous',
                                            'cowardly, craven, gutless, nerveless, pusillanimous, spineless, timorous',
                                            'valiance n. 英勇')]),
                              Word('valid', "",
                                   [TestWay('adj',
                                            '逻辑上正确的',
                                            'logically correct',
                                            ["Only further experiments will show whether your theory is valid. 只有进一步的实验才能验证你的理论是否正确。", "Your argument isn't valid because you're taking what should be the conclusion and using it as a premise. 你的论述逻辑上是错误的, 因为你把本该是结论的东西当成了前提条件。"],
                                            'analytic, coherent, consequent, rational, reasonable, sensible, sound, well-founded, well-grounded',
                                            'groundless, illegitimate, illogical, incoherent, inconsequent, invalid, irrational, unreasonable, unsound',
                                            'validity n.合乎逻辑')]),
                              Word('vanquish', "",
                                   [TestWay('vt',
                                            '打败, 征服',
                                            'to defeat in a conflict or contest',
                                            ["vanquished his inner fear 战胜了他内心的恐惧conquer, dominate, overpower, pacify, subdue, subject, subjugate, subordinate"],
                                            'conquer, dominate, overpower, pacify, subdue, subject, subjugate, subordinate',
                                            'capitulate, succor, surrender, yield')]),
                              Word('vapid', "",
                                   [TestWay('adj',
                                            '无趣的, 乏味的',
                                            'lacking liveliness, animation, or interest',
                                            ["a song with vapid lyrics 一首歌词乏味的歌曲"],
                                            'driveling, dull, flat, inane, insipid, jejune, sapless, tasteless',
                                            'absorbing, arresting, engaging, engrossing, enthralling, fascinating, immersing, intriguing, riveting')]),
                              Word('vaporize', "",
                                   [TestWay('vt',
                                            '使(液体)蒸发',
                                            'to convert (as by the application of heat or by spraying) into vapor',
                                            synonyms = 'gasify',
                                            antonyms = 'condense (气体)液化'),
                                    TestWay('vt',
                                            '彻底消灭',
                                            'to destroy by or as if by converting into vapor',
                                            ["The entire fleet was vaporized. 整个舰队都被消灭了。"],
                                            'annihilate, decimate, demolish, devastate, extinguish, nuke, pulverize, raze, ruin, smash, wreck',
                                            'build, construct, erect, establish, raise, rear',
                                            'vaporous adj. 模糊的, 空洞的')]),
                              Word('variance', "",
                                   [TestWay('n',
                                            '不一致, 不和谐',
                                            'a lack of agreement or harmony',
                                            ["Persistent variance within the band eventually caused it to break up. 乐团中持续不断的分歧最终导致了它的解散"],
                                            'conflict, disaccord, discordance, disharmony, dissent, division, friction, schism, variation, war',
                                            'accord, agreement, concord, concordance, harmony, peace',
                                            'variant adj. 变体的, 不同的')]),
                              Word('variegated', "",
                                   [TestWay('adj',
                                            '杂色的, 斑驳的',
                                            'having discrete markings of different colors',
                                            ["variegated costumes of the dancers in the nightclub 夜总会舞者身上色彩斑驳的服装"],
                                            'chromatic, kaleidoscopic, iridescent, motley, rainbow',
                                            'monochromatic, colorless',
                                            'variegation n. 杂色')]),
                              Word('varnish', "",
                                   [TestWay('vt',
                                            '上清漆, 使有光泽',
                                            'to give a smooth and glossy finish to',
                                            ["Don't sit on that chair - I've just varnished it. 不要坐在那张椅子上——我刚刚上过漆。"],
                                            'adorn, bedeck, bedizen, decorate, embellish, garnish, ornament'),
                                    TestWay('vt',
                                            '粉饰(令人不悦的东西)',
                                            'to cover or conceal (as something unpleasant) with something that gives an attractive appearance',
                                            ["She tried to varnish her mistakes. 她试图掩盖她的失误。"],
                                            'blanch, extenuate, gloss, palliate, sugarcoat, veneer',
                                            'bare, disclose, discover, divulge, expose, reveal, uncloak, uncover, unmask, unveil')])])

list26_unit10 = VocabularyList([Word('vault', "",
                                   [TestWay('vi',
                                            '跳起, 跳跃',
                                            'to propel oneself upward or forward into the air',
                                            ["The horse vaulted over the obstacle with ease. 骏马轻松地跃过障碍物。"],
                                            'bound, hop, jump, leap, spring'),
                                    TestWay('vi',
                                            '一跃而至',
                                            'to accomplish something as if by leaping suddenly or vigorously',
                                            ["She vaulted into a position of wealth. 她一夜暴富。"])]),
                              Word('vaunt', "",
                                   [TestWay('vi',
                                            '吹嘘',
                                            'to speak boastfully',
                                            ["vaunted his country’s military might 吹嘘他的国家的军事实力"],
                                            'boast, brag, brandish, swagger',
                                            'belittle, deprecate, diminish, minimize, underrate, undervalue',
                                            'vaunting adj. 吹嘘的')]),
                              Word('veer', "",
                                   [TestWay('v',
                                            '转向, 改变航线',
                                            'to change direction or course',
                                            ["He veered the car abruptly to the right to avoid a collision. 他向右猛打方向盘以避免撞击"],
                                            'avert, deviate, deflect, divert, redirect, swerve, swing, wheel',
                                            'straighten')]),
                              Word('vehement', "",
                                   [TestWay('adj',
                                            '(情感)强烈的, 热情的',
                                            'having or expressing great depth of feeling',
                                            ["a vehement defender of the rights of minorities 一个立场强烈的少数民族维权者"],
                                            'ardent, demonstrative, emotional, fervid, impassioned, intense, passionate, perfervid, torrid',
                                            'cold, cool, dispassionate, emotionless, impassive, unemotional',
                                            'vehemence n. 强烈')]),
                              Word('venal', "",
                                   [TestWay('adj',
                                            '容易贪污受贿的',
                                            'open to corrupt influence and especially bribery',
                                            ["a judge who is known for being venal and easily bought 一名因为贪污和容易收买而闻名的法官"],
                                            'bribable, corruptible, dirty, purchasable',
                                            'incorruptible, scrupulous')]),
                              Word('vendor', "",
                                   [TestWay('n',
                                            '小贩, 商贩',
                                            'one that sells or vends',
                                            ["We're thinking of making a deal with that other software vendor. 我们在考虑和那个软件供应商的交易"],
                                            'broker, dealer, merchandiser, retailer, seller, trader',
                                            'buyer, consumer, purchaser')]),
                              Word('veneer', "",
                                   [TestWay('n',
                                            '薄木板, 用以贴在家具外面的饰面板',
                                            'a thin surface layer, as of finely grained wood, glued to a base of inferior material',
                                            synonyms = 'cover, façade, mask',
                                            antonyms = 'center, core, kernel'),
                                    TestWay('vt',
                                            '粉饰(不好的东西)',
                                            'to cover over with a veneer; especially to conceal (as a defect of character) under a superficial and deceptive attractiveness',
                                            synonyms = 'blanch, extenuate, gloss, palliate, sugarcoat, varnish',
                                            antonyms = 'bare, disclose, discover, divulge, expose, reveal, uncloak, uncover, unmask, unveil')]),
                              Word('venerate', "",
                                   [TestWay('vt',
                                            '尊敬',
                                            'to regard with reverential respect or with admiring deference',
                                            ["She is venerated by the public as a saint. 她被当作圣人, 受万众景仰。"],
                                            'adore, deify, esteem, regard, respect, revere',
                                            'despise, disdain, disregard, flout, scorn',
                                            'veneration n. 尊敬')]),
                              Word('venial', "",
                                   [TestWay('adj',
                                            '可宽恕的',
                                            'easily excused or forgiven',
                                            ["Taking the restaurant's menu as a souvenir seems like a venial offense. 把餐厅的菜单当成纪念品带走似乎是一个可以宽恕的罪行。"],
                                            'condonable, excusable, forgivable, pardonable, remissible, remittable',
                                            'heinous, indefensible, inexcusable, mortal, unforgivable, unpardonable')]),
                              Word('venom', "",
                                   [TestWay('n',
                                            '毒液',
                                            'poisonous matter normally secreted by some animals as snakes, scorpions, or bees',
                                            ["an antidote to snake venom 蛇毒的解药"],
                                            'toxic, toxin',
                                            'antidote'),
                                    TestWay('n',
                                            '恶意, 恶毒的用心',
                                            'the desire to cause pain for the satisfaction of doing harm',
                                            ["She spoke of him with venom in her voice. 她的评论怀揣着恶意。"],
                                            'despite, malevolence, maliciousness, malignance, malignity, meanness, nastiness, spite, viciousness',
                                            'comity, friendship, goodwill')])])

LIST26 = VocabularyList(list26_unit1.words+list26_unit2.words+list26_unit3.words+list26_unit4.words+list26_unit5.words+list26_unit6.words+list26_unit7.words+list26_unit8.words+list26_unit9.words+list26_unit10.words)
