#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list14_unit1 = VocabularyList([Word('interminable', "",
                                   [TestWay('adj',
                                            '无尽头的',
                                            'having or seeming to have no end',
                                            ["A large audience fell asleep during the interminable sermon. 许多观众都在冗长的布道演说上睡着了"],
                                            'continual, ceaseless, endless, everlasting, perpetua',
                                            '')]),
                              Word('intermittent', "",
                                   [TestWay('adj',
                                            '间歇的, 断断续续的',
                                            'coming and going at intervals, not continuous',
                                            ["intermittent rain in June 六月里断断续续的梅雨"],
                                            'episodic, erratic, occasional, periodical, recurrent, recurring',
                                            'constant, continuous, incessant, unceasing 持续不断的'),
                                    TestWay('adj',
                                            '不定期的',
                                            'lacking in steadiness or regularity of occurrence',
                                            ["The husband’s intermittent employment put the family in a difficult position financially. 丈夫不稳定的工作使得全家陷入了经济上的困境"],
                                            'aperiodic, casual, catchy, discontinuous, irregular, occasional, spasmodic, sporadic, unsteady',
                                            'habitual, periodic, regular, repeated')]),
                              Word('interregnum', "",
                                   [TestWay('n',
                                            '过渡期',
                                            'break in continuity',
                                            ["The democratic regime proved to be a short-lived interregnum between dictatorships. 这个民主政权被证明只不过是两个独裁政权之间的短暂过渡罢"],
                                            'breach, break, gap, interim, interruption, interval, interlude, parenthesis',
                                            'continuation, continuity')]),
                              Word('interrogate', "",
                                   [TestWay('vt',
                                            '质问, 审问',
                                            'to question formally and systematically',
                                            ["interrogate the prisoner of war for valuable intelligence 审问战俘以获取有价值的情报"],
                                            'ask, grill, inquire, milk, question',
                                            'answer, reply, respond',
                                            'interrogation n. 审讯')]),
                              Word('intimate', "",
                                   [TestWay('adj',
                                            '有紧密联系的, 亲密无间的',
                                            'marked by very close association, contact, or familiarity',
                                            ["intimate friends since childhood 孩童时期以来的密友"],
                                            'familiar, close, confidential',
                                            'distant, remote'),
                                    TestWay('adj',
                                            '不为人知的',
                                            'not known or meant to be known by the general populace',
                                            ["They broke up after she shared intimate information with all 500 of her closest friends. 在她把那些不为人知的消息告诉了她500个朋友之后, 他们分手了"],
                                            'confidential, esoteric, nonpublic, secret',
                                            'open, public'),
                                    TestWay('n',
                                            '密友',
                                            'a person who has a strong liking for and trust in another',
                                            ["Usually quite aloof in public, he's actually quite relaxed with his intimates. 通常他在大众面前显得比较孤傲, 但和好朋友在一起时他却是个很放松的人"],
                                            'acquaintance, amigo, comrade, confidant, friend, insider, mate',
                                            'stranger, enemy, foe'),
                                    TestWay('v',
                                            '迂回地交流, 间接地沟通',
                                            'to communicate delicately and indirectly',
                                            ["intimate a wish to leave 暗示想离开"],
                                            'allude, connote, hint, imply, indicate, infer, suggest',
                                            'articulate'),]),
                              Word('intimidate', "",
                                   [TestWay('vt',
                                            '威吓',
                                            'to make timid or fearful, frighten',
                                            ["refused to be intimidated by the manager 对经理的恐吓不为所动"],
                                            'browbeat, bully, coerce, cow, frighten, hector, terrify',
                                            'blandish, cajole, coax',
                                            'intimidation n. 恐吓')]),
                              Word('intoxicant', "",
                                   [TestWay('n',
                                            '使人陶醉的东西(尤指酒精饮料)',
                                            'an agent that intoxicates, especially an alcoholic beverage',
                                            synonyms = 'alcohol, liquor, stimulant',
                                            antonyms = 'refresher',
                                            other_form = 'intoxicating adj. 使人陶醉的')]),
                              Word('intransigent', "",
                                   [TestWay('adj',
                                            '不妥协的, 固执的',
                                            'characterized by refusal to compromise or to abandon an extreme position',
                                            ["an intransigent attitude 不妥协的态度"],
                                            'adamant, headstrong, intractable, obstinate, pertinacious, stubborn, uncompromising, unyielding',
                                            'compliant, pliable, tractable, yielding',
                                            'intransigence n. 顽固')]),
                              Word('intrepid', "",
                                   [TestWay('adj',
                                            '无畏的',
                                            'characterized by resolute fearlessness, fortitude, and endurance',
                                            ["an intrepid explorer 无畏的探险家"],
                                            'audacious, brave, bold, courageous, dauntless, fearless, gallant, valiant, valorous',
                                            'apprehensive, cowardly, craven, gutless, pusillanimous, timorous',
                                            'intrepidity n. 无所畏惧')]),
                              Word('intrigue', "",
                                   [TestWay('n',
                                            '阴谋',
                                            'a secret plan for accomplishing evil or unlawful ends',
                                            ["The intrigue was quickly discovered, and the would-be assassins were arrested. 随着阴谋的迅速识破, 未得手的刺客被逮捕了"],
                                            'conspiracy, design, intrigue, machination, scheme'),
                                    TestWay('vt',
                                            '激起…的兴趣',
                                            'to arouse the interest, desire, or curiosity of',
                                            ["The children are apparently intrigued by the tale. 孩子们很明显被这个传奇故事吸引了"],
                                            'appeal, attract, enthrall, entice, excite, fascinate, interest, occupy',
                                            'ennui, pall',
                                            'intriguing adj. 有趣的')])])

list14_unit2 = VocabularyList([Word('intrinsic', "",
                                   [TestWay('adj',
                                            '固有的, 内在的',
                                            'of or relating to the essential nature of a thing',
                                            ["the intrinsic worth of a gem 宝石的内在价值"],
                                            'congenial, constitutional, immanent, inborn, inherent, innate, native, natural',
                                            'adventitious, extraneous, extrinsic')]),
                              Word('intuitive', "",
                                   [TestWay('adj',
                                            '直觉的',
                                            'knowing or perceiving by intuition',
                                            ["The twins have an intuitive awareness of each other's feelings. 这对双胞胎天生就能感知彼此的感受"],
                                            'instinctive',
                                            'acquired',
                                            'intuition n. 直觉')]),
                              Word('inundate', "",
                                   [TestWay('vt',
                                            '淹没',
                                            'to cover with or as if with flood',
                                            ["inundated with trash e-mails 被垃圾邮件所淹没"],
                                            'avalanche, deluge, drown, engulf, overflow, overwhelm, submerge',
                                            'drain',
                                            'inundation n. 淹没')]),
                              Word('inure', "",
                                   [TestWay('vt',
                                            '使习惯接受不好的东西',
                                            'to accustom to accept something undesirable',
                                            ["children inured to violence 习惯了暴力的孩子们"],
                                            'accustom, familiarize, habituate',
                                            other_form = 'inured adj. 习惯的'),
                                    TestWay('vt',
                                            '使坚强',
                                            'to make able to withstand physical hardship, strain, or exposure',
                                            ["The hardship of army training inured her to the rigors of desert warfare. 军营里的艰苦训练把她打造成了能适应沙漠艰苦战事的女兵"],
                                            'fortify, indurate, season, steel, strengthen, toughen',
                                            'enfeeble, soften, weaken, undermine')]),
                              Word('invective', "",
                                   [TestWay('adj',
                                            '侮辱性的',
                                            'of, relating to, or characterized by insult or abuse',
                                            ["invective comments on female activists 对女权主义者的侮辱性评论"],
                                            'abusive, opprobrious, scurrile, scurrilous, truculent, vitriolic, vituperative',
                                            'adulatory, flattery, complimentary')]),
                              Word('inveigh', "",
                                   [TestWay('vi',
                                            '激烈抗议, 表示强烈不满',
                                            'to protest or complain bitterly or vehemently',
                                            ["inveighed against the bank industry 对银行业表示强烈不满"],
                                            'gripe, grouse, object, protest, remonstrate, repine',
                                            'support, delight, rejoice')]),
                              Word('inveigle', "",
                                   [TestWay('vt',
                                            '诱骗',
                                            'to win over by coaxing, flattery, or artful talk',
                                            ["inveigle consumers into buying the item 诱骗顾客购买商品"],
                                            'allure, bait, decoy, entice, entrap, seduce, tempt',
                                            'demand',
                                            'inveigling adj. 诱骗性的')]),
                              Word('inventory', "",
                                   [TestWay('n',
                                            '存货清单',
                                            "a detailed, itemized list, report, or record of things in one's possession, especially a periodic survey of all goods and materials in stock",
                                            ["The dealership has an unusually large inventory of pre-owned vehicles. 销售商手中有着一份巨大的二手车库存单"],
                                            'budget, pool, repertoire, reservoir, stock'),
                                    TestWay('n',
                                            '(写有要点的)简介',
                                            'a short statement of the main points',
                                            ["They decided to offer the public an informative inventory of everything that is known about the virus at this time. 他们决定向公众提供一份极富价值的报告, 它涵盖了目前为止关于这种病毒的所有认识"],
                                            'abstract, brief, epitome, outline, résumé, summarization, synopsis')]),
                              Word('inveterate', "",
                                   [TestWay('adj',
                                            '积习的',
                                            'firmly established by long persistence',
                                            ["the inveterate tendency to overlook the obvious 总是忽视显而易见事物的习惯"],
                                            'chronic, entrenched, ingrained, rooted, settled, hard-cored',
                                            'adventitious')]),
                              Word('invidious', "",
                                   [TestWay('adj',
                                            '惹人反感的',
                                            'tending to cause discontent, animosity, or envy',
                                            ["the invidious task of arbitration 令人反感的仲裁任务"],
                                            'abhorrent, detestable, obnoxious, odious, repugnant, repellent',
                                            'agreeable, gratifying, pleasant'),
                                    TestWay('',
                                            '羡慕嫉妒恨的',
                                            "having or showing mean resentment of another's possessions or advantages",
                                            ["Inevitably, his remarkable success attracted the invidious attention of the other sales representatives. 不可避免地, 他巨大的成功引来了其他销售代表羡慕嫉妒恨的眼光"],
                                            'covetous, envious, jaundiced, jealous, resentful, green-eyed')])])

list14_unit3 = VocabularyList([Word('invigorate', "",
                                   [TestWay('vt',
                                            '使精神, 使强壮, 鼓舞激励',
                                            'to impart vigor, strength, or vitality to',
                                            ["news that invigorates the public 给大众打鸡血的新闻"],
                                            'animate, energize, fortify, reinforce, strengthen, vitalize',
                                            'dampen, deaden, debilitate, emaciate, sap, demoralize',
                                            'invigorated adj. 精力充沛的')]),
                              Word('invincible', "",
                                   [TestWay('adj',
                                            '不可战胜的, 不可超越的',
                                            'incapable of being conquered, overcome, or subdued',
                                            ["The soccer team proved to be invincible. 这支球队证明了自己是不可战胜的"],
                                            'bulletproof, impregnable, invulnerable, unbeatable, unconquerable',
                                            'conquerable, surmountable, vulnerable',
                                            'invincibility n. 无敌')]),
                              Word('invoke', "",
                                   [TestWay('vt',
                                            '实施',
                                            'to put into effect or operation',
                                            ["New train timetable has been invoked. 新的火车时刻表已经生效"],
                                            'enforce, effect, execute, implement, perform',
                                            'suspend'),
                                    TestWay('vt',
                                            '产生, 造成',
                                            'to be the cause of (a situation, action, or state of mind)',
                                            ["We should be prepared for the possibility that any solution may invoke another set of problems. 我们必须要为这样一种可能做好心理准备: 任何解决方案都可能带来一系列新的问题"],
                                            'beget, bring, catalyze, cause, create, engender, generate, induce, produce, result')]),
                              Word('irascible', "",
                                   [TestWay('adj',
                                            '易怒的',
                                            'marked by hot temper and easily provoked anger',
                                            ["The new boss is so irascible that several employees have resigned. 由于新老板太容易发飙, 许多员工已经递交了辞呈"],
                                            'choleric, irritable, peevish, petulant',
                                            'affable')]),
                              Word('irate', "",
                                   [TestWay('adj',
                                            '极其愤怒的',
                                            'extremely angry',
                                            ["an irate taxpayer 极为愤怒的纳税人"],
                                            'aggravated, apoplectic, choleric, enraged, exasperated, infuriated, ireful, mad, wrathful',
                                            'calm, halcyon, delighted, pleased')]),
                              Word('iridescent', "",
                                   [TestWay('adj',
                                            '五颜六色的',
                                            'displaying a play of lustrous colors like those of the rainbow',
                                            ["an iridescent soap bubble 一个五颜六色的肥皂泡"],
                                            'nacreous, opalescent, pearlescent',
                                            'monochromatic',
                                            'iridescence n. 五彩斑斓')]),
                              Word('irk', "",
                                   [TestWay('n',
                                            '令人烦恼的事物',
                                            'something that is a source of irritation',
                                            ["One of the prof's major irks is a cell phone that rings during a lecture. 课堂上突然响起的手机铃声是最让教授火大的事情之一"],
                                            'aggravation, bother, exasperation, frustration, headache, irritant, nuisance, vexation'),
                                    TestWay('v',
                                            '使烦恼, 使厌倦',
                                            'to be irritating, wearisome, or vexing to',
                                            ["She irked her friends by chewing her gum loudly during the movie. 她因为看电影时嚼口香糖弄出声响而惹怒了她的朋友们"],
                                            'annoy, bother, fret, gall, provoke, ruffle, vex',
                                            'appease, assuage, pacify, placate, propitiate, soothe',
                                            'irksome adj. 令人厌烦的')]),
                              Word('ironclad', "",
                                   [TestWay('adj',
                                            '非常坚固的, 坚不可摧的',
                                            'so firm or secure as to be unbreakable',
                                            ["pride on their ironclad fleet 对他们坚不可摧的舰队感到自豪"],
                                            'firm, invulnerable, secure, sound, tenacious, tough',
                                            'fragile')]),
                              Word('irradicable', "",
                                   [TestWay('adj',
                                            '不能根除的',
                                            'impossible to uproot or destroy',
                                            ["Smoking has become an irradicable bad habit for him. 吸烟已成了他不能根除的恶习"],
                                            'entrenched, ineradicable, ingrained, inveterate, rooted',
                                            'eradicable')]),
                              Word('irreducible', "",
                                   [TestWay('adj',
                                            '(数)不可约分的',
                                            'incapable of being factored into polynomials of lower degree with coefficients in some given field (as the rational numbers) or integral domain (as the integers)',
                                            ["irreducible integrals 质数"],
                                            antonyms = 'factorable 可约分的')])])

list14_unit4 = VocabularyList([Word('irrigate', "",
                                   [TestWay('vt',
                                            '灌溉',
                                            'to supply (dry land) with water by means of ditches, pipes, or streams; water artificially',
                                            ["irrigate crops periodically 定期灌溉农作物"],
                                            'water'),
                                    TestWay('vt',
                                            '冲洗',
                                            'to flush (a body part) with a stream of liquid (as in removing a foreign body or medicating)',
                                            ["irrigate the wound 冲洗伤口"],
                                            'flush, rinse, wash',
                                            'irrigation n. 灌溉')]),
                              Word('irritate', "",
                                   [TestWay('vt',
                                            '刺激, 惹恼',
                                            'to provoke impatience, anger, or displeasure in',
                                            ["His rude interruptions really irritated her. 他粗鲁的打断激怒了她"],
                                            'aggravate, annoy, exasperate, gall, inflame, nettle, peeve, provoke, rile, roil',
                                            'appease, assuage, pacify, placate, propitiate, soothe',
                                            'irritant n. 刺激物')]),
                              Word('issue', "",
                                   [TestWay('n',
                                            '(有争议的)话题, 议题',
                                            'a matter that is in dispute between two or more parties',
                                            ["focused on economic and political issues 重点关注经济和政治话题"],
                                            'nut, problem, question'),
                                    TestWay('vi',
                                            '发布(期刊等)',
                                            'to produce and release for distribution in printed form',
                                            ["plans to issue a monthly newsletter 计划发布新闻月刊"],
                                            'print'),
                                    TestWay('vi',
                                            '流出',
                                            'to go, come, or flow out',
                                            ["strange sound issued from the abandoned house 废弃房中传来的奇怪声音"],
                                            'discharge, emit, exude, release, vent',
                                            'withdraw')]),
                              Word('jabber', "",
                                   [TestWay('vi',
                                            '快而不清楚地说',
                                            'to talk rapidly, indistinctly, or unintelligibly',
                                            ["monkeys jabbering at each other in their cages 在笼子里唧唧歪歪的猴子"],
                                            'babble, blabber, drivel, gabble, gibber, jabber, mumbo jumbo',
                                            'speak slowly')]),
                              Word('jaded', "",
                                   [TestWay('adj',
                                            '疲惫的',
                                            'depleted in strength, energy, or freshness',
                                            ["After that long bar exam, I'm too jaded for anything but a nap. 律师资格考试结束后, 我累得只想睡觉"],
                                            'drained, exhausted, fatigued, prostrate, spent, wearied, worn-out'),
                                    TestWay('adj',
                                            '厌倦的, 没兴趣没热情的',
                                            "having one's patience, interest, or pleasure exhausted",
                                            ["Even jaded sci-fi fans are finding this new space adventure fresh and exciting. 即使是见多识广、口味很挑的科幻小说忠粉也觉得这次的太空探险非常新鲜有趣"],
                                            'bored, tired, wearied, fed up',
                                            'absorbed, engaged, engrossed, interested, intrigued, rapt')]),
                              Word('jape', "",
                                   [TestWay('v',
                                            '嘲弄',
                                            'to say or do something jokingly or mockingly',
                                            ["The characters in Oscar Wilde's plays jape with a sophistication that is rarely encountered in real life. 奥斯卡·王尔德戏剧作品中的角色用一种十分世故的态度进行嘲讽, 而这种态度在真实生活当中是很少见的"],
                                            'jest, quip, wisecrack, banter, chaff, gag, jive, jolly, josh',
                                            'revere')]),
                              Word('jargon', "",
                                   [TestWay('n',
                                            '行业术语',
                                            'the specialized or technical language of a trade, profession, or similar group',
                                            ["medical jargon that the layman cannot understand 外行不理解的医学术语"],
                                            'argot, cant, dialect, jive, lingo, patois')]),
                              Word('jarring', "",
                                   [TestWay('adj',
                                            '刺耳的',
                                            'harsh or discordant',
                                            ["the final chord of that song is too jarring for me 那首歌最后的合声部分太刺耳了"],
                                            'astounding, blindsiding, jolting, startling, stunning',
                                            'melodious'),
                                    TestWay('adj',
                                            '震惊的',
                                            'causing a strong emotional reaction because of unexpectedness',
                                            ["the jarring news that major financial institutions were on the verge of collapse 有消息称主要的几个金融机构处于倒闭的边缘, 真是让人震惊"],
                                            'amazing, astonishing, astounding, blindsiding, dumbfounding, flabbergasting, jaw-dropping, jolting, shocking, startling, stunning')]),
                              Word('jaundice', "",
                                   [TestWay('n',
                                            '(因嫉妒或厌世而产生的)偏见',
                                            'to affect with the negativity or bitterness of jaundice; bias',
                                            ["the jaundice in the eyes of the two feuding neighbors 两个有积怨的邻居之间的偏见"],
                                            'animosity, animus, antagonism, antipathy, gall, hostility, rancor',
                                            'amity')]),
                              Word('jaunty', "",
                                   [TestWay('adj',
                                            '轻快的, 活泼的',
                                            'sprightly in manner or appearance: lively',
                                            ["a jaunty stroll 轻快的散步"],
                                            'animate, brisk, energetic, frisky, perky, racy, spirited, vivacious',
                                            'staid, dead, inactive, inanimate, lackadaisical, languid, languishing, leaden, limp, listless, spiritless, vapid')])])

list14_unit5 = VocabularyList([Word('jejune', "",
                                   [TestWay('adj',
                                            '无趣乏味的',
                                            'not interesting; dull',
                                            ["jejune lectures 无聊的讲座"],
                                            'arid, drab, dreary, leaden, monotonous, ponderous, tedious, weary',
                                            'absorbing, engaging, engrossing, gripping, interesting, intriguing, involving, riveting, thought provoking'),
                                    TestWay('adj',
                                            '幼稚的',
                                            'having or showing the annoying qualities (as silliness) associated with children',
                                            ["an essay filled with jejune, simplistic opinions about international politics 充满着有关国际政治的幼稚、简单看法的文章"],
                                            'adolescent, immature, infantile, juvenile, kiddish, puerile',
                                            'adult, grown-up, mature')]),
                              Word('jest', "",
                                   [TestWay('n',
                                            '轻浮的态度, 戏谑',
                                            'a frivolous mood or manner',
                                            ["spoken in jest 戏谑地说"],
                                            'butt, derision, mockery',
                                            'solemnity, solemn utterance')]),
                              Word('jeopardy', "",
                                   [TestWay('n',
                                            '危险',
                                            'risk of loss or injury; peril or danger',
                                            ["the city's firefighters routinely put their lives in jeopardy 消防队员们早就把生命置之度外了"],
                                            'distress, endangerment, imperilment, peril',
                                            'safeness, safety, secureness, security')]),
                              Word('jettison', "",
                                   [TestWay('vt',
                                            '丢弃, 投弃',
                                            'to cast overboard or off',
                                            ["a ship jettisoning wastes 投弃废物的船"],
                                            'discard, dump, junk, scrap, throwing away',
                                            'keep, retain')]),
                              Word('jibe', "",
                                   [TestWay('vi',
                                            '意见一致',
                                            'to be in accord: agree',
                                            ["Your figures jibe with mine. 你的数据与我的一致。"],
                                            'accord, cohere, conform, correspond, harmonize, tally',
                                            'conflict')]),
                              Word('jingoist', "",
                                   [TestWay('n',
                                            '极端爱国激进分子(通常表现为好战的对外政策)',
                                            'extreme chauvinism or nationalism marked especially by a belligerent foreign policy',
                                            ["jingoists who cry for war 叫嚣着鼓吹开战的激进分子"],
                                            'chauvinist, nationalist, superpatriot, war hawk',
                                            'dove, pacifist, peacenik')]),
                              Word('jitters', "",
                                   [TestWay('n',
                                            '紧张, 不安',
                                            'a sense of panic or extreme nervousness',
                                            ["she suffered pre-wedding jitters 她有婚前恐惧"],
                                            'butterflies, dither, jimjams, nerves, shakes, shivers, willies',
                                            'aplomb, calm, composure, equanimity, imperturbability, self-possession, tranquility')]),
                              Word('jocular', "",
                                   [TestWay('adj',
                                            '搞笑的, 欢乐的',
                                            'characterized by joking, playful',
                                            ["a jocular man who could make the most serious people laugh 这个搞笑的人可以使得最严肃的人都开怀大笑"],
                                            'blithesome, festive, gleeful, jocund, jovial, mirthful',
                                            'lachrymose, saturnine, dour, dreary, morose, serious')]),
                              Word('jocund', "",
                                   [TestWay('adj',
                                            '欢快的, 高兴的',
                                            'sprightly and lighthearted in disposition, character, or quality',
                                            ["old friends engaged in jocund teasing 老朋友相见, 互相打趣调侃"],
                                            'blithesome, jocose, jocular, jolly, jovial, mirthful, sunny',
                                            'lachrymose, saturnine, dour, dreary, morose, serious')]),
                              Word('jog', "",
                                   [TestWay('n',
                                            '慢跑',
                                            'a movement, pace, or instance of jogging (as for exercise)'),
                                    TestWay('vi',
                                            '唤起',
                                            'to rouse or stimulate',
                                            ["an old photo that might jog your memory 一张也许会唤起你回忆的老照片"],
                                            'arouse, excite, incite, instigate, pique, remind, stimulate, stir',
                                            'allay, alleviate, assuage, ease, mitigate, mollify, palliate, relieve, soothe')])])

list14_unit6 = VocabularyList([Word('jolt', "",
                                   [TestWay('vi',
                                            '突然移动',
                                            'to move or dislodge with a sudden, hard blow'),
                                    TestWay('v',
                                            '惊吓',
                                            'to cause an unpleasant surprise for',
                                            ["The sneak terrorist attack jolted the country out of its indolence and indifference. 偷偷摸摸的恐怖分子将该国从懒惰和冷漠无情中惊醒"],
                                            'appall, floor, shake up')]),
                              Word('jot', "",
                                   [TestWay('vt',
                                            '简要记录',
                                            'to write briefly or hurriedly',
                                            ["jot down an address 简要地记下地址"],
                                            'log, mark, put down, register, report, set down, take down, write down')]),
                              Word('jovial', "",
                                   [TestWay('adj.',
                                            '愉快的',
                                            'markedly good-humored especially as evidenced by jollity and conviviality',
                                            ["a jovial host 快活的主人"],
                                            'blithesome, festive, gay, gleeful, jocular, jocund, jolly, mirthful',
                                            'lachrymose, saturnine, dour, dreary, morose, serious')]),
                              Word('jubilant', "",
                                   [TestWay('adj',
                                            '喜悦的',
                                            'exultingly joyful',
                                            ["The nominee delivered a jubilant speech before the cheering crowd. 在欢呼的人群面前, 被提名人发表了充满喜悦的演说"],
                                            'exulting, glorying, rejoicing, triumphant',
                                            'lachrymose, saturnine, dour, dreary, morose, serious')]),
                              Word('judicious', "",
                                   [TestWay('adj',
                                            '明智的, 慎重的',
                                            'having or exhibiting sound judgment; prudent',
                                            ["a judicious choice 明智的抉择"],
                                            'intelligent, judgmatic, prudent, tactical, wise',
                                            'daft, imprudent, inadvisable, inexpedient, indiscrete, impolitic, unwise')]),
                              Word('juggernaut', "",
                                   [TestWay('n',
                                            '无法阻挡的力量, 摧毁一切的强大力量',
                                            'an overwhelming, advancing force that crushes everything in its path',
                                            ["the juggernaut of industrialization 工业化无法阻挡的力量"],
                                            'steamroller')]),
                              Word('ken', "",
                                   [TestWay('n',
                                            '视野范围',
                                            'the range of vision',
                                            ["abstract words that are beyond the ken of children 那些孩子们不能理解的抽象字词"],
                                            'sight'),
                                    TestWay('vt',
                                            '知道、了解(人或物)',
                                            'to know (a person or thing)',
                                            synonyms = 'appreciate, apprehend, cognize, comprehend, grasp, perceive, savvy, understand',
                                            antonyms = 'misapprehend, misconceive, misinterpret, misperceive, misunderstand')]),
                              Word('kidnap', "",
                                   [TestWay('vt',
                                            '绑架勒索',
                                            'to seize and detain by unlawful force or fraud and often with a demand for ransom',
                                            ["the child was kidnapped and held for ransom 歹徒绑架了孩子, 并且向家属勒索赎金"],
                                            'abduct',
                                            'release, set free')]),
                              Word('kindle', "",
                                   [TestWay('vt',
                                            '点燃',
                                            'to build or fuel (a fire); to set fire to; ignite',
                                            ["kindle interest 激发兴趣"],
                                            'enkindle, ignite, inflame, torch',
                                            'douse, extinguish, quench, put out, snuff out')]),
                              Word('kindred', "",
                                   [TestWay('adj',
                                            '类似的; 具有相似或相近的起源, 本性或性质的',
                                            'having a similar or related origin, nature, or character',
                                            ["finally found people who were kindred spirits when she joined the hiking club 她加入登山俱乐部的时候终于发现了志向相同的人"],
                                            'agreeable, amicable, compatible, congenial, frictionless, unanimous, united',
                                            'disagreeable, discordant, disharmonious, disunited, incompatible, inharmonious, uncongenial')])])

list14_unit7 = VocabularyList([Word('knack', "",
                                   [TestWay('n',
                                            '诀窍, 聪明的做法',
                                            'a clever trick or stratagem; a clever way of doing something',
                                            ["She's tried every knack in Cupid's book to get her guy to marry her. 她试过了所有爱情三十六计, 希望那男人娶她"],
                                            'artifice, device, gambit, ploy, scheme, sleight, stratagem',
                                            'foolishness')]),
                              Word('knead', "",
                                   [TestWay('vt',
                                            '揉捏, 塑造',
                                            'to make or shape by or as if by folding, pressing, and stretching with the hands',
                                            ["knead dough 揉面团", "kneading a painful calf muscle 给疼痛的小腿肌肉按摩"],
                                            'massage, manipulate, mould, squeeze, stroke')]),
                              Word('knit', "",
                                   [TestWay('vt',
                                            '编织(纱线)',
                                            'to form by interlacing yarn or thread in a series of connected loops with needles',
                                            ["She knitted him a sweater for Christmas. 圣诞节她为他缝了一件毛衣"],
                                            'braid, plait, weave',
                                            'ravel'),
                                    TestWay('vt',
                                            '连接, 联系',
                                            'to join closely; unite securely',
                                            ["Sport knits the whole family close together. 体育将整个家庭紧紧地联系在一起"],
                                            'bind, bond, combine, connect, fasten, join, link, meld, merge, tie, secure, unite',
                                            'disassociate, disconnect, disjoin, divide, sever, split, sunder')]),
                              Word('knotty', "",
                                   [TestWay('adj',
                                            '多结的, 复杂的, 困难的',
                                            'marked by or full of knots especially: so full of difficulties and complications as to be likely to defy solution',
                                            ["The candidates cautiously gave their views on an array of knotty issues. 候选人就一系列的困难问题谨慎地给出了自己的看法"],
                                            'baroque, byzantine, complicated, convoluted, intricate, involved, labyrinthine, sophisticated, tangled',
                                            'easy, effortless, plain, simple')]),
                              Word('kudos', "",
                                   [TestWay('n',
                                            '名望, 名声',
                                            'fame and renown resulting from an act or achievement',
                                            ["Employees enjoy the kudos that the job brings as much as the financial rewards. 正如同喜欢工作带来的经济回报一样, 雇员们也很享受工作所带来的名声和荣誉"],
                                            'credit, distinction, homage, honor, laurels',
                                            'infamy, notoriety'),
                                    TestWay('n',
                                            '夸奖, 赞扬',
                                            'acclaim or praise for exceptional achievement',
                                            ["The attorney did pro bono work because it was the right thing to do, and not for any future kudos that it might bring. 这名律师之所以为慈善机构和穷人所􁨀供免费服务, 是因为他觉得这是正确的事情, 而非为了任何可能因此而产生的赞扬"],
                                            'acclaim, accolade, applause, credit, distinction, homage, honor, laud, laurels',
                                            'belittlement, denigration, deprecation, derogation, diminishment, disparagement')]),
                              Word('labile', "",
                                   [TestWay('adj',
                                            '易变的, 不稳定的',
                                            'continually undergoing chemical, physical, or biological change; unstable',
                                            ["labile mineral 不稳定的矿物质", "an emotionally labile person 一个多愁善感的人"],
                                            'capricious, fluctuating, fluid, inconstant, mercurial, temperamental, unsettled, unsteady, variable, volatile',
                                            'constant, immutable, invariable, stable, stationary, steady')]),
                              Word('laborious', "",
                                   [TestWay('adj',
                                            '勤奋的',
                                            'hard-working; industrious',
                                            ["The volunteers have been commendably laborious in their cleanup of the beach. 清理海滩的志愿者们的勤奋努力值得赞扬‖He was gentle and kindly, living a laborious life in his Paris flat. 他是一个温柔、好心的人, 住在巴黎的公寓里过着勤奋的生活"],
                                            'active, assiduous, bustling, diligent, engaged, industrious, occupied, sedulous',
                                            'idle, inactive, indolent, inert, slothful'),
                                    TestWay('adj',
                                            '费力的',
                                            'marked by or requiring long, hard work',
                                            ["the laborious task of cleaning up the oil spill 清除泄露石油的艰苦工作"],
                                            'arduous, challenging, demanding, difficult, exacting, formidable, grueling, heavy, labored, rigorous, rough, rugged, severe, strenuous, sweaty, toilsome, tough',
                                            'easy, effortless, facile, light, mindless, simple, undemanding')]),
                              Word('labyrinthine', "",
                                   [TestWay('adj',
                                            '迷宫似的, 复杂曲折的',
                                            'of, relating to, resembling, or constituting a labyrinth; extremely complex or tortuous in structure',
                                            ["The labyrinthine political situation of Middle East left us totally befuddled. 中东地区复杂迷离的政治局势让我们彻底迷惑了"],
                                            'baroque, byzantine, complicate, complicated, convoluted, intricate, involved, knotty, sophisticated, tangled',
                                            'easy, effortless, plain, simple')]),
                              Word('lacerate', "",
                                   [TestWay('vt',
                                            '使非常痛苦',
                                            'to cause deep emotional pain to; distress',
                                            ["He was born into a family already lacerated with tensions and divisions. 他出生在一个已经被冲突和分裂折磨不堪的家庭当中"],
                                            'afflict, distress, harrow, hurt, rend, torment, torture, wound',
                                            'allay, alleviate, assuage, ease, mitigate, mollify, palliate, relieve, soothe')]),
                              Word('lackluster', "",
                                   [TestWay('adj',
                                            '黯淡无光泽的',
                                            'lacking brightness, luster, or vitality',
                                            ["lackluster hair 黯淡无光的头发"],
                                            'dim, dull, flat, lusterless',
                                            'burnished, glistening, glossy, lustrous, polished, shiny, sleek')])])

list14_unit8 = VocabularyList([Word('laconic', "",
                                   [TestWay('adj',
                                            '简洁(以至于显得粗鲁或难以理解)的',
                                            'using or involving the use of a minimum of words: concise to the point of seeming rude or mysterious',
                                            ["His mentor’s comment tends to be laconic but very much to the point. 他导师的点评很简短, 但是却总能说到点子上"],
                                            'apothegmatic, brief, capsule, compact, compendious, curt, pithy, succinct, summary, telegraphic, terse',
                                            'circuitous, circumlocutory, diffuse, prolix, rambling, verbose, windy, wordy')]),
                              Word('lachrymose', "",
                                   [TestWay('adj',
                                            '催人泪下的, 悲伤的',
                                            'tending to cause tears, mournful',
                                            ["The lachrymose mourners at the funeral required a steady supply of tissues. 葬礼上多愁善感的哀悼者对纸巾提出了巨大的需求"],
                                            'doleful, lamentable, lugubrious, melancholy, mournful, tearful, teary, weepy, woeful',
                                            'cheerful, delighted, jocund, jovial')]),
                              Word('lambaste', "",
                                   [TestWay('vt',
                                            '严厉斥责',
                                            'to scold sharply; berate',
                                            ["Critics lambasted his performance. 评论家严厉斥责了他的表演"],
                                            'assail, baste, belabor, berate, castigate, excoriate, reprimand, reproach, scathe, scold, slam, upbraid, vituperate',
                                            'carol, extol, glorify, hymn, laud, magnify, praise')]),
                              Word('lament', "",
                                   [TestWay('n',
                                            '悼词',
                                            "a composition expressing one's grief over a loss",
                                            ["her lament for her grandmother 她为她祖母写的悼词"],
                                            'dirge, elegy, requiem'),
                                    TestWay('n',
                                            '抱怨',
                                            'an expression of dissatisfaction, pain, or resentment',
                                            ["the career woman's lament that there aren't any good men left 职场女性的抱怨: 没剩下多少好男人了"],
                                            'carp, complaint, fuss, grievance, gripe, grouch, grouse, grumble, moan, murmur'),
                                    TestWay('vi',
                                            '哀悼, 表达痛苦或遗憾',
                                            'to express sorrow or regret; mourn',
                                            ["lament an innocent death 为无辜的死者而悲痛"],
                                            'bemoan, deplore, grieve, moan, mourn, wail',
                                            'delight, exult, joy, rejoice')]),
                              Word('lamentable', "",
                                   [TestWay('adj',
                                            '值得惋惜的, 悲哀的',
                                            'inspiring or deserving of lament or regret; deplorable or pitiable; mournful',
                                            ["The lamentable cries of the women for their lost sons were heard throughout the village. 女人们由于丧子之痛的哀嚎响彻整个山谷"],
                                            'deplorable, distressful, grievous, heartbreaking,, lugubrious, plaintive, plangent, sorrowful, woeful',
                                            'cheerful, delighted, jocund, jovial')]),
                              Word('lampoon', "",
                                   [TestWay('n',
                                            '讽刺',
                                            'a harsh satire usually directed against an individual',
                                            ["a lampoon of the movie business at the time 对当时电影产业的一种讽刺"],
                                            'burlesque, caricature, farce, mockery, parody, ridicule, spoof, travesty',
                                            'eulogy, ode, paean')]),
                              Word('languid', "",
                                   [TestWay('adj',
                                            '没精打采的, 虚弱的',
                                            'lacking energy or vitality; weak',
                                            ["be languid for weeks after surgery 术后的几周都无精打采的"],
                                            'debilitated, effete, enervated, feeble, frail, infirm, lackadaisical, spiritless, debilitated, sapped, enfeebled',
                                            'animated, energetic, vehement, vivacious, mighty, powerful, stalwart, stout, strong')]),
                              Word('languish', "",
                                   [TestWay('vi',
                                            '变得衰弱',
                                            'to be or become feeble, weak, or enervated',
                                            ["languishing during the prolonged heat wave 在持续的热浪下变得虚弱"],
                                            'decay, droop, emaciate, fade, fail, flag, sag, wither',
                                            'burgeon, flourish, thrive, prosper')]),
                              Word('languor', "",
                                   [TestWay('n',
                                            '懒惰',
                                            'physical or mental inertness',
                                            ["He enjoyed the languor brought on by a hot summer afternoon. 他很享受夏日午后的慵懒"],
                                            'collapse, exhaustion, frazzle, lassitude, listlessness, stupor, torpor, prostration',
                                            'verve, vim,animation,vitality'),
                                    TestWay('n',
                                            '衰弱',
                                            'weakness or weariness of body or mind',
                                            ["The tropical heat sapped our strength, leaving us in a state of unaccustomed languor. 热带的炎热气候消磨着我们的力量, 让我们感到一阵虚弱的不适"],
                                            'debilitation, enervation, enfeeblement, fragility, infirmity',
                                            'robustness, strength, vivacity')]),
                              Word('lank', "",
                                   [TestWay('adj',
                                            '细长瘦弱的',
                                            'long, straight, and limp; not stiff in structure',
                                            ["a woman with long, lank hair 有着长而稀疏头发的女子"],
                                            'emaciated, lean, slender, svelte, tenuous, thin',
                                            'fat, fleshy, gross, obese'),
                                    TestWay('adj',
                                            '不僵硬的, 柔软松弛的',
                                            'not stiff in structure',
                                            ["Right after a shower, her lank hair hung down to her shoulders. 刚出浴的她柔软的头发搭在她的肩上"],
                                            'droopy, flaccid, floppy, lank, yielding',
                                            'inflexible, rigid, stiff, sturdy, tense, resilient')])])

list14_unit9 = VocabularyList([Word('lapse', "",
                                   [TestWay('n',
                                            '小过失',
                                            'a slight error typically due to forgetfulness or inattention',
                                            ["The alumna's huge bequest was an unexpected largess. 校友们的巨额遗赠是一笔意料之外的财富"],
                                            'bestowal, donation, giveaway, present'),
                                    TestWay('v',
                                            '结束, 终止',
                                            'to come to an end',
                                            ["The contract will lapse at the end of the year. 合同将于年底到期"],
                                            'cease, conclude, die, end, expire, finish, stop, terminate',
                                            'continue, persist, hang on')]),
                              Word('largesse', "",
                                   [TestWay('n',
                                            '捐赠物',
                                            'something given to someone without expectation of a return',
                                            ["The alumna's huge bequest was an unexpected largess. 校友们的巨额遗赠是一笔意料之外的财富"],
                                            'bestowal, donation, giveaway, present'),
                                    TestWay('n',
                                            '慷慨',
                                            'liberality in giving or willingness to give',
                                            ["be noted for his largesse 因慷慨而闻名"],
                                            'bountifulness, generosity, munificence, openhandedness, philanthropy',
                                            'miserliness, parsimony, penury, stinginess')]),
                              Word('lash', "",
                                   [TestWay('n',
                                            '击打',
                                            'a hard strike with a part of the body or an instrument',
                                            ["suddenly felt the lash of her drunken husband's hand on her cheek 突然感觉到脸颊被醉酒的丈夫扇了一耳光"],
                                            'bang, bash, bat, beat, clap, hit, knock, punch, slam, slap, smash, stinger, stroke, swat'),
                                    TestWay('v',
                                            '猛击, 撞击',
                                            'to strike against with force or violence',
                                            ["All night long a barrage of rain lashed the windows. 倾盆大雨整夜敲击着窗户"],
                                            'baste, hammer, lace, lambaste, punch'),
                                    TestWay('vt',
                                            '捆扎',
                                            'to bind with or as if with a line',
                                            ["Secure the anchor by lashing it to the rail. 通过将锚绑在栏杆上使其稳固。"],
                                            antonyms = 'unbind')]),
                              Word('lassitude', "",
                                   [TestWay('n',
                                            '乏力, 没精打采',
                                            'a state or feeling of weariness, diminished energy, or listlessness',
                                            ["Symptoms of anaemia include general fatigue and lassitude. 贫血的通常症状包括体虚和乏力"],
                                            'collapse, exhaustion, frazzle, languor, listlessness, stupor, torpor, prostration',
                                            'verve, vim,animation,vitality')]),
                              Word('latent', "",
                                   [TestWay('adj',
                                            '潜在的, 不活跃的',
                                            'present or potential but not evident or active',
                                            ["a latent infection 潜伏性传染病‖He has a latent talent for acting that he hasn't had a chance to express yet. 他有着表演的天赋, 只不过他还没有机会来表现这一才能"],
                                            'dormant, fallow, inert, inoperative',
                                            'apparent, evident, manifest, obvious, plain, active',
                                            'latency n. 潜伏期')]),
                              Word('latitude', "",
                                   [TestWay('n',
                                            '(行动或言论)自由',
                                            'freedom from normal restraints, limitations, or regulations',
                                            ["Students are allowed considerable latitude in choosing courses. 学生在选课时被给予相当大的自由度"],
                                            'authorization, license, freedom, leeway, free hand',
                                            'limitation, custody')]),
                              Word('laudatory', "",
                                   [TestWay('adj',
                                            '表示赞扬的',
                                            'of, relating to, or expressing praise',
                                            ["a laudatory review of the new play 对新剧目的赞扬性的评论"],
                                            'adulatory, commendatory, complimentary, extolling, eulogistic, panegyric',
                                            'derogatory, depreciatory, disparaging, pejorative',
                                            'laudable adj. 值得赞扬的')]),
                              Word('lavish', "",
                                   [TestWay('adj',
                                            '奢侈大量的',
                                            'characterized by or produced with extravagance and profusion',
                                            ["lavish buffet 奢侈的自助餐"],
                                            'copious, exuberant, gushing, lush, luxuriant, opulent, profuse, riotous',
                                            'moderate, modest, reasonable, temperate'),
                                    TestWay('v',
                                            '挥霍, 浪费',
                                            'to give readily and in large quantities; to use up carelessly',
                                            ["a great actor who lavished his talent in lousy movies 将才华浪费在低劣电影上的影星"],
                                            'blow, dissipate, fritter, misspend, squander, waste',
                                            'conserve')]),
                              Word('leaven', "",
                                   [TestWay('vt',
                                            '用轻松、活泼或变更的影响力来充斥',
                                            'to mingle or permeate with some modifying, alleviating, or vivifying element',
                                            ["He needs to leaven his speeches with more humor. 他需要在演讲中再加入点幽默元素。"],
                                            'imbue, infuse, ingrain, inoculate, inspire, permeate, steep, suffuse',
                                            'extract')]),
                              Word('leer', "",
                                   [TestWay('vi',
                                            '一瞥, 斜眼看',
                                            'to cast a sidelong glances',
                                            ["He gave her a leering look. 他瞥了她一眼"],
                                            'squint',
                                            'gape, gaze, glare, goggle, stare')]),
                              ])

list14_unit10 = VocabularyList([Word('leery', "",
                                   [TestWay('adj',
                                            '怀疑的, 不信任的',
                                            'suspicious or distrustful; wary',
                                            ["be leery of strangers 对陌生人的怀疑"],
                                            'dubious, distrustful, skeptical, suspicious, wary',
                                            'credulous')]),
                              Word('legacy', "",
                                   [TestWay('n',
                                            '遗产',
                                            'something handed down from an ancestor or a predecessor or from the past',
                                            ["the legacy of the ancient philosophers 古代哲学家们的思想遗产"],
                                            'bequest, heritage, patrimony')]),
                              Word('legend', "",
                                   [TestWay('n',
                                            '传奇, 传说',
                                            'a popular myth of recent origin',
                                            ["Some ancient civilizations had legends about spirits that inhabited trees and rocks. 许多古老的文明都有着关于寄居于树木、岩石之中的灵魂的传说"],
                                            'fable, myth, mythos'),
                                    TestWay('n',
                                            '图例',
                                            'an explanatory list of the symbols on a map or chart',
                                            ["The legend in the science textbook indicated that the accompanying picture had been enlarged by 1000%. 科学课本上彩图的图例告诉我们这幅图片被放大了十倍"],
                                            'cutline',
                                            'legendary adj. 如传奇般闻名的')]),
                              Word('legion', "",
                                   [TestWay('n',
                                            '大量的人, (尤指)军团',
                                            'a large body of men and women organized for land warfare',
                                            ["joined the French Foreign Legion 加入了法国外籍军团"],
                                            'army, battalion, flock, herd, horde, mob, swarm, throng'),
                                    TestWay('adj',
                                            '大量的',
                                            'many, numerous',
                                            ["The problems are legion. 问题不计其数"],
                                            'beaucoup, multifold, multitudinous, numerous',
                                            'few, lack in number')]),
                              Word('lenient', "",
                                   [TestWay('adj',
                                            '宽大仁慈的',
                                            'inclined not to be harsh or strict; merciful, generous, or indulgent',
                                            ["the lenient sentences 仁慈的审判"],
                                            'clement, gentle, merciful, mild, sparing, tender, tolerant',
                                            'harsh, merciless, severe, strict',
                                            'lenience n. 仁慈')]),
                              Word('lethal', "",
                                   [TestWay('adj',
                                            '非常有害的, 致命的',
                                            'extremely harmful; devastating',
                                            ["This dagger is lethal. 这把匕首是致命的武器‖launched a lethal attack 发动了致命的进攻"],
                                            'baleful, deadly, deathly, fatal, mortal, murderous, pestilent, terminal, vital',
                                            'innocuous, healthy, salubrious, wholesome')]),
                              Word('lethargic', "",
                                   [TestWay('adj',
                                            '没精打采的, 行动迟缓的',
                                            'of, relating to, or characterized by lethargy, sluggish',
                                            ["a big nice meal always makes me feel lethargic and sleepy 一顿大餐吃完总是让我既慵懒又想睡"],
                                            'dull, inert, quiescent, sluggish, torpid',
                                            'dynamic, energetic, robust, vigorous, active')]),
                              Word('levelheaded', "",
                                   [TestWay('adj',
                                            '明智的',
                                            'characteristically self-composed and sensible',
                                            ["a levelheaded assessment of the problem 对于问题的一个明智的评估"],
                                            'informed, justified, logical, rational, reasonable, sensible, sober, valid, well-founded',
                                            'foolish, groundless, invalid, unfounded, unjustified, unsound')]),
                              Word('levity', "",
                                   [TestWay('n',
                                            '轻浮',
                                            'excessive or unseemly frivolity',
                                            ["The teachers disapprove of any displays of levity during school assemblies. 老师们不允许学生在学校聚会过程中表现出任何轻浮的态度"],
                                            'facetiousness, flightiness, flippancy, frivolousness, frothiness, silliness',
                                            'earnestness, gravity, seriousness, soberness, solemnity')]),
                              Word('liability', "",
                                   [TestWay('n',
                                            '责任',
                                            'the quality or state of being liable',
                                            ["The company is trying to reduce its liability in this case. 在这个案件中, 公司试图减少他们的责任"],
                                            'accountability, answerability, responsibility',
                                            'immunity'),
                                    TestWay('n',
                                            '障碍, 不利条件',
                                            'a feature of someone or something that creates difficulty for achieving success',
                                            ["Their chief asset has now become a considerable liability. 他们最大的优点如今已成了不可小觑的负担"],
                                            'burden, debit, drawback, handicap, hurdle, incommodity, manacle, saddle, trammel',
                                            'advantage, asset, edge, plus')])])

LIST14 = VocabularyList(list14_unit1.words+list14_unit2.words+list14_unit3.words+list14_unit4.words+list14_unit5.words+list14_unit6.words+list14_unit7.words+list14_unit8.words+list14_unit9.words+list14_unit10.words)
