#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list12_unit1 = VocabularyList([Word('harsh', "",
                                   [TestWay('adj',
                                            '粗糙的, 不具有美感的',
                                            "unpleasantly coarse and rough to the touch, disagreeable to one's aesthetic or artistic sense",
                                            ["the harsh lighting in the cafeteria makes the food look slightly off-color 咖啡厅劣质刺眼的灯光让食物看起来卖相不佳"],
                                            ['grating', 'grotesque', 'jarring', 'unaesthetic'],
                                            ['soft', 'aesthetic']),
                                    TestWay('adj',
                                            '严厉的',
                                            'unduly exacting, given to exacting standards of discipline and self-restraint',
                                            ["a harsh judge when it comes to drug users and especially drug dealers 对于瘾君子特别是毒贩处罚格外严厉的法官"],
                                            'afflicting, agonizing, cruel, excruciating, galling, grievous, harrowing',
                                            'clement, forbearing, gentle, indulgent, lax, lenient, tolerant')]),
                              Word('hasten', "",
                                   [TestWay('vt',
                                            '促进',
                                            'to speed up; accelerate',
                                            ["The man’s death was hastened by alcohol abuse. 酗酒加速了老人的死亡。"],
                                            "accelerate, bundle, fast-track, rush, speed up",
                                            'slow the progress of, check, retard, brake, decelerate, retard, slow down')]),
                              Word('hasty', "",
                                   [TestWay('adj',
                                            '轻率的',
                                            'fast and typically superficial; acting or done with excessive or careless speed',
                                            ["a hasty decision 轻率的决定"],
                                            'cursory, headlong, precipitate, rash, rushed, pell-mell',
                                            'deliberate, well considered, unhurried, unrushed')]),
                              Word('haunt', "",
                                   [TestWay('vt',
                                            '常去拜访',
                                            'to visit often; frequent',
                                            ["haunt the movie theater 常去影院"],
                                            'frequent, affect, habituate, visit, hang at, resort to',
                                            ['avoid', 'shun']),
                                    TestWay('vt',
                                            '不断地想起, 萦绕心头',
                                            'to come to mind continually; obsess',
                                            ["a riddle that haunted me all morning 整个早上萦绕在我心头的谜"])]),
                              Word('hauteur', "",
                                   [TestWay('n',
                                            '傲慢, 自大',
                                            'haughtiness in bearing and attitude; arrogance',
                                            ["he looked at her with the hauteur of someone who is accustomed to being instantly obeyed 他看着她, 带着向来被顺从惯了的傲慢。"],
                                            'bumptiousness, imperiousness, peremptoriness, pomposity, presumptuousness, pretentiousness, superciliousness, superiority',
                                            'humility, humbleness, modesty, unassumingness, unpretentiousness')]),
                              Word('haven', "",
                                   [TestWay('n',
                                            '安全的地方',
                                            'a place of safety',
                                            ["a haven for artists 艺术家们的圣地"],
                                            'asylum, harbor, refuge, retreat, sanctuary',
                                            ['unsafe place', 'dangerous place'])]),
                              Word('havoc', "",
                                   [TestWay('n',
                                            '大混乱',
                                            'a state in which everything is out of order',
                                            ["the blackout caused havoc in the city 断电造成了城市一片混乱"],
                                            'disarrangement, disarray, dishevelment, muddle, muss, tumble, welter, discord',
                                            ['order', 'orderliness']),
                                    TestWay('n',
                                            '大范围破坏',
                                            'the state or fact of being rendered nonexistent, physically unsound, or useless',
                                            ["the powerful hurricane wreaked havoc all along the coast 威力巨大的飓风摧毁着沿岸的一切"],
                                            'annihilation, decimation, demolishment, desolation, devastation, extermination, extinction, obliteration, ruin, wreckage',
                                            'building, construction, erection, raising')]),
                              Word('headlong', "",
                                   [TestWay('adj',
                                            '鲁莽的',
                                            'without deliberation',
                                            ["terrified forest creatures in a headlong retreat from the rapidly spreading fire 受惊的动物们惊慌失措地从不断蔓延的森林大火中逃离出来"],
                                            'cursory, overhasty, precipitate, precipitous, rash, pell-mell, helter-skelter',
                                            'deliberate, unhurried, unrushed')]),
                              Word('hearken', "",
                                   [TestWay('vi',
                                            '倾听, 关注',
                                            'to give respectful attention',
                                            synonyms = 'attend, harken, heed, mind',
                                            antonyms = ['ignore'])]),
                              Word('hearten', "",
                                   [TestWay('vt',
                                            '给予鼓励, 鼓舞',
                                            'to give strength, courage, or hope to; encourage',
                                            ["thinking we were hopelessly lost, we were heartened by the sight of a familiar farmhouse 悲催地以为我们完全迷路了, 前方一座熟悉的农场给了我们新的希望"],
                                            'embolden, inspire, inspirit, buck up, buoy up, cheer up',
                                            'daunt, dismay, discourage, dishearten, dispirit')])])

list12_unit2 = VocabularyList([Word('heartrending', "",
                                   [TestWay('adj',
                                            '令人心碎的',
                                            'causing intense sorrow or distress',
                                            ["a heartrending choice between saving his mother or his wife 先救老妈还是先救老婆的纠结选择"])]),
                              Word('hedonism', "",
                                   [TestWay('n',
                                            '享乐主义',
                                            'the doctrine that pleasure or happiness is the sole or chief good in life',
                                            ["their spring break trip to Mexico became an exercise in heedless hedonism 他们春季的墨西哥之行成为了一次未加注意的享乐之旅"],
                                            'carnality, debauchery, sybaritism, voluptuousness',
                                            'abstinence, asceticism, sobriety, temperance')]),
                              Word('hegemony', "",
                                   [TestWay('n',
                                            '霸权, 统治权',
                                            'preponderant influence or authority over others',
                                            ["battled for hegemony in Asia 争夺在亚洲地区的霸权地位"],
                                            'ascendancy, dominance, dominion, predominance, preeminence',
                                            ['lack of authority'])]),
                              Word('heinous', "",
                                   [TestWay('adj',
                                            '可憎的, 十恶不赦的',
                                            'hatefully or shockingly evil, abominable',
                                            ["a heinous crime 十恶不赦的罪行"],
                                            antonyms = ['commendable'])]),
                              Word('hew', "",
                                   [TestWay('vi',
                                            '遵守',
                                            'confirm, adhere, to hold to something firmly as if by adhesion',
                                            ["hew to tradition 遵守传统"],
                                            ['adhere', 'cling', 'conform']),
                                    TestWay('v',
                                            '支持',
                                            'to give steadfast support to',
                                            ["no longer was able to hew to the party line and so he switched political parties 不再赞同该党的纲领, 他投奔了另一个党"],
                                            ['cling to', 'keep to', 'stand by', 'stick to'],
                                            ['defect'])]),
                              Word('herald', "",
                                   [TestWay('vt',
                                            '告知',
                                            'to make known openly or publicly',
                                            ["herald the great tidings to all the world 将重大消息告知全世界"],
                                            'annunciate, broadcast, declare, enunciate, proclaim, promulgate'),
                                    TestWay('v',
                                            '预示, 预兆',
                                            'to give a slight indication of beforehand',
                                            ["the reshuffle of the company's management heralded the sweeping changes to come 公司管理层的重新洗牌预示着即将到来的巨大变革"],
                                            'adumbrate, forerun, harbinger, prefigure')]),
                              Word('heresy', "",
                                   [TestWay('n',
                                            '异教, 和普遍观点相悖',
                                            'a controversial or unorthodox opinion or doctrine, departure from a generally accepted theory, opinion, or practice',
                                            ["the heresy of asserting that Shakespeare was not a great writer 声称莎士比亚不是伟大作家的非主流观点"],
                                            'dissent, dissidence, heterodoxy, nonconformity',
                                            'dogma, conformity, orthodoxy')]),
                              Word('heretical', "",
                                   [TestWay('adj',
                                            '异教的, 异端的',
                                            'departure from established beliefs or standards',
                                            ["the belief that women should be allowed to have careers outside the home was once considered heretical 女人应该拥有自己的事业这一观点一度被认为是异端想法"],
                                            'heterodox, nonconformist, unconventional, unorthodox',
                                            'conforming, conformist, conventional, orthodox')]),
                              Word('hermetic', "",
                                   [TestWay('adj',
                                            '深奥的',
                                            'relating to or characterized by occultism or abstruseness',
                                            ["wrote hermetic poetry 写晦涩难懂的诗歌"],
                                            'abstruse, arcane, esoteric, recondite',
                                            'easily comprehended, shallow, superficial')]),
                              Word('hesitance', "",
                                   [TestWay('n',
                                            '犹豫, 不情愿',
                                            'the quality or state of being hesitant, reluctance',
                                            ["sales figures for the month were up, as consumers began to overcome their hesitance about purchasing big-ticket items 月销售额有所上涨, 因为消费者对于大件商品的购买由观望转向消费"],
                                            'faltering, indecision, irresolution, vacillation, wavering, wobbling',
                                            'alacrity, impetuosity, inclination, willingness')])])

list12_unit3 = VocabularyList([Word('heterodox', "",
                                   [TestWay('adj',
                                            '非正统的, 异端的',
                                            'holding unorthodox opinions or doctrines, not rigidly following established form, custom, or rules',
                                            ["her heterodox approach to teaching science initially met with some resistance from her peers 她对于教学的一些非正统方法最开始受到了同辈的抵触"],
                                            'dissenting, out-there, unconventional, unorthodox',
                                            'conforming, conventional, orthodox, regular, routine')]),
                              Word('hidebound', "",
                                   [TestWay('adj',
                                            '死板的, 极度保守的',
                                            'tending to favor established ideas, conditions, or institutions',
                                            ["the hidebound innkeeper refused to see the need for a Web site 死板的酒馆老板坚决不肯装宽带"],
                                            'archconservative, brassbound, die-hard, old-fashioned, standpat, ultraconservative',
                                            ['broad-minded', 'large-minded', 'liberal', 'nonconservative', 'nonconventional', 'nonorthodox', 'nontraditional', 'open-minded', 'progressive'])]),
                              Word('hideous', "",
                                   [TestWay('adj',
                                            '非常丑陋的',
                                            'exceedingly ugly',
                                            ["wearing a hideous Halloween mask that made the kids all jump with fright 戴着一个丑陋的万圣节面具把小孩子全都吓跑了"],
                                            ['homely', 'ill-favored', 'monstrous', 'uncomely', 'unsightly'],
                                            ['pulchritudinous', 'aesthetic', 'attractive', 'comely', 'gorgeous', 'handsome', 'knockout', 'ravishing', 'seemly', 'stunning', 'taking', 'well-favored'],
                                            'hideousness 丑陋 【反】affinity 吸引力')]),
                              Word('hie', "",
                                   [TestWay('vi',
                                            '匆匆忙忙',
                                            'to go quickly, hasten',
                                            ["we had best hie home before the rain gets worse 我们最好在雨下大之前赶快回家"],
                                            'bustle, dash, hustle, scoot, scurry, scuttle, shoot, trot',
                                            'dawdle, crawl, creep, poke')]),
                              Word('hike', "",
                                   [TestWay('vi',
                                            '上涨',
                                            'to rise up, to move from a lower to a higher place or position',
                                            ["hike rents 涨租金"],
                                            'boost, elevate, heighten, hoist, upraise',
                                            'backset, drop, lower')]),
                              Word('hilarious', "",
                                   [TestWay('adj',
                                            '非常好笑的',
                                            'marked by or causing hilarity: extremely funny',
                                            ["hilarious cartoons that the whole family can enjoy 适合全家观看的搞笑动画片"],
                                            'hysterical, ludicrous, ridiculous, screaming, sidesplitting, uproarious',
                                            'humorless, lame, unamusing, uncomic, unfunny')]),
                              Word('histrionic', "",
                                   [TestWay('adj',
                                            '戏剧的, 演员的',
                                            'of or relating to actors, acting, or the theater',
                                            ["a penchant for dish throwing, door slamming, and other histrionic displays of temper 有倾向做出一些砸盘子、摔门和其他一些电视剧里的经典生气动作"],
                                            'melodramatic, operatic, stagy, theatrical',
                                            ['undramatic'])]),
                              Word('hive', "",
                                   [TestWay('n',
                                            '忙碌之地',
                                            'a place swarming with activity',
                                            ["The house was a hive of activity as we prepared for the party. 我们筹备派对时, 房子里很是熙熙攘攘。"]),
                                    TestWay('v', "",
                                            '储备, 积累',
                                            'to store up; accumulate')]),
                              Word('hoard', "",
                                   [TestWay('v',
                                            '贮藏, 秘藏',
                                            'to keep hidden or private',
                                            ["He's been hoarding empty yogurt containers all winter. 他整个冬天都在攒空酸奶瓶"],
                                            'cache, stash, stockpile, store, squirrel, stockpile',
                                            ['lavish'])]),
                              Word('hoary', "",
                                   [TestWay('adj',
                                            '极老的',
                                            'extremely old',
                                            ["hoary legends 上古传说"],
                                            'aged, antique, dateless, immemorial, antediluvian',
                                            'modern, new, recent')])])

list12_unit4 = VocabularyList([Word('hoax', "",
                                   [TestWay('n./v',
                                            '欺骗',
                                            'to cause to believe what is untrue',
                                            ["a skilled forger who hoaxed the art world into believing that the paintings were long-lost Vermeers 一个老道的骗子成功让艺术界相信那些画作是遗失多年的维米尔的真迹"],
                                            ['bamboozle', 'beguile', 'bluff', 'con', 'cozen', 'delude', 'dupe', 'fake out', 'gull', 'hoodwink', 'take in'])]),
                              Word('hodgepodge', "",
                                   [TestWay('n',
                                            '大杂烩',
                                            'a mixture of dissimilar ingredients; a jumble',
                                            ["a hodgepodge of styles 混搭风格", "the exhibit was a hodgepodge of mediocre art, bad art, and really bad art 整场展览就是中庸、烂和非常烂的艺术作品的大杂烩"],
                                            'agglomeration, assortment, collage, medley, mishmash, pastiche, potpourri')]),
                              Word('homage', "",
                                   [TestWay('n',
                                            '尊敬, 敬意',
                                            'expression of high regard: respect',
                                            ["Homage to Catalonia 向加泰罗尼亚致敬"],
                                            'commendation, eulogy, hymn, paean, panegyric, salutation, tribute, dithyramb',
                                            ['disrespect'])]),
                              Word('homely', "",
                                   [TestWay('adj',
                                            '其貌不扬的, 朴素简单的',
                                            'not attractive or good-looking',
                                            ["homely truth 朴素的真理"],
                                            'hideous, unappealing, unattractive, uncomely, unsightly',
                                            'pulchritudinous, aesthetic, attractive, beautiful, comely, gorgeous, handsome, knockout, lovely, pretty, ravishing, seemly, sightly, stunning, taking, well-favored')]),
                              Word('homily', "",
                                   [TestWay('n',
                                            '冗长乏味的道德讲演或训诫',
                                            'an idea or expression that has been used by many people',
                                            ["a TV movie filled with the usual hokey homilies about people triumphing over life's adversities 一档说教性质的、充满了介绍逆境中的人们如何成就自我的电视节目"],
                                            'banality, bromide, chestnut, cliché, groaner, platitude, shibboleth')]),
                              Word('homogenize', "",
                                   [TestWay('v',
                                            '使统一化',
                                            'to make agree with a single established standard or model',
                                            ["plans to homogenize the science curriculum in public high schools throughout the state 计划将全州的公立高中的课程安排统一化"],
                                            'formalize, homogenize, normalize, regularize')]),
                              Word('hone', "",
                                   [TestWay('v',
                                            '磨快',
                                            'to sharpen or smooth with a whetstone',
                                            ["honed the knife's blade to razor-like sharpness 把小刀磨得像剃刀一样锋利", "honed his crossword-puzzle skills by reading the dictionary 通过背字典把填词游戏的水平练得炉火纯青"],
                                            'edge, grind, strop, whet',
                                            ['blunt', 'dull'])]),
                              Word('hoodwink', "",
                                   [TestWay('vt',
                                            '欺骗',
                                            'to take in by deceptive means; deceive',
                                            ["Don't let yourself be hoodwinked into buying things you don't need. 别被忽悠着去买用不着的东西。"],
                                            'beguile, con, delude, dupe, fool, hoax, humbug',
                                            ['disabuse'])]),
                              Word('hortative', "",
                                   [TestWay('adj',
                                            '鼓励的',
                                            'giving exhortation')]),
                              Word('hovel', "",
                                   [TestWay('n',
                                            '茅屋',
                                            'a small, wretched, and often dirty house',
                                            synonyms = 'cabin, camp, hooch, hut, hutch, hutment, shanty')])])

list12_unit5 = VocabularyList([Word('hubris', "",
                                   [TestWay('n',
                                            '狂妄自大',
                                            'exaggerated pride or self-confidence',
                                            ["His failure was brought on by his hubris. 就是他的狂妄自大才导致了失败。"],
                                            antonyms = ['humility'])]),
                              Word('humble', "",
                                   [TestWay('adj',
                                            '谦逊的',
                                            'marked by meekness or modesty in behavior, attitude, or spirit; not arrogant or prideful',
                                            ["a medical scientist who remained remarkably humble even after winning the Nobel Prize 获得诺贝尔奖之后仍然保持谦逊的医学家"],
                                            'modest, unassuming, unpretentious, demure, down-to-earth',
                                            'arrogant, bumptious, conceited, egotistic, haughty, high-and-mighty, imperious, lordly, overweening, peremptory, pompous, presuming, presumptuous, pretentious, self-assertive, supercilious, superior, toplofty, uppish, uppity'),
                                    TestWay('adj',
                                            '顺从的, 谦卑的',
                                            'showing, expressing, or offered in a spirit of humility or unseemly submissiveness',
                                            ["please accept my humble thanks 请接受我的卑微的感谢"],
                                            'base, humble, menial, servile, slavish')]),
                              Word('humility', "",
                                   [TestWay('n',
                                            '谦卑, 谦逊',
                                            'the absence of any feelings of being better than others',
                                            ["Haughtiness invites disaster; humility receives benefit. 满招损, 谦受益"],
                                            'demureness, humbleness, lowliness, meekness, modesty',
                                            'arrogance, assumption, bumptiousness, hauteur, pomposity, presumption, superciliousness')]),
                              Word('humor', "",
                                   [TestWay('n',
                                            '幽默, 令人发笑的事物',
                                            'something that is or is designed to be comical or amusing',
                                            ["The speech is full of wit and humor. 演讲妙趣横生"],
                                            'comedy, comic, drollery, drollness, funniness, hilariousness',
                                            ['pathos']),
                                    TestWay('v',
                                            '迎合, 迁就',
                                            'to comply with the wishes or ideas of',
                                            ["Parents need to know how to humor kids when they are upset. 父母需要知道当孩子烦躁的时候怎么哄孩子"],
                                            'cater, gratify, indulge')]),
                              Word('hurricane', "",
                                   [TestWay('n',
                                            '飓风',
                                            'a violent rotating storm or system of winds',
                                            ["The hurricane struck the coast early today. 飓风今晨袭击了海岸"],
                                            ['storm', 'typhoon'],
                                            ['calm']),
                                    TestWay('n',
                                            '飓风般的事物, 引起动荡的事物',
                                            'something resembling a hurricane especially in its turmoil',
                                            ["economic news that unleashed a hurricane on the trading floor 在交易大厅掀起轩然大波的经济新闻"],
                                            'disturbance, furor, pandemonium, tumult, turmoil, uproar')]),
                              Word('husband', "",
                                   [TestWay('vt',
                                            '节俭, 勤俭持家',
                                            'to use sparingly or economically',
                                            ["Husbanding precious resources was part of rural life. 节俭使用珍贵的资源就是农村生活的一部分"],
                                            'budget, conserve, economize',
                                            'dissipate, lavish, prodigalize, squander, waste',
                                            'husbandly adj. 节俭的; husbandry n. 节俭')]),
                              Word('husk', "",
                                   [TestWay('n',
                                            '(果类或谷物的)外壳',
                                            'a usually dry or membranous outer covering (as a pod or one composed of bracts) of various seeds and fruits (as barley and corn)',
                                            ["a grey squirrel nibbling on a peanut husk 一个啃着花生壳的灰松鼠"],
                                            'bark, chaff, hull, shell',
                                            ['core', 'kernel']),
                                    TestWay('v',
                                            '剥去',
                                            'to remove the natural covering of',
                                            ["the tedious task of husking coconuts 无聊的任务——剥椰子"],
                                            'bark, flay, hull, shell, shuck, skin')]),
                              Word('husky', "",
                                   [TestWay('adj',
                                            '(尤指声音)沙哑的, 粗糙的',
                                            'hoarse or rough in quality',
                                            ["a voice husky with emotion 富有感情的沙哑声音"],
                                            'coarse, grating, gravelly, harsh, rasping, rusty, scratchy, throaty',
                                            ['mellifluous']), 
                                    TestWay('adj',
                                            '高大威猛的',
                                            'big and muscular',
                                            ["a very husky young man, built like a football player 一个体格像橄榄球运动员一样的高大的男孩"],
                                            'beefy, burly, hefty, muscular, powerful, strapping, rugged',
                                            ['dwarf'])]),
                              Word('hybrid', "",
                                   [TestWay('n',
                                            '杂交品种, 混合品种',
                                            'something of mixed origin or composition',
                                            ["a hybrid of medieval and Renaissance styles 中世纪和文艺复兴的混搭风"],
                                            'amalgam, bastard, compound, mixture, mule'),
                                    TestWay('adj',
                                            '杂交的',
                                            'being offspring produced by parents of different races, breeds, species, or genera',
                                            ["a hybrid rose called “American Beauty” 一种被称为“美国丽人”的杂交玫瑰"],
                                            ['crossbred', 'mongrel'],
                                            ['purebred'])]),
                              Word('hymn', "",
                                   [TestWay('n',
                                            '赞歌, 赞美诗',
                                            'a song of praise or joy',
                                            ["They sang a hymn of praise to God. 他们唱赞歌赞美上帝"],
                                            'eulogy, homage, hymn, ode, paean, panegyric, psalm, salutation, tribute',
                                            ['dirge', 'elegy']),
                                    TestWay('v',
                                            '赞美',
                                            'to proclaim the glory of',
                                            ["During the honeymoon following the inauguration, newspaper articles seemed to hymn the president's every move. 在上任后的“蜜月期”之中, 报纸新闻似乎在赞美总统的每一项措施"],
                                            'bless, carol, celebrate, emblazon, exalt, extol, glorify, laud, magnify, resound',
                                            'blame, censure, reprehend, reprobate')])])

list12_unit6 = VocabularyList([Word('hyperbole', "",
                                   [TestWay('n',
                                            '夸张',
                                            'a figure of speech in which exaggeration is used for emphasis or effect',
                                            ["The debate was carried on with increasing rhetorical hyperbole. 随着辩论的进行, 双方修辞当中的夸张越来越多"],
                                            'coloring, embellishment, embroidering, exaggeration, magnification, overstatement',
                                            ['understatement'])]),
                              Word('hypnotic', "",
                                   [TestWay('adj',
                                            '催眠的',
                                            'tending to cause sleep',
                                            ["Her eyes soon grew heavy from the hypnotic rhythm of the train's wheels. 伴随着催眠的铁轨声, 她很快就有了睡意"],
                                            'drowsy, narcotic, opiate, sleepy, slumberous, soporific',
                                            'stimulating, refreshing')]),
                              Word('hypocritical', "",
                                   [TestWay('adj',
                                            '虚伪的',
                                            'not being or expressing what one appears to be or express',
                                            ["It's hypocritical to say mean things behind someone's back, and then to act nice when you want something from her. 这种在背后说别人坏话、而有求于人时又装出另一副样子的人就是虚伪"],
                                            'artificial, backhanded, feigned, mealy-mouthed, phony, pretended, unctuous',
                                            'artless, candid, genuine, honest, sincere, undesigning, unfeigned',
                                            'hypocrite n. 虚伪的人, 伪君子')]),
                              Word('iconoclast', "",
                                   [TestWay('n',
                                            '特立独行的人',
                                            'a person who does not conform to generally accepted standards or customs',
                                            ["He was an iconoclast who refused to be bound by tradition. 他是个不愿被传统所束缚的叛逆者"],
                                            'bohemian, deviant, heretic, maverick, non-conformer',
                                            'conformer, conformist',
                                            'iconoclastic adj. 特立独行的')]),
                              Word('idolatrize', "",
                                   [TestWay('v',
                                            '(通常盲目)崇拜',
                                            'admires intensely and often blindly',
                                            ["Some teenagers idolatrized Hitler more than their own parents. 曾经有一些青少年崇拜希特勒超过自己的父母"],
                                            'adore, adulate, canonize, deify, dote, worship',
                                            'abhor, abominate, detest, dislike, hate, loathe',
                                            'idolatry n. 崇拜')]),
                              Word('idyll', "",
                                   [TestWay('n',
                                            '无忧无虑的生活',
                                            'a carefree episode or experience',
                                            ["a summer idyll on the coast of the Mediterranean 地中海岸的悠闲夏日"],
                                            'frisk, frolic, gambol, revel, lark')]),
                              Word('ignite', "",
                                   [TestWay('vt',
                                            '点燃',
                                            'to cause to burn; to set fire to',
                                            ["The bombs ignited a fire which destroyed some 60 houses. 炸弹引发的大火摧毁了大约60间房屋"],
                                            'enkindle, fire, inflame, kindle, light, torch',
                                            'douse, extinguish, quench, put out'),
                                    TestWay('vt',
                                            '激起, 唤起(感情等)',
                                            'to arouse the passions of',
                                            ["The insults ignited my anger. 那些侮辱让我倍感愤怒"],
                                            'arouse, incite, instigate, pique, spark, stimulate, stir',
                                            'appease, assuage, calm, conciliate, mollify, pacify, placate, propitiate, soothe')]),
                              Word('ignominy', "",
                                   [TestWay('n',
                                            '耻辱',
                                            'the state of having lost the esteem of others',
                                            ["He spent the remainder of his life in ignominy after being involved in a bribery scandal. 因为卷入了受贿丑闻当中, 他在耻辱中度过余生"],
                                            'discredit, disesteem, dishonor, disrepute, infamy, obloquy, odium, opprobrium, reproach, shame',
                                            'glory, honor, esteem, respect',
                                            'ignominious adj. 可鄙的')]),
                              Word('illiteracy', "",
                                   [TestWay('n',
                                            '文盲',
                                            'the condition of being unable to read and write',
                                            ["a nationwide campaign against illiteracy 全国扫盲运动"],
                                            ['ignorance'],
                                            ['learning', 'literacy'],
                                            'illiterate adj. 不识字的')]),
                              Word('illuminati', "",
                                   [TestWay('n',
                                            '智者',
                                            'persons who claim to be unusually enlightened',
                                            synonyms = 'clerisy, intellectual, intelligentsia, literati',
                                            antonyms = 'fool, dolt, dullard, idiot, simpleton'),
                                    TestWay('n',
                                            '精英',
                                            'individuals carefully selected as being the best of a class',
                                            ["a book launching party to which only New York's cultural illuminati were invited 一个只邀请了纽约上层文化精英的新书发布会"],
                                            'aristocracy, elite, upper crust')])])

list12_unit7 = VocabularyList([Word('illuminate', "",
                                   [TestWay('vt',
                                            '照明',
                                            'to make luminous or shining',
                                            ["to illuminate with a spotlight 用聚光灯照亮"],
                                            'bathe, beacon, emblaze, illume, illumine, irradiate, lighten',
                                            'blacken, darken, obfuscate'),
                                    TestWay('vt',
                                            '阐明',
                                            'to make plain or understandable',
                                            ["Roosevelt′s New Deal illuminates what the role of government is in Keynesian Economics. 罗斯福新政阐明了在凯恩斯主义中政府的作用"],
                                            'clarify, clear, construe, demonstrate, demystify, elucidate, explicate, expound, illustrate, interpret',
                                            ['obscure']),
                                    TestWay('vt',
                                            '启迪, 启发',
                                            'to provide (someone) with moral or spiritual understanding',
                                            ["how man is illuminated by a higher spirit 人们是如何被更高境界的思想开化的"],
                                            'edify, educate, enlighten, inspire, nurture',
                                            'confuse, perplex, puzzle',
                                            'illumination n. 照明; 启迪')]),
                              Word('illusory', "",
                                   [TestWay('adj',
                                            '幻觉的, 虚幻的',
                                            'produced by, based on, or having the nature of an illusion',
                                            ["the illusory definition of nationhood 国家的虚幻定义"],
                                            'chimerical, fanciful, fantastic, fictional, fictitious, imaginary, suppositious, supposititious, unreal',
                                            ['factual'],
                                            'illusion n. 幻觉')]),
                              Word('imbibe', "",
                                   [TestWay('v',
                                            '喝水, 摄取水分',
                                            'to take in (something liquid) through small openings',
                                            ["Plants can imbibe water through their roots. 植物可以通过它们的根摄取水分"],
                                            'drink, guzzle, hoist, quaff, sip, sponge',
                                            ['urinate', '排尿'])]),
                              Word('imbroglio', "",
                                   [TestWay('n',
                                            '困境, 复杂的局面',
                                            'an intricate or complicated situation',
                                            ["What investor would willingly become involved in this imbroglio? 怎样的投资者才会像这样明知山有虎, 偏向虎山行呢？"],
                                            'complexity, complication, embarrassment, entanglement, involvement, misunderstanding, quandary'),
                                    TestWay('n',
                                            '纷争',
                                            'an often noisy or angry expression of differing opinions',
                                            ["an imbroglio involving some big names in the entertainment industry 一场涉及娱乐圈数位明星的纷争"],
                                            'altercation, controversy, disagreement, dispute, fight, quarrel, squabble, wrangle',
                                            ['harmony'])]),
                              Word('imitation', "",
                                   [TestWay('n',
                                            '仿制品',
                                            'something that is made to look exactly like something else',
                                            ["usually wore imitations of her costly jewels 通常只戴她那些贵重珠宝的复刻品"],
                                            'clone, copy, dupe, duplication, facsimile, mock, reduplication, replica, replication, reproduction',
                                            'archetype, original, prototype',
                                            'imitating adj. 仿制的')]),
                              Word('immaculate', "",
                                   [TestWay('adj',
                                            '干净的, 纯净的',
                                            'free from dirt or stain; free from any trace of the coarse or indecent',
                                            ["an immaculate soul 一个纯净的灵魂"],
                                            'antiseptic, chaste, clean, decent, modest, pristine, pure, spotless, stainless, virgin',
                                            'coarse, indecent, obscene, vulgar, besmirched, dirty, filthy, foul, spotted, stained, sullied'),
                                    TestWay('adj',
                                            '完美的, 没有任何错误的',
                                            'being entirely without fault or flaw',
                                            ["an immaculate rendering of the Queen of the Night ’s aria (《魔笛》中)夜后咏叹调的完美演绎"],
                                            'absolute, faultless, flawless, impeccable, indefectible, irreproachable, perfect, seamless, unblemished',
                                            'amiss, defective, faulty, flawed, imperfect')]),
                              Word('immanent', "",
                                   [TestWay('adj',
                                            '内在的',
                                            'being a part of the innermost nature of a person or thing',
                                            ["Beauty is not something imposed but something immanent. 美丽是内在的品格而非外加的东西"],
                                            'constitutional, essential, inborn, inbred, indigenous, ingrained, innate, integral, intrinsic, natural',
                                            'adventitious, extrinsic, extraneous')]),
                              Word('immaterial', "",
                                   [TestWay('adj',
                                            '非实体的',
                                            'not composed of matter',
                                            ["It is only possible to study immaterial forces like gravity by observing their effects on the physical world. 要研究那些非实体的作用力——例如万有引力, 只能观察它们对于现实世界的影响"],
                                            'ethereal, formless, incorporeal, insubstantial, nonmaterial, spiritual',
                                            'bodily, corporeal, material, physical, substantial'),
                                    TestWay('adj',
                                            '无关的, 不重要的',
                                            'of no importance or relevance',
                                            ["While undoubtedly upsetting, that story is immaterial to the question of why you are late. 尽管那个故事的确很让人遗憾, 但是和你为什么迟到没有半点关系"],
                                            'extraneous, impertinent, inapplicable, inapposite, irrelevant',
                                            'applicable, apposite, apropos, germane, pertinent, relevant, crucial, important, significant')]),
                              Word('immature', "",
                                   [TestWay('adj',
                                            '未完全发展的, 未发育成熟的',
                                            'lacking complete growth, differentiation, or development',
                                            ["immature frogs are called “tadpoles” 为发育成熟的青蛙被称为“蝌蚪”"],
                                            'adolescent, juvenile, youngish, youthful'),
                                    TestWay('adj',
                                            '(思维、举止)不够成熟的',
                                            'lacking in adult experience or maturity',
                                            ["Many high school students are still too immature to foresee the consequences of their actions. 很多高中生还是不够成熟, 不能意识到他们的行为所带来的后果"],
                                            'green, inexperienced, puerile, raw, unfledged, unripe',
                                            'adult, experienced, mature, ripe')]),
                              Word('immemorial', "",
                                   [TestWay('adj',
                                            '古老的',
                                            'dating or surviving from the distant past',
                                            ["a modern version of an immemorial myth 一个远古传说的现代版本"],
                                            'aged, age-old, antediluvian, antique, dateless, hoary, old, venerable',
                                            'contemporary, modern, recent')])])

list12_unit8 = VocabularyList([Word('immune', "",
                                   [TestWay('adj',
                                            '不易被感染的, 有免疫力的',
                                            'of, relating to, or having resistance to infection',
                                            ["The blood test will tell whether you are immune to the disease. 验血可以判断你是否对这种疾病免疫"],
                                            ['resistant'],
                                            ['susceptible', 'vulnerable']),
                                    TestWay('adj',
                                            '不受影响的',
                                            'not affected by a given influence',
                                            ["immune to persuasion 不听劝"],
                                            'insusceptible, unaffected, unresponsive',
                                            'ductile, pliable, pliant, yielding'),
                                    TestWay('adj',
                                            '不受约束的',
                                            'not subject to an obligation imposed on others',
                                            ["immune from taxation 免税"],
                                            ['exempt', 'free'],
                                            ['liable', 'responsible'],
                                            'immunity n. 免疫性')]),
                              Word('immure', "",
                                   [TestWay('v',
                                            '监禁, 禁闭',
                                            'to confine within or as if within walls',
                                            ["immure oneself for GRE 闭门苦读GRE"],
                                            'bastille, confine, constrain, incarcerate, intern, jail, imprison',
                                            'discharge, release, enfranchise, free, liberate')]),
                              Word('immutable', "",
                                   [TestWay('adj',
                                            '不可变的',
                                            'not capable of changing or being changed',
                                            ["One of the immutable laws of television is that low ratings inevitably lead to cancellation. 电视行业中一个不变的原则就是: 低收视率的节目必然会被撤掉"],
                                            'constant, fixed, inalterable, inflexible, invariable, unalterable, unchangeable',
                                            'alterable, changeable, elastic, flexible, mutable, variable',
                                            'immutability n. 不变性')]),
                              Word('impassive', "",
                                   [TestWay('adj',
                                            '冷漠的, 无感情的',
                                            'giving no sign of feeling or emotion',
                                            ["She remained impassive as the officers informed her of her son's death. 她面不改色地听着警官宣读她儿子的死讯"],
                                            'affectless, apathetic, cold-blooded, deadpan, emotionless, numb, phlegmatic, stoic, undemonstrative',
                                            'demonstrative, emotional, fervent, fervid, impassioned, passionate, vehement')]),
                              Word('impeccable', "",
                                   [TestWay('adj',
                                            '无罪的',
                                            'free from sin, guilt or blame',
                                            ["the belief that there can be no such thing as an impeccable soul 不相信存在无罪的灵魂"],
                                            'blameless, clear, guiltless, inculpable, pure, sinless',
                                            ['guilty', 'sinful']),
                                    TestWay('adj',
                                            '无瑕的, 无可挑剔的',
                                            'free from fault or blame',
                                            ["She had impeccable taste in clothes. 她有着无可挑剔的穿衣品味"],
                                            'absolute, faultless, flawless, immaculate, indefectible, irreproachable, perfect, seamless, unblemished',
                                            'amiss, defective, faulty, flawed, imperfect')]),
                              Word('impecunious', "",
                                   [TestWay('adj',
                                            '贫穷的',
                                            'having very little or no money',
                                            ["They were so impecunious that they couldn't afford to give one another even token Christmas gifts. 他们穷到了连象征性的圣诞礼物都互送不起的地步"],
                                            'beggared, destitute, impoverished, indigent, necessitous, needy, penniless, penurious, threadbare',
                                            'affluent, flush, opulent, rich, wealthy')]),
                              Word('impede', "",
                                   [TestWay('v',
                                            '妨碍, 阻碍',
                                            'to interfere with or slow the progress of',
                                            ["Storms at sea impeded our expedition. 海上的风暴阻碍了我们的远征"],
                                            'clog, embarrass, encumber, fetter, hinder, inhibit, obstruct, retard, shackle, stymie, trammel',
                                            'aid, assist, facilitate, help',
                                            'impediment n. 障碍, 阻碍')]),
                              Word('impending', "",
                                   [TestWay('adj',
                                            '即将发生的',
                                            'being soon to appear or take place',
                                            ["an impending celebration of the 100th anniversary of the college's founding 即将来临的百年校庆"],
                                            'approaching, coming, imminent, nearing, pending, proximate, upcoming, around the corner',
                                            'late, recent, distant, remote')]),
                              Word('impenetrable', "",
                                   [TestWay('adj',
                                            '不可渗透的, 不可穿透的',
                                            'impossible to get through or into',
                                            ["The ancient temple was surrounded by vast stretches of impenetrable jungle. 包围着古老的神庙的是密不透风的灌木丛"],
                                            'impassable, impermeable, impervious, impregnable',
                                            'passable, penetrable, permeable, pervious'),
                                    TestWay('adj',
                                            '难以理解的',
                                            'incapable of being comprehended',
                                            ["The textbook's language is completely impenetrable, at least to me. 至少在我看来, 这个教材就是天书"],
                                            'arcane, cryptic, enigmatic, incomprehensible, inscrutable, unfathomable, ungraspable, unintelligible',
                                            'fathomable, intelligible, understandable')]),
                              Word('impenitent', "",
                                   [TestWay('adj',
                                            '不悔悟的',
                                            'not feeling or expressing humble or regretful pain or sorrow for sins or offenses',
                                            ["remain impenitent about her criminal past 对她过去所犯罪行执迷不悟"],
                                            'remorseless, regretless, shameless, unashamed, unrepentant',
                                            'contrite, regretful, remorseful, rueful, penitent')])])

list12_unit9 = VocabularyList([Word('imperative', "",
                                   [TestWay('n',
                                            '命令',
                                            'a statement of what to do that must be obeyed by those concerned',
                                            ["a secretary of defense who was fond of issuing harshly worded imperatives 一个很喜欢发布措辞严厉的命令的国防部长"],
                                            'command, decree, dictate, direction, directive, instruction, order, word'),
                                    TestWay('adj',
                                            '命令的, 强制性的',
                                            "forcing one's compliance or participation by or as if by law",
                                            ["requests that grew more and more imperative 命令性越来越强的请求"],
                                            'compulsory, forced, involuntary, obligatory, peremptory, required',
                                            'optional, voluntary'),
                                    TestWay('adj',
                                            '迫切的',
                                            'needing immediate attention',
                                            ["an imperative need for medical supplies in the earthquake-ravaged country 地震灾区国家对于医疗物资的迫切需求"],
                                            'clamant, compelling, critical, crying, emergent, exigent, imperious, importunate, pressing, urgent',
                                            'noncritical, unimportant'),
                                    TestWay('adj',
                                            '必要的',
                                            'impossible to do without',
                                            ["Proper equipment is imperative for the success of this chemical experiment. 合适的仪器是这个化学实验成功必不可少的条件"],
                                            'indispensable, necessary, necessitous, requisite, vital',
                                            'dispensable, inessential, needless, unnecessary')]),
                              Word('imperial', "",
                                   [TestWay('adj',
                                            '帝国的, 帝王的',
                                            'of, relating to, or suggestive of an empire or a sovereign, especially an emperor or empress',
                                            ["Imperial College London 帝国理工学院"],
                                            'kingly, queenly, regal, royal'),
                                    TestWay('adj',
                                            '巨大的, 令人惊叹的',
                                            'large and impressive in size, grandeur, extent, or conception',
                                            ["envisioned an imperial city that would rival the capitals of Europe for beauty and magnificence 幻想着一个比欧洲各国首都更为动人和壮丽的巨大城市"],
                                            'august, epic, glorious, grand, imposing, magnificent, monumental, noble, splendid',
                                            'common, humble, inferior, low')]),
                              Word('imperious', "",
                                   [TestWay('adj',
                                            '爱发号施令的',
                                            'fond of ordering people around',
                                            ["an imperious little boy who liked to tell the other scouts what to do 一个爱发号施令的小男孩, 总是喜欢指挥别的童子军做事"],
                                            'authoritarian, autocratic, despotic, dictatorial, domineering, masterful, tyrannical'),
                                    TestWay('adj',
                                            '傲慢的, 专横的',
                                            'arrogantly domineering or overbearing',
                                            ["an imperious movie star who thinks she's some sort of goddess 一个把自己当成某种女神的傲慢的影星"],
                                            'arrogant, bumptious, haughty, lofty, lordly, peremptory, pompous, presumptuous, supercilious, superior',
                                            'humble, lowly, modest'),
                                    TestWay('adj',
                                            '迫切的',
                                            'intensely compelling',
                                            ["As war casualties mounted, the need for trained nurses became imperious. 随着战争伤亡人数的攀升, 对于受训护士的需求变得愈发迫切"],
                                            'clamant, compelling, critical, crying, dire, emergent, exigent, imperative, importunate, pressing, urgent',
                                            'noncritical, unimportant')]),
                              Word('impertinent', "",
                                   [TestWay('adj',
                                            '无关紧要的',
                                            'not having a clear decisive relevance to the matter in hand',
                                            ["Your résumé needlessly lists extracurricular experiences that are impertinent to the PhD program for which you are applying. 你的简历里列出的一些课外活动和你申请的博士项目是毫不相关的"],
                                            'extraneous, immaterial, inapplicable, inapposite, irrelevant',
                                            'germane, pertinent, relevant, crucial, important, significant'),
                                    TestWay('adj',
                                            '粗鲁无礼的, 大胆的',
                                            'given to or characterized by insolent rudeness',
                                            ["I don't like strangers who ask impertinent questions. 我很讨厌那些问无礼问题的陌生人"],
                                            'audacious, bold, brash, brassbound, brassy, brazen, impudent, insolent',
                                            'meek, mousy, retiring, shy, timid'),
                                    TestWay('adj',
                                            '不守礼节的, 不为他人着想的',
                                            'showing a lack of manners or consideration for others',
                                            ["impertinent salesmen who telephone people during the dinner hour 在就餐时间打电话骚扰别人的无礼销售员"],
                                            'discourteous, disrespectful, inconsiderate, rude, thoughtless',
                                            'civil, courteous, genteel, gracious, mannerly, polite, considerate')]),
                              Word('imperturbable', "",
                                   [TestWay('adj',
                                            '沉着冷静的, 淡定的',
                                            'marked by extreme calm, impassivity, and steadiness',
                                            ["The chef was absolutely imperturbable—even when the kitchen caught on fire. 这个厨师可谓淡定到了极致——他连厨房着火的时候都依然沉着"],
                                            'collected, composed, cool, disimpassioned, nonchalant, unflappable, unruffled',
                                            'choleric, touchy')]),
                              Word('impervious', "",
                                   [TestWay('adj',
                                            '不可渗透的, 不可穿透的',
                                            'not allowing entrance or passage',
                                            ["The material for this coat is supposed to be impervious to rain. 这件大衣的材料应该是能防雨的"],
                                            'impassable, impenetrable, impermeable, impregnable',
                                            'passable, penetrable, permeable, pervious'),
                                    TestWay('adj',
                                            '不能被破坏的',
                                            'not capable of being damaged or harmed',
                                            ["a carpet impervious to rough treatment 耐用的地毯"],
                                            'bulletproof, imperishable, indestructible, inextinguishable, invulnerable',
                                            'delicate, sensitive, vulnerable'),
                                    TestWay('adj',
                                            '不为所动的',
                                            'not capable of being affected or disturbed',
                                            ["These sailors are impervious to fear. 这些水手无所畏惧"],
                                            'immune, insusceptible, unaffected, unresponsive',
                                            'ductile, pliable, pliant, yielding')]),
                              Word('impetuous', "",
                                   [TestWay('adj',
                                            '冲动的, 性急的, 轻率的',
                                            'marked by impulsive vehemence or passion',
                                            ["He is young and impetuous. 他年轻易冲动"],
                                            'ardent, hasty, headlong, impassioned, impulsive, passionate, rash, vehement',
                                            'cautious, circumspect, wary'),
                                    TestWay('adj',
                                            '剧烈的, 猛烈的',
                                            'marked by force and violence of movement or action',
                                            ["an impetuous wind 猛烈的风"],
                                            'abrupt, hasty, hurried, precipitate, precipitous, rushing, sudden, violent',
                                            'calm, halcyon, placid, quiet',
                                            'impetus n. 推动力')]),
                              Word('impious', "",
                                   [TestWay('adj',
                                            '不敬神的',
                                            'lacking reverence for holy or sacred matters',
                                            ["made impious remarks about the church 对教会做出不敬的评论blasphemous, irreverent, profane, sacrilegious"],
                                            'blasphemous, irreverent, profane, sacrilegious',
                                            'pious, reverent',
                                            'impiety n. (对神的)不敬')]),
                              Word('implacable', "",
                                   [TestWay('adj',
                                            '固执的',
                                            'sticking to an opinion, purpose, or course of action in spite of reason, arguments, or persuasion',
                                            synonyms = 'adamant, dogged, headstrong, intransigent, mulish, obdurate, pertinacious, stubborn, unyielding',
                                            antonyms = 'acquiescent, compliant, flexible, pliable, pliant, yielding'),
                                    TestWay('adj',
                                            '无法平息的',
                                            'not capable of being appeased, significantly changed, or mitigated',
                                            ["an implacable enemy 无法与之和解的敌人"],
                                            'determined, grim, relentless, unappeasable',
                                            'placable')]),
                              Word('implement', "",
                                   [TestWay('n',
                                            '工具',
                                            'a device used in the performance of a task',
                                            ["gardening implements such as hoes, spades, and pruners 诸如锄头、铲子和修枝剪一类的园艺工具"],
                                            'apparatus, device, instrument, tool, utensil'),
                                    TestWay('v',
                                            '执行, 实施',
                                            'to put into practical effect; carry out',
                                            ["implement the new online application procedures 实行新的网申程序"],
                                            'administer, apply, effect, enforce, execute, invoke, perform',
                                            'cancel, repeal, rescind, revoke',
                                            'implementation n. 执行, 履行')])])

list12_unit10 = VocabularyList([Word('implode', "",
                                   [TestWay('v',
                                            '剧烈收缩, 坍缩, 内爆',
                                            'to collapse inward violently',
                                            ["The flask imploded during the vacuum distilling. 做低压蒸馏的时候烧瓶发生了内爆"],
                                            'buckle, founder, tumble, yield',
                                            'explode')]),
                              Word('imposing', "",
                                   [TestWay('adj',
                                            '宏伟壮丽的',
                                            'impressive in size, bearing, dignity, or grandeur',
                                            ["The corporation's imposing headquarters were designed by one of the nation's cutting-edge architects. 这家公司宏伟壮丽的总部是由该国最优秀的建筑师设计的"],
                                            'august, epic, glorious, grand, imperial, magnificent, monumental, noble, splendid',
                                            'common, humble, inferior, low')]),
                              Word('importune', "",
                                   [TestWay('vt',
                                            '恳求, 迫切请求',
                                            'to make a request to (someone) in an earnest or urgent manner',
                                            ["beggars importuning passers-by 在恳求着过路人的乞丐"],
                                            'appeal,beseech, besiege, conjure, entreat, impetrate, implore, petition, plead, pray, solicit, supplicate',
                                            'demand')]),
                              Word('impostor', "",
                                   [TestWay('n',
                                            '冒充者',
                                            'one that assumes false identity or title for the purpose of deception',
                                            ["The man who claimed to be a prince turned out to be an impostor. 那个自称是王子的人原来是冒充的"],
                                            'charlatan, fake, fraud, hoaxer, mountebank, phony, pretender, quack, sham')]),
                              Word('impotent', "",
                                   [TestWay('adj',
                                            '无生育能力的',
                                            'unable to produce fruit or offspring',
                                            ["Most mules are impotent. 绝大多数的骡子都无法生育"],
                                            'barren, fruitless, infertile, unfruitful',
                                            'fecund, fertile, fruitful, productive'),
                                    TestWay('adj',
                                            '无力的, 无能的',
                                            'lacking in power, strength, or vigor',
                                            ["an impotent ruler who was just a figurehead 一个无能的傀儡统治者"],
                                            'hamstrung, handcuffed, helpless, impuissant, paralyzed, weak',
                                            'mighty, potent, powerful, puissant, strong')]),
                              Word('imprecise', "",
                                   [TestWay('adj',
                                            '不精确的',
                                            'not precise',
                                            ["incomplete and imprecise satellite data 既不完整又不精确的卫星数据"],
                                            'approximate, inaccurate, loose, squishy',
                                            'accurate, exact, precise, veracious',
                                            'imprecision n. 不准确, 不精确')]),
                              Word('impromptu', "",
                                   [TestWay('n',
                                            '即席的表演',
                                            'something, such as a speech, that is made or done extemporaneously',
                                            synonyms = 'improvisation, extemporization'),
                                    TestWay('adj',
                                            '即席的, 即兴的',
                                            'composedwithout previous preparation',
                                            ["Our dinner guest thanked us with an impromptu song. 客人们即兴高歌一首以表达谢意"],
                                            'ad-lib, extemporary, improvised, offhand, unplanned, unpremeditated, unprepared, unrehearsed',
                                            'considered, planned, premeditated, prepared, rehearsed')]),
                              Word('improvise', "",
                                   [TestWay('v',
                                            '即兴而作',
                                            'to invent, compose, or perform with little or no preparation',
                                            ["Since the award was a complete surprise, I improvised an acceptance speech. 因为那个奖项完全是个惊喜, 所以我即兴发表了一个获奖演说"],
                                            'ad-lib, extemporize',
                                            'plan, premeditate')]),
                              Word('imprudent', "",
                                   [TestWay('adj',
                                            '不明智的',
                                            'lacking discretion, wisdom, or good judgment',
                                            ["an imprudent investment ha made many years ago 他许多年前做的一笔不明智的投资"],
                                            'impolitic, inadvisable, indelicate, injudicious, tactless, undiplomatic, unwise',
                                            'advisable, politic, prudent, tactical, wise')]),
                              Word('impudent', "",
                                   [TestWay('adj',
                                            '放肆大胆的, 无礼的',
                                            'marked by contemptuous or cocky boldness or disregard of others',
                                            ["Some children were well behaved, while others were impudent. 一些孩子表现得很得体, 另一些则很无礼"],
                                            'audacious, barefaced, bold, brash, brazen, impertinent, insolent, shameless',
                                            'courteous, genteel, mannerly, polite, proper',
                                            'impudencen. 放肆无礼')])])


LIST12 = VocabularyList(list12_unit1.words+list12_unit2.words+list12_unit3.words+list12_unit4.words+list12_unit5.words+list12_unit6.words+list12_unit7.words+list12_unit8.words+list12_unit9.words+list12_unit10.words)
