#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list9_unit1 = VocabularyList([Word('entangle', "",
                                   [TestWay('vt',
                                            '卷入, 纠缠',
                                            'to twist together into a usually confused mass',
                                            ["we managed to entangle the string of lights into a hopeless mess of wires 我们将小灯泡的线纠缠成了一堆"],
                                            ['interlace', 'intertwist', 'knot', 'snarl', 'tangle']),
                                    TestWay('v',
                                            '使变复杂或困难',
                                            'to make complex or difficult',
                                            ["the history of Alexander the Great is entangled by variant accounts of his exploits 亚历山大大帝的生平历史被不同版本的记录搞得很纠结"],
                                            ['complexify', 'perplex', 'sophisticate'],
                                            ['simplify', 'streamline'])]),
                              Word('enthusiasm', "",
                                   [TestWay('n',
                                            '热情, 兴趣',
                                            'urgent desire or interest',
                                            ["in my enthusiasm to get going, I forgot to pack any foul-weather clothing 在强烈的出游热情下, 我忘记带上防备坏天气的衣服了"],
                                            ['ardor', 'avidity', 'desirousness', 'impatience', 'keenness', 'lust', 'thirst'],
                                            ['apathy', 'indifference'],
                                            'enthusiastic adj. 热情的 【反】halfhearted 心不在焉的')]),
                              Word('entice', "",
                                   [TestWay('vt',
                                            '诱使',
                                            'to attract artfully or adroitly or by arousing hope or desire: tempt; lure',
                                            ["entice sb into doing sth 诱使某人做某事"],
                                            ['allure', 'bait', 'beguile', 'decoy', 'seduce', 'solicit', 'tempt', 'lead on'],
                                            other_form = 'enticing adj. 诱人的 【反】formidable 可怕的')]),
                              Word('entrance', "",
                                   [TestWay('n',
                                            '进入权, 进入许可',
                                            'the means or right of entering or participating in',
                                            ["entrance to the club is by invitation only 该俱乐部只接受受邀入会"],
                                            ['access', 'admission', 'admittance', 'gateway', 'ingress', 'passport', 'ticket']),
                                    TestWay('vt',
                                            '使入迷',
                                            'to fill with delight, wonder, or enchantment',
                                            ["be entranced by the view 陶醉于景色"],
                                            ['enrapture', 'enthrall', 'ravish', 'transport', 'carry away'],
                                            ['bore', 'disappoint', 'disgust', 'repel', 'repulse'],
                                            'entrancing adj. 使人欣喜的 【反】unprepossessing 不讨人喜欢的')]),
                              Word('entrap', "",
                                   [TestWay('vt',
                                            '诱骗',
                                            'to lure into a compromising statement or act',
                                            ["a string of inconsistent statements finally entrapped the witness 一系列不一致的陈述最终蒙骗了目击者"],
                                            ['ensnare', 'ensnarl', 'entoil', 'mesh', 'net', 'snare', 'catch up'],
                                            ['disentangle', 'untangle'])]),
                              Word('entreat', "",
                                   [TestWay('v',
                                            '恳求',
                                            'to plead with especially in order to persuade, ask urgently',
                                            ["entreated his boss for another chance 恳求老板再给一次机会"],
                                            ['beseech', 'besiege', 'conjure', 'implore', 'importune', 'solicit', 'supplicate', 'plead to', 'appeal to'])]),
                              Word('enunciate', "",
                                   [TestWay('vi',
                                            '清晰地说',
                                            'to utter articulate sounds',
                                            ["enunciate your words, and then you won't have to repeat them so often 把话说清楚, 你就不用经常重复了"],
                                            ['articulate']),
                                    TestWay('v',
                                            '公开宣布, 宣称',
                                            'to make known openly or publicly',
                                            ["today the President enunciated a new foreign policy 总统在今天宣布了一项新的对外政策"],
                                            ['annunciate', 'broadcast', 'declare', 'herald', 'proclaim', 'promulgate', 'publicize', 'release', 'give out'])]),
                              Word('ephemeral', "",
                                   [TestWay('adj',
                                            '短暂的',
                                            'lasting a very short time',
                                            ["ephemeral pleasures 暂时的压力"],
                                            ['evanescent', 'fleeting', 'impermanent', 'temporary', 'transient', 'transitory', 'fugacious', 'fugitive'],
                                            ['eternal', 'permanent', 'perpetual', 'enduring', 'everlasting', 'ceaseless', 'immortal', 'undying'])]),
                              Word('epic', "",
                                   [TestWay('adj',
                                            '宏大的, 超凡脱俗的',
                                            'surpassing the usual or ordinary, particularly in scope or size',
                                            ["his genius was epic 他聪明过人"],
                                            ['august', 'grandiose', 'imposing', 'magnificent', 'majestic', 'monumental'],
                                            ['humble', 'unheroic', 'unimpressive', 'modest'])]),
                              Word('epicure', "",
                                   [TestWay('n',
                                            '美食家',
                                            'one with sensitive and discriminating tastes especially in food or wine',
                                            ["Thomas Jefferson was one of America's first great epicures 托马斯·杰斐逊算得上是美国早期美食家一枚"],
                                            ['bon vivant', 'gastronomist', 'gourmand', 'gourmet'])])])

list9_unit2 = VocabularyList([Word('epigram', "",
                                   [TestWay('n',
                                            '机智的短诗, 警句',
                                            'a short, witty poem expressing a single thought or observation',
                                            ["Benjamin Franklin's most famous epigram, “Remember that time is money” 本杰明·富兰克林最著名的警句就是, 时间就是金钱"],
                                            ['adage', 'aphorism', 'apothegm', 'byword', 'maxim', 'proverb'])]),
                              Word('epilogue', "",
                                   [TestWay('n',
                                            '文学作品的结局',
                                            'a concluding section that rounds out the design of a literary work',
                                            antonyms = ['preface']),
                                    TestWay('n',
                                            '戏剧的收场白',
                                            'the final scene of a play that comments on or summarizes the main action',
                                            synonyms = ['coda'])]),
                              Word('epithet', "",
                                   [TestWay('n',
                                            '外号, 绰号',
                                            'a descriptive or familiar name given instead of or in addition to the one belonging to an individual; a disparaging or abusive word or phrase',
                                            ["King Richard I of England was given the very laudatory epithet “the Lion-Hearted” 英王理查一世因英勇大胆被赞誉为“狮心理查”"],
                                            ['alias', 'cognomen', 'sobriquet'])]),
                              Word('epitomize', "",
                                   [TestWay('v',
                                            '摘要',
                                            'to make into a short statement of the main points (as of a report)',
                                            ["his personal code of behavior on the playing field is epitomized by his favorite saying, Nice guys finish last. 他在赛场上的座右铭是: 好男坚持到底。"],
                                            ['abstract', 'digest', 'encapsulate', 'outline', 'recapitulate', 'synopsize', 'sum up']),
                                    TestWay('v',
                                            '代表, 体现, 是…的典型范例',
                                            'to represent in visible form, to be a typical example of',
                                            ["the Parthenon in Athens epitomizes the ancient Greek ideal of architectural beauty 雅典的巴特农神庙体现了古希腊对于建筑美感的理念", "behavior that epitomizes selfishness 典型的自私行为"],
                                            ['body', 'express', 'externalize', 'incarnate', 'incorporate', 'instantiate', 'manifest', 'materialize', 'substantiate'])]),
                              Word('equable', "",
                                   [TestWay('adj',
                                            '(脾气、性情)温和的',
                                            'not easily disturbed; serene',
                                            ["equable temperament 温和的性情"],
                                            ['balmy', 'genial', 'gentle', 'moderate', 'temperate'],
                                            ['harsh', 'inclement', 'intemperate', 'severe'],
                                            'equanimity n.温和 【反】agitation, excitability 激动')]),
                              Word('equity', "",
                                   [TestWay('n',
                                            '不偏不倚, 公平',
                                            'lack of favoritism toward one side or another',
                                            ["the lower wages paid to women for equal work violated the notion of equity 同等工作付给女性更低的报酬违背了公平的理念"],
                                            ['disinterestedness', 'equity', 'evenhandedness', 'fairness', 'impartiality', 'neutrality', 'nonpartisanship'],
                                            ['bias', 'favoritism', 'nonobjectivity', 'one-sidedness', 'partiality', 'partisanship', 'prejudice'],
                                            'equitable adj.公平的 【反】biased, discriminatory 偏袒的, 差别对待的')]),
                              Word('equivalent', "",
                                   [TestWay('adj./n',
                                            '等价的, 相等的',
                                            'equal in force, amount, or value',
                                            ["that huge mansion is the equivalent of five ordinary houses 那栋巨大的公馆有五套一般户型的房子那么大"],
                                            ['coequal', 'coordinate', 'counterpart', 'peer', 'rival', 'parallel'])]),
                              Word('equivocate', "",
                                   [TestWay('vi',
                                            '(带有欺骗目的地)模棱两可地说, 说谎话',
                                            'to use equivocal language especially with intent to deceive',
                                            ["When asked about his tax plan, the candidate didn't equivocate. 当被问到税收方案时, 候选人直言不讳。"],
                                            ['fudge', 'hedge', 'weasel', 'prevaricate', 'palter'],
                                            ['communicate straightforwardly'],
                                            'equivocal adj. 模棱两可的:  open to two or more interpretations and often intended to mislead; ambiguous. 【派】equivocation n. 模棱两可的话 【反】clarity 清楚')]),
                              Word('erode', "",
                                   [TestWay('v',
                                            '侵蚀, 慢慢减少',
                                            'to consume or wear away gradually',
                                            ["flooding eroded the hillside 洪水冲刷着山岭", "inflation eroding buying power 通货膨胀导致购买力下降"],
                                            ['corrode', 'fret', 'gnaw', 'nibble', 'bite at'])]),
                              Word('errant', "",
                                   [TestWay('adj',
                                            '居无定所的',
                                            'traveling from place to place',
                                            ["the errant gunslinger as a standard character in western novels 在西部题材小说中, 叛逆的持枪歹徒是经典形象"],
                                            ['ambulant', 'fugitive', 'nomadic', 'perambulatory', 'roaming', 'roving', 'vagabond', 'vagrant', 'wandering']),
                                    TestWay('adj',
                                            '误入歧途的, 犯错误的',
                                            'straying from the proper course or standards',
                                            ["errant youngsters 误入歧途的青少年"],
                                            ['misbehaving', 'mischievous'],
                                            ['behaved', 'behaving', 'nice', 'orderly'])])])

list9_unit3 = VocabularyList([Word('erratic', "",
                                   [TestWay('adj',
                                            '善变的',
                                            'not staying constant',
                                            ["business at the fast-food restaurant has been so erratic lately that the manager never knows how much staff to have on hand 快餐店的生意最近非常起伏以至于经理也不清楚需要多少人手"],
                                            ['changing', 'fluctuating', 'irregular', 'unequal', 'unstable', 'unsteady', 'varying'],
                                            ['changeless', 'constant', 'stable', 'steady', 'unchanging', 'unvarying']),
                                    TestWay('adj',
                                            '异常的, 不同寻常的',
                                            'different from the ordinary in a way that causes curiosity or suspicion',
                                            ["the key to the code was the erratic punctuation the killer used 解开密码的关键是杀手使用的不同寻常的标点符号"],
                                            ['bizarre', 'eccentric', 'offbeat', 'outlandish', 'out-of-the-way', 'peculiar', 'quaint', 'queer', 'remarkable', 'screwy', 'spaced-out', 'way-out', 'weird'])]),
                              Word('erudite', "",
                                   [TestWay('adj',
                                            '博学的',
                                            'characterized by erudition; learned',
                                            ["an erudite scholar 渊博的学者"],
                                            ['knowledgeable', 'learned', 'lettered', 'literate', 'scholarly', 'well-read'],
                                            ['ignorant', 'unlettered', 'benighted', 'illiterate', 'uneducated', 'unscholarly'])]),
                              Word('escalate', "",
                                   [TestWay('vi',
                                            '(战争等)升级, 扩大',
                                            'to increase in extent, volume, number, amount, intensity, or scope',
                                            ["We don’t want to escalate the war. 我们不想使战争扩大。"],
                                            ['aggrandize', 'amplify', 'augment', 'boost', 'expand', 'pump up', 'build up'],
                                            ['wane', 'diminish'])]),
                              Word('eschew', "",
                                   [TestWay('v',
                                            '刻意避开；戒绝',
                                            'to avoid habitually especially on moral or practical grounds',
                                            ["the minister eschews involvement in local politics, since he doesn't want to diminish his moral authority in the community 首相回避参与当地政治, 因为他不想降低其道德权威"],
                                            ['dodge', 'elude', 'evade', 'shirk', 'shun', 'weasel out of'],
                                            ['embrace', 'greet', 'welcome', 'habitually indulge in', 'seek'])]),
                              Word('esoteric', "",
                                   [TestWay('adj',
                                            '深奥难懂的',
                                            'difficult for one of ordinary knowledge or intelligence to understand',
                                            ["esoteric terminology 深奥难懂的专业术语"],
                                            ['abstruse', 'arcane', 'hermetic', 'recondite'],
                                            ['shallow', 'superficial']),
                                    TestWay('adj',
                                            '少数人知道的',
                                            'not known or meant to be known by the general populace',
                                            ["The actor must have had some esoteric motive for leaving stage. 该演员淡出舞台肯定有不为人知的原因。"],
                                            ['confidential', 'inside', 'intimate', 'nonpublic', 'privy', 'secret'],
                                            ['common accepted', 'generally known', 'open', 'public'])]),
                              Word('espouse', "",
                                   [TestWay('vt',
                                            '支持；拥护',
                                            'to take up and support as a cause',
                                            ["the revolutionary cause 支持革命事业"],
                                            ['embrace', 'take on', 'take up'],
                                            ['abjure', 'repudiate']),
                                    TestWay('vt',
                                            '结婚',
                                            'to take in marriage; marry')]),
                              Word('esteem', "",
                                   [TestWay('n./v',
                                            '尊重',
                                            'to regard with respect; prize',
                                            ["be held in high esteem 被高度敬仰"],
                                            ['appreciation', 'estimation', 'favor', 'regard', 'respect'],
                                            ['disfavor', 'odium'])]),
                              Word('estimable', "",
                                   [TestWay('adj',
                                            '值得尊敬的',
                                            'deserving of esteem; admirable',
                                            ["an estimable adversary 一位值得尊敬的对手"],
                                            ['prestigious', 'reputable', 'applaudable', 'commendable', 'creditable', 'meritorious', 'praiseworthy'],
                                            ['contemptible', 'infamous', 'censurable', 'discreditable', 'illaudable', 'reprehensible'])]),
                              Word('estrange', "",
                                   [TestWay('vt',
                                            '使疏远, 离间, 使感情失和',
                                            'to arouse especially mutual enmity or indifference in where there had formerly been love, affection, or friendliness',
                                            ["he estranged several of his coworkers 他和好多同事疏远了"],
                                            ['alienate', 'disaffect', 'disgruntle', 'sour'],
                                            ['reconcile'])]),
                              Word('etch', "",
                                   [TestWay('v',
                                            '蚀刻',
                                            "to produce (as a pattern or design) on a hard material by eating into the material's surface (as by acid or laser beam)",
                                            ["the artist etched his landscape on a copper plate 艺术家将风景画刻在铜盘上"],
                                            ['grave', 'incise', 'inscribe']),
                                    TestWay('v',
                                            '留下深刻印象, 铭记',
                                            'to produce a vivid impression of',
                                            ["in just a few pages the writer etched an unforgettable portrait of one of the more remarkable First Ladies 仅用数页, 作者刻画出了一位杰出的第一夫人令人难忘的形象"],
                                            ['impress', 'imprint', 'infix', 'ingrain'])])])

list9_unit4 = VocabularyList([Word('eternal', "",
                                   [TestWay('adj',
                                            '永恒的',
                                            'having infinite duration; everlasting; perpetual',
                                            ["eternal love 永恒的爱"],
                                            ['ageless', 'everlasting', 'immortal', 'imperishable', 'perennial', 'perpetual', 'undying'],
                                            ['ephemeral'])]),
                              Word('ethereal', "",
                                   [TestWay('adj',
                                            '轻巧精致的',
                                            'resembling air in lightness, highly refined; delicate',
                                            ["the bakery's scrumptious pastries have a wonderfully ethereal consistency 面包师可口的糕点有着一种奇妙的蓬松轻巧的质感"],
                                            ['fluffy', 'gossamer', 'light'],
                                            ['heavy', 'leaden', 'ponderous']),
                                    TestWay('adj',
                                            '天国的',
                                            'of, relating to, or suggesting heaven',
                                            ["a land of ethereal beauty and tranquility 具有缥缈的美感和宁静的一片土地"],
                                            ['elysian', 'empyreal', 'heavenly', 'supernal'],
                                            ['chthonic', 'hellish', 'infernal', 'Tartarean']),
                                    TestWay('adj',
                                            '非物质的, 精神(上)的',
                                            'not of this world; spiritual; not composed of matter',
                                            ["that ethereal attribute that every performer should have—charisma 每位演奏者都应该具有一种精神上的特质——那就是个人魅力"],
                                            ['bodiless', 'formless', 'incorporeal', 'insubstantial', 'nonmaterial', 'nonphysical', 'spiritual'],
                                            ['bodily', 'corporeal', 'material', 'physical', 'substantial'])]),
                              Word('ethics', "",
                                   [TestWay('n',
                                            '道德规范',
                                            'rules or standards governing the conduct of a person or the members of a profession',
                                            ["an old-fashioned work ethic 传统的工作行为规范"],
                                            ['ethos', 'morality', 'morals', 'norms', 'principles', 'standards'])]),
                              Word('eulogize', "",
                                   [TestWay('vt',
                                            '称赞；颂扬',
                                            'to speak or write in high praise of',
                                            ["He was eulogized at his funeral as a caring husband and a good father. 他在悼词中被称赞为一个好丈夫、一个好爸爸。"],
                                            antonyms = ['defame', 'pan', 'stricture'])]),
                              Word('euphemism', "",
                                   [TestWay('n',
                                            '婉言, 委婉的说法',
                                            'the substitution of an agreeable or inoffensive expression for one that may offend or suggest something unpleasant',
                                            ['using "eliminate" as a euphemism for "kill" “杀死”的委婉说法是“灭掉”'])]),
                              Word('euphonious', "",
                                   [TestWay('adj',
                                            '悦耳的',
                                            'pleasing or agreeable to the ear',
                                            synonyms = ['mellifluous', 'melodious', 'canorous', 'harmonizing', 'symphonious', 'tuneful'],
                                            antonyms = ['cacophonous', 'discordant', 'disharmonious', 'dissonant', 'tuneless', 'unmelodious'])]),
                              Word('euphoria', "",
                                   [TestWay('n',
                                            '感觉极其愉快',
                                            'a state of overwhelming usually pleasurable emotion',
                                            ["The initial euphoria following her victory in the election has now subsided. 选举成功带来的最初的欢愉感现在已经消失。"],
                                            ['elation', 'exhilaration', 'intoxication', 'transport', 'rapture', 'rhapsody'],
                                            ['depression'])]),
                              Word('evacuate', "",
                                   [TestWay('vt',
                                            '撤空',
                                            'to empty or remove the contents of',
                                            ["were ordered to evacuate the building 被命令搬出大楼"],
                                            ['clear', 'vacate', 'void'],
                                            ['fill up', 'occupy', 'load']),
                                    TestWay('vt',
                                            '撤退',
                                            'to remove especially from a military zone or dangerous area',
                                            ["During World War II, children were evacuated from London to the country. 二战期间, 伦敦市的儿童被撤离到郊区"],
                                            antonyms = ['conquer'])]),
                              Word('evanescent', "",
                                   [TestWay('adj',
                                            '逐渐消失的, 短暂的',
                                            'tending to vanish like vapor',
                                            ["Beauty is as evanescent as a rainbow. 容颜易老, 年华易逝。"],
                                            ['ephemeral', 'fleeting', 'impermanent', 'temporary', 'transient', 'transitory'],
                                            ['ceaseless', 'endless', 'enduring', 'eternal', 'everlasting', 'immortal', 'permanent', 'perpetual', 'timeless', 'undying', 'unending', 'abiding', 'lasting', 'perpetual'])]),
                              Word('evasive', "",
                                   [TestWay('adj',
                                            '难以发现、捕捉、分离的；含糊其词的',
                                            'hard to find, capture, or isolate; equivocal',
                                            ["an evasive statement 模棱两可的陈述"],
                                            ['fugitive', 'slippery'],
                                            ['unequivocal'])])])

list9_unit5 = VocabularyList([Word('everlasting', "",
                                   [TestWay('adj',
                                            '永恒的, 持久的',
                                            'lasting forever; eternal',
                                            ["To his everlasting credit, he never once gave in to temptation. 他人品非常好, 从来没有受到诱惑。"],
                                            ['ageless', 'enduring', 'eternal', 'immortal', 'imperishable', 'perennial', 'perpetual', 'undying'],
                                            ['impermanent', 'mortal', 'temporary', 'transient', 'ephemeral'])]),
                              Word('evict', "",
                                   [TestWay('vt',
                                            '赶出, 逐出',
                                            'to put out (a tenant, for example) by legal process; expel',
                                            ["Her landlord has threatened to evict her if she doesn't pay the rent soon. 她的房东威胁说如果再不交房租就要把她赶出去。"],
                                            antonyms = ['harbor'])]),
                              Word('evince', "",
                                   [TestWay('vt',
                                            '表明',
                                            'to make known (something abstract) through outward signs',
                                            ["evince a strong desire 明显地表现出强烈的欲望"],
                                            ['bespeak', 'betray', 'declare', 'demonstrate', 'expose', 'manifest', 'reveal', 'give away'],
                                            ['conceal', 'keep hidden'])]),
                              Word('evoke', "",
                                   [TestWay('vt',
                                            '唤起, 引发',
                                            'to call forth or up',
                                            ["evoke memories 唤起回忆"],
                                            ['elicit', 'inspire', 'raise'])]),
                              Word('exacerbate', "",
                                   [TestWay('vt',
                                            '使加剧, 使恶化',
                                            'to make more violent, bitter, or severe',
                                            ["a heavy rainfall that exacerbated the flood problems 大雨恶化了洪水问题"],
                                            ['aggravate', 'complicate', 'worsen'],
                                            ['allay', 'alleviate', 'assuage', 'mitigate', 'relieve', 'palliate'])]),
                              Word('exacting', "",
                                   [TestWay('adj',
                                            '严格的, 苛求的',
                                            'making severe demands; rigorous',
                                            ["an exacting instructor 一位严苛的导师"],
                                            ['choosy', 'demanding', 'fastidious', 'finical', 'fussy', 'pernickety', 'persnickety', 'picky'],
                                            other_form = 'exact v. 强求, 索取:  to force the payment or yielding of 【例】exact tribute from a conquered people 从征服的人民手中强取贡品 【反】condone, forgive 赦免免除债务'),
                                    TestWay('adj',
                                            '费时间花心思的',
                                            'requiring much time, effort, or careful attention',
                                            ["editing and proofreading will always be an exacting task 编辑和校对是花时间花心思的工作"],
                                            ['arduous', 'burdensome', 'challenging', 'grueling', 'killing', 'laborious', 'onerous', 'taxing', 'toilsome'],
                                            ['light', 'unchallenging', 'undemanding'])]),
                              Word('exalt', "",
                                   [TestWay('vt',
                                            '提升, 提拔',
                                            'to raise in rank, character, or status; elevate',
                                            ["popular support and media hype have exalted Super Bowl Sunday to the level of a national holiday 大众广泛的支持和媒体的大肆宣传已然将超级碗杯星期天变成了一个全民狂欢的大节日"],
                                            ['aggrandize', 'canonize', 'deify', 'dignify', 'elevate', 'ennoble', 'magnify'],
                                            ['abase', 'degrade', 'demean' ,'humble', 'lower in status']),
                                    TestWay('vt',
                                            '赞扬',
                                            'to glorify, praise, or honor.',
                                            synonyms = ['emblazon', 'extol', 'glorify', 'laud', 'magnify'],
                                            antonyms = ['condemn'])]),
                              Word('exasperate', "",
                                   [TestWay('vt',
                                            '激怒',
                                            'to excite the anger of',
                                            ["I was exasperated by the flight delays. 我被飞机延误激怒了。"],
                                            ['aggravate', 'gall', 'nettle', 'peeve', 'rile', 'ruffle', 'vex', 'burn up'],
                                            ['mitigate', 'mollify'])]),
                              Word('excavate', "",
                                   [TestWay('v',
                                            '挖掘, 挖空',
                                            'to dig out and remove',
                                            ["excavate soil from one area 从某处挖土出来"],
                                            ['fill in'])]),
                              Word('exceptional', "",
                                   [TestWay('adj',
                                            '例外的, 特别的, 非凡的',
                                            'being an exception; uncommon; extraordinary',
                                            ["exceptional bravery 非凡的勇敢"],
                                            ['aberrant', 'abnormal', 'anomalous', 'exceeding', 'extraordinary', 'peculiar', 'unwonted'],
                                            ['commonplace', 'prosaic', 'customary', 'normal', 'ordinary', 'typical', 'unextraordinary', 'usual'])])])

list9_unit6 = VocabularyList([Word('excoriate', "",
                                   [TestWay('v',
                                            '严厉批评',
                                            'to criticize harshly and usually publicly',
                                            ["She was excoriated as a racist. 她被指责是一个种族歧视者。"],
                                            ['abuse', 'assail', 'belabor', 'castigate', 'excoriate', 'lambaste', 'vituperate'],
                                            ['accolade', 'extol', 'flatter', 'praise lavishly'])]),
                              Word('excrete', "",
                                   [TestWay('vt',
                                            '排泄',
                                            'to separate and discharge (waste matter) from the blood, tissues, or organs',
                                            ["excrete sweat 排汗"],
                                            antonyms = ['absorb', 'ingest'])]),
                              Word('excruciate', "",
                                   [TestWay('vt',
                                            '折磨, 使痛苦',
                                            'to inflict severe pain on; torture',
                                            ["She has long been excruciated by a persistent pain in her back. 她长久以来被背痛折磨"],
                                            ['agonize', 'anguish', 'plague', 'rack', 'torment', 'torture', 'harrow'],
                                            ['exult'])]),
                              Word('exculpate', "",
                                   [TestWay('vt',
                                            '声明无罪；开脱, 使无罪',
                                            'to clear from alleged fault or guilt',
                                            ["I have gathered evidence that will exculpate my client. 我已经搜集到能够证明委托人无罪的证据了。"],
                                            ['absolve', 'acquit', 'clear', 'exonerate', 'vindicate'],
                                            ['attribute guilt', 'inculpate', 'indict', 'criminate', 'incriminate'])]),
                              Word('excursive', "",
                                   [TestWay('adj',
                                            '离题的；散漫的',
                                            'passing from one topic to another',
                                            ["an excursive story line that some readers of Melville's novel find very rewarding 一些梅尔维尔小说的读者非常喜欢松散的故事主线"],
                                            ['desultory', 'digressive', 'meandering', 'rambling', 'wandering'])]),
                              Word('execrate', "",
                                   [TestWay('v',
                                            '谴责',
                                            'to declare to be morally wrong or evil',
                                            ["leaders from all over the world execrated the terrorists responsible for the bomb blast 世界各国首脑强烈谴责对爆炸袭击负责的恐怖分子"],
                                            ['anathematize', 'censure', 'decry', 'denounce', 'reprehend', 'reprobate'],
                                            ['bless']),
                                    TestWay('v',
                                            '痛恨',
                                            'to dislike strongly',
                                            ["execrates anyone who would physically abuse children or animals 痛恨那些虐待儿童和动物的人"],
                                            ['abhor', 'abominate', 'despise', 'detest', 'loathe'],
                                            ['love'])]),
                              Word('exemplary', "",
                                   [TestWay('adj',
                                            '榜样的, 值得效仿的',
                                            'constituting, serving as, or worthy of being a pattern to be imitated',
                                            ["as a hospital volunteer he has given exemplary service to his community 他作为医疗志愿者为社区起到了模范的作用"],
                                            ['monitory', 'archetypal', 'imitable', 'paradigmatic', 'quintessential'],
                                            other_form = 'exemplify v. (通过榜样)示范, 显示: to show or illustrate by example'),
                                    TestWay('adj',
                                            '作为警告的',
                                            'serving as or offering a warning',
                                            ["armies have traditionally used public execution as an exemplary punishment for the crime of desertion 军队通常将公开处决作为玩忽职守罪的惩罚, 以儆效尤"],
                                            ['admonishing', 'admonitory', 'monitory', 'premonitory', 'warning'])]),
                              Word('exempt', "",
                                   [TestWay('vt',
                                            '使免除',
                                            'to release or deliver from some liability or requirement to which others are subject',
                                            ["a man exempted from military service 免服军役的人"])]),
                              Word('exhaust', "",
                                   [TestWay('v',
                                            '耗尽',
                                            'to consume entirely; to make complete use of',
                                            ["exhausted our funds in a week 在一周内就耗尽了我们的经费"],
                                            ['consume', 'devour', 'drain', 'expend', 'spend', 'use up'],
                                            other_form = 'exhaustive adj. 彻底的, 完整的, 详尽的: testing all possibilities; thorough；complete 【例】conduct an exhaustive investigation 做详尽的调查 【反】incomplete, partial 不完全的'),
                                    TestWay('vt',
                                            '使筋疲力尽',
                                            'to wear out completely',
                                            ["exhausted by overwork 加班使得筋疲力尽"],
                                            ['fatigue', 'frazzle', 'harass', 'wear out', 'weary', 'knock out'])]),
                              Word('exhilarate', "",
                                   [TestWay('vt',
                                            '使高兴；使兴奋',
                                            'to make cheerful and excited',
                                            ["be exhilarated by her success 为她的成功感到兴奋"],
                                            ['electrify', 'galvanize', 'intoxicate', 'pump up', 'turn on'],
                                            ['sadden', 'depress'],
                                            'exhilarating adj. 令人兴奋的 【反】soporific 昏昏欲睡的')])])

list9_unit7 = VocabularyList([Word('exhort', "",
                                   [TestWay('vt',
                                            '敦促；力劝',
                                            'to urge by strong, often stirring argument, admonition, advice, or appeal',
                                            ["The speaker exhorted the graduating students to go forth and try to make a difference in the world. 演讲者鼓励毕业生们去广阔天地有所作为。"],
                                            ['encourage', 'goad', 'nudge', 'prod', 'prompt', 'egg on'])]),
                              Word('exigent', "",
                                   [TestWay('adj',
                                            '紧急的',
                                            'requiring immediate aid or action',
                                            ["exigent circumstances 紧急情况"],
                                            ['compelling', 'dire', 'emergent', 'exigent', 'imperative', 'importunate', 'necessitous', 'pressing', 'urgent'],
                                            ['deferrable', 'noncritical', 'nonurgent'])]),
                              Word('exodus', "",
                                   [TestWay('vt',
                                            '大批离去',
                                            'a mass departure',
                                            ["the mass exodus from the cities for the beaches on most summer weekends 在多数夏季的周末, 大批都市人奔向海滩"],
                                            ['gush', 'outpour', 'outpouring'],
                                            ['influx', 'flux', 'inflow', 'inrush'])]),
                              Word('exonerate', "",
                                   [TestWay('vt',
                                            '免除责备',
                                            'to free from blame',
                                            ["An investigation exonerated the school from any blame. 一项调查使学校免受责备。"],
                                            ['absolve', 'acquit', 'clear', 'vindicate'],
                                            ['censure', 'incriminate', 'inculpate', 'prove guilty'])]),
                              Word('exorbitant', "",
                                   [TestWay('adj',
                                            '过度的',
                                            'exceeding the customary or appropriate limits in intensity, quality, amount, or size',
                                            ["exorbitant prices 过高的价格"],
                                            ['extravagant', 'intolerable', 'lavish', 'overdue', 'overweening', 'unconscionable'],
                                            ['middling', 'moderate', 'modest', 'reasonable', 'temperate'])]),
                              Word('exotic', "",
                                   [TestWay('adj',
                                            '外来的, 不同寻常的',
                                            'excitingly or mysteriously unusual',
                                            ["famous for her exotic tastes 她以有异域风情著称"],
                                            ['outlandish', 'strange'],
                                            ['indigenous', 'familiar', 'nonglamorous', 'plain-Jane', 'unexotic'])]),
                              Word('expansive', "",
                                   [TestWay('adj',
                                            '广阔的',
                                            'having a great expanse or extent',
                                            ["expansive beach 广阔的沙滩"],
                                            ['broad', 'extended', 'far-reaching', 'rangy'],
                                            ['limited', 'narrow']),
                                    TestWay('adj',
                                            '健谈的, 外向的',
                                            'open and communicative; talkative or effusive',
                                            ["Wine made the guest expansive. 宾客们酒后变得话多。"],
                                            antonyms = ['reserved', 'taciturn', 'withdrawn', 'diffident'])]),
                              Word('expedite', "",
                                   [TestWay('vt',
                                            '加快进程',
                                            'to speed up the progress of; accelerate',
                                            ["expedite your plans 加快你的计划"],
                                            antonyms = ['retard'])]),
                              Word('expedition', "",
                                   [TestWay('n',
                                            '动作迅速',
                                            'speed in performance; promptness',
                                            ["deal with the order with the greatest possible expedition 以可能的最快的速度处理订单"],
                                            ['passage', 'peregrination', 'travel', 'trek'],
                                            ['foot-dragging'])]),
                              Word('expiate', "",
                                   [TestWay('vt',
                                            '赎罪, 纠正',
                                            'to extinguish the guilt incurred by',
                                            ["expiate one’s sin 赎罪"],
                                            ['mend', 'redeem', 'atone for'])])])

list9_unit8 = VocabularyList([Word('expire', "",
                                   [TestWay('v',
                                            '断气, 死亡',
                                            "to breathe one's last breath; die",
                                            ["The patient expired early this morning. 病人今早咽气了。"],
                                            ['conclude', 'elapse', 'terminate', 'decease', 'leave off', 'let up'],
                                            ['come to life']),
                                    TestWay('v',
                                            '到期',
                                            'to come to an end',
                                            ["My membership in the club has expired. 我的会员资格到期了。"],
                                            ['discontinue', 'elapse', 'end', 'finish', 'terminate', 'wind up', 'wink out'],
                                            ['continue', 'persist', 'hang on'])]),
                              Word('explicit', "",
                                   [TestWay('adj',
                                            '表达清晰的',
                                            'fully revealed or expressed without vagueness, implication, or ambiguity',
                                            ["explicit instructions 表达清晰的指示说明"],
                                            ['clear-cut', 'definite', 'specific', 'unambiguous', 'unequivocal', 'univocal'],
                                            ['obscure', 'implicit', 'implied', 'inferred', 'ambiguous', 'circuitous', 'equivocal', 'indefinite', 'unspecific', 'vague']),
                                    TestWay('adj',
                                            '成熟的, 完全形成的',
                                            'fully developed or formulated',
                                            ["explicit plan 成熟的计划"],
                                            antonyms = ['inchoate'])]),
                              Word('exploit', "",
                                   [TestWay('n',
                                            '英雄行为',
                                            'a notable or heroic act',
                                            ["his wartime exploits 他在战争期间的英勇行为"]),
                                    TestWay('v',
                                            '最大程度地利用',
                                            'to employ to the greatest possible advantage',
                                            ["exploit your opponent's weakness 利用你对手的弱点"],
                                            ['abuse', 'leverage', 'milk', 'play on', 'capitalize on impose on'])]),
                              Word('exponent', "",
                                   [TestWay('n',
                                            '倡导者, 支持者',
                                            'one that speaks for, represents, or advocates',
                                            ["Exponents of space exploration earnestly called for more missions to the outer reaches of the solar system. 太空探险的支持者强烈要求对太阳系的外边缘进行探索。"],
                                            ['advocator', 'backer', 'booster', 'champion', 'espouser', 'friend', 'promoter', 'proponent'],
                                            ['adversary', 'antagonist', 'opponent']),
                                    TestWay('n',
                                            '实践者',
                                            'one who brings an art or science to full realization',
                                            ["has long reigned as the nation's leading exponent of modern dance 被认为是该国现代舞的集大成者"],
                                            ['expounder', 'guru', 'interpreter', 'practitioner', 'high priest'])]),
                              Word('expurgate', "",
                                   [TestWay('v',
                                            '净化, 删去不当处',
                                            'to remove erroneous, vulgar, obscene, or otherwise objectionable material from (a book, for example) before publication',
                                            ["an expurgated edition of the letters 信件的删减版"],
                                            ['bowdlerize', 'obliterate', 'launder', 'red-pencil', 'clean up'])]),
                              Word('exquisite', "",
                                   [TestWay('adj',
                                            '程度强烈的',
                                            'extreme in degree, power, or effect',
                                            ["suffered exquisite pain 遭受强烈的痛感"],
                                            ['acute', 'dreadful', 'excruciating', 'explosive', 'ferocious', 'fierce', 'furious', 'intensive', 'keen', 'profound', 'terrible', 'vehement', 'vicious'],
                                            ['light', 'moderate', 'soft']),
                                    TestWay('adj',
                                            '精致精巧的',
                                            'having qualities that appeal to a refined taste',
                                            ["exquisite pen-and-ink drawings of city scenes 精巧的城市钢笔画"],
                                            ['dainty', 'delicate', 'elegant', 'recherché', 'select'])]),
                              Word('extant', "",
                                   [TestWay('adj',
                                            '现存的',
                                            'still in existence; not destroyed, lost, or extinct',
                                            ["the most charming writer extant 目前活着的作家中最有魅力的一位", "extant manuscripts 未毁坏的手稿"],
                                            ['current', 'immediate', 'ongoing', 'present-day', 'existent'],
                                            ['destroyed', 'extinct' ,'lost', 'missing', 'dead', 'extinct', 'nonextant'])]),
                              Word('extemporize', "",
                                   [TestWay('v',
                                            '即席表现',
                                            'to do or perform (something) without prior preparation or practice',
                                            ["a good talk show host has to be able to extemporize the interviews when things don't go as planned 一个好的脱口秀主持人要能够在计划之外即兴表现"],
                                            antonyms = ['follow a script', '参考草稿'],
                                            other_form = 'extemporaneous 【反】planned 有计划的')]),
                              Word('extenuate', "",
                                   [TestWay('vt',
                                            '减轻罪过',
                                            'to lessen or to try to lessen the seriousness or extent of by making partial excuses',
                                            ["try to extenuate their vandalism with the old refrain of “Boys will be boys” 企图用“江山易改本性难移”的俗语为他们的暴行开脱"],
                                            ['deodorize', 'excuse', 'explain away', 'gloss over', 'gloze over'])]),
                              Word('extinct', "",
                                   [TestWay('adj',
                                            '灭绝的',
                                            'no longer existing or living',
                                            ["extinct species 灭绝的物种"],
                                            ['bygone', 'bypast', 'defunct', 'expired', 'nonextant', 'vanished'],
                                            ['alive', 'extant', 'existing', 'living', 'resuscitated'],
                                            'extinction n. 灭绝 【反】perpetuation 永存')])])

list9_unit9 = VocabularyList([Word('extinguish', "",
                                   [TestWay('vt',
                                            '熄灭',
                                            'to put out (a fire, for example); quench',
                                            ["the fire in the skillet was quickly extinguished by slamming the lid on 平底锅的火苗很快被水浇灭了"],
                                            ['blanket', 'douse', 'quench', 'put out', 'snuff out'],
                                            ['ignite', 'rekindle']),
                                    TestWay('v',
                                            '终止',
                                            'to bring to a complete end the physical soundness, existence, or usefulness of',
                                            ["a fatal blunder that extinguished all hope that the team would actually win the play-offs 一个致命的失误使得队伍赢得季后赛的希望完全破灭"],
                                            ['annihilate', 'decimate', 'demolish', 'desolate', 'devastate', 'pulverize', 'ruin', 'shatter', 'smash', 'tear down', 'pull down', 'rub out'],
                                            ['build', 'construct', 'erect', 'raise', 'rear', 'set up', 'put up'])]),
                              Word('extol', "",
                                   [TestWay('v',
                                            '赞美; 吹捧',
                                            'to praise highly; glorify',
                                            ["extol the virtues of… 赞美……的优点"],
                                            ['carol', 'exalt', 'glorify', 'laud', 'magnify', 'resound'],
                                            ['censure', 'impugn', 'malign', 'deprecate', 'detract rail', 'villify', 'excoriate'])]),
                              Word('extort', "",
                                   [TestWay('v',
                                            '勒索',
                                            'to obtain from a person by force, intimidation, or undue or illegal power',
                                            ["The criminals extorted large sums of money from their victims. 绑匪向受害者勒索大笔钱财。"],
                                            ['wrest', 'wring'])]),
                              Word('extract', "",
                                   [TestWay('v',
                                            '用力拔出',
                                            'to pull or take out forcibly',
                                            ["extracted a wisdom tooth 拔出一颗智齿"],
                                            ['pull', 'uproot', 'wrest', 'wring', 'yank', 'root out', 'tear out'],
                                            ['embed'])]),
                              Word('extraction', "",
                                   [TestWay('n',
                                            '血统',
                                            'origin; lineage; ancestry',
                                            ["a family of French extraction 有法国血统的家族"],
                                            ['bloodline', 'breeding', 'descent', 'genealogy', 'lineage', 'origin', 'family tree'])]),
                              Word('extraneous', "",
                                   [TestWay('adj',
                                            '无关的',
                                            'having no relevance',
                                            ["an extraneous digression 无关的跑题"],
                                            ['impertinent', 'inapplicable', 'irrelative', 'accidental', 'adventitious', 'external'],
                                            ['applicable', 'apposite', 'apropos', 'germane', 'pertinent', 'relative', 'relevant']),
                                    TestWay('adj',
                                            '非主要因素的',
                                            'not forming an essential or vital part',
                                            ["the architect's streamlined modern style shuns any sort of extraneous ornamentation 建筑师流线型的现代设计避免了一切多余的装饰"],
                                            ['accidental', 'adventitious', 'alien', 'external', 'foreign'],
                                            ['essential', 'inherent', 'innate', 'intrinsic'])]),
                              Word('extravagant', "",
                                   [TestWay('adj',
                                            '挥霍的',
                                            'given to spending money freely or foolishly',
                                            ["has always been extravagant with her money 挥金如土"],
                                            ['profligate', 'spendthrift', 'squandering', 'thriftless', 'unthrifty', 'wasteful'],
                                            ['frugal', 'conserving', 'economical', 'penny-pinching', 'scrimping', 'skimping', 'thrifty']),
                                    TestWay('adj',
                                            '过度的, 不必要的',
                                            'going beyond a normal or acceptable limit in degree or amount',
                                            ["the book doesn't quite merit the extravagant praise that it has received 这本书被盛赞过度"],
                                            ['baroque', 'exorbitant', 'immoderate', 'inordinate', 'lavish', 'overdue', 'overmuch', 'overweening', 'plethoric', 'unconscionable', 'unmerciful'],
                                            ['middling', 'moderate', 'modest', 'reasonable', 'temperate'])]),
                              Word('extricate', "",
                                   [TestWay('vt',
                                            '使解脱, 救出',
                                            'to free or remove from an entanglement or difficulty',
                                            ["extricate himself from financial difficulties 使他摆脱财政困境disengage, disentangle, free, liberate, release, untangle"],
                                            ['disengage', 'disentangle', 'free', 'liberate', 'release', 'untangle'],
                                            ['enmesh', 'entangle', 'embroil'])]),
                              Word('exuberant', "",
                                   [TestWay('adj',
                                            '非常高兴的, 热情洋溢的',
                                            'joyously unrestrained and enthusiastic',
                                            ["Exuberant crowds rushed to greet the returning national champions. 激动的人群争先恐后地向凯旋归来的全国冠军表示问候"],
                                            ['ebullient', 'effervescent', 'frolic', 'buoyant', 'bouncy', 'vivacious'],
                                            ['austere', 'sullen']),
                                    TestWay('adj',
                                            '大量的, 充分的',
                                            'produced in extreme abundance',
                                            ["an exuberant imagination 丰富的想象力"],
                                            ['ample', 'lavish', 'lush', 'luxuriant', 'opulent', 'plentiful', 'prodigal', 'profuse', 'riotous'],
                                            ['meager', 'scant', 'sparse'])]),
                              Word('exude', "",
                                   [TestWay('vi',
                                            '分泌, 流',
                                            'to flow forth slowly through small openings',
                                            ["a sticky resin exuded from the bark 从树皮中分泌出来的带有恶臭的树脂"],
                                            ['bleed', 'ooze', 'seep'],
                                            ['absorb'])])])

list9_unit10 = VocabularyList([Word('exult', "",
                                   [TestWay('vi',
                                            '感到欢喜',
                                            'to rejoice especially with feelings or display of triumph or self-satisfaction',
                                            ["exult in a triumph 沉浸在胜利的喜欢当中"],
                                            ['delight', 'glory', 'jubilate', 'joy', 'rejoice', 'triumph'],
                                            ['lament', 'mourn', 'bemoan'],
                                            'exultant adj. 狂喜的')]),
                              Word('fable', "",
                                   [TestWay('n',
                                            '寓言故事',
                                            'a story intended to teach a basic truth or moral about life',
                                            ["This classic Christmas film is essentially a fableshowing how every person's life has meaning. 这部经典的基督教电影本质上来说是一个寓言, 它告诉我们每个人的生命都是有意义的"],
                                            ['apologue', 'parable']),
                                    TestWay('n',
                                            '神话, 传说',
                                            'a legendary story of supernatural happenings',
                                            ["According to an ancient fable, the waters of the mountain spring are the tears of a woman weeping for her lost children. 根据一个古老的传说, 这条山中的泉水是一名失去孩子的母亲所流下的眼泪"],
                                            ['legend', 'mythos', 'tale']),
                                    TestWay('n',
                                            '谎言',
                                            'a statement known by its maker to be untrue and made in order to deceive',
                                            ["The stories of lost cities of gold may have been fables deliberately concocted by Native Americans to dupe the Spanish. 所谓的“失落的黄金之都”的故事也许只是美洲土著们杜撰出来忽悠西班牙人的"],
                                            ['fabrication', 'falsehood', 'lie', 'mendacity', 'prevarication', 'story'],
                                            ['fact', 'truth'],
                                            'fabulous adj. 寓言般的, 难以置信的')]),
                              Word('fabricate', "",
                                   [TestWay('vt',
                                            '捏造',
                                            'to make up for the purpose of deception',
                                            ["be accused of fabricating evidence 被指控有捏造证据的行为"],
                                            ['concoct', 'coin', 'devise', 'forge', 'fake', 'feign', 'invent']),
                                    TestWay('vt',
                                            '搭建, 组建; 打造',
                                            'to bring into being by combining, shaping, or transforming materials',
                                            ["The house was essentially fabricated at the factory and then shipped to the site for assembly. 这间房屋的核心主体在工厂内建好之后, 它被运往目的地直接进行组装", "All the key parts are fabricated from high quality titanium alloy. 所有的关键零件都是由上好的钛合金打造的"],
                                            ['assemble', 'construct', 'erect', 'frame', 'fashion', 'manufacture', 'produce', 'rear', 'set up'],
                                            ['demount', 'disassemble', 'dismantle', 'dismember'],
                                            'fabrication n. 组建; 虚构的事物')]),
                              Word('facetious', "",
                                   [TestWay('adj',
                                            '喜欢开玩笑的, 轻浮的',
                                            'joking or jesting often inappropriately',
                                            ["Stop being facetious! This is the life-and-death moment. 别开玩笑了！这可是生死攸关的时刻"],
                                            ['humorous', 'jocose', 'jocular', 'waggish', 'witty'],
                                            ['earnest', 'sincere', 'lugubrious'])]),
                              Word('facile', "",
                                   [TestWay('adj',
                                            '表面的, 浅尝辄止的',
                                            'having or showing a lack of depth of understanding or character',
                                            ["propose a facile solution to a complex problem 给一个复杂的问题􁨀议一个肤浅的解决方案"],
                                            ['cursory', 'shallow', 'simplistic', 'superficial'],
                                            ['deep', 'profound', 'comprehensive', 'exhaustive']),
                                    TestWay('adj',
                                            '容易的, 唾手可得的',
                                            'easily accomplished or attained',
                                            ["a facile victory 一场轻松易得的胜利"],
                                            ['cheap', 'easy', 'effortless', 'painless', 'royal'],
                                            ['arduous', 'demanding', 'difficult', 'formidable', 'hard', 'laborious', 'toilsome', 'tough'])]),
                              Word('facilitate', "",
                                   [TestWay('vt',
                                            '使变容易, 促进',
                                            'to make easy or easier',
                                            ["The new airport will facilitate the development of tourism. 新建机场促进了旅游业的发展。"],
                                            ['ease', 'expedite', 'forward', 'further', 'help'],
                                            ['check', 'hamper', 'handicap', 'hinder', 'impede', 'obstruct', 'thwart', 'retard', 'complicate'],
                                            'facility n. 设施; 容易, 方便')]),
                              Word('faction', "",
                                   [TestWay('n',
                                            '派系',
                                            'a party or group (as within a government) that is often contentious or self-seeking',
                                            ["affiliated with one faction 附属于某个党派; North-Ocean Faction 北洋派"],
                                            ['bloc', 'body', 'clique', 'coalition', 'sect', 'wing'],
                                            other_form = 'factional adj.派系的, 派别的')]),
                              Word('fallacious', "",
                                   [TestWay('adj',
                                            '谬误的, 不合逻辑的',
                                            'containing or based on a fallacy',
                                            ["the once-common fallacious claim that girls just weren't any good at math 曾经广为流传的一个谬论: 女孩子无论如何就是学不好数学"],
                                            ['illogical', 'invalid', 'irrational', 'mad', 'reasonless', 'sophistic', 'unreasonable'],
                                            ['sound', 'valid']),
                                    TestWay('adj',
                                            '欺骗性的',
                                            'tending to deceive or mislead',
                                            ["fallacious testimony 不真实的证词"],
                                            ['beguiling', 'deceiving', 'deceptive', 'deluding', 'delusive', 'delusory', 'false', 'fraudulent', 'misleading'],
                                            ['authentic', 'veritable'],
                                            'fallacy n.逻辑谬误')]),
                              Word('fallow', "",
                                   [TestWay('adj',
                                            '休耕的',
                                            'left untilled or unsown after plowing',
                                            ["The field was lying fallow. 那田地正在休耕中"],
                                            ['untilled', 'uncultivated']),
                                    TestWay('adj',
                                            '闲置的',
                                            'not being in a state of use, activity, or employment',
                                            ['The coal mine has been lying fallow since the drop in prices made it unprofitable. 自从煤价下跌造成亏损, 这个煤矿就一直处于停工状态'],
                                            ['dead', 'dormant', 'inert', 'inoperative', 'latent', 'unused', 'vacant'],
                                            ['functioning', 'occupied', 'operative', 'running', 'working', 'active'])]),
                              Word('fail-safe', "",
                                   [TestWay('n',
                                            '保险措施',
                                            'a measure taken to preclude loss or injury',
                                            ["There are so many fail-safes built into the system that a highly unlikely series of mistakes would have to be made before failure could occur. 系统中嵌入了大量的保险措施, 因此在系统崩溃之前, 必须要发生一系列几乎不可能出现的错误"],
                                            ['caution', 'palladium', 'preventive', 'safeguard']),
                                    TestWay('adj',
                                            '万无一失的',
                                            'having no chance of failure',
                                            ["a fail-safe device 自动防故障装置", "Men have traditionally regarded flowers as the fail-safe gift for Valentine's Day. 男士们长期以来认为鲜花是情人节永远不会错的礼物"],
                                            ['certain', 'foolproof', 'sure', 'unfailing'],
                                            ['fallible'])])])

LIST9 = VocabularyList(list9_unit1.words+list9_unit2.words+list9_unit3.words+list9_unit4.words+list9_unit5.words+list9_unit6.words+list9_unit7.words+list9_unit8.words+list9_unit9.words+list9_unit10.words)
