#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list1_unit1 = VocabularyList([Word('abandon', "ə'beɪt",
                                   [TestWay('n',
                                            '放弃',
                                            'carefree, freedom from constraint',
                                            ['added spices to the stew with complete abandon 肆无忌惮地向炖菜里面加调料'],
                                            ['unconstraint', 'uninhibitedness', 'unrestraint']),
                                    TestWay('v',
                                            '放纵',
                                            'to give (oneself) over unrestrainedly',
                                            ['abadon oneself to emotion 感情用事', 'abandon herself to a life of complete idleness 放纵自己过着闲散的生活'],
                                            ['indulge', 'surrender', 'give up']),
                                    TestWay('v',
                                            '放弃',
                                            'to withdraw from often in the face of danger or encroachment',
                                            ['abandon the ship/homes 弃船, 离家'],
                                            antonyms = ['salvage']),
                                    TestWay('v',
                                            '停止做某事',
                                            'to put an end to (something planned or previously agreed to)',
                                            ['the bad weather forced NASA to abandon the launch 坏天气迫使NASA停止了发射'],
                                            ['abort', 'drop', 'repeal', 'rescind', 'revoke', 'call off'],
                                            ['keep', 'continue', 'maintain', 'carry on']),]),
                              Word('abase', "ə'beɪs",
                                   [TestWay('v',
                                            '降低(地位、职位、威望或尊严)',
                                            'to lower in rank, office, prestige, or esteem',
                                            ['was unwilling to abase himself by pleading guilty to a crime that he did not commit 不愿意屈就自己去承认一个莫须有的罪名'],
                                            ['debauch', 'degrade', 'profane', 'vitiate', 'discredit', 'foul', 'smirch', 'take down'],
                                            ['elevate', 'ennoble', 'uplift', 'aggrandize', 'canonize', 'deify', 'exalt'])]),
                              Word('abash', "ə'bæʃ",
                                   [TestWay('vt',
                                            '使尴尬, 使羞愧',
                                            'to destroy the self-possession or self-confidence of ,disconcert, embarrass',
                                            ['Nothing could abash him. 没有什么可以使他感到难堪。'],
                                            ['discomfit', 'disconcert', 'discountenance', 'faze', 'fluster', 'nonplus', 'mortify'],
                                            ['embolden'])]),
                              Word('abate', "",
                                   [TestWay('v',
                                            '减轻(程度或者强度)',
                                            'to reduce in degree or intensity',
                                            ['abate his rage/pain 平息他的愤怒/减轻痛苦'],
                                            ['moderate', 'recede', 'subside', 'remit', 'wane', 'die (away or down or out)','let up', 'phase down', 'ratchet (down)', 'taper off'],
                                            ['intensify']),
                                    TestWay('v',
                                            '减少(数量或者降低价值)',
                                            'to reduce in amount or value',
                                            ['abate a tax 降低税收'],
                                            ['de-escalate', 'deplete', 'downscale', 'dwindle',],
                                            ['augment', 'promote']),
                                    TestWay('v',
                                            '停止, 撤销',
                                            'to put an end to',
                                            ['abate a nuisance 停止伤害'],
                                            ['abrogate', 'annul', 'invalidate', 'nullify', 'rescind', 'vacate'])]),
                              Word('abbreviate', "ə'bri:vɪeɪt",
                                   [TestWay('v',
                                            '缩写, 缩短',
                                            'to make briefer',
                                            ['abbreviate the word "building" as "bldg." 将“building”缩写作“bldg”'],
                                            ['abridge', 'curtail', 'cut back', 'syncopate', 'truncate'],
                                            ['extend', 'protract', 'elongate', 'lengthen', 'prolong'])]),
                              Word('abdicate', "'æbdkeɪt",
                                   [TestWay('v',
                                            '正式放弃(权力、责任)',
                                            'to renounce a throne, to relinquish (power or responsibility) formally',
                                            ['abdicate the throne/crown 退位'],
                                            ['cede', 'relinquish', 'renounce', 'resign', 'step down (from)'],
                                            ['constitute', 'assume', 'usurp'])]),
                              Word('aberrant', "æ'berənt",
                                   [TestWay('adj',
                                            '异常的, 非常规的',
                                            'deviating from the usual or natural type',
                                            ['This behavior might be aberrant enough to draw attention. 这样的行为已经异常得足以引起人们的注意。'],
                                            ['abnormal', 'anomalous', 'peculiar', 'singular', 'unwonted', 'uncustomary'],
                                            ['normal', 'natural', 'regular', 'standard', 'typical'])]),
                              Word('abet', "ə'bet",
                                   [TestWay('v',
                                            '帮助, 怂恿',
                                            'to assist or support in the achievement of a purpose',
                                            ['aid and abet <法律>协助教唆'],
                                            ['ferment', 'foment', 'provoke', 'instigate', 'stir (up)', 'whip (up)']),
                                    TestWay('v',
                                            '鼓励',
                                            'to actively encourage (as an activity or plan)',
                                            synonyms = ['aid', 'assist', 'back', 'support', 'prop (up)'],
                                            antonyms = ['stymie', 'frustrate', 'obstruct', 'thwart', 'impede', 'forestall', 'hinder'])],),
                              Word('abeyance', "ə'beɪəns",
                                   [TestWay('n',
                                            '中止, 搁置',
                                            'temporary inactivity',
                                            ['hold the plan in abeyance 使计划暂停'],
                                            ['doldrums', 'quiescence', 'moratorium', 'latency', 'dormancy', 'suspension', 'cold storage', 'deep freeze'],
                                            ['continuance', 'fulfillment'])]),
                              Word('abhor', "əb'hɔ:",
                                   [TestWay('vt',
                                            '深恶痛绝, 极度厌恶',
                                            'to regard with extreme repugnance',
                                            ['He abhors the way people leave their trash at the picnic sites in the park. 他很厌恶人们把垃圾留在公园的野餐点。'],
                                            ['abominate', 'despise', 'detest', 'execrate', 'loathe'],
                                            ['greatly admire'])]),])
list1_unit2 = VocabularyList([Word('abiding', "",
                                   [TestWay('vt',
                                            '永久的',
                                            'lasting for a long time; enduring',
                                            ['an abiding love of Espanol 对西班牙语持久的热爱'],
                                            ['ageless', 'enduring', 'eternal', 'everlasting', 'perennial', 'perpetual', 'timeless'],
                                            ['evanescent' , 'ephemeral'])]),
                              Word('abject', "",
                                   [TestWay('adj',
                                            '无精打采的',
                                            'cast down in spirit, spiritless',
                                            ['a man made abject by suffering 被生活折磨得无精打采的人'],
                                            ['spiritless'],
                                            ['spirited', 'excited', 'exultant']),
                                    TestWay('adj',
                                            '(地位、身份)悲惨、凄凉的',
                                            'sunk to or existing in a low state or condition',
                                            ['abject poverty 让人绝望的贫穷']),
                                    TestWay('adj',
                                            '卑微的, 讨好的',
                                            'expressing or offered in a humble and often ingratiating spirit',
                                            ['abject flattery 卑躬屈膝般的恭维', 'an abject apology 讨好般的、真心的道歉'],
                                            ['base', 'humble', 'menial', 'servile', 'slavish'])]),
                              Word('abjure', "æb'dʒʊə",
                                   [TestWay('v',
                                            '发誓放弃',
                                            'a firm and final rejecting or abandoning often made under oath',
                                            ['abjure one’s belief 发誓放弃信仰'],
                                            ['recant', 'renege', 'renounce', 'abnegate', 'forswear (also foreswear)', 'repudiate'],
                                            ['affirm', 'espouse', 'embrace']),
                                    TestWay('v',
                                            '抵制, 避免',
                                            'to resist the temptation of',
                                            ['abjure extravagance 抵制铺张浪费'],
                                            ['keep (from)', 'refrain (from)', 'withhold (from)'],
                                            ['bow to', 'give in to', 'submit to', 'succumb to', 'surrender to', 'yield to'])]),
                              Word('abnegate', "",
                                   [TestWay('v',
                                            '否认',
                                            'deny, renounce',
                                            ['abnegated the idea of freedom 放弃自由的观念'],
                                            ['recant', 'renege', 'repudiate', 'unsay', 'forswear (also foreswear)', 'take back'],
                                            ['reaffirm']),
                                    TestWay('v',
                                            '投降, 放弃, 交出(权力等)',
                                            'surrender, relinquish',
                                            ['abnegated her powers 交出她拥有的权力'],
                                            ['cede', 'resign', 'step aside (from)', 'step down (from)'],
                                            ['adhere to'])]),
                              Word('abominate', "",
                                   [TestWay('v',
                                            '憎恶',
                                            'to hate or loathe intensely, abhor',
                                            ['We abominate jokes that make fun of people who have physical disabilities. 我们鄙视对有生理缺陷的人开玩笑。'],
                                            ['despise', 'detest', 'execrate', 'loathe'],
                                            ['esteem', 'love', 'adore'])]),
                              Word('aboveboard', "",
                                   [TestWay('adj',
                                            '无欺诈的, 光明正大',
                                            'free from all traces of deceit or duplicity',
                                            ['This transaction was totally aboveboard, so there was no reason to question it. 这项交易完全公开公正, 没有必要质疑。'],
                                            antonyms = ['chicanery', 'surreptitious', 'underhanded'])]),
                              Word('abrade', "",
                                   [TestWay('v',
                                            '磨损, 精神上折磨',
                                            'to rub or wear away especially by friction; wear down spiritually',
                                            ['My skin was abraded. 我的皮肤被磨损了。'],
                                            ['chafe', 'excoriate', 'rasp', 'graze', 'scuff'],
                                            ['augment'])]),
                              Word('abridge', "",
                                   [TestWay('v',
                                            '缩短, 缩小',
                                            'to shorten in duration or extent',
                                            ['modern transportation abridges distance 现代运输方式缩短了路途'],
                                            ['curtail', 'truncate', 'cut back'],
                                            ['extend in length', 'protract', 'amplify']),
                                    TestWay('v',
                                            '在不改变本意的条件下删减词语, 缩写',
                                            'to shorten by omission of words without sacrifice of sense',
                                            ['an abridged edition 精简版'],
                                            ['abbreviate', 'curtail', 'condense', 'syncopate'])]),
                              Word('abrogate', "",
                                   [TestWay('v',
                                            '官方的正式废除',
                                            'to abolish by authoritative action, annul',
                                            ['abrogate the law/ treaty 废除法律、条约'],
                                            ['disannul', 'invalidate', 'nullify', 'quash', 'rescind', 'roll back', 'strike down'],
                                            ['embrace', 'uphold', 'institute']),
                                    TestWay('v',
                                            '无视(某事的)存在',
                                            'to treat as nonexistent',
                                            ['abrogate their responsibilities 抛开、不顾他们的责任'])]),
                              Word('abscond', "",
                                   [TestWay('v',
                                            '偷偷离开',
                                            'to depart secretly and hide oneself',
                                            ['abscond from the prison 越狱'],
                                            ['flee', 'lam', 'run off', 'break out (of)', 'clear out'])])])
list1_unit3 = VocabularyList([Word('absolute', "",
                                   [TestWay('adj',
                                            '专制的',
                                            'unconstrained by constitutional or other provisions',
                                            ['absolute ruler 专制的统治者'],
                                            ['arbitrary', 'autocratic', 'despotic', 'dictatorial', 'monocratic', 'tyrannical']),
                                    TestWay('adj',
                                            '无限的',
                                            'unqualified in extent or degree; total',
                                            ['absolute silence 鸦雀无声'],
                                            ['complete', 'utter', 'deadly', 'downright', 'out-and-out'],
                                            ['qualified']),
                                    TestWay('adj',
                                            '完美的、纯净不掺杂的',
                                            'free from imperfection free or relatively; free from mixture',
                                            ['absolute alcohol 无水酒精(纯酒精)'],
                                            ['plain', 'refined', 'unadulterated', 'unalloyed', 'undiluted', 'unmixed'],
                                            ['adulterated', 'alloyed', 'diluted', 'impure', 'mixed']),
                                    TestWay('adj',
                                            '不容置疑的, 确凿的',
                                            'positive, unquestionable',
                                            ['absolute proof 确凿的证据'],
                                            ['clear', 'deciding', 'decisive', 'definitive'],
                                            ['inconclusive', 'indecisive', 'unclear'])]),
                              Word('absolve', "",
                                   [TestWay('v',
                                            '使无罪, 解除责任',
                                            'to set free from an obligation or the consequences of guilt, exculpate',
                                            ['absolve somebody from blame 使某人免受责备'],
                                            ['acquit', 'exonerate', 'vindicate'],
                                            ['blame', 'criminate', 'incriminate'])]),
                              Word('abstain', "",
                                   [TestWay('v',
                                            '自我克制, 主动戒绝',
                                            "to refrain from something by one's own choice",
                                            ['abstain from smoking/voting 戒烟, 弃权'],
                                            ['forgo', 'keep from', 'refrain from', 'withhold (from)'],
                                            ['bow to', 'give in to', 'submit to', 'succumb to', 'surrender to', 'yield to'])]),
                              Word('abstemious', "",
                                   [TestWay('adj',
                                            '(吃喝等)有节制的, 节俭的',
                                            'marked by restraint especially in the consumption of food or alcohol, sparring',
                                            ['an abstemious diet 有节制的饮食', 'abstemious meals 节俭的晚餐'],
                                            ['continent', 'temperate', 'self-abnegating', 'self-denying'],
                                            ['indulgent'])]),
                              Word('abstract', "",
                                   [TestWay('vt',
                                            '做总结, 概括',
                                            'to make an abstract of, summarize',
                                            ['abstracted the 135-page report in three short paragraphs 将一份135页的报告概括为三段话'],
                                            ['digest', 'recapitulate', 'synopsize', 'sum up', 'boil down'],
                                            ['elaborate']),
                                    TestWay('vt',
                                            '使分心',
                                            'to draw away the attention of',
                                            ['personal problems abstracted him 私人问题让他分心'],
                                            ['detract', 'divert', 'call off', 'throw off'],
                                            ['attention'],
                                            'abstraction n. 心不在焉')]),
                              Word('abstruse', "",
                                   [TestWay('adj',
                                            '难以理解的',
                                            'difficult to comprehend: recondite',
                                            ['the abstruse calculations 复杂深奥的计算'],
                                            ['arcane', 'esoteric', 'hermetic (also hermetical)', 'recondite'],
                                            ['accessible', 'patent', 'shallow', 'superficial'])]),
                              Word('absurd', "",
                                   [TestWay('adj',
                                            '不合理的',
                                            'ridiculously unreasonable, unsound, or incongruous',
                                            ['an absurd argument 无稽之谈'],
                                            ['wild', 'bizarre', 'ludicrous', 'insane', 'nonsensical', 'preposterous', 'half-baked'],
                                            ['rational', 'sensible', 'realistic', 'reasonable'])]),
                              Word('abundant', "",
                                   [TestWay('adj',
                                            '大量的',
                                            'marked by great plenty (as of resources)',
                                            ['a abundant land 一片富饶的土地'],
                                            ['ample', 'cornucopian', 'teeming', 'replete', 'abounding'],
                                            ['infrequent', 'rare', 'uncommon', 'inadequate', 'scanty', 'scarce'])]),
                              Word('abuse', "",
                                   [TestWay('v',
                                            '辱骂抨击',
                                            'language that condemns or vilifies usually unjustly, intemperately, and angrily',
                                            ['He alleged that he was verbally abused by his colleagues. 他声称受到了同事的言语攻击。'],
                                            ['assail', 'bash', 'castigate', 'excoriate', 'lambaste'],
                                            other_form = 'abusive 辱骂的'),
                                    TestWay('v',
                                            '不正当不合理使用; 过分过量使用',
                                            'to put to a wrong or improper use; to use excessively',
                                            ['abuse a privilege 滥用特权', 'abuse alcohol 酗酒'],
                                            ['misemploy', 'misuse'])]),
                              Word('abut', "",
                                   [TestWay('v',
                                            '邻接, 毗邻',
                                            'to touch at one end or side; lie adjacent',
                                            ['Our land abuts a wildlife preserve. 我们的土地靠近一片野生动物保护区。'],
                                            ['skirt', 'verge on', 'border on', 'butt on', 'march with'])])])
list1_unit4 = VocabularyList([Word('abysmal', "",
                                   [TestWay('adj',
                                            '极低的或极可怜的',
                                            'immeasurably low or wretched',
                                            ['abysmal living conditions 极可怜的生活条件'],
                                            ['bottomless'],
                                            ['shallow', 'shoal']),
                                    TestWay('adj',
                                            '(程度)很深的、极端的',
                                            'immeasurably great',
                                            ['abysmal ignorance 极端的无知', 'an abysmal cliff 深不见底的悬崖'],
                                            ['profound'],
                                            ['skin-deep', 'superficial'])]),
                              Word('accede', "",
                                   [TestWay('v',
                                            '赞成',
                                            'to express approval or give consent',
                                            ['acceded to their pleas 同意了他们的请愿'],
                                            ['acquiesce', 'assent', 'consent', 'subscribe', 'come round'],
                                            ['demur', 'dissent']),
                                    TestWay('v',
                                            '就任, 就职',
                                            'To arrive at or come into an office or dignity',
                                            ['accede to the throne 就任国王'])]),
                              Word('accelerate', "",
                                   [TestWay('v',
                                            '加速',
                                            'to cause to move faster',
                                            ['accelerate his steps 加快脚步'],
                                            ['balloon', 'escalate', 'snowball', 'mushroom', 'proliferate', 'burgeon', 'build up'],
                                            ['retard']),
                                    TestWay('v',
                                            '使提前发生',
                                            'to bring about at an earlier time',
                                            ['accelerate their departure 提前离开']),
                                    TestWay('v',
                                            '变大, 变多',
                                            'to become greater in size, extent, volume, amount, or number',
                                            ['toy purchases accelerate dramatically during the Christmas season 玩具销售量在圣诞期间暴涨'],
                                            ['accumulate', 'balloon', 'enlarge', 'escalate', 'mushroom', 'proliferate', 'snowball', 'roll up'],
                                            ['contract', 'decrease', 'diminish', 'dwindle', 'lessen', 'recede', 'wane'])]),
                              Word('accessible', "",
                                   [TestWay('adj',
                                            '可以到达的',
                                            'situated within easy reach',
                                            ['the town accessible by rail 有铁路通达的城'],
                                            ['handy', 'reachable'],
                                            ['inconvenient', 'unhandy', 'unreachable', 'untouchable']),
                                    TestWay('adj',
                                            '可理解的',
                                            'capable of being understood or appreciated',
                                            ['The information ought to be made more accessible. 信息应该更清晰易懂。'],
                                            ['apprehensible', 'fathomable', 'legible', 'scrutable'],
                                            ['abstruse', 'incoherent', 'incomprehensible', 'inscrutable', 'insensible']),
                                    TestWay('adj',
                                            '能够获得的',
                                            'possible to get',
                                            ['The data is not currently accessible. 数据目前还不可用。'],
                                            ['available', 'attainable', 'obtainable', 'procurable'],
                                            ['unattainable', 'unavailable', 'unobtainable'])]),
                              Word('accessory', "",
                                   [TestWay('adj',
                                            '辅助的, 附属的',
                                            'having a secondary, supplementary, or subordinate function',
                                            ['accessory features such as call-waiting 类似呼叫等待的附属功能'],
                                            ['accessory', 'peripheral', 'supplementary'],
                                            ['of primarily importance', 'chief', 'main', 'principal']),
                                    TestWay('n',
                                            '帮凶',
                                            'one associated with another in wrongdoing',
                                            ['two accessories, the driver of the getaway car and the dishonest bank teller, were charged in the robbery case 两个帮凶, 逃逸车辆的司机和不诚信的银行出纳, 在抢劫案中被控告'],
                                            ['abettor', 'confederate'])]),
                              Word('accidental', "",
                                   [TestWay('adj',
                                            '意外发生的, 偶然的',
                                            'occurring unexpectedly or by chance',
                                            ['The discovery of gold was entirely accidental. 黄金的发现纯属偶然。'],
                                            ['incidental', 'fortuitous', 'unintended', 'unintentional', 'unpremeditated', 'unwitting'],
                                            ['calculated', 'deliberate', 'intended', 'planned', 'premeditated']),
                                    TestWay('adj',
                                            '附带的, 不重要',
                                            'not being a vital part of or belonging to something',
                                            ['Its commercial value was accidental. 它的商业价值微乎其微。'],
                                            ['alien', 'extraneous', 'external', 'adventitious'],
                                            ['inherent', 'innate', 'intrinsic'])]),
                              Word('acclimate', "",
                                   [TestWay('vt',
                                            '使适应',
                                            'to change (something) so as to make it suitable for a new use or situation',
                                            ['acclimate oneself to a nine-to-five office job 适应朝九晚五的坐班生活'],
                                            ['adjust', 'accommodate', 'shape', 'suit', 'tailor'],
                                            ['make unfamiliar with'])]),
                              Word('accolade', "",
                                   [TestWay('n',
                                            '同意, 赞赏',
                                            'an expression of approval',
                                            ['won virtually every accolade that the film world has to offer 赢得了电影界几乎一致的赞赏'],
                                            ['applause', 'credit', 'distinction'],
                                            ['disapprobation']),
                                    TestWay('v',
                                            '赞扬',
                                            'to praise or honor',
                                            antonyms = ['excoriation', 'criticism', 'reprobation', 'castigation', 'cutting remark', 'derogation', 'reproof', 'denigration', 'denunciation', 'swearword'])]),
                              Word('accommodate', "",
                                   [TestWay('v',
                                            '提供所需(例如服务、借贷、寄宿)',
                                            'to provide with something desired, needed, or suited (as a helpful service, a loan, or lodgings)',
                                            ['This cruise ship was big enough to accommodate over 600 people. 该游轮可以为超过600 人提供食宿。'],
                                            ['fit', 'hold', 'take']),
                                    TestWay('v',
                                            '改变以适应新情况、新场景',
                                            'to change (something) so as to make it suitable for a new use or situation',
                                            ['accommodated the lectern to the height of the guest speaker 将讲台的高度调节得适合讲演者'],
                                            ['acclimate', 'adjust', 'condition', 'conform', 'doctor', 'edit', 'shape', 'suit', 'tailor']),
                                    TestWay('v',
                                            '使和谐',
                                            'to bring to a state free of conflicts, inconsistencies, or differences',
                                            ['The idea that the United States could harmoniously accommodate all was a fiction. 认为美国能够和谐一切就是幻想。'],
                                            ['attune', 'conciliate', 'conform', 'coordinate', 'reconcile'],
                                            ['disharmonize'])]),
                              Word('accost', "",
                                   [TestWay('vt',
                                            '以挑衅的形式搭讪',
                                            'to approach and speak to often in a challenging or aggressive way',
                                            ['accosted by three gang members 被三个混混搭讪'])])])
list1_unit5 = VocabularyList([Word('accrete', "",
                                   [TestWay('v',
                                            '逐渐增长',
                                            'to grow or increase gradually, as by addition',
                                            ['silt accreting at the mouth of the river 泥沙在河口淤积'],
                                            ['accumulate', 'build up', 'pile (up)', 'stack (up)'],
                                            ['wear away', 'reduction in substance caused by erosion'],
                                            'accretion n. 慢慢增加')]),
                              Word('accumulate', "",
                                   [TestWay('vi',
                                            '逐渐增长',
                                            'to increase gradually in quantity or number',
                                            ['accumulate a fortune 积攒了一笔财富'],
                                            ['mount', 'swell', 'garner', 'snowball', 'build up', 'bulk (up)'],
                                            ['dissipate', 'diminish', 'dwindle', 'recede', 'wane'])]),
                              Word('acerbic', "",
                                   [TestWay('adj',
                                            '酸涩的心情、心境或者语调',
                                            'marked by the use of wit that is intended to cause hurt feelings',
                                            ['acerbic commentary 尖酸的评论'],
                                            ['pungent', 'sardonic', 'satiric', 'scalding', 'scathing'],
                                            ['sweet', 'saccharin'],
                                            'acerbity n. 酸')]),
                              Word('acme', "",
                                   [TestWay('n',
                                            '顶点, 极点',
                                            'the highest point or stage, as of achievement or development',
                                            ['the acme of his career 他事业的巅峰'],
                                            ['culmination', 'pinnacle', 'tip-top', 'high-water mark'],
                                            ['bottom', 'nadir', 'rock bottom'])]),
                              Word('acquiesce', "",
                                   [TestWay('v',
                                            '勉强同意; 默许',
                                            'to accept, comply, or submit tacitly or passively',
                                            ['acquiesce to my own fleecing 默许我的敲竹杠行为'],
                                            ['assent', 'consent', 'subscribe', 'come round'],
                                            ['resist', 'defy', 'dissent'])]),
                              Word('acrid', "",
                                   [TestWay('adj',
                                            '辛辣的, 刺鼻的',
                                            'sharp and harsh or unpleasantly pungent in taste or odor: irritating',
                                            ['acrid smell of tobacco 烟草刺鼻的味道']),
                                    TestWay('adj',
                                            '刻薄的',
                                            'marked by the use of wit that is intended to cause hurt feelings',
                                            ['acrid temper 刻薄的性情'],
                                            antonyms = ['gentle'])]),
                              Word('acrimonious', "",
                                   [TestWay('adj',
                                            '刻薄的, 充满仇恨的',
                                            'having or showing deep-seated resentment',
                                            ['the acrimonious debate between the two candidates 候选人之间言辞激烈的辩论'],
                                            ['embittered', 'hard', 'rancorous', 'resentful', 'sore'])]),
                              Word('acumen', "",
                                   [TestWay('n',
                                            '不同寻常的洞察力和鉴别力',
                                            'exceptional discernment and judgment especially in practical matters',
                                            ['the business acumen 商业方面的洞察力'],
                                            ['keenness', 'shrewdness', 'canniness', 'clear-sightedness', 'hardheadedness'],
                                            ['unable to discerning'])]),
                              Word('acute', "",
                                   [TestWay('adj',
                                            '敏锐的',
                                            'marked by keen discernment or intellectual perception especially of subtle distinctions, penetrating',
                                            ['an acute thinker 思维敏锐的思想者'],
                                            ['delicate', 'fine', 'keen', 'perceptive', 'sensitive']),
                                    TestWay('adj',
                                            '严重的, 急性的',
                                            'needing immediate attention',
                                            ['acute appendicitis 急性阑尾炎'],
                                            ['exigent', 'imperative', 'compelling', 'urgent'],
                                            ['mild', 'noncritical', 'nonurgent']),
                                    TestWay('adj',
                                            '(程度、影响)极强',
                                            'extreme in degree, or effect',
                                            ['experiencing acute distress over the misunderstanding with her best friend 因误会她的死党陷入了深深的痛苦'],
                                            ['dreadful', 'excruciating', 'profound'],
                                            ['light', 'moderate', 'soft'])]),
                              Word('adamant', "",
                                   [TestWay('adj',
                                            '固执的, 不可动摇的',
                                            'unshakable or insistent especially in maintaining a position or opinion, unyielding; inflexible',
                                            ['adamant about staying here 执意留下来'],
                                            ['hardheaded', 'headstrong', 'intransigent', 'pertinacious', 'obdurate', 'uncompromising'],
                                            ['vacillatory', 'incline to yield', 'amenable', 'compliant', 'relenting', 'yielding'])])])
list1_unit6 = VocabularyList([Word('adapt', "",
                                   [TestWay('vt',
                                            '修改, 使适应',
                                            'to modify according with the changing circumstances',
                                            ['adapt to the change 适应变化', 'adapt the novel for the screen 改编小说为影视作品'],
                                            ['adjust', 'conform', 'edit', 'accommodate', 'shape', 'suit', 'tailor'])]),
                              Word('addict', "",
                                   [TestWay('v',
                                            '沉溺, 上瘾',
                                            'to devote or surrender (oneself) to something habitually or obsessively',
                                            ['be addicted to drug/ alcohol 沉溺于毒品、酒']),
                                    TestWay('n',
                                            '对某事上瘾的人',
                                            'a person with a strong and habitual liking for something',
                                            ['science-fiction addicts who eagerly await each new installment in the series 科幻小说爱好者, 等待着系列的每一次更新'],
                                            ['devotee', 'enthusiast', 'fanatic', 'maniac'],
                                            ['nonfan'])]),
                              Word('adhere', "",
                                   [TestWay('v',
                                            '依附, 粘着',
                                            'to cause to stick fast',
                                            ['adhere to the surface 附着在表面'],
                                            ['cleave', 'cling', 'hew'],
                                            ['detach']),
                                    TestWay('v',
                                            '服从命令',
                                            'to act according to the commands of',
                                            ['adhere to the rules 遵守规定'],
                                            ['cling to', 'hew to', 'stand by', 'stick to', 'comply with'],
                                            ['defy', 'disobey', 'rebel against']),
                                    TestWay('v',
                                            '坚定地支持',
                                            'to give steadfast support to',
                                            ['our coach adheres to the belief that we can win this game if we just have a positive attitude 我们的教练坚定地相信, 只要我们有积极的态度, 我们就能拿下比赛'],
                                            ['keep to', 'stand by', 'stick to or with'],
                                            ['defect from'],
                                            'adherent n. 追随者: a follower of a leader, party, or profession 【反】forerunner 先行者')]),
                              Word('adjourn', "",
                                   [TestWay('vi',
                                            '延期, 休会',
                                            'to suspend a session indefinitely or to another time or place',
                                            ['The meeting adjourned for a week. 会议延期一周。'],
                                            ['prorogate', 'prorogue', 'recess', 'suspend'],
                                            ['convoke'])]),
                              Word('adjunct', "",
                                   [TestWay('n',
                                            '附属物, 非必须部分',
                                            'something joined or added to another thing but not essentially a part of it',
                                            ['Massage therapy can be used as an adjunct along with the medication. 按摩治疗可以作为药物治疗的补充疗法。'],
                                            ['appendage', 'appliance', 'attachment', 'add-on'],
                                            ['essential element'])]),
                              Word('ad-lib', "",
                                   [TestWay('adj',
                                            '即兴的',
                                            'made or done without previous thought or preparation',
                                            ['not bad for an ad-lib comedy routine 对即兴喜剧表演来说已经不错了'],
                                            ['extemporary', 'impromptu', 'improvisational', 'offhanded'],
                                            ['considered', 'planned', 'premeditated', 'rehearsed'])]),
                              Word('admonish', "",
                                   [TestWay('v',
                                            '建议',
                                            'to give advice to',
                                            ['admonished the patient to eat more healthy foods 建议患者多吃健康食品'],
                                            ['counsel']),
                                    TestWay('v',
                                            '责备',
                                            'to reprove gently but earnestly.',
                                            ['admonished her for littering 责备她乱扔垃圾'],
                                            ['chide', 'reprimand', 'reproach', 'reprove', 'tick off'],
                                            other_form = 'admonishment n. 责备')]),
                              Word('adore', "",
                                   [TestWay('vt',
                                            '喜爱, 感到愉悦',
                                            'to take pleasure in',
                                            ['I adore those earrings. 我相中那对耳环了。'],
                                            ['fancy', 'relish', 'savor', 'delight in', 'rejoice in']),
                                    TestWay('vt',
                                            '宠爱',
                                            'to feel passion, devotion, or tenderness for',
                                            ['adored his wife 宠爱他的妻子'],
                                            ['cherish'],
                                            ['abhor', 'abominate', 'despise', 'detest', 'execrate', 'loathe'])]),
                              Word('adulate', "",
                                   [TestWay('v',
                                            '极度谄媚',
                                            'to praise too much',
                                            ['incompetent assistants who spend all their time adulating her 成天恭维她的不称职的下属'],
                                            ['overpraise', 'belaud', 'soft-soap', 'butter up'],
                                            ['scorn', 'disdain', 'vituperate', 'disparage'])]),
                              Word('adulterate', "",
                                   [TestWay('vt',
                                            '掺杂, 加入低等成分',
                                            'to corrupt, debase, or make impure by the addition of a foreign or inferior substance or element',
                                            ['adulterate its products with cheap additives 在产品中掺杂廉价的添加剂'],
                                            ['alloy', 'contaminate', 'pollute', 'taint', 'water down'],
                                            ['enrich', 'fortify', 'strengthen'])])])
list1_unit7 = VocabularyList([Word('adumbrate', "",
                                   [TestWay('vt',
                                            '部分地或有保留地揭露',
                                            'to disclose partially or guardedly',
                                            ['adumbrate a plan 透露计划'],
                                            ['revelation 完全显示']),
                                    TestWay('vt',
                                            '预示着',
                                            'to give a slight indication of beforehand',
                                            ['The strife in Bloody Kansas adumbrated the civil war that would follow. 发生在堪萨斯州的流血冲突预示了之后的南北内战的爆发。'],
                                            ['forerun', 'harbinger', 'herald', 'prefigure'])]),
                              Word('adventitious', "",
                                   [TestWay('adj',
                                            '外来的, 后天的',
                                            'coming from another source and not inherent or innate',
                                            ['Moral considerations are adventitious to the study of art. 道德的考量对于艺术研究来说是不必要的。'],
                                            ['alien', 'extraneous', 'external', 'foreign', 'supervenient'],
                                            ['constitutional', 'essential', 'intrinsic', 'inborn', 'inbred', 'innate', 'inherent'])]),
                              Word('adversary', "",
                                   [TestWay('n',
                                            '敌手, 对手',
                                            'one that contends with, opposes, or resists: enemy',
                                            ['political adversary 政敌'],
                                            ['antagonist', 'foe', 'opponent'],
                                            ['ally', 'amigo', 'friend'])]),
                              Word('advert', "",
                                   [TestWay('vi',
                                            '引起注意; 提到',
                                            'to call attention; refer',
                                            ['He adverted to the problem in the opening paragraph. 他开门见山地引出了问题。'],
                                            antonyms = ['inattentive, remiss, heedless, negligent'],
                                            other_form = 'advertent adj. 留意的')]),
                              Word('advocate', "",
                                   [TestWay('vt',
                                            '支持, 提倡',
                                            'to speak, plead, or argue in favor of; support',
                                            ['advocates traditional teaching methods 提倡传统教学方法'],
                                            ['back', 'champion', 'endorse', 'patronize'],
                                            ['impunge'])]),
                              Word('affable', "",
                                   [TestWay('adj',
                                            '和蔼的, 温和的',
                                            'characterized by ease and friendliness',
                                            ['an affable manner 随和的举止'],
                                            ['cordial', 'genial', 'hospitable', 'sociable', 'good-natured', 'good-tempered', 'well-disposed'],
                                            ['irascible', 'testy', 'ill-tempered', 'unamiable', 'ungenial'])]),
                              Word('affinity', "",
                                   [TestWay('n',
                                            '喜欢, 亲切感',
                                            'a habitual attraction to some activity or thing',
                                            ['always had an affinity for nurturing living things 喜欢培养活物'],
                                            ['bent', 'penchant', 'predilection', 'predisposition', 'proclivity', 'propensity'],
                                            ['aversion', 'repugnance', 'antipathy']),
                                    TestWay('n',
                                            '相似',
                                            'the fact or state of having something in common',
                                            ['a study showing an affinity between obesity and socioeconomic status 一项表现了肥胖程度和社会经济水平之间相似性的研究'],
                                            ['association', 'bearing', 'kinship'])]),
                              Word('affluent', "",
                                   [TestWay('adj',
                                            '富裕的',
                                            'having a generously sufficient and typically increasing supply of material possessions',
                                            ['affluent society 富裕的社会'],
                                            ['opulent', 'loaded', 'deep-pocketed', 'silk-stocking', 'well-endowed', 'well-off', 'well-to-do'],
                                            ['needy', 'impecunious', 'impoverished', 'indigent', 'penurious'])]),
                              Word('aggrandize', "",
                                   [TestWay('vt',
                                            '增加、提高力量、财富、地位、声誉等',
                                            'to enhance the power, wealth, position, or reputation of',
                                            ['exploited the situation to aggrandize himself 借势而上使得自己地位提升、财富增长'],
                                            ['augment', 'boost', 'expand', 'magnify', 'add (to)', 'pump up'],
                                            ['relegate', 'disparage', 'efface', 'abase', 'demean'])]),
                              Word('aggravate', "",
                                   [TestWay('vt',
                                            '加重, 恶化',
                                            'to make worse, more serious, or more severe',
                                            ['Stress and lack of sleep could aggravate the situation. 压力和睡眠不足使情况恶化。'],
                                            ['complicate', 'worsen'],
                                            ['alleviate', 'succor', 'console', 'assuage', 'mitigate', 'relieve']),
                                    TestWay('v',
                                            '使不爽',
                                            'to disturb the peace of mind of (someone) especially by repeated disagreeable acts',
                                            ["it really aggravates me when I arrive 10 minutes before the stated closing time, and the store's closed already 我在号称的打烊时间前 10 分钟到达, 但发现商店已经关门了, 让我很不爽"],
                                            ['annoy', 'bother', 'nettle', 'vex'])])])
list1_unit8 = VocabularyList([Word('aggregate', "",
                                   [TestWay('n',
                                            '集合体',
                                            'a mass or body of units or parts somewhat loosely associated with one another',
                                            ['An empire is the aggregate of many states under one common head.帝国是以一个共同领袖领导的若干国家的集合体。'],
                                            ['sum', 'summation', 'totality'],
                                            ['isolated units']),
                                    TestWay('v',
                                            '集合, 聚集',
                                            'to collect or gather into a mass or whole',
                                            ['aggregates content from many other sites 搜罗集合了其他网站的内容'],
                                            ['coalesce', 'join together'],
                                            other_form = 'disaggregate v. 分解 【反】disperse')]),
                              Word('aggressive', "",
                                   [TestWay('adj',
                                            '好斗的',
                                            'having a quality of anger and determination that makes it ready to attack others',
                                            ['aggressive behavior 具有攻击性的行为'],
                                            ['fierce', 'assaultive', 'combative', 'militant', 'confrontational', 'go-getting', 'self-assertive', 'truculent', 'pugnacious'],
                                            ['even-tempered', 'nonbelligerent', 'pacific', 'uncombative', 'uncontentious']),
                                    TestWay('adj',
                                            '强有力的, 强烈的',
                                            'marked by or uttered with forcefulness',
                                            ['an aggressive campaign to win the African-American vote 一次能够获得非裔美国人选票的强有力的竞选'],
                                            ['dynamic', 'energetic', 'full-blooded', 'vigorous'])]),
                              Word('aggrieve', "",
                                   [TestWay('vt',
                                            '使苦恼,悲痛',
                                            'to give pain or trouble to, distress',
                                            ['a line of aggrieved ticket-holders, demanding a refund for the cancelled play 一队怨念的购票者, 为取消的话剧要求退款'],
                                            ['discontent', 'disgruntled', 'displeased', 'dissatisfied', 'malcontent'],
                                            ['gratify'],
                                            'aggrieved adj. 苦恼的, 怨念的')]),
                              Word('agitate', "",
                                   [TestWay('v',
                                            '煽动, 激起',
                                            'to attempt to arouse public feeling',
                                            ['agitate for better conditions 为得到更好的工作条件而煽动'],
                                            ['debate', 'dispute', 'bat (around or back and forth)', 'hash (over or out)', 'talk over']),
                                    TestWay('v',
                                            '使不安',
                                            'to excite and often trouble the mind or feelings of: disturb',
                                            ["There's no need to agitate the patient about little things. 没必要因为鸡毛蒜皮的事让患者烦躁。"],
                                            ['bother', 'discomfort', 'discompose', 'perturb'],
                                            ['calm', 'compose', 'soothe', 'tranquilize'])]),
                              Word('agog', "",
                                   [TestWay('adj',
                                            '极度感兴趣的',
                                            'showing urgent desire or interest',
                                            ['Children were agog over new toys. 孩子们见到了新玩具极其兴奋。'],
                                            ['avid', 'ardent', 'enthusiastic', 'solicitous', 'voracious'],
                                            ['apathetic', 'indifferent', 'uneager', 'unenthusiastic'])]),
                              Word('agonize', "",
                                   [TestWay('v',
                                            '使非常痛苦',
                                            'to feel deep sadness or mental pain',
                                            ['agonizes over every decision 做每一个决定都非常痛苦'],
                                            ['anguish, suffer'])]),
                              Word('airtight', "",
                                   [TestWay('adj',
                                            '无瑕疵的',
                                            'having no noticeable weakness, flaw, or loophole',
                                            ['an airtight argument 滴水不漏、无懈可击的论断']),
                                    TestWay('adj',
                                            '密封的, 不透气的',
                                            'impermeable to air or nearly so',
                                            ['an airtight seal 不透气的封口'])]),
                              Word('alacrity', "",
                                   [TestWay('n',
                                            '反应迅速, 乐意',
                                            'promptness in response: cheerful readiness',
                                            ['accepted the invitation with alacrity 欣喜地接受了邀请'],
                                            ['amenability', 'gameness', 'obligingness', 'willingness'],
                                            ['dilatoriness', 'hesitance and reluctance'])]),
                              Word('alibi', "",
                                   [TestWay('n',
                                            '不在场的证明; 托辞, 借口',
                                            'an excuse usually intended to avert blame or punishment (as for failure or negligence)',
                                            ['He always has a very creative alibi for undone homework. 他对于不完成作业总是有各种新奇的借口。'],
                                            ['defense', 'justification', 'plea', 'reason'])]),
                              Word('alienate', "",
                                   [TestWay('v',
                                            '疏远, 离间',
                                            'to make unfriendly, or indifferent especially where attachment formerly existed',
                                            ['alienated most of his colleagues with his bad temper 因为他的坏脾气, 很多同事都和他疏远了s'],
                                            ['disaffect', 'disgruntle', 'sour'],
                                            ['unite', 'reunite', 'reconcile']),
                                    TestWay('v',
                                            '转移、变卖(财产或权利)',
                                            'to convey or transfer (as property or a right) usually by a specific act rather than the due course of law',
                                            ['A landowner has a right to alienate his right of ownership. 地主有权利变卖自己的地产。'],
                                            ['assign', 'cede', 'deed', 'make over'])])])
list1_unit9 = VocabularyList([Word('align', "",
                                   [TestWay('vt',
                                            '排成一行',
                                            'to bring into line or alignment',
                                            ['align the cars with the curb 使车与路缘对齐'],
                                            antonyms = ['askew', 'awry', 'warped']),
                                    TestWay('vt',
                                            '调准, 校准',
                                            'to adjust to produce a proper relationship or orientation',
                                            ['align the wheels of the truck 调整卡车的轮子'],
                                            antonyms = ['improperly adjusted', 'irregular'])]),
                              Word('allay', "",
                                   [TestWay('vt',
                                            '减轻',
                                            'to subdue or reduce in intensity or severity, alleviate',
                                            ['allay one’s fears or doubts 减轻某人的恐惧或怀疑'],
                                            ['assuage', 'ease', 'mitigate', 'mollify', 'palliate', 'relieve', 'soothe'],
                                            ['excite', 'aggravate', 'foment', 'increase the intensity of', 'exacerbate'])]),
                              Word('allegiance', "",
                                   [TestWay('n',
                                            '忠诚',
                                            'devotion or loyalty to a person, group, or cause',
                                            ['They swore their allegiance to the USA. 他们宣誓效忠美国。'],
                                            ['commitment', 'dedication', 'piety', 'faithfulness', 'steadfastness'],
                                            ['inconstancy', 'infidelity', 'perfidiousness', 'treachery'])]),
                              Word('alleviate', "",
                                   [TestWay('v',
                                            '缓和, 减轻',
                                            'relieve, lessen',
                                            ['alleviate pain/suffering 减轻痛苦'],
                                            ['ease', 'assuage', 'mitigate', 'mollify', 'palliate', 'soothe'],
                                            ['exacerbate'])]),
                              Word('allude', "",
                                   [TestWay('vi',
                                            '间接提到',
                                            'to attract or delight as if by magic',
                                            ["He also alluded to his rival's past marital troubles. 他间接提到了对手过去的婚姻问题。"],
                                            ['imply', 'indicate', 'infer', 'insinuate', 'intimate', 'suggest'])]),
                              Word('allure', "",
                                   [TestWay('vt',
                                            '吸引',
                                            'to attract or delight as if by magic',
                                            synonyms = ['entice', 'seduce', 'solicit', 'tempt', 'captivate', 'enchant', 'lead on'],
                                            other_form = 'alluring 诱惑的, 有吸引力的 【例】 an alluring smile 迷人的微笑 【反】 unattractive 无吸引力的'),
                                    TestWay('vt',
                                            '诱惑做某事',
                                            'to lead away from a usual or proper course by offering some pleasure or advantage',
                                            ['allured by the promise of big bucks, he decided to have a go at a job on the trading floor of the stock market 被赚大钱的许诺所引诱, 他决定投身股票市场工作'],
                                            ['bait', 'beguile', 'decoy', 'entice', 'seduce', 'lead on'])]),
                              Word('ally', "",
                                   [TestWay('n',
                                            '盟友, 支持者',
                                            'one in helpful association with another',
                                            ['enter the war as an ally of America 以美国的同盟者身份加入战争'],
                                            ['supporter', 'confederate', 'sympathizer'],
                                            ['adversary', 'rival']),
                                    TestWay('v',
                                            '加入联盟',
                                            'to enter into an alliance',
                                            ['several tribes allied to fend off the invaders 几个部落联合起来抵抗侵略者'],
                                            antonyms = ['disband'])]),
                              Word('aloft', "",
                                   [TestWay('adv',
                                            '在空中',
                                            'in the air especially: in flight (as in an airplane)',
                                            ['The balloon stayed aloft for dayy. 气球在空中停留了很多天。'],
                                            ['overhead'],
                                            ['grounded'])]),
                              Word('aloof', "",
                                   [TestWay('adj',
                                            '孤高的, 不合群的',
                                            'removed or distant either physically or emotionally',
                                            ['an aloof church 一座孤零零的教堂', 'stood apart with aloof dignity 带着超然的尊严站在一旁'],
                                            ['detached', 'offish', 'unsociable', 'withdrawn', 'standoffish'],
                                            ['sociable'])]),
                              Word('altruism', "",
                                   [TestWay('n',
                                            '利他主义',
                                            'unselfish regard for or devotion to the welfare of others',
                                            ['Ambition that is masked as altruism. 在利他主义掩盖下的野心。'],
                                            antonyms = ['egoism'],
                                            other_form = 'altruistic adj.利他的 【反】egotistic, self-centered, self-concerned, selfish')])])
list1_unit10 = VocabularyList([Word('amalgamate', "",
                                   [TestWay('v',
                                            '合并, 混合',
                                            'to combine into a unified or integrated whole; unite',
                                            ['to amalgamate with an American company 与一家美国公司合并'],
                                            ['mix', 'fuse', 'intermix', 'compound', 'meld', 'comingle', 'integrate', 'intermingle'],
                                            ['separate', 'isolate'])]),
                              Word('ambiguous', "",
                                   [TestWay('adj',
                                            '有多种理解方式的; 不确定的',
                                            'open to more than one interpretation; doubtful or uncertain',
                                            ['Students have ambiguous feelings about their role in the world. 学生们为他们在世界中的角色感到迷茫。', 'Frustrated by ambiguous instructions 因为不明确的指示而受挫'],
                                            ['doubtful', 'equivocal', 'unclear', 'uncertain'],
                                            ['distinct', 'pellucid', 'patent', 'blatant', 'explicit', 'lucid', 'perspicuous'])]),
                              Word('amble', "",
                                   [TestWay('vi./n',
                                            '漫步, 闲逛',
                                            'to walk slowly or leisurely; stroll',
                                            ['Every evening, they ambled along the bank. 他们每晚沿河边散步。'],
                                            ['ramble', 'saunter', 'stroll', 'wander', 'dally', 'dawdle'],
                                            ['step quickly'])]),
                              Word('ambrosial', "",
                                   [TestWay('adj',
                                            '(食物或者气味)特别美味的',
                                            'something extremely pleasing to taste or smell',
                                            ['The ambrosial aroma of the roast stimulated our appetites. 烤肉的美味香气刺激了我们的食欲。'],
                                            ['savory', 'aromal', 'aromatic', 'perfumed', 'redolent', 'odorous'],
                                            ['fetid', 'noisome', 'stenchy', 'malodorous', 'rancid'])]),
                              Word('ameliorate', "",
                                   [TestWay('vt',
                                            '改善, 改进',
                                            'to make or become better; improve',
                                            ['to ameliorate the suffering of people who have lost their jobs 改善失业人员的痛苦'],
                                            ['improve', 'convalesce', 'recuperate'],
                                            ['aggravate', 'worsen', 'deteriorate'],
                                            'ameliorator n. 改良物【反】damper n. 抑制因素')]),
                              Word('amenable', "",
                                   [TestWay('adj',
                                            '顺从的, 服从的',
                                            'readily brought to yield, submit, or cooperate',
                                            ['a high-spirited and rebellious girl not at all amenable to persuasion. 一个泼辣而反叛的女孩根本不听从劝告。'],
                                            ['compliant', 'docile', 'submissive', 'tractable', 'obedient'],
                                            ['intransigent', 'contumacious', 'intractable', 'recalcitrant', 'refractory', 'uncontrollable', 'ungovernable', 'unruly'])]),
                              Word('amenity', "",
                                   [TestWay('n',
                                            '(环境, 设备等的)舒适, 人性化',
                                            'something that conduces to comfort, convenience, or enjoyment',
                                            ['the amenity of the new surroundings 新环境的宜人之处'],
                                            ['comfort', 'convenience', 'affability']),
                                    TestWay('n',
                                            '融洽, 和谐',
                                            'the quality of being pleasant or agreeable',
                                            ['a discussion conducted in perfect amenity 在和谐融洽的气氛中进行的讨论'],
                                            ['agreeability', 'cordiality', 'harmony', 'accord', 'concord', 'consonance'],
                                            ['discordance', 'inharmony'])]),
                              Word('amiable', "",
                                   [TestWay('adj',
                                            '好脾气的, 友好易相处的',
                                            'being friendly, sociable, and congenial',
                                            ['an amiable teacher not easily annoyed 一个不易惹恼易相处的老师'],
                                            ['friendly', 'affable', 'amicable', 'genial', 'easy to get along with'],
                                            ['disagreeable', 'ill-natured', 'ill-tempered', 'unamiable', 'ungenial', 'ungracious', 'unpleasant'])]),
                              Word('amicable', "",
                                   [TestWay('adj',
                                            '友善的',
                                            'characterized by friendly goodwill; amiable',
                                            ['maintain amicable relations 保持友好关系; an amicable divorce 和平离婚'],
                                            ['friendly', 'affable', 'amicable', 'genial', 'easy to get along with'],
                                            ['antagonistic', 'hostile', 'unfriendly'])]),
                              Word('amity', "",
                                   [TestWay('n',
                                            '友好, 亲善和睦关系',
                                            'friendship; especially: friendly relations between nations',
                                            ['live in amity with his neighbors 与邻居和谐相处', 'They parted in amity. 他们很友好地分别了。'],
                                            ['friendship'],
                                            ['enmity', 'hostility'])])])

LIST1 = VocabularyList(list1_unit1.words+list1_unit2.words+list1_unit3.words+list1_unit4.words+list1_unit5.words+list1_unit6.words+list1_unit7.words+list1_unit8.words+list1_unit9.words+list1_unit10.words)
