#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list17_unit1 = VocabularyList([Word('nuance', "",
                                   [TestWay('n',
                                            '细微的差异',
                                            'a subtle distinction or variation',
                                            ["a poem of little depth and nuance 一首没有什么深度、没有什么辨识度的诗"],
                                            antonyms = 'patent difference, lack of subtlety, sharp distinction, patency')]),
                              Word('nudge', "",
                                   [TestWay('vt',
                                            '用肘推以引起注意',
                                            'to seek the attention of by a push of the elbow',
                                            ["accidentally nudged me as he squeezed past 他过去的时候不小心用肘碰到了我"]),
                                    TestWay('vt',
                                            '说服某人做某事',
                                            'to try to persuade (someone) through earnest appeals to follow a course of action',
                                            ["the car salesman nudged me into taking a test-drive 汽车销售员说服我进行试驾"],
                                            'encourage, exhort, goad, press, prod, prompt')]),
                              Word('nugatory', "",
                                   [TestWay('adj',
                                            '无关紧要的',
                                            'of little or no consequence; inconsequential',
                                            ["the book is entertaining, but its contributions to Shakespearean scholarship are nugatory 这本书娱乐性不错, 但是对于莎士比亚研究的贡献微不足道"],
                                            'incidental, inconsequential, inconsiderable, insignificant, negligible, trifling, trivial',
                                            'consequential, eventful, important, major, meaningful, momentous, significant, substantial, unfrivolous, weighty')]),
                              Word('nurture', "",
                                   [TestWay('vt',
                                            '提供营养',
                                            'to supply with nourishment',
                                            ["nurtured her children through the winters with home-cooked soup 一整个冬天都给孩子们喂自制的汤"],
                                            antonyms = 'withhold sustenance from'),
                                    TestWay('vt',
                                            '培育, 培养',
                                            'to provide (someone) with moral or spiritual understanding',
                                            ["he feels that his lifelong practice of reading the Bible daily has nurtured him in ways he cannot describe 一生中每天都阅读圣经在潜移默化中影响了他"],
                                            'edify, illuminate, inspire',
                                            'impede, stunt, disregard')]),
                              Word('oath', "",
                                   [TestWay('n',
                                            '誓言',
                                            'a solemn, formal declaration or promise to fulfill a pledge',
                                            ["an oath to defend the nation 保卫祖国的誓言"],
                                            'pledge, troth, vow, word')]),
                              Word('obdurate', "",
                                   [TestWay('adj',
                                            '固执的',
                                            'resistant to persuasion or softening influences',
                                            ["She is known for her obdurate determination. 她以坚定不移著称。"],
                                            'adamant, hard-nosed, headstrong, inflexible, intransigent, pertinacious, stubborn, unbending, uncompromising, unrelenting, unyielding, willful',
                                            'acquiescent, agreeable, amenable, compliant, complying, flexible, pliable, pliant, relenting, yielding'),
                                    TestWay('adj',
                                            '冷酷无情的',
                                            'having or showing a lack of sympathy or tender feelings',
                                            ["the obdurate refusal of the crotchety old man to let the neighborhood kids retrieve their ball from his backyard 那个怪老头冷酷无情地拒绝了孩子们进他后院找球的请求"],
                                            'affectless, callous, compassionless, hard-hearted, heartless, indurate, inhuman, insensate, ironhearted, merciless, remorseless, ruthless, unsparing',
                                            'charitable, compassionate, humane, kindhearted, kindly, merciful, softhearted, sympathetic, tender, warmhearted')]),
                              Word('obedient', "",
                                   [TestWay('adj',
                                            '服从的, 顺从的',
                                            'submissive to the restraint or command of authority',
                                            ["that girl is so obedient that she does everything the first time she is asked 这个妹子如此顺从, 叫她做事随叫随到"],
                                            'amenable, compliant, submissive, tractable',
                                            'contumacious, imperial, balky, contrary, contumacious, defiant, disobedient, froward, incompliant, insubordinate, intractable, noncompliant, obstreperous, rebel, rebellious, recalcitrant, refractory, restive, unamenable, ungovernable, unruly, untoward, wayward, willful')]),
                              Word('obeisance', "",
                                   [TestWay('n',
                                            '敬礼, 尊重',
                                            'a movement of the body made in token of respect or submission',
                                            ["makes obeisance to her mentors 向她的导师们致敬"],
                                            other_form = 'obeisant 恭敬的 【反】impertinent, impudent, imperious 不敬的, 无礼的')]),
                              Word('obfuscate', "",
                                   [TestWay('vt',
                                            '使困惑, 使模糊',
                                            'to make so confused or opaque as to be difficult to perceive or understand',
                                            ["obfuscate the reader 让读者困惑"],
                                            'becloud, befog, blur, cloud, fog, muddy',
                                            'demystify, elucidate, illuminate, clarify, explain clearly',
                                            'obfuscated 模糊的 【反】lucid 清晰的')]),
                              Word('obligatory', "",
                                   [TestWay('adj',
                                            '强制性的',
                                            'of the nature of an obligation; compulsory',
                                            ["obligatory military service 强制性的服军役"],
                                            'compulsory, imperative, involuntary, peremptory, required',
                                            'discretionary, selective, elective, optional, voluntary'),
                                    TestWay('adj',
                                            '(见得多以至于)无聊的',
                                            'used or heard so often as to be dull',
                                            ["the obligatory cliff-hanger endings for season finales of TV shows 电视剧总是以恶俗的惊心动魄的结局作为完季"],
                                            'banal, cliché, commonplace, hack, hackneyed, moth-eaten, musty, shopworn, stereotyped, threadbare, timeworn, trite, well-worn',
                                            'fresh, new, novel, original, unclichéd, unhackneyed')])])

list17_unit2 = VocabularyList([Word('obliging', "",
                                   [TestWay('adj',
                                            '乐于助人的',
                                            'willing to do favors',
                                            ["an obliging concierge used his pull to get us reservations at the town's hottest restaurant 一个好心的看房人利用他的影响力帮我们在镇上最火爆的餐厅订到了座"],
                                            'accommodative, friendly, indulgent')]),
                              Word('oblique', "",
                                   [TestWay('adj',
                                            '斜的',
                                            'inclined or twisted to one side',
                                            ["gave the eavesdropper an oblique glance 给了偷听者一个白眼"],
                                            'askew, cant, inclined, leaning, listing, slanted, sloping, tilted',
                                            'direct, even, level, straight')]),
                              Word('obliterate', "",
                                   [TestWay('vt',
                                            '除去',
                                            'to remove from existence',
                                            ["the March snowstorm obliterated our hopes for an early spring 三月的暴风雪摧毁了我们对于一个早春的念想"],
                                            'efface, eradicate, expunge, expurgate, exterminate, extirpate, wipe out')]),
                              Word('oblivious', "",
                                   [TestWay('adj',
                                            '不知道的, 不知情的',
                                            'lacking conscious awareness; not informed about or aware of something',
                                            ["He seemed oblivious to the fact that he had hurt her. 他似乎并不在意他伤害了她"],
                                            'incognizant, insensible, unaware, unconscious, uninformed, unwitting',
                                            'mindful, vigilant, acquainted, cognizant, conscious, conversant, grounded, informed, knowing, mindful,witting')]),
                              Word('obloquy', "",
                                   [TestWay('n',
                                            '谩骂, 诽谤',
                                            'abusively detractive language or utterance; calumny',
                                            ["she unleashed a torrent of obloquy on her opponent 她滔滔不绝地辱骂了对手一顿"],
                                            'billingsgate, fulmination, invective, scurrility, vitriol, vituperation',
                                            'adulation'),
                                    TestWay('n',
                                            '恶名, 耻辱',
                                            'the state of having lost the esteem of others',
                                            ["the accused murderer was condemned to live out his days in perpetual obloquy 凶手终将在骂名中度过余生"],
                                            'discredit, disesteem, dishonor, disrepute, ignominy, infamy, odium, opprobrium, reproach, shame',
                                            'esteem, honor, respect')]),
                              Word('obscure', "",
                                   [TestWay('adj',
                                            '含义模糊的',
                                            'not clearly understood or expressed; having an often intentionally veiled or uncertain meaning',
                                            ["a fantasy writer who likes to put lots of obscure references in her tales of wizards and warlocks 一个喜欢在巫师故事中添加很多含义模糊的引用的魔幻小说作家"],
                                            'ambiguous, arcane, enigmatic, equivocal, fuliginous, inscrutable, opaque',
                                            'explicit, manifest, clear, certain, accessible, nonambiguous, obvious, plain, unambiguous, unequivocal'),
                                    TestWay('adj',
                                            '平凡的, 不知名的',
                                            'not prominent or famous',
                                            ["an obscure poet 无名的诗人"],
                                            'noteless, uncelebrated, unfamous, unknown, unrecognized, unsung',
                                            'legendary, celebrated, famed, famous, noted, notorious, prominent, renowned, well-known',
                                            'obscurity 无名之辈 【反】celebrity 名人'),
                                    TestWay('v',
                                            '使模糊',
                                            'to make dark, dim, or indistinct',
                                            ["when it isn't obscured by smog, the view of the city from the observatory can be spectacular 如果在晴朗的天气, 从天文台看出去的城市全景非常赞"],
                                            'blear, blur, darken, dim, overshadow, shroud',
                                            'elucidate, brighten, illuminate, light up, lighten')]),
                              Word('obsequious', "",
                                   [TestWay('adj',
                                            '谄媚的, 奴性的',
                                            'marked by or exhibiting a fawning attentiveness',
                                            ["She's constantly followed by obsequious assistants who will do anything. 她总是有一群谄媚的跟班, 原意为她赴汤蹈火。"],
                                            'supercilious')]),
                              Word('obsess', "",
                                   [TestWay('vt',
                                            '迷住, 使困扰',
                                            'to haunt or excessively preoccupy the mind of',
                                            ["The war obsesses her—she talks about nothing else. 她被战争彻底迷住了, 张口闭口都谈这个。"],
                                            'intense disgust')]),
                              Word('obstinate', "",
                                   [TestWay('adj',
                                            '固执的',
                                            'perversely adhering to an opinion, purpose, or course in spite of reason, arguments, or persuasion',
                                            ["obstinate resistance to change 坚决抵制改变"],
                                            'adamant, headstrong, intransigent, stubborn, uncompromising, unyielding, willful',
                                            'acquiescent, agreeable, amenable, compliant, complying, flexible, pliable, pliant, relenting, yielding'),
                                    TestWay('adj',
                                            '难于减轻或治愈的',
                                            'not easily subdued, remedied, or removed',
                                            ["obstinate fever 高烧不退", "an obstinate headache 难以治愈的头痛"])]),
                              Word('obstreperous', "",
                                   [TestWay('adj',
                                            '难驾驭的, 任性的',
                                            "stubbornly resistant to control; unruly; given to resisting authority or another's control",
                                            ["the club's president was at his wits' end with obstreperous members who refused to cooperate 俱乐部主席拿那些不合作的会员一点办法都没有"],
                                            'balky, defiant, incompliant, insubordinate, intractable, rebellious, recalcitrant, refractory',
                                            'disciplined, amenable, biddable, compliant, conformable, docile, obedient, ruly, submissive, tractable'),
                                    TestWay('adj',
                                            '吵闹的',
                                            'engaging in or marked by loud and insistent cries especially of protest',
                                            ["an obstreperous crowd protesting the government's immigration policy 一堆吵闹的民众游行抗议政府的移民政策"],
                                            'blatant, clamant, clamorous, squawking, vociferant')])])

list17_unit3 = VocabularyList([Word('obstruct', "",
                                   [TestWay('vt',
                                            '妨碍, 制造困难',
                                            'to impede, retard, or interfere with; hinder; to create difficulty for the work or activity of',
                                            ["He was charged with obstructing justice by lying to investigators. 他被指控向检察官说谎, 妨碍司法。"],
                                            'encumber, fetter, handicap, hinder, impede, inhibit, stymie, interfere with',
                                            'facilitate, abet, aid, assist'),
                                    TestWay('vt',
                                            '阻挡',
                                            'to prevent passage through by filling with something',
                                            ["an unobstructed view 无阻碍的视野"],
                                            'occlude',
                                            'clear, free, open up, unblock, unclog, unplug, unstop')]),
                              Word('obtuse', "",
                                   [TestWay('adj',
                                            '愚钝的',
                                            'not having or showing an ability to absorb ideas readily',
                                            ["Are you being deliberately obtuse? 你是故意装笨吗?"],
                                            'dumb, fatuous, mindless, oafish, opaque, senseless, unintelligent, vacuous',
                                            'insightful, apt, brainy, bright, brilliant, clever, fast, intelligent, keen, nimble, quick, quick-witted, sharp, sharp-witted, smart')]),
                              Word('obviate', "",
                                   [TestWay('vt',
                                            '排除, 使不必要',
                                            'to anticipate and prevent (as a situation) or make unnecessary (as an action)',
                                            ["The new treatment obviates the need for surgery. 新的疗法使手术不再是必须的。"],
                                            'avert, forestall, preclude, stave off, head off')]),
                              Word('occult', "",
                                   [TestWay('adj',
                                            '难以理解的',
                                            'not easily apprehended or understood: abstruse, mysterious',
                                            ["an occult reference in the text that has puzzled scholars 文章中一处晦涩的难倒了学者们的引注"],
                                            'ambiguous, arcane, equivocal, inscrutable, opaque, impenetrable',
                                            'bare, manifest, patent, readily fathomable'),
                                    TestWay('v',
                                            '使隐藏或神秘',
                                            'to keep secret or shut off from view',
                                            ["occulted their house from prying eyes by planting large trees around it 在住所周围种满大树防止别人偷窥", "the actor's private life had long been occulted by a contrived public persona 演员的私人生活被一个精心打造的公众形象所遮掩"],
                                            'belie, blanket, cloak, conceal, cover, curtain, disguise, enshroud, mask, obscure, screen, shroud, suppress, veil, blot out, paper over',
                                            'bare, disclose, display, divulge, expose, reveal, show, uncloak, uncover, unmask, unveil')]),
                              Word('odium', "",
                                   [TestWay('n',
                                            '憎恶, 讨厌',
                                            'strong dislike, contempt, or aversion',
                                            ["time did nothing to diminish the odium in which the traitor lived out his days 时间也没有减少大家对这个叛徒的唾弃"],
                                            'ignominy, infamy, obloquy, opprobrium',
                                            'esteem, honor, respect, hankering, infatuation')]),
                              Word('offbeat', "",
                                   [TestWay('adj',
                                            '不平常的',
                                            'noticeably different from what is generally found or experienced',
                                            ["this writer has an enjoyably offbeat sense of humor 这个作者笑点很奇特"],
                                            'extraordinary, peculiar, queer, unaccustomed, uncommon, uncustomary, out-of-the-way',
                                            'conventional, bathetic, hackneyed, common, ordinary, plain, usual')]),
                              Word('offhand', "",
                                   [TestWay('adj',
                                            '即兴的, 没有准备的',
                                            "without premeditation or preparation",
                                            ["couldn't give the figures offhand"],
                                            'ad-lib, extemporary, impromptu, improvised, unplanned, unpremeditated, unrehearsed',
                                            'considered, planned, premeditated, prepared, rehearsed')]),
                              Word('officious', "",
                                   [TestWay('adj',
                                            '多管闲事的',
                                            'thrusting oneself where one is not welcome or invited',
                                            ["an officious little man who was always telling everyone else how to do their jobs 一个多管闲事的人, 总喜欢对他人的事情指手画脚"],
                                            'interfering, intruding, meddlesome, obtrusive, presuming, prying, snoopy',
                                            'unobtrusive')]),
                              Word('offish', "",
                                   [TestWay('adj',
                                            '冷淡的',
                                            'Inclined to be distant and reserved; aloof',
                                            ["consistently surly and offish with the would-be suitors who came calling 对于追求者总是阴沉并且冷淡"],
                                            'aloof, detached, distant, remote, unbending, unsociable',
                                            'sociable, cordial, friendly, social, warm')]),
                              Word('off-key', "",
                                   [TestWay('adj',
                                            '不寻常的, 不合适的',
                                            'being out of accord with what is considered normal or appropriate',
                                            ["a high-flown, off-key speech by a newcomer 来自于新手的颇有野心、不寻常的一次演讲"])])])

list17_unit4 = VocabularyList([Word('ominous', "",
                                   [TestWay('adj',
                                            '凶兆的',
                                            'of or being an omen, especially an evil one',
                                            ["an ominous threat of war 战争来临的凶兆"],
                                            'baleful, foreboding, inauspicious, portentous, sinister, threatening, minatory',
                                            'auspicious, unthreatening')]),
                              Word('omniscient', "",
                                   [TestWay('adj',
                                            '无所不知的',
                                            'possessed of universal or complete knowledge',
                                            ["an omniscient deity 无所不知的神"],
                                            antonyms = 'vacuous')]),
                              Word('onerous', "",
                                   [TestWay('adj',
                                            '费时间花心思的',
                                            'requiring much time, effort, or careful attention',
                                            ["building the scale model of the frigate was an onerous task 建造军舰的小模型非常花时间"],
                                            'arduous, burdensome, challenging, exacting, grueling, taxing, toilsome',
                                            'requiring little effort, light, nondemanding, unchallenging, undemanding')]),
                              Word('opaque', "",
                                   [TestWay('adj',
                                            '不透光的',
                                            'impenetrable by light; neither transparent nor translucent',
                                            synonyms = 'blurry, dim, misty, murky, obscure, shadowy, unclear',
                                            antonyms = 'diaphanous, transparent'),
                                    TestWay('adj',
                                            '晦涩的',
                                            'so obscure as to be unintelligible',
                                            ["opaque prose 晦涩的诗歌"],
                                            'ambiguous, arcane, enigmatic, equivocal, inscrutable, occult',
                                            'clear, accessible, obvious, plain, unambiguous, unequivocal')]),
                              Word('opine', "",
                                   [TestWay('vt',
                                            '表达观点',
                                            'to express opinions',
                                            ["You can opine about any subject you like. 你可以畅所欲言"],
                                            'comment, editorialize, note, observe, reflect, weigh in')]),
                              Word('opportune', "",
                                   [TestWay('adj',
                                            '合适的, 适当的',
                                            'suitable or convenient for a particular occurrence',
                                            ["an opportune moment 方便的时机"],
                                            'seasonable, well-timed',
                                            'inconvenient, untimely, inappropriate, unseasonable')]),
                              Word('opprobrious', "",
                                   [TestWay('adj',
                                            '辱骂的',
                                            'expressing contemptuous reproach; scornful or abusive',
                                            ["opprobrious language 脏话"],
                                            'scurrilous, vitriolic, vituperative, contumelious'),
                                    TestWay('adj',
                                            '臭名昭著的, 令人鄙视的',
                                            'bringing disgrace; shameful or infamous',
                                            ["opprobrious conduct 令人鄙视的行为"],
                                            'discreditable, disgraceful, dishonorable, ignominious, infamous, notorious, shameful, unrespectable',
                                            'irreproachable, honorable, reputable, respectable',
                                            'opprobrium 恶名 【反】good repute 好名声')]),
                              Word('oration', "",
                                   [TestWay('n',
                                            '(颇有野心、自高自大的)演说',
                                            'a speech delivered in a high-flown or pompous manner',
                                            synonyms = 'address, declamation, harangue, peroration')]),
                              Word('orient', "",
                                   [TestWay('vt',
                                            '确定方向, 使熟悉或适应',
                                            'to set or arrange in any determinate position especially in relation to the points of the compass; to make familiar with or adjusted to facts, principles, or a situation',
                                            ["orient students toward a career in medicine 指导学生从事医学的职业道路"],
                                            'accustom, familiarize, initiate, introduce, orientate',
                                            'confuse')]),
                              Word('original', "",
                                   [TestWay('adj',
                                            '创新的',
                                            'independent and creative in thought or action :inventive',
                                            ["The car has a highly original design. 这车的设计很新颖"],
                                            'ingenious, innovative, inventive',
                                            'commonplace, banal, trite, familiar, hackneyed, time-honored, tired, warmed-over'),
                                    TestWay('adj',
                                            '最初的, 最早的',
                                            'coming before all others in time or order',
                                            ["the original plan had to be discarded when the situation changed drastically 当环境发生剧烈变化时, 最初的计划就该被放弃"],
                                            'earliest, foremost, headmost, inaugural, initial, leadoff, maiden, pioneer, premier, virgin',
                                            'final, last, latter, terminal, ultimate')])])

list17_unit5 = VocabularyList([Word('orthodox', "",
                                   [TestWay('adj',
                                            '传统的',
                                            'following or agreeing with established form, custom, or rules',
                                            ["He believes in the benefits of both orthodox medicine and alternative medicine. 他既相信传统药物又相信替代药物的效用。"],
                                            'ceremonial, conventional, regular, routine',
                                            'casual, freewheeling, informal, irregular, unceremonious, unconventional, unorthodox')]),
                              Word('oscillate', "",
                                   [TestWay('vt',
                                            '振动, 摇晃',
                                            'to swing backward and forward like a pendulum',
                                            antonyms = 'remain static'),
                                    TestWay('v',
                                            '犹豫, 变化',
                                            'vary between opposing beliefs, feelings, or theories')]),
                              Word('ossify', "",
                                   [TestWay('vi',
                                            '硬化, 僵化',
                                            'to become hardened or conventional and opposed to change',
                                            ["a disease that ossifies the joints 一种会使关节僵化的疾病"],
                                            'make pliant, transcend conventions, amenable to change')]),
                              Word('ostentatious', "",
                                   [TestWay('adj',
                                            '炫耀卖弄的',
                                            'marked by or fond of conspicuous or vainglorious and sometimes pretentious display',
                                            ["wears an ostentatious diamond ring on her finger 她手指上戴着一枚巨大的钻戒"],
                                            'flamboyant, flaring, flashy, splashy',
                                            'modest, artless, austere, unpretentious, conservative, quiet, understated, unflamboyant, unflashy')]),
                              Word('ostracize', "",
                                   [TestWay('vt',
                                            '驱逐',
                                            'to exclude from a group',
                                            ["He was ostracized from the scientific community for many years because of his radical political beliefs. 他因激进的政治理想被驱逐出了科学界很多年。"],
                                            'banish, bounce, chase, dismiss, expel, extrude, oust, boot out, cast out, run off, drum out, kick out, throw out, turf out',
                                            'take in, include, embrace, welcome')]),
                              Word('oust', "",
                                   [TestWay('vt',
                                            '免职',
                                            'to remove from a position of prominence or power (as a throne)',
                                            ["be ousted from power 被赶下台"],
                                            'deprive, displace, uncrown, unthrone',
                                            'instate, crown, enthrone, throne'),
                                    TestWay('v',
                                            '驱逐',
                                            'to drive or force out',
                                            ["she was ousted from her job after it was proven she'd been pilfering company supplies 她贪污公司财物这事被证实后, 她被驱逐了"],
                                            'banish, boot out, cast out, chase, dismiss, drum out, expel, extrude, kick out, throw out, turf out, turn out')]),
                              Word('outgoing', "",
                                   [TestWay('adj',
                                            '友好的, 外向的',
                                            'openly friendly and responsive: extroverted',
                                            ["a salesman whose aggressively outgoing personality could sometimes be overbearing 一个销售员如果过于热情会让人不能忍"],
                                            'companionable, extroverted, gregarious, sociable',
                                            'antisocial, introverted, nongregarious, reclusive, unsociable, unsocial')]),
                              Word('outlandish', "",
                                   [TestWay('adj',
                                            '古怪的, 奇异的',
                                            'strikingly out of the ordinary: bizarre',
                                            ["an outlandish costume 奇装异服"],
                                            'bizarre, cranky, eccentric, erratic, offbeat, peculiar, remarkable',
                                            'conventional, familiar, nonexotic, nonglamorous, plain-Jane, unglamorous, unromantic')]),
                              Word('outmaneuver', "",
                                   [TestWay('vt',
                                            '以策略取胜',
                                            'to overcome (an opponent) by artful, clever maneuvering',
                                            ["outmaneuvered his congressional opponent 以计谋战胜了国会的对手"],
                                            'outfox, outslick, outsmart, outthink, outwit',
                                            'yield')]),
                              Word('outset', "",
                                   [TestWay('n',
                                            '开端, 开始',
                                            'beginning, start',
                                            ["I wish you'd mentioned this problem at the outset. 我希望你开门见山就􁨀到这个问题。"],
                                            'alpha, commencement, genesis, inception, incipience, nascence',
                                            'termination, close, conclusion, end, ending, omega')])])

list17_unit6 = VocabularyList([Word('outwit', "",
                                   [TestWay('v',
                                            '瞒骗, 以智取胜',
                                            'to surpass in cleverness or cunning; outsmart',
                                            ["a plan to outwit their opponents at their own game 在擅长的领域智取对手的计划"],
                                            'outfox, outmaneuver, outslick, outsmart, outthink')]),
                              Word('overbearing', "",
                                   [TestWay('adj',
                                            '专横傲慢的',
                                            'domineering in manner; arrogant',
                                            ["Her husband's overbearing manner made her miserable. 她的丈夫专横傲慢, 让她痛不欲生。"],
                                            'authoritative, despotic, dictatorial, imperious, masterful, peremptory',
                                            'meek, unassuming'),
                                    TestWay('adj',
                                            '压倒一切的, 在力量或重要性上势不可挡的; 支配的, 显著的',
                                            'overwhelming in power or significance; predominant, coming before all others in importance',
                                            ["the overbearing problem in our nation's schools 我国中小学教育的最突出的问题"],
                                            'capital, cardinal, central, chief, dominant, key, leading, master, number one, overmastering, overriding, paramount, predominant, preeminent, premier, primary, prior, sovereign, supreme')]),
                              Word('overlap', "",
                                   [TestWay('vt',
                                            '重叠, 重复',
                                            'to occupy the same area in part',
                                            ["Baseball season overlaps football season in September. 棒球赛季和橄榄球赛季在九月有时间重合。"],
                                            'lap, overlay, overlie, overspread')]),
                              Word('overt', "",
                                   [TestWay('adj',
                                            '明显的, 公开的',
                                            'open and observable; not hidden, concealed, or secret',
                                            ["overt hostility 公然的敌意"],
                                            antonyms = 'shadowy')]),
                              Word('overture', "",
                                   [TestWay('n',
                                            '前言',
                                            'an introductory section or part, as of a poem; a prelude',
                                            synonyms = 'preamble, preliminary, prologue, warm-up, curtain-raiser'),
                                    TestWay('n',
                                            '序曲',
                                            'an instrumental composition intended especially as an introduction to an extended work, such as an opera or oratorio',
                                            ["the parade down Main Street served as the overture for a weekend of fun and festivities 主干道上的游行活动拉开了一周节日活动的序幕"],
                                            antonyms = 'coda')]),
                              Word('oxymoron', "",
                                   [TestWay('n',
                                            '矛盾修饰法',
                                            'a combination of contradictory or incongruous words',
                                            ["The phrase “cruel kindness” is an oxymoron. “残酷的仁慈”就是矛盾修饰法的一个例子。", "The phrase “Broadway rock musical” is an oxymoron. Broadway doesn't have the nerve to let the really hard stuff in the house. “百老汇的摇滚音乐剧”是个反讽。百老汇才不会允许吵吵闹闹的东西在里面演出。"])]),
                              Word('pacify', "",
                                   [TestWay('vt',
                                            '使平静, 安慰',
                                            'to ease the anger or agitation of',
                                            ["pacify a crying child 安抚一个哭泣的孩子"],
                                            'appease, assuage, conciliate, mollify, placate, propitiate',
                                            'incite, rankle, tantrum, vex, discompose, truculent')]),
                              Word('padding', "",
                                   [TestWay('n',
                                            '夸张, 废话',
                                            'the representation of something in terms that go beyond the facts',
                                            ["that feature writer is sometimes guilty of padding, but he keeps it from getting out of hand 这作者有时候夸夸其谈, 但是保持了适度"],
                                            'caricature, coloring, elaboration, embellishment, embroidery, hyperbole, magnification, overstatement, stretching',
                                            'meiosis, understatement')]),
                              Word('paean', "",
                                   [TestWay('n',
                                            '欢乐颂',
                                            'a joyous song or hymn of praise, tribute, thanksgiving, or triumph',
                                            ["her retirement party featured many paeans for her long years of service to the company 她的退休派对满是对她多年在公司辛勤工作的赞颂"],
                                            'accolade, citation, dithyramb, eulogium, eulogy, hymn, panegyric, tribute')]),
                              Word('painstaking', "",
                                   [TestWay('adj',
                                            '煞费苦心的',
                                            'taking pains: expending, showing, or involving diligent care and effort',
                                            ["It took months of painstaking research to write the book. 这本书的写作耗费了几个月的苦心研究。"],
                                            'careful, conscientious, fussy, meticulous, scrupulous',
                                            'slipshod, cursory, careless')])])

list17_unit7 = VocabularyList([Word('palatable', "",
                                   [TestWay('adj',
                                            '感到愉悦满足的',
                                            'giving pleasure or contentment to the mind or senses',
                                            ["I always associate the palatable aroma of roasting turkey with Thanksgiving. 我总是把香喷喷的烤火鸡的味道和感恩节联系起来"],
                                            'agreeable, blessed, congenial, delectable, delightful, delightsome, dreamy, dulcet, enjoyable, felicitous, grateful, gratifying, heavenly, jolly, luscious, pleasurable, satisfying, savory',
                                            'disagreeable, pleasureless, unpalatable, unpleasant, unwelcome')]),
                              Word('palatial', "",
                                   [TestWay('adj',
                                            '宫殿般奢华的',
                                            'of the nature of a palace, as in spaciousness or ornateness',
                                            ["a palatial penthouse apartment 一套豪华的顶层公寓"],
                                            'deluxe, lavish, luxuriant, opulent, sumptuous',
                                            'ascetic, austere, humble, no-frills, spartan')]),
                              Word('pall', "",
                                   [TestWay('vi',
                                            '失去兴趣',
                                            'to lose in interest or attraction',
                                            ["His humor began to pall on us. 他的幽默开始使我们生腻了。"],
                                            antonyms = 'interest, intrigue')]),
                              Word('palliate', "",
                                   [TestWay('v',
                                            '平息, 减轻',
                                            'to make less severe or intense; mitigate',
                                            ["palliative drug 缓解剂"],
                                            'allay, alleviate, assuage, mitigate, mollify, palliate, relieve, soothe',
                                            'aggravate, exacerbate, worsen, increase intensity')]),
                              Word('pallid', "",
                                   [TestWay('adj',
                                            '无生气的, 缺乏活力的',
                                            'lacking in radiance or vitality; dull',
                                            [" The movie is a pallid version of the classic novel. 这部经典小说改编的电影很苍白无力。"],
                                            antonyms = 'piquant'),
                                    TestWay('adj',
                                            '苍白无血色的',
                                            'having an abnormally pale or wan complexion',
                                            ["a pallid girl who looked as though she'd never seen the sun 一个面色苍白的姑娘, 仿佛从来没有晒过太阳"],
                                            'ashen, ashy, blanched, pasty, wan',
                                            'rubicund, blooming, florid, flush, full-blooded, glowing, ruddy, sanguine')]),
                              Word('palmy', "",
                                   [TestWay('adj',
                                            '繁荣的',
                                            'marked by prosperity',
                                            ["the palmy days of the British drama 英国戏剧的繁荣时期"],
                                            'flourishing, prosperous, thriving, booming, lush, roaring, halcyon',
                                            'failed, depressed, unprosperous, unsuccessful')]),
                              Word('palpable', "",
                                   [TestWay('adj',
                                            '摸得到的',
                                            'capable of being touched or felt',
                                            ["a small but palpable lump in my neck我脖子上有一块小但是能摸得到的肿块"],
                                            'touchable',
                                            'impalpable, intangible'),
                                    TestWay('adj',
                                            '明显的, 易觉察的',
                                            'easily perceived; obvious',
                                            ["a palpable difference 易觉察的差别"],
                                            'apprehensible, detectable, discernible, distinguishable, sensible',
                                            'imperceptible, inappreciable, indistinguishable, insensible, undetectable')]),
                              Word('palter', "",
                                   [TestWay('vi',
                                            '欺骗',
                                            'to act insincerely or deceitfully',
                                            ["unwilling to palter over the price of the house 拒绝对房子漫天要价"],
                                            'chaffer, deal, dicker, haggle, horse-trade, negotiate, equivocate',
                                            'candor')]),
                              Word('paltry', "",
                                   [TestWay('adj',
                                            '无价值的;微不足道的',
                                            'lacking in importance or worth',
                                            ["used a paltry, underhanded scheme to get him fired 用一个微小卑鄙的手段炒了他鱿鱼"],
                                            'inconsequential, inconsiderable, insignificant, niggling, piddling, piffling, trivial',
                                            'significant, important, big, consequential, considerable, material'),
                                    TestWay('adj',
                                            '让人厌恶, 让人鄙视的',
                                            "arousing or deserving of one's loathing and disgust",
                                            ["a paltry, underhanded scheme to get someone fired 一个卑鄙的炒掉 人的计谋"],
                                            'cheap, cruddy, deplorable, despicable, grubby, lame, lousy, mean, scummy, scurvy, sneaking, wretched',
                                            'admirable, commendable, creditable, laudable, meritorious, praiseworthy')]),
                              Word('pan', "",
                                   [TestWay('v./n',
                                            '严厉批评',
                                            'a harsh criticism',
                                            ["almost all the movie critics have panned this latest sequel in a tired series 几乎所有的影评家都批评这部最新续集, 认为是狗尾续貂"],
                                            'blame, censure, condemn, denounce, dispraise, reprehend',
                                            'eulogize, extol, rave, laud, praise')])])

list17_unit8 = VocabularyList([Word('panache', "",
                                   [TestWay('n',
                                            '炫耀',
                                            'dash or flamboyance in style and action',
                                            ["The BBC Symphony Orchestra played with great panache. BBC 交响乐队"],
                                            antonyms = 'humility, unremarkable behavior, dullness')]),
                              Word('pandemic', "",
                                   [TestWay('adj',
                                            '大范围流行的',
                                            'widespread; general',
                                            ["pandemic malaria 大规模的疟疾"],
                                            antonyms = 'limited')]),
                              Word('pandemonium', "",
                                   [TestWay('n',
                                            '喧嚣, 骚动',
                                            'wild uproar or noise',
                                            ["Christmas morning at our house is always marked by pandemonium 圣诞节的早上总是免不了一番吵吵闹闹"],
                                            'bluster, bustle, disturbance, furor, fuss, hubbub, moil, pother, ruckus, ruction, tumult, turmoil, uproar',
                                            'serene')]),
                              Word('panegyric', "",
                                   [TestWay('n',
                                            '赞颂之词',
                                            'a eulogistic oration or writing',
                                            ["wrote a panegyric on the centennial of the Nobel laureate's birth 为诺贝尔获得者百年诞辰纪念日写了一篇溢美之词"],
                                            'accolade, citation, commendation, dithyramb, eulogium, eulogy, hymn, paean',
                                            'anathema, denunciation, condemnation')]),
                              Word('panoramic', "",
                                   [TestWay('adj',
                                            '全景的',
                                            'of an unobstructed or complete view of an area in every directiona panorama of American history 美国历史总览',
                                            ["a panorama of American history 美国历史总览"],
                                            'compendious, complete, comprehensive, cyclopedic, embracive, exhaustive, thorough, in-depth',
                                            'narrow')]),
                              Word('parable', "",
                                   [TestWay('n',
                                            '寓言',
                                            'a story intended to teach a basic truth or moral about life',
                                            ["the parable in which the repentant sinner is compared to the returning prodigal son 这个寓言故事将不愿悔过的罪人和回头的浪子进行了比较"],
                                            'apologue, fable')]),
                              Word('paradigm', "",
                                   [TestWay('n',
                                            '典范, 模范',
                                            'one that serves as a pattern or model',
                                            ["He was the paradigm of the successful man. 他是成功人士的典范"],
                                            'archetype, example, exemplar, ideal, model, pattern, paragon')]),
                              Word('paradise', "",
                                   [TestWay('n',
                                            '天堂, 极乐世界',
                                            'an often imaginary place or state of utter perfection and happiness',
                                            ["an idealist who trotted the globe looking for paradise 一个奔波于全世界以寻找一片乐土的理想主义者"],
                                            'bliss, empyrean, heaven, nirvana, utopia',
                                            'hell, inferno'),
                                    TestWay('n',
                                            '快乐, 狂喜',
                                            'a state of overwhelming usually pleasurable emotion',
                                            ["that early stage of a romance when lovers are in paradise 爱情初期, 当恋人们都处于快乐兴奋的状态时"],
                                            'elation, euphoria, exhilaration, intoxication, rapture, rhapsody, transport',
                                            'dejection, depression, gloominess, melancholy')]),
                              Word('paradox', "",
                                   [TestWay('n',
                                            '表面矛盾实际可能正确的话, 悖论',
                                            'a statement that is seemingly contradictory or opposed to common sense and yet is perhaps true',
                                            ["The paradox is that fishermen would catch more fish if they fished less. 存在的一个悖论就是:如果渔民减少捕鱼量的话, 他们将会捕到更多的鱼"],
                                            'dichotomy, incongruity')]),
                              Word('paragon', "",
                                   [TestWay('n',
                                            '优秀模范',
                                            'a model of excellence or perfection of a kind; a peerless example',
                                            ["a paragon of good husband 模范好丈夫"],
                                            'archetype, example, exemplar, ideal, model, pattern, paradigm'),
                                    TestWay('vt',
                                            '把...比作; 显示相似',
                                            'to compare with; parallel',
                                            ["paragon retreat with treachery 把撤退比作是背叛"],
                                            'assimilate, compare, equate, liken, match, parallel',
                                            'contrast')])])

list17_unit9 = VocabularyList([Word('paramount', "",
                                   [TestWay('adj',
                                            '最重要的',
                                            'to evade especially by an adroit answer',
                                            ["He parried the embarrassing question with a clever reply. 他以巧妙的回答躲避了这个令人尴尬的问题"],
                                            'avoid, dodge, elude, eschew, evade, finesse, scape, shirk, shun',
                                            'confront, face, meet, embrace')]),
                              Word('paranoid', "",
                                   [TestWay('adj',
                                            '多疑的, 对他人极端恐惧和怀疑的',
                                            'exhibiting or characterized by extreme and irrational fear or distrust of others',
                                            ["a paranoid suspicion that the phone might be bugged 疑神疑鬼地担心电话被窃听了"],
                                            'distrustful, nervous, suspicious, unbelieving, worried',
                                            'credulous',
                                            'paranoia n. 偏执狂')]),
                              Word('paraphrase', "",
                                   [TestWay('v',
                                            '转述, 意译, 改写',
                                            'to express something (as a text or statement) in different words',
                                            ["Could you please paraphrase your diagnosis of my health condition, using simpler language? 您能否用更通俗的话语转述一下您对我健康状况的诊断呢"],
                                            'rephrase, restate, reword, translate',
                                            'quote')]),
                              Word('parch', "",
                                   [TestWay('vi',
                                            '烤干',
                                            'to make extremely dry, especially by exposure to heat',
                                            ["parch a surface from exposure to sun 通过太阳照射烤干一个面"],
                                            'dehydrate, desiccate, dry, scorch, sear',
                                            'douse, drench, hydrate, steep, wash, water, wet')]),
                              Word('parenthesis', "",
                                   [TestWay('n',
                                            '间断',
                                            'an interruption of continuity; an interval',
                                            ["a parenthesis in another wise solid marriage 在本该是完满婚姻中的一个插曲"],
                                            'discontinuity, interim, interlude, intermission, interregnum, interruption, interstice, interval',
                                            'continuation, continuity, resumption继续')]),
                              Word('pariah', "",
                                   [TestWay('n',
                                            '被排斥或鄙视的人',
                                            'one that is despised or rejected, outcast',
                                            ["I felt like a pariah when I wore the wrong outfit to the dinner party. 当我穿着不恰当的礼服赴宴时, 我感觉自己被别人狠狠地鄙视了"],
                                            'castaway, castoff, leper, reject',
                                            'respectable person')]),
                              Word('parity', "",
                                   [TestWay('n',
                                            '相称, 同等, 平等',
                                            'the quality or state of being equal or equivalent',
                                            ["to achieve parity with our commercial competitors 取得与我们的商业竞争对手同等的地位"],
                                            'coequality, coordinateness, equality, equivalency, par, sameness',
                                            'disparity, imparity, inequality, incommensurateness')]),
                              Word('parody', "",
                                   [TestWay('n',
                                            '(以嘲笑原作作者的)模仿作品',
                                            'a literary or musical work in which the style of an author or work is closely imitated for comic effect or in ridicule',
                                            ["The Back Dormitory Boys specialize in parody of Backstreet Boys. 后舍男生擅长恶搞后街男孩。"],
                                            'burlesque, caricature, spoof, travesty'),
                                    TestWay('v',
                                            '模仿(以嘲弄)',
                                            'to copy or exaggerate (someone or something) in order to make fun of',
                                            ["parodying a public figure's mannerisms 模仿嘲弄一个公共人物的举止"],
                                            'imitate, mock, mimic')]),
                              Word('paroxysm', "",
                                   [TestWay('n',
                                            '(感情、动作的)突发',
                                            'a sudden outburst of emotion or action',
                                            ["a paroxysm of coughing 突然一阵咳嗽"],
                                            'burst, ebullition, eruption, explosion, flare, flash, flush, gush, outburst, storm'),
                                    TestWay('n',
                                            '(政治、社会领域的)大动荡',
                                            'a violent disturbance (as of the political or social order)',
                                            ["Darwin's introduction of the theory of evolution created paroxysms in both religion and science that are still being felt today. 达尔文提出的进化论给宗教界和科学界都带来了巨大的冲击, 时至今日我们仍然可以感觉到"],
                                            'bouleversement, cataclysm, earthquake, hurricane, storm, tempest, tumult, upheaval, uproar')]),
                              Word('parrot', "",
                                   [TestWay('vt',
                                            '(机械地)模仿, 复制',
                                            'to repeat or imitate, especially without understanding',
                                            ["parrot others blindly 盲目地人云亦云"],
                                            'copy, ditto, duplicate, echo, quote',
                                            'coin, create, devise, invent')])])

list17_unit10 = VocabularyList([Word('parry', "",
                                   [TestWay('vt',
                                            '躲避(问题)',
                                            'to evade especially by an adroit answer',
                                            ["He parried the embarrassing question with a clever reply. 他以巧妙的回答躲避了这个令人尴尬的问题"],
                                            'avoid, dodge, elude, eschew, evade, finesse, scape, shirk, shun',
                                            'confront, face, meet, embrace')]),
                              Word('parsimonious', "",
                                   [TestWay('adj',
                                            '过度节俭的, 吝啬的',
                                            'frugal to the point of stinginess',
                                            ["the stereotype of the dour and parsimonious Scotsman 严肃而吝啬的苏格兰人的典型代表"],
                                            'closefisted, mean, mingy, miserly, niggardly, penurious, stinting, tight, tightfisted, uncharitable, ungenerous',
                                            'generous, liberal, munificent, dissolute, extravagant, prodigal, wasteful')]),
                              Word('partial', "",
                                   [TestWay('adj',
                                            '偏袒的, 偏爱的',
                                            'inclined to favor one party more than the other: biased',
                                            ["He is partial to Maverick. 他偏爱小牛队"],
                                            'biased, one-sided, partisan, prejudiced',
                                            'disinterested,equitable,evenhanded,fair,impartial,neutral,objective,unbiased,unprejudiced'),
                                    TestWay('adj',
                                            '部分的, 不完整的',
                                            'lacking some necessary part',
                                            ["a partial answer to the problem 一部分的解答"],
                                            'deficient, fragmental, fragmentary, half, halfway',
                                            'complete, entire, full, intact, integral, perfect, whole',
                                            'partially adv. 部分地; partiality n. 偏袒, 偏爱')]),
                              Word('particularize', "",
                                   [TestWay('vt',
                                            '详述',
                                            'to go into or give details or particulars',
                                            ["particularize the rules you must observe 详述了你需要遵守的规定"],
                                            'detail, specificate, specify',
                                            'abbreviate, abridge, condense, shorten')]),
                              Word('partisan', "",
                                   [TestWay('n',
                                            '跟随者, 信徒',
                                            'one who follows the opinions or teachings of another',
                                            ["Partisans of the charismatic leader refuse to tolerate any criticism of him at all. 跟随者们不允许任何有关他们富有魅力的领导的负面言论"],
                                            'acolyte, adherent, disciple, pupil, votary',
                                            'bellwether, leader'),
                                    TestWay('n',
                                            '(狂热、坚定的)拥护者, 支持者',
                                            'one who is intensely or excessively devoted to a cause',
                                            ["a partisan of the revolution who was even willing to give her life for it 一个愿意为了革命献出自己生命的坚定拥护者"],
                                            'crusader, fanatic, ideologue, zealot, true believer',
                                            'adversary, antagonist, opponent '),
                                    TestWay('adj',
                                            '偏袒的',
                                            'inclined to favor one side over another',
                                            ["a shamelessly partisan news report 一篇无耻的、有倾向性的新闻报道"],
                                            'biased, one-sided, partial, prejudiced',
                                            'disinterested,equitable,evenhanded,fair,impartial,neutral,objective,unbiased,unprejudiced')]),
                              Word('pastiche', "",
                                   [TestWay('n',
                                            '(带嘲讽的)模仿',
                                            'a literary, artistic, musical, or architectural work that imitates the style of previous work, often with satirical intent',
                                            ["a pastiche of Botticelli's Birth of Venus 波提且利画作《维纳斯的诞生》的仿品"],
                                            'burlesque, caricature, imitation, parody, spoof, travesty',
                                            'original work'),
                                    TestWay('n',
                                            '大杂烩',
                                            'a pasticcio of incongruous parts; a hodgepodge',
                                            ["a pastiche of dishes from many countries 来自众多国家的饮食杂烩"],
                                            'agglomerate, collage, hodgepodge, jumble, jungle, medley, montage, motley, salad, variety, welter')]),
                              Word('partition', "",
                                   [TestWay('n',
                                            '分割, 划分',
                                            'the act or process of dividing something into parts',
                                            ["the partition of Czechoslovakia into the Czech Republic and Slovakia 捷克斯洛伐克被分裂成捷克共和国和斯洛伐克"],
                                            'bifurcation, breakup, cleavage, disunion, division, fractionalization, schism, scission, split, sundering',
                                            'unification, union')]),
                              Word('patent', "",
                                   [TestWay('adj',
                                            '显而易见的, 明显的',
                                            'readily visible or intelligible: obvious',
                                            ["Unfortunately, the patent flaw of the proposal did not deter the city council from putting it up for a vote. 不幸的是, 尽管提案中有着显而易见的缺陷, 市议会依然将它拿出来进行投票"],
                                            'apparent, blatant, conspicuous, evident, flagrant, manifest, obvious, plain',
                                            'concealed, hidden, invisible')]),
                              Word('pathological', "",
                                   [TestWay('adj',
                                            '不正常的, 病态的',
                                            'being such to a degree that is extreme, excessive, or markedly abnormal',
                                            ["She has a pathological fear of snakes. 她对蛇有一种病态的恐惧"],
                                            'abnormal, aberrant, anomalous, morbid',
                                            'normal, natural')]),
                              Word('patina', "",
                                   [TestWay('n',
                                            '外表',
                                            'a superficial covering or exterior',
                                            ["a superficial patina of knowledge 表面肤浅的知识"],
                                            'façade, hull, skin, veneer',
                                            'essential quality, core, kernel'),
                                    TestWay('n',
                                            '(由内而外散发的)氛围, 气场',
                                            'an appearance or aura that is derived from association, habit, or established character',
                                            ["Although the winery is brand-new, it has been constructed and decorated to give it a patina of old-world quaintness. 尽管酿酒厂是全新建造的, 但它的构造和装饰都刻意营造出一种古色古香的奇异氛围"],
                                            antonyms = 'air, ambience, aroma, atmosphere, climate, flavor, halo, odor, smell, temper, vibration')])])

LIST17 = VocabularyList(list17_unit1.words+list17_unit2.words+list17_unit3.words+list17_unit4.words+list17_unit5.words+list17_unit6.words+list17_unit7.words+list17_unit8.words+list17_unit9.words+list17_unit10.words)
