#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list20_unit1 = VocabularyList([Word('prowess', "",
                                   [TestWay('n',
                                            '英勇, 勇敢',
                                            'superior strength, courage, or daring, especially in battle',
                                            ["his prowess on the football field 他在球场上过人的勇气"],
                                            'bravery, courageousness, daring, gallantry, guts, intrepidity',
                                            'timid, cowardice, cravenness, dastardliness, poltroonery, spinelessness')]),
                              Word('prowl', "",
                                   [TestWay('vt',
                                            '潜行, 巡游以猎取猎物',
                                            'to roam through stealthily, as in search of prey or plunder',
                                            ["I prowled the shop looking for sales. 我在商店里转悠, 寻找打折商品。"])]),
                              Word('prude', "",
                                   [TestWay('n',
                                            '过分正经的人: 一个过分关心自己是否是或显得得体、谦逊或正确的人',
                                            'a person who is greatly concerned with seemly behavior and morality especially regarding sexual matters',
                                            ["the racy sitcom frequently satirizes exactly the sort of prude who would like to see the show taken off the air"],
                                            'bluenose, moralist, puritan',
                                            'immoralist')]),
                              Word('prudish', "",
                                   [TestWay('adj',
                                            '过分守礼的',
                                            'marked by prudery',
                                            ["By the prudish standards of the 19th century, any depiction of the nude was scandalous. 根据19世纪的保守标准, 任何对裸露的刻画描述都是下流无耻的。"],
                                            'nice-nelly, prim, puritanical')]),
                              Word('prudent', "",
                                   [TestWay('adj',
                                            '明智的',
                                            'marked by wisdom or judiciousness; wise',
                                            ["prudent advice 明智的建议"],
                                            'advisable, desirable, judicious, politic, tactical, intelligent',
                                            'fool'),
                                    TestWay('adj',
                                            '小心谨慎的, 审慎的',
                                            'marked by circumspection')]),
                              Word('prune', "",
                                   [TestWay('n',
                                            '梅干',
                                            'a plum dried or capable of drying without fermentation'),
                                    TestWay('vt',
                                            '修剪',
                                            'to cut off or remove dead or living parts or branches of (a plant, for example) to improve shape or growth',
                                            ["The students were asked to prune their essays. 学生们被要求修改文章。"],
                                            'shave, shear, snip, trim')]),
                              Word('pry', "",
                                   [TestWay('v',
                                            '刺探',
                                            'to look or inquire closely, curiously, or impertinently',
                                            ["don't go prying into other people's business 别去打探别人的事"],
                                            'interlope, intermeddle, intrude, nose, obtrude, snoop')]),
                              Word('pseudonym', "",
                                   [TestWay('n',
                                            '假名, 笔名',
                                            'a fictitious name',
                                            ["Mark Twain is the pseudonym of the American writer Samuel L. Clemens. 马克· 吐温是美国作家塞缪尔·L·克莱蒙斯的笔名。"],
                                            'alias, nom de guerre')]),
                              Word('psychology', "",
                                   [TestWay('n',
                                            '心理学',
                                            'the science that deals with mental processes and behavior',
                                            ["She studied psychology in college. 她大学专业是心理学。"]),
                                    TestWay('n',
                                            '心理战术',
                                            'subtle tactical action or argument used to manipulate or influence another',
                                            ["He used poor psychology on his employer when trying to make the point. 他表达观点时, 对老板用了拙劣的心理战术。"])]),
                              Word('pucker', "",
                                   [TestWay('vi',
                                            '撅(嘴), 使收缩',
                                            'to become gathered, contracted, and wrinkled',
                                            ["pucker my lips 撅起嘴"])])])

list20_unit2 = VocabularyList([Word('puckish', "",
                                   [TestWay('adj',
                                            '淘气的, 顽皮的',
                                            'mischievous; impish',
                                            ["She had a puckish smile on her face. 她脸上挂着顽皮的笑容。"],
                                            'devilish, impish, prankish, rascally, waggish',
                                            'sober, grave, staid')]),
                              Word('puerile', "",
                                   [TestWay('adj',
                                            '幼稚的, 不成熟的',
                                            'immature; lacking in adult experience or maturity',
                                            ["puerile remarks 幼稚的评论"],
                                            'adolescent, green, immature, puerile, unfledged, unformed, unripened',
                                            'adult, experienced, grown-up, mature, ripe, sagacious')]),
                              Word('puissance', "",
                                   [TestWay('n',
                                            '权力',
                                            'power; might',
                                            ["the president pledged to put the full puissance of the nation into the war effort 总统下令全国进入战争状态"],
                                            'force, might, potency, strength, vigor, sinew',
                                            'powerlessness, impotence, weakness')]),
                              Word('pulchritude', "",
                                   [TestWay('n',
                                            '美丽',
                                            'great physical beauty and appeal',
                                            antonyms = 'ugliness, homeliness, hideousness')]),
                              Word('pulverize', "",
                                   [TestWay('vt',
                                            '研磨成粉',
                                            'to bring to a complete end the physical soundness, existence, or usefulness of',
                                            ["Bits of pulverized rock filled the air. 被碾碎的岩石碎片充斥在空气里。"],
                                            antonyms = 'solidify, build, construct, erect, put up, raise, rear, set up')]),
                              Word('pun', "",
                                   [TestWay('n',
                                            '双关语',
                                            'the usually humorous use of a word in such a way as to suggest two or more of its meanings or the meaning of another word similar in sound',
                                            ["He's a skillful pilot whose career has—no pun intended—really taken off. 她是个技术娴熟的飞行员, 飞行生涯——没有别的意思——真正腾飞了。"])]),
                              Word('punctilious', "",
                                   [TestWay('adj',
                                            '注意细节的, 一丝不苟的',
                                            'strictly attentive to minute details of form in action or conduct.',
                                            synonyms = 'decorous, proper, starchy, stilted',
                                            antonyms = 'remiss, slipshod, casual, easygoing, informal, laid-back, unceremonious')]),
                              Word('pundit', "",
                                   [TestWay('n',
                                            '权威人士, 专家',
                                            'a person who gives opinions in an authoritative manner usually through the mass media',
                                            ["the new laptop has gotten a thumbs-up from industry pundits 新出的笔记本电脑受到了业界专家的一致好评"],
                                            'savant, scholar')]),
                              Word('pungent', "",
                                   [TestWay('adj',
                                            '辛辣的, 讽刺的',
                                            'marked by the use of wit that is intended to cause hurt feelings',
                                            ["pungent language 辛辣讽刺的语言"],
                                            'acerbic, acid, acrid, caustic, mordant, sardonic, scalding, scathing')]),
                              Word('puny', "",
                                   [TestWay('adj',
                                            '微小的, 弱小的',
                                            'of inferior size, strength, or significance; weak',
                                            ["I wouldn't mess with him—he makes bodybuilders look puny in comparison. 我不敢招惹他——其他健身的人和他比起来都像小孩。"],
                                            'diminutive, dwarfish, slight, subnormal',
                                            'enormous, considerable, grand, husky, king-size, outsize, overscale, substantial, whacking, whopping')])])

list20_unit3 = VocabularyList([Word('purity', "",
                                   [TestWay('n',
                                            '纯净; 清白, 无罪',
                                            'the quality or state of being morally pure; the quality or state of being morally pure',
                                            ["struggling to live a life of purity while surrounded by wickedness即使周围充满邪恶, 也要使自己生命纯粹、完美"],
                                            'chasteness, immaculacy, innocence, modesty',
                                            'impurity, unchasteness, unchastity',
                                            'impurity n. 杂质; purist n. 纯粹主义者')]),
                              Word('purlieu', "",
                                   [TestWay('n',
                                            '常去的地方',
                                            'a place for spending time or for socializing',
                                            ["The restaurant, the preferred purlieu of the theatergoing crowd, is always packed an hour or two before showtime. 观剧的人群经常去的那间餐厅, 总是在演出开始前1-2小时爆满"],
                                            'haunt, purlieu, rendezvous, resort, stamping ground, stomping ground'),
                                    TestWay('n',
                                            '临近的地区',
                                            'an adjoining region or space',
                                            ["We stopped at one of the several pubs in the purlieus of the stadium. 我们在体育馆附近的一间酒吧停下来。"],
                                            'backyard, neighborhood, purlieus, vicinage, vicinity')]),
                              Word('purloin', "",
                                   [TestWay('vt',
                                            '偷窃',
                                            'to steal, often in a violation of trust',
                                            ["fearing that someone might attempt to purloin a copy of the script for the show's season finale 害怕该剧的完季那集剧本被盗"],
                                            'appropriate, filch, pilfer, snitch, thieve')]),
                              Word('purvey', "",
                                   [TestWay('v',
                                            '(大量)供给, 供应',
                                            'to supply (food, for example); furnish',
                                            ["a little shop purveying handmade merchandise 出售手工商品的小店"])]),
                              Word('pusillanimous', "",
                                   [TestWay('adj',
                                            '懦弱的, 胆小得令人鄙视的',
                                            'lacking courage and resolution : marked by contemptible timidity',
                                            ["pusillanimous politicians who vote according to whichever way the political wind is blowing 胆小懦弱的政客, 舆论风向倒向谁就投票给谁"],
                                            'craven, dastardly, gutless, poltroon, recreant, spineless',
                                            'brave, courageous, daring, dauntless, doughty, gallant, gutsy, intrepid, lionhearted, stalwart, stout, stouthearted, valiant, valorous')]),
                              Word('quack', "",
                                   [TestWay('n',
                                            '骗子医生, 江湖郎中',
                                            'a pretender to medical skill',
                                            ["don't bother to see that guy, as I've heard he's a quack with no actual training 别再找他看病了, 我听说他就是个没有真才实学的江湖郎中"],
                                            'charlatan, fake, fraud, hoaxer, mountebank, phony',
                                            'honest practitioner')]),
                              Word('quaff', "",
                                   [TestWay('vt',
                                            '大口地喝',
                                            'to drink (a beverage) heartily',
                                            ["He stopped at a bar and quaffed a few beers. 他在酒吧停下来, 痛饮了几杯啤酒。"],
                                            'draft, gulp, swig, swill')]),
                              Word('quail', "",
                                   [TestWay('vi',
                                            '胆怯, 畏缩',
                                            'to shrink back in fear; cower',
                                            ["She quailed at the thought of seeing him again. 她想到还要再见他就害怕。"],
                                            'blench, cringe, recoil, shrink, wince',
                                            'become resolute, give bold')]),
                              Word('qualify', "",
                                   [TestWay('vt',
                                            '限定',
                                            'to reduce from a general to a particular or restricted form',
                                            ["qualified support 有限的支持"],
                                            'qualified',
                                            'unreserved, absolute, categorical'),
                                    TestWay('v',
                                            '使有资格, 有能力',
                                            'to make competent (as by training, skill, or ability) for a particular office or function',
                                            ["raising five children has qualified her to be an advice columnist on parenting 抚养五个孩子的经历让她成为了育儿板块的专栏作家"],
                                            'equip, fit, prepare, ready, season, train')]),
                              Word('quandary', "",
                                   [TestWay('n',
                                            '困惑, 窘境',
                                            'a state of perplexity or doubt',
                                            ["I've had two job offers, and I'm in a real quandary about/over which one to accept. 我有两个工作机会,但实在是进退两难, 不知道应该选哪一个."],
                                            'catch-22, double bind',
                                            'state of complete certainty')])])

list20_unit4 = VocabularyList([Word('quarantine', "",
                                   [TestWay('n',
                                            '隔离',
                                            'to isolate from normal relations or communication',
                                            ["The cows will be kept in quarantine for another two weeks. 牛群还需要被隔离观察两周。"])]),
                              Word('quarry', "",
                                   [TestWay('n',
                                            '采石场',
                                            'an open excavation or pit from which stone is obtained by digging, cutting, or blasting'),
                                    TestWay('n',
                                            '目标, 猎物',
                                            'an object of pursuit',
                                            ["a hunter relentlessly tracking his quarry 无情捕杀猎物的猎人"],
                                            'chase',
                                            'predator')]),
                              Word('quash', "",
                                   [TestWay('vt',
                                            '镇压, 阻止',
                                            'to put a stop to (something) by the use of force',
                                            ["quash a rebellion 镇压一次叛变"],
                                            'repress, squelch, subdue, suppress, clamp down on, crack down on',
                                            'engender, foment')]),
                              Word('quaver', "",
                                   [TestWay('vt',
                                            '发颤音',
                                            'to speak in a quivering voice; utter a quivering sound',
                                            ["His voice quavered during the speech. 整个演讲过程中, 他的声音都是颤抖的。"],
                                            'temble, trill')]),
                              Word('quell', "",
                                   [TestWay('vt',
                                            '压制',
                                            'to put down forcibly; suppress',
                                            ["quell riot 镇压骚乱"],
                                            'quash, repress, squash, squelch, subdue, suppress, clamp down on, crack down on'),
                                    TestWay('vt',
                                            '使平静, 安静',
                                            '使平静, 安静',
                                            ["quell fears 减轻害怕"],
                                            'dumb, extinguish, hush, mute, settle',
                                            'foment, instigate, rouse, incite')]),
                              Word('quench', "",
                                   [TestWay('vt',
                                            '熄灭',
                                            'to put out (a fire, for example); extinguish',
                                            ["We thoroughly quenched the campfire before we headed to bed. 我们在睡前把营火完全熄灭了。"],
                                            'blanket, douse, put out, snuff out',
                                            'fire, ignite, inflame, kindle, light'),
                                    TestWay('v',
                                            '使满足',
                                            'to put a complete end to (a physical need or desire)',
                                            ["this lemonade really quenches my thirst 这杯柠檬汁真是解渴"],
                                            'assuage, quench, sate, satiate, slake')]),
                              Word('querulous', "",
                                   [TestWay('adj',
                                            '抱怨的, 爱发牢骚的',
                                            'habitually complaining',
                                            ["a querulous voice 抱怨的声音"],
                                            'crabby, cranky, grouchy, grumpy',
                                            'forbearing, long-suffering, patient, stoic, tolerant, uncomplaining')]),
                              Word('quibble', "",
                                   [TestWay('vi',
                                            '吹毛求疵',
                                            'to find fault or criticize for petty reasons; cavil',
                                            ["she spent the entire evening quibbling about the historical inaccuracies in the television series on World War II 她一整晚都在对那个关于二战的电视剧里的历史错误吹毛求疵"],
                                            'carp, cavil, fuss, niggle, nitpick'),
                                    TestWay('n',
                                            '牵强之词: 微不足道的差别或不切中要点的异议, 小反对',
                                            'a minor objection or criticism',
                                            ["My only quibble about the trip was that it rained a lot. 我对旅行唯一的小不满就是下雨有点多。"])]),
                              Word('quiescent', "",
                                   [TestWay('adj',
                                            '平静的, 静止的',
                                            'being quiet, still, or at rest; inactive',
                                            ["a group of quiescent loungers 一群平静懒散的流浪汉"],
                                            'dull, inert, lethargic, sluggish, torpid',
                                            'rambunctious, tumultuous, active, restlessly active')]),
                              Word('quixotic', "",
                                   [TestWay('adj',
                                            '不切实际的, 空想的',
                                            'having or marked by a tendency to be guided more by ideals than by reality',
                                            ["She had quixotic dreams about the future. 她对未来有着幻想。"],
                                            'impractical, ideal, romantic, starry, utopian, visionary',
                                            'clear-eyed, clear-sighted')])])

list20_unit5 = VocabularyList([Word('quota', "",
                                   [TestWay('n',
                                            '配额, 限额',
                                            'a proportional part or share',
                                            ["The department set new sales quotas in May. 部门设定了五月的销售定额。"],
                                            'allowance, portion, proportion',
                                            'unlimited number')]),
                              Word('quotidian', "",
                                   [TestWay('adj',
                                            '平凡的',
                                            'everyday; commonplace',
                                            ["plagued by a quotidian coughing 每天被咳嗽困扰"],
                                            'commonplace, everyday, frequent, ordinary, routine, ubiquitous',
                                            'remarkable, striking, extraordinary, unusual, rare, infrequent, seldom')]),
                              Word('rabble', "",
                                   [TestWay('n',
                                            '混乱的人群',
                                            'a disorganized or disorderly crowd of people',
                                            ["the crown prince was reminded that even the rabble deserved his attention and compassion 太子应该知道即使是草民, 也值得他的关注和同情"],
                                            'ragtag and bobtail, riffraff, scum, rag, trash, unwashed')]),
                              Word('rabid', "",
                                   [TestWay('adj',
                                            '狂热的, 不冷静的',
                                            'extremely zealous or enthusiastic; fanatical',
                                            ["soccer fans whose rabid enthusiasm makes them go berserk when their team wins 不冷静的粉丝们在球队获胜以后变得很狂暴"],
                                            'delirious, ferocious, feverish, fierce, frantic, frenetic, violent',
                                            'logical, detached')]),
                              Word('racy', "",
                                   [TestWay('adj',
                                            '活泼生动的',
                                            'vigorous; lively',
                                            ["vivid writing and a racy plot that keeps readers turning the pages 栩栩如生的手法和生动新鲜的情节让读者手不释卷"],
                                            'animate, brisk, frisky, jaunty, perky, spirited, vivacious',
                                            'tame, dead, inactive, inanimate, lackadaisical, languid, languorous, leaden, lifeless, limp, listless, spiritless, vapid')]),
                              Word('raffish', "",
                                   [TestWay('adj',
                                            '低俗的',
                                            'marked by or suggestive of flashy vulgarity or crudeness',
                                            ["the dowager cringed at the thought of raffish tourists tromping all over her Persian rugs 寡妇一想到低俗的游客践踏她的波斯地毯就痛苦不已"],
                                            'crass, lowbred, uncouth, uncultivated, uncultured, unpolished, unrefined, vulgar',
                                            'civilized, cultivated, cultured, genteel, polished, refined, ultrarefined, well-bred')]),
                              Word('raffle', "",
                                   [TestWay('n',
                                            '垃圾, 废物',
                                            'discarded or useless material',
                                            ["The front lawn was littered with the raffle that the workers had left behind. 前院的草坪上满是工人们丢的垃圾。"],
                                            'chaff, deadwood, debris, dreck, dross, effluvium, litter, offal, offscouring, refuse, riffraff, rubbish, scrap, spilth')]),
                              Word('rage', "",
                                   [TestWay('n./v',
                                            '暴怒',
                                            'violent and uncontrolled anger',
                                            ["Her rages rarely last more than a few minutes. 她的暴躁来得快去得也快。"],
                                            'agitation, deliriousness, delirium, distraction, furor, hysteria, rampage')]),
                              Word('ragged', "",
                                   [TestWay('adj',
                                            '衣衫褴褛的',
                                            'dressed in tattered or threadbare clothes',
                                            ["A ragged coat may cover an honest man. 不能以衣著取人。"],
                                            'raggedy, ragtag, tattered, tatterdemalion, shabby',
                                            'kempt, neat, trim'),
                                    TestWay('adj',
                                            '凹凸不平的, 不光滑的',
                                            'not having a level or smooth surface',
                                            ["She cut herself on the ragged edge of the tin can's lid. 她被罐头盖的锋利边缘割伤了。"],
                                            'broken, bumpy, coarse, irregular, jagged, lumpy, pebbly, rough, roughened, rugged, scraggy',
                                            'even, flat, level, plane, smooth')]),
                              Word('rail', "",
                                   [TestWay('vi',
                                            '怒骂, 猛烈抨击',
                                            'to revile or scold in harsh, insolent, or abusive language',
                                            ["We could hear the cook in the kitchen railing against his assistant and wondered if we'd ever get our food. 我们可以听到厨师在厨房怒斥他的助手, 由此我们怀疑我们点的菜还能不能做好。"],
                                            'baste, berate, castigate, chastise, hammer, lambaste, rebuke, reprimand, reproach, upbraid',
                                            'accredit, applaud, commend, eulogize, extol, laud, praise',
                                            'raillery n. 善意的打闹')])])

list20_unit6 = VocabularyList([Word('rakish', "",
                                   [TestWay('adj',
                                            '放荡的, 行为不检点的',
                                            'having or showing lowered moral character or standards; dissolute',
                                            ["He wore his hat at a rakish angle. 他帽子戴得吊儿郎当的。"],
                                            'debased, debauched, demoralized, depraved, dissolute, libertine, perverse, perverted, reprobate',
                                            'good, moral, pure, righteous, virtuous, uncorrupted',
                                            'rake n. 行为不检点的人, 放荡的人')]),
                              Word('ramble', "",
                                   [TestWay('vi',
                                            '漫步, 漫游',
                                            'to move aimlessly from place to place',
                                            ["rambling under the starlight 在星光下漫步‖rambling around Beijing for a week 在北京四处漫游一周"],
                                            'amble, cruise, drift, float, meander, perambulate, roam, saunter, stroll, traipse, wander'),
                                    TestWay('vi',
                                            '漫谈; 长篇大论(并经常离题)地说或写',
                                            'to talk at length without sticking to a topic or getting to a point',
                                            ["rambling on about dating, homework, movies, and the local football team 扯了一些关于约会、作业、电影以及本地橄榄球队的闲谈"],
                                            'blather, chat, chatter, drivel, maunder, patter, prattle')]),
                              Word('rambunctious', "",
                                   [TestWay('adj',
                                            '喧闹的, 骚乱的',
                                            'being rough or noisy in a high-spirited way',
                                            ["That beach is often taken over by packs of rambunctious young people, so don't go there expecting peace and quiet. 那个海滩经常被一帮吵闹的年轻人占领, 所以不要指望过去能享受到平静和安宁。"],
                                            'boisterous, clamorous, raucous, riotous, rowdy, tumultuous, turbulent',
                                            'orderly, calm, noiseless, peaceful, placid, quiet, serene, silent, soundless, tranquil')]),
                              Word('ramshackle', "",
                                   [TestWay('adj',
                                            '摇摇欲坠的',
                                            'appearing ready to collapse; rickety',
                                            ["a ramshackle cabin in the woods 树林中摇摇欲坠的小木屋"],
                                            'rickety, shaky, tottering',
                                            'concrete, firm, solid, sturdy, stable')]),
                              Word('rancor', "",
                                   [TestWay('n',
                                            '敌意, 深仇',
                                            'a bitter deep-seated ill will',
                                            ["A good man terminates a friendship without rancor. 君子绝交不记仇。"],
                                            'animosity, animus, antagonism, antipathy, bitterness, gall, grudge, hostility, jaundice',
                                            'amity, harmony, goodwill, rapport, rapprochement, friendship')]),
                              Word('random', "",
                                   [TestWay('adj',
                                            '随机的, 随意的',
                                            'lacking a definite plan, purpose, or pattern',
                                            ["We received several answers and picked one at random. 我们收到了若干答案, 并随机抽取了一个。"],
                                            'aimless, arbitrary, desultory, erratic, haphazard, scattered, slapdash, stray',
                                            'methodical, orderly, organized, regular, systematic, systematized',
                                            'randomly adv. 随机地; randomize v. 随机挑选、排列')]),
                              Word('rankle', "",
                                   [TestWay('vt',
                                            '激怒',
                                            'to cause anger, irritation, or deep bitterness',
                                            ["It rankles me when some schools can't even afford paper and pencils for the students. 当我获悉有些学校连纸张和铅笔都无法提供给学生时, 我感到十分愤怒。"],
                                            'aggravate, enrage, exasperate, incense, inflame, infuriate, ire, madden, rile, roil',
                                            'delight, gratify, please 使愉悦; appease, assuage, conciliate, mollify, placate, propitiate')]),
                              Word('rant', "",
                                   [TestWay('n',
                                            '(尤指长时间的)训斥, 责骂',
                                            'a long angry speech or scolding',
                                            ["After complaining about the hotel’s lousy service, the woman went off on another rant about the condition of her room. 在抱怨完旅店差劲的服务之后, 她继续对房间的条件开骂。"],
                                            'castigation, diatribe, harangue, lambasting, philippic, reprimand, reproach, vituperation',
                                            'encomium, eulogy, panegyric, rhapsody, tribute'),
                                    TestWay('vi',
                                            '怒吼',
                                            'to speak or write in a noisy, angry or violent manner',
                                            ["The old expert ranted that nobody paid any attention to his opinion. 老专家怒气冲冲的叫嚷说没人听他的观点。"],
                                            'bluster, fulminate, huff, rave, roar, spout',
                                            'grumble, murmur, mutter')]),
                              Word('rapacious', "",
                                   [TestWay('adj',
                                            '食量大的, 贪食的',
                                            'having a huge appetite',
                                            ["The manager at the buffet restaurant was apparently astonished by a team of rapacious professional basketball players. 自助餐厅的经理很明显被那一队胃口巨大的职业篮球队员们震惊到了。"],
                                            'edacious, esurient,gluttonous, greedy, ravenous, voracious'),
                                    TestWay('adj',
                                            '过度贪婪的',
                                            'excessively grasping or covetous',
                                            ["Some companies is rapacious and hardly looking for the long-term value. 有些公司十分贪婪, 而且不考虑长期利益。"],
                                            'acquisitive, avaricious, avid, coveting, covetous, grasping, mercenary, moneygrubbing',
                                            'content, sated, satiated, satisfied',
                                            'rapaciousness n. 贪婪')]),
                              Word('rapport', "",
                                   [TestWay('n',
                                            '和睦, 友好',
                                            'a friendly relationship marked by ready communication and mutual understanding',
                                            ["His good rapport with his students was one of the reasons why the school board named him Teacher of the Year. 他和学生的关系和睦是他被􁨀名为“年度教师”的原因之一。"],
                                            'amity,communion, concord, fellowship, harmony, rapprochement',
                                            'animosity, antagonism, antipathy, bitterness, enmity, hostility, jaundice, rancor')])])

list20_unit7 = VocabularyList([Word('rapprochement', "",
                                   [TestWay('n',
                                            '和睦, 友好',
                                            'establishment of or state of having cordial relations',
                                            ["an era of rapprochement betweenChina and Russia 中俄两国睦邻友好关系的新纪元"],
                                            'amity,communion, concord, fellowship, harmony, rapport',
                                            'animosity, antagonism, antipathy, bitterness, enmity, hostility, jaundice, rancor')]),
                              Word('rapscallion', "",
                                   [TestWay('n',
                                            '流氓, 恶棍',
                                            'a mean, evil, or unprincipled person',
                                            ["an unsafe place frequented by drunkards and rapscallions 一个酒鬼和流氓经常造访的不安全的地方"],
                                            'brute, devil, evildoer, fiend, knave, miscreant, rascal, reprobate, rogue, savage, scamp, varlet, wretch',
                                            'saint, cavalier, chevalier')]),
                              Word('rapt', "",
                                   [TestWay('adj',
                                            '狂喜的',
                                            'experiencing or marked by overwhelming usually pleasurable emotion',
                                            ["a rock band that still attracts rapt crowds 一个仍然拥有者狂热粉丝的乐队"],
                                            'elated, elevated, enraptured, entranced, euphoric, exhilarated, intoxicated, rapturous, rhapsodic',
                                            'crestfallen, dejected, depressed 沮丧的; doleful, gloomy, melancholy, mournful, woeful'),
                                    TestWay('adj',
                                            '全神贯注的',
                                            'deeply absorbed; engrossed',
                                            ["With a mixture of delight and awe, the rapt children stared at the chick in the incubator breaking out of its shell. 怀着愉快和敬畏的复杂心理, 孩子们全神贯注地盯着孵化箱中的小鸡破壳而出。"],
                                            'absorbed, concentrated, deep, engrossed, enthralled, focused, immersed, intent, observant',
                                            'absent, abstracted, distracted, inattentive 不专心的; apathetic, disinterested, unconcerned')]),
                              Word('rash', "",
                                   [TestWay('adj',
                                            '草率的, 仓促的',
                                            'marked by or proceeding from undue haste or lack of deliberation or caution',
                                            ["That was too rash a move: for now you've lost your bishop and probably the whole chess game. 那一招棋着实是太草率了, 现在你丢掉了象, 很有可能会输掉整场比赛。"],
                                            'cursory, gadarene, headlong, hurried, overhasty, precipitate, precipitous, rushed',
                                            'deliberate 慎重考虑的; leisurely, unhurried, unrushed',
                                            'rashly adv. 草率地, 仓促地')]),
                              Word('rarefy', "",
                                   [TestWay('vt',
                                            '使稀薄',
                                            'to make rare, thin, porous, or less dense: to expand without the addition of matter',
                                            ["rarefy the air 使空气变得稀薄"],
                                            'attenuate, dilute, thin',
                                            'concentrate, condense',
                                            'rarefaction n. 稀薄, 稀疏')]),
                              Word('raspy', "",
                                   [TestWay('adj',
                                            '声音刺耳的',
                                            'harsh and dry in sound',
                                            ["The dying man was speaking in a raspy and barely discernible voice. 将死的人在用一种沙哑刺耳且难以听清的语调说话。"],
                                            'cacophonous, coarse, croaky, harsh, grating, gravelly, gruff, husky, rasping, rusty, scratchy, throaty',
                                            'mellifluous, sweet, gentle, soft, tender'),
                                    TestWay('adj',
                                            '容易生气的',
                                            'easily irritated or annoyed',
                                            ["Overwork tends to make him raspy. 过度的工作让他变得烦躁易怒。"],
                                            'choleric, fiery, grouchy, irascible, peevish, pettish, petulant, prickly, ratty, testy',
                                            'agreeable, amiable, good-natured, good-tempered, well-disposed')]),
                              Word('ratify', "",
                                   [TestWay('vt',
                                            '(官方地)认可, 批准',
                                            'to give official acceptance of as satisfactory',
                                            ["Lincoln's home state of Illinois was the first to ratify the 13th Amendment to the U.S. Constitution, which provided for the abolition of slavery. 林肯的老家——伊利诺伊是美国第一个通过《宪法第十三修正案》的州, 该决案提供了废除奴隶制的法律基础。"],
                                            'accredit, approbate, authorize, certify, endorse, finalize, formalize, pass, sanction, validate, warrant',
                                            'decline, deny, disallow, disapprove, negative, reject, veto',
                                            'ratification n. 正式批准')]),
                              Word('ratiocination', "",
                                   [TestWay('n',
                                            '推理',
                                            'the thought processes that have been established as leading to valid solutions to problems',
                                            ["As an expert in ratiocination, the detective Sherlock Holmes has few rivals. 作为推理专家, 大侦探福尔摩斯可谓无人能及。"],
                                            'deduction, intellection, reason, reasoning, sense')]),
                              Word('ration', "",
                                   [TestWay('n',
                                            '定额供应量, 配给量',
                                            'an amount allotted or made available especially from a limited supply',
                                            ["The meat ration was down to one pound per person per week. 肉的人均供给量降至了每周一磅。"],
                                            'allotment, allowance, apportionment, portion, provision, quota, share'),
                                    TestWay('vt',
                                            '按比例分配',
                                            'to give as a share or portion',
                                            ["The region has had to ration water during times of drought. 干旱时该地区不得不按比例分配水资源。"],
                                            'allocate, allot, allow, apportion, assign, distribute, lot',
                                            'keep, retain, withhold')]),
                              Word('rational', "",
                                   [TestWay('adj',
                                            '合乎逻辑的',
                                            'consistent with or based on reason; logical',
                                            ["He insisted there was a rational explanation for the strange creaking noises and that there were no such things as ghosts. 他坚持认为奇怪的咯吱声一定有一个合理的解释, 而不是所谓的鬼在作怪。"],
                                            'analytic, coherent, consequent, logical, reasonable, sensible, sound, valid, well-founded, well-grounded',
                                            'illogical, incoherent, inconsequent, invalid, irrational, unreasonable, unsound, weak'),
                                    TestWay('adj',
                                            '理性的',
                                            'based on sound reasoning or information',
                                            ["Betting all of your savings on the lottery is not a rational move. 把你所有的存款赌在彩票上可不是一个理智的决定。"],
                                            'commonsensical, firm, informed, just, justified, levelheaded, sober, solid',
                                            'groundless, unfounded, unjustified',
                                            'rationalize v. 使合理化; 找借口')])])

list20_unit8 = VocabularyList([Word('rave', "",
                                   [TestWay('vi',
                                            '狂热赞扬',
                                            'to make an exaggerated display of affection or enthusiasm',
                                            ["Critics raved about the new play. 新剧得到了评论家们的热烈赞扬。"],
                                            'drool, effuse, enthuse, fuss, rhapsodize, slobber',
                                            'blame, censure, condemn, criticize, denounce, pan, reprehend'),
                                    TestWay('vi',
                                            '(发疯般地)怒吼',
                                            'to talk irrationally and wildly in or as if in delirium',
                                            ["a man standing outside the city hall,raving like a lunatic about his tax bill 站在市政大厅外、像疯子一样叫嚷着自己税单的人"],
                                            'bluster, fulminate, huff, rant, roar, spout',
                                            'grumble, murmur, mutter')]),
                              Word('ravel', "",
                                   [TestWay('vt',
                                            '解开, 松开',
                                            'to separate the various strands of',
                                            ["Since the sweater is too small, you could ravel the yarnout and make something else with it. 既然这个毛衣太大, 你可以把它拆了然后织些新的东西。"],
                                            'disentangle, extricate, unbraid, unsnarl, untwine, unweave',
                                            'braid, knit, plait, weave'),
                                    TestWay('vt',
                                            '阐明',
                                            'to clarify by separating the aspects of',
                                            synonyms = 'clarify, clear, elucidate, untangle, unravel',
                                            antonyms = 'complex, complicate, entangle, perplex, sophisticate, snarl, tangle'),
                                    TestWay('vt',
                                            '使纠缠, 使复杂化',
                                            'to tangle or complicate',
                                            ["a ravelled story 一个复杂的故事"],
                                            'complex, complicate, entangle, perplex, sophisticate, snarl, tangle',
                                            'clarify, clear, elucidate, untangle, unravel')]),
                              Word('ravish', "",
                                   [TestWay('vt',
                                            '使陶醉, 使沉迷',
                                            'to overcome with emotion (as wonder or delight)',
                                            ["I was completely ravished by those marvelous pictures taken by HST. 那些哈勃太空望远镜拍摄的壮观图片让我彻底的陶醉了。"],
                                            'captivate, enchant, enrapture, enthrall, rapture, transport',
                                            'disenchant, sober',
                                            'ravishing adj. 极美丽的')]),
                              Word('raze', "",
                                   [TestWay('vt',
                                            '摧毁, 粉碎',
                                            'to destroy completely by or as if by knocking down or breaking to pieces',
                                            ["Excavators were began to raze old school building. 挖土机开始夷平学校的老建筑。", "An entire city block razed by a terrible fire. 大火摧毁了整个街区"],
                                            'annihilate, decimate, demolish, devastate, level, nuke, pulverize, ruin, smash, vaporize, wreck, tear down',
                                            'build, construct, erect, raise, rear, set up',
                                            'razor n. 剃须刀')]),
                              Word('react', "",
                                   [TestWay('vt',
                                            '做出反应',
                                            'to act or behave in response (as to a stimulus or influence)',
                                            ["didn't know how to react to the cheers of the crowd 不知如何对人群的欢呼声做出回应"],
                                            'answer, reply, respond',
                                            other_form = 'reaction n. 反应; reactant n. (化学反应当中的)反应物')]),
                              Word('reactionary', "",
                                   [TestWay('adj',
                                            '反对变革的, 极保守的',
                                            'characterized by reaction, especially opposition to progress or liberalism; extremely conservative',
                                            ["reactionary rulers 保守的统治者"],
                                            'brassbound, conservative, die-hard, hidebound, traditionalistic, ultraconservative',
                                            'liberal, progressive, radical, aggressive')]),
                              Word('ream', "",
                                   [TestWay('v',
                                            '怒斥, 训斥',
                                            'to criticize (someone) severely or angrily especially for personal failings',
                                            ["You are so going to get reamed out when the boss learns that you wrecked the company car. 要是老板知道你把公司的车弄坏了, 你肯定会挨骂的。"],
                                            'baste, berate, castigate, chastise, hammer, lambaste, rail, rebuke, reprimand, reproach, upbraid',
                                            'accredit, applaud, commend, eulogize, extol, laud, praise')]),
                              Word('reap', "",
                                   [TestWay('v',
                                            '收割, 收获',
                                            'to collect (a crop or natural resource) or to receive as return for effort',
                                            ["As you sow, so shall you reap. 唯有付出, 才有回报。", "She reaped large profits from her patents. 她的专利给她带来了丰厚的回报。"],
                                            'acquire, attain, capture, harvest, gain, garner, obtain, procure, secure',
                                            'plant, seed, sow, forfeit, lose',
                                            'reaper n. 收割机; 死神')]),
                              Word('reassure', "",
                                   [TestWay('vt',
                                            '使安心, 打消疑虑',
                                            'to restore to confidence',
                                            ["I tried to reassure her that the dog would come back home by nightfall. 我尽力让她安心, 说夜幕降临之前小狗一定会回家的"],
                                            'assure, cheer, console, solace, soothe',
                                            'distress, torment, torture, trouble',
                                            'reassurance n. 消除疑虑')]),
                              Word('rebuff', "",
                                   [TestWay('vt',
                                            '严词拒绝',
                                            'to reject or criticize sharply',
                                            ["rebuffed an invitation from her colleagues 回绝了同事们的邀请‖She rebuffed him when he asked her for a date. 她拒绝了他约会的邀请。"],
                                            'decline, deny, refuse, reject, repudiate, repulse, snub, spurn',
                                            'accept, approve, welcome')])])

list20_unit9 = VocabularyList([Word('recalcitrant', "",
                                   [TestWay('adj',
                                            '顽抗的, 不顺从的',
                                            'marked by stubborn resistance to and defiance of authority or guidance',
                                            ["a recalcitrant teenager 执拗的少年‖The manager worried that the recalcitrant employee would try to undermine his authority. 经理担心那些不听命的员工会削弱它的权威。"],
                                            'balky, contumacious, defiant, incompliant, insubordinate, intractable, obstreperous, rebellious, refractory, unruly',
                                            'amenable, compliant, conformable, docile, governable, obedient, ruly, submissive, tractable',
                                            'recalcitrance n. 固执, 不服从命令')]),
                              Word('recant', "",
                                   [TestWay('vt',
                                            '撤回, 放弃, 改变',
                                            'to withdraw or repudiate (a statement or belief) formally and publicly',
                                            ["The man has refused after torture to recant his heresy. 这个人在受折磨后依旧拒绝放弃他的异教信仰。"],
                                            'abjure, abnegate, forswear, renege, renounce, repeal, repudiate, retract, withdraw',
                                            'adhere, insist, maintain, stick',
                                            'recantation n. 改变论调')]),
                              Word('recessive', "",
                                   [TestWay('adj',
                                            '(基因等)隐性的, 由隐形基因控制的',
                                            'of, relating to, or designating an allele that does not produce a characteristic effect when present with a dominant allele',
                                            ["a recessive disease 阴性基因控制的疾病"],
                                            antonyms = 'dominant'),
                                    TestWay('adj',
                                            '内向的, 内敛的',
                                            'not comfortable around people',
                                            ["For such a recessive genius, the most comfortable thing is working alone in his lab. 对于这样一个内向的天才而言, 最舒服的事情就是一个人在实验室里干活。"],
                                            'backward, bashful, coy, demure, diffident, introverted, modest, retiring, self-effacing, sheepish, withdrawn',
                                            'extroverted, immodest, outgoing, gregarious, sociable',
                                            'recession n. 后退, 衰退')]),
                              Word('recidivate', "",
                                   [TestWay('vi',
                                            '回到原先的习惯, 尤指重新犯罪',
                                            'to return to a previous pattern of behavior, especially to return to criminal habits',
                                            ["The suspect has recidivated for several times. 这个嫌犯是个惯犯了"],
                                            'regress, relapse, retrogress, revert',
                                            'habilitate, reclaim, redeem, regenerate, rehabilitate',
                                            'recidivism n. 再犯, 重犯; recidivist n. 再次犯罪的人')]),
                              Word('reciprocate', "",
                                   [TestWay('vi',
                                            '往复运动',
                                            'to move forward and backward alternately',
                                            ["According to Marx’s economic principle, the average price of a certain product should be reciprocating over its value. 根据马克思的经济学理论, 商品的平均价格应该在它的价值周边波动。"],
                                            'fluctuate, oscillate, sway, swing, vacillate'),
                                    TestWay('vt',
                                            '报答, 回报',
                                            'to return in kind or degree',
                                            ["reciprocated the favor by driving their neighbor to the airport 开车送邻居去机场以还人情"],
                                            'recompense, repay, requite, retaliate, return',
                                            'owe',
                                            'reciprocal adj. 相互之间的, 互惠的')]),
                              Word('reckless', "",
                                   [TestWay('adj',
                                            '不考虑后果的, 大胆鲁莽的',
                                            'careless of consequences; foolishly adventurous or bold',
                                            ["His reckless driving accounted for the accident. 他鲁莽的开车行为导致了这场事故。"],
                                            'audacious, bold, brash, brassy, brazen, careless, daredevil, rash, madcap, temerarious',
                                            'careful, cautious, circumspect, guarded, heedful, prudent, wary')]),
                              Word('recluse', "",
                                   [TestWay('n',
                                            '隐士',
                                            'a person who lives away from others',
                                            ["He was sick of cities and crowds, so he decided to go live by himself in the woods as a recluse. 他厌倦了城市和拥挤的人群, 因此他决定像隐士一样遁隐山林。"],
                                            'anchorite, eremite, hermit, isolate, solitary'),
                                    TestWay('adj',
                                            '隐居的, 不爱社交的',
                                            'marked by withdrawal from society',
                                            ["a recluse poet who left a large amount of literature legacies 一个留下了大量文学遗产的隐居诗人", "My neihgbor is so recluse that I only see him about once a year. 我的邻居太神秘了, 一般我一年只能见他一面。"],
                                            'cloistered, hermetic, secluded, secluse, seclusive, sequestered',
                                            'gregarious, social',
                                            'reclusive adj. 隐居的')]),
                              Word('recoil', "",
                                   [TestWay('vi',
                                            '退却, 畏缩',
                                            'to shrink back, as under pressure or in fear or repugnance',
                                            ["recoil from the snake 因为害怕蛇而畏缩不前", "She recoiled from his touch. 她因害怕与他接触而退缩"],
                                            'blench, cringe, flinch,quail, shrink, squinch, wince',
                                            'confront, meet')]),
                              Word('reconcile', "",
                                   [TestWay('vt',
                                            '使和解, 协调',
                                            'to restore to friendship or harmony',
                                            ["Historians have never been able to reconcile the two eyewitness accounts of the battle. 历史学家们一直以来都无法协调这场战役两种记载之间的矛盾。"],
                                            'accommodate, attune, conciliate, conform, coordinate, harmonize, key',
                                            'disharmonize, estrange',
                                            'reconciliation n. 协调')]),
                              Word('recondite', "",
                                   [TestWay('adj',
                                            '深奥的, 难解的',
                                            'difficult or impossible for one of ordinary understanding or knowledge to comprehend',
                                            ["I think Quantum Mechanics and Random Process arethe two most recondite courses in our curriculum this semester. 我觉得量子力学和随机过程是这学期课表中最难的两门课程"],
                                            'abstruse, arcane, deep, enigmatic, esoteric, hermetic, occult, profound',
                                            'facile, shallow, superficial, easy, simple')])])

list20_unit10 = VocabularyList([Word('reconnoiter', "",
                                   [TestWay('vt',
                                            '侦察, 勘查',
                                            'to make a preliminary inspection of, especially in order to gather military information',
                                            ["The wide utilization of unmanned aerial vehicles makes it much less risky to reconnoiter a certain area. 无人飞行器的广泛运用大大减少了军事侦察的风险"],
                                            'probe,scout, survey',
                                            other_form = 'reconnaissance n. 侦察')]),
                              Word('reconstitute', "",
                                   [TestWay('vt',
                                            '重建, (尤其是通过加水)使复原',
                                            'to constitute again or anew; to restore to a former condition, especiallyby adding water',
                                            ["reconstitute dried coffee powder 冲咖啡", "Slowly Jewish communities ravaged by Nazi Germany were reconstituted and life began anew.被纳粹德国摧残的犹太人社区慢慢得以重建, 新的生活开始了。"],
                                            'reconstruct, reorder, reorganize, reshuffle, retool',
                                            'annihilate, decimate, demolish, devastate, level, nuke, pulverize, ruin, smash, vaporize, wreck',
                                            'reconstitution n. (加水)复原')]),
                              Word('reconvene', "",
                                   [TestWay('v',
                                            '重新集合, 重新召集',
                                            'to gather, call together, or summon again, especially for a formal meeting',
                                            ["The leaders will reconvene tomorrow. 明天领导们会再次召开会议。"],
                                            'reassemble',
                                            'adjourn, suspend')]),
                              Word('rectitude', "",
                                   [TestWay('n',
                                            '正直',
                                            'the quality or state of being straight; moral integrity',
                                            ["The principal encouraged the graduates to go on to live lives of rectitude. 校长鼓励毕业生们在今后的生活中做一个正直的人。"],
                                            'honesty, integrity, probity, righteousness, scrupulousness, uprightness, virtue, virtuousness',
                                            'badness, evil, immorality, iniquity, sin, villainy, wickedness')]),
                              Word('recumbent', "",
                                   [TestWay('adj',
                                            '躺着的',
                                            'lying down, especially in a position of comfort or rest',
                                            ["lying recumbent on the floor 躺在地板上势"],
                                            'decumbent, procumbent, prone, prostrate, reclining, supine',
                                            'erect, upright')]),
                              Word('recuperate', "",
                                   [TestWay('vi',
                                            '恢复(健康或力量), 康复',
                                            'to recover health or strength',
                                            ["He is gradually recuperating from a serious back injury. 他正渐渐地从严重的背部损伤中恢复过来。"],
                                            'convalesce, heal, rally, recoup, recover, rehabilitate',
                                            'deteriorate, flag, wane, weaken, die, expire, perish, pass away',
                                            'recuperative adj. 有助于康复的')]),
                              Word('redolent', "",
                                   [TestWay('adj',
                                            '芳香的',
                                            'having or emitting fragrance',
                                            ["be redolent with the aroma of baking bread 充满了烤面包的香味"],
                                            'ambrosial, aromatic, fragrant, perfumed, savory, scented, sweet',
                                            'unscented, fetid, foul, malodorous, noisome, rancid, reeky, stinky',
                                            'redolence n. 芳香, 香味')]),
                              Word('redoubtable', "",
                                   [TestWay('adj',
                                            '杰出的, 值得尊敬的',
                                            'worthy of respect or honor',
                                            ["a surprising discovery by one of the most redoubtable figures in Egyptian archaeology 埃及考古学领域最值得敬重的人物之一所做出的一个惊人发现"],
                                            'bright, distinguished, illustrious, luminous, notable, noteworthy, outstanding, preeminent, prestigious',
                                            'average, inferior, mediocre'),
                                    TestWay('adj',
                                            '可怕的',
                                            'arousing fear or awe',
                                            ["His next opponent would be by far the most redoubtable adversary the young boxer had ever faced. 年轻的拳击手的下一个对手将会是迄今为止他见过的最可怕的敌人"],
                                            'direful, dreadful, fearsome, formidable, frightening, ghastly, horrifying, intimidating, scary, terrifying',
                                            'calming, comforting, consoling, lulling, pacifying, quieting, reassuring, relaxing, soothing')]),
                              Word('redundant', "",
                                   [TestWay('adj',
                                            '多余的, 冗余的',
                                            'exceeding what is necessary or normal',
                                            ["This area is already chockablock with shopping malls; another one would be redundant. 这个地区已经是商场扎堆了, 再建一个完全是多此一举。"],
                                            'excess, extra, supererogatory, superfluous, supernumerary, surplus',
                                            'deficient, inadequate, insufficient, meager, niggardly, scant, scarce, short, sparse',
                                            'redundancy n. 过剩, 过多')]),
                              Word('reel', "",
                                   [TestWay('vi',
                                            '感到眩晕',
                                            'to be in a confused state as if from being twirled around',
                                            ["My head reeled with the facts and figures. 我的头脑被这些事实和数据给弄晕了。‖His mind reeled upon hearing the news that his employer had been indicted for fraud. 当他听到雇主因为欺诈而被起诉时, 他顿觉天旋地转。"],
                                            'spin, swirl, turn, whirl',
                                            'calm'),
                                    TestWay('vi',
                                            '蹒跚地走路',
                                            'to move forward while swaying from side to side',
                                            ["The drunkard reeled down the alley. 醉汉蹒跚地沿着小巷走去"],
                                            'careen, dodder, falter, lurch, stagger, stumble, teeter, totter, waddle')])])

LIST20 = VocabularyList(list20_unit1.words+list20_unit2.words+list20_unit3.words+list20_unit4.words+list20_unit5.words+list20_unit6.words+list20_unit7.words+list20_unit8.words+list20_unit9.words+list20_unit10.words)
