#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list7_unit1 = VocabularyList([Word('despicable', "",
                                   [TestWay('adj',
                                            '令人鄙视的',
                                            "arousing or deserving of one's loathing and disgust",
                                            ["even within the prison population, pedophiles are regarded as particularly despicable 即使在囚犯内部, 恋童癖者也被认为极其让人鄙视的。"],
                                            ['contemptible', 'detestable', 'dishonorable'],
                                            ['admirable', 'commendable', 'creditable', 'meritorious', 'praiseworthy']),
                                    TestWay('adj',
                                            '不荣耀的, 不得体的',
                                            'not following or in accordance with standards of honor and decency',
                                            ["the cad's despicable behavior toward women 公车售票员对女性不得体的举动"],
                                            ['currish', 'dirty', 'execrable', 'ignominious', 'sordid', 'wretched'],
                                            ['honorable', 'lofty', 'noble', 'upright', 'venerable', 'virtuous'])]),
                              Word('despise', "",
                                   [TestWay('vt',
                                            '极其不喜欢',
                                            'to dislike strongly',
                                            ["I despise anchovies on pizza, and I refuse to eat them. 我讨厌在披萨上的凤尾鱼, 所以从来不吃。"],
                                            ['abhor', 'abominate', 'detest', 'execrate', 'loathe', 'disregard', 'flout'],
                                            ['love'])]),
                              Word('despotic', "",
                                   [TestWay('adj',
                                            '专制的, 暴虐的',
                                            'arbitrary, autocratic, monocratic, tyrannical',
                                            ["a despotic tyrant 专制的暴君"],
                                            ['authoritative', 'dictatorial', 'imperious', 'overbearing', 'peremptory', 'tyrannous'])]),
                              Word('desultory', "",
                                   [TestWay('adj',
                                            '无计划、无目的的',
                                            'lacking a definite plan, purpose, or pattern',
                                            ["a desultory search for something of interest on TV 漫无目的地换台"],
                                            ['digressive', 'excursive', 'meandering', 'rambling', 'wandering'],
                                            ['carefully' 'planned', 'strictly' 'methodical', 'assiduous']),
                                    TestWay('adj',
                                            '令人失望的',
                                            'disappointing in progress, performance, or quality',
                                            ["a desultory fifth place finish 让人失望的第五名"])]),
                              Word('detach', "",
                                   [TestWay('v',
                                            '分离',
                                            'to separate or unfasten; disconnect',
                                            ["Detach the white part of the application form and keep it. 撕下申请表的白色部分并予以保留。"],
                                            antonyms = ['tether'])]),
                              Word('detain', "",
                                   [TestWay('v',
                                            '拘留',
                                            'to hold or keep in or as if in custody',
                                            ["detained by the police for questioning 被警察扣留下问讯"],
                                            antonyms = ['manumit'])]),
                              Word('deter', "",
                                   [TestWay('v',
                                            '吓住, 威慑',
                                            'to prevent or discourage from acting, as by means of fear or doubt',
                                            ["wouldn't be deterred by threats 不被威胁吓住"],
                                            ['dissuade', 'inhibit'],
                                            ['spur', 'courage', 'persuade'],
                                            'deterrent adj/ n. 威慑力量, 威慑的 【例】deterrent weapons 威慑性武器; a deterrent to theft 对偷窃的威慑 【反】inducement, incentive 引诱, 刺激')]),
                              Word('deterioration', "",
                                   [TestWay('n',
                                            '恶化；堕落',
                                            'a gradual sinking and wasting away of mind or body',
                                            ["a continuing deterioration in relations between the two countries 两国关系的持续恶化"],
                                            ['decadence', 'degeneration', 'deterioration', 'devolution', 'downfall', 'downgrade'],
                                            ['improvement', 'recovery', 'recuperation', 'rehabilitation', 'revitalization'])]),
                              Word('detour', "",
                                   [TestWay('n',
                                            '偏离正常标准',
                                            'a turning away from a course or standard',
                                            ["we'll regard this relapse as just a brief detour on your road to recovery from substance abuse 我们把这次旧病复发看成你戒瘾道路上的一个小偏离"],
                                            ['deflection', 'departure', 'deviation', 'divergency']),
                                    TestWay('v',
                                            '改变方向或者路线',
                                            "to change one's course or direction",
                                            ["we had to detour for a few miles around the section of highway under construction 我们不得不绕远几公里为了避开正在维修的高速公路路段"],
                                            ['deviate', 'diverge', 'sheer', 'swerve', 'veer'])]),
                              Word('detract', "",
                                   [TestWay('v',
                                            '贬低',
                                            'to diminish the importance, value, or effectiveness of something',
                                            ["It is wrong to detract from the achievements of other people in the same field. 贬低同行是不对的。"],
                                            ['belittle', 'depreciate', 'derogate', 'disparage', 'dispraise', 'write off'],
                                            ['extol', 'praise', 'eulogize', 'laud', 'panegyrize']),
                                    TestWay('v',
                                            '使分心',
                                            'to draw the attention or mind to something else',
                                            ["Numerous typos in the text detract the reader's attention from the novel's intricate plot. 许多打印错误把读者分心, 不关注复杂的情节了。"],
                                            ['divert', 'abstract', 'call off'])])])

list7_unit2 = VocabularyList([Word('detritus', "",
                                   [TestWay('n',
                                            '废品, 碎屑, 遗骸',
                                            'a product of disintegration, destruction, or wearing away: debris',
                                            ["the detritus of war 战争的遗骸"],
                                            ['debris', 'residue', 'wreck'],
                                            ['valuable product'])]),
                              Word('devoted', "",
                                   [TestWay('adj',
                                            '投入的, 忠诚的',
                                            'characterized by loyalty and devotion',
                                            ["Good teachers are devoted to learning. 好老师会专心学习。"],
                                            ['constant', 'loyal', 'allegiant', 'dedicated', 'devout', 'loyal', 'pious', 'staunch', 'steadfast'],
                                            ['disloyal', 'faithless', 'perfidious', 'unfaithful', 'recreant', 'traitorous', 'treacherous']),
                                    TestWay('adj',
                                            '示爱的, 恩爱的',
                                            'feeling or showing love',
                                            ["a devoted couple will enjoy sharing their lives with one another. 一对恩爱的情侣喜欢和对方一起度过自己的人生。"],
                                            ['adoring', 'affectionate', 'fond', 'tender', 'tenderhearted'],
                                            ['unloving'])]),
                              Word('devout', "",
                                   [TestWay('adj',
                                            '(对于宗教)虔诚的',
                                            'devoted to religion or to religious duties or exercises',
                                            ["a devout Buddhist 虔诚的佛教徒"],
                                            ['pious', 'religious', 'sainted'],
                                            ['antireligious', 'impious']),
                                    TestWay('adj',
                                            '忠诚的',
                                            "firm in one's allegiance to someone or something",
                                            ["Devout Mavericks fans never lost faith in Nowitzki. 忠诚的小牛队球迷从来没有对诺维斯基失去信心。"],
                                            ['constant', 'loyal', 'allegiant', 'dedicated', 'devoted', 'loyal', 'pious', 'staunch', 'steadfast'],
                                            ['disloyal', 'faithless', 'perfidious', 'unfaithful', 'recreant', 'traitorous', 'treacherous'])]),
                              Word('dexterous', "",
                                   [TestWay('adj',
                                            '动作灵活的',
                                            'ready and skilled in physical movements',
                                            ["a dexterous surgeon 技术娴熟的外科医生", "The dexterous watchmaker was able to repair the antique watch's delicate gears and parts. 手巧的手表匠能够修理古董手表的精密的齿轮和部件。"],
                                            ['deft', 'handy'],
                                            ['ham-fisted', 'ham-handed', 'handless', 'heavy-handed', 'unhandy']),
                                    TestWay('adj',
                                            '头脑灵活的',
                                            'mentally adroit and skillful: clever',
                                            synonyms = ['adroit', 'clever', 'cunning'],
                                            antonyms = ['dull', 'foolish', 'silly', 'fatuous', 'unwise'])]),
                              Word('diabolic', "",
                                   [TestWay('adj',
                                            '恶魔一般的',
                                            'of, relating to, or characteristic of the devil',
                                            ["The police quickly mobilized to track down the diabolical serial killer. 警察迅速调动起来来追查出这个恶魔般的连环杀人狂。"],
                                            ['demoniac', 'demonian', 'demonic', 'devilish', 'satanic'],
                                            ['angelic', 'seraphic'])]),
                              Word('diaphanous', "",
                                   [TestWay('adj',
                                            '模糊的, 非实在的',
                                            'vague or insubstantial',
                                            ["only a diaphanous hope of success 只有一丝成功的希望"],
                                            ['vague', 'obscure', 'unexplicit', 'insubstantial', 'immaterial'],
                                            ['substantial', 'clear', 'distinct']),
                                    TestWay('adj',
                                            '(质地精致得)几乎透明的',
                                            'of such fine texture as to be transparent or translucent',
                                            ["The bride wore a diaphanous veil. 新娘戴着透明的面纱。"],
                                            ['transparent', 'translucent', 'transpicuous', 'gossamer'],
                                            ['opaque', 'impermeable of light'])]),
                              Word('diatribe', "",
                                   [TestWay('n',
                                            '长篇抨击性演讲',
                                            'a long angry speech or scolding',
                                            ["He was forced to sit through a long diatribe. 他被迫耐着性子听完一个长篇抨击性演讲。"],
                                            ['tirade', 'harangue', 'jeremiad', 'philippic', 'rant']),
                                    TestWay('n',
                                            '挖苦, 讽刺的指责',
                                            'ironic or satirical criticism',
                                            ["The movie reviewer wrote a diatribe of the movie describing it as having excessive sex and violence. 那个影评人指责这个电影还有过多的色情和暴力。"],
                                            ['irony', 'satire'],
                                            ['encomium', 'eulogy', 'panegyric', 'tribute', 'laudatory piece of writing'])]),
                              Word('didactic', "",
                                   [TestWay('adj',
                                            '喜欢说教的',
                                            'designed or intended to teach',
                                            ["Parents’ speech to their kids often seems to be painfully didactic. 父母对他们孩子的话都是让人痛苦的说教。"],
                                            ['homiletic', 'preachy', 'moralistic', 'sententious'],
                                            ['undidactic'])]),
                              Word('diehard', "",
                                   [TestWay('adj./n',
                                            '顽固的, 保守的/顽固的人, 保守的人',
                                            'strongly or fanatically determined or devoted someone who opposes change and refuses to accept new ideas',
                                            ["Some diehard smokers belied the doctors' suggestion. 一些顽固的烟民违背了医生们的建议。"],
                                            ['conservative', 'hidebound', 'old-fashioned', 'reactionary', 'ultraconservative'],
                                            ['liberal', 'nonconservative', 'open-minded', 'liberal'])]),
                              Word('diffident', "",
                                   [TestWay('adj',
                                            '不自信的',
                                            'hesitant in acting or speaking through lack of self-confidence',
                                            ["He is diffident to express his opinions in public. 他在公共场合表达自己的观点时有点害羞"],
                                            ['unassured', 'bashful', 'retiring', 'self-effacing', 'withdrawn'],
                                            ['confident', 'assured', 'self-assured', 'self-confident']),
                                    TestWay('adj',
                                            '内向的',
                                            'reserved in manner; unassertive',
                                            ["She was diffident about stating her opinion. 她很内向, 表达自己的观点的时候有点害羞。"],
                                            ['introverted'],
                                            ['extroverted', 'outgoing'])])])

list7_unit3 = VocabularyList([Word('diffuse', "",
                                   [TestWay('adj',
                                            '罗嗦的',
                                            'being at once verbose and ill-organized',
                                            ['a diffuse report 冗长的报告'],
                                            ['circuitous', 'circumlocutory', 'long-winded', 'prolix', 'verbose', 'windy', 'rambling'],
                                            ['concise', 'pithy', 'succinct', 'terse', 'laconic']),
                                    TestWay('adj',
                                            '不集中的, 扩散的',
                                            'not concentrated or localized',
                                            ["diffuse lighting 散射光"],
                                            antonyms = ['concentrated']),
                                    TestWay('v',
                                            '扩展, 散开',
                                            'extend, scatter',
                                            ["The photographer uses a screen to diffuse the light. 摄影师用一个屏幕来分散光线。"],
                                            ['spread', 'extend', 'disperse', 'disseminate', 'scatter'],
                                            ['concentrate', 'center', 'centralize', 'focus'])]),
                              Word('digress', "",
                                   [TestWay('v',
                                            '脱离主题',
                                            'to turn aside especially from the main subject of attention or course of argument',
                                            ["digress from her prepared subject 脱离她准备好的主题", "He digressed so often that it was hard to follow what he was saying. 他经常跑题, 以至于我们很难跟上他说的内容。"],
                                            ['excurse', 'ramble', 'diverge', 'get off the subject'],
                                            other_form = 'digressive adj.偏离的 【近】discursive 【派】digression n. 题外话： the act or an instance of digressing in a discourse 【近】aside')]),
                              Word('dilapidate', "",
                                   [TestWay('v',
                                            '使荒废',
                                            'to bring into a condition of decay or partial ruin',
                                            ["The house has been dilapidated by neglect. 由于没人照看, 这个房子已经要荒废了。"],
                                            ['ruin', 'wreck'],
                                            ['be in use', '还在使用', 'restore' '恢复使用', 'mend', 'repair', '修理', 'rejuvenate', 'renew', 'renovate', '翻新'])]),
                              Word('dilate', "",
                                   [TestWay('v',
                                            '使膨胀, 扩大',
                                            'to enlarge or expand in bulk or extent；to become wide',
                                            ["The cat dilated its eyes in the darkness. 猫在黑暗中睁大眼睛。", "The drug dilates the blood vessels. 药使血管膨胀。"],
                                            ['expand', 'amplify', 'enlarge'],
                                            ['contract', 'narrow']),
                                    TestWay('v',
                                            '详细表达',
                                            'to express more fully and in greater detail',
                                            ["He refused to dilate upon his plan for improving the economy in the event that he won the election. 他拒绝在他赢得选举的情况下透露更多关于振兴经济计划的细节。"],
                                            ['amplify', 'develop', 'elaborate on', 'flesh out', 'dilate on', 'enlarge on'],
                                            ['abbreviate', 'abridge', 'condense', 'shorten'])]),
                              Word('dilatory', "",
                                   [TestWay('adj',
                                            '拖延的, 磨蹭的',
                                            'tending or intended to cause delay, characterized by procrastination',
                                            ["dilatory tactics 拖延战术", "The homeowner is claiming that local firefighters were dilatory in responding to the call. 业主声称本地的消防队员对(火警)电话的有拖延。"],
                                            ['delaying', 'procrastinating', 'dragging', 'lagging', 'tardy'],
                                            ['rapid', 'fast', 'fleet', 'precipitate', 'rocketing', 'swift hasty', 'hurrying', 'scurrying'])]),
                              Word('dilettante', "",
                                   [TestWay('n./adj',
                                            '业余爱好者(对艺术或知识领域涉猎浅薄者)/缺乏专业技术的',
                                            'a person having a superficial interest in an art/ lacking or showing a lack of expert skill',
                                            ["Dilettante watch the scene of bustle, adept guard the entrance. 外行看热闹, 内行看门道 。", "Many dilettante efforts could be seen at the sidewalk art show. 街边艺术展上可以看到很多技术业余的作品"],
                                            ['dabbler', 'amateur', 'nonexpert', 'nonprofessional', 'cognoscente'],
                                            ['authority', 'expert', 'pro', 'professional', 'specialist'])]),
                              Word('diligent', "",
                                   [TestWay('adj',
                                            '勤勉的, 辛勤的',
                                            'characterized by steady, earnest, and energetic effort: painstaking',
                                            ["A new bride is diligent for three days. 新娶媳妇三日勤。", "a student who has been unceasingly diligent in pursuit of a degree in mathematics. 一个不断勤奋追求数学学位的学生"],
                                            ['assiduous', 'industrious', 'sedulous', 'engaged', 'hopping', 'tied-up'],
                                            ['idle', 'inactive', 'unbusy', 'unemployed', 'unoccupied'])]),
                              Word('dilute', "",
                                   [TestWay('v',
                                            '稀释',
                                            'to make thinner or less concentrated by adding a liquid such as water/ of relatively low strength or concentration',
                                            ["dilute a color 稀释色彩", "a dilute acid that's safe to handle in the classroom 稀释了的可以安全在教室处理的酸"],
                                            ['thin'],
                                            ['condense', 'densify', 'concentrate', 'thicken']),
                                    TestWay('vt',
                                            '削弱',
                                            'to diminish the strength, flavor, or brilliance of by admixture',
                                            ["The hiring of the new CEO diluted the power of the company's president. 新的CEO削弱了董事长的权力。"],
                                            ['weaken'],
                                            ['fortify', 'strengthen'])]),
                              Word('diminish', "",
                                   [TestWay('v',
                                            '变小, 减少',
                                            'to become smaller or less',
                                            ["diminish an army's strength 削弱军队力量", "The sound of the train diminished as our distance from it increased. 当我们距离火车的越远时, 火车的声音就越小。"],
                                            ['abate', 'dwindle', 'lessen', 'lower', 'reduce', 'decline'],
                                            ['aggrandize', 'amplify', 'augment', 'boost', 'enlarge', 'escalate', 'expand', 'increase', 'raise', 'balloon']),
                                    TestWay('v',
                                            '轻视, 贬低',
                                            'to lessen the authority, dignity, or reputation of : belittle',
                                            ["diminish a rival's accomplishments 贬低对手的成就"],
                                            ['belittle', 'deprecate', 'depreciate', 'disparage'],
                                            ['acclaim', 'applaud', 'exalt', 'extol', 'glorify', 'laud', 'praise'])]),
                              Word('din', "",
                                   [TestWay('n',
                                            '喧闹声, 嘈杂声',
                                            'a loud continued noise',
                                            ["The din of the engines was deafening. 引擎的嘈杂声震耳欲聋。", "There's always a great din from the cafeteria during lunch. 午餐时间经常从咖啡店里传来很大的喧闹声。"],
                                            ['blare', 'bluster', 'cacophony', 'chatter', 'clamor', 'discordance', 'racket', 'rattle', 'roar'],
                                            ['quiet', 'silence', 'still']),
                                    TestWay('v',
                                            '重复',
                                            'to say or state again',
                                            ["Safety lessons dinned into us over and over. 我们一遍又一遍的进行安全教育。"],
                                            ['iterate', 'rehearse', 'reiterate'])])])

list7_unit4 = VocabularyList([Word('dingy', "",
                                   [TestWay('adj',
                                            '昏暗的, 肮脏的',
                                            'darkened with smoke and grime; dirty or discolored',
                                            ["A dingy room is always Dickensian image of the poor. 一个肮脏而昏暗的房间经常作为狄更斯时代的穷人形象。", "The bed sheets were pretty dingy so we threw them in the laundry pile. 床单太脏了以至于我们把它扔进了脏衣服堆。"],
                                            ['darkened', 'dirty', 'bedraggled', 'bemired', 'besmirched', 'dusty', 'mucky', 'muddy', 'nasty', 'smudged', 'soiled', 'sordid', 'stained', 'sullied'],
                                            ['clean', 'cleanly', 'immaculate', 'spotless', 'stainless', 'unsoiled', 'unstained', 'unsullied'])]),
                              Word('diocesan', "",
                                   [TestWay('adj',
                                            'of or relating to a diocese',
                                            '主教管辖区的',
                                            ["national or diocesan authority 国家或教区权利"],
                                            antonyms = ['ecumenical', '普世的'],
                                            other_form = 'diocese n. 教区: a district under the pastoral care of a bishop in the Christian Church.')]),
                              Word('diplomatic', "",
                                   [TestWay('adj',
                                            '使用策略的, 机智的',
                                            'employing tact and conciliation especially in situations of stress',
                                            ["be very diplomatic with awkward clients 总是有办法对付难缠的顾客"],
                                            ['diplomatic', 'politic'],
                                            ['gauche', 'impolitic', 'tactless', 'undiplomatic', 'untactful'])]),
                              Word('dire', "",
                                   [TestWay('adj',
                                            '不吉利的, 不祥的',
                                            'being or showing a sign of evil or calamity to come',
                                            ["a dire forecast of a plunge in stock prices 股市大跌不祥的预测"],
                                            ['baleful', 'direful', 'foreboding', 'ill-boding', 'inauspicious', 'menacing', 'minatory', 'portentous', 'sinister', 'threatening'],
                                            ['propitious', 'unthreatening']),
                                    TestWay('adj',
                                            '可怕的, 恐怖的',
                                            'causing fear',
                                            ["a series of dire tremors that hinted at a volcanic eruption 一系列暗示火山爆发的恐怖的震动"],
                                            ['alarming', 'direful', 'dread', 'dreadful', 'fearsome', 'forbidding', 'formidable', 'frightening', 'frightful', 'ghastly',  'hair-raising', 'horrendous', 'horrible', 'horrifying', 'intimidating', 'redoubtable', 'scary', 'shocking', 'terrible', 'terrifying']),
                                    TestWay('adj',
                                            '迫切的',
                                            'needing immediate attention; urgent',
                                            ["There is a dire need for food and medicine in the famine-stricken country. 在闹饥荒的国家迫切需要食物和药品。"],
                                            ['immediate', 'burning', 'compelling', 'critical', 'crying', 'emergent', 'exigent', 'imperative', 'imperious', 'importunate', 'instant', 'necessitous', 'pressing', 'urgent'],
                                            ['nonurgent', 'noncritical']),
                                    TestWay('adj',
                                            '悲惨的adj',
                                            'causing or marked by an atmosphere lacking in cheer',
                                            ["With stock prices steadily falling, these are dire days on the trading floor. 股价稳步走低, 交易大厅一片悲惨的景象。"],
                                            ['cheerless', 'chill', 'depressing', 'depressive', 'desolate', 'disconsolate', 'dismal', 'drear', 'dreary', 'funereal', 'glum', 'lugubrious', 'miserable', 'morose', 'saturnine', 'somber', 'sullen', 'sunless', 'wretched'],
                                            ['bright', 'cheerful', 'cheering', 'cheery', 'festive', 'gay', 'sunshiny'])]),
                              Word('dirge', "",
                                   [TestWay('n',
                                            '挽歌',
                                            'a slow, solemn, and mournful piece of music',
                                            ["This funeral dirge is for the dead friend. 这首葬礼挽歌是写给故去的朋友的。"],
                                            ['elegy', 'requiem'])]),
                              Word('disabuse', "",
                                   [TestWay('v',
                                            '打消错误念头, 纠正',
                                            'to free from error, fallacy, or misconception',
                                            ["disabuse sb. of the notion that…打消某人的…观点", "I must disabuse you of your feelings of grandeur.我必须去消除你的傲气。"],
                                            ['disenchant', 'undeceive'],
                                            ['lead into error', 'mislead'])]),
                              Word('disaffected', "",
                                   [TestWay('adj',
                                            '不满的, 叛逆的',
                                            'discontented and resentful especially against authority; rebellious',
                                            ["gangs of disaffected teenagers 一群叛逆的年轻人", "The soldiers were disaffected toward the government. 那些士兵对政府不满."],
                                            ['discontented', 'dissatisfied', 'malcontent', 'rebellious', 'insubordinate', 'contumacious'],
                                            ['satisfied', 'contented'],
                                            'disaffect v. 使不安, 使不满: to fill with discontent and unrest 【近】dissatisfy, agitate, upset 【反】mollify 平息, 抚慰')]),
                              Word('disarm', "",
                                   [TestWay('vi',
                                            '解除武装',
                                            'to give up or reduce armed forces',
                                            ["disarm the captured soldiers 解除被捕士兵的武装", "The defeated nation was disarmed so that it would never again be a threat to international order. 战败国被解除武装, 这样一来它就不会再对国际秩序造成威胁了。"],
                                            ['demilitarize'],
                                            ['arm', 'militarize', 'put on guard']),
                                    TestWay('vt',
                                            '使息怒, 平息抚慰',
                                            'to lessen the anger or agitation of',
                                            ["Her future father-in-law was totally disarmed by her words. 她未来的继父听了她的话彻底没脾气了。"],
                                            ['appease', 'assuage', 'conciliate', 'gentle', 'mollify', 'placate', 'propitiate'],
                                            ['anger', 'enrage', 'incense', 'inflame', 'enflame', 'infuriate', 'ire', 'madden', 'outrage']),
                                    TestWay('v',
                                            '使无害',
                                            'to make harmless',
                                            ["disarm a bomb 拆除炸弹"])]),
                              Word('disarray', "",
                                   [TestWay('n',
                                            '混乱, 无秩序',
                                            'a lack of order or sequence',
                                            ["The room was in disarray. 房间一片混乱。"],
                                            ['confusion', 'disarrangement', 'disorder', 'disorderliness', 'disorganization', 'havoc', 'mess', 'messiness', 'misorder', 'muddle', 'muss', 'shambles', 'jumble', 'welter'],
                                            ['order', 'orderliness']),
                                    TestWay('v',
                                            '使混乱',
                                            'to undo the proper order or arrangement of',
                                            ["Changing offices disarrayed my papers completely. 办公室搬迁, 使我的文件全部乱套了."],
                                            ['confuse', 'disarrange', 'discompose', 'dishevel', 'dislocate', 'disorganize', 'disrupt', 'disturb', 'hash', 'jumble', 'muddle', 'muss', 'rumple', 'scramble', 'upset', 'mess up', 'mix up'],
                                            ['arrange', 'array', 'dispose', 'order', 'organize', 'range', 'regulate', 'straighten up'])]),
                              Word('disavow', "",
                                   [TestWay('vt',
                                            '拒绝承认, 否认',
                                            'to disclaim knowledge of, responsibility for, or association with；to declare not to be true',
                                            ["disavow the rumor 否认谣言", "She disavowed the testimony that she had given earlier in the trial. 她在审判中否认了自己之前的证词。"],
                                            ['deny', 'repudiate', 'disaffirm', 'disclaim', 'disconfirm', 'gainsay', 'negate'],
                                            ['acknowledge', 'avow', 'concede'])])])

list7_unit5 = VocabularyList([Word('discern', "",
                                   [TestWay('vt',
                                            '识别, 辨别差异',
                                            'to perceive with the eyes or intellect; detect',
                                            ["discern the motives 辨识出动机", "too young to discern between right and wrong 太年轻了而辨别不了是非"],
                                            ['behold', 'descry', 'distinguish', 'espy', 'perceive', 'regard', 'differentiate', 'discriminate'],
                                            ['confuse', 'mix up'],
                                            'discerning adj. 有洞察力的, 洞悉的: showing insight and understanding 【例】a very discerning art critic 眼光敏锐有洞察力的艺术评论家; She has a discerning palate. 她的味觉很敏锐。 【近】insightful, incisive 【反】myopic, shortsighted, undiscerning 【派】discernible/discernable adj. 可辨识的, 可辨别的:perceptible 【例】 a discernible mark 可辨别的痕迹 【近】perceptible, detectable, distinguishable 【反】indiscernible, imperceptible 不可辨识的')]),
                              Word('discharge', "",
                                   [TestWay('vt',
                                            '解雇',
                                            'to dismiss from employment',
                                            ["discharge a worker/soldier 开除员工/军籍"],
                                            ['fire', 'dismiss'],
                                            ['employ', 'engage', 'hire', 'take on', 'sign up or on']),
                                    TestWay('n',
                                            '不承担责任',
                                            'a freeing from an obligation or responsibility',
                                            ["a full discharge from responsibility for the accident 对事故完全不负有责任"],
                                            ['delivery', 'quietus', 'quittance']),
                                    TestWay('v',
                                            '释放',
                                            'to set free (as from slavery or confinement)',
                                            ["discharged the prisoners upon the signing of the peace treaty 根据和约释放罪犯"],
                                            ['disenthrall', 'emancipate', 'enfranchise', 'liberate', 'loose', 'manumit', 'release', 'spring', 'unbind', 'uncage', 'unchain', 'unfetter'],
                                            ['bind', 'confine', 'enchain', 'fetter'])]),
                              Word('disciple', "",
                                   [TestWay('n',
                                            '信徒, 追随者',
                                            'one who accepts and assists in spreading the doctrines of another, follower',
                                            ["A circle of dedicated disciples who conscientiously wrote down everything the prophet said. 一圈忠实的信徒认真的记下了先知所说的话。"],
                                            ['acolyte', 'adherent', 'convert', 'epigone', 'partisan', 'votary'],
                                            ['leader', 'coryphaeus'])]),
                              Word('discombobulate', "",
                                   [TestWay('v',
                                            '使不安, 使混乱',
                                            'upset, confuse',
                                            ['invent cool new ways to discombobulate the old order 发明新的好方法打乱了旧秩序'],
                                            ['upset', 'addle', 'baffle', 'bamboozle', 'befog', 'befuddle', 'confound', 'fuddle', 'gravel', 'muddle', 'muddy', 'mystify', 'perplex', 'puzzle', 'vex'],
                                            ['compose', 'soothe', 'calm', 'pacify'])]),
                              Word('discomfit', "",
                                   [TestWay('v',
                                            '使尴尬',
                                            'to put into a state of perplexity and embarrassment',
                                            ["He was discomfited by the awkward situation of having his ex-girlfriend meet his current one. 他的前女友看到他现任女友的情况让他很尴尬。"],
                                            ['embarrass', 'abash', 'faze', 'fluster', 'mortify', 'nonplus', 'rattle']),
                                    TestWay('v',
                                            '阻碍',
                                            'to prevent from achieving a goal',
                                            ["Constant interruptions discomfited her in her attempt to finish the speech. 经常的打断她讲话使她无法完成演讲。"],
                                            ['balk', 'foil', 'thwart', 'baffle', 'checkmate'],
                                            ['advance', 'forward', 'foster', 'further', 'promote', 'encourage'])]),
                              Word('discommode', "",
                                   [TestWay('v',
                                            '打扰, 使不便',
                                            'to cause inconvenience to: trouble',
                                            ["The breakdown of her car didn't discommode her seriously. 车的故障没有给他带来很大麻烦。"],
                                            ['disturb', 'trouble', 'incommode', 'put out'],
                                            ['accommodate', 'assist', 'oblige', 'favor'])]),
                              Word('discompose', "",
                                   [TestWay('vt',
                                            '使不安',
                                            'to disturb the composure or calm of; perturb',
                                            ["GRE does not seem to discompose Jason; on the contrary, he looked rather relaxed. GRE没有使Jason感到慌乱, 正相反, 他看上去很轻松。"],
                                            ['agitate', 'bother', 'discomfort', 'disquiet', 'distemper', 'disconcert', 'disturb', 'perturb', 'upset', 'weird out'],
                                            ['calm', 'compose', 'quiet', 'settle', 'soothe', 'tranquilize']),
                                    TestWay('v',
                                            '使混乱',
                                            'to undo the proper order or arrangement of',
                                            ["The wind ruffled her hair and discomposed her carefully arranged papers. 风凌乱了她的头发, 吹乱了她细心整理的纸张。"],
                                            ['disarrange', 'disarray', 'disorganize'],
                                            ['arrange', 'array', 'order', 'organize', 'range'])]),
                              Word('disconcert', "",
                                   [TestWay('vt',
                                            '使不安',
                                            'to disturb the composure of',
                                            ["We were disconcerted by the unexpected changes to the program. 我们对项目未预料到的变化感到不安。"],
                                            ['abash', 'discomfit', 'disconcert', 'discountenance', 'mortify', 'rattle'],
                                            ['calm', 'compose', 'quiet', 'settle', 'soothe', 'tranquilize'])]),
                              Word('discord', "",
                                   [TestWay('n',
                                            '意见不一致, 不和谐',
                                            'lack of agreement or harmony (as between persons, things, or ideas)',
                                            ['No discord, no concord. 不打不成交。'],
                                            ['conflict', 'disaccord', 'discordance', 'disharmony', 'dissension', 'dissidence', 'dissonance', 'disunion', 'disunity', 'division', 'friction', 'inharmony', 'schism', 'strife'],
                                            ['accord', 'agreement', 'concord', 'harmony', 'peace'],
                                            'discordant adj. 不和谐的, 刺耳的: disagreeable in sound; harsh or dissonant 【近】dissonant, cacophonous, disharmonic, disharmonious')]),
                              Word('discredit', "",
                                   [TestWay('v',
                                            '羞辱, 使丧失名誉',
                                            'to damage in reputation; disgrace.',
                                            ["discredit his opponents 羞辱他的对手"],
                                            ['abase', 'debase', 'degrade', 'demean', 'disgrace', 'dishonor', 'humiliate', 'shame', 'sink', 'smirch', 'take down 【反】concordant, harmonious 和谐的'],
                                            ['aggrandize', 'canonize', 'deify', 'elevate', 'exalt']),
                                    TestWay('v',
                                            '怀疑, 不相信',
                                            'to think not to be true or real',
                                            ["I discredit the story that the old house is haunted. 我怀疑那个房子闹鬼不是真的。"],
                                            ['negate', 'doubt', 'distrust'],
                                            ['accept', 'believe', 'credit', 'confirm', 'prove', 'validate', 'verify'])])])

list7_unit6 = VocabularyList([Word('discrepancy', "",
                                   [TestWay('n',
                                            '(在事实和宣称之间的)差异或矛盾',
                                            'divergence or disagreement, as between facts or claims',
                                            ["a large discrepancy between the ideal image and the reality 理想与现实之间的巨大差距"],
                                            ['contrast', 'disagreement', 'disparity', 'dissimilarity', 'distance', 'distinction', 'diversity'],
                                            ['converge' 'concord consonant', 'analogousness', 'community', 'resemblance', 'similarity'])]),
                              Word('discrete', "",
                                   [TestWay('adj',
                                            '离散的, 不连续的',
                                            'constituting a separate entity',
                                            ["a discrete variable 离散变量"],
                                            ['detached', 'disconnected', 'unattached', 'unconnected', 'separate'],
                                            ['continuous', 'attached', 'connected', 'joined', 'linked'])]),
                              Word('discretion', "",
                                   [TestWay('n',
                                            '谨慎',
                                            'the quality of being discreet; circumspection',
                                            ['You must show discretion in choosing your teammates. 你选择队友时必须慎重。'],
                                            ['discreetness', 'prudence'],
                                            ['imprudence', 'indiscretion'],
                                            'indiscretion n. 不谨慎, 不符合社会道德规范： an act at variance with the accepted morality of a society 【例】resign because of financial indiscretions 因为财政方面的不检点而辞职'),
                                    TestWay('n',
                                            '自制, 节制',
                                            "the checking of one's true feelings and impulses when dealing with others",
                                            ["In that job you'll be expected to show discretion and act like a professional at all times. 那项工作要求你时刻自制节制, 表现得像一个专业人士。"],
                                            ['continence', 'discipline', 'inhibition', 'refrainment', 'restraint', 'self-control', 'self-restraint'],
                                            ['disinhibition', 'incontinence', 'unconstraint'])]),
                              Word('discretionary', "",
                                   [TestWay('adj',
                                            '自主决定的',
                                            "left to discretion : exercised at one's own discretion",
                                            ["In many restaurants, discretionary tipping is being replaced by a standard service charge. 在很多饭店, 标准的服务价格取代了随意支付的小费。"],
                                            ['elective', 'voluntary'],
                                            ['compulsory', 'mandatory', 'nonelective', 'nonvoluntary', 'obligatory', 'required'])]),
                              Word('discriminate', "",
                                   [TestWay('vt',
                                            '区分',
                                            'to perceive the distinguishing features of; recognize as distinct',
                                            ["discriminate different kinds of animals 区分不同的动物"],
                                            ['differentiate', 'discern', 'distinguish'],
                                            ['confuse', 'mistake', 'mix up']),
                                    TestWay('vi',
                                            '歧视',
                                            'to make a difference in treatment or favor on a basis other than individual merit',
                                            ["The new law discriminated against lower-paid workers. 这条新法律歧视低工资的工人。"],
                                            other_form = 'discriminatory adj. 差别对待的： marked by or showing prejudice; biased 【近】prejudiced, biased 【反】equitable, impartial, unbiased, impersonal, unprejudiced 公平的')]),
                              Word('discursive', "",
                                   [TestWay('adj',
                                            '(谈话内容)杂乱的',
                                            'moving from topic to topic without order',
                                            ["a long, discursive article 冗长杂乱的文章", "The speaker's discursive style made it difficult to understand his point. 演讲者讲话杂乱, 很难让人理解他的观点。"],
                                            ['desultory', 'digressional', 'excursive', 'meandering', 'rambling', 'wandering'],
                                            ['keen on title', 'concentrated'])]),
                              Word('disdain', "",
                                   [TestWay('v',
                                            '轻视, 鄙视',
                                            'to look on with scorn',
                                            ['disdain that man for snobbishness 鄙视那个势利小人'],
                                            ['contemn', 'disrespect', 'slight', 'sniff', 'snub', 'look down'],
                                            ['honor', 'respect', 'treat favorably'])]),
                              Word('disengage', "",
                                   [TestWay('vt',
                                            '分开',
                                            'to set free from entanglement or difficulty',
                                            ["Disengage the gears when you park the car. 当你停车的时候要把(传动)齿轮分开。", "seek to disengage myself from the embarrassing situation 试图把我自己从尴尬的气氛中解救出来"],
                                            ['disengage', 'disentangle', 'untangle'],
                                            ['embroil', 'entangle', 'mesh'])]),
                              Word('disgorge', "",
                                   [TestWay('v',
                                            '呕吐出',
                                            'to discharge by the throat and mouth; vomit',
                                            ["He cannot disgorge a fish bone without the doctor’s assistant. 没有医生的帮助他吐不出鱼刺来。", "The volcano disgorged lava. 火山喷出岩浆。"],
                                            ['belch', 'disgorge', 'eject', 'eruct', 'expel', 'jet', 'spew', 'spout'],
                                            ['swallow', 'ingest']),
                                    TestWay('v',
                                            '放弃',
                                            'to give up on request or under pressure',
                                            ["The corrupt officials refused to disgorge his ill-gotten gains. 贪官们拒绝放弃赃款。"])]),
                              Word('disgruntle', "",
                                   [TestWay('vt',
                                            '使发怒, 使不满意',
                                            'to make ill-humored or discontented',
                                            ["be disgruntled with sb 对某人不满"],
                                            ['disaffect', 'displease', 'dissatisfy', 'disgruntle'],
                                            ['content', 'gratify', 'please', 'satisfy']),
                                    TestWay('v',
                                            '使疏远, 使不友好',
                                            'to cause to change from friendly or loving to unfriendly or uncaring',
                                            ['alien', 'alienate'],
                                            ['reconcile'])])])

list7_unit7 = VocabularyList([Word('disguise', "",
                                   [TestWay('v',
                                            '伪装(防止被认出)',
                                            'to modify the manner or appearance of in order to prevent recognition',
                                            ["He always disguises his true feelings. 他经常掩饰自己的真实感受。"],
                                            ['camouflage', 'costume', 'mask'],
                                            ['unmask']),
                                    TestWay('v',
                                            '隐藏',
                                            'to keep secret or shut off from view',
                                            ["That investigative reporter usually does a good job of disguising her true motives for interviewing a person. 当采访时, 那个调查记者经常很好地隐藏自己的真实目的"],
                                            ['belie', 'blanket', 'conceal', 'cover', 'curtain', 'occult', 'veil'],
                                            ['bare', 'disclose', 'display', 'divulge', 'expose', 'reveal', 'show', 'uncover', 'unmask', 'unveil'])]),
                              Word('disinclination', "",
                                   [TestWay('n',
                                            '不喜欢, 厌恶, 不情愿',
                                            'a lack of willingness or desire to do or accept something；a lack of willingness or desire to do or accept something',
                                            ["showing a marked disinclination 表现出明显的不情愿"],
                                            ['aversion', 'disfavor', 'disliking', 'disrelish', 'mislike', 'unwillingness'],
                                            ['appetite', 'favor', 'fondness', 'liking', 'partiality', 'preference', 'relish', 'inclination', 'willingness'])]),
                              Word('disinfect', "",
                                   [TestWay('vt',
                                            '消毒, 使无菌',
                                            'to free from infection especially by destroying harmful microorganisms',
                                            ["disinfect with bleaching powder 用漂白粉消毒"],
                                            ['sterilize'],
                                            ['infect', 'pollute', 'contaminate', 'taint'])]),
                              Word('disjointed', "",
                                   [TestWay('adj',
                                            '机能失调的',
                                            'being thrown out of orderly function',
                                            ["a disjointed society 混乱的社会"],
                                            ['chaotic', 'disorderly'],
                                            ['orderly', 'regular', 'systematic']),
                                    TestWay('adj',
                                            '不连贯的',
                                            'not clearly or logically connected',
                                            ["a disjointed speech about a hodgepodge of things 关于一大堆杂事的不连贯的演讲"],
                                            ['disconnected', 'unconnected'],
                                            ['coherent', 'connected'])]),
                              Word('disinter', "",
                                   [TestWay('v',
                                            '(从墓地里)掘出',
                                            'to take out of the grave or tomb',
                                            ["The Egyptian mummy was carefully disinterred in hopes that it would yield secrets about the Old Kingdom. 那个埃及木乃伊被小心地挖掘出来, 人们希望它可以告诉我们关于这个古老王国的一些秘密。"],
                                            ['unbury', 'unearth'],
                                            ['bury', 'inter', 'tomb', 'inhume'])]),
                              Word('disinterested', "",
                                   [TestWay('adj',
                                            '公正的, 无偏见的',
                                            'free from selfish motive or interest: unbiased',
                                            ["a disinterested decision 公正的决定"],
                                            ['equal', 'evenhanded', 'impartial', 'just', 'nonpartisan', 'dispassionate', 'objective', 'square', 'unbiased', 'unprejudiced'],
                                            ['biased', 'inequitable', 'nonobjective', 'one-sided', 'partial', 'partisan', 'prejudiced', 'unjust']),
                                    TestWay('adj',
                                            '没有兴趣的',
                                            'having or showing a lack of interest or concern',
                                            ["The city's philistines, naturally disinterested in art, voted to cut the museum's budget. 城市里对艺术本来就不感兴趣的俗人们, 投票表决要缩进博物馆的预算。"],
                                            ['apathetic', 'incurious', 'insouciant', 'nonchalant', 'perfunctory', 'unconcerned'],
                                            ['concerned', 'interested'])]),
                              Word('disjunctive', "",
                                   [TestWay('adj',
                                            '分离的',
                                            'marked by breaks or disunity',
                                            ["a disjunctive narrative sequence 分散的叙述顺序"],
                                            ['discrete', 'separate', 'disconnected', 'disunited'],
                                            ['combined', 'connected', 'jointed', 'mixed', 'united'])]),
                              Word('dismantle', "",
                                   [TestWay('vt',
                                            '分解, 分拆',
                                            'to take to pieces also : to destroy the integrity or functioning of',
                                            ["dismantle a machine 分拆机器"],
                                            ['break down', 'knock down'],
                                            ['assemble', 'construct'])]),
                              Word('dismay', "",
                                   [TestWay('v',
                                            '使失去勇气',
                                            'to cause to lose courage or resolution',
                                            ["The excessive homework dismayed ourselves. 过量的作业让我们失去了信心。"],
                                            ['chill', 'daunt', 'dishearten', 'dispirit', 'frustrate', 'unnerve'],
                                            ['embolden', 'encourage', 'hearten', 'nerve']),
                                    TestWay('v',
                                            '使不安, 使焦虑',
                                            'to trouble the mind of; to make uneasy',
                                            ["Parents became increasingly dismayed by their son's GPA. 父母对他们儿子的平均成绩非常焦虑。"],
                                            ['agitate', 'bother', 'discomfort', 'discompose', 'disquiet', 'distemper', 'distress', 'perturb', 'unsettle', 'upset'],
                                            ['calm', 'compose', 'quiet', 'soothe', 'tranquilize'])]),
                              Word('disparage', "",
                                   [TestWay('vt',
                                            '贬低, 轻蔑地说',
                                            'to lower in rank or reputation; to speak of in a slighting or disrespectful way; belittle',
                                            ["use the past to disparage the present 借古讽今", "Voters don't like political advertisements in which opponents disparage one another.选民不喜欢看到贬低竞争对手的政治广告。"],
                                            ['belittle', 'denigrate', 'deprecate', 'depreciate', 'derogate', 'degrade'],
                                            ['acclaim', 'applaud', 'exalt', 'extol', 'glorify', 'laud'])])])

list7_unit8 = VocabularyList([Word('disparate', "",
                                   [TestWay('adj',
                                            '迥然不同的',
                                            'fundamentally distinct or different in kind; entirely dissimilar',
                                            ["This couple of seemingly disparate topics have something in common. 这两个看似无关的主题其实有些相同之处。"],
                                            ['dissimilar', 'distinct', 'distinguishable', 'diverse', 'nonidentical', 'unalike'],
                                            ['alike', 'identical', 'indistinguishable', 'kindred', 'like', 'parallel', 'same', 'similar'])]),
                              Word('dispassionate', "",
                                   [TestWay('adj',
                                            '客观公正的, 不易被情绪或偏见影响的',
                                            'devoid of or unaffected by passion, emotion, or bias',
                                            ["Journalists should aim to be dispassionate observers. 记者们应该朝着成为一个公正的观察者努力。"],
                                            ['disinterested', 'equal', 'equitable', 'evenhanded', 'impartial', 'just', 'nonpartisan', 'objective', 'unbiased', 'unprejudiced'],
                                            ['biased', 'inequitable', 'nonobjective', 'one-sided', 'partial', 'partisan', 'prejudiced', 'unjust'])]),
                              Word('dispatch', "",
                                   [TestWay('n',
                                            '迅速',
                                            'promptness and efficiency in performance or transmission',
                                            ["do sth. with dispatch 迅速的做某事"],
                                            ['alacrity', 'haste', 'swiftness', 'expedition', 'promptitude'],
                                            ['leisureliness', 'delay', 'procrastination']),
                                    TestWay('v',
                                            '发送, 运输',
                                            'to cause to go or be taken from one place to another',
                                            ["to dispatch a messenger with urgent news 发送一个紧急消息"],
                                            ['transfer', 'transmit', 'transport', 'pack off'],
                                            ['accept', 'receive']),
                                    TestWay('v',
                                            '使死亡',
                                            'to deprive of life',
                                            ["dispatch a criminal 处决罪犯|| The man dispatched the termites with professional efficiency. 那个男人技术纯熟地杀死了白蚁。"],
                                            antonyms = ['animate']),
                                    TestWay('v',
                                            '获胜',
                                            'to achieve a victory over',
                                            ["They dispatched the other team with breaking a sweat. 他们险胜其他的队。"],
                                            ['conquer', 'defeat', 'subdue', 'triumph over', 'prevail over'],
                                            ['lose to'])]),
                              Word('dispose', "",
                                   [TestWay('',
                                            '使倾向',
                                            'to give a tendency to: incline',
                                            ["faulty diet disposes one to sickness 营养不全面导致疾病"],
                                            other_form = 'disposed adj. 喜欢的: willing or likely, inclined 【例】not feel disposed to argue with her 不喜欢与她争执 【近】willing, inclined, predisposed, prone 【反】disinclined, indisposed 不喜欢的'),
                                    TestWay('vi',
                                            '处理掉(与 of 连用, dispose of)',
                                            'to get rid of; throw out',
                                            other_form = 'disposal n. 处理, 不再利用: the act of getting rid of something that is no longer wanted or needed 【例】the permanent disposal of radioactive wastes 对放射性废物的永久处理'),
                                    TestWay('v',
                                            '布置有序',
                                            'to place, distribute, or arrange especially in an orderly way',
                                            ["Dispose the surgical instruments in the exact order in which they would be needed. 把手术仪器按他们被需要的顺序放置。"],
                                            ['array', 'arrange'],
                                            ['disarrange', 'disarray', 'disorder', 'upset', 'mess up', 'muss up'])]),
                              Word('disregard', "",
                                   [TestWay('v',
                                            '漠视, 不关注',
                                            'to pay no attention to',
                                            ["disregard the advice of his executives 漠视执行管理者的建议"],
                                            ['ignore', 'overlook', 'slight'],
                                            ['heed', 'mind', 'regard', 'attend to']),
                                    TestWay('n',
                                            '缺乏兴趣, 缺乏关心',
                                            'lack of interest or concern',
                                            [" Revelers fired guns in the air with complete disregard for the possible consequences. 饮酒狂欢者一点也不关心后果的开枪"],
                                            ['apathy', 'disinterestedness', 'incuriosity', 'nonchalance', 'torpor', 'unconcern'],
                                            ['concern', 'interest', 'regard'])]),
                              Word('dissect', "",
                                   [TestWay('vt',
                                            '仔细分析',
                                            'to examine, analyze, or criticize in minute detail',
                                            ["dissect some basic problems in mathematics analysis 仔细分析一些数学分析的基本问题", "let's dissect the plot of this thriller to see what makes it thrilling. 让我们来仔细分析一下这个恐怖电影为什么恐怖。"],
                                            synonyms = ['analyze']),
                                    TestWay('vt',
                                            '切成片(尤其是为了解剖研究)',
                                            'to cut apart or separate (tissue), especially for anatomical study',
                                            ["dissect the brain of Einstein 解剖爱因斯坦的大脑"],
                                            ['anatomize', 'assay', 'break down'])]),
                              Word('dissemble', "",
                                   [TestWay('v',
                                            '用假象隐藏真相, 掩饰',
                                            'to put on a false appearance',
                                            ["dissemble fear with a smile 用微笑来掩饰恐惧", "He dissembled happiness at the news that his ex-girlfriend was getting married to someone else. 他对其他人假装高兴听到前女友结婚的消息。"],
                                            ['dissimulate', 'affect', 'assume', 'bluff', 'counterfeit', 'fake', 'sham'],
                                            ['behave honestly'])]),
                              Word('disseminate', "",
                                   [TestWay('v',
                                            '散播, 传播',
                                            'to spread abroad; promulgate',
                                            ["disseminate Marxism-Leninism 传播马列主义", "The Internet allows us to disseminate information faster. 互联网允许我们更快的传播信息"],
                                            ['broadcast', 'circulate', 'propagate'],
                                            ['gather', 'amass', 'garner'])]),
                              Word('dissension', "",
                                   [TestWay('n',
                                            '意见不合',
                                            'difference of opinion; disagreement',
                                            ["Although we have dissension, we are friend all the same. 虽然我们意见不和, 但我们还是朋友。", "There is a continued dissension among historians on the exact spot of Columbus's first landing. 关于哥伦布第一次的准确登陆地点这个问题, 总是存在分歧。"],
                                            ['conflict', 'disaccord', 'discordance', 'discordancy', 'disharmony', 'dissent', 'dissidence', 'dissonance', 'disunion', 'disunity', 'division', 'friction', 'inharmony', 'schism', 'strife'],
                                            ['accord', 'agreement', 'concord', 'concordance', 'harmony', 'consensus', 'unanimity'])]),
                              Word('dissent', "",
                                   [TestWay('v',
                                            '持异议, 不同意',
                                            'to differ in opinion',
                                            ["I dissent from what you said. 我不同意你说的话。", "Anyone who dissented was encouraged to speak out while they had the chance. 谁有异议得到机会都可以发言。"],
                                            ['differ', 'disagree', 'nonconcur'],
                                            ['agree', 'assent', 'concur']),
                                    TestWay('n',
                                            '反对正统',
                                            'departure from a generally accepted theory, opinion, or practice',
                                            ["The church reacted to any form of dissent by promptly excommunicating its proponents. 教堂会立即开除任何反对正统教义的人。"],
                                            ['heterodoxy', 'nonconformity'],
                                            ['conformity', 'orthodoxy' ]),
                                    TestWay('n',
                                            '不和谐',
                                            'a lack of agreement or harmony',
                                            synonyms = ['conflict', 'disaccord', 'discordance', 'discordancy', 'disharmony', 'dissent', 'dissidence', 'dissonance', 'disunion', 'disunity', 'division', 'friction', 'inharmony', 'schism', 'strife'],
                                            antonyms = ['accord', 'agreement', 'concord', 'concordance', 'harmony', 'consensus', 'unanimity'])])])

list7_unit9 = VocabularyList([Word('dissipate', "",
                                   [TestWay('vt',
                                            '驱散',
                                            'to drive away; disperse.',
                                            ["The wind finally dissipated the smoke. 风终于吹散了雾气。"],
                                            ['disband', 'dispel', 'disperse', 'scatter'],
                                            ['accumulate', 'gather', 'amass', 'cluster', 'assemble', 'concentrate', 'congregate']),
                                    TestWay('vt',
                                            '浪费',
                                            'to spend or expend intemperately or wastefully: squander',
                                            ["dissipate too much time and effort 挥霍了太多的时间与精力"],
                                            ['waste', 'squander', 'lavish'],
                                            ['conserve']),
                                    TestWay('vi',
                                            '放纵',
                                            'to indulge in the intemperate pursuit of pleasure, especially : to drink to excess',
                                            synonyms = ['indulge'])]),
                              Word('dissolute', "",
                                   [TestWay('adj',
                                            '放荡的, 无节制的',
                                            'lacking moral restraint; indulging in sensual pleasures or vices.',
                                            ["lead a dissolute life 过着放荡无节制的生活"],
                                            ['dissipated', 'libertine', 'rakish', 'reprobate'],
                                            ['abstinent', 'abstemious', 'temperate', 'ascetic', 'stoic', 'spartan', 'self-denying', 'pure', 'uncorrupt', 'uncorrupted'])]),
                              Word('dissolve', "",
                                   [TestWay('v',
                                            '溶解, 融化',
                                            'to cause to pass into solution: to reduce (solid matter) to liquid form; melt',
                                            ["Sugar dissolves in the water. 糖在水中溶解"],
                                            ['liquefy', 'melt'],
                                            ['coagulate', 'solidify', 'freeze']),
                                    TestWay('vt',
                                            '解散',
                                            'to break into component parts; disintegrate',
                                            synonyms = ['disintegrate', 'disband', 'break up'],
                                            antonyms = ['consolidate', 'unify']),
                                    TestWay('v',
                                            '消失',
                                            'to cease to be visible; to cease to exist',
                                            ['The mist dissolved in the morning sun. 雾消失在朝阳中。'],
                                            ['dematerialize', 'vanish'],
                                            ['appear', 'materialize']),
                                    TestWay('v',
                                            '废除, 撤销',
                                            'to put an end to by formal action',
                                            ["The king dissolved parliament. 国王废除了议会"],
                                            ['terminate', 'abrogate', 'annul', 'cancel', 'disannul', 'invalidate', 'negate', 'null', 'nullify', 'repeal', 'rescind'])]),
                              Word('dissonance', "",
                                   [TestWay('n',
                                            '不和谐, 刺耳',
                                            'a harsh, disagreeable combination of sounds; discord',
                                            ["cognitive dissonance 认识上的分歧", "Dissonance among the three partners doomed the project. 三 个股东间的不调和注定了那计划的失败。"],
                                            ['conflict', 'disaccord', 'discordance', 'discordancy', 'disharmony', 'dissent', 'dissidence', 'dissonance', 'disunion', 'disunity', 'division', 'friction', 'inharmony', 'schism', 'strife'],
                                            ['accord', 'agreement', 'concord', 'concordance', 'harmony', 'consensus', 'unanimity'])]),
                              Word('dissuade', "",
                                   [TestWay('vt',
                                            '劝阻,反对',
                                            'to deter (a person) from a course of action or a purpose by persuasion or exhortation',
                                            ["dissuade sb. from (doing) sth 劝阻/反对 人做 事", "Her parents tried to dissuade her from her intention to drop out of college. 她的父母劝她不要退学。"],
                                            ['deter', 'dissuade', 'inhibit'],
                                            ['encourage', 'persuade'])]),
                              Word('distain', "",
                                   [TestWay('v',
                                            '贬损, 伤害名誉',
                                            'loss of honor, respect, or reputation',
                                            ['dishonor', 'belittle', 'denigrate', 'deprecate', 'depreciate', 'degrade'],
                                            ['praise', 'acclaim', 'applaud', 'exalt', 'extol', 'glorify', 'laud']),
                                    TestWay('v',
                                            '弄脏',
                                            'to make dirty',
                                            ["hands distained with blood 被血弄脏的手"],
                                            ['bemire', 'besmirch', 'daub', 'muddy', 'smirch', 'smudge', 'soil', 'stain', 'sully'],
                                            ['clean'])]),
                              Word('distal', "",
                                   [TestWay('adj',
                                            '远离中心的, (神经)末梢的',
                                            'situated away from the point of attachment or origin or a central point',
                                            ["the distal end of nerve 神经末梢"],
                                            antonyms = ['proximal'])]),
                              Word('distend', "",
                                   [TestWay('v',
                                            '膨胀',
                                            'to swell out or expand from or as if from internal pressure',
                                            ["The stomachs of starving people often distend. 饥民的肚子经常涨起来。"],
                                            ['expand', 'dilate', 'inflate', 'swell'],
                                            ['constrict', 'compress'])]),
                              Word('distill', "",
                                   [TestWay('vt',
                                            '用蒸馏法 高纯度',
                                            'to increase the concentration of, separate, or purify by or as if by distillation',
                                            ["distill the water before pouring it in the steam iron 在把水倒到熨斗里前蒸馏一下"],
                                            ['purify', 'filter', 'refine', 'fine'],
                                            other_form = 'distillate n. 蒸馏物, 纯化物, 本质: a purified form; an essence'),
                                    TestWay('v',
                                            '渗出;滴下',
                                            'to fall or let fall in or as if in drops',
                                            ["The basement walls distill water every time it rains heavily. 地下室的墙壁每次下大雨都渗出水来。"],
                                            ['distill', 'dribble', 'drop', 'trickle'])]),
                              Word('distort', "",
                                   [TestWay('vt',
                                            '扭曲, 歪曲',
                                            'to twist out of the true meaning or proportion',
                                            [" A painter may exaggerate or distort shapes and forms. 画家可能夸张或扭曲形状。", "The coach's message was so distorted after passing through so many people that it was unintelligible. 教练的信息在经过许多人传递后 已经被歪曲的很难看懂了。"],
                                            ['deform', 'misshape', 'torture', 'falsify', 'misinterpret', 'misrepresent', 'pervert', 'twist'])])])

list7_unit10 = VocabularyList([Word('distract', "",
                                   [TestWay('vt',
                                            '转移兴趣, 使分心',
                                            "to draw or direct (as one's attention) to a different object",
                                            ["be distracted by a sudden noise 被突然的噪音分心"],
                                            ['abstract', 'divert', 'detract', 'call off'],
                                            other_form = 'distracted adj. 精力分散的 【反】rapt 全心投入的'),
                                    TestWay('vt',
                                            '使焦虑, 使不安',
                                            'to trouble the mind of; to make uneasy',
                                            ["The students are easily distracted before the exam. 学生们在考试前很容易焦虑不安。"],
                                            ['agitate', 'bother', 'discomfort', 'discompose', 'dismay', 'disquiet', 'distress', 'perturb', 'upset'],
                                            ['calm', 'compose', 'quiet', 'soothe', 'tranquilize']),
                                    TestWay('adj',
                                            '疯狂的',
                                            'insane, mad',
                                            synonyms = ['insane', 'delirious', 'hysterical'])]),
                              Word('distraught', "",
                                   [TestWay('adj',
                                            '精神狂乱的, 极疯狂的',
                                            'deeply agitated, as from emotional conflict; insane',
                                            ["Her distraught mother had spent all night waiting by the phone. 她母亲忧心如焚, 在电话旁守了一个晚上。"],
                                            ['agitated', 'delirious', 'distracted', 'frenzied', 'hysterical'],
                                            ['collected', 'composed', 'recollected', 'self-collected', 'self-composed', 'self-possessed'])]),
                              Word('diurnal', "",
                                   [TestWay('adj',
                                            '白天发生或行动的',
                                            'occurring or active during the daytime rather than at night',
                                            ["diurnal animals 昼行性动物"],
                                            antonyms = ['nocturnal']),
                                    TestWay('adj',
                                            '每天的',
                                            'occurring, done, produced, or appearing every day',
                                            ["a love as constant and certain as the diurnal tides 像每天潮汐一样始终如一的爱情"],
                                            synonyms = ['daily', 'day-to-day']),
                                    TestWay('adj',
                                            '期刊',
                                            'a publication that appears at regular intervals',
                                            ["A microfilm contains a collection of diurnals. 一个微缩胶片里包含很多期刊的合集。"],
                                            ['bulletin', 'magazine', 'periodical', 'review', 'serial', 'journal'])]),
                              Word('diverge', "",
                                   [TestWay('v',
                                            '改变方向',
                                            "to change one's course or direction",
                                            ["The deer abruptly diverged from its intended path the moment it spied the waiting lion. 当那只鹿发现潜伏的狮子的时候就突然改变了自己原来的路线"],
                                            ['detour', 'deviate', 'diverge', 'sheer', 'swerve', 'turn off']),
                                    TestWay('vt',
                                            '散开',
                                            'to go or move in different directions from a central point',
                                            ["At that point the road and the railroad tracks diverge. 公路和铁路在那个点分叉了。"],
                                            ['branch out', 'divide', 'spread'],
                                            ['converge', 'join']),
                                    TestWay('v',
                                            '分歧',
                                            'to become or be different in character or form: differ in opinion',
                                            synonyms = ['differ', 'disagree'],
                                            antonyms = ['conform']),
                                    TestWay('vt',
                                            '离题',
                                            'to depart from a set course or norm; deviate',
                                            synonyms = ['excurse', 'ramble', 'diverge', 'get off the subject'])]),
                              Word('diversity', "",
                                   [TestWay('n',
                                            '多样性',
                                            'variety or multiformity',
                                            ["the diversity of species 物种的多样性"],
                                            ['diverseness', 'multifariousness', 'multiplicity', 'variousness', 'miscellaneousness']),
                                    TestWay('n',
                                            '分歧, 不同点',
                                            'the quality or state of being different',
                                            ["There is no fundamental diversity between the two ideologies. 这两种思想意识之间并没有根本的分歧。"],
                                            ['contrast', 'disagreement', 'discrepancy', 'disparateness', 'disparity', 'dissimilarity', 'dissimilitude', 'distinction', 'otherness', 'unlikeness'],
                                            ['alikeness', 'analogy', 'likeness', 'resemblance', 'sameness', 'similarity'])]),
                              Word('divert', "",
                                   [TestWay('vt',
                                            '使转向',
                                            'to turn from one course or use to another: deflect',
                                            ["divert traffic to a side street 使交通转至辅路"],
                                            ['deflect', 'redirect', 'swing', 'veer', 'wheel'],
                                            ['fix', 'set', 'settle']),
                                    TestWay('v',
                                            '使消遣',
                                            'to cause (someone) to pass the time agreeably occupied',
                                            ["A light comedy divert the tired business executive 一个轻松的喜剧让疲惫的企业主管人员得到了放松。"],
                                            ['disport', 'entertain', 'regale', 'solace']),
                                    TestWay('v',
                                            '使分心',
                                            'to draw the attention or mind to something else',
                                            ["divert one’s attention 转移 人注意力", "The parents tried to divert the child with a toy while the doctor was giving her a shot. 当医生要给那个孩子打针的时候, 孩子父母试图用玩具转移孩子的注意力。"],
                                            ['abstract', 'detract', 'call off'])]),
                              Word('divestiture', "",
                                   [TestWay('n',
                                            '剥夺',
                                            'the act of taking away from a person',
                                            ["Melodramas were popular because they offered the audience a divestiture of neutrality. 情节剧之所有受到欢迎是因为他们给观众一个缺乏中立的(世界)。"],
                                            ['deprivation', 'dispossession'],
                                            ['acquisition', 'endowment'])]),
                              Word('divulge', "",
                                   [TestWay('vt',
                                            '泄漏(秘密)',
                                            'to make known (as a confidence or secret)',
                                            ["refuse to divulge details of the negotiations 拒绝透露谈判的细节内容", "We tried to make him divulge the name of the winner, but he wouldn't budge. 我们试图让他透露胜利者的名字, 但是他没有那样做。"],
                                            ['bare', 'disclose', 'discover', 'expose', 'uncover', 'unmask', 'unveil'],
                                            ['conceal', 'cover up', 'hide', 'mask', 'shroud', 'veil'])]),
                              Word('dodder', "",
                                   [TestWay('vi',
                                            '蹒跚, 颤巍巍地行进',
                                            'to progress feebly and unsteadily',
                                            ["He could only dodder along after the operation. 他手术后只能步履蹒跚的走。"],
                                            ['careen', 'lurch', 'teeter', 'totter', 'waddle'])]),
                              Word('dodge', "",
                                   [TestWay('v',
                                            '躲避',
                                            'to avoid (a blow, for example) by moving or shifting quickly aside',
                                            ["dodge a storm of bullets 躲避枪林弹雨", "He dodged the first punch but was hit by the second. 他躲过了第一次打击但是没有躲过第二次。"],
                                            ['avoid', 'escape', 'shirk', 'malinger', 'goldbrick', 'evade', 'parry', 'sidestep', 'circumvent', 'fence', 'hedge', 'avert', 'elude', 'shun', 'skirt', 'bilk', 'eschew', 'weasel'])])])

LIST7 = VocabularyList(list7_unit1.words+list7_unit2.words+list7_unit3.words+list7_unit4.words+list7_unit5.words+list7_unit6.words+list7_unit7.words+list7_unit8.words+list7_unit9.words+list7_unit10.words)
