#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list28_unit1 = VocabularyList([Word('ravenous', "",
                                   [TestWay('adj',
                                            '食量大的, 贪食的',
                                            'having a huge appetite',
                                            ["He had moderated his ravenous appetite. 他克制了自己的食欲。", "ravenous for power 渴望权力"],
                                            'edacious, esurient, gluttonous, greedy, rapacious, voracious',
                                            'content, sated, satiated, satisfied')]),
                              Word('simile', "",
                                   [TestWay('n',
                                            '明喻',
                                            'a figure of speech comparing two unlike things that is often introduced by like or as',
                                            ['Even though both similes and metaphors are forms of comparison, similes indirectly compare the two ideas and allow them to remain distinct in spite of their similarities, whereas metaphors compare two things directly. For instance, a simile that compares a person with a bullet would go as follows: "Chris was a record-setting runner as fast as a speeding bullet." A metaphor might read something like, "When Chris ran, he was a speeding bullet racing along the track." 尽管明喻和暗喻都是比喻的手法, 明喻会间接地对两个对象进行比较, 同时允许差异的存在, 而暗喻则直接对两者进行比较。比如说, 用明喻来把一个人比作子弹会这样说: “克里斯是一个不断打破记录的选手, 他跑得就和高速子弹一样快。”而暗喻可能会说: “当克里斯奔跑的时候, 他就是一颗在赛场上高速飞行的子弹。”'],
                                            antonyms = 'metaphor')]),
                              Word('shift', "",
                                   [TestWay('vt',
                                            '改变…的位置',
                                            'to change the place or position of',
                                            ["She shifted the vase closer to the wall so that it wouldn't get knocked over. 她把花瓶靠墙挪动了一点, 从而防止它被碰倒。"],
                                            'budge, dislocate, displace, disturb, relocate, remove, reposition, transfer, transpose',
                                            'anchor, fix, freeze, secure, set'),
                                    TestWay('vi',
                                            '改变, 变化',
                                            'to pass from one form, state, or level to another',
                                            ["She watched the aurora in fascination as its colors shifted from green to blue. 她着迷地看着极光的色彩从绿变成蓝。"],
                                            'fluctuate, mutate, snap, vary',
                                            'plateau, stabilize'),
                                    TestWay('vt',
                                            '交换',
                                            'to give up (something) and take something else in return',
                                            ["My father and I shifted seats just before takeoff so that I could sit by the window. 起飞前我和我父亲交换了座位, 这样我就可以靠窗坐了。"],
                                            'commute, exchange, shift, substitute, swap, switch, trade')]),
                              Word('damn', "",
                                   [TestWay('vt',
                                            '(在道德上)谴责',
                                            'to declare to be morally wrong or evil',
                                            ["a cleric who damned gambling and strong drink 一个严厉谴责赌博和酗酒的牧师"],
                                            'anathematize, censure, decry, denounce, execrate, reprehend, reprobate',
                                            'bless, eulogize, exalt, extol, glorify, laud, praise'),
                                    TestWay('adv',
                                            '非常地, 极其地',
                                            'to a great degree',
                                            ["Let's have a damn good party. 让我们尽情享乐狂欢吧。"],
                                            'deadly, desperately, exceedingly, extremely, greatly, heavily, highly, incredibly, really, seriously, very',
                                            'little, negligibly, nominally, slightly, somewhat')]),
                              Word('nirvana', "",
                                   [TestWay('n',
                                            '彻底放松的状态',
                                            "a state of being disregardful or unconscious of one's surroundings, concerns, or obligations",
                                            ["The spa experience was a week of pure nirvana. 去泡温泉水疗的经历真是彻底的放松。"],
                                            'forgetfulness, obliviousness',
                                            'alertness, awareness, cognizance, consciousness'),
                                    TestWay('n',
                                            '天堂, 极乐世界',
                                            'an often imaginary place or state of utter perfection and happiness',
                                            ["They believe in a continuous cycle of births and deaths until the soul is perfected and achieves nirvana. 他们相信生命会不断轮回, 直到灵魂变得完美并升入天堂。"],
                                            'empyrean, fantasyland, heaven, lotusland, utopia',
                                            'hell, inferno')]),
                              Word('nourish', "",
                                   [TestWay('vt',
                                            '养育, 抚养',
                                            'to provide with food or other substances necessary for life and growth',
                                            ["He willingly nourished a child that was not his own. 他主动地抚养了一名不是他亲生的孩子。"],
                                            'breed, foster, nurse, nurture, raise, rear'),
                                    TestWay('vt',
                                            '培养, 促进',
                                            'to help the growth or development of',
                                            ["a friendship nourished by trust 在信任的基础之上开出的友谊之花"],
                                            'advance, cultivate, encourage, forward, further, incubate, promote',
                                            'discourage, frustrate, hinder, inhibit')]),
                              Word('plodder', "",
                                   [TestWay('n',
                                            '行走缓慢的人',
                                            'someone who moves slowly or more slowly than others',
                                            ["The guide halted the tour group so that the plodders who had fallen behind could catch up. 导游让队伍停下来, 以便那些落在后头的行动缓慢的人可以跟上。"],
                                            'crawler, dallier, dawdler, dragger, laggard, lagger, lingerer, loiterer, snail, straggler',
                                            'speedster')]),
                              Word('misapprehension', "",
                                   [TestWay('n',
                                            '错误的理解',
                                            'a failure to understand correctly',
                                            ["tried to eliminate all misapprehensions about the planned riverfront development 尽可能消除所有关于河流沿岸发展计划的误解"],
                                            'incomprehension, misconstruction, misconstruing, misimpression, misinterpretation, misknowledge, misreading, misunderstanding'),
                                    TestWay('n',
                                            '错误的判断',
                                            'a wrong judgement',
                                            ["a common misapprehension about how our language functions 有关我们的语言如何运作的常见误判"],
                                            'miscalculation, misjudging, misjudgment, misstep, slip, slipup')]),
                              Word('ferocious', "",
                                   [TestWay('adj',
                                            '极端的, 剧烈的',
                                            'marked by unrelenting intensity',
                                            ["Ferocious heat wave kept people indoor. 剧烈的热浪使人不能出门。"],
                                            'dreadful, excruciating, explosive, fearsome, fierce, intensive, profound, vehement, violent',
                                            'light, moderate, soft'),
                                    TestWay('adj',
                                            '激烈的, 爆发性的',
                                            'marked by bursts of destructive force or intense activity',
                                            ["Ferocious forest fires threatened to destroy hundreds of homes in the scrubland. 肆虐的森林大火威胁着灌木丛中数百户居民的住所。"],
                                            'cyclonic, explosive, furious, paroxysmal, rabid, stormy, tempestuous, tumultuous, turbulent, volcanic',
                                            'nonviolent, peaceable, peaceful'),
                                    TestWay('adj',
                                            '凶猛的, 残暴的',
                                            'violently unfriendly or aggressive in disposition',
                                            ["captured and slaughtered by the ferocious tribesmen 被残暴的部落居民所抓获并惨遭屠杀"],
                                            'feral, grim, savage, vicious',
                                            'gentle, mild, unaggressive',
                                            'ferocity n. 凶猛, 残暴')]),
                              Word('affix', "",
                                   [TestWay('vt',
                                            '粘合',
                                            'to attach physically',
                                            ["affix a stamp to a letter 把邮票贴在信封上"],
                                            'attach, bend, fix',
                                            'detach, undo, unfasten, unhook')])])

list28_unit2 = VocabularyList([Word('asymmetry', "",
                                   [TestWay('n',
                                            '不对称, 不平衡',
                                            'lack of balance or symmetry',
                                            ["functional asymmetry of cerebral hemispheres 大脑两半球功能不对称性"],
                                            'disproportion, imbalance',
                                            'symmetry, balance, proportion',
                                            'asymmetric adj. 不对称的')]),
                              Word('equilibrium', "",
                                   [TestWay('n',
                                            '均势, 平衡',
                                            'a condition in which opposing forces are equal to one another',
                                            ["We must find an equilibrium between commercial development and conservation of our natural treasures. 我们必须在发展经济和保护自然资源之间找到一个平衡点。"],
                                            'counterpoise, equilibration, equipoise, poise, stasis',
                                            'disequilibration, disequilibrium, imbalance, nonequilibrium, unbalance'),
                                    TestWay('n',
                                            '(感情上的)平静',
                                            'evenness of emotions or temper',
                                            ["That stunning insult left me speechless, and several minutes passed before I recovered my equilibrium. 那个令人震惊的侮辱弄得我哑口无言, 我花了好几分钟才使心情得以平静。"],
                                            'aplomb, calmness, composure, countenance, imperturbability, placidity, repose, sangfroid, serenity, tranquillity',
                                            'agitation, discomposure, perturbation')]),
                              Word('delegate', "",
                                   [TestWay('n',
                                            '代理人, 代表',
                                            'a person authorized to act as representative for another',
                                            ["The real estate developer sent a delegate to the town meeting to represent his interests. 房地产开发商派了一名能代表自己利益的代理前往镇上开会。", "the U.N. delegates from African countries 非洲国家的驻联合国代表"],
                                            'agent, assignee, commissary, deputy, emissary, envoy, legate, minister, proxy, representative'),
                                    TestWay('vt',
                                            '移交(权力, 任务等)',
                                            'to put (something) into the possession or safekeeping of another',
                                            ["The manager is reluctant to delegate authority to subordinates while abroad. 经理不愿意在国外期间将自己的权力转交给下级。"],
                                            'commit, confide, consign, deliver, entrust, repose, transfer, transmit, vest, give over, hand over, turn over',
                                            'hold, keep, retain',
                                            'delegation n. 代表团')]),
                              Word('pious', "",
                                   [TestWay('adj',
                                            '(信仰上)虔诚的',
                                            'marked by or showing reverence for deity and devotion to divine worship',
                                            ["a pious woman who decided to become a nun 一个决心成为修女的虔诚女子"],
                                            'devout, godly, religious, sainted, saintly',
                                            'antireligious, faithless, godless, impious, irreligious, ungodly, unholy'),
                                    TestWay('adj',
                                            '忠诚的',
                                            "firm in one's allegiance to someone or something",
                                            ["a pious supporter of his school's athletic teams, during winning and losing seasons alike 学校体育队的忠诚支持者, 不论他们是输或赢"],
                                            'constant, dedicated, devoted, loyal, staunch, steadfast, steady, true',
                                            'disloyal, fickle, inconstant, perfidious, recreant, traitorous, treacherous, unfaithful')]),
                              Word('hierarchical', "",
                                   [TestWay('adj',
                                            '分等级的, 等级制的',
                                            'classified according to various criteria into successive levels or layers',
                                            ["the traditional hierarchical system of military organization 军队中传统的等级制度"],
                                            'graded, graduated, ranked',
                                            other_form = 'hierarchy n. 等级制度')]),
                              Word('obsolete', "",
                                   [TestWay('adj',
                                            '过时的, 被淘汰的',
                                            'no longer in use or no longer useful',
                                            ["I was told my old printer is obsolete and I can't get replacement parts. 我被告知我的打印机已经被淘汰了, 因此无法更换配件。", "an obsolete word 一个已经废弃不用的单词"],
                                            'antiquated, archaic, dated, fossilized, medieval, moribund, moth-eaten, outdated, outmoded, outworn, prehistoric, rusty',
                                            'contemporary, current, modern, recent')]),
                              Word('peel', "",
                                   [TestWay('vt',
                                            '剥去',
                                            'to strip off an outer layer of',
                                            ["She can peel apples with lightning speed. 她能以飞快的速度削苹果。"],
                                            'bark, flay, hull, husk, shell, shuck, skin, strip'),
                                    TestWay('vi',
                                            '脱去(衣服等)',
                                            "to take off one's clothes",
                                            ["peeled off the wet clothes 脱去湿衣服"],
                                            'doff, douse, put off, shrug off, take off',
                                            'don, put on')]),
                              Word('wiretap', "",
                                   [TestWay('n./vt',
                                            '偷听, 窃听',
                                            'to tap a telephone or telegraph wire in order to get information',
                                            ["This line is not clean asCIAmight have wiretapped it. 这根线路不安全, 因为中情局可能已经在监听了。"],
                                            'eavesdrop, overhear, tap')]),
                              Word('surveillance', "",
                                   [TestWay('n',
                                            '监视, 监控',
                                            'close observation of a person or group, especially one under suspicion',
                                            ["government surveillance of suspected terrorists 政府对于恐怖分子嫌疑人的监控"],
                                            'oversight, supervision, watch')]),
                              Word('perceptive', "",
                                   [TestWay('adj',
                                            '敏锐的',
                                            'able to sense slight impressions or differences',
                                            ["Due to their ability to rotate their ears, cats are very perceptive when it comes to pinpointing the source of a sound. 由于猫能够转动它们的耳朵, 所以它们能十分敏锐地确定声源的位置。"],
                                            'delicate, fine, keen,quick, sensitive, sharp',
                                            'dead, imperceptive, insensible, insensitive, numb'),
                                    TestWay('adj',
                                            '洞察力强的',
                                            'having or showing deep understanding and intelligent application of knowledge',
                                            ["A perceptive teacher was able to discover what was really troubling the youth. 一个洞察力强的老师应该能察觉真正困扰青少年是什么。"],
                                            'discerning, insightful, prudent, sagacious, sage, sapient',
                                            'brainless, dumb, foolish, idiotic, imbecile, moronic, silly, simple, slow, stupid, thoughtless, unintelligent, unwise, witless')])])

list28_unit3 = VocabularyList([Word('renege', "",
                                   [TestWay('vt',
                                            '放弃, 摒弃',
                                            'to solemnly or formally reject or go back on (as something formerly adhered to)',
                                            ["She refused to renege the principles by which she had always lived her life, even if it resulted in losing her business. 尽管有可能使她失去她的事业, 但她仍然拒绝放弃她在生命中所坚持的那些原则。"],
                                            'abnegate, forswear, recant, renounce, repeal, repudiate, retract, withdraw',
                                            'adhere',
                                            'renegade n. 叛徒')]),
                              Word('rigmarole', "",
                                   [TestWay('n',
                                            '混乱而无意义的话',
                                            'language marked by abstractions, jargon, euphemisms, and circumlocutions; confused or meaningless talk',
                                            ["The security guard gave me some kind of rigmarole about passes and authorizations. 保安不知所云地跟我说了一些关于通关和授权的话。"],
                                            'abracadabra, babble, drivel, gabble, gibber, jabber, nonsense, prattle')]),
                              Word('implicit', "",
                                   [TestWay('adj',
                                            '不言而喻的, 心照不宣的',
                                            'capable of being understood from something else though unexpressed',
                                            ["The implicit agreement among members of the outing club is that everyone pays his or her own way on all trips. 野外俱乐部成员之间一条心照不宣的约定就是: 沿途所有开销都AA。"],
                                            'implied, unexpressed, unspoken, unvoiced, wordless',
                                            'explicit, expressed, spoken, stated, voiced'),
                                    TestWay('adj',
                                            '无疑问的, 无保留的',
                                            'being without doubt or reserve',
                                            ["Members of the expedition must have implicit trust in their leaders. 远征的队员必须百分之百地信任他们的领队。"],
                                            'assured, clear, confident, doubtless, positive, sanguine, sure',
                                            'doubtful, dubious, uncertain, unsure')]),
                              Word('marginal', "",
                                   [TestWay('adj',
                                            '边缘的',
                                            'located at or near a border',
                                            ["Marginal locations in the open-air market are a bit cheaper. 露天市场边缘的地段通常都要便宜些。"],
                                            'frontier',
                                            'interior'),
                                    TestWay('adj',
                                            '不重要的',
                                            'not of central importance',
                                            ["regards violence as a marginal rather than a central problem 并不把暴力问题当作重要的核心问题来看"],
                                            'inconsequential, inconsiderable, insignificant, minor, minute, negligible, nugatory, slight, trifling, trivial',
                                            'consequential, eventful, important, meaningful, momentous, significant, substantial, weighty')]),
                              Word('pivotal', "",
                                   [TestWay('adj',
                                            '最关键的, 最为重要的',
                                            'of the greatest possible importance',
                                            ["The report was missing a pivotal piece of information. 报告遗漏了最为重要的信息。"],
                                            'critical, crucial, decisive, key, vital',
                                            'inconsequential, inconsiderable, insignificant, marginal, minor, minute, negligible, nugatory, slight, trifling, trivial')]),
                              Word('unavailing', "",
                                   [TestWay('adj',
                                            '徒劳的, 无果的',
                                            'producing no results',
                                            ["an unavailing effort to avert a war 试图避免战争的徒劳尝试"],
                                            'abortive, barren, bootless, fruitless, ineffectual, unproductive, unprofitable, unsuccessful, useless, vain',
                                            'effective, effectual, efficacious, fruitful, potent, productive, successful')]),
                              Word('cachet', "",
                                   [TestWay('n',
                                            '威望, 声望',
                                            'a mark or quality, as of distinction, individuality, or authenticity',
                                            ["Federal courts have a certain cachet which state courts lack. 联邦法院拥有州立法院所不具备的威信。"],
                                            'credit, distinction, esteem, homage, kudos, prestige',
                                            'infamy, notoriety')]),
                              Word('graft', "",
                                   [TestWay('vt',
                                            '移植, 移接',
                                            'to implant (living tissue) surgically or as if surgically',
                                            ["The top layer of skin has to be grafted onto the burns. 顶层的皮肤需要被移植到烧伤的伤口上。", "graft old traditions onto the new ones 把老传统移植到新的习俗之上"],
                                            'implant, transplant')]),
                              Word('feisty', "",
                                   [TestWay('adj',
                                            '好斗的, 好争论的',
                                            'having or showing a lively aggressiveness',
                                            ["At 66, she was as feisty as ever. 尽管已经66岁高龄, 她还是一样好斗。"],
                                            'aggressive, agonistic, assaultive, bellicose, belligerent, combative, contentious, disputatious, gladiatorial, militant, quarrelsome, truculent',
                                            'pacific, peaceful, peace-loving')]),
                              Word('cascade', "",
                                   [TestWay('n',
                                            '(尤指小的)瀑布',
                                            'a steep usually small fall of water',
                                            ["The river forms a series of cascades as it drops a total of 200 feet in elevation. 这条河前后海拔差达200余英尺, 故而形成了一系列的小瀑布。"],
                                            'fall, waterfall',
                                            'cataract')])])

list28_unit4 = VocabularyList([Word('domineer', "",
                                   [TestWay('vt',
                                            '专制统治',
                                            'to exercise arbitrary or overbearing control',
                                            ["Her husband and mother-in-law tyrannize her. 她生活在她丈夫和婆婆的高压统治下。"],
                                            'tyrannize',
                                            other_form = 'domineering adj. 专横的, 盛气凌人的')]),
                              Word('vile', "",
                                   [TestWay('adj',
                                            '丑陋的',
                                            'unpleasant to look at',
                                            ["a truly vile combination of colors 着实丑陋的混搭色调"],
                                            'grotesque, hideous, homely, monstrous',
                                            'aesthetic, attractive, beautiful, comely, cute, fair, gorgeous, handsome, ravishing, seemly'),
                                    TestWay('adj',
                                            '(道德上)可鄙的, 卑鄙的',
                                            'morally despicable or abhorrent',
                                            ["Nothing is so vile as intellectual dishonesty. 没什么比智力上的欺骗更为可鄙的了。"],
                                            'base, contemptible, despicable, detestable, dishonorable, execrable, ignominious, mean, nasty, paltry, sordid, wretched',
                                            'honorable, lofty, noble, straight, upright, venerable, virtuous')]),
                              Word('poach', "",
                                   [TestWay('vt',
                                            '水煮',
                                            'to cook in a liquid heated to the point that it gives off steam',
                                            ["He poached an egg for breakfast. 他煮了一个荷包蛋做早饭。"],
                                            'coddle, parboil, simmer, stew')]),
                              Word('palpitation', "",
                                   [TestWay('n',
                                            '(有节奏的)舒张收缩',
                                            'a rhythmic expanding and contracting',
                                            ["a palpitation of the blood vessels 血管有节奏的舒张收缩"],
                                            'beat, beating, pulse, throb')]),
                              Word('palaver', "",
                                   [TestWay('n',
                                            '对话, 交流',
                                            'an exchange of views for the purpose of exploring a subject or deciding an issue',
                                            ["seemingly endless palaver between the negotiating parties 谈判双方之间看似没有尽头的对话"],
                                            'argument, colloquy, conference, consult, council, counsel, debate, dialogue, parley'),
                                    TestWay('vi',
                                            '闲聊',
                                            'to talk profusely or idly',
                                            ["Mothers were palavering and drinking coffee while watching their children play. 母亲们一边看着她们的孩子玩耍, 一边喝着咖啡闲谈。"],
                                            'babble, chatter, converse, gabble, jabber, prate, prattle, rattle, twitter')]),
                              Word('favoritism', "",
                                   [TestWay('n',
                                            '偏爱, 偏袒',
                                            'the showing of special favor',
                                            ["Favoritism blinded the administrator to the benefits of the proposed system for distributing work. 偏袒使得经理无法意识到这一待讨论的分配系统所带来的收益。"],
                                            'favor, one-sidedness, partiality, prejudice, tendentiousness',
                                            'impartiality, neutrality, objectivity, open-mindedness, unbiasedness')]),
                              Word('overwrought', "",
                                   [TestWay('adj',
                                            '十分激动的, 非常不安的',
                                            'being in a state of increased activity or agitation',
                                            ["She became overwrought when she heard that her child was missing. 当她得知自己孩子失踪的消息后变得极其激动和不安。"],
                                            'agitated, excited, frenzied, heated, hectic, hyperactive, overactive',
                                            'calm, collected, composed, placid, serene, tranquil'),
                                    TestWay('adj',
                                            '(装饰)过分华丽的',
                                            'elaborately and often excessively decorated',
                                            ["The author's prose is overwrought with purple passages and florid metaphors. 这个作者的散文里充满了词藻华丽的段落和比喻, 显得有些过分。"],
                                            'baroque, bedizened, flamboyant, florid, fussy, gingerbreaded, ornate, overdecorated',
                                            'austere, plain, severe, stark, unadorned')]),
                              Word('sequel', "",
                                   [TestWay('n',
                                            '结果',
                                            'a result or consequence',
                                            ["Higher prices are a logical sequel to higher costs for manufacturers. 从逻辑上来说, 更高的价格是更高的生产成本的结果。"],
                                            'aftermath, conclusion, consequence, fate, fruit, outcome, product, result, sequence',
                                            'antecedent, causation, cause, occasion, reason')]),
                              Word('fad', "",
                                   [TestWay('n',
                                            '(短暂的)流行, 时尚',
                                            'a practice or interest that is very popular for a short time',
                                            ["Once the fad for that kind of music had passed, nobody would have been caught dead listening to it. 一旦那种流派的音乐流行风刮过之后, 就没有人会来听它出丑了。"],
                                            'buzz, craze, enthusiasm, fashion, trend, vogue',
                                            'classic, standard')]),
                              Word('arid', "",
                                   [TestWay('adj',
                                            '干燥的',
                                            'marked by little or no precipitation or humidity',
                                            ["arid wastelands unfit for human habitation 不适合人类居住的干燥荒原"],
                                            'droughty, dry, sere, thirsty, waterless',
                                            'damp, dank, humid, moist, wet'),
                                    TestWay('adj',
                                            '无趣的, 无聊的',
                                            'causing weariness, restlessness, or lack of interest',
                                            synonyms = 'dreary, dull, flat, humdrum, jading, jejune, monochromatic, monotonous, pedestrian, stale, stodgy, tedious, wearisome',
                                            antonyms = 'absorbing, engaging, engrossing, gripping, interesting, intriguing, involving, riveting')])])

list28_unit5 = VocabularyList([Word('avowal', "",
                                   [TestWay('n',
                                            '承认',
                                            'a solemn and often public declaration of the truth or existence of something',
                                            ["With jingoism rampant, the peace candidate felt compelled to make an avowal of his patriotism. 在沙文主义肆虐的情况下, 爱好和平的候选人被迫承认自己是个爱国主义者。"],
                                            'affirmation, assertion, asseveration, avouchment, claim, declaration, insistence, profession',
                                            'disavowal')]),
                              Word('backfire', "",
                                   [TestWay('vi',
                                            '产生相反的结果, 事与愿违',
                                            'to have the reverse of the desired or expected effect',
                                            ["My plan to throw her a surprise party backfired when she ended up sobbing that everyone had forgotten her birthday. 我本想给她的生日开一个聚会作为惊喜, 但没想到事与愿违: 她啜泣着说所有人都忘记了她的生日。"],
                                            'boomerang',
                                            'succeed')]),
                              Word('baffle', "",
                                   [TestWay('vt',
                                            '挫败, 阻挠',
                                            'to frustrate or check (a person) as by confusing or perplexing',
                                            ["baffled by the language barrier 受到语言障碍的阻挠"],
                                            'balk, beat, check, discomfit, foil, frustrate, thwart',
                                            'advance, cultivate, encourage, forward, foster, further, nurture, promote'),
                                    TestWay('vt',
                                            '使疑惑',
                                            'to throw into a state of mental uncertainty',
                                            ["I was baffled by many of the scientific terms used in the article. 这篇文章中各种学术词汇让我很困惑。"],
                                            'befog, befuddle, bewilder, confound, discombobulate, disorient, maze, mystify, perplex, puzzle, vex',
                                            'clarify, elucidate',
                                            'baffling adj. 令人困惑的')]),
                              Word('careen', "",
                                   [TestWay('vi',
                                            '蹒跚而行, 不稳地行走',
                                            'to lurch or swerve while in motion',
                                            ["He careened unsteadily to the couch after hitting his head. 在撞到头以后, 他摇摇摆摆地走向沙发。"],
                                            'dodder, lurch, reel, sway, teeter, totter, waddle, wobble'),
                                    TestWay('vi',
                                            '狂奔, 快速运动',
                                            'to rush headlong or carelessly',
                                            ["Sounding its siren, an ambulance careened through the intersection. 救护车响着警笛飞驰通过十字路口"],
                                            'blast, bolt, bustle, career, dash, fly, hustle, rush, rustle, speed, whirl',
                                            'crawl, creep, lag, poke')]),
                              Word('constrict', "",
                                   [TestWay('vt',
                                            '压缩, 压紧',
                                            'to make smaller or narrower by or as if by binding or squeezing',
                                            ["lives constricted by poverty 因为贫穷而拮据的生活", "Severe migraine can be treated with a drug which constricts the blood vessels. 􁸀些能使血管收缩的药物可用来治疗严重的偏头痛。"],
                                            'capsule, collapse, compact, condense, constringe, contract, narrow, squeeze, telescope',
                                            'decompress, expand, open, outspread, outstretch')]),
                              Word('dampen', "",
                                   [TestWay('vt',
                                            '(特指稍稍地)弄湿',
                                            'to make or become slightly or moderately wet',
                                            ["dampen a paper towel with water and use it to clean up the mess 把纸巾弄湿用来清扫"],
                                            'bedew, damp, douse , drench, impregnate, saturate, soak, souse, steep',
                                            'dehydrate, desiccate, dry, parch, scorch, sear'),
                                    TestWay('vt',
                                            '抑制, 压抑(感情, 精力等), 泼冷水',
                                            'to check or diminish the feeling, activity or vigor of',
                                            ["Nothing could dampen their enthusiasm. 没有什么能扼杀他们的激情。", "The oppressive heat dampened our spirits. 让人难以忍受的酷暑让我们精神不振。"],
                                            'benumb, blunt, castrate, deaden, devitalize, enervate, geld, lobotomize, petrify',
                                            'brace, energize, enliven, invigorate, quicken, stimulate, vitalize, vivify')]),
                              Word('debonair', "",
                                   [TestWay('adj',
                                            '无忧无虑的, 不在乎的',
                                            'having or showing freedom from worries or troubles',
                                            ["His debonair dismissal of my inquiry concerning his financial situation led me to believe that nothing was wrong. 对于我有关他个人理财的问题, 他表现得毫不在乎, 这使我相信没有问题。"],
                                            'blithe, carefree, gay, insouciant, lighthearted, lightsome, slaphappy, unconcerned',
                                            'careworn'),
                                    TestWay('adj',
                                            '风度翩翩的',
                                            'having or showing very polished and worldly manners',
                                            ["The debonair gentleman charmed all of the ladies in the room. 风度翩翩的绅士吸引了在场的所有女士。"],
                                            'civilized, graceful, polished, refined, smooth, sophisticated, suave, svelte, urbane',
                                            'boorish, churlish, loutish, uncouth, clumsy, gauche, graceless')]),
                              Word('fabulous', "",
                                   [TestWay('adj',
                                            '传说中的',
                                            'based on, described in, or being a fable',
                                            ["The city of Phoenix is named after a fabulous bird that every 500 years destroys itself with fire, only to rise again from its own ashes. 凤凰城的名字来源于传说中的一种鸟, 它每隔500年会在火焰中毁灭, 然后再从灰烬中重生。"],
                                            'fabled, legendary'),
                                    TestWay('adj',
                                            '幻想中的, 不真实的',
                                            'not real and existing only in the imagination',
                                            ["a story of a fabulous land where the people know nothing of war and live together in perfect harmony 一个有关世外桃源的故事, 当地的居民不知道战争为何物, 和谐融洽地生活在一起"],
                                            'chimerical, dreamy, illusory, phantom, unreal, visionary',
                                            'actual, existent, existing, real'),
                                    TestWay('adj',
                                            '令人惊讶的, 令人称奇的',
                                            'causing wonder or astonishment',
                                            ["the fabulous endurance of a marathon runner 马拉松参赛者令人惊讶的耐力"],
                                            'amazing, astonishing, astounding, miraculous, portentous, prodigious, staggering, stunning, stupendous, sublime, wonderful',
                                            'common, ordinary'),
                                    TestWay('adj',
                                            '极好的',
                                            'extremely pleasing or successful',
                                            ["We had a fabulous time on our vacation. 我们的假期赞极了。"],
                                            'awesome, divine, fantastic, heavenly, marvelous, noble, prime, splendid, superb, superior, terrific',
                                            'atrocious, awful, execrable, lousy, pathetic, poor, rotten, terrible, wretched')]),
                              Word('hobble', "",
                                   [TestWay('vi',
                                            '跛行, 蹒跚而行',
                                            'to walk or move along haltingly or with difficulty',
                                            ["She picked up her cane and hobbled across the room. 她拿起了一根手杖, 一拐一拐地穿过了房间。"],
                                            'falter, halt, limp, stagger, totter',
                                            'stride'),
                                    TestWay('vt',
                                            '阻碍, 妨碍',
                                            'to hamper the action or progress of',
                                            ["We were hobbled by the snowstorm from getting out to do some Christmas shopping. 暴雪阻碍了我们圣诞购物的计划。"],
                                            'encumber, fetter, handicap, hamper, hinder, impede, inhibit, manacle, obstruct, shackle, stymie, trammel',
                                            'aid, assist, facilitate')]),
                              Word('plush', "",
                                   [TestWay('adj',
                                            '(味道等)浓郁的',
                                            'having an abundance of some characteristic quality (as flavor)',
                                            ["a plush, ripe wine 味道浓郁的陈年老窖"],
                                            'concentrated, full, heady, lusty, muscular, potent, rich, robust, strong',
                                            'delicate, light, mild, thin, weak'),
                                    TestWay('adj',
                                            '奢华的, 豪华的',
                                            'notably luxurious',
                                            ["a plush castle filled with priceless art and antiques 一座充满了无价艺术品和古董的奢华城堡"],
                                            'deluxe, lavish, luxuriant, luxurious, opulent, palatial, silken, sumptuous',
                                            'ascetic, austere, humble, spartan')])])

list28_unit6 = VocabularyList([Word('rhetorical', "",
                                   [TestWay('adj',
                                            '语言上的, 文字上的',
                                            'of or relating to words or language',
                                            ["The next war that those two nations fight won't be rhetorical - it will be with bombs and bullets. 两国之间的下一场战争可不会是斗嘴皮了——他们会来真格的。"],
                                            'lexical, linguistic, vocabular, wordy'),
                                    TestWay('adj',
                                            '言辞华丽(却往往无内涵的)',
                                            'full of fine words and fancy expressionsbut mostly meaningless words and phrases',
                                            ["You can skip over the rhetorical passages and still get the gist of the essay. 你可以跳过那些词藻华丽的段落, 直接获取文本的主旨。", "The new governor delivered a long rhetorical speech about our state's bright future but laid out no specific programs for ensuring it. 新的执政官发表了词藻华丽的演说, 畅谈国家的美好未来, 但却没有提出实现这一目标的具体措施。"],
                                            'bombastic, flatulent, florid, fustian, gaseous, gassy, grandiloquent, oratorical, orotund, purple, windy',
                                            'prosaic, plain, simple')]),
                              Word('thick-skinned', "",
                                   [TestWay('adj',
                                            '冷漠无情的, 不顾及他人感受的',
                                            'largely unaffected by the needs and feelings of other people',
                                            ["She was so thick-skinned that she was clueless about the fact that the joke had hurt her friend's feelings. 她很少顾及他人的感受, 以至于她根本没有意识到那个玩笑伤害了她朋友的感情。"],
                                            'affectless, callous, cold-blooded, heartless, indurate, inhumane, insensitive, merciless, obdurate, ruthless',
                                            'charitable, compassionate, humane, kindhearted, merciful, sympathetic, tender, warmhearted')]),
                              Word('trifle', "",
                                   [TestWay('n',
                                            '不重要的事',
                                            'something of little importance or value',
                                            ["Let us not speak of trifles when our nation may be going to war. 战事在即, 我们还是先放下这些琐事吧。"],
                                            'bagatelle, frippery, triviality'),
                                    TestWay('vi',
                                            '不正经地对待, 玩弄',
                                            'to behave amorously without serious intent',
                                            ["Do not trifle with me unless you mean to ask me to marry you. 如果你不是真心想和我结婚, 就请不要来玩弄我的感情。"],
                                            'coquet, dally, flirt, frivol, toy',
                                            other_form = 'trifling adj. 不重要的')]),
                              Word('weather', "",
                                   [TestWay('vt',
                                            '安全渡过(危机等), 经受住',
                                            'to come through (something) safely',
                                            ["We haveve weathered worse crises, and so we'll survive this one. 更为严重的危机我们都闯过了, 这个也不会有问题的。", "They weathered a terrible storm while at sea. 他们在海上平安渡过了一场巨大的风暴。"],
                                            'survive',
                                            'decease, die, expire, perish, succumb, pass away')]),
                              Word('wily', "",
                                   [TestWay('adj',
                                            '狡诈的, 狡猾的',
                                            "clever at attaining one's ends by indirect and often deceptive means",
                                            ["He is an experienced and wily old statesman. 他是一个经验丰富而狡诈的老销售员。‖His wily plan only rebounded on him. 聪明反被聪明误。"],
                                            'beguiling, cagey, crafty, cunning, devious, foxy, guileful, scheming, shrewd, slick, sly, subtle, tricky',
                                            'artless, guileless, ingenuous, innocent, undesigning')]),
                              Word('arable', "",
                                   [TestWay('adj',
                                            '适合耕种的',
                                            'fit for or used for the growing of crops',
                                            ["explore the west for arable land 向西探索适合耕种的土地"],
                                            'cultivable, tillable',
                                            'barren, sterile, infertile, unfruitful, unproductive')]),
                              Word('convene', "",
                                   [TestWay('vt',
                                            '召开, 召集',
                                            'to bring together in assembly by or as if by command',
                                            ["convened the members of the council for an emergency session 召集委员会的成员进入紧急议程"],
                                            'assemble, call, convene, muster, summon',
                                            'disband, dispel, disperse, dissipate, dissolve, squander'),
                                    TestWay('vi',
                                            '聚集, 集合',
                                            'to come together in a body',
                                            ["The students convened in the auditorium to hear the principal’saddress. 学生们在大礼堂集合, 聆听校长的致辞。"],
                                            'cluster, collect, concenter, concentrate, conglomerate, congregate, converge, gather, meet, rendezvous',
                                            other_form = 'convention n. 集会, 大会')]),
                              Word('decadent', "",
                                   [TestWay('adj',
                                            '堕落的, 腐败的',
                                            'having or showing lowered moral character or standards',
                                            ["Opponents of gambling casinos claim that gambling is a decadent form of entertainment. 赌场的反对者们宣称赌博是一种堕落腐化的娱乐形式。"],
                                            'debased, debauched, degenerate, depraved, dissolute, perverse, perverted, reprobate, warped',
                                            'pure, uncorrupted'),
                                    TestWay('n',
                                            '放纵的人',
                                            'a person whose life is devoted to luxury and sensual pleasures',
                                            ["a decadent who squandered her once considerable family fortune 一个挥霍了大量的家族财富的人"],
                                            'debauchee, hedonist, libertine, sensualist, sybarite, profligate',
                                            'ascetic'),
                                    TestWay('n',
                                            '道德上堕落的人',
                                            'a person in a condition or process of mental or moral decay',
                                            ["avant-garde artists who were scorned by the bourgeoisie as talentless decadents 被中产阶级鄙视为没有才华的堕落者的前卫艺术家"],
                                            'deviate',
                                            'saint')]),
                              Word('demotion', "",
                                   [TestWay('n',
                                            '降级, 降职',
                                            'the act or an instance of bringing to a lower grade or rank',
                                            ["Anyone who objects will get a demotion. 任何胆敢反对的人都会被降职。", "received a demotion from sergeant to corporal 从中士降为下士"],
                                            'degradation, downgrading, reduction',
                                            'elevation, promotion')]),
                              Word('glower', "",
                                   [TestWay('vi',
                                            '怒目而视',
                                            'to look or stare with sullen annoyance or anger',
                                            ["Baseball fans glowering at their TVs as they watched their favorite team lose. 看着他们支持的球队输球, 棒球迷们恶狠狠地盯着电视屏幕。", "He just glowered without speaking. 他一言不发地怒视着我。"],
                                            'glare, gloom, lower, scowl',
                                            'beam, grin, smile')])])

list28_unit7 = VocabularyList([Word('grit', "",
                                   [TestWay('n',
                                            '(面对困难时所表现出来的)毅力',
                                            'the strength of mind that enables a person to endure pain or hardship',
                                            ["She was an athlete with true grit, continuing her training despite bad weather and an injury. 她是真正一个有着惊人毅力的运动员, 即便是在受了伤外加天气恶劣的情况下仍然坚持训练。"],
                                            'backbone, constancy, fiber, grittiness, guts, intestinal fortitude, pluck, spunk',
                                            'cowardliness, cravenness, gutlessness, pusillanimity, spinelessness')]),
                              Word('infraction', "",
                                   [TestWay('n',
                                            '违背, 违犯',
                                            'a failure to uphold the requirements of law, duty, or obligation',
                                            ["Speeding is only a minor infraction, but vehicular homicide is a serious felony. 超速只是小的违章, 但是用机动车故意杀人就是重罪了。"],
                                            'breach, contravention, infringement, transgression, trespass, violation',
                                            'observance')]),
                              Word('madcap', "",
                                   [TestWay('n',
                                            '热爱冒险的人',
                                            'a person who seeks out very dangerous or foolhardy adventures with no apparent fear',
                                            ["an incorrigible madcap who loves drag racing and white-water rafting 一个热爱飙车和激流竹筏的无药可救的冒险狂"],
                                            'daredevil, madman'),
                                    TestWay('adj',
                                            '大胆的, 鲁莽的',
                                            'behaving or acting impulsively or rashly;foolishly adventurous or bold',
                                            ["They switched from one madcap scheme to another. 他们从一个鲁莽的方案换到了另一个。"],
                                            'audacious, bold, brash, daredevil, overbold, overconfident, reckless, temerarious',
                                            'careful, cautious, circumspect, guarded, heedful, prudent, wary')]),
                              Word('novice', "",
                                   [TestWay('n',
                                            '新手, 初学者',
                                            'a person new to a field or activity',
                                            ["a novice chess player 象棋初学者"],
                                            'apprentice, colt, fledgling, freshman, greenhorn, neophyte, newcomer, recruit, rook, tenderfoot, tyro, virgin',
                                            'doyen, maven, veteran')]),
                              Word('observant', "",
                                   [TestWay('adj',
                                            '警惕的, 警觉的',
                                            'paying close attention usually for the purpose of anticipating approaching danger or opportunity',
                                            ["Good reporters are keenly observant of everything around them. 优秀的记者应该对身边所有的事情都保持高度的警惕。", "If you were more observant, you would perceive that something is troubling her deeply. 如果你能再警觉一些的话, 你就会发现她正被某些东西困扰。"],
                                            'alert, attentive, awake, cautious, sharp, vigilant, watchful',
                                            'careless, heedless, inattentive, unmindful, unthinking, unwary'),
                                    TestWay('adj',
                                            '严格遵守(规章、制度或原则)的',
                                            'diligent in observing a law, custom, duty, or principle',
                                            ["observant of the speed limit 严格遵守速度限制", "pious and religiously observant families 虔诚而严守教规的家庭"],
                                            'law-abiding',
                                            'observance n. 遵守(规定)')]),
                              Word('plenitude', "",
                                   [TestWay('n',
                                            '丰富, 充沛',
                                            "an amount or supply more than sufficient to meet one's needs",
                                            ["a region blessed with a plenitude of natural resources 充满着上帝赐予的丰富资源的地区"],
                                            'abundance, cornucopia, feast, plentitude, plethora, wealth',
                                            'deficiency, inadequacy, insufficiency, undersupply'),
                                    TestWay('n',
                                            '大量',
                                            'a considerable amount',
                                            ["She has gathered a plenitude of information on the topic. 有关这个话题她收集了大量的资料。"],
                                            'bunch, bundle, dozen, multiplicity, myriad, plateful, plenty, profusion, reams, scads, spate, stack, volume',
                                            'ace, bit, glimmer, handful, hint, mite, nip, ounce, pittance, speck, spot, trace')]),
                              Word('replenish', "",
                                   [TestWay('vt',
                                            '补充',
                                            'to fill or make complete again; add a new stock or supply to',
                                            ["He went to replenish her glass. 他去续杯了。"],
                                            'refill, reload',
                                            'consume, drain, empty, exhaust')]),
                              Word('stasis', "",
                                   [TestWay('n',
                                            '平衡, 停滞',
                                            'a condition of balance among various forces',
                                            ["For the time being, the populations of the national park's predators and prey remain in stasis. 目前国家公园中捕食者和猎物的数量保持着一定的平衡。", "Language is a primary element of culture,and stasis in the arts is tantamount to death. (Charles Marsh) 语言是文化当中的主要元素, 艺术的停滞和平衡就等同于死亡。——查理斯·马氏"],
                                            'counterpoise, equilibration, equilibrium, equipoise, poise',
                                            'disequilibration, disequilibrium, imbalance, nonequilibrium, unbalance')]),
                              Word('tycoon', "",
                                   [TestWay('n',
                                            '大亨, 巨头',
                                            'a person of rank, power, or influence in a particular field',
                                            ["an oil tycoon who's widely considered the most powerful man in the county 被认为是郡上最有势力的一个石油大亨", "The automobile tycoon is on the verge of bankruptcy. 汽车巨头濒临破产的边缘。"],
                                            'baron, captain, king, lion, lord, magnate, mogul, monarch, prince',
                                            'nobody, nothing, zero')]),
                              Word('umbrage', "",
                                   [TestWay('n',
                                            '不悦, 生气',
                                            'the feeling of being offended or resentful after a slight or indignity',
                                            ["He would take umbrage at the slightest suggestion of disrespect. 哪怕是一点点的不敬也会让他不悦。"],
                                            'dudgeon, huff, miff, offense, peeve, resentment',
                                            'contentment, delight, gratification, happiness, pleasure')])])

list28_unit8 = VocabularyList([Word('wilt', "",
                                   [TestWay('vi',
                                            '(花、植物等)萎蔫',
                                            'to become limp or flaccid',
                                            ["The plants wilted after I forgot to water them for three whole days. 在我整整三天忘记浇水之后, 植物们全都萎蔫了。"],
                                            'flag, hang, loll, sag, swag'),
                                    TestWay('vi',
                                            '精神萎靡, 憔悴',
                                            'to feel or exhibit the effects of fatigue or exhaustion',
                                            ["She had wilted a bit after walking around the hot and humid city. 在炎热潮湿的城市中行走使得她略显憔悴。", "His brain wilted from hitherto unprecedented weariness. 在前所未有的疲劳面前, 他的开始变得神情憔悴。"],
                                            'decay, droop, emaciate, fade, fail, lag, languish, sink, waste, wither',
                                            'convalesce, rally, rebound, recover, recuperate')]),
                              Word('agape', "",
                                   [TestWay('adj',
                                            '急切盼望的',
                                            'having or showing signs of eagerly awaiting something',
                                            ["At the sound of the sleigh bells the children were all agape, waiting for Santa to appear. 听到雪橇铃, 孩子们开始好奇地等待圣诞老人的到来。"],
                                            'agog, anticipant, anticipatory',
                                            'apathetic, indifferent, unconcerned, uninterested')]),
                              Word('annex', "",
                                   [TestWay('n',
                                            '裙楼, 副楼',
                                            'a building added on to a larger one or an auxiliary building situated near a main one',
                                            ["The new annex that will serve as the permanent home for the school library. 新的裙楼将成为学校图书馆的永久住所。"],
                                            'addition, extension, penthouse'),
                                    TestWay('vt',
                                            '添加, 合并',
                                            'to join (something) to a mass, quantity, or number so as to bring about an overall increase',
                                            ["plans to annex the supply room so as to make the classroom bigger 计划将工具房并入教室, 从而扩充其容量"],
                                            'adjoin, affix, append, attach, subjoin, tack',
                                            'abate, deduct, remove, subtract'),
                                    TestWay('vt',
                                            '吞并, 夺取(土地等)',
                                            'to incorporate (a country or other territory) within the domain of a state',
                                            ["Rome annexed the Nabatean kingdom in 106 AD. 公元前106年罗马帝国吞并了古城那巴顿。"],
                                            'acquire, appropriate, arrogate, expropriate, seize, take over',
                                            'lose')]),
                              Word('baffling', "",
                                   [TestWay('adj',
                                            '令人疑惑的, 难以理解的',
                                            'making great mental demands; hard to comprehend or solve',
                                            ["I was constantly ill, with a baffling array of symptoms. 我常常生病, 而且有着一系列令人困惑的症状。"],
                                            'befuddling, bewildering, confounding, confusing, enigmatic, puzzling, perplexing',
                                            'apparent, distinct, evident, lucid, manifest, obvious, patent, pellucid, perspicuous, plain, transparent')]),
                              Word('bewitching', "",
                                   [TestWay('adj',
                                            '迷人的, 令人着迷的',
                                            'having an often mysterious or magical power to attract',
                                            ["bewitching woman who has never lacked for suitors 一个从不缺乏追求者的迷人女子"],
                                            'alluring, appealing, attractive, captivating, charismatic, enchanting, engaging, entrancing, glamorous, luring, magnetic, seductive',
                                            'repellent, repelling, repugnant, repulsive, revolting')]),
                              Word('bore', "",
                                   [TestWay('n',
                                            '令人厌烦的人或事物',
                                            'one that causes boredom',
                                            ["For once, the graduation speaker wasn't a real bore. 就这一次毕业演讲者不是那么令人厌倦。"],
                                            'drip, droner, snoozer, yawner'),
                                    TestWay('vt',
                                            '使厌倦, 使厌烦',
                                            'to make weary by being dull, repetitive, or tedious',
                                            ["The professor's lifeless and unimaginative teaching style bored the students to death. 教授毫无生气和想象力的说教方式让学生厌倦至极。"],
                                            'jade, pall, tire, weary',
                                            'absorb, engage, engross, enthrall, fascinate, grip, interest, intrigue',
                                            'boring adj. 令人厌烦的; boredom n. 厌烦, 乏味')]),
                              Word('bumble', "",
                                   [TestWay('vi',
                                            '含糊不清地说, 杂乱无章地说',
                                            'to speak rapidly, inarticulately, and usually unintelligibly',
                                            ["Overcome with stage fright, I could only bumble through the speech. 由于怯场, 我结结巴巴地说完了演讲稿。"],
                                            'babble, drivel, drool, gabble, gibber, jabber, prattle, sputter',
                                            'articulate, enunciate, pronounce'),
                                    TestWay('vi',
                                            '笨拙地行动',
                                            'to move, act, or proceed clumsily',
                                            ["I sort of bumbled through the dance number, hoping that it would soon end. 我笨拙地跟着曲子舞蹈, 心里指望着它快点结束。"],
                                            'blunder, flounder, limp, lumber, plod, struggle, stumble, trudge',
                                            'coast, drift, glide, sail, slide')]),
                              Word('carefree', "",
                                   [TestWay('adj',
                                            '无忧无虑的',
                                            'free from care as having no worries or troubles',
                                            ["passengers on a luxury cruise ship enjoying a carefree vacation 在豪华游轮上享受着无忧旅途的乘客", "carefree college students on spring break 春假期间无忧无虑的大学生"],
                                            'blithe, debonair, gay, insouciant, lighthearted, lightsome, slaphappy, unconcerned',
                                            'careworn')]),
                              Word('chaperone', "",
                                   [TestWay('vt',
                                            '同行, 护送',
                                            'to go along with in order to provide assistance, protection, or companionship',
                                            ["Three parents will chaperone the students on the school trip. 本次班级旅行将有三名家长同行。"],
                                            'accompany, attend, companion, company, convoy, escort, squire',
                                            'abandon, desert, ditch, dump, forsake')]),
                              Word('charisma', "",
                                   [TestWay('n',
                                            '魅力, 吸引力',
                                            'a special magnetic charm or appeal',
                                            ["a movie star with unique charisma 有着独特魅力的电影明星", "The candidate was lacking in charisma. 候选人就是缺乏了点个人魅力。"],
                                            'allure, appeal, attractiveness, captivation, enchantment, fascination, glamor, seductiveness, witchery',
                                            'repulsion, repulsiveness',
                                            'charismatic adj. 有魅力的, 吸引人的')])])

list28_unit9 = VocabularyList([Word('conflagration', "",
                                   [TestWay('n',
                                            '大火',
                                            'a large destructive fire',
                                            ["All the stock was destroyed in a warehouse conflagration. 仓库里所有的货物都被一场大火烧毁了。"],
                                            'holocaust, inferno'),
                                    TestWay('n',
                                            '武装冲突, 战争',
                                            'a state of armed violent struggle between states, nations, or groups',
                                            ["What began as a skirmish over disputed territory erupted into a conflagration that swept the continent. 这场席卷整个大陆的战争是由之前关于有纠纷的领土的小冲突引发的。"],
                                            'conflict, war, warfare',
                                            'peace, truce')]),
                              Word('crow', "",
                                   [TestWay('vi',
                                            '感到高兴',
                                            'to feel or express joy or triumph',
                                            ["Being the home of the new Super Bowl champs was the first thing that city residents had to crow about in a very long time. 当地的队伍获得超级碗冠军队伍是这个城市居民长期以来得以感到高兴的第一件事情。"],
                                            'delight, exuberate, glory, jubilate, joy, rejoice, triumph',
                                            'bemoan, bewail, grieve, lament, weep'),
                                    TestWay('vt',
                                            '自鸣得意',
                                            "to praise or express pride in one's own possessions, qualities, or accomplishments often to excess",
                                            ["He is already crowing over his victory. 他已经在那里为自己的胜利而自鸣得意了。"],
                                            'blow, brag, swagger, vapor, vaunt')]),
                              Word('dashing', "",
                                   [TestWay('adj',
                                            '爱好冒险的, 大胆的',
                                            'inclined or willing to take risks',
                                            ["the dashing heroes in stories about the American West 美国西部故事中那些勇敢无畏的英雄"],
                                            'adventurous, audacious, daring, emboldened, enterprising, gutsy, nerved, nervy, venturous',
                                            'cowardly, craven, pusillanimous, timid, timorous')]),
                              Word('dated', "",
                                   [TestWay('adj',
                                            '过时的',
                                            'having passed its time of use or usefulness; out-of-date',
                                            ["His jokes are awfully dated, referring to things that happened years ago. 他的笑话全是些关于几年前的事情的过时货。"],
                                            'antiquated, archaic, fossilized, medieval, moribund, moth-eaten, obsolete, outdated, outmoded, outworn, prehistoric, rusty',
                                            'contemporary, current, modern, recent')]),
                              Word('dependable', "",
                                   [TestWay('adj',
                                            '可靠的, 值得信赖的',
                                            'capable of being depended on',
                                            ["a dependable source of income 可靠的收入来源", "He was a good friend and a dependable companion. 他是一个值得信赖的好伙伴。"],
                                            'calculable, reliable, responsible, safe, secure, solid, trustable, trustworthy',
                                            'undependable, unreliable, unsafe, untrustworthy')]),
                              Word('deplorable', "",
                                   [TestWay('adj',
                                            '可鄙的, 可耻的',
                                            'worthy of severe condemnation or reproach',
                                            ["We will not tolerate such deplorable behavior in a house of worship. 我们绝不能容许这样一种可鄙的行为出现在礼拜堂中。"],
                                            'despicable, dirty, grubby, lousy, mean, nasty, paltry, scurvy, wretched',
                                            'admirable, commendable, creditable, laudable, meritorious, praiseworthy'),
                                    TestWay('adj',
                                            '悲惨的, 可悲的',
                                            'of a kind to cause great distress',
                                            ["Many of them work under deplorable conditions. 许多人的工作环境十分悲惨。"],
                                            'distressful, distressing, grievous, heartbreaking, heartrending, lamentable, tragic, unfortunate, woeful')]),
                              Word('dike', "",
                                   [TestWay('n',
                                            '堤坝, 水坝',
                                            'a bank usually of earth constructed to control or confine water',
                                            ["An elaborate system of dikes was built to protect the lowlands from the relentless onslaught of the sea. 建立了一套精密复杂的堤坝系统, 使低地不再受到海水的无情侵袭。"],
                                            'dam, embankment, levee'),
                                    TestWay('n',
                                            '水沟, 水渠',
                                            'a long narrow channel dug in the earth',
                                            ["Water flowed along the dike to the small pond. 水沿着沟渠流入小池塘。"],
                                            'ditch, gutter, trench')]),
                              Word('escort', "",
                                   [TestWay('n',
                                            '护卫队, 护送者',
                                            'a person or group of persons accompanying another to give protection or as a courtesy',
                                            ["The mayor served as the First Lady's escort for her tour of the city. 市长陪同第一夫人参观了城市。"],
                                            'attendant, companion, guard, guide'),
                                    TestWay('vt',
                                            '同行, 护送',
                                            'to go along with in order to provide assistance, protection, or companionship',
                                            ["Asenior student from the college escorted my parents and me on our tour of the campus. 来自学院的一个师兄陪同我和我父母参观了校园。", "a VIP escorted by an army of bodyguards and journalists 被一群保镖和记者包围的重要人物"],
                                            'accompany, attend, chaperone, companion, company, convoy, squire',
                                            'abandon, desert, ditch, dump, forsake')]),
                              Word('felony', "",
                                   [TestWay('n',
                                            '重罪',
                                            'one of several grave crimes, such as murder, rape, or burglary, punishable by a more stringent sentence than that given for a misdemeanor',
                                            ["a felony punishable by life imprisonment 可被判处无期徒刑的重罪"],
                                            'crime',
                                            'misdemeanor, peccadillo')]),
                              Word('grumble', "",
                                   [TestWay('vi',
                                            '(尤指低声地)抱怨, 埋怨',
                                            'to complain in a surly manner; mutter discontentedly',
                                            ["The governed will always find something to grumble about. (Crane Brinton) 被统治者总能找到发牢骚的理由。——瑞恩·布林顿"],
                                            'carp, croak, fuss, gripe, grouch, grouse, grump, moan, murmur, mutter, repine',
                                            'crow, delight, rejoice')])])

list28_unit10 = VocabularyList([Word('heckle', "",
                                   [TestWay('vt',
                                            '起哄, 使难堪',
                                            'to harass and try to disconcert with questions, challenges, or gibes',
                                            ["a controversial player who was constantly heckled by the fans 一个时常被粉丝起哄的有争议的歌手", "Several protesters were heckling the speaker at the rally. 不少示威者在集会上起哄让发言者难堪"],
                                            'badger, bait, hassle, haze, hector, needle, ride, taunt')]),
                              Word('lag', "",
                                   [TestWay('adj',
                                            '最终的, 最后的',
                                            'following all others of the same kind in order or time',
                                            ["We're now in the lag end of the project. 现在我们到了项目的尾声阶段。"],
                                            'bottommost, closing, concluding, final, hindmost, last, latest, rearmost, terminal, terminating, ultimate',
                                            'beginning, earliest, first, foremost, inaugural, initial, maiden, opening, original, pioneer, primary'),
                                    TestWay('vi',
                                            '缓慢行走',
                                            'to proceed or develop with comparative slowness',
                                            ["The tired puppy was lagging behind the rest of the pack. 疲倦的小狗在队伍的后面缓缓地走着。"],
                                            'crawl, creep, dally, dawdle, dillydally, linger, loiter, mope, poke, tarry',
                                            'blast, bolt, bustle, careen, career, dash, fly, hustle, rush, rustle, speed, whirl'),
                                    TestWay('vi',
                                            '萎靡, 失去活力',
                                            'to lose bodily strength or vigor',
                                            ["During the fourth quarter the whole team seemed to lag. 到了第四节整支队伍似乎都已经精疲力竭了。"],
                                            'decay, droop, emaciate, fade, fail, languish, sink, waste, wilt, wither',
                                            'convalesce, rally, rebound, recover, recuperate',
                                            'lagging n. 延迟')]),
                              Word('lance', "",
                                   [TestWay('n',
                                            '长矛, 标枪',
                                            'a weapon with a long straight handle and sharp head or blade',
                                            ["The lance struck squarely on the knight's shield, knocking him from his horse. 标枪正中盾牌, 将骑士掀于马下。"],
                                            'javelin, pike, shaft, spear'),
                                    TestWay('vt',
                                            '刺穿, 刺破',
                                            'to penetrate or hold (something) with a pointed object',
                                            ["Doctors used to lance infected sores, so that they could drain clean. 以前医生会刺破受感染的疮, 从而使脓液流出。"],
                                            'gore, harpoon, jab, pierce, puncture, spike, stab, stick',
                                            'lancer n. 枪骑兵')]),
                              Word('magnitude', "",
                                   [TestWay('n',
                                            '重要, 重大',
                                            'greatness in significance or influence',
                                            ["The magnitude of the issue is severely underestimated. 这个事件的重要性被严重低估了。"],
                                            'account, consequence, importance, moment, momentousness, significance, weight, weightiness',
                                            'insignificance, littleness, puniness, slightness, smallness, triviality'),
                                    TestWay('n',
                                            '巨大',
                                            'greatness in size or extent',
                                            ["The mountain's sheer magnitude usually leaves tourists speechless. 巨大的山脉往往让旅游者哑口无言。"],
                                            'enormousness, giantism, gigantism, hugeness, immenseness, massiveness, prodigiousness, vastness',
                                            'diminutiveness, minuteness, tininess')]),
                              Word('maneuver', "",
                                   [TestWay('vt',
                                            '巧妙地操纵',
                                            'to guide with adroitness and design or to bring about or secure as a result of skillful management',
                                            ["They maneuvered him into signing the contract. 他们巧妙地诱使他签下合同。", "The host maneuvered the conversation so as to avoid the touchy subject of her divorce. 主人巧妙地控制着对话的内容, 以避免触及有关她离婚的敏感话题。"],
                                            'contrive, finagle, finesse, frame, machinate, manipulate, mastermind, negotiate, wangle',
                                            'botch, bungle, fumble, mishandle, muff, scamp, mess up')]),
                              Word('rampant', "",
                                   [TestWay('adj',
                                            '(植物)生长茂盛的',
                                            'growing thickly and vigorously',
                                            ["a rampant growth of weeds in the neglected yard 被遗忘的院子里杂草疯长"],
                                            'lush, luxuriant, prosperous, weedy',
                                            'sparse'),
                                    TestWay('adj',
                                            '猖獗的, 不受限制的',
                                            'occurring without restraint and frequently, widely, or menacingly',
                                            ["Mayor promised to put a stop to the rampant crime that plagued the city. 市长承诺要采取措施, 消灭那些扰乱城市治安的猖獗的犯罪活动。", "rampant corruption in city government 市政府中猖獗的腐败"],
                                            'abandoned, intemperate, runaway, unbounded, unbridled, unchecked, uncontrolled, unhampered, unhindered, unrestrained',
                                            'bridled, checked, constrained, controlled, curbed, governed, hampered, hindered, restrained, temperate')]),
                              Word('remnant', "",
                                   [TestWay('n',
                                            '残余, 剩余物',
                                            'something left over',
                                            ["a remnant of his past glory 他辉煌过去的一丝残余", "The shop is selling remnants of cloth at half price. 商店在半价抛售剩余的衣物"],
                                            'debris, remainder, remains, residue, vestige')]),
                              Word('residual', "",
                                   [TestWay('adj',
                                            '剩余的, 残存的',
                                            'of, relating to, or characteristic of a residue',
                                            ["residual radiation from nuclear tests 核试验所遗留下来的残余辐射"],
                                            'leftover, remaining, vestigial',
                                            'comprehensive, entire, full, integral, total, whole')]),
                              Word('screen', "",
                                   [TestWay('n',
                                            '掩护物, 屏障',
                                            'something that shelters, protects, or hides',
                                            ["The target will be difficult to reach as it is behind a screen of anti-aircraft batteries. 目标在防空炮火的掩护之下难以靠近。", "Please keep away from the screen door. 请不要倚靠屏蔽门。"],
                                            'aegis, ammunition, armor, cover, guard, protection, safeguard, security, shield, wall, ward'),
                                    TestWay('vt',
                                            '保护, 使…免受攻击',
                                            'to drive danger or attack away from',
                                            ["Gunships were called in to help screen the troops from further attacks. 武装直升机被呼叫对步兵进行支援, 使之免受进一步的攻击。"],
                                            'defend, fence, fend, forfend, protect, secure',
                                            'assail, assault, attack'),
                                    TestWay('vt',
                                            '掩护, 遮蔽',
                                            'to keep secret or shut off from view',
                                            ["Bushes screened the swimming pool from passersby on the street. 灌木丛将游泳池和外面的行人隔绝开来。"],
                                            'belie, cloak, conceal, curtain, disguise, enshroud, mask, obscure, occult, shroud, veil',
                                            'disclose, expose, reveal, uncloak, uncover, unmask, unveil')]),
                              Word('scrimp', "",
                                   [TestWay('vi',
                                            '节俭',
                                            'to avoid unnecessary waste or expense',
                                            ["They had to scrimp and save for years in order to be able to afford a house. 他们不得不节俭度日才能攒够钱买房。"],
                                            'conserve, economize, husband, pinch, save, skimp, spare',
                                            'dissipate, lavish, squander, waste')])])

LIST28 = VocabularyList(list28_unit1.words+list28_unit2.words+list28_unit3.words+list28_unit4.words+list28_unit5.words+list28_unit6.words+list28_unit7.words+list28_unit8.words+list28_unit9.words+list28_unit10.words)
