#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list24_unit1 = VocabularyList([Word('spent', "",
                                   [TestWay('adj',
                                            '精疲力竭的',
                                            'drained of energy or effectiveness',
                                            ["After all that exertion, we were completely spent. 在完成所有的锻炼之后我们已是筋疲力尽。"],
                                            'beaten, bleary, done, drained, enervate, exhausted, fatigued, jaded, prostrate, tired, wearied, worn-out',
                                            'active, energetic, invigorated, peppy, strengthened, strong, tireless, vitalized, weariless')]),
                              Word('spindly', "",
                                   [TestWay('adj',
                                            '细长纤弱的',
                                            'frail or flimsy in appearance or structure',
                                            ["I prefer having rather spindly legs. 我更希望有一双细腿。"],
                                            'gangling, gangly, lanky, spindling',
                                            'squat')]),
                              Word('spiny', "",
                                   [TestWay('adj',
                                            '多刺的',
                                            'bearingspines, prickles, or thorns',
                                            ["low spiny bushes of sage 低矮多刺的长满鼠尾草的灌木丛"],
                                            'brambly, prickly, thorny',
                                            'even, flat, plane, smooth'),
                                    TestWay('adj',
                                            '棘手的, 麻烦的',
                                            'requiring exceptional skill or caution in performance or handling',
                                            ["This promises to be a spiny problem to negotiate. 这有可能成为谈判过程中棘手的问题。"],
                                            'catchy, delicate, difficult, knotty, problematic, sensitive, sticky, ticklish, thorny, tough, troublesome',
                                            'easy, effortless, manageable, painless, simple, straightforward, uncomplicated, undemanding')]),
                              Word('spleen', "",
                                   [TestWay('n',
                                            '怒气, 怨恨',
                                            'feelings of anger or ill will often suppressed',
                                            ["She vented her spleen on her boyfriend and felt much better for having done so. 在她把怒气一股脑地倾泻到她男朋友身上之后, 她感觉好多了。"],
                                            'angriness, choler, furor, fury, indignation, ire, madness, outrage, rage, wrath',
                                            'delight, pleasure')]),
                              Word('splice', "",
                                   [TestWay('vt',
                                            '接合, 叠接',
                                            'to unite (as two ropes) by interweaving the strands, or to join (as two pieces of film) at the ends',
                                            ["He taught me to edit and splice film. 他教会我如何剪辑和叠合胶卷。"],
                                            'associate, coalesce, combine, conjoin, conjugate, connect, couple, fuse, interfuse, join, link, marry, unify',
                                            'disassociate, disconnect, disjoin, divide, sever, split, sunder')]),
                              Word('spontaneous', "",
                                   [TestWay('adj',
                                            '自发的, 不经思索的',
                                            'acting or activated without apparent thought or deliberation',
                                            ["Hugging a crying child is simply a spontaneous reaction. 去抱一个哭泣的小孩是很自然而然的反应。"],
                                            'automatic, impulsive, instinctive, involuntary, mechanical, natural',
                                            'calculated, deliberate, intentional, planned, predetermined, premeditated, studied')]),
                              Word('spoof', "",
                                   [TestWay('n',
                                            '轻松幽默的模仿, 小恶搞',
                                            'a work that imitates and exaggerates another work for comic effect',
                                            ["Many viewers thought that the spoof of a television newscast was the real thing. 许多观众认为这则新闻报道被恶搞之后的作品才是真实的东西。"],
                                            'burlesque, caricature, mimicking, parody, travesty'),
                                    TestWay('v',
                                            '诱骗, 诱使相信',
                                            'to cause to believe what is untrue',
                                            ["The public was spoofed by a supposedly plausible report of a UFO encounter.一个听起来真实的UFO 遭遇报告欺骗了大众。"],
                                            'beguile, cozen, delude, dupe, fool, hoax, misguide, misinform, mislead, trick',
                                            'disabuse, disenchant, disillusion, undeceive')]),
                              Word('sporadic', "",
                                   [TestWay('adj',
                                            '偶尔的, 零星发生的',
                                            'not often occurring or repeated',
                                            ["On the whole, situation has significantly improved with only sporadic disturbances. 总体而言, 局势得到了明显的改善, 现在只有偶尔发生的骚乱。"],
                                            'few, infrequent, occasional, odd, rare, scarce, seldom, uncommon',
                                            'frequent, habitual, repeated')]),
                              Word('sprawl', "",
                                   [TestWay('vt',
                                            '杂乱无序地发展',
                                            'to grow, develop, or spread irregularly and without apparent design or plan',
                                            ["The city sprawls down the whole coast. 城市顺着整条海岸线蔓延。"],
                                            'ramble, scramble, straddle',
                                            'sprawling adj. 蔓延的, 不规则伸展的')]),
                              Word('sprightly', "",
                                   [TestWay('adj',
                                            '活泼的, 充满活力的',
                                            'full of spirit and vitality',
                                            ["He was deeply impressed by the sprightly Gypsy dance. 活力四射的吉普赛舞蹈给他留下了深刻印象。"],
                                            'active, airy, animated, brisk, energetic, frisky, gay, jaunty, kinetic, mettlesome, racy, spirited, vital, vivacious',
                                            'dead, inactive, inanimate, lackadaisical, languid, languishing, leaden, lifeless, listless, spiritless, vapid')])])

list24_unit2 = VocabularyList([Word('spur', "",
                                   [TestWay('n',
                                            '刺激物',
                                            'something that arouses action or activity',
                                            ["The threat of losing its only sports franchise was the spur the city council needed to finally do something about the rising crime rate. 有可能失去唯一的体育赛事举办权带来的威胁, 成为了刺激市政府决定就攀升的犯罪率采取相关措施的因素。"],
                                            'boost, catalyst, impetus, incentive, incitement, instigation, momentum, motivation, provocation, stimulus',
                                            'deterrent, disincentive'),
                                    TestWay('n',
                                            '支撑物',
                                            'a structure that holds up or serves as a foundation for something else',
                                            ["a weak wall that might need a spur 一面或许需要支撑的墙"],
                                            'brace, buttress, mount, prop, reinforcement, shore, underpinning'),
                                    TestWay('vt',
                                            '刺激, 激励',
                                            'to incite or stimulate',
                                            ["Appreciation spurred his ambition. 赞扬激起了他的雄心壮志。"],
                                            'arouse, excite, exhort, goad, instigate, prod, stir, urge',
                                            'bridle, check, constrain, curb, deter, fetter, hamper, inhibit, manacle, shackle')]),
                              Word('spurious', "",
                                   [TestWay('adj',
                                            '假的, 伪造的',
                                            'lacking authenticity or validity in essence or origin; not genuine',
                                            ["In statistics, a spurious relationship is a mathematical relationship in which two events or variables have no direct causal connection, but it may be wrongly inferred that they do, due to either coincidence or the presence of a certain third, unseen factor. 在统计学中, “伪相关关系”是两个不存在因果关联的事件或变量, 因为巧合或是不可见的第三方因素, 而被误判为存在因果联系的关系。"],
                                            'apocryphal, bogus, counterfeit, fake, forged, phony, sham',
                                            'authentic, bona fide, genuine, real',
                                            'spuriously adv. 伪造地, 虚假地')]),
                              Word('spurn', "",
                                   [TestWay('vt',
                                            '摈弃, 拒绝',
                                            'to reject with disdain or contempt',
                                            ["spurned his recommendation 拒绝了他的推荐‖Fiercely independent, the elderly couple spurned all offers of financial help. 这对老夫妻极其独立, 回绝了所有经济上援助。"],
                                            'decline, disapprove, negative, refuse, reject, reprobate, repudiate',
                                            'accede, accept, agree, approve, assent, consent, embrace',
                                            'spurned adj. 被摒弃的, 被拒绝的')]),
                              Word('squabble', "",
                                   [TestWay('n',
                                            '口角, 小争吵',
                                            'a noisy quarrel, usually about a trivial matter',
                                            ["a brief squabble over what to do next 关于接下来该做什么的争吵"],
                                            'altercation, argument, controversy, disagreement, dispute, imbroglio, quarrel, riff, spat, skirmish, wrangle',
                                            'harmony')]),
                              Word('squalid', "",
                                   [TestWay('adj',
                                            '污秽的, 肮脏的',
                                            'dirty and wretched',
                                            ["The migrants have been living in squalid conditions. 移民们一直居住在肮脏的条件下。"],
                                            'black, dirty, filthy, foul, impure, nasty, slipshod, slovenly, unclean',
                                            'clean, immaculate, spotless, unsoiled, unsullied'),
                                    TestWay('adj',
                                            '道德败坏的',
                                            'morally repulsive',
                                            ["the squalid atmosphere of intrigue and betrayal 充满了阴谋与背叛的不正之风"],
                                            'base, despicable, ignoble, scurvy, sordid, vile, wretched',
                                            'moral, noble')]),
                              Word('squall', "",
                                   [TestWay('n',
                                            '(通常伴随着雨或雪的)风暴, 暴风雪',
                                            'a brief, sudden, violent windstorm, often accompanied by rain or snow',
                                            ["A snow squall is expected tonight. 今晚预计有暴风雪。"],
                                            'blizzard, hailstorm, snowstorm, tempest'),
                                    TestWay('vt',
                                            '尖叫',
                                            'to scream or cry loudly and harshly',
                                            ["The baby squalled in pain. 婴儿因为疼痛而大叫。"],
                                            'cry, howl, screech, shout, shriek, shrill, squeal, thunder, yelp, yell',
                                            'murmur, mutter, whisper')]),
                              Word('squander', "",
                                   [TestWay('vt',
                                            '使分散',
                                            'to cause (members of a group) to move widely apart',
                                            ["A single blast of the shotgun squandered the herd of deer. 猎枪的一声枪响让鹿群四处逃窜。"],
                                            'disband, dispel, disperse',
                                            'assemble, cluster, collect, concentrate, congregate, gather, ingather'),
                                    TestWay('vt',
                                            '浪费',
                                            'to spend wastefully or extravagantly',
                                            ["He squandered his inheritance on women and gambling. 他把他继承的遗产浪费在女人和赌博上。"],
                                            'blow, dissipate, fritter, lavish, misspend, waste',
                                            'conserve, husband',
                                            'squandering adj. 浪费的')]),
                              Word('squat', "",
                                   [TestWay('adj',
                                            '又矮又胖的',
                                            'being compact and broad in build and often short in stature',
                                            ["a squat but adroit craftsman 一个又胖又矮, 但是手艺灵巧的工匠"],
                                            'chunky, dumpy, heavyset, squatty, stocky, stout, stubby, stumpy, thickset',
                                            'gangling, lanky')]),
                              Word('squint', "",
                                   [TestWay('vt',
                                            '斜视, 睥睨',
                                            'to look or glance sideways',
                                            ["The driver squinted as the sun hit his windshield. 阳光使得驾驶员不得不把眼睛偏向一边"],
                                            'leer',
                                            'gaze, goggle')]),
                              Word('squelch', "",
                                   [TestWay('vt',
                                            '压制, 镇压(运动)',
                                            'to put a stop to (something) by the use of force',
                                            ["The authority tried to squelch the workers’ protest. 政府试图镇压工人的游行。"],
                                            'crush, muffle, quell, repress, squash, subdue, suppress, crack down',
                                            'abet, aid, assist, back, help, support, prop up'),
                                    TestWay('vt',
                                            '击溃, 使无言以对',
                                            'to put down or silence, as with a crushing retort',
                                            ["His irritated glare squelched any other potential objectors. 他怒目而视, 使得其他的反对者都不敢说话。"],
                                            'dumb, extinguish, mute, quiet, settle, still, shut up',
                                            'foment, incite, instigate, provoke, stir',
                                            'squelcher n. 镇压者')])])

list24_unit3 = VocabularyList([Word('stabilize', "",
                                   [TestWay('vt./vi',
                                            '使稳定; 变得稳定',
                                            'to make stable, steadfast, or firm; to become stable, steadfast, or fixed',
                                            ["a policy that intended to stabilize the situation in Iraq 一项旨在维护伊拉克局势稳定的政策", "The country's population has stabilized at 3.2 million. 这个国家的人口维持在三百二十万。"],
                                            'ballast, poise, steady',
                                            'destabilize, overthrow, overturn, subvert',
                                            'stability n. 稳定性')]),
                              Word('stalwart', "",
                                   [TestWay('adj',
                                            '无所畏惧的',
                                            'feeling or displaying no fear by temperament',
                                            ["the stalwart soldiers in the army of Alexander the Great, who willingly followed him to the ends of the known world 亚历山大大帝军队中无所畏惧的士兵们, 他们愿意跟随亚历山大奔赴世界的尽头"],
                                            'bold, courageous, dauntless, fearless, gallant, intrepid, manful, stout, stouthearted, valiant, valorous',
                                            'cowardly, craven, fearful, gutless, nerveless, pusillanimous, spineless, spiritless, timorous'),
                                    TestWay('adj',
                                            '(体魄等)强健的',
                                            'marked by outstanding strength and vigor of body, mind, or spirit',
                                            ["a stalwart supporter of the UN 联合国的坚定支持者", "a lithe yet stalwart athlete 瘦小但结实的运动员"],
                                            'brawny, firm, muscular, rugged, sinewy, sound, stout, strong, sturdy',
                                            'delicate, feeble, frail, weak, wimpy')]),
                              Word('stamina', "",
                                   [TestWay('n',
                                            '耐力',
                                            'physical or moral strength to resist or withstand illness, fatigue, or hardship',
                                            ["A marathon challenges a runner's stamina. 马拉松挑战参赛者的耐力。"],
                                            'endurance, tolerance',
                                            'frailty')]),
                              Word('stammer', "",
                                   [TestWay('vi',
                                            '口吃, 结巴',
                                            'to speak with involuntary pauses or repetitions',
                                            ["The frightened child started to stammer. 受惊吓的小孩开始结巴地说话。"],
                                            'falter, stutter',
                                            'articulate')]),
                              Word('startle', "",
                                   [TestWay('vt',
                                            '使吓一跳, 使大吃一惊',
                                            'to frighten or surprise suddenly and usually not seriously',
                                            ["They were startled at the prohibitive price. 他们被高得离谱的价格吓到了"],
                                            'amaze, astonish, astound, dumbfound, rock, scare, shock, stun, stupefy',
                                            'reassure',
                                            'startling adj. 惊人惊奇的')]),
                              Word('static', "",
                                   [TestWay('adj',
                                            '静态的, 停滞的',
                                            'characterized by a lack of movement, animation, or progression',
                                            ["Both your pictures are of static subjects. 你的两张照片都是静物。‖a static economy 停滞不前的经济"],
                                            'inactive, fixed, immobile, immotile, immovable, inert, stable, stagnant, stationary, still',
                                            'active, dynamic, lively, vibrant, mobile, movable'),
                                    TestWay('adj',
                                            '无改变的',
                                            'showing little change',
                                            ["a static population 没有变化的人口"],
                                            'inflexible, invariable, rigid, stiff, steadfast',
                                            'capricious, changeful, fluid, mercurial, temperamental, versatile, volatile',
                                            'stasis n. 静止不变')]),
                              Word('stature', "",
                                   [TestWay('n',
                                            '高度, 身高',
                                            'natural height (as of a person) in an upright position',
                                            ["a man of surprisingly great stature 拥有惊人身高的人"],
                                            'altitude, elevation, inches'),
                                    TestWay('n',
                                            '才干, 水平',
                                            'quality or status gained by growth, development, or achievement',
                                            ["This club has grown in stature over the last 20 years. 二十年间这家俱乐部的水平得到了提升。"],
                                            'merit, quality, value, virtue, worth')]),
                              Word('steadfast', "",
                                   [TestWay('adj',
                                            '坚定的, 忠诚的',
                                            'firm in belief, determination, or adherence',
                                            ["Her comrades remained steadfast despite brutal tortures. 尽管有残酷的折磨, 她的同志们都保持了忠诚。"],
                                            'constant, dedicated, devoted, devout, loyal, pious, staunch, steady, true-blue',
                                            'disloyal, perfidious, recreant, traitorous, treacherous, unfaithful')]),
                              Word('stealth', "",
                                   [TestWay('n',
                                            '秘密行动',
                                            'the act or action of proceeding furtively, secretly, or imperceptibly',
                                            ["Both sides advanced by stealth. 双方都隐秘地行军。"]),
                                    TestWay('adj',
                                            '秘密的',
                                            'intended not to attract attention',
                                            ["The SWAT team carried out a stealth raid on the house, which was believed to be harboring a terrorist cell. 特警们对这间被认为是恐怖分子老巢的房屋进行了秘密的突袭。"],
                                            'backstairs, clandestine, covert, furtive, private, sneak, stealthy, surreptitious, undercover, underground',
                                            'open, overt, public',
                                            'stealthy adj. 秘密的, 隐秘的')]),
                              Word('steep', "",
                                   [TestWay('vt',
                                            '浸泡',
                                            'to make thoroughly wet',
                                            ["steep the tea for five minutes 浸泡茶叶五分钟"],
                                            'drench, drown, impregnate, macerate, saturate, sodden, sop, souse',
                                            'desiccate, dry, parch, sear, wring'),
                                    TestWay('adj',
                                            '陡峭的',
                                            'having an incline approaching the perpendicular',
                                            ["a very steep rock face that is nearly impossible to climb 一面非常陡峭以至于不可能攀爬的岩石"],
                                            'abrupt, precipitate, sheer',
                                            'gradual, flat'),
                                    TestWay('adj',
                                            '过分的, 过高的',
                                            'going beyond a normal or acceptable limit in degree or amount',
                                            ["We would like to hire him, but his salary demands are just too steep. 我们很想雇用他, 可是他对于薪水的要求实在是太高了。"],
                                            'exorbitant, extravagant, extreme, immoderate, inordinate, insane, lavish, overdue, overweening, plethoric, stiff',
                                            'moderate, modest, reasonable, temperate')])])

list24_unit4 = VocabularyList([Word('stench', "",
                                   [TestWay('n',
                                            '臭气, 恶臭',
                                            'a strong, foul odor',
                                            ["We finally discovered the dead rat that was causing the stench in the living room. 我们终于发现是死老鼠带来了卧室里的恶臭。"],
                                            'fetor, funk, malodor, reek, stink',
                                            'aroma, fragrance, perfume, scent')]),
                              Word('stentorian', "",
                                   [TestWay('adj',
                                            '声音洪亮的',
                                            'extremely loud',
                                            ["an tenor with a stentorian voice 拥有洪亮声音的男高音", "The professor's stentorian voice was enough to keep even the drowsiest student awake. 教授洪亮的声音足以使最困的学生保持清醒。"],
                                            'blaring, blasting, clamorous, deafening, earsplitting, plangent, resounding, roaring, sonorous, thunderous',
                                            'gentle, low, soft')]),
                              Word('sterile', "",
                                   [TestWay('adj',
                                            '贫瘠的',
                                            'not productive or effective',
                                            ["a sterile land which used to be a forest 曾经是森林的一块贫瘠土地"],
                                            'barren, effete, fruitless, impotent, infertile',
                                            'verdant, fat, fertile, fruitful'),
                                    TestWay('adj',
                                            '无菌的',
                                            'free from live bacteria or other microorganisms',
                                            ["The hospitals in the war-torn city often lack necessary drugs and sterile surgical supplies. 在这个被战争所蹂躏的城市中的医院通常缺乏必需的药物和无菌的手术用品。"],
                                            'aseptic, germfree, hygienic',
                                            'insanitary, unhygienic, contaminated, polluted',
                                            'sterilize v. 消毒, 杀菌')]),
                              Word('stickler', "",
                                   [TestWay('n',
                                            '坚持细节的人, 一丝不苟的人',
                                            'one who insists on exactness or completeness in the observance of something',
                                            ["a stickler for perfection 完美主义者", "a stickler for neatness 有洁癖的人"],
                                            'disciplinarian, pedant, purist, martinet')]),
                              Word('stiff', "",
                                   [TestWay('adj',
                                            '僵硬的, 无法弯曲的',
                                            'lacking in suppleness or flexibility',
                                            ["a stiff cardboard packing box 不易弯折的硬纸板盒", "When I got out of bed this morning my back was stiff as a board. 今早起床时我的背和木板一样僵硬。"],
                                            'immalleable, impliable, inflexible, petrified, rigid, unbending, unyielding',
                                            'flexible, floppy, pliable, pliant, supple, yielding'),
                                    TestWay('adj',
                                            '(在社交场合)缺乏优雅的, 不自在的',
                                            'lacking social grace and assurance',
                                            ["She always felt stiff and ill-at-ease whenever she was introduced to her father's friends. 只要她被介绍给父亲的朋友, 她就会感到不自在和浑身不舒服。"],
                                            'clumsy, gauche, graceless, inelegant, rustic, stilted, uncomfortable, uneasy, wooden',
                                            'graceful, suave, urbane'),
                                    TestWay('adj',
                                            '过分的, 过高的',
                                            'going beyond a normal or acceptable limit in degree or amount',
                                            ["Don't you think that's a pretty stiff fine for such a minor infraction? 你难道不觉得对于这么小的一个错误, 罚款实在太高了么？"],
                                            'exorbitant, extravagant, extreme, immoderate, inordinate, insane, lavish, overdue, overweening, plethoric, steep',
                                            'moderate, modest, reasonable, temperate'),
                                    TestWay('adj',
                                            '艰苦的, 费力的',
                                            'requiring considerable physical or mental effort',
                                            ["We'll have a stiff climb to actually reach the summit. 我们还有一段艰苦的征途才能登顶。"],
                                            'arduous, challenging, difficult, formidable, grueling, laborious, strenuous, sweaty, testing, toilsome, tough',
                                            'easy, effortless, facile, light, mindless, simple, soft, undemanding')]),
                              Word('stifle', "",
                                   [TestWay('vt',
                                            '抑制(声音、呼吸等)',
                                            'to keep in or hold back',
                                            ["to stifle free expression 限制言论自由"],
                                            'choke, muffle, mute, repress, smother, strangle, suffocate, suppress',
                                            'foment, incite, instigate, provoke, stir',
                                            'stifling adj. 抑制的')]),
                              Word('stigma', "",
                                   [TestWay('n',
                                            '耻辱, 污名',
                                            'a mark of shame or discredit',
                                            ["the stigma of cowardice 由懦弱而带来的污点", "There's a social stigma attached to receiving welfare. 伴随着社会福利有一种社会耻辱感。"],
                                            'blemish, brand, onus, slur, smirch, smudge, spot, stain, taint',
                                            'award, credit, honor, fame, glory, renown, repute')]),
                              Word('stint', "",
                                   [TestWay('vt',
                                            '吝惜, 节省',
                                            'to be sparing or frugal',
                                            ["They never stint with their praise. 他们从不吝啬他们的赞美之词。"],
                                            'scrimp, skimp',
                                            'blow, dissipate, fritter, lavish, misspend, squander, waste')]),
                              Word('stingy', "",
                                   [TestWay('adj',
                                            '小气的, 吝啬的',
                                            'being unwilling or showing unwillingness to share with others',
                                            ["too stingy to tip the waiter 小气到不肯给小费"],
                                            'closefisted, mean, mingy, miserly, niggardly, parsimonious, penurious, sparing, stinting, tightfisted',
                                            'bountiful, charitable, freehanded, generous, liberal, munificent, openhanded'),
                                    TestWay('adj',
                                            '极少量的',
                                            'less plentiful than what is normal, necessary, or desirable',
                                            ["Many people may consider this a rather stingy amount of food. 很多人都会认为这是分量比较少的食物。"],
                                            'exiguous, poor, scant, scanty, scarce, skimpy, sparse',
                                            'abundant, ample, bounteous, copious, plenteous, plentiful',
                                            'stinginess n. 小气')]),
                              Word('stipple', "",
                                   [TestWay('vt',
                                            '点刻, 用点标记',
                                            'to mark with small spots especially unevenly',
                                            ["They crossed a field stippled with purple lavender. 他们穿越了一片有紫色薰衣草点缀的田野。"],
                                            'blotch, dapple, dot, freckle, marble, mottle, speckle, splotch, sprinkle, spot')])])

list24_unit5 = VocabularyList([Word('stipulate', "",
                                   [TestWay('vt',
                                            '规定, 特定要求',
                                            'to specify or arrange in an agreement',
                                            ["Total disarmament was stipulated in the peace treaty. 和平协约中要求彻底解除武装。"],
                                            'claim, designate, detail, particularize, qualify',
                                            'relinquish, surrender, yield, waive',
                                            'stipulation n. 规范, 要求')]),
                              Word('stitch', "",
                                   [TestWay('n',
                                            '突然剧痛',
                                            'a sharp unpleasant sensation usually felt in some specific part of the body',
                                            ["He had to drop out of the race when the stitch in his side became too painful. 因为他突然感到剧痛, 所以不得不放弃比赛。"],
                                            'ache, pang, prick, shoot, smart, sting, throe, tingle, twinge',
                                            'comfort, ease, easiness')]),
                              Word('stock', "",
                                   [TestWay('n',
                                            '库存, 储备',
                                            'the inventory of goods of a merchant or manufacturer',
                                            ["This type of product is currently out of stock. 这种商品已经脱销。"],
                                            'inventory, pool, repertoire, reserve, reservoir'),
                                    TestWay('adj',
                                            '普通的, 常备的',
                                            'commonly used or brought forward',
                                            ["the stock answers to sensitive questions 对于敏感问题的常备回答"],
                                            'common, conventional, general, ordinary, prosaic, routine, standard, universal',
                                            'unique')]),
                              Word('stockade', "",
                                   [TestWay('n',
                                            '栅栏, 围栏',
                                            'an enclosure or pen made with posts and stakes',
                                            ["a heavy stockade that protected the troops 保护驻扎部队的厚厚的栅栏"],
                                            'barricade, barrier, blockade, fence, wall'),
                                    TestWay('n',
                                            '监狱',
                                            'a place of confinement for persons held in lawful custody',
                                            ["All POWs were kept in a remote stockade. 所有的战俘都被关在一个遥远的监狱里。"],
                                            'bastille, coop, jail, pen, prison')]),
                              Word('stodgy', "",
                                   [TestWay('adj',
                                            '平庸的, 乏味的',
                                            'dull, unimaginative, and commonplace',
                                            ["The sitcom was offbeat and interesting in its first season, but has since become predictable and stodgy. 这部情景喜剧在第一季是离奇而有趣的, 但是近来变得老套和乏味。"],
                                            'arid, dreary, dull, flat, jading, jejune, monochromatic, monotonous, pedestrian, stale, tedious, wearisome',
                                            'absorbing, engaging, engrossing, gripping, interesting, intriguing, involving, riveting'),
                                    TestWay('adj',
                                            '非常守旧的',
                                            'extremely old-fashioned',
                                            ["Without notice she received a letter from his stodgy father. 她毫无征兆地收到了一封来自她保守父亲的信。"],
                                            'conservative, hidebound, intolerant',
                                            'avant-guard, radical',
                                            'stodginess n. 乏味, 无趣')]),
                              Word('stoke', "",
                                   [TestWay('vt',
                                            '添加燃料',
                                            'supply with fuel',
                                            ["She was stoking the furnace. 她正用给火炉添木头。"],
                                            'fuel, rekindle'),
                                    TestWay('vt',
                                            '增大, 促进',
                                            'to make greater in size, amount, or number',
                                            ["stoke workers’ commitment to the company by raising their salaries 通过加薪来􁨀升员工对公司的忠诚度"],
                                            'aggrandize, amplify, augment, boost, enlarge, escalate, expand, extend, multiply, raise',
                                            'abate, decrease, diminish, downsize, dwindle, lessen, lower, minify, reduce, subtract')]),
                              Word('stoic', "",
                                   [TestWay('adj',
                                            '隐忍的, 冷静的',
                                            'seemingly indifferent to or unaffected by pleasure or pain',
                                            ["stoic resignation in the face of hunger 默默忍受着饥饿"],
                                            'aloof, apathetic, detached, forbearing, indifferent, impassive, phlegmatic, stolid, tolerant, unemotional',
                                            'demonstrative, emotional, fervent, fervid, impassioned, passionate, vehement')]),
                              Word('stolid', "",
                                   [TestWay('adj',
                                            '无动于衷的, 感情麻木的',
                                            'having or revealing little emotion or sensibility',
                                            ["Her face showed nothing but stolid indifference. 她的脸上只露出了麻木和冷漠。"],
                                            'apathetic, catatonic, deadpan, emotionless, impassive, indifferent, numb, phlegmatic, stoic',
                                            'demonstrative, emotional, fervent, fervid, impassioned, passionate, vehement',
                                            'stolidity n. 麻木, 无动于衷')]),
                              Word('stomach', "",
                                   [TestWay('v',
                                            '容忍',
                                            'to bear without overt reaction or resentment',
                                            ["I can't stomach his bragging. 我受不了他自吹自擂了。"],
                                            'abide, brook, countenance, endure, handle, stand, tolerate',
                                            'decline, refuse, reject, repudiate, spurn')]),
                              Word('stonewall', "",
                                   [TestWay('v',
                                            '拒绝(合作), 阻挠',
                                            'to be uncooperative, obstructive, or evasive',
                                            ["lobbying efforts to stonewall passage of the legislation 意在阻止法律通过的游说行动"],
                                            'blockade, filibuster, hinder, impede, obstruct',
                                            'collaborate, cooperate')])])

list24_unit6 = VocabularyList([Word('stouthearted', "",
                                   [TestWay('adj',
                                            '勇敢的',
                                            'having a stout heart or spirit',
                                            ["a stouthearted army officer who risked his life to save his men 为了拯救部下宁愿牺牲自己的勇敢军官"],
                                            'bold, brave, courageous, dauntless, fearless, gallant, intrepid, stalwart, stout, valiant, valorous',
                                            'cowardly, craven, fearful, gutless, nerveless, pusillanimous, spineless, spiritless, timorous')]),
                              Word('stratagem', "",
                                   [TestWay('n',
                                            '谋略, 策略',
                                            'an artifice or trick in war for deceiving and outwitting the enemy',
                                            ["a stratagem to secure customer loyalty 用来稳固客户忠诚度的计谋"],
                                            'artifice, device, gambit, gimmick, intrigue, maneuver, ruse, scheme, trick, wile')]),
                              Word('strait', "",
                                   [TestWay('n',
                                            '海峡',
                                            'a narrow channel joining two larger bodies of water',
                                            ["Thousands of vessels pass through the straits annually. 每年数以千计的货轮要通过这个海峡。"],
                                            'channel, narrow, neck',
                                            'isthmus'),
                                    TestWay('n',
                                            '痛苦',
                                            'a state of great suffering of body or mind',
                                            ["in dire straits over the loss of her mother’s cherished necklace 因为丢失了母亲最珍贵的项链而陷入了极端的痛苦之中"],
                                            'affliction, agony, anguish, excruciation, misery, pain, torment, torture, travail, tribulation, woe')]),
                              Word('strand', "",
                                   [TestWay('n',
                                            '绳、线之一股',
                                            'a single filament, such as a fiber or thread, of a woven or braided material',
                                            ["a strand of DNA DNA中的一条链"],
                                            'thread'),
                                    TestWay('v',
                                            '遗弃, 使置于困境',
                                            'to leave in a strange or an unfavorable place especially without funds or means to depart',
                                            ["The convoy was stranded in the desert. 车队被困在了沙漠之中。"],
                                            'abandon, desert, forsake, maroon, quit',
                                            'evacuate, reclaim, rescue')]),
                              Word('stratify', "",
                                   [TestWay('vt',
                                            '使分成各种等级',
                                            'to divide into classes, castes, or social strata',
                                            ["Income distribution often stratifies a society. 收入分配往往将社会分层"],
                                            'assort, categorize, classify, differentiate, distinguish, separate',
                                            'homogenize, commingle, mingle',
                                            'stratification n. 分层化')]),
                              Word('stray', "",
                                   [TestWay('adj',
                                            '漫无目的的',
                                            'lacking a definite plan, purpose, or pattern',
                                            ["No stray sighting of UFO’s has been rigorously analyzed by scientists. 在无规律出现的UFO 事件之中, 尚未有被科学家严谨分析的案例"],
                                            'aimless, arbitrary, desultory, erratic, haphazard, scattered, slapdash',
                                            'methodical, orderly, organized, regular, systematic, systematized'),
                                    TestWay('vi',
                                            '离群, 迷途, 偏离',
                                            'to move away from a group, deviate from the correct course, or go beyond established limits',
                                            ["to stray from the main road 偏离了主干道"],
                                            'deviate, digress, err, wander')]),
                              Word('strength', "",
                                   [TestWay('n',
                                            '力量',
                                            'the ability to exert effort for the accomplishment of a task',
                                            ["We are facing an army of great strength. 我们面对的是一支强大的军队。"],
                                            'energy, force, might, potency, power, puissance, sinew, vigor',
                                            'impotence, impotency, powerlessness, weakness'),
                                    TestWay('n',
                                            '(抵抗攻击、压力的)强度',
                                            'the ability to withstand force or stress without being distorted, dislodged, or damaged',
                                            ["This cheap shelve unit doesn't have the strength to hold all those books. 这个廉价的书架不足以支撑所有的书本。"],
                                            'firmness, soundness, sturdiness',
                                            'insecurity, instability, precariousness, shakiness, unstableness, unsteadiness',
                                            'strengthen vt. 增强')]),
                              Word('striate', "",
                                   [TestWay('vt',
                                            '加条纹',
                                            'to mark with striations or striae',
                                            ["The inner surface of the bark is smooth, of a pale, yellowish brown and very finely striated. 树皮的内部十分光滑, 显着偏暗偏黄的棕色, 并且有着十分精细的条纹。"],
                                            'furrow, streak, stripe',
                                            other_form = 'striated adj. 有条纹的')]),
                              Word('stricture', "",
                                   [TestWay('n',
                                            '责难, 批评',
                                            'an adverse criticism',
                                            ["The reviewer made several strictures upon the author's style. 评论家就作者的文风发出了不少责难。"],
                                            'censure, condemnation, denunciation, excoriation, obloquy, rebuke, reprimand, reproach, reproof',
                                            'commendation, eulogy')]),
                              Word('stride', "",
                                   [TestWay('vi',
                                            '迈大步走',
                                            'to move with or as if with long steps',
                                            ["strode to the door and slammed it 大步走向门口, 狠狠地把门摔上"],
                                            'march, pace, parade',
                                            'mince')])])

list24_unit7 = VocabularyList([Word('strident', "",
                                   [TestWay('adj',
                                            '刺耳的',
                                            'characterized by harsh, insistent, and discordant sound',
                                            ["plagued by the strident noise 被刺耳的噪声所折磨"],
                                            'grating, harsh, hoarse, jarring, rasping, raucous, squawky',
                                            'mellifluous, harmonious',
                                            'stridence n. 喧闹, 刺耳')]),
                              Word('strike', "",
                                   [TestWay('n',
                                            'a refusal to work organized by a body of employees as a form of protest, typically in an attempt to gain a concession or concessions from their employer',
                                            '罢工',
                                            ["dockers voted for an all-out strike"],
                                            'industrial action, walkout, job action, stoppage'),
                                    TestWay('n',
                                            '攻击',
                                            'the act or action of setting upon with force or violence',
                                            ["The first strike was directed at a munitions warehouse. 第一轮攻击的目标是军火仓库。"],
                                            'aggression, assault, charge, offense, onset, onslaught, raid, rush'),
                                    TestWay('vt',
                                            '铸造(奖牌)',
                                            'to form by stamping, printing, or punching',
                                            synonyms = 'build, fabricate, forge, form, make, mold, shape'),
                                    TestWay('vt',
                                            '击打',
                                            'to aim and usually deliver a blow, stroke, or thrust (as with the hand, a weapon, or a tool)',
                                            ["angrily stuck the security guard 愤怒地殴打保安"],
                                            'bat, beat, hammer, hit, knock, nail, punch, swat'),
                                    TestWay('vt',
                                            '袭击, 攻击',
                                            'to take sudden, violent action against',
                                            ["A rattlesnake strikes its prey with lightning speed. 响尾蛇以惊人的速度攻击了它的猎物。"],
                                            'assail, beset, storm, set on'),
                                    TestWay('vt',
                                            '撞击',
                                            'to come into usually forceful contact with something',
                                            ["One bullet-train struck the other one which had been forced to stop on a viaduct due to lightning strike, resulting in huge casualties. 一辆动车撞向了另一辆因雷击而停在高架桥上的动车, 造成了巨大的人员伤亡。"],
                                            'bang, bash, bump, collide, crash, impact, impinge, ram, slam, smash, swipe, thud',
                                            other_form = 'striking adj. 引人注目的')]),
                              Word('stringent', "",
                                   [TestWay('adj',
                                            '紧绷的',
                                            'tight, constricted',
                                            synonyms = 'inflexible, rigid, taut',
                                            antonyms = 'lax, loose, slack'),
                                    TestWay('adj',
                                            '严格的',
                                            'marked by rigor, strictness, or severity especially with regard to rule or standard',
                                            ["Its drug-testing procedures are the most stringent in the world. 它的药检程序是世界上最严格的"],
                                            'draconian, exacting, ironhanded, rigorous, severe, strict, uncompromising',
                                            'lenient')]),
                              Word('strip', "",
                                   [TestWay('vt',
                                            '脱衣, 剥去',
                                            'to remove clothing, covering, or surface matter from',
                                            ["Guards stripped and start to search the prisoners. 守卫剥光了犯人, 开始搜身。"],
                                            'denude, disrobe, doff, unclothe, undress',
                                            'dress, gown, robe, bedeck')]),
                              Word('strut', "",
                                   [TestWay('vt',
                                            '趾高气扬地走',
                                            'to walk with a pompous and affected air',
                                            ["A pompous general strutted off the parade ground. 盛气凌人的将军从阅兵场上趾高气扬的走过"],
                                            'parade, prance, stalk, swagger'),
                                    TestWay('n',
                                            '支柱, 压杆',
                                            'a structural element used to brace or strengthen a framework by resisting longitudinal compression',
                                            synonyms = 'brace, buttress, column, girder, support, underpinning')]),
                              Word('studio', "",
                                   [TestWay('n',
                                            '工作室, 画室, 摄影室',
                                            'the working place of a painter, sculptor, or photographer',
                                            ["moved to a larger studio 搬进了更大的工作室"],
                                            'workshop')]),
                              Word('stultify', "",
                                   [TestWay('vt',
                                            '使无效, 抑制',
                                            'to deprive of vitality and render futile especially by enfeebling or repressive influences',
                                            ["The accident stultified his previous efforts. 这场意外使他过去的努力都白费了。"],
                                            'constipate, stagnate, stifle, trammel',
                                            'encourage, foster, nourish',
                                            'stultifying adj. 抑制的')]),
                              Word('stupor', "",
                                   [TestWay('n',
                                            '迟钝, 麻痹, 无知觉',
                                            'a condition of greatly dulled or completely suspended sense or sensibility',
                                            ["lapsed into an alcoholic stupor 陷入了无知觉的酒醉状态"],
                                            'coma, dullness, languor, lethargy, lassitude, listlessness, torpidity, torpor',
                                            'alertness, vigilance, vigor, vim, vitality, vivacity')]),
                              Word('stunt', "",
                                   [TestWay('vt',
                                            '阻碍(成长)',
                                            'to hinder the normal growth, development, or progress of',
                                            ["The inhospitable climate had stunted all vegetation. 不佳的气候条件抑制了所有植物的生长。"],
                                            'check, curb, dwarf, suppress',
                                            'advance, boost, foster, nourish, nurture, promote')]),
                              Word('sturdy', "",
                                   [TestWay('adj',
                                            '强健的, 结实的',
                                            'marked by or reflecting physical strength or vigor; substantially made or built',
                                            ["sturdy young athletes 年轻有力的运动员‖Remember to wear sturdy boots because we will be going over sharp rocks and uneven terrain. 别忘了穿一双靠谱的靴子, 因为我们要在锋利的岩石和不平的地形上行走。"],
                                            'durable, firm, robust, rugged, stalwart, stout, strong, sound, tough, vigorous',
                                            'delicate, feeble, frail, weak, wimpy, rickety, unsound, unstable, unsteady',
                                            'sturdiness n. 强健')])])

list24_unit8 = VocabularyList([Word('stygian', "",
                                   [TestWay('adj',
                                            '极黑暗的',
                                            'extremely dark, gloomy, or forbidding',
                                            ["the stygian blackness of the cave 山洞里令人恐惧的黑暗"],
                                            'black, caliginous, dark, dim, gloomy, pitch-black',
                                            'bright, brilliant, illuminated, illumined, light, lightsome, lucent, lucid, luminous')]),
                              Word('stymie', "",
                                   [TestWay('vt',
                                            '阻碍',
                                            'to present an obstacle to',
                                            ["stymied by red tape 被冗长的政策条款所阻碍"],
                                            'encumber, fetter, handcuff, handicap, hinder, impede, inhibit, manacle, obstruct, shackle, trammel',
                                            'aid, assist, facilitate, help',
                                            'stymieing adj. 阻碍的')]),
                              Word('subdue', "",
                                   [TestWay('vt',
                                            '征服; 使顺从',
                                            "to conquer and bring into subjection; to bring under one's control by force of arms",
                                            ["subdued the native tribes after years of fighting 经过多年征战终于征服了当地的部落"],
                                            'conquer, defeat, squelch, subjugate, vanquish',
                                            'capitulate, surrender',
                                            'subdued adj. 臣服的, 柔和的')]),
                              Word('subject', "",
                                   [TestWay('n',
                                            '臣民, 受支配的人',
                                            'one that is placed under authority or control',
                                            ["Because of the tense situation in that country, British subjects were advised to return home as soon as possible. 因为该国紧张的局势, 英国公民被建议尽快返回英国国内。"],
                                            'citizen, national',
                                            'alien, potentate'),
                                    TestWay('adj',
                                            '取决于其他因素的',
                                            'contingent on or under the influence of some later action',
                                            ["The price of seafood is subject to weather conditions. 海鲜的价格受天气影响。"],
                                            'affected, conditional, contingent, dependent, reliant, subordinate',
                                            'independent, unconditional')]),
                              Word('subjugate', "",
                                   [TestWay('vt',
                                            '征服, 镇压',
                                            'to bring under control and governance as a subject',
                                            ["I would rather die than be subjugated. 我宁死也不愿臣服。"],
                                            'conquer, dominate, overpower, pacify, quash, squelch, subdue, vanquish',
                                            'capitulate, surrender, lose'),
                                    TestWay('vt',
                                            '剥夺自由',
                                            'to make subservient',
                                            synonyms = 'enfetter, enslave, enthrall',
                                            antonyms = 'discharge, emancipate, enfranchise, liberate, manumit, release, unfetter',
                                            other_form = 'subjugation n. 征服')]),
                              Word('sublime', "",
                                   [TestWay('adj',
                                            '崇高的, 庄严的',
                                            'of high spiritual, moral, or intellectual worth',
                                            ["the sublime virtue of having given all one's worldly goods to the poor 将所有财产都捐给穷人的崇高美德"],
                                            'chivalrous, elevated, gallant, greathearted, lofty, magnanimous, noble',
                                            'base, debased, degenerate, degraded, ignoble, low'),
                                    TestWay('adj',
                                            '(因为杰出、装光、美丽等而)令人惊叹的',
                                            'tending to inspire awe usually because of elevated quality (as of beauty, nobility, or grandeur) or transcendent excellence',
                                            ["the sublime beauty of the canyon 峡谷令人惊叹的美丽"],
                                            'amazing, astonishing, astounding, awesome, fabulous, miraculous, portentous, prodigious, staggering, stunning, stupendous, wonderful',
                                            'common, ordinary',
                                            'sublimity n. 庄严, 壮观')]),
                              Word('subliminal', "",
                                   [TestWay('adj',
                                            '下意识的, 潜在意识的',
                                            'below the threshold of conscious perception',
                                            ["subliminal advertising in movies 电影中的潜意识广告"],
                                            'concealed, hidden, subconscious',
                                            'apparent, clear, evident, manifest, obvious, patent')]),
                              Word('submerge', "",
                                   [TestWay('vt',
                                            '使淹没',
                                            'to put under water',
                                            ["The river burst its banks, submerging an entire village. 河水冲上了堤岸, 淹没了整个村庄。"],
                                            'dip, douse, drench, drown, immerse, inundate, sop, submerse',
                                            'emerge',
                                            'submerged adj. 被淹没的')]),
                              Word('submissive', "",
                                   [TestWay('adj',
                                            '服从的, 顺从的, 恭顺的',
                                            'submitting to others',
                                            ["submissive employees 恭顺的员工", "It's not in her nature to be submissive. 服从不是她的本性。"],
                                            'amenable, biddable, compliant, conformable, docile, obeisant, obsequious, servile, subservient, tractable',
                                            'contumacious, defiant, intractable, obstreperous, rebellious, recalcitrant, refractory, unruly',
                                            'submission n. 服从, 顺从')]),
                              Word('subordinate', "",
                                   [TestWay('adj',
                                            '下级的, 次要的',
                                            'belonging to a lower or inferior class or rank',
                                            ["His contention is that environment plays a subordinate role to heredity in determining what we become. 他的观点就是: 在决定我们成长的因素——环境和遗传之中, 前者处于更次要的地位。"],
                                            'inferior, junior, lower, minor, secondary, subject, tributary',
                                            'greater, higher, major, primary, prime, senior, superior'),
                                    TestWay('vt',
                                            '征服',
                                            "to bring under one's control by force of arms",
                                            ["It is one of the lessons of history that more powerful civilizations often subordinate weaker ones. 强大的文明往往征服弱势的文明, 这是历史的教训之一。"],
                                            'conquer, dominate, overpower, pacify, subdue, subject, subjugate, vanquish',
                                            'capitulate, surrender, lose')])])

list24_unit9 = VocabularyList([Word('subservient', "",
                                   [TestWay('adj',
                                            '奉承的, 屈从的',
                                            'obsequiously submissive',
                                            synonyms = 'amenable, biddable, compliant, conformable, docile, obeisant, obsequious, servile, submissive, tractable',
                                            antonyms = 'contumacious, defiant, intractable, obstreperous, rebellious, recalcitrant, refractory, unruly',
                                            other_form = 'subservience n. 服从')]),
                              Word('subside', "",
                                   [TestWay('vt',
                                            '下陷, 下沉, 减弱',
                                            'to tend downward',
                                            ["Local officials say the flood waters have subsided. 当地官员表示洪水已经退去。‖As the noise of the siren subsided, I was able to fall back to sleep. 随着警笛声的减弱, 我可以再次睡着了。", "The pain will subside in a couple of hours. 几个小时之内疼痛感就会退去的。"],
                                            'abate, decline, decrease, diminish, drop, dwindle, ebb, fall, lessen, moderate, recede, wane',
                                            'balloon, burgeon, escalate, expand, grow, increase, intensify, rise, snowball, soar, wax',
                                            'subsidence n. 下沉')]),
                              Word('subsidiary', "",
                                   [TestWay('adj',
                                            '次要的',
                                            'of secondary importance',
                                            ["The river has several subsidiary streams. 这条河拥有数条支流。"],
                                            'minor, secondary, subordinate, tributary',
                                            'capital, cardinal, central, chief, key, leading, main, paramount, predominant, primary, principal, supreme'),
                                    TestWay('adj',
                                            '起辅助作用的',
                                            'furnishing aid or support',
                                            ["Attached are subsidiary materials. 附件当中的是辅助资料。"],
                                            'accessory, auxiliary, contributory, supplemental, supporting, upholding')]),
                              Word('subsidy', "",
                                   [TestWay('n',
                                            '补助金, 津贴',
                                            'monetary assistance granted by a government to a person or group in support of an enterprise regarded as being in the public interest',
                                            ["a subsidy to manufacturers during the war 战争期间对制造商的补贴金"],
                                            'allotment, allowance, appropriation, grant, subvention',
                                            other_form = 'subsidize vt. 提供补助')]),
                              Word('substantial', "",
                                   [TestWay('adj',
                                            '物质的',
                                            'of, relating to, or having substance',
                                            ["a world of dreams, even less substantial than a rainbow 一个梦想中的世界, 甚至比彩虹还虚无缥缈"],
                                            'corporeal, concrete, gross, material, objective, physical, tangible',
                                            'tenuous, vaporous, diaphanous, ethereal, immaterial'),
                                    TestWay('adj',
                                            '有重大意义的',
                                            'considerable in importance, value, degree, amount, or extent',
                                            ["made a substantial progress 取得了实质性的进展"],
                                            'consequential, considerable, earthshaking, important, meaningful, momentous, significant, weighty',
                                            'inconsequential, inconsiderable, insignificant, little, minor, negligible, slight, trifling, trivial')]),
                              Word('substantiate', "",
                                   [TestWay('vt',
                                            '证实',
                                            'to support with proof or evidence',
                                            ["There is little scientific evidence to substantiate the claims. 现在还缺乏足够的科学证据来证实这种言论。"],
                                            'attest, authenticate, confirm, corroborate, justify, validate, verify',
                                            'controvert, disprove, rebut, refute',
                                            'substantiated adj. 经证实的'),
                                    TestWay('vt',
                                            '使实体化',
                                            'to give material form to',
                                            ["The artist's intense feelings are substantiated by his paintings' bold colors and broad brush strokes. 画家强烈的情感通过他画作中鲜艳的色彩和很宽的笔画体现出来。"],
                                            'embody, epitomize, externalize, incarnate, incorporate, manifest, materialize, personalize',
                                            'disembody',
                                            'substantiated adj. 已证实')]),
                              Word('substantive', "",
                                   [TestWay('adj',
                                            '本质的, 关键的',
                                            'of or relating to the essence or substance',
                                            ["The substantive information is their political stance. 关键的信息是他们的政治立场。"],
                                            'constitutional, elemental, essential, fundamental, substantial, vital',
                                            'inconsequential, inconsiderable, insignificant, insubstantial, negligible, nominal')]),
                              Word('subterfuge', "",
                                   [TestWay('n',
                                            '狡计',
                                            'deception by artifice or stratagem in order to conceal, escape, or evade',
                                            ["The spy obtained the documents by subterfuge. 间谍通过狡猾的计谋获得了文件。"],
                                            'artifice, cheat, chicanery, deception, fraud, trickery, wile')]),
                              Word('subtle', "",
                                   [TestWay('adj',
                                            '微妙的, 难以感知的',
                                            '(so slight as to be)difficult to understand or perceive',
                                            ["subtle differences in meaning between the words 单词词义之间的细微差别"],
                                            'delicate, elusive, evasive, faint, fine, impalpable, intangible, nice, slight',
                                            'batant, conspicuous, obvious, patent, plain, open, public'),
                                    TestWay('adj',
                                            '巧妙的, 间接或带有欺骗性的',
                                            "clever at attaining one's ends by indirect and often deceptive means",
                                            ["used subtle methods of persuasion 采用了十分巧妙的劝说方式"],
                                            'beguiling, crafty, cunning, cute, designing, devious, foxy, guileful, scheming, shrewd, sly, tricky, wily',
                                            'artless, guileless, ingenuous, innocent, undesigning',
                                            'subtlety n. 微妙; 微妙的想法')]),
                              Word('subvert', "",
                                   [TestWay('vt',
                                            '颠覆',
                                            'to overturn or overthrow from the foundation',
                                            ["an alleged plot to subvert the state 一个谣传的旨在推翻政权的阴谋"],
                                            'overthrow, overturn, topple',
                                            'reinforce',
                                            'subversion n. 颠覆')])])

list24_unit10 = VocabularyList([Word('succinct', "",
                                   [TestWay('adj',
                                            '简明的, 简洁的',
                                            'characterized by clear, precise expression in few words',
                                            ["His speech is always succinct and perspicacious. 他的发言总是简洁而一针见血。"],
                                            'apothegmatic, brief, compact, compendious, concise, laconic, pithy, summary, telegraphic, terse',
                                            'circuitous, circumlocutory, diffuse, long-, prolix, rambling, verbose, windy, wordy',
                                            'succinctness n. 简洁, 扼要')]),
                              Word('succor', "",
                                   [TestWay('vt',
                                            '救援, 援助',
                                            'to go to the aid of',
                                            ["We see it as our duty to succor anyone in need. 我们视帮助他人为自己的职责"],
                                            'aid, assist, help, relieve, support')]),
                              Word('suffocate', "",
                                   [TestWay('vt',
                                            '使窒息',
                                            'to deprive of oxygen',
                                            ["The law requires the owner of a discarded refrigerator to remove its door so that a child won't get trapped inside and suffocate. 法律要求废弃冰箱的所有者移除箱门, 从而防止儿童被困其中而窒息致死。"],
                                            'asphyxiate, choke, smother, stifle, strangle',
                                            other_form = 'suffocating adj. 令人窒息的, 压抑的')]),
                              Word('suffuse', "",
                                   [TestWay('vt',
                                            '(色彩等)弥漫, 染遍, 充满',
                                            'to spread through or over, as with liquid, color, or light',
                                            ["a room suffused with warm sunlight 一个充满温暖阳光的房间"],
                                            'flush, fill, imbue, infuse, interpenetrate, percolate, pervade, transfuse',
                                            'suffusing adj. 弥漫的')]),
                              Word('sulk', "",
                                   [TestWay('vi',
                                            '生气, 愠怒',
                                            'to be sullenly aloof or withdrawn, as in silent resentment or protest',
                                            ["He would sulk for hours whenever he didn’t get what he want. 当他的愿望没被满足时, 他会生几个小时的闷气"],
                                            'frown, grump, mope, pout',
                                            'crow, delight, exuberate, jubilate, rejoice, triumph',
                                            'sulky adj. 生气的, 不悦的')]),
                              Word('sullen', "",
                                   [TestWay('adj',
                                            '闷闷不乐的',
                                            'causing or marked by an atmosphere lacking in cheer',
                                            ["She remained sullen amid festivities alone. 她独自一人在喜庆的气氛中闷闷不乐。", "sullen skies that matched our mood on the day of the funeral 葬礼当天与我们很搭调的沉闷天气"],
                                            'bleak, cheerless, dark, depressing, dire, gloomy, glum, gray, lugubrious, morose, saturnine, sulky, surly',
                                            'bright, cheerful, cheering, cordial, festive, gay',
                                            'lighthearted')]),
                              Word('summary', "",
                                   [TestWay('n',
                                            '摘要',
                                            'an abstract, abridgment, or compendium especially of a preceding discourse',
                                            ["Many book reports choose to begin with a summary of the book. 许多书评以该书的摘要开始。"],
                                            'abstract, brief, epitome, outline, recapitulation, synopsis, summarization',
                                            'elaboration'),
                                    TestWay('adj',
                                            '就地的, 立即的',
                                            'done or executed on the spot and without formality',
                                            ["a summary trial and speedy execution 就地的判决和快速的处决"],
                                            'drumhead',
                                            'prolonged, protracted')]),
                              Word('summit', "",
                                   [TestWay('n',
                                            '顶点',
                                            'the highest point',
                                            ["the summit of his ambition 他雄心壮志的顶点"],
                                            'acme, apex, climax, crescendo, crest, crown, culmination, meridian, peak, pinnacle, top, zenith',
                                            'bottom, nadir')]),
                              Word('summon', "",
                                   [TestWay('vt',
                                            '召集, 召唤',
                                            'to call together',
                                            ["The general summoned all his troops before the operation. 行动之前, 将军把所有的部队召集到了一起。"],
                                            'assemble, convene, convoke, muster, rally',
                                            'dismiss'),
                                    TestWay('vt',
                                            '传唤(出庭、出席)',
                                            'to command by service of a summons, especially to appear in court',
                                            ["was summoned to answer charges 他被传唤出庭应对起诉"],
                                            'call, hail')]),
                              Word('sumptuous', "",
                                   [TestWay('adj',
                                            '豪华的, 奢侈的',
                                            'extremely costly, rich, luxurious, or magnificent',
                                            ["The hotel claims to offer sumptuous furnishings and exquisitely prepared cuisine. 酒店宣称有奢华的装潢和精心准备的食物。"],
                                            'deluxe, lavish, lush, luxurious, opulent, palatial, resplendent, splendid, superb',
                                            'ascetic, austere, humble, spartan')])])

LIST24 = VocabularyList(list24_unit1.words+list24_unit2.words+list24_unit3.words+list24_unit4.words+list24_unit5.words+list24_unit6.words+list24_unit7.words+list24_unit8.words+list24_unit9.words+list24_unit10.words)
