#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list19_unit1 = VocabularyList([Word('ponderable', "",
                                   [TestWay('adj',
                                            '有价值的, 值得考虑的',
                                            'considerable enough to be weighed or assessed',
                                            ["Climate change has exerted a ponderable influence on world politics. 气候变化对世界政局有着不容忽视的影响。"],
                                            'appreciable, perceptible, sensible',
                                            'inappreciable')]),
                              Word('ponderous', "",
                                   [TestWay('adj',
                                            '沉重的',
                                            'of very great weight',
                                            ["a ponderous machine 沉重的机器"],
                                            'cumbersome, heavy, hefty, massive, onerous, weighty',
                                            'ethereal, gossamer, light, weightless'),
                                    TestWay('adj',
                                            '沉闷无聊的',
                                            'oppressively or unpleasantly dull',
                                            ["a ponderous sermon no one really cares 实际上无人关心的沉闷无聊的布道"],
                                            'dreary, dull, flat, elephantine, monotonous, insipid, vapid',
                                            'absorbing, engaging, engrossing, gripping, interesting, intriguing, involving, riveting')]),
                              Word('pontificate', "",
                                   [TestWay('vi',
                                            '傲慢地做或说',
                                            'to speak or express opinions in a pompous or dogmatic way',
                                            ["pontificate to show a sense of superiority 傲慢地说以显示高人一等的优越感"],
                                            antonyms = 'condescend',
                                            other_form = 'pontification n. 傲慢的言行; pontifical adj. 傲慢的')]),
                              Word('pore', "",
                                   [TestWay('vi',
                                            '仔细浏览, 仔细研究',
                                            'to read or study attentively(usually used with over)',
                                            ["The committee will probably pore over the results of the study for a long time before making their decision. 在正式做决定之前, 委员会或需要花很长的时间来仔细研究调查结果。"],
                                            'cogitate, consider, contemplate, deliberate, meditate, perpend, ruminate, study, weigh, chew over',
                                            'flip, glance, leaf, riffle, skim')]),
                              Word('porous', "",
                                   [TestWay('adj',
                                            '多孔可渗透的',
                                            'admitting the passage of gas or liquid through pores or interstices',
                                            ["Lava rock has a porous structure which makes the material lightweight and highly moisture-retentive. 火山岩的多孔结构使得它密度很小, 同时有很高的吸湿性。"],
                                            'passable, penetrable, permeable, pervious',
                                            'impassable, impenetrable, impermeable, impervious',
                                            'porosity n. 多孔性')]),
                              Word('portentous', "",
                                   [TestWay('adj',
                                            '预兆性的, 凶兆的',
                                            'being or showing a sign of evil or calamity to come',
                                            ["an eerie and portentous stillness 阴森神秘, 充满凶兆的寂静"],
                                            'baleful, direful, doomy, foreboding, inauspicious, menacing, minatory, ominous, sinister, ill-omened',
                                            'auspicious, propitious'),
                                    TestWay('adj',
                                            '勾起兴趣的, 令人遐想的',
                                            'eliciting amazement or wonder',
                                            ["The way in which he could bring together opposing forces was truly portentous. 他整合两股对抗势力的方法着实令人好奇"],
                                            'amazing, astonishing, astounding, fabulous, marvelous, miraculous, prodigious, wonderful',
                                            'common, commonplace, ordinary')]),
                              Word('poseur', "",
                                   [TestWay('n',
                                            '故作姿态、不真诚的人',
                                            'an affected or insincere person',
                                            ["She is such a poseur and you will never know if she is really crying or pretending. 她就是个爱装的人, 你从不知道她是真的在哭还是只是假装而已。"],
                                            'grandstander, poser')]),
                              Word('posit', "",
                                   [TestWay('vt',
                                            '假定, 断定',
                                            'to assume or affirm the existence of',
                                            ["The committee posited that he was qualified for the election. 委员会假定他是够格参加选举的。"],
                                            'assume, postulate, presuppose, premise, presume',
                                            'falsify')]),
                              Word('postulate', "",
                                   [TestWay('n',
                                            '前提条件',
                                            'something taken as being true or factual and used as a starting point for a course of action or reasoning',
                                            ["One of the postulates that the true agnostic rejects is the assumption that it is even possible for us to know whether God exists. 我们无法知道上帝是否存在——这是一个真正的不可知论者所反对的假设。"],
                                            'premise, presumption, presupposition, supposition',
                                            'conclusion'),
                                    TestWay('v',
                                            '假定为真',
                                            'to assume or claim as true, existent, or necessary',
                                            ["postulate a causal relationship 假定存在因果关系"],
                                            'assume, conjecture, hypothesize, posit, presuppose, premise, presume, suppose',
                                            'belie, disprove, falsify',
                                            'postulation n. 推测')]),
                              Word('posture', "",
                                   [TestWay('n',
                                            '姿势, 姿态',
                                            'a general way of holding the body',
                                            ["A good upright posture will prevent backaches. 良好的站姿可以预防背痛。"],
                                            'attitude, carriage, poise, stance, station'),
                                    TestWay('vi',
                                            '故作姿态, 装模作样',
                                            'to assume an artificial or pretended attitude',
                                            ["postured to impress 故作姿态以给别人留下印象"],
                                            'attitudinize, feign, grandstand, masquerade, pose, pretend',
                                            other_form = 'posturer n. 故作姿态之人')])])

list19_unit2 = VocabularyList([Word('potable', "",
                                   [TestWay('n',
                                            '饮品, 尤指有酒精饮料',
                                            'a beverage, especially an alcoholic beverage',
                                            ["Potables are offered at bar counter for free. 饮料可以在吧台免费领取。"],
                                            'beverage, drink, juice, liquor, spirits',
                                            'non-intoxicant, soft drink'),
                                    TestWay('adj',
                                            '适于饮用的',
                                            'suitable for drinking',
                                            ["Price of the potable water has soared. 饮用水价格飙升。"],
                                            'drinkable, edible',
                                            'undrinkable')]),
                              Word('potentate', "",
                                   [TestWay('n',
                                            '有权的人',
                                            'one who has the power and position to rule over others',
                                            ["a son of a potentate 官二代"],
                                            'authority, autocrat, monarch, ruler, sovereign',
                                            'figurehead')]),
                              Word('potentiate', "",
                                   [TestWay('vt',
                                            '激活, 加强',
                                            'to make effective or active, or more effective or more active',
                                            ["additives to potentiate the drug 增强药效的添加剂"],
                                            'activate, energize, enhance, intensify, stir, wake, vitalize',
                                            'deactivate, abate, attenuate, dwindle, lessen, moderate, reduce')]),
                              Word('pout', "",
                                   [TestWay('vt',
                                            '(特别是撅嘴)表示不悦',
                                            'to show displeasure, especially by thrusting out the lips or wearing a sullen expression',
                                            ["She pouted and didn't say a word to anyone all morning. 她整个早上都闷闷不乐, 没和别人说一句话。"],
                                            'grump, mope, sulk',
                                            'grin')]),
                              Word('practitioner', "",
                                   [TestWay('n',
                                            '职业人士',
                                            'one who practices a profession',
                                            ["medical practitioner 医护人员, 行医者"],
                                            'expert, expounder, guru, professional, specialist, virtuoso',
                                            'fledgling, quack')]),
                              Word('prairie', "",
                                   [TestWay('n',
                                            '大草原',
                                            'an extensive area of flat or rolling, predominantly treeless grassland',
                                            ["Canadian Prairie 加拿大大草原地区"],
                                            'grassland, meadow, plain, savanna')]),
                              Word('prate', "",
                                   [TestWay('vt',
                                            '闲聊, 空谈',
                                            'to talk long and idly',
                                            ["They have been prating on the phone for hours. 他们已经煲了几个小时的电话粥了。"],
                                            'babble, chat, chatter, converse, gabble, jabber, prattle, twitter',
                                            other_form = 'prater n. 闲聊的人')]),
                              Word('preach', "",
                                   [TestWay('vi',
                                            '传道, 布道',
                                            'to deliver a sermon',
                                            ["a minister who loves to preach 一个爱布道的牧师"],
                                            'discourse, sermonize',
                                            other_form = 'preacher n. 布道者')]),
                              Word('precarious', "",
                                   [TestWay('adj',
                                            '危险不稳定的',
                                            'dangerously lacking in security or stability',
                                            ["a precarious livelihood 不稳定的生计"],
                                            'delicate, fragile, sensitive, touchy, unstable',
                                            'firm, stable, safe, secure'),
                                    TestWay('adj',
                                            '可疑的, 不明确的',
                                            'dependent on uncertain premises',
                                            ["His entire argument relies on a precarious assumption. 他的整篇论证都建立在一个可疑的假设之上。"],
                                            'ambiguous, doubtful, dubious, equivocal, uncertain, unfounded',
                                            'indubitable, unambiguous, unequivocal, unquestionable')]),
                              Word('precedent', "",
                                   [TestWay('n',
                                            '先例, 前例',
                                            'an earlier occurrence of something similar',
                                            ["There has not been any precedent so far. 到目前为止还没有先例。", "a landmark decision that set a legal precedent 在法律上首开先河的重大决议"],
                                            'example, instance, model, paradigm, pattern, standard'),
                                    TestWay('adj',
                                            '先前的',
                                            'prior in time, order, arrangement, or significance',
                                            ["Her violent behaviors may be explained by some precedent events in her troubled life. 她的暴力行径或许可以由她之前苦难生活中遭遇到的一些事件来解释."],
                                            'antecedent, anterior, former, preceding, previous, prior',
                                            'ensuing',
                                            'unprecedented adj. 前所未见的')])])

list19_unit3 = VocabularyList([Word('precipice', "",
                                   [TestWay('n',
                                            '悬崖峭壁',
                                            'a very steep or overhanging place',
                                            ["a precipice too steep to climb 过于陡峭而无法攀爬的悬崖"],
                                            'bluff, cliff, crag, escarpment, palisade',
                                            'ridge',
                                            'precipitous adj. 陡峭的')]),
                              Word('precipitate', "",
                                   [TestWay('adj',
                                            '匆忙的',
                                            'acting or done with excessive or careless speed',
                                            ["the army's precipitate withdrawal from the field of battle 匆忙将军队从战场上撤下"],
                                            'cursory, flying, headlong, hurried, overhasty, precipitous, rash, rushed',
                                            'deliberate, leisurely, unhurried, unrushed'),
                                    TestWay('vt',
                                            '促使, 导致',
                                            'to cause to happen, especially suddenly or prematurely',
                                            ["to precipitate an international crisis 产生国际危机"],
                                            'accelerate, escalate, expedite, hasten, impel, speed, trigger',
                                            'check, encumber, enfetter, hamper, handicap, hinder, manacle, obstruct, retard, trammel',
                                            'precipitation n. 急促; 沉淀; 降水')]),
                              Word('precipitation', "",
                                   [TestWay('n',
                                            '沉积物, 尤指降水',
                                            'something precipitated as a deposit on the earth of hail, mist, rain, sleet, or snow',
                                            ["The storm brought several inches of precipitation. 风暴带来的降水量高达数英尺。"],
                                            'deposit, sediment'),
                                    TestWay('n',
                                            '仓促',
                                            'excited and often showy or disorderly speed',
                                            ["I fear that I may have acted with some precipitation on this matter, so I would like to reconsider. 我害怕自己在这个事情上考虑得太仓促了, 因此我想再想想。"],
                                            'haste, hastiness, hustle, precipitousness, rush',
                                            'deliberation')]),
                              Word('precipitous', "",
                                   [TestWay('adj',
                                            '非常陡峭的',
                                            'very steep, perpendicular, or overhanging in rise or fall',
                                            ["a precipitous gorge 险峻的峡谷"],
                                            'abrupt, arduous, precipitate, sheer, steep',
                                            'flat, level'),
                                    TestWay('adj',
                                            '匆忙的',
                                            'acting or done with excessive or careless speed',
                                            ["They soon regretted their precipitous actions in international affairs 他们很快就为他们在国际事务中的匆忙举动感到后悔。"],
                                            'cursory, flying, headlong, hurried, overhasty, precipitate, rash, rushed',
                                            'deliberate, leisurely, unhurried, unrushed')]),
                              Word('preclude', "",
                                   [TestWay('vt',
                                            '预先阻止',
                                            'to make impossible, as by action taken in advance',
                                            ["Age alone will not preclude him from standing as a candidate. 年龄并没有阻止他成为候选人。"],
                                            'avert, deter, forestall, obviate, prevent, stave off'),
                                    TestWay('vt',
                                            '排斥',
                                            'to exclude or prevent (someone) from a given condition or activity',
                                            ["He refused to preclude the subject from discussion . 他拒绝将这个话题排出讨论范围。"],
                                            'bar, exclude, except',
                                            'enclose',
                                            'preclusive adj. 预先阻止的')]),
                              Word('precursor', "",
                                   [TestWay('n',
                                            '先驱者, 先导',
                                            'one that precedes and indicates the approach of another',
                                            ["18th-century lyric poets like Robert Burns were precursors of the Romantics. 十八世纪的抒情诗人(如罗伯特·彭斯)是浪漫主义的先驱。"],
                                            'foregoer, forerunner, harbinger, herald, outrider',
                                            'sequela, successor, descendant',
                                            'precursory adj. 先驱性的, 开创性的')]),
                              Word('predecessor', "",
                                   [TestWay('n',
                                            '前任, 先辈',
                                            'a person who has previously occupied a position or office to which another has succeeded',
                                            ["a political legacy left by his predecessor 他的前任留下来的政治遗产"],
                                            'ancestor, antecedent, foregoer, forerunner, precursor',
                                            'successor, descendant')]),
                              Word('predilection', "",
                                   [TestWay('n',
                                            '爱好, 偏袒',
                                            'a partiality or disposition in favor of something',
                                            ["a predilection for travel 热爱旅行"],
                                            'affection, affinity, bias, disposition, inclination, leaning, penchant, predisposition, propensity, tendency',
                                            'aversion, loathing, nausea, repugnance, repulsion, revulsion')]),
                              Word('preeminent', "",
                                   [TestWay('adj',
                                            '优秀的, 重要的',
                                            'having paramount rank, dignity, or importance',
                                            ["The writer's style is brilliant and his command of words, preeminent. 作者的文风和用词都十分出色"],
                                            'distinguished, illustrious, incomparable, notable, outstanding, peerless, superb, supreme, unmatchable',
                                            'negligible, trivial',
                                            'preeminence n. 杰出')]),
                              Word('preempt', "",
                                   [TestWay('vt',
                                            '预先占有',
                                            'to appropriate, seize, or take for oneself before others',
                                            ["The naughty children had preempted front-row seats that were reserved for the guests of honor. 调皮的孩子们把前排留给贵客的座位占了。"],
                                            'appropriate, arrogate, commandeer, convert, expropriate, preempt, press, seize, usurp'),
                                    TestWay('v',
                                            '替换',
                                            'to replace with something considered to be of greater value or priority: take precedence over',
                                            ["The special newscast preempted the usual television program. 特别新闻取代了常规节目。"],
                                            'displace, replace, supersede, supplant',
                                            'preemptive adj. 先发制人的')])])

list19_unit4 = VocabularyList([Word('preen', "",
                                   [TestWay('vt',
                                            '整理(羽毛)',
                                            'to smooth or clean (feathers) with the beak or bill',
                                            synonyms = 'plume',
                                            antonyms = 'rumple'),
                                    TestWay('vt',
                                            '打扮修饰',
                                            'to dress or groom (oneself) with elaborate care',
                                            ["She always preen herself in an elaborate suit before going to the opera. 她去听歌剧之前总要精心打扮一番, 穿上最豪华的服装。"],
                                            'groom, plume, primp'),
                                    TestWay('vt',
                                            '自满',
                                            'to take pride or satisfaction in (oneself)',
                                            ["He always preen himself on his ancestry. 他总是因为他的血统而洋洋得意"],
                                            'gloat, plume, pride',
                                            'efface')]),
                              Word('preface', "",
                                   [TestWay('n',
                                            '序言',
                                            'a preliminary statement or essay introducing a book that explains its scope, intention, or background and is usually written by the author',
                                            ["An informal brunch served as a preface to the three-day conference. 一顿非正式的便餐作为为期三天的会议的序曲。"],
                                            'exordium, foreword, introduction, overture, preamble, prelude, prologue',
                                            'epilogue',
                                            'prefatory adj. 序言的')]),
                              Word('pregnant', "",
                                   [TestWay('adj',
                                            '重要的, 意味深长的',
                                            'weighty or significant; full of meaning',
                                            ["the pregnant phrases of the Bible 《圣经》中充满哲理的话语"],
                                            'eloquent, meaningful, momentous, profound, revelatory, significant, suggestive',
                                            'inane'),
                                    TestWay('adj',
                                            '怀孕的',
                                            'containing a developing embryo, fetus, or unborn offspring within the body',
                                            ["Being pregnant represents great news, but it comes with a lot of responsibilities. 怀孕是件大好事, 但是它也带来了许多的责任。"],
                                            'enceinte, expectant, expecting, gravid',
                                            other_form = 'pregnancy n. 怀孕')]),
                              Word('premeditate', "",
                                   [TestWay('vi',
                                            '预先考虑',
                                            'to think, consider, or deliberate beforehand',
                                            ["carefully premeditating each step of his plan 细致谋略他计划的每一步"],
                                            'deliberate, prearrange, prepare, preplan',
                                            'disregard, ignore, neglect, omit, overlook',
                                            'premeditation n. 谋略, 事先考虑')]),
                              Word('preoccupation', "",
                                   [TestWay('n',
                                            '非常关心, 全神贯注',
                                            'extreme or excessive concern with something',
                                            ["He kept sinking back into gloomy preoccupation. 他陷入了深深的忧虑之中。"],
                                            'absorption, engagement, engrossment, immersion',
                                            'apathy, indifference, nonchalance, unconcern',
                                            'preoccupied adj. 全神贯注的')]),
                              Word('preponderant', "",
                                   [TestWay('adj',
                                            '占优势的, 更重要的',
                                            'having superior weight, force, importance, or influence',
                                            ["a preponderant misconception 一个影响甚广的错误概念"],
                                            'dominant, paramount, predominant, prevalent, overruling',
                                            'secondary, subsidiary',
                                            'preponderance n. 优势地位')]),
                              Word('prepossessing', "",
                                   [TestWay('adj',
                                            '给人好感的',
                                            'serving to impress favorably',
                                            ["He was fascinated by her prepossessing appearance at first sight. 他第一眼就被她迷人的外表吸引了。"],
                                            'alluring, attractive, appealing, captivating, charming, enchanting, pleasing, riveting',
                                            'abhorrent, appalling, disgusting, hideous, loathsome, repellent, repulsive',
                                            'unprepossessing adj. 不吸引人的')]),
                              Word('preposterous', "",
                                   [TestWay('adj',
                                            '荒谬的, 不符合常理的',
                                            'contrary to nature, reason, or common sense',
                                            ["a preposterous conclusion of quantum mechanics 量子力学里有悖于常理的结论"],
                                            'absurd, asinine, fallacious, fatuous, lunatic, ludicrous, insane, irrational, unreasonable',
                                            'commonsensical, reasonable, sensible')]),
                              Word('presage', "",
                                   [TestWay('n',
                                            '征兆',
                                            'something believed to be a sign or warning of a future event',
                                            ["The sight of the first robin is always a welcome presage of spring. 第一只知更鸟的出现总是迎接春天到来的象征"],
                                            'augury, auspice, boding, foreboding, foreshadowing, portent, prefiguring'),
                                    TestWay('vt',
                                            '预示, 预言',
                                            'to foretell or predict',
                                            ["The incident may presage war. 这个事件可能是战争的征兆"],
                                            'adumbrate, augur, forecast, foretell, portend, predict, prognosticate, prophesy')]),
                              Word('prescience', "",
                                   [TestWay('n',
                                            '预知, 先见',
                                            'knowledge of actions or events before they occur',
                                            ["Most believers would probably agree that complete prescience is one of God's attributes. 所有的信徒大概都会同意上帝能够预见未来"],
                                            'foresight, forethought, providence',
                                            'improvidence, myopia, shortsightedness')])])

list19_unit5 = VocabularyList([Word('prescription', "",
                                   [TestWay('n',
                                            '规定, 传统的规矩',
                                            'something prescribed as a rule; especially an inherited or established way of thinking, feeling, or doing',
                                            synonyms = 'convention, custom, decree, law, regulation, rule',
                                            other_form = 'prescribe v. 开药方; 设立规定')]),
                              Word('preservative', "",
                                   [TestWay('n',
                                            '防腐剂',
                                            'an additive used to protect against decay, discoloration, or spoilage',
                                            ["containing no chemical preservative 不含化学防腐剂"],
                                            other_form = 'preserve v. 保存')]),
                              Word('prestige', "",
                                   [TestWay('n',
                                            '声望, 威望',
                                            'the level of respect at which one is regarded by others',
                                            ["The prestige of the university has been irrevocably impaired by the plagiarism scandal. 这所大学的声望已经因剽窃丑闻而受到了不可挽回的损失。"],
                                            'credit, fame, influence, reputation',
                                            'infamy',
                                            'prestigious adj. 有名望的')]),
                              Word('presumptuous', "",
                                   [TestWay('adj',
                                            '放肆的, 冒昧的',
                                            'overstepping due bounds (as of propriety or courtesy)',
                                            ["Under such a circumstance his demand for attention was utterly presumptuous. 在那种情况下他要求被关注是极其冒昧的"],
                                            'audacious, bold, brash, impertinent, impudent, insolent, pompous, presuming',
                                            'courteous, decorous, genteel, gracious, urbane'),
                                    TestWay('adj',
                                            '傲慢的',
                                            'having a feeling of superiority that shows itself in an overbearing attitude',
                                            ["The presumptuous doctor didn't even bother to explain to me the treatment that I would be receiving. 傲慢的医生连给我说明我会接受何种治疗的耐性都没有。"],
                                            'assumptive, bumptious, cavalier, haughty, imperious, lofty, overweening, peremptory, supercilious',
                                            'humble, modest')]),
                              Word('pretense', "",
                                   [TestWay('n',
                                            '虚假, 伪装',
                                            'the act of pretending; a false appearance or action intended to deceive',
                                            ["There is too much pretense in his piety. 他的虔诚大多都是伪装。"],
                                            'affectation, camouflage, deceit, disguise, imposture, mask, masquerade',
                                            'sincerity'),
                                    TestWay('n',
                                            '自大, 优越感n',
                                            "an exaggerated sense of one's importance that shows itself in the making of excessive or unjustified claims",
                                            synonyms = 'assumption, hauteur, imperiousness, loftiness, lordliness, pomposity, superciliousness, superiority',
                                            antonyms = 'humility, modesty')]),
                              Word('preternatural', "",
                                   [TestWay('adj',
                                            '超乎寻常的',
                                            'surpassing the normal or usual',
                                            ["They exhibited preternatural courage in face of danger. 他们在危险面前显示出了超乎寻常的勇气。"],
                                            'aberrant, abnormal, anomalous, extraordinary, phenomenal, magical, miraculous, unearthly',
                                            'common, ordinary, prosaic')]),
                              Word('prevail', "",
                                   [TestWay('vi',
                                            '盛行, 战胜',
                                            'to be greater in strength or influence',
                                            ["a custom that still prevails 依然盛行的传统"],
                                            'conquer, dominate, overcome, reign, triumph',
                                            'yield',
                                            'prevailing adj. 盛行的')]),
                              Word('prevalent', "",
                                   [TestWay('adj',
                                            '流行的, 普遍的',
                                            'widely or commonly occurring, existing, accepted, or practiced',
                                            ["The kinds of accidents are frequently seen in places where snowmobiles are prevalent. 这种类型的事故在摩托雪橇盛行的地区是很常见的。"],
                                            'conventional, dominant, common, popular, predominant, preponderant, prevailing, rife',
                                            'absent, rare, unusual',
                                            'prevalence n. 流行, 遍及')]),
                              Word('prevaricate', "",
                                   [TestWay('vi',
                                            '支吾其词, 撒谎',
                                            'to stray from or evade the truth',
                                            ["During the hearings the witness did his best to prevaricate. 听证会上证人在竭尽全力地支吾其词。"],
                                            'equivocate, fabricate, falsify, lie, palter',
                                            'prevarication n. 支吾其词')]),
                              Word('primordial', "",
                                   [TestWay('adj',
                                            '原始的, 最初的',
                                            'being or happening first in sequence of time',
                                            ["primordial forms of life 最原始的生命形态"],
                                            'ancient, early, primal, primeval, primitive',
                                            'late, recent')])])

list19_unit6 = VocabularyList([Word('primp', "",
                                   [TestWay('v',
                                            '精心打扮',
                                            'to dress, adorn, or arrange in a careful or finicky manner',
                                            ["She primps for hours before a date. 她出门约会前要花数小时打扮。"],
                                            'preen, dress up')]),
                              Word('principal', "",
                                   [TestWay('adj',
                                            '主要的, 重要的',
                                            'first, highest, or foremost in importance, rank, worth, or degree',
                                            ["The region's principal city is getting hammered by a series of terrorist attacks. 该地区的中心城市正在被一系列恐怖袭击攻击。"],
                                            'capital, cardinal, chief, dominant, grand, main, major, paramount, predominant, preeminent, primary',
                                            'secondary, subordinate')]),
                              Word('pristine', "",
                                   [TestWay('adj',
                                            '纯净的, 质朴的, 未被文明腐蚀的',
                                            'remaining in a pure state; uncorrupted by civilization. remaining free from dirt or decay; clean',
                                            ["a pristine forest 一片未被文明影响的森林"],
                                            'immaculate, spotless, stainless, unsoiled, unstained, unsullied',
                                            'tainted, squalid, contaminated, besmirched ,corrupted by civilization')]),
                              Word('privation', "",
                                   [TestWay('n',
                                            '缺乏, 穷困',
                                            'lack of what is needed for existence',
                                            ["the constant privation of sleep was starting to affect his work 长期以来的睡眠不足开始影响他的工作"],
                                            'deprivation, loss',
                                            'repletion')]),
                              Word('probe', "",
                                   [TestWay('v./n',
                                            '深入调查',
                                            'a penetrating or critical investigation',
                                            ["probe into his background 深入调查他的背景"],
                                            'delving, disquisition, exploration, inquisition')]),
                              Word('probity', "",
                                   [TestWay('n',
                                            '正直',
                                            'faithfulness to high moral standards',
                                            ["a person of indisputable probity should head the disciplinary panel 一个绝对正直的人应该来领导纪律委员会"],
                                            'honesty, integrity, rectitude, righteousness, uprightness',
                                            'unscrupulousness, shiftiness, baseness, dishonor, lowness')]),
                              Word('proclivity', "",
                                   [TestWay('n',
                                            '癖性, 偏好',
                                            'a natural propensity or inclination; predisposition',
                                            ["showed artistic proclivities at an early age 在很小的时候就表现除了对艺术的喜好"],
                                            'aptitude, disposition, leaning, partiality, penchant, predilection, propensity',
                                            'aversion, antipathy, disinclination')]),
                              Word('procrastinate', "",
                                   [TestWay('vi',
                                            '(因为懒散)拖延',
                                            'to put off doing something, especially out of habitual carelessness or laziness',
                                            ["She procrastinated and missed the submission deadline. 她一直拖拖拉拉, 导致错过了截止日期。"])]),
                              Word('procure', "",
                                   [TestWay('vt',
                                            '获得, 取得',
                                            'to get possession of',
                                            ["procured the prisoner's release 得到了释放囚犯的许可"],
                                            'acquire, attain, garner, knock down, pull down, bring in',
                                            'relinquish, forfeit, lose')]),
                              Word('prod', "",
                                   [TestWay('vt',
                                            '促使……行动',
                                            'to try to persuade (someone) through earnest appeals to follow a course of action',
                                            ["The strike may prod the government into action. 罢工也许会迫使政府采取行动。"],
                                            'encourage, exhort, goad, nudge, prompt, spur, egg on',
                                            'rein')])])

list19_unit7 = VocabularyList([Word('prodigal', "",
                                   [TestWay('adj',
                                            '挥霍的',
                                            'recklessly spendthrift',
                                            ["prodigal outlays for her clothes 买衣服时挥金如土"],
                                            'extravagant, profligate, squandering, unthrifty, wasteful',
                                            'frugal, parsimonious, conserving, economical, economizing, penny-pinching, scrimping, skimping, thrifty',
                                            'prodigality 浪费挥霍 【反】penury, husbandry 贫困, 节约'),
                                    TestWay('n',
                                            '败家子',
                                            'someone who spends money freely or foolishly',
                                            ["The million-dollar lottery winner was such a prodigal that his windfall was exhausted after only a few years. 靠彩票中了百万的赢家是个败家子, 几年之内就把这笔意外之财全部花完了。"],
                                            'fritterer, high roller, profligate, spender, spendthrift, squanderer, waster, wastrel',
                                            'economizer, penny-pincher')]),
                              Word('prodigious', "",
                                   [TestWay('adj',
                                            '巨大的',
                                            'impressively great in size, force, or extent; enormous',
                                            ["a prodigious supply of canned food kept in the basement 地下室贮存着大量罐头食品"],
                                            'colossal, elephantine, enormous, gigantic, titanic, tremendous',
                                            'slight',
                                            'prodigy n. 天才, 神童'),
                                    TestWay('adj',
                                            '惊人的, 了不起的',
                                            'causing wonder or astonishment',
                                            ["stage magicians performing prodigious feats for rapt audiences 舞台魔术师在全神贯注的观众们面前表演"],
                                            'amazing, astonishing, astounding, awesome, fabulous, miraculous, portentous, staggering, stunning, stupendous, sublime, surprising')]),
                              Word('profane', "",
                                   [TestWay('v',
                                            '亵渎',
                                            'to treat (something sacred) with abuse, irreverence, or contempt',
                                            ["invading troops profaned the altar by playing poker on it 侵略军亵渎了祭坛, 竟然在上面打扑克"],
                                            'defile, violate',
                                            other_form = 'profaned 被亵渎的 【反】unviolated, inviolable 未被亵渎的, 不可亵渎的'),
                                    TestWay('v',
                                            '滥用',
                                            'to put to a bad or improper use',
                                            ["profaned his considerable acting talents by appearing in some wretched movies 在一些烂俗的电影里面出现简直就是浪费表演才华"],
                                            'abuse, misemploy, misuse, pervert, prostitute')]),
                              Word('proffer', "",
                                   [TestWay('v./n',
                                            '献出, 提供',
                                            'to offer for acceptance; tender',
                                            ["proffered her assistance in helping the two sides reach a compromise 她在斡旋双方达成妥协过程中尽了力"],
                                            'extend, give, proffer, tender, trot out',
                                            'retain, withhold')]),
                              Word('proficient', "",
                                   [TestWay('adj',
                                            '熟练的, 精通的',
                                            'having or marked by an advanced degree of competence, as in an art, vocation, profession, or branch of learning',
                                            ["proficient in translating foreign languages 精通外语翻译"],
                                            'accomplished, complete, expert, skilled, versed, virtuoso',
                                            'inept, incompetent, amateur, inexperienced, inexpert, jackleg, unprofessional, unseasoned, unskilled')]),
                              Word('profligate', "",
                                   [TestWay('adj./n',
                                            '挥金如土的, 挥霍的',
                                            'recklessly wasteful; wildly extravagant',
                                            ["leading a profligate life 过着骄奢淫逸的生活"],
                                            'extravagant, high-rolling, spendthrift, squandering, thriftless, unthrifty, wasteful',
                                            'parsimonious, provident, thrift, economical, frugal, conserving'),
                                    TestWay('n',
                                            '败家子',
                                            'someone who spends money freely or foolishly',
                                            ["profligate who could not really afford the grand style he maintained at Monticello, Jefferson died deeply in debt 再也支撑不了在蒙蒂塞洛之时的大手大脚的作风, 败家子杰斐逊最终深陷债务危机"],
                                            'fritterer, high roller, spender, spendthrift, squanderer, waster, wastrel',
                                            'economizer, penny-pincher'),
                                    TestWay('n',
                                            '堕落的人',
                                            'a person who has sunk below the normal moral standard',
                                            ["a drunken profligate, he was given to wretched excess in every aspect of his life 一个喝醉的堕落的人, 在生活的方方面面都日趋堕落"],
                                            'backslider, debauchee, debaucher, decadent, deviate, libertine, perv, pervert, profligate, rake, rakehell, rip')]),
                              Word('profundity', "",
                                   [TestWay('n',
                                            '深奥, 深刻',
                                            'something profound or abstruse',
                                            ["His books are a mixture of playfulness and profundity. 他的作品都是搞笑和深刻的结合体。"],
                                            'deepness, profoundness',
                                            'superficiality')]),
                              Word('profusion', "",
                                   [TestWay('n',
                                            '丰富, 大量',
                                            'the state of being profuse; abundance',
                                            ["snow falling in profusion 雪量很大"],
                                            'abundance, mass, plentitude, scads, volume, wealth',
                                            'paucity',
                                            'profuse 丰富的 【反】scanty 缺乏的'),
                                    TestWay('n',
                                            '挥霍, 浪费',
                                            'the quality or fact of being free or wasteful in the expenditure of money',
                                            ["in giving gifts to his girlfriend, he was generous to the point of profusion 对于给女朋友的礼物支出一项, 他慷慨到了几乎奢侈的地步"],
                                            'extravagancy, lavishness, prodigality, wastefulness',
                                            'economy, frugality, penny-pinching')]),
                              Word('prohibitive', "",
                                   [TestWay('adj',
                                            '禁止的; 阻止的',
                                            'tending to prohibit or restrain'),
                                    TestWay('adj',
                                            '(价格高得)抑制购买的',
                                            'so high or burdensome as to discourage purchase or use',
                                            ["prohibitive prices 抑制购买的高价"])]),
                              Word('proliferate', "",
                                   [TestWay('vi',
                                            '快速繁殖, 激增',
                                            'to grow or multiply by rapidly producing new tissue, parts, cells, or offspring',
                                            ["rumors about the accident proliferated on the Internet 关于事故的小道消息在网上迅速扩散"],
                                            'balloon, boom, build up, escalate, expand, mushroom, snowball',
                                            'decrease in amount, dwindle, contract, decrease, diminish, dwindle, lessen, recede, wane')])])

list19_unit8 = VocabularyList([Word('prolix', "",
                                   [TestWay('adj',
                                            '罗嗦的, 冗长的',
                                            'tending to speak or write at excessive length',
                                            ["habitually transforms brief anecdotes into prolix sagas that exhaust his listeners 总是将简短的小趣事变成冗长的传说故事, 让听众很疲倦"],
                                            'diffuse, garrulous, rambling, verbose, windy',
                                            'pithy, taciturn, terse, succinct, concise, extreme brief')]),
                              Word('prologue', "",
                                   [TestWay('n',
                                            '序言',
                                            'the preface or introduction to a literary work',
                                            ["the burglary, which he committed while still a teen, was but a prologue to a wasted life of crime 他青少年时犯过的入室抢劫拉开了他偷盗生涯的序幕"],
                                            'exordium, foreword, preamble, preface, prelude, proem, prolusion',
                                            'epilogue')]),
                              Word('prolong', "",
                                   [TestWay('vt',
                                            '延长, 拖延',
                                            'to lengthen in extent, scope, or range',
                                            ["Additives are used to prolong the shelf life of packaged food. 添加剂被用来延长包装食品的保存期限。"],
                                            'elongate, lengthen, outstretch, protract, stretch, drag (out), draw out',
                                            'abbreviate, abridge, curtail, cut, cut back, shorten , truncate')]),
                              Word('proofread', "",
                                   [TestWay('vt',
                                            '校对',
                                            'to read (copy or proof) in order to find errors and mark corrections',
                                            ["She proofread the paper carefully. 她仔细把论文校对了。"])]),
                              Word('promulgate', "",
                                   [TestWay('vt',
                                            '正式宣布',
                                            'to make known openly or publicly',
                                            ["The law was promulgated in June 1988. 法律在1988年6月出台。"],
                                            'annunciate, declare, enunciate, proclaim, publicize, herald',
                                            'keep secret')]),
                              Word('propagate', "",
                                   [TestWay('v',
                                            '繁殖',
                                            'to cause to continue or increase by sexual or asexual reproduction',
                                            ["the dams along the river are interfering with the salmon's ability to propagate 河上的大坝影响了大马哈鱼的繁殖"],
                                            'breed, multiply, reproduce',
                                            'fail to multiply'),
                                    TestWay('vt',
                                            '传播, 宣传',
                                            'to cause to spread out and affect a greater number or greater area: extend',
                                            ["the various ways in which churches can propagate the faith 不同的宣传教义的方法"],
                                            'broadcast, circulate, disseminate',
                                            'check')]),
                              Word('propensity', "",
                                   [TestWay('n',
                                            '倾向, 癖好',
                                            'an often intense natural inclination or preference',
                                            ["a neighbor who has an unfortunate propensity for snooping 好管闲事的邻居"],
                                            'affinity, aptitude, bent, partiality, penchant, predilection, predisposition, proclivity',
                                            'aversion')]),
                              Word('prophetic', "",
                                   [TestWay('adj',
                                            '预言的, 预示的',
                                            'foretelling events: predictive',
                                            ["those lower-than-expected sales numbers were a prophetic indicator of the financial trouble the company would soon be in 那些低于预期的销售数字就是公司即将陷入的金融危机的先兆"],
                                            'predictive')]),
                              Word('propitiate', "",
                                   [TestWay('vt',
                                            '慰抚, 劝解',
                                            'to conciliate (an offended power); appease',
                                            ["the temple was built to honor the gods in times of plenty and to propitiate them in times of trouble 该庙宇的作用是, 丰收之时感谢神明, 有难之时安抚神明"],
                                            'appease, assuage, conciliate, disarm, mollify, placate',
                                            'enrage, incense, inflame, infuriate, ire, madden, outrage, antagonize, arouse hostility')]),
                              Word('propitious', "",
                                   [TestWay('adj',
                                            '吉祥的',
                                            'favorably disposed: pointing toward a happy outcome',
                                            ["propitious sign 吉祥的征兆"],
                                            'auspicious, encouraging, fair, heartening, optimistic, promising, upbeat',
                                            'dim, discouraging, disheartening, futureless, hopeless, inauspicious, unfavorable, unpromising, unpropitious')])])

list19_unit9 = VocabularyList([Word('proponent', "",
                                   [TestWay('n',
                                            '建议者, 支持者',
                                            'one who argues in support of something; an advocate',
                                            ["a proponent of the use of electric-powered cars"],
                                            'advocate, apostle, champion, expounder, espouser, friend, promoter, supporter, protagonist',
                                            'adversary, antagonist, opponent , detractor')]),
                              Word('propriety', "",
                                   [TestWay('n',
                                            '礼节',
                                            'conformity to what is socially acceptable in conduct or speech',
                                            ["When attending a wedding, there are certain proprieties that must be followed. 参加婚礼时, 有一些礼节需要遵守。"],
                                            'decorum, form, etiquette',
                                            'impropriety, indecency, indecorum'),
                                    TestWay('n',
                                            '适当得体',
                                            'the quality or state of being especially suitable or fitting',
                                            ["I'm not sure about the propriety of serving champagne in these glasses. 我不确定在这种杯子里倒香槟是否得体"],
                                            'appositeness, aptness, felicity, fitness, properness, rightness, seemliness, suitability',
                                            'improperness, impropriety, inappositeness, inappropriateness, inaptness, infelicity, unfitness, unseemliness, unsuitability, wrongness')]),
                              Word('prosaic', "",
                                   [TestWay('adj',
                                            '单调的, 常见的',
                                            'being of the type that is encountered in the normal course of events',
                                            ["prosaic advice 老掉牙的建议"],
                                            'commonplace, everyday, routine, unexceptional, unremarkable, workaday',
                                            'abnormal, exceptional, extraordinary, odd, out-of-the-way, strange, exciting, preternatural, ingenious, imaginary')]),
                              Word('proscribe', "",
                                   [TestWay('vt',
                                            '禁止, 排斥',
                                            'to prohibit; forbid',
                                            ["acts proscribed by law 被法律禁止的行为"],
                                            'ban, enjoin, interdict, outlaw, prohibit',
                                            'sanction, permit, allow, let, suffer')]),
                              Word('prosecution', "",
                                   [TestWay('n',
                                            '实行, 执行',
                                            'the doing of an action',
                                            ["oversaw the prosecution of the president's foreign policy 监督总统对外政策的执行情况"],
                                            'accomplishment, achievement, discharge, enactment, execution, fulfillment, implementation, performance, perpetration, pursuance',
                                            'nonfulfillment, nonperformance')]),
                              Word('proselytize', "",
                                   [TestWay('v',
                                            '改变信仰',
                                            "to persuade to change to one's religious faith",
                                            ["The efforts of early missionaries to proselytize the Native Americans of Minnesota were largely unproductive. 早期传教士对于明尼苏达的土著人的改变信仰的努力大多无功而返。"],
                                            'convert')]),
                              Word('prospect', "",
                                   [TestWay('vi',
                                            '探查, 勘探',
                                            'to go into or range over for purposes of discovery',
                                            ["people had arrived in the valley to prospect it for gold 人们来到山谷淘金"],
                                            'hunt, probe, search, skirr'),
                                    TestWay('n',
                                            '期待, 被期望的某物',
                                            'the act or state of looking forward to some occurrence',
                                            ["The prospect of a quiet, restful Sunday ended when our basement flooded. 对一个宁静休闲的周日的期待被地下室涨水打破了。"],
                                            'anticipation, contemplation, expectancy')]),
                              Word('prosperous', "",
                                   [TestWay('adj',
                                            '成功的, 繁盛的',
                                            'marked by vigorous growth and well-being especially economically',
                                            ["The company had a prosperous year. 公司今年业绩斐然。"],
                                            'booming, flourishing, halcyon, lush, palmy, roaring, thriving',
                                            'depressed, impecunious')]),
                              Word('prostrate', "",
                                   [TestWay('adj./v',
                                            '平躺',
                                            'lying flat or at full length',
                                            ["He was lying prostrate on the bed. 他平躺在床上。"],
                                            'debilitated, effete, enervated, enfeebled, languid, sapped',
                                            'erect, upright'),
                                    TestWay('adj./v',
                                            '衰弱的/使衰竭',
                                            'to reduce to extreme weakness or incapacitation',
                                            ["illness that prostrated an entire family 将整个家庭拖垮的疾病"],
                                            'debilitate, devitalize, enervate, enfeeble, etiolate, sap, tire',
                                            'fortify, strengthen, beef up')]),
                              Word('protean', "",
                                   [TestWay('adj',
                                            '善变的, 多才多艺的',
                                            'displaying great diversity or variety; versatile',
                                            ["He loved to show off his protean talent. 他喜欢炫耀自己多样的才华."],
                                            'adaptable, universal, all-around',
                                            'static')])])

list19_unit10 = VocabularyList([Word('protocol', "",
                                   [TestWay('n',
                                            '正确的礼仪规范',
                                            'a code of correct conduct',
                                            ["a breach of protocol 社交礼仪的破坏"])]),
                              Word('protract', "",
                                   [TestWay('vt',
                                            '延长, 拖长',
                                            'to draw out or lengthen in time; prolong',
                                            synonyms = 'elongate, lengthen, prolong, stretch, drag out, draw out',
                                            antonyms = 'curtail, abridge, abbreviate, shorten, cut back')]),
                              Word('protrude', "",
                                   [TestWay('vi',
                                            '突出',
                                            'to jut out; project; bulge',
                                            ["a handkerchief protruding from his breast pocket 手帕从他的上衣口袋里突出出来"],
                                            'bulge, overhang, poke, project, stand out, stick out',
                                            'concave')]),
                              Word('protuberant', "",
                                   [TestWay('adj',
                                            '隆起的, 凸出的',
                                            'thrusting out from a surrounding or adjacent surface often as a rounded mass',
                                            ["protuberant eyes 暴鱼眼"],
                                            'depressed',
                                            'protuberance 隆起 【反】concavity 凹陷')]),
                              Word('provident', "",
                                   [TestWay('adj',
                                            '节俭的',
                                            'frugal; economical',
                                            ["it is possible to be provident without being miserly 人可以做到节俭但不吝啬"],
                                            'economical, sparing, thrifty, farsighted, provident, scrimping',
                                            'profligate'),
                                    TestWay('adj',
                                            '有远见的',
                                            'having or showing awareness of and preparation for the future',
                                            ["her provident measures kept us safe while we waited out the hurricane 她之前有远见的准备让我等待飓风结束的期间安全无恙"],
                                            'farseeing, farsighted, forehanded, foreseeing, forethoughtful, prescient, proactive, visionary',
                                            'half-baked, half-cocked, improvident, myopic, shortsighted')]),
                              Word('providential', "",
                                   [TestWay('adj',
                                            '天意的, 幸运的',
                                            'happening as if through divine intervention',
                                            ["a providential escape 幸运的逃脱"],
                                            'lucky, fluky, fortuitous',
                                            'unfortunate, mishap, hapless, ill-fated, ill-starred, luckless, star-crossed')]),
                              Word('provincial', "",
                                   [TestWay('adj./n',
                                            '狭隘的',
                                            'limited in perspective; narrow and self-centered',
                                            ["an artist who has been criticized for being provincial 一个被批评非常狭隘的艺术家"],
                                            'illiberal, insular, parochial, sectarian, narrow-minded',
                                            'ecumenical, broad-minded, catholic, cosmopolitan, liberal, open, open-minded, receptive, tolerant')]),
                              Word('provisional', "",
                                   [TestWay('adj',
                                            '临时的',
                                            'provided or serving only for the time being; temporary',
                                            ["he was appointed provisional executor of the industrialist's vast estate 他被任命为庞大工业帝国的临时执行官"],
                                            'impermanent, interim, provisionary, short-term',
                                            'long-term, permanent')]),
                              Word('provisory', "",
                                   [TestWay('adj',
                                            '有附带条件的, 临时的',
                                            'depending on a proviso; conditional; serving in a position for the time being',
                                            ["a provisory permit to block off the street while movie scenes were being shot 一个同意在电影拍摄期间封锁道路的临时许可"],
                                            'interim, provisional, provisionary, provisory',
                                            'unconditional, long-term, permanent')]),
                              Word('provoke', "",
                                   [TestWay('vt',
                                            '激怒',
                                            'to incite to anger or resentment',
                                            ["his teasing finally provoked her to anger 他的调戏最终把她激怒了"],
                                            'arouse, excite, incite, instigate, pique, stimulate, stir, fire up'),
                                    TestWay('vt',
                                            '驱使, 激起',
                                            'to stir to action or feeling',
                                            ["rankings that are sure to provoke an argument among film critics 排名必将引发影评家们的争论"],
                                            'abet, ferment, foment, instigate, stir up, whip up')])])

LIST19 = VocabularyList(list19_unit1.words+list19_unit2.words+list19_unit3.words+list19_unit4.words+list19_unit5.words+list19_unit6.words+list19_unit7.words+list19_unit8.words+list19_unit9.words+list19_unit10.words)
