#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list5_unit1 = VocabularyList([Word('compound', "",
                                   [TestWay('n',
                                            '混和物',
                                            'composed of or resulting from union of separate elements, ingredients, or parts',
                                            ['mixed the chemicals together to form a new compound 将化学试剂混合形成新的化合物'],
                                            ['admixture', 'alloy', 'amalgam', 'amalgamation', 'cocktail', 'combination', 'composite', 'fusion', 'intermixture', 'meld', 'mix', 'conflation', 'synthesis']),
                                    TestWay('adj',
                                            '混合的',
                                            'consisting of two or more substances, ingredients, elements, or parts',
                                            ["a compound word 复合词", "“Steamboat” is a compound noun. “汽船”是一个复合名词。"],
                                            ['amalgamated'],
                                            ['noncompound']),
                                    TestWay('vt',
                                            '混合',
                                            'to put or bring together so as to form a new and longer whole',
                                            ["the German language's propensity for compounding words 德语喜欢复合单词"],
                                            ['chain', 'conjugate', 'couple', 'hook', 'interconnect', 'interlink', 'join', 'link', 'yoke'],
                                            ['disconnect', 'disjoin', 'disjoint', 'dissever', 'disunite', 'separate', 'unchain', 'uncouple', 'unhitch', 'unyoke']),
                                    TestWay('v',
                                            '扩大, 增多',
                                            'to make greater in size, amount, or number',
                                            ['We compounded our error by waiting too long to call for help. 我们等着不寻求帮助会增大我们的错误。'],
                                            ['Aggrandize', 'amplify', 'augment', 'boost', 'enlarge', 'escalate', 'expand', 'extend', 'raise', 'swell'],
                                            ['abate', 'decrease', 'diminish', 'dwindle', 'lessen', 'lower', 'minify', 'reduce']),
                                    TestWay('v',
                                            '和解',
                                            'to agree for a consideration not to prosecute (an offense)',
                                            ['compound a felony 私了案件'])]),
                              Word('compress', "",
                                   [TestWay('vt',
                                            '压缩(体积)',
                                            'to reduce in size or volume as if by squeezing',
                                            ["compress a computer file 压缩电脑文档", "The science textbook compresses a lot of information about human reproduction into a few short chapters. 科学教科书将人类的生殖知识压缩成了几个短章节。"],
                                            ['capsule', 'collapse', 'compact', 'condense', 'constrict', 'constringe', 'contract', 'shrink', 'telescope'],
                                            ['increase in volume', 'decompress', 'expand', 'outspread', 'outstretch', 'balloon' ])]),
                              Word('compromise', "",
                                   [TestWay('v',
                                            '妥协',
                                            'to adjust or settle by mutual concessions',
                                            ["Eventually we reached a compromise on the number of hours per week that would be devoted to piano practice. 最后我们在每周练琴的时间上妥协了。"],
                                            ['accommodation', 'negotiation']),
                                    TestWay('v',
                                            '使危险',
                                            'to place in danger',
                                            ["Officials were concerned that his statements would compromise national security. 官员们认为他的言论会 危害国家安全。"],
                                            ['hazard', 'imperil', 'jeopardy', 'jeopardize', 'menace', 'peril', 'venture'])]),
                              Word('compunction', "",
                                   [TestWay('n',
                                            '焦虑',
                                            'anxiety arising from awareness of guilt',
                                            ["compunction of conscience 良心不安", "a brutal murderer who killed without compunction 一个野蛮没有良 心的杀人犯"],
                                            ['anxiety', 'misgiving', 'scruple'],
                                            ['absence of misgiving'])]),
                              Word('concatenate', "",
                                   [TestWay('v',
                                            '连结, 混合',
                                            'to put or bring together so as to form a new and longer whole',
                                            ["The movie actually concatenates several episodes from various books into one extended narrative. 这部电影把很多书中的片段混合成了一个故事。"],
                                            ['catenate', 'chain', 'couple', 'hook', 'interconnect', 'interlink', 'join', 'link', 'yoke'],
                                            ['disconnect', 'disjoin', 'disjoint', 'dissever', 'disunite', 'separate', 'unchain', 'uncouple', 'unhitch', 'unyoke'])]),
                              Word('concave', "",
                                   [TestWay('adj',
                                            '凹的',
                                            'curved like the inner surface of a sphere',
                                            ['a concave lens 凹透镜'],
                                            ['dented', 'depressed', 'dished', 'indented', 'recessed'],
                                            ['bulging', 'convex', 'protuberant'])]),
                              Word('conceal', "",
                                   [TestWay('v',
                                            '隐藏, 隐瞒',
                                            'to prevent disclosure or recognition of',
                                            ['Drunkenness reveal what soberness conceal. 酒后吐真言'],
                                            ['cache', 'secrete', 'disguise', 'mask', 'occult', 'ensconce'],
                                            ['display', 'exhibit', 'bare', 'disclose', 'expose', 'reveal', 'uncover', 'unmask'])]),
                              Word('concede', "",
                                   [TestWay('vt',
                                            '承认',
                                            'to grant as a right or privilege',
                                            ['She grudgingly conceded his point. 她不情愿的承认了他的观点。'],
                                            ['acknowledge', 'grant', 'confess'],
                                            ['refuse to grant', 'deny'],
                                            'concession n. 让步: the act of yielding 【反】aggression 侵犯'),
                                    TestWay('v',
                                            '停止抵抗',
                                            "to cease resistance (as to another's arguments, demands, or control)",
                                            ['He conceded as soon as it became clear that he could not win. 当他明显赢不了的时候他就停止了抵抗。'],
                                            ['capitulate', 'give in', 'quit', 'submit', 'succumb', 'surrender'],
                                            ['resist'])]),
                              Word('concentrate', "",
                                   [TestWay('v',
                                            '集中',
                                            'to bring or direct toward a common center or objective : focus',
                                            ['concentrate one’s efforts 集中精力'],
                                            ['center', 'focus', 'rivet'],
                                            ['deploy', 'dispel', 'disperse', 'dissipate']),
                                    TestWay('v',
                                            '浓缩',
                                            'to make less dilute',
                                            ['prolonged boiling is required to concentrate the sap when making maple syrup'],
                                            ['condense'],
                                            ['dilute', 'water down']),
                                    TestWay('v',
                                            '聚集',
                                            'to come together in one body or place',
                                            ['recent immigrants tend to concentrate in port cities. 进来的移民倾向于聚集在海港城市。'],
                                            ['accumulate', 'amass', 'assemble', 'collect', 'congregate', 'garner'],
                                            ['dispel', 'disperse', 'dissipate', 'scatter', 'break up', 'disband'])]),
                              Word('concerted', "",
                                   [TestWay('adj',
                                            '共同完成的',
                                            'planned or accomplished together',
                                            ["The ITER project, commendable though it is, should be merely a component of a concerted effort. “国际 热核聚变实验堆”计划虽然是值得称赞的, 但是它仅仅是(人类)齐心协力的一部分。", "A victory results from the concerted effort of the entire team. 一项成功来自于整个团队的齐心协力。"],
                                            ['collaborative', 'combined', 'cooperative', 'united'],
                                            ['separate', 'individual', 'single', 'sole', 'solitary'])])])

list5_unit2 = VocabularyList([Word('conciliate', "",
                                   [TestWay('v',
                                            '平息, 抚慰',
                                            'to lessen the anger or agitation of',
                                            ['A principal trying to conciliate the parents who did not receive their tickets to the graduation ceremonies. 校长试着平息这对没有收到他们的毕业晚会门票的家长的气愤情绪。'],
                                            ['appease', 'pacify', 'assuage', 'conciliate', 'mollify', 'placate', 'propitiate', 'calm (down)', 'ease', 'soothe', 'palliate', 'disarm'],
                                            ['annoy', 'enrage', 'vex', 'nettle', 'rile', 'incense', 'inflame', 'exasperate', 'infuriate', 'discompose', 'disturb', 'perturb', 'upset']),
                                    TestWay('vt',
                                            '调解',
                                            'to make compatible : reconcile',
                                            ["It will be hard to conciliate the views of labor and management regarding health benefits. 调解劳资双方对于健康保险金的观点很难。"],
                                            ['attune', 'reconcile', 'coordinate', 'accommodate'],
                                            ['discontent', 'disharmonize'],
                                            'conciliatory adj. 调和的, 安抚的 【反】contentious 好争吵的;belligerent 好战的')]),
                              Word('concise', "",
                                   [TestWay('adj',
                                            '简洁的',
                                            'marked by brevity of expression or statement',
                                            ["a clear and concise account of the accident 一个清楚间断的事故描述", "Concise Design of Spacecraft Automatic System 航天器自动控制系统简要设计"],
                                            ['aphoristic', 'compendious', 'curt', 'laconic', 'pithy', 'succinct', 'terse', 'elliptical'],
                                            ['circuitous', 'circumlocutory', 'diffuse', 'long-winded', 'prolix', 'verbose', 'windy', 'wordy'])]),
                              Word('concord', "",
                                   [TestWay('n',
                                            '一致, 和睦',
                                            'harmony or agreement of interests or feelings; accord',
                                            ['No discord, no concord. 不打不成交'],
                                            ['comity', 'compatibility', 'peace'],
                                            ['conflict', 'discord', 'dissension', 'variance'])]),
                              Word('concur', "",
                                   [TestWay('vi',
                                            '',
                                            'to express agreement',
                                            ['concur with an excellent opinion 同意一个好的想法'],
                                            ['agree', 'coincide'],
                                            ['differ', 'disagree']),
                                    TestWay('v',
                                            '同一时间发生、存在',
                                            'to occur or exist at the same time',
                                            ['The race to the moon, the Vietnam War, and the civil rights movement all concurred in the 1960s. 登月,  越战和人权运动都发生在二十世纪六十年代。'],
                                            ['coexist', 'synchronize', 'co-occur']),
                                    TestWay('v',
                                            '团结合作',
                                            'to participate or assist in a joint effort to accomplish an end',
                                            ['All people concurred to pass the reform legislation 所有人都联合起来使改革的法案通过。'],
                                            ['band together', 'collaborate', 'concert', 'conjoin', 'league', 'team up', 'unite'])]),
                              Word('condescending', "",
                                   [TestWay('adj',
                                            '摆出高人一等的姿态的',
                                            'displaying a patronizingly superior attitude',
                                            ['treat sb. in a condescending manner 以屈尊俯就的态度对待某人'],
                                            ['patronizing'],
                                            other_form = 'condescension n. 屈尊俯就:patronizing attitude or behavior')]),
                              Word('condign', "",
                                   [TestWay('adj',
                                            '应得的, 恰当的',
                                            'deserved, appropriate',
                                            ["condign punishment 应得的惩罚 || A suspension without pay is condign punishment for breaking the company's code of business ethics 停职是违反公司商业道德准则应得的惩罚。"],
                                            ['due', 'deserved', 'merited', 'justified', 'warranted'],
                                            ['undeserved', 'undue', 'unmerited'])]),
                              Word('condole', "",
                                   [TestWay('vi',
                                            '表达同情',
                                            'to express sympathetic sorrow',
                                            ['We condole with him on the death of his father. 我们对他父亲的死向他深表同情。'],
                                            ['compassionate', 'sympathize with', 'yearn over'],
                                            other_form = 'condolence n. 同情; sympathy with another in sorrow')]),
                              Word('condone', "",
                                   [TestWay('vt',
                                            '宽恕, 忽视',
                                            'to overlook, forgive, or disregard (an offense) without protest or censure.',
                                            ["By his silence, he seemed to condone their behavior. 他的沉默流露出了他对他们行为的宽恕。", "He is too quick to condone his friend's faults. 她太快了以至于忽视了他朋友的过错。"],
                                            ['disregard', 'ignore', 'overlook', 'remit', 'shrug off', 'gloss over'],
                                            ['denounce', 'exact'])]),
                              Word('conducive', "",
                                   [TestWay('adj',
                                            '有益的, 有促进的',
                                            'tending to promote or assist',
                                            ['be conducive to education 于教育有利的', "The state's long-standing low tax is conducive to entrepreneurship. 政府长期的低税率有利于创业者。"],
                                            ['facilitative', 'useful'],
                                            ['unhelpful', 'useless'])]),
                              Word('confident', "",
                                   [TestWay('adj',
                                            '有信心的, 自信的',
                                            'having or showing assurance and self-reliance',
                                            ['Thicker and fuller hair would make a man more confident at work. 更加自信。'],
                                            ['assured', 'self-assured', 'self-confident'],
                                            ['diffident'])])])

list5_unit3 = VocabularyList([Word('confine', "",
                                   [TestWay('vt',
                                            '禁闭, 监禁',
                                            'to shut or keep in, especially to imprison',
                                            ['The thief was confined in a prison. 小偷被关在监狱里。'],
                                            ['imprison', 'commit', 'confine', 'immure', 'incarcerate', 'jail'],
                                            ['discharge', 'free', 'liberate', 'release']),
                                    TestWay('v',
                                            '限制',
                                            'to keep within limits',
                                            ['Please confine yourself to the subject 请不要离题。'],
                                            ['limit', 'circumscribe', 'restrict'],
                                            ['exceed'])]),
                              Word('confluence', "",
                                   [TestWay('n',
                                            '汇合, 混合',
                                            'the coming together of two or more things to the same point',
                                            ['a happy confluence of beautiful weather and spectacular scenery during our vacation 旅途中美好的天气和壮丽的景色令人欣喜的汇合'],
                                            ['conjunction'],
                                            ['divergence'])]),
                              Word('confront', "",
                                   [TestWay('v',
                                            '直接对抗, 直面',
                                            'to come face to face with, especially with defiance or hostility',
                                            ['You must confront your fear in order to conquer it. 要战胜你的恐惧, 就必须首先敢于面对'],
                                            ['affront', 'brazen', 'encounter', 'face', 'meet'],
                                            ['dodge', 'duck', 'parry', 'shirk', 'sidestep'],
                                            'confrontation n. 对抗, 冲突')]),
                              Word('confound', "",
                                   [TestWay('v',
                                            '使困惑',
                                            'to throw into a state of mental uncertainty',
                                            ['We are all confounded by his self-contradictory claims. 我们都对他自相矛盾的言论感到困惑'],
                                            ['baffle', 'bewilder', 'confuse', 'muddle', 'perplex', 'puzzle'],
                                            ['clarify']),
                                    TestWay('v',
                                            '无法区分, 混淆',
                                            'to fail to differentiate (a thing) from something similar or related',
                                            ['I think you must have confounded astrology with astronomy. 我想你一定是把占星术和天文学搞混了'],
                                            ['misidentify', 'mistake', 'mix up'],
                                            ['discriminate', 'distinguish']),
                                    TestWay('v',
                                            '证明为假, 证伪',
                                            'to prove to be false',
                                            ['new discoveries that confounded much of what archaeologists thought they have known about the ancient Mayan civilization一些新的发现, 它们颠覆了考古学家们长期以来对于古代玛雅文明的认识'],
                                            ['belie', 'debunk', 'falsify', 'disprove', 'rebut', 'refute'],
                                            ['confirm', 'validate', 'verify'],
                                            'confounding adj. 使人困惑的')]),
                              Word('congeal', "",
                                   [TestWay('v',
                                            '凝固, 固化',
                                            'to change from a fluid to a solid state by or as if by cold',
                                            ['The blood had started to congeal. 血液开始凝结了'],
                                            ['coagulate', 'solidify', 'indurate', 'clot'],
                                            ['melt', 'liquefy'],
                                            'congealment n. 凝固')]),
                              Word('congenial', "",
                                   [TestWay('adj',
                                            '和善的, 友好的',
                                            'having or marked by agreement in feeling or action',
                                            ['a congenial host who invited us for a feast 一位邀请我们美餐一顿的和善主人'],
                                            ['agreeable', 'amicable', 'compatible', 'unanimous', 'united'],
                                            ['discordant', 'incompatible']),
                                    TestWay('adj',
                                            '令人愉悦的',
                                            'giving pleasure or contentment to the mind or senses',
                                            ['delightful', 'dulcet', 'felicitous', 'palatable'],
                                            ['unpleasant'],
                                            ['congeniality n. 友善'])]),
                              Word('congruent', "",
                                   [TestWay('adj',
                                            '和谐一致的',
                                            'being in agreement, harmony, or correspondence; congruous',
                                            ['a theory congruent with the known facts 一个与已知事实相一致的理论'],
                                            ['consonant', 'compatible', 'consistent', 'harmonious', 'accordant'],
                                            ['disagreeable', 'conflicting', 'incompatible']),
                                    TestWay('adj',
                                            '全等的',
                                            'coinciding exactly when superimposed',
                                            ['These two triangles are congruent. 这两个三角形是全等的'],
                                            ['identical', 'exact'],
                                            ['disparate'],
                                            'congruity n. 和谐一致')]),
                              Word('conjecture', "",
                                   [TestWay('n',
                                            '揣测的结果',
                                            'a conclusion deduced by surmise or guesswork',
                                            ['That was only a conjecture, not a fact. 那只是猜测而非事实'],
                                            ['speculation', 'supposition', 'surmise', 'theory'],
                                            ['fact', 'axiom']),
                                    TestWay('v',
                                            '猜测, 估计(大小、数量等)',
                                            'to decide the size, amount, number, or distance of (something) without actual measurement',
                                            synonyms = ['calculate', 'estimate', 'guess', 'gauge'],
                                            antonyms = ['prove']),
                                    TestWay('v',
                                            '(没有依据地)认为',
                                            'to form an opinion from little or no evidence',
                                            ['conjecture that this disease is caused by ad efective gene 揣测这种疾病是由基因缺陷导致的'],
                                            ['assume', 'imagine', 'presume', 'speculate', 'suppose'])]),
                              Word('connive', "",
                                   [TestWay('vi',
                                            '暗中合作',
                                            'to cooperate secretly or have a secret understanding; collude',
                                            ['They connived to take over the throne. 他们密谋篡位'],
                                            ['conspire', 'intrigue', 'plot', 'collude', 'intrigue', 'machinate', 'put up']),
                                    TestWay('v',
                                            '纵容: 假装忽视或并未采取措施阻止错误',
                                            'to pretend ignorance of or fail to take action against something one ought to oppose',
                                            ['blink', 'disregard', 'overlook', 'wink'],
                                            ['disapprove'],
                                            ['conniver n. 共谋者'])]),
                              Word('connoisseur', "",
                                   [TestWay('n',
                                            '鉴赏家(尤其艺术领域)',
                                            'a person who enjoys with discrimination and appreciation of subtleties and details especially in matters of culture or art',
                                            ['a connoisseur of wine and cigarette 烟酒鉴赏的行家'],
                                            ['aesthete', 'cognoscente']),
                                    TestWay('n',
                                            '专家',
                                            'a person with a high level of knowledge or skill in a field',
                                            ['works that are highly prized by connoisseurs of art glass 被玻璃艺术制品专家高度赞誉的作品'],
                                            ['adept', 'artist', 'authority', 'maestro', 'master', 'maven', 'proficient', 'virtuoso'],
                                            ['amateur', 'inexpert', 'nonexpert'])])])

list5_unit4 = VocabularyList([Word('conscientious', "",
                                   [TestWay('adj',
                                            '仔细的, 一丝不苟的',
                                            'taking, showing, or involving great care and effort',
                                            ['a conscientious researcher 一丝不苟的研究者'],
                                            ['careful', 'exact', 'heedful', 'meticulous', 'painstaking', 'scrupulous'],
                                            ['careless', 'remiss']),
                                    TestWay('adj',
                                            '有良心的, 正直的',
                                            'governed by or conforming to the dictates of conscience',
                                            ['a conscientious police officer 一名有良心的警察'],
                                            ['conscionable', 'ethical', 'honest', 'moral', 'upright', 'principled', 'scrupulous'],
                                            ['unscrupulous'],
                                            'conscience n. 良心')]),
                              Word('consensus', "",
                                   [TestWay('n',
                                            '一致同意',
                                            'general agreement; unanimity',
                                            ['The board has finally reached a consensus. 董事会最终达成了一致'],
                                            ['accord', 'assent', 'agreement', 'harmony', 'unanimity', 'unison'],
                                            ['disagreement'])]),
                              Word('consequence', "",
                                   [TestWay('n',
                                            '结果',
                                            'something produced by a cause or necessarily following from a set of conditions',
                                            ['negative consequences of the war 战争带来的负面后果'],
                                            ['aftermath', 'effect', 'outcome', 'result'],
                                            ['source', 'origin', 'cause', 'antecedent']),
                                    TestWay('n',
                                            '重要性, 价值',
                                            'significance; importance',
                                            ['a mistake of no consequence 不重要的错误'],
                                            ['moment', 'magnitude', 'weight'],
                                            ['triviality'],
                                            'consequential adj. 重要的')]),
                              Word('conservative', "",
                                   [TestWay('adj',
                                            '守旧的, 不愿改变的',
                                            'favoring traditional views and values; tending to oppose change',
                                            ['a conservative political stance 一个守旧的政治立场'],
                                            ['hidebound', 'reactionary', 'die-hard'],
                                            ['radical', 'aggressive']),
                                    TestWay('adj',
                                            '不招摇的, 低调的',
                                            'not excessively showy',
                                            ['dressing in conservative outfits so as to make a good impression at job interviews 身着低调得体的套装 以期待在面试时留下一个好印象'],
                                            ['muted', 'repressed', 'low-key', 'understated', 'unpretentious'],
                                            ['flamboyant', 'ostentatious', 'splashy']),
                                    TestWay('adj',
                                            '谨慎小心的',
                                            'having or showing a close attentiveness to avoiding danger or trouble',
                                            ["He made conservative investments, and so he wasn't ruined when the market went into a free fall. 他 只做了一份谨慎保守的投资, 以防市场崩盘时不至于破产"],
                                            ['alert', 'heedful', 'cautious', 'circumspect', 'gingerly', 'guarded', 'wary', 'vigilant'],
                                            ['heedless'])]),
                              Word('conservatory', "",
                                   [TestWay('n',
                                            '温室',
                                            'a greenhouse for growing or displaying plants',
                                            ["The college's conservatory is entirely devoted to cultivating and displaying orchids. 学校的温室几乎全部用于兰花的种植和观赏了"],
                                            ['greenhouse', 'hothouse']),
                                    TestWay('n',
                                            '艺术学院',
                                            'a school specializing in one of the fine arts',
                                            ['an opera conservatory 歌剧学院'])]),
                              Word('conserve', "",
                                   [TestWay('vt',
                                            '保存, 避免浪费',
                                            'to keep in a safe or sound state, especially to avoid wasteful or destructive use',
                                            ['conserve natural resources 保护自然资源'],
                                            ['husband', 'preserve', 'save'],
                                            ['dissipate', 'lavish', 'waste', 'squander'],
                                            'conservation n. 保护')]),
                              Word('considerable', "",
                                   [TestWay('adj',
                                            '(数量上)可观(而值得注意)的',
                                            'sufficiently large in size, amount, or number to merit attention',
                                            ['a considerable amount of fortune 一笔可观的财富'],
                                            ['extensive', 'substantial', 'large-scale']),
                                    TestWay('adj',
                                            '值得考虑的, 重要的',
                                            'worth consideration; significant',
                                            ['a considerable artist 一位举足轻重的艺术家'],
                                            ['important', 'significant', 'consequential', 'momentous', 'weighty'],
                                            ['trivial', 'insubstantial', 'negligible', 'nominal', 'trifling'])]),
                              Word('console', "",
                                   [TestWay('vt',
                                            '安慰, 藉慰',
                                            'to alleviate the grief, sense of loss, or trouble of; comfort',
                                            ['Only her children could console her when her husband died. 只有她的孩子们才能安抚她失去丈夫的悲痛'],
                                            ['comfort', 'solace', 'soothe', 'calm'],
                                            ['distress', 'torment', 'torture'],
                                            'consolation n. 安慰')]),
                              Word('consolidate', "",
                                   [TestWay('vt',
                                            '使联合, 统一',
                                            'to join together into one whole; unite',
                                            ['consolidate several small school districts 合并了几个小的校区'],
                                            ['unify', 'combine', 'amalgamate'],
                                            ['dissolve', 'sunder', 'fragment']),
                                    TestWay('vt',
                                            '加固, 使安全',
                                            'to make firm or secure; strengthen',
                                            ['consolidate the defense line 加固防线'],
                                            ['enhance', 'strengthen', 'fortify', 'reinforce'],
                                            ['abate', 'attenuate', 'undermine', 'weaken'],
                                            'consolidation n. 合并;加固')]),
                              Word('consonant', "",
                                   [TestWay('adj',
                                            '和谐一致的',
                                            'being in agreement or harmony; free from elements making for discord',
                                            ['His performance was rarely consonant with his reputation. 他的表现与名气大不相符'],
                                            ['harmonious', 'compatible', 'congenial', 'consistent', 'congruous', 'correspondent'],
                                            ['conflicting', 'dissonant', 'discrepant', 'inconsistent'],
                                            'consonance n. 和谐, 一致')])])

list5_unit5 = VocabularyList([Word('conspicuous', "",
                                   [TestWay('',
                                            '显而易见的, 吸引人的',
                                            'obvious to the eye or mind, attracting attention',
                                            ['a conspicuous change in her appearance 她外貌的明显改变'],
                                            ['apparent', 'clear', 'distinct', 'evident', 'manifest', 'plain', 'patent', 'noticeable'],
                                            ['hidden', 'concealed'],
                                            'conspicuousness n. 显然性')]),
                              Word('conspire', "",
                                   [TestWay('v',
                                            '合谋, 秘谋',
                                            'to plan together secretly to commit an illegal or wrongful act or accomplish a legal purpose through illegal action',
                                            ['A group of POWs conspired to abscond. 一批战俘密谋潜逃'],
                                            ['plot', 'contrive', 'connive', 'cogitate', 'intrigue', 'put up'],
                                            other_form = 'conspiracy n. 密谋')]),
                              Word('constitute', "",
                                   [TestWay('vt',
                                            '指派, 任命',
                                            'to appoint to an office, function, or dignity',
                                            ['He was constituted manager. 他被任命为经理'],
                                            ['nominate', 'designate', 'authorize'],
                                            ['discharge', 'dismiss', 'abdicate', 'resign']),
                                    TestWay('v',
                                            '构成',
                                            'make up, form, compose',
                                            ['Waterconstitutesthegreaterpartofthehumanbody. 人体中包含着大量的水分'],
                                            ['compose', 'comprise', 'form'],
                                            other_form = 'constitution n. 构成;宪法;体格')]),
                              Word('constrain', "",
                                   [TestWay('v',
                                            '限制',
                                            'to force by imposed stricture, restriction, or limitation',
                                            ['Low temperature constrains the chemical reactivity. 低温降低了化学反应活性'],
                                            ['bridle', 'check', 'confine', 'imprison', 'restrain', 'trammel'],
                                            ['release']),
                                    TestWay('v',
                                            '使人屈服于(压力、感情等)',
                                            'to cause (a person) to give in to pressure',
                                            ['constrained by his conscience to tell the truth 受他良心的驱使而说实话'],
                                            ['coerce', 'compel', 'oblige', 'sandbag'],
                                            other_form = 'constrained adj. 受限的')]),
                              Word('constringe', "",
                                   [TestWay('vt',
                                            '使紧缩',
                                            'to make narrow or draw together',
                                            ['A styptic pencil stopped the bleeding by constringing the small blood vessels at the site of cut. 止血笔通过挤压伤口处的血管阻止了出血'],
                                            ['capsule', 'constrict', 'narrow', 'compress', 'squeeze', 'telescope'],
                                            ['broaden', 'expand', 'outstretch'])]),
                              Word('construct', "",
                                   [TestWay('v',
                                            '建造, 建立',
                                            'to form by assembling or combining parts',
                                            ['construct a new library 建一座新图书馆'],
                                            ['assemble', 'build', 'fabricate', 'make', 'produce', 'rear', 'set up'],
                                            ['demolish', 'destroy', 'raze']),
                                    TestWay('v',
                                            '创造, 想出',
                                            'to create or think of by clever use of the imagination',
                                            ['He managed to construct a theory that fits all the facts. 他成功 出了一个与所有事实相吻合的理论'],
                                            ['contrive', 'devise', 'excogitate', 'fabricate', 'vamp up'],
                                            other_form = 'construction n. 建设, 建造')]),
                              Word('consummate', "",
                                   [TestWay('adj',
                                            '专业的, 有造诣的',
                                            'extremely skilled and accomplished',
                                            ['a consummate liar 一个老练的骗子'],
                                            ['accomplished', 'finished', 'virtuosic', 'versed', 'veteran'],
                                            ['amateur']),
                                    TestWay('adj',
                                            '无纰漏的, 完美的',
                                            'complete in every detail; perfect',
                                            ['The difficult aria displayed her consummate skill. 高难度的咏叹调展示了她完美的技巧'],
                                            ['flawless', 'impeccable', 'perfect'],
                                            ['defective']),
                                    TestWay('adj',
                                            '最高档次的, 最大规模的',
                                            'of the greatest or highest degree or quantity',
                                            synonyms = ['maximum', 'paramount', 'supreme', 'top', 'utmost'],
                                            antonyms = ['minimal'])]),
                              Word('contagious', "",
                                   [TestWay('adj',
                                            '传染的',
                                            'communicable by contact; catching',
                                            ['contagious diseases 传染病'],
                                            ['infectious', 'pestilent', 'transmissible'],
                                            ['incommunicable']),
                                    TestWay('adj',
                                            '(情绪等)唤起共鸣的',
                                            'exciting a similar feeling or reaction in others',
                                            ['The enthusiasm of the new club members was contagious. 新成员的热情具有很强的感染力'],
                                            ['catching', 'epidemic', 'spreading'],
                                            other_form = 'contagiousness n. 可传染性')]),
                              Word('contaminate', "",
                                   [TestWay('vt',
                                            '染污, 掺杂',
                                            'to soil, stain, corrupt, or infect by contact or association',
                                            ['Bacteria contaminated the wound. 细菌感染了伤口'],
                                            ['pollute', 'defile', 'taint', 'infect'],
                                            ['purify', 'sanitize'],
                                            'contamination n. 污染; contaminant n. 污染物')]),
                              Word('content', "",
                                   [TestWay('v',
                                            '使满足',
                                            'to appease the desires of',
                                            ['One glass of beer every day could content him. 每天一杯啤酒就能满足他'],
                                            ['satisfy', 'gratify', 'rejoice'],
                                            ['discontent']),
                                    TestWay('n',
                                            '主题',
                                            'a major object of interest or concern (as in a discussion or artistic composition)',
                                            ["Although I appreciate the poem's lyrical qualities, I don't understand its content. 虽然我很欣赏这首诗歌的 节奏美, 但我无法理解其主题"],
                                            ['motive', 'subject', 'theme', 'topic']),
                                    TestWay('n',
                                            '内容, 内涵',
                                            'the idea that is conveyed or intended to be conveyed to the mind by language, symbol, or action',
                                            ['The speech was filled with fancy words but devoid of any real content. 这篇演讲辞藻华丽, 但是没什么实质性内容'],
                                            ['intention', 'purport', 'sense', 'significance'],
                                            other_form = 'contented adj. 满足的')])])

list5_unit6 = VocabularyList([Word('contentious', "",
                                   [TestWay('adj',
                                            '引起争论的',
                                            'likely to cause contention; argumentative',
                                            ['contentious contents in a movie 电影中引发争论的内容'],
                                            ['controversial', 'disputatious', 'polemical', 'scrappy']),
                                    TestWay('adj',
                                            '好争论的, 好战的',
                                            'exhibiting an often perverse and wearisome tendency to quarrels and disputes',
                                            ['The Tartars were a contentious people who terrorized much of Asia and eastern Europe during the Middle Ages. 鞑靼是一个好斗的民族, 他在中世纪时期统治了大片亚洲和东欧的土地'],
                                            ['belligerent', 'bellicose', 'combative', 'truculent', 'litigious', 'pugnacious'],
                                            ['dovish', 'peace-loving'])]),
                              Word('contiguous', "",
                                   [TestWay('adj',
                                            '接壤, 相邻的',
                                            'sharing an edge or boundary; touching',
                                            ['contiguous nations at war 交战中的邻国'],
                                            ['adjacent', 'abutting', 'neighboring', 'juxtaposed', 'verging'],
                                            ['apart', 'separate'],
                                            'contiguity 接壤')]),
                              Word('contort', "",
                                   [TestWay('vt',
                                            '扭曲',
                                            'to twist, wrench, or bend severely out of shape',
                                            ['acontortedversionofthetruth 被歪曲的真相'],
                                            ['deform', 'distort', 'warp', 'misshape'],
                                            other_form = 'contortion n. 扭曲')]),
                              Word('contract', "",
                                   [TestWay('n',
                                            '契约, 合同',
                                            'a binding agreement between two or more persons or parties, especially one that is written and enforceable by law',
                                            ['a billion-dollar contract from Department of Defense 来自国防部的巨额合同'],
                                            ['agreement', 'compact', 'convention', 'treaty']),
                                    TestWay('v',
                                            '收缩',
                                            'to reduce in size by drawing together; shrink',
                                            ['contract muscle 收缩肌肉'],
                                            ['compress', 'condense', 'concentrate'],
                                            ['expand', 'inflate']),
                                    TestWay('v',
                                            '感染疾病',
                                            'to become affected by a disease or disorder',
                                            ['contracted a severe cold that later turned into pneumonia 染上了重感冒, 最终发展成肺炎'],
                                            ['catch', 'get', 'sicken'],
                                            ['heal'],
                                            'contractor n. 承包商')]),
                              Word('contravene', "",
                                   [TestWay('v',
                                            '违反, 反对',
                                            'to violate, to oppose in argument: contradict',
                                            ['contravene the proposal with no reservation 毫无保留地反对这一 案'],
                                            ['breach', 'infringe', 'transgress', 'fracture', 'deny', 'contradict', 'gainsay', 'reject'],
                                            ['uphold', 'support', 'buttress', 'comply', 'conform', 'observe'],
                                            'contravention n. 反对;违反, 触犯')]),
                              Word('contrite', "",
                                   [TestWay('adj',
                                            '(因为有罪孽或过错而感到)后悔悲痛的',
                                            'feeling or showing sorrow and remorse for a sin or shortcoming',
                                            ['too late to feel contrite 现在后悔已为时已晚'],
                                            ['compunctious', 'regrettable', 'remorseful', 'apologetic', 'penitent', 'repentant', 'rueful'],
                                            ['impenitent', 'unrepentant'])]),
                              Word('contumacious', "",
                                   [TestWay('adj',
                                            '不服从的, 倔强的',
                                            'stubbornly disobedient; rebellious',
                                            ['Contumaciousinsurgentsrefusetotalk. 不愿服从命令的叛军拒绝对话'],
                                            ['balky', 'contumacious', 'defiant', 'insubordinate', 'intractable', 'obstreperous', 'rebellious', 'recalcitrant', 'refractory', 'restive', 'ungovernable', 'unruly', 'untoward', 'wayward', 'willful'],
                                            ['obedient', 'docile', 'ruly'],
                                            'contumacy n. 不服从, 反抗')]),
                              Word('conundrum', "",
                                   [TestWay('n',
                                            '无法解决的问题, 迷',
                                            'a paradoxical, insoluble, or difficult problem; a dilemma',
                                            ['a difficult conundrum even for the experts 一道即便是专家也束手无策的难题'],
                                            ['enigma', 'mystery', 'puzzlement', 'riddle', 'secret'])]),
                              Word('convalesce', "",
                                   [TestWay('vi',
                                            '渐渐康复, 渐愈',
                                            'to recover health and strength gradually after sickness or weakness',
                                            ['the time needed to convalesce after an operation 手术后需要用来康复的时间'],
                                            ['heal', 'recover', 'recuperate', 'recoup', 'snap back'],
                                            ['aggravate', 'deteriorate', 'intensify'])]),
                              Word('convenience', "",
                                   [TestWay('n',
                                            '便利, 方便',
                                            'fitness or suitability for performing an action or fulfilling a requirement',
                                            ['the convenience of living in megacity 住在大城市的便利'],
                                            ['accommodation', 'amenity', 'ease', 'facility'],
                                            ['burden', 'millstone'],
                                            'convenient adj. 方便的, 便捷的')])])

list5_unit7 = VocabularyList([Word('convention', "",
                                   [TestWay('n',
                                            '常规, 习俗',
                                            'general agreement on or acceptance of certain practices or attitudes',
                                            ['By convention, north is at the top of most maps. 按照常规, 北方在大多数地图上指向上'],
                                            ['custom', 'ritual', 'manner'],
                                            ['deviation']),
                                    TestWay('n',
                                            '公约, 协议',
                                            'a general agreement about basic principles or procedures',
                                            ['Under this circumstance Geneva convention does not comply. 此情形下《日内瓦公约》无效'],
                                            ['treaty', 'agreement', 'compact', 'contract']),
                                    TestWay('n',
                                            '大会, 集会',
                                            'a coming together of a number of persons for a specified purpose',
                                            ['attended a convention of mathematicians in California 参加了加州数学家的一次集会'],
                                            ['assembly', 'congress', 'council', 'gathering'],
                                            other_form = 'conventional adj. 传统习俗上的')]),
                              Word('converge', "",
                                   [TestWay('v',
                                            '汇集, 交汇于一点',
                                            'tending to move toward one point or one another',
                                            ['the main streets converge on a central square 众主干道在中央广场交汇'],
                                            ['meet', 'focus', 'concentrate'],
                                            ['diverge', 'deviate', 'digress'],
                                            'convergent adj. 汇集的; convergence n. 汇集')]),
                              Word('conversant', "",
                                   [TestWay('adj',
                                            '熟悉的',
                                            'having frequent or familiar association',
                                            ['conversant with the accounting system 熟知会计系统'],
                                            ['acquaint', 'aware', 'familiar', 'informed', 'versed'],
                                            ['ignorant', 'unfamiliar'],
                                            'conversance n. 熟知, 造诣')]),
                              Word('convert', "",
                                   [TestWay('n',
                                            '被改变宗教信仰的人',
                                            'one that is converted',
                                            synonyms = ['proselyte']),
                                    TestWay('vt',
                                            '使改变信仰',
                                            'to bring over from one belief, view, or party to another',
                                            ['European missionaries converted thousands to Christianity. 欧洲传教士使成百上千的人改信了基督教'],
                                            ['persuade', 'proselytize', 'bring', 'lead']),
                                    TestWay('vt',
                                            '改变, 转化',
                                            'to alter the physical or chemical nature or properties of especially in manufacturing',
                                            ['convert water into ice 将水转化成冰'],
                                            ['alter', 'change', 'transform', 'transfigure'],
                                            other_form = 'converter n. 转换器;convertible adj. 可转变的; n. 敞篷跑车')]),
                              Word('convex', "",
                                   [TestWay('adj',
                                            '凸起的',
                                            'having a surface or boundary that curves or bulges outward, as the exterior of a sphere',
                                            ['A convex function has the property that a line joining any two points on its graph lies on or above the graph. 凸函数具有如下的性质: 其图像上任何两点连线的任何部分都不低于连结两点的函数曲线'],
                                            ['bulging'],
                                            ['dent', 'concave'])]),
                              Word('convey', "",
                                   [TestWay('vt',
                                            '运输',
                                            'to take or carry from one place to another; transport',
                                            ['goods conveyed by sea 海路运输的货物'],
                                            ['carry', 'transfer', 'ferry', 'transmit']),
                                    TestWay('v',
                                            '传递, 交流',
                                            'to impart or communicate by statement, suggestion, gesture, or appearance',
                                            ['struggling to convey his feelings 挣扎着表达他的情感'],
                                            ['conduct', 'communicate', 'impart', 'pass on'],
                                            ['withhold'])]),
                              Word('conviction', "",
                                   [TestWay('n',
                                            '深信, 确信',
                                            'the state of being convinced',
                                            ['a warrior of strong conviction 一名信念坚定的战士'],
                                            ['assurance', 'certainty', 'certitude'],
                                            ['dubiety', 'incredulity', 'uncertainty', 'incertitude']),
                                    TestWay('n',
                                            '证明有罪',
                                            'state of being found or proved guilty',
                                            ["evidence that led to the suspect's conviction 证明嫌疑犯有罪的证据"],
                                            ['sentence'],
                                            ['acquittal', '宣告无罪'],
                                            'convict v. 宣判有罪')]),
                              Word('convoke', "",
                                   [TestWay('v',
                                            '召集开会',
                                            'to bring together by or as if by summons',
                                            ['to convoke Parliament 召开国会'],
                                            ['assemble', 'convene', 'summon', 'muster'],
                                            ['adjourn'])]),
                              Word('convoluted', "",
                                   [TestWay('adj',
                                            '复杂的, 费解的',
                                            'complicated; intricate',
                                            ['a convoluted way of describing a simple mechanism 用令人费解的方法解释一个简单的原理'],
                                            ['complex', 'knotty', 'involved', 'sophisticated', 'twisted', 'tangled', 'labyrinthine'],
                                            ['straightforward'])]),
                              Word('convulsion', "",
                                   [TestWay('n',
                                            '痉挛(强烈的、无法控制的肌肉收缩)',
                                            'an abnormal violent and involuntary contraction of the muscles',
                                            ['Convulsions are usually accompanied by loss of consciousness. 痉挛常常伴随着失去意识']),
                                    TestWay('n',
                                            '骚乱',
                                            'a violent disturbance',
                                            ['a regime in convulsion 动荡中的政权'],
                                            ['commotion', 'ferment', 'tumult', 'upheaval', 'clamor', 'tempest', 'uproar'],
                                            ['serenity', 'tranquility'],
                                            'convulse v. 剧烈震动; 痉挛')])])

list5_unit8 = VocabularyList([Word('coop', "",
                                   [TestWay('vt',
                                            '监禁, 困于...之中',
                                            'to confine in a restricted and often crowded area',
                                            ['Those restless kids were cooped up in the house on a rainy. 雨天那些好动的孩子们被困在房子里'],
                                            ['box', 'cage', 'corral', 'encage', 'enclose', 'envelop', 'fence', 'hedge', 'immure', 'include', 'pen', 'wall'],
                                            ['free', 'liberate', 'release'])]),
                              Word('copious', "",
                                   [TestWay('adj',
                                            '丰富的, 大量的',
                                            'large in quantity; abundant',
                                            ['a copious harvest 大丰收'],
                                            ['plentiful', 'abundant', 'ample', 'gushing'],
                                            ['sparse', 'dearth', 'scant'])]),
                              Word('coquette', "",
                                   [TestWay('n',
                                            '调情的女子',
                                            'a woman who makes teasing sexual or romantic overtures; a flirt',
                                            [' A coquette though she might appear to be at first, Violetta from Verdi’s La Traviata is actually yearning for true love. 乍看之下, 威尔第歌剧《茶花女》中的薇奥莱塔是一个轻浮的女子, 但实际上她渴望真爱'],
                                            ['vamp', 'flirt']),
                                    TestWay('v',
                                            '不认真对待',
                                            'to deal with something playfully rather than seriously',
                                            ['interested only in coquetting with her, not marrying her 只想与她保持暧昧关系, 而不结婚'],
                                            ['trifle', 'dally', 'flirt', 'mess around'],
                                            other_form = 'coquet v. 不认真对待, 调情; coquettish adj. 调情的')]),
                              Word('cordon', "",
                                   [TestWay('n',
                                            '警戒线',
                                            'a line or ring of police, soldiers, or vehicles preventing people from entering an area',
                                            ['a cordon of police 警察围成的警戒线'],
                                            ['perimeter']),
                                    TestWay('v',
                                            '围城一道防线',
                                            'to form a protective or restrictive cordon around',
                                            ['cordoned off the area around the explosion scene 在爆炸现场周边设置警戒线'],
                                            ['close', 'obstruct', 'block'])]),
                              Word('cornucopia', "",
                                   [TestWay('n',
                                            '大量',
                                            'an overflowing store; an abundance',
                                            ['a cornucopia of employment opportunities 大量的就业机会'],
                                            ['plentitude', 'plethora', 'wealth', 'profusion', 'affluence'],
                                            ['lack', 'pittance', 'deficiency'])]),
                              Word('coronation', "",
                                   [TestWay('n',
                                            '加冕, 加冕礼',
                                            "the act or ceremony of crowning a sovereign or the sovereign's consort",
                                            ['Two different musical pieces by Mozart (a piano concerto and a mass) are both titled “Coronation”. 莫扎特两部不同的音乐作品(一部钢琴协奏曲和一部弥撒)都被称作“加冕”'],
                                            ['enthronement', 'crowning'],
                                            ['abdication'],
                                            'coronate v. 加冕')]),
                              Word('corporeal', "",
                                   [TestWay('adj',
                                            '肉体的',
                                            'not spiritual',
                                            ['corporeal suffering 肉体上的折磨'],
                                            ['bodily', 'carnal', 'corporal', 'somatic', 'physical', 'fleshly'],
                                            ['spiritual']),
                                    TestWay('adj',
                                            '有形的, 实体的',
                                            'not immaterial or intangible',
                                            synonyms = ['material', 'physical', 'substantial', 'sensible', 'tangible'],
                                            antonyms = ['intangible', 'disembodied', 'immaterial'])]),
                              Word('corroborate', "",
                                   [TestWay('vt',
                                            '用证据或权威证实',
                                            'to support with evidence or authority; make more certain',
                                            ["new evidence to corroborate the defendant's story 能证实被告的故事的新证据"],
                                            ['confirm', 'authenticate', 'justify', 'substantiate', 'validate', 'verify'],
                                            ['controvert', 'contradict', 'deny']),
                                    TestWay('vt',
                                            '供证据, 支持',
                                            'to provide evidence or information for (as a claim or idea)',
                                            ['My personal experience does not corroborate your faith in the essential goodness of people. 我的经历可不赞同你关于“人性本善”的信念'],
                                            ['back', 'bolster', 'buttress', 'reinforce', 'support'],
                                            other_form = 'corroboration n. 证实')]),
                              Word('corrosive', "",
                                   [TestWay('adj',
                                            '腐蚀性的',
                                            'tending to destroy slowly by chemical action',
                                            ['Concentrated sulfur acid is highly corrosive. 浓硫酸有极强的腐蚀性'],
                                            ['erosive', 'caustic'],
                                            ['noncorrosive']),
                                    TestWay('adj',
                                            '讽刺性的',
                                            'bitingly sarcastic',
                                            ['corrosive satire 讽刺性的作品'],
                                            ['sarcastic', 'barbed', 'acerbic', 'satiric', 'acrid', 'barbed', 'mordant', 'tart'],
                                            ['corrosion n. 侵蚀'])]),
                              Word('corrugated', "",
                                   [TestWay('adj',
                                            '褶皱的',
                                            'shaped into a series of regular folds that look like waves',
                                            ['corrugated paper 褶皱的纸'],
                                            ['wrinkled', 'creased', 'folded'],
                                            ['smooth'],
                                            'corrugation n. 褶皱, 折痕')])])

list5_unit9 = VocabularyList([Word('cosmopolitan', "",
                                   [TestWay('adj',
                                            '有世界性眼光的, 包容的',
                                            'having worldwide rather than limited or provincial scope or bearing',
                                            ['a cosmopolitan traveler 云游四海的旅行者'],
                                            ['universal', 'catholic', 'global', 'worldwide'],
                                            ['insular', 'provincial'],
                                            'cosmopolitism n. 世界主义, 天下主义')]),
                              Word('cosset', "",
                                   [TestWay('v',
                                            '宠爱',
                                            'to treat as a pet; pamper',
                                            synonyms = ['caress', 'cuddle', 'dote', 'pet', 'mollycoddle'],
                                            antonyms = ['slight', 'abuse'],
                                            other_form = 'cosseted adj. 被宠坏的')]),
                              Word('countenance', "",
                                   [TestWay('v',
                                            '容忍',
                                            'to put up with (something painful or difficult)',
                                            ['The college administration will not countenance cheating. 大学管理部门决不容忍作弊的存在'],
                                            ['abide', 'endure', 'stand', 'stomach', 'wear']),
                                    TestWay('v',
                                            '赞成, 推崇',
                                            'to have a favorable opinion of',
                                            ["I don't countenance such behavior in children of any age. 对于任何年龄的孩子, 我都不推崇那种行为"],
                                            ['accept', 'favor', 'subscribe'],
                                            ['disapprove', 'frown']),
                                    TestWay('n',
                                            '沉着, 冷静',
                                            'evenness of emotions or temper',
                                            ["The doctor’s purposeful countenance was in stark contrast to everyone else's hysteria. 医生带有目的性的沉着与他人的歇斯底里形成了巨大的反差"],
                                            ['aplomb', 'calmness', 'composure', 'sangfroid', 'serenity'],
                                            ['agitation', 'discomposure', 'perturbation'])]),
                              Word('counterfeit', "",
                                   [TestWay('adj',
                                            '仿制的, 假冒的',
                                            'made in imitation of something else with intent to deceive',
                                            ['counterfeit money 假币'],
                                            ['forged', 'bogus', 'spurious', 'pseudo', 'feigned', 'artificial', 'phony'],
                                            ['authentic', 'genuine']),
                                    TestWay('vt',
                                            '仿制',
                                            'to make a fraudulent replica of',
                                            ['counterfeit the signature 仿造签名'],
                                            ['copy', 'forge', 'imitate', 'simulate', 'mimic']),
                                    TestWay('vt',
                                            '伪装成',
                                            'to present a false appearance of',
                                            ['to counterfeit a happy expression while visiting a sick friend 在看望患病的朋友时装出一副高兴的样子'],
                                            ['affect', 'assume', 'fake', 'pretend'])]),
                              Word('countermand', "",
                                   [TestWay('vt',
                                            '取消, 撤销',
                                            'to revoke (a command) by a contrary order',
                                            ['countermand an order 撤销命令'],
                                            ['annul', 'repeal', 'rescind', 'revoke', 'cancel'],
                                            ['approve', 'permit', 'sanction'])]),
                              Word('court', "",
                                   [TestWay('vt./n',
                                            '追求, 献殷勤',
                                            'to seek the affections of',
                                            ['court the young lady by bring her flowers every day 通过每天给年轻女孩送花追求女孩'],
                                            ['woo', 'pursue', 'invite'],
                                            ['spurn', 'snub'],
                                            'courteous adj. 彬彬有礼的')]),
                              Word('covert', "",
                                   [TestWay('adj',
                                            '隐蔽的, 秘密的',
                                            'not openly shown, engaged in, or avowed',
                                            ['covert alliance 秘密联盟'],
                                            ['cloistered', 'hidden', 'secret', 'sheltered'],
                                            ['open', 'overt', 'aboveboard']),
                                    TestWay('n',
                                            '隐秘掩护所',
                                            'a place where a person goes to hide or to avoid others',
                                            ['set up a covert from which to watch wildlife without being detected 设立了一个隐蔽的野生动物观测点'],
                                            ['concealment', 'hermitage', 'hideaway', 'nest', 'lair'])]),
                              Word('covetous', "",
                                   [TestWay('adj',
                                            '贪婪的, 渴求财富的',
                                            "marked by inordinate desire for wealth or possessions or for another's possessions",
                                            ['cast covetous eyes on their neighbors’ fields 对他邻居的土地垂涎'],
                                            ['acquisitive', 'avaricious', 'avid', 'rapacious', 'grasping'],
                                            ['easily-satiated', 'unenvious'],
                                            'covet v. 觊觎, 贪婪')]),
                              Word('cow', "",
                                   [TestWay('v',
                                            '恐吓, 威胁',
                                            'to frighten with threats or a show of force',
                                            ['cow sb. into doing sth. 威吓某人做某事'],
                                            ['intimidate', 'browbeat', 'bully', 'hector', 'awe'],
                                            ['embolden', 'encourage', 'inspirit'],
                                            'cowed adj. 被吓倒的')]),
                              Word('cowardice', "",
                                   [TestWay('n',
                                            '懦弱, 不坚定',
                                            'lack of courage or resolution',
                                            ['cowardice in the face of danger 面对危险时的懦弱'],
                                            ['cravenness', 'dastardliness', 'gutlessness', 'poltroonery', 'pusillanimity', 'spinelessness'],
                                            ['courage', 'guts', 'pluck', 'intrepidness', 'nerve', 'stoutness', 'valiance', 'valor'],
                                            'coward n. 懦夫')])])

list5_unit10 = VocabularyList([Word('cower', "",
                                   [TestWay('vi',
                                            '畏缩',
                                            'to cringe in fear',
                                            ['The dog cowered under the table. 狗吓得蜷缩在桌子下面'],
                                            ['fawn', 'flinch', 'grovel', 'quail', 'recoil', 'wince'])]),
                              Word('cozen', "",
                                   [TestWay('v',
                                            '诱骗',
                                            'to mislead by means of a petty trick or fraud; deceive',
                                            ['The salesman cozened the old lady into buying his goods. 推销员诱使老太太买下了他的东西'],
                                            ['bamboozle', 'dupe', 'cheat', 'deceive', 'beguile', 'delude', 'take in'])]),
                              Word('cramped', "",
                                   [TestWay('adj',
                                            '狭促的',
                                            'uncomfortably small or restricted',
                                            ['a cramped cubbyhole in an office 办公室里狭小的隔间'],
                                            ['confined', 'limited', 'restrained'],
                                            ['commodious', 'spacious'],
                                            'cramp n. 狭窄')]),
                              Word('crass', "",
                                   [TestWay('adj',
                                            '粗俗的, 愚钝的',
                                            'so crude and unrefined as to be lacking in discrimination and sensibility',
                                            ['crass receptionist 粗俗的招待员'],
                                            ['coarse', 'crude', 'rude', 'incult', 'uncouth', 'vulgar'],
                                            ['civilized', 'polished', 'refined', 'urbane', 'genteel'])]),
                              Word('crave', "",
                                   [TestWay('vt',
                                            '热望',
                                            'to have an intense desire for',
                                            ['crave alcohols and cigarettes 渴望烟酒'],
                                            ['need', 'yearn', 'desire', 'pine', 'thirst', 'itch', 'long', 'yen'],
                                            ['spurn'],
                                            'craving n. 迫切的渴望')]),
                              Word('craven', "",
                                   [TestWay('adj',
                                            '非常懦弱的, 因胆小令人鄙视的',
                                            'lacking the least bit of courage; contemptibly fainthearted',
                                            ['a craven deserter 一个懦弱的逃兵'],
                                            ['cowardly', 'gutless', 'pusillanimous', 'spineless'],
                                            ['dauntless', 'fearless', 'gallant', 'gutsy', 'intrepid', 'stalwart', 'stout', 'stouthearted', 'valiant', 'valorous'])]),
                              Word('crease', "",
                                   [TestWay('n',
                                            '折痕',
                                            'a line made by pressing, folding, or wrinkling',
                                            ['flatten the creases of the map 抚平地图上的折痕'],
                                            ['wrinkle', 'corrugation', 'fold', 'furrow'],
                                            other_form = 'creased adj. 有折痕的')]),
                              Word('credence', "",
                                   [TestWay('n',
                                            '坚信',
                                            'firm belief in the integrity, ability, effectiveness, or genuineness of someone or something',
                                            ['give credence to gossip 相信绯闻'],
                                            ['belief', 'credit', 'faith', 'trust', 'reliance'],
                                            ['doubt', 'skepticism'])]),
                              Word('credulous', "",
                                   [TestWay('and',
                                            '轻信的, 易受骗的',
                                            'disposed to believe too readily; gullible',
                                            ['accused of swindling credulous investors 被控欺骗轻信的投资者'],
                                            ['believing', 'unwary', 'gullible', 'naïve', 'unsuspecting'],
                                            ['disbelieving', 'skeptical'],
                                            'credulity n. 轻信')]),
                              Word('creek', "",
                                   [TestWay('n',
                                            '小溪, 小河',
                                            'a natural stream of water normally smaller than and often tributary to a river',
                                            ['went wading in the creek 在小溪中涉水而行'],
                                            ['stream', 'branch', 'brook', 'rivulet'])])])

LIST5 = VocabularyList(list5_unit1.words+list5_unit2.words+list5_unit3.words+list5_unit4.words+list5_unit5.words+list5_unit6.words+list5_unit7.words+list5_unit8.words+list5_unit9.words+list5_unit10.words)

