#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list21_unit1 = VocabularyList([Word('referee', "",
                                   [TestWay('n',
                                            '仲裁者; 裁判员',
                                            'a person who impartially decides or resolves a dispute or controversy',
                                            ["served as the unofficial referee in disputes over the family business 作为一个非官方协调员, 解决家庭事务中的纠纷"],
                                            'adjudicator, arbiter, arbitrator, judge, umpire'),
                                    TestWay('vt',
                                            '(就纠纷或争议)给出意见',
                                            'to give an opinion about (something at issue or in dispute)',
                                            ["Their father usually ends up refereeing any disputes concerning use of the big TV. 最后往往是他们的父亲决定该看什么电视频道, 从而解决了相关争执。"],
                                            'adjudge, adjudicate, arbitrate, decide, determine, settle',
                                            'consult')]),
                              Word('refine', "",
                                   [TestWay('vt',
                                            '提纯, 精炼',
                                            'to free (as metal, sugar, or oil) from impurities or unwanted material',
                                            ["Oil is refined so as to remove naturally occurring impurities. 原油通过精炼可去除其中天然存在的杂质。"],
                                            'filter, garble, purify, winnow',
                                            'adulterate, contaminate, pollute'),
                                    TestWay('vt',
                                            '改善, 改进',
                                            'to improve or perfect by pruning or polishing',
                                            ["You’d better refine your backhand before the big tennis match if you want to throne. 如果你想获得冠军的话, 你最好在网球大赛开赛前再提升一下反手的技术。"],
                                            'ameliorate, amend, better, enhance, enrich, help, meliorate, perfect, polish, upgrade',
                                            'deteriorate, worsen',
                                            'refined adj. (物品)精雕细琢的, (人)彬彬有礼的; refinery n. 炼油厂')]),
                              Word('reflect', "",
                                   [TestWay('vt',
                                            '反射',
                                            'to prevent passage of and cause to change direction',
                                            ["The color of an objective is largely determined by what light it reflects. 物体的颜色很大程度上是由它能反射的光所决定的。", "Mirrors indiscriminately reflect all visible lights. 镜子不加区分地反射所有的可见光。"],
                                            antonyms = 'absorb'),
                                    TestWay('vt',
                                            '反映, 显露',
                                            'to make manifest or apparent: show',
                                            ["Her book clearly reflects her religious beliefs. 她的书反映了她的宗教信仰。", "Where you come fromcouldbe easily reflected in your accent. 你的口音可以轻易地暴露你来自哪里。"],
                                            'bespeak, betray, demonstrate, evince, manifest, reveal, show',
                                            'conceal, cover, hide, mask, obscure, occlude, veil'),
                                    TestWay('vi',
                                            '思考',
                                            'to think seriously',
                                            ["I reflected on my path as an undergraduate and my future as a PhD candidate. 我思考了我作为一名本科生的成长足迹以及我读博士的未来。"],
                                            'consider, cogitate, contemplate, deliberate, meditate, muse, ponder, ruminate, think',
                                            'reflective adj. 思考的, 深思熟虑的')]),
                              Word('refractory', "",
                                   [TestWay('adj',
                                            '倔强的, 不顺从的',
                                            'resisting control or authority',
                                            ["Refractory players will be ejected from the game. 不服从裁判命令的球员将会被驱逐出场。"],
                                            'balky, contumacious, defiant, incompliant, insubordinate, intractable, obstreperous, rebellious, refractory, unruly',
                                            'amenable, compliant, conformable, docile, governable, obedient, ruly, submissive, tractable')]),
                              Word('refulgent', "",
                                   [TestWay('adj',
                                            '辉煌的, 灿烂的',
                                            'shining radiantly; resplendent',
                                            ["Refulgent sunlight broke through the clouds, creating huge swaths of light in the valley below us. 耀眼的阳光穿透了云层, 在我们脚下的峡谷中投下了一块巨大的光斑"],
                                            'beaming, brilliant, dazzling, incandescent, lucid, luminous, lustrous, radiant, resplendent, splendid',
                                            'dim, dull, lackluster',
                                            'refulgence n. 灿烂, 光芒四射')]),
                              Word('refute', "",
                                   [TestWay('vt',
                                            '否认',
                                            'to declare not to be true',
                                            ["While the speak woman was publicly refuting rumors of a merger, behind the scenes the CEO was working to effect that very outcome. 尽管女发言人一再公开否认合并的谣言, 首席执行官却在幕后为这一目标而努力。"],
                                            'contradict, disaffirm, disavow, disclaim, disconfirm, deny, gainsay, negate, negative, reject, repudiate',
                                            'acknowledge, admit, avow, concede, confirm'),
                                    TestWay('vt',
                                            '证明为假, 证伪',
                                            'to prove wrong by argument or evidence: show to be false or erroneous',
                                            ["The triumph of Chinese athlete Liu Xiang in the 2004 Olympics effectively refuted the views that Asians are physically inferior to others. 中国运动员刘翔在2004年雅典奥运会上的胜利有效地驳斥了亚洲人在体格上不如其他人种的观点"],
                                            'belie, confute, debunk, discredit, falsify, rebut, shoot down',
                                            'confirm, prove, validate, verify',
                                            'refutable adj.可辩驳的')]),
                              Word('regenerate', "",
                                   [TestWay('vt',
                                            '使重获新生, 使焕然一新',
                                            'to bring back to life, practice, activity or a former condition of vigor',
                                            ["The lizard is able to regenerate its tail. 蜥蜴能够重新长出断尾。", "The whole community was regenerated thanks to a government grant for repairing all the old buildings. 多亏了政府用于维修老楼的专项拨款, 整个社区焕然一新。"],
                                            'recharge, refresh, rejuvenate, rekindle, renew, restore, resurrect, resuscitate, revitalize, revivify',
                                            'degenerate, deteriorate, worsen'),
                                    TestWay('vi./vt',
                                            '(使)洗心革面',
                                            'to make better in behavior or character',
                                            ["Every time he made a mistake, he would promise to regenerate. 每次犯错他都会保证洗心革面, 下次不再犯。"],
                                            'habilitate, reclaim, redeem, rehabilitate',
                                            other_form = 'regeneration n. 复兴')]),
                              Word('regimen', "",
                                   [TestWay('n',
                                            '(政治上的)统治',
                                            'lawful control over the affairs of a political unit (as a nation)',
                                            ["A new party will have regimen over the nation and, hopefully, bring some much-needed change. 一个新的政党将要上台, 希望他们能带来一些迫切的改革。"],
                                            'administration, authority, governance, jurisdiction, regime')]),
                              Word('regress', "",
                                   [TestWay('vi',
                                            '后退',
                                            'to go back; move backward',
                                            ["To stand still is to regress.不进则退。"],
                                            'retrogress, return, revert',
                                            'advance, develop, evolve, progress'),
                                    TestWay('vi',
                                            '退化, 恶化',
                                            'to become worse or of less value',
                                            ["The annual celebration has regressed to the point where it's nothing more than an excuse to get drunk. 年度的庆祝活动已经堕落成一个尽情喝醉的借口了。"],
                                            'atrophy, crumble, decay, decline, degenerate, descend, deteriorate, ebb, retrograde, rot, sink, worsen',
                                            'ameliorate, improve, meliorate',
                                            'regressive adj. 后退的, 退化的; regression n. 后退, 退化')]),
                              Word('rehabilitate', "",
                                   [TestWay('vt',
                                            '使复原, 使康复',
                                            'to restore to a former state (as of efficiency, good management, or solvency) or a healthy condition',
                                            ["new policies in hopes of rehabilitating the national economy 被指望能振兴国家经济的新政策", "She decided to undergo physical therapy to help rehabilitate her broken elbow. 她决定采取理疗来治疗受伤的手肘。"],
                                            'cure, fix, mend, rejuvenate, resuscitate, revitalize, revive, set up',
                                            'debilitate, enervate, enfeeble, weaken, relapse'),
                                    TestWay('vi./vt',
                                            '(使)洗心革面',
                                            'to make better in behavior or character',
                                            ["an organization that rehabilitates criminals so they can reenter society 一个让罪犯洗心革面的机构, 以便让他们能重返社会"],
                                            'habilitate, reclaim, redeem, regenerate',
                                            other_form = 'rehabilitation n. 康复, 复原')])])

list21_unit2 = VocabularyList([Word('rehearsal', "",
                                   [TestWay('n',
                                            '排练, 彩排',
                                            'the act of practicing in preparation for a public performance',
                                            ["We made a few mistakes in rehearsal, but we were pretty sure that we'd be OK on opening night. 彩排过程中我们犯了几个错误, 但正式开幕式当晚我们有信心做得很好。"],
                                            'practice, trial, dry run',
                                            'extemporization, impromptu, improvisation')]),
                              Word('reign', "",
                                   [TestWay('n',
                                            '统治权',
                                            'the right or means to command or control others',
                                            ["A healthy nation should be governed by the reign of law and not by the will of its chief executive. 一个健康的国家应该是法制的, 而非由最高领导人的意志统领。", "They accused him of carrying out a reign of terror. 他们指责他搞独裁暴政。"],
                                            'arm, authority, clutch, command, control, dominion, grip, hold, mastery, sway',
                                            'impotence, impotency, powerlessness'),
                                    TestWay('vi',
                                            '占统治地位或盛行',
                                            'to be predominant or prevalent',
                                            ["Chaos reigned in the classroom. 整个教室充满了混乱。", "Panic reigned as the fire spread. 随着大火的扩散, 恐慌也迅速蔓延"],
                                            'dominate, domineer, prevail, predominate, rule')]),
                              Word('rein', "",
                                   [TestWay('n',
                                            '抑制, 限制',
                                            'the act or practice of keeping something (as an activity) within certain boundaries',
                                            ["The oversight committee called on the corporation to keep a much tighter rein on the activities of its contractors. 监督委员会要求这个公司对其承包商的行为采取更为严格的管控。"],
                                            'circumscription, confinement, limitation, stint'),
                                    TestWay('vi',
                                            '抑制, 控制',
                                            'to keep from exceeding a desirable degree or level (as of expression)',
                                            ["A good man knows how to rein in his temper. 君子知道如何按捺住火气。"],
                                            'bridle, check, constrain, contain, curb, govern, hold, inhibit, keep, measure, regulate, restrain, rule, tame',
                                            'liberate,loose, loosen,unleash')]),
                              Word('reiterate', "",
                                   [TestWay('v',
                                            '重申',
                                            'to say or state again',
                                            ["Let me reiterate our stance. 让我来重述我们的立场。", "I want to reiterate that under no circumstances are you to leave the house. 我想再次重申: 无论如何你都不能离开这间房子。"],
                                            'chime, din, iterate, recapitulate, rehearse, repeat')]),
                              Word('rejoice', "",
                                   [TestWay('vi',
                                            '欣喜, 喜悦',
                                            'to feel joy or great delight',
                                            ["We rejoiced over our unexpected victory on the soccer field. 我们为预料之外的足球胜利而感到欢喜。"],
                                            'crow, delight, exuberate, glory, jubilate, joy, kvell, triumph',
                                            'bemoan, bewail, deplore, grieve, lament, moan, mourn, regret, weep',
                                            'rejoiced adj. 高兴的')]),
                              Word('relapse', "",
                                   [TestWay('vi',
                                            '故态复萌, 再犯',
                                            'to slip or fall back into a former worse state',
                                            ["The patient wondered whether his illness would relapse. 病人想知道他的病会不会复发。"],
                                            'recidivate, regress, retrogress, revert',
                                            'habilitate, reclaim, redeem, regenerate, convalesce, rehabilitate')]),
                              Word('release', "",
                                   [TestWay('vt',
                                            '排放',
                                            'to throw or give off',
                                            ["We bought an air freshener that releases a pleasing scent into the room. 我们买了一个能向房间里释放怡人香味的空气净化机"],
                                            'cast, exhale, expel, irradiate, issue, vent',
                                            'absorb'),
                                    TestWay('vt',
                                            '释放, 使获得自由',
                                            'to set free from restraint, confinement, or servitude',
                                            ["The government was asked to release the prisoners immediately. 政府被要求立即释放囚犯。"],
                                            'discharge, disenthrall, emancipate, enfranchise, liberate, loose, loosen, manumit, unchain, unfetter',
                                            'bind, confine, enchain, fetter, restrain'),
                                    TestWay('vt',
                                            '解雇',
                                            'to let go from office, service, or employment',
                                            ["They released the workers who couldn't handle the new technology. 他们解雇了所有不能掌握新技术的工人。"],
                                            'bounce, cashier, dismiss, fire, remove, retire, sack, terminate',
                                            'employ, engage, hire')]),
                              Word('relentless', "",
                                   [TestWay('adj',
                                            '残酷的, 无情的',
                                            'showing or promising no abatement of severity, intensity, strength, or pace',
                                            ["He was the most teacher enemy I have ever known. 他是我所知的最狠的老师。"],
                                            'grim, inexorable, ironfisted, merciless, mortal, ruthless, unrelenting',
                                            'charitable, clement, merciful, lenient'),
                                    TestWay('adj',
                                            '固执的, 不肯妥协的',
                                            "showing no signs of slackening or yielding in one's purpose",
                                            ["The team's offense was relentless in trying to score. 进攻球员毫不妥协地努力得分。"],
                                            'adamant, dogged, headstrong, mulish, obdurate, pertinacious, rigid, uncompromising, unyielding',
                                            'acquiescent, amenable, compliant, complying, flexible, pliable, pliant, relenting, yielding')]),
                              Word('relevant', "",
                                   [TestWay('adj',
                                            '有关系的, 重要的',
                                            'having a bearing on or connection with the matter at hand',
                                            ["Make sure your answers during the interview are short and relevant. 确保你在面试时的回答简短而恰当。", "You need to bring all the relevant certificates with you. 你需要携带所有的相关证明。"],
                                            'applicable, apposite, apropos, germane, material, pertinent, pointed, relative',
                                            'extraneous, immaterial, impertinent, inapplicable, inapposite, irrelevant, pointless',
                                            'relevance n. 关联')]),
                              Word('religion', "",
                                   [TestWay('n',
                                            '宗教, 信仰',
                                            'a body of beliefs and practices regarding the supernatural and the worship of one or more deities',
                                            ["The Jewish religion has followers in many parts of the globe. 犹太教在全球范围内有大量信徒。"],
                                            'credo, creed, cult, faith, persuasion'),
                                    TestWay('n',
                                            '(对于宗教信仰的)忠诚, 虔诚',
                                            'belief and trust in and loyalty to God',
                                            ["Without his religion, he would not have been able to survive all the difficulties he has faced over the years. 如果不是他的虔诚, 他是不可能渡过这些年来一直面临的难关的。"],
                                            'devotion, piety',
                                            'atheism, godlessness',
                                            'religious adj. 宗教的, 忠诚的')])])

list21_unit3 = VocabularyList([Word('relinquish', "",
                                   [TestWay('vt',
                                            '放弃(职位、权力等)',
                                            'to give up (as a position of authority) formally',
                                            ["She relinquished his position to the company's vice president with very mixed feelings. 怀着十分复杂的情感, 她放弃了公司副总裁的职位。"],
                                            'abnegate, cede, renounce, resign, surrender',
                                            'inaugurate, usurp'),
                                    TestWay('vt',
                                            '移交, 交出',
                                            'to give (something) over to the control or possession of another usually under duress',
                                            ["The boy reluctantly relinquished the illegal fireworks to the police officer. 小男孩不情愿地把非法的焰火交给了警察。", "The court ordered him to relinquish custody of his child. 法庭要求他交出孩子的监护权。"],
                                            'deliver, render, yield, turn in, turn over',
                                            'keep, retain, withhold')]),
                              Word('relish', "",
                                   [TestWay('n',
                                            '喜好, 偏好',
                                            'an appetite for something; a strong appreciation or liking',
                                            ["She has great relish for early morning walks, which she takes nearly every day. 她对早晨散步有格外的喜好——几乎每天早上她都会如此。"],
                                            'appetite, fancy, favor, fondness, like, love, partiality, preference, taste',
                                            'aversion, disfavor, disgust, dislike, distaste, hatred, loathing'),
                                    TestWay('n',
                                            '(愿望达成时的)高兴, 满足感',
                                            "the feeling experienced when one's wishes are met",
                                            ["He ate the bowl of ice cream with relish. 他高兴地吃着冰淇淋。"],
                                            'content, delectation, delight, enjoyment, gladness, gratification, happiness, satisfaction',
                                            'discontent, displeasure, dissatisfaction, unhappiness'),
                                    TestWay('vt',
                                            '享受, 喜欢',
                                            'to take keen or zestful pleasure in',
                                            ["He is so hungry that he will relish even plain food. 他是如此的饥饿, 以至于普通的食物也能让他满意。"],
                                            'adore, enjoy, like, love, rejoice, revel, savor',
                                            'abhor, abominate, detest, dislike, hate, loathe')]),
                              Word('reluctant', "",
                                   [TestWay('adj',
                                            '不情愿的, 反感的',
                                            'feeling or showing aversion, hesitation, or unwillingness',
                                            ["I'm reluctant to let him borrow my CDs since he never gives back anything I lend him. 我很不愿意把我的CD借给他, 因为他借了我东西从来不还。"],
                                            'averse, disinclined, indisposed, loath, unwilling',
                                            'willing, disposed, inclined, eager',
                                            'reluctance n. 不愿意, 不情愿')]),
                              Word('remiss', "",
                                   [TestWay('adj',
                                            '疏忽的, 不留心的',
                                            'exhibiting carelessness or slackness',
                                            ["I would be remiss if I didn't tell you how much I appreciated the lovely gift. 如果我不告诉你我是多么的喜欢这个可爱的礼物的话, 那我就太疏忽大意了。"],
                                            'careless, derelict, disregardful, heedless, lax, lazy, neglectful, neglecting, slack',
                                            'attentive, careful, conscientious, meticulous, painstaking, scrupulous')]),
                              Word('remodel', "",
                                   [TestWay('vt',
                                            '改造, 改变结构',
                                            'to alter the structure of',
                                            ["We decided to remodel the warehouse into a museum displaying the products of the company. 我们决定把仓库改造成展览我们公司产品的博物馆"],
                                            'alter, modify, recast, redo, refashion, remake, revamp, revise, rework, vary',
                                            'fix, freeze, set, stabilize')]),
                              Word('remonstrance', "",
                                   [TestWay('n',
                                            '抗议, 抱怨',
                                            'an expression of protest, complaint, or reproof, especially a formal statement of grievances',
                                            ["She seems deaf to her son’s remonstrances. 她似乎对儿子的抗议充耳不闻。", "Aggravated by the noisy metro construction, many residents wrote letters of remonstrance to city officials. 许多被地铁建设的噪音激怒的居民向市政府投去了抗议信。"],
                                            'challenge, complaint, demur, difficulty, fuss, objection, protest, question, remonstration, stink',
                                            'acceptance, acquiescence, agreement, approval, assent, sanction')]),
                              Word('remorse', "",
                                   [TestWay('n',
                                            '懊悔, 悔恨',
                                            'moral anguish arising from repentance for past misdeeds; bitter regret',
                                            ["He felt a deep remorse for having neglected his family over the years. 他为多年来忽略家人的行为表示懊悔。"],
                                            'contriteness, contrition, penitence, regret, remorsefulness, repentance, rue, self-reproach, shame',
                                            'impenitence, remorselessness',
                                            'remorseful adj. 懊悔的, 悔恨的')]),
                              Word('remunerate', "",
                                   [TestWay('vt',
                                            '支付报酬或补偿',
                                            'to pay an equivalent to for a service, loss, or expense',
                                            ["He promptly remunerated the repair company for fixing the satellite TV. 他迅速地支付了维修公司修卫星电视所应得的酬劳。"],
                                            'compensate, indemnify, recompense, recoup, redress, remedy, repay, requite',
                                            other_form = 'remunerative adj. 有报酬的')]),
                              Word('rend', "",
                                   [TestWay('vt',
                                            '撕裂, 猛拉',
                                            'to tear or split apart or into pieces violently',
                                            ["Wolves rend a game to pieces. 狼群会把猎物撕成碎片。", "pain that rends the heart 撕心般的痛"],
                                            'cleave, lacerate, ribbon, rip, rive, rupture, shred, split, tatter, tear',
                                            'associate, coalesce, combine, conjoin, conjugate, connect, fuse, interfuse, join, link, unify')]),
                              Word('renegade', "",
                                   [TestWay('n',
                                            '背教者, 叛徒',
                                            'one who rejects a religion, cause, allegiance, or group for another; a deserter',
                                            ["A band of renegades who had deserted their infantry units were making their way to Mexico. 一支背叛了他们所属的步兵编队的士兵朝着墨西哥前进。"],
                                            'apostate, betrayer, defector, deserter, recreant, traitor, turncoat',
                                            'adherent, loyalist, partisan')])])

list21_unit4 = VocabularyList([Word('renounce', "",
                                   [TestWay('vt',
                                            '(正式地)放弃',
                                            'to give up, refuse, or resign usually by formal declaration',
                                            ["renounce his nationality 退出国籍"],
                                            'abnegate, cede, relinquish, resign, surrender',
                                            'inaugurate, usurp'),
                                    TestWay('vt',
                                            '宣布与…决裂',
                                            'to refuse to follow, obey, or recognize any further',
                                            ["renounce the authority of the church 宣布与教廷彻底决裂"],
                                            'forswear, recant, renege, repeal, repudiate, retract, withdraw',
                                            'adhere, stick',
                                            'renunciation n. 放弃')]),
                              Word('renovate', "",
                                   [TestWay('vt',
                                            '修复, 维修',
                                            'to restore to a former better state (as by cleaning, repairing, or rebuilding)',
                                            ["We will have to renovate the house extensively before we can move in. 在入住之前我们必须大规模翻修一下这栋房子"],
                                            'doctor, fix, patch, recondition, repair, revamp',
                                            'blemish, break, damage, deface, disfigure, harm, hurt, impair, injure, mar, ruin, vandalize, wreck'),
                                    TestWay('vt',
                                            '使重获新生, 使焕然一新',
                                            'to bring back to life, practice, activity or a former condition of vigor',
                                            ["The church was renovated by a new ecumenical spirit. 新的宗教领袖的到来让教堂焕发新生。"],
                                            'recharge, refresh, rejuvenate, rekindle, renew, restore, resurrect, resuscitate, revitalize, revivify',
                                            'degenerate, deteriorate, worsen')]),
                              Word('repartee', "",
                                   [TestWay('n',
                                            '机智的回答',
                                            'a quick witty response',
                                            ["That repartee to the reporter's question drew laughs from the bystanders. 对记者问题的那个机智回答引来了旁观者的笑声。"],
                                            'comeback, riposte'),
                                    TestWay('n',
                                            '打趣, 善意的玩笑',
                                            'good-natured teasing or exchanging of clever remarks',
                                            ["Repartee is harder to do with text messaging. 用短信开起玩笑来困难多了。"],
                                            'backchat, badinage, chaff, jesting, joshing, persiflage, raillery')]),
                              Word('repatriate', "",
                                   [TestWay('vt',
                                            '遣返',
                                            'to restore or return to the country of origin, allegiance, or citizenship',
                                            ["As soon as the war ends, the government will start to repatriate war refugees. 只要战争一结束, 政府就会开始遣返战争难民。"],
                                            'banish, deport, expatriate')]),
                              Word('repeal', "",
                                   [TestWay('vt',
                                            '撤销, 废除(法律等)',
                                            'to rescind or annul by authoritative act',
                                            ["The company called the furniture store to repeal the order for six new desks. 公司要求家具店撤销六张新桌子的订单。", "In 1933, Congress passed the 21st Amendment which repealed the Prohibition Amendment of 1919, thus making the sale, distribution, and use of alcohol legal once again. 1933年, 国会通过了《第二十一修正案》, 该法案废除了于1919年制订的《禁酒法》, 从而使得酒的买卖、配送和使用再次合法化。"],
                                            'abort, abrogate, annul, cancel, disannul, invalidate, negate, null, nullify, rescind, revoke, vacate, void',
                                            'continue, keep, enact, establish, legislate'),
                                    TestWay('vt',
                                            '宣布与…决裂',
                                            'to refuse to follow, obey, or recognize any further',
                                            ["If I find that you have been lying about this, I'll instantly repeal every promise I made to you. 只要我发现在这个问题上你对我撒了谎, 那我们之间的承诺就彻底断裂了。"],
                                            'forswear, recant, renege, renounce, repudiate, retract, withdraw',
                                            'adhere, stick')]),
                              Word('repel', "",
                                   [TestWay('vt',
                                            '抵制',
                                            'to fight against; resist',
                                            ["Self-discipline ensures that you can repel the things that induce you. 自律可以保证你抵制那些诱惑你的事物。", "I repelled the temptation to stay out late and call in sick the next day. 我抵住了晚上玩通宵然后第二天谎称生病的诱惑。"],
                                            'buck, defy, fight, oppose, resist, withstand',
                                            'capitulate, submit, succumb, surrender, yield, give in'),
                                    TestWay('vt',
                                            '使厌恶',
                                            'to cause aversion in: disgust',
                                            ["Evil odors always repel me. 臭味总是让我恶心。"],
                                            'disgust, nauseate, repulse, revolt, sicken',
                                            'allure, attract, bewitch, captivate, charm, enchant, entice, fascinate, lure, seduce, tempt',
                                            'repelling adj. 令人厌恶的')]),
                              Word('repertoire', "",
                                   [TestWay('n',
                                            '(技术、设备或原料等的)详单',
                                            'the complete list or supply of skills, devices, or ingredients used in a particular field, occupation, or practice',
                                            ["The chef's repertoire of specialties seems to be limited, with several of the dishes appearing over and over again in slightly varied guises. 这个厨师的所有拿手好戏看来是很有限的, 因为上来的几盘菜看起来只是稍微换了一下装饰而已。"],
                                            'budget, fund, inventory, pool, reservoir, stock')]),
                              Word('repine', "",
                                   [TestWay('vi',
                                            '抱怨, 表达不满',
                                            'to feel or express discontent or dejection',
                                            ["There is no use repining over a love that's been long lost. 抱怨早已失去的爱情是没有用的。"],
                                            'carp, complain, fuss, gripe, grouch, grouse, growl, grumble, inveigh, moan, murmur, mutter, wail, whine',
                                            'crow, delight, rejoice'),
                                    TestWay('v',
                                            '渴望',
                                            'to long for something',
                                            ["During the deep cold of winter, I repine for warm tropical beaches. 在寒冬, 我渴望温暖的热带海滩。"],
                                            'ache, covet, crave, desiderate, hunger, itch, long, lust, pine, salivate, thirst, want, wish, yearn',
                                            'abhor, abominate, detest, dislike, hate, loathe')]),
                              Word('replete', "",
                                   [TestWay('adj',
                                            '彻底吃饱了的',
                                            "having one's appetite completely satisfied",
                                            ["Everyone is completely replete after the huge meal. 在大餐之后, 每个人都吃撑了。"],
                                            'sated, satiate, satiated, stuffed, surfeited',
                                            'empty, famished, hungry, starved, starving'),
                                    TestWay('adj',
                                            '充满…的, 富于…的',
                                            'possessing or covered with great numbers or amounts of something specified',
                                            ["a scholar replete with knowledge 博学的学者"],
                                            'abounding, abundant, awash, flush, fraught, lousy, swarming, teeming, thick, thronging',
                                            'depleted, drained, exhausted, deficient, incomplete, insufficient, short',
                                            'repletion n. 装满')]),
                              Word('repose', "",
                                   [TestWay('n',
                                            '(劳作后的)休息',
                                            'a state of resting after exertion or strain',
                                            ["The doctor ordered a period of repose for the patient suffering from insomnia. 医生要求正在饱受失眠折磨的病人好好休息一阵。"],
                                            'ease, leisure, relaxation',
                                            'exertion, labor, toil, work'),
                                    TestWay('n',
                                            '平静, 宁静',
                                            'a state of freedom from storm or disturbance',
                                            ["We enjoyed the repose of a summer evening on a remote island. 我们在遥远的小岛上共享了夏日傍晚的片刻安宁。"],
                                            'calmness, hush, peace, placidity, quietness, restfulness, serenity, still, tranquility',
                                            'commotion, pandemonium, tumult, turmoil, unrest, uproar'),
                                    TestWay('vi',
                                            '休息',
                                            'to take a rest',
                                            ["They have to repose on couches because all beds have been occupied. 因为所有的床都有人占了, 他们不得不在沙发上休息。"],
                                            'idle, loll, lounge, relax, rest',
                                            'drudge, hustle, moil, strive, struggle, sweat, travail'),
                                    TestWay('vt',
                                            '放置, 交给他人',
                                            'to put (something) into the possession or safekeeping of another',
                                            ["The Constitution reposes the power to declare war to Congress, and to that body alone. 宪法将宣战的权力交给了国会单独保管。"],
                                            'consign, delegate, deliver, entrust, leave, pass, transfer, transmit, vest, hand over, turn over, give over',
                                            'hold, keep, retain, withhold')])])

list21_unit5 = VocabularyList([Word('reprehend', "",
                                   [TestWay('vt',
                                            '谴责, 责难, 批评',
                                            "to express one's unfavorable opinion of the worth or quality of",
                                            ["Without exception, book reviewers reprehended the novel's trite plot. 毫无例外的, 小说缺乏新意的故事情节收到了评论家们的责难。"],
                                            'berate, blame, castigate, censure, condemn, denounce, dispraise, fault, knock, lambaste, pan, upbraid',
                                            'extol, laud, praise',
                                            'reprehensible adj. 应受谴责的')]),
                              Word('repress', "",
                                   [TestWay('vt',
                                            '镇压',
                                            'to put down by force, usually before total control has been lost; quell',
                                            ["Military quickly repressed the rebellion in the city and restored order. 军方迅速平息了市内的暴乱, 恢复了秩序。"],
                                            'crush, quash, quell, silence, squash, squelch, subdue, suppress',
                                            'foment, incite, instigate, provoke, stir'),
                                    TestWay('vt',
                                            '阻止(正常的表达、活动或发展等)',
                                            'to prevent the natural or normal expression, activity, or development of',
                                            ["You can't repress your feelings forever, so tell her that you love her. 你不可能永远压抑自己的感受, 所以大胆地跟她表白吧。"],
                                            'bridle, check, curb, muffle, smother, stifle, strangle, swallow',
                                            'express, loose, release, take out, unleash, vent',
                                            'repression n. 阻止, 镇压')]),
                              Word('reprieve', "",
                                   [TestWay('vt',
                                            '暂缓处刑, 免罪',
                                            'to postpone or cancel the punishment of',
                                            ["Fourteen people, waiting to be hanged for the murder of a former prime minister, have been reprieved 十四个因为谋杀前首相而等待绞刑的人获得了缓刑。"],
                                            'absolve, acquit, amnesty, condone, excuse, forgive, pardon, remit, respite, spare',
                                            'penalize, punish'),
                                    TestWay('vt',
                                            '维持运行',
                                            'to prevent (something) from being closed, destroyed, etc., for a period of time',
                                            ["The library has been reprieved and will remain open for at least another year. 图书馆的状况得到了缓解, 还将继续开放一年。"],
                                            'deliver, rescue, save')]),
                              Word('reproach', "",
                                   [TestWay('n',
                                            '令人羞愧的事物, 耻辱',
                                            'one that causes shame, rebuke or blame',
                                            ["a reproach to this entire school 整个学校的耻辱"],
                                            'dishonor, opprobrium, reflection, spot, scandal, stain, stigma, taint',
                                            'credit, honor'),
                                    TestWay('vt',
                                            '批评, 责备',
                                            'to express disapproval, criticism, or disappointment in (someone)',
                                            ["reproached by their mother for untidiness 因为邋遢而被他们的母亲批评"],
                                            'admonish, berate, castigate, chide, condemn, denounce, lambaste, rebuke, reprimand, reprove, upbraid',
                                            'commend, eulogize, extol, laud, praise',
                                            'irreproachable adj. 无可指责的')]),
                              Word('reprobate', "",
                                   [TestWay('n',
                                            '堕落者, 道德败坏的人',
                                            'a morally unprincipled person',
                                            ["The program rehabilitates reprobates and turns them into hard-working, law-abiding citizens. 这个项目让那些堕落的人改过自新, 并将他们变成勤劳守法的好公民。"],
                                            'brute, devil, fiend, miscreant, rapscallion, rascal, villain',
                                            'saint'),
                                    TestWay('adj',
                                            '堕落的, 放荡的',
                                            'morally corrupt',
                                            ["He is a reprobate judge who could be bribed, and often with astonishing ease. 他是一个堕落的法官, 极其容易就被贿赂了。"],
                                            'debased, debauched, degraded, depraved, dissipated, dissolute, libertine, perverse, perverted, rakish',
                                            'good, moral, righteous, virtuous, pure, uncorrupted'),
                                    TestWay('vt',
                                            '谴责, 痛斥',
                                            'to condemn strongly as unworthy, unacceptable, or evil',
                                            ["He reprobated his son's unconventional lifestyle. 他怒斥他儿子不遵循传统的生活习惯。"],
                                            'blame, criticize, censure, condemn, denounce, denunciate, reprehend',
                                            'commend, eulogize, extol, laud, praise'),
                                    TestWay('vt',
                                            '拒绝, 不提供',
                                            'to be unwilling to grant',
                                            ["The government will most likely reprobate the request for parole. 政府很有可能会拒绝假释的要求。"],
                                            'decline, disallow, disapprove, negative, nix, refuse, reject, reprobate, repudiate, withhold',
                                            'allow, concede, grant, let, permit, vouchsafe')]),
                              Word('reproof', "",
                                   [TestWay('n',
                                            '批评, 反对: ',
                                            'criticism for a fault, rebuke',
                                            ["The head teacher speaks in tones of gentle reproof. 校长的话语中带有隐晦的批评。"],
                                            'commination, condemnation, denunciation, excoriation, rebuke, reprimand, reproach, stricture',
                                            'commendation, eulogy, praise, endorsement')]),
                              Word('reprove', "",
                                   [TestWay('vt',
                                            '温和地责备, 警告',
                                            'to scold or correct usually gently or with kindly intent',
                                            ["My piano teacher often reproves me for slouching while playing, observing that good posture helps one play better. 我的钢琴老师常常会因为懒散的坐姿而批评我, 他认为良好的坐姿能让我弹得更好。"],
                                            'admonish, blame, chide, criticize, reprimand, reproach',
                                            'lambaste, commend, eulogize, extol, laud, praise'),
                                    TestWay('vt',
                                            '不欣赏, 不喜欢',
                                            'to hold an unfavorable opinion of',
                                            ["The older generation has always reproved the younger generation's taste in music. 老一代的人总是不喜欢新一代的音乐品味。"],
                                            'deprecate, discountenance, disesteem, disfavor, dislike, frown',
                                            'adore, approve, endorse, enjoy, favor, like')]),
                              Word('repudiate', "",
                                   [TestWay('vt',
                                            '否认',
                                            'to declare not to be true',
                                            ["She repudiated the charge that she had lied on her résumé. 她否认了她在简历中作假的指控"],
                                            'contradict, disaffirm, disavow, disclaim, disconfirm, disown, gainsay, negate, negative, refute, reject',
                                            'acknowledge, admit, allow, avow, concede, confirm'),
                                    TestWay('vt',
                                            '拒绝接受',
                                            'to show unwillingness to accept, do, engage in, or agree to',
                                            ["We didn't like the terms, so we repudiated the contract. 我们没有接受这份合同, 因为我们对其中的条款表示不满。"],
                                            'balk, deselect, disapprove, negative, nix, refuse, reprobate, spurn',
                                            'accept, agree, approve',
                                            'repudiation n. 拒绝, 否认')]),
                              Word('repugnant', "",
                                   [TestWay('adj',
                                            '令人厌恶的',
                                            'arousing disgust or aversion',
                                            ["The idea of moving again became repugnant to her. 又要搬家的想法让她感到厌恶。"],
                                            'abhorrent, abominable, awful, disgusting, distasteful, hideous, loathsome, noisome, obnoxious, repulsive',
                                            'innocuous, inoffensive, agreeable, delightful, enjoyable, gratifying, pleasing'),
                                    TestWay('adj',
                                            '不和谐的, 不协调的',
                                            'not being in agreement or harmony',
                                            ["Technically speaking, it may not be a violation, but it is certainly repugnant to the spirit of the law. 技术上来说这还算不上违法, 但是这肯定违背了法律的精神。"],
                                            'conflicting, discordant, incompatible, incongruous, inconsonant, inharmonious, mutually exclusive',
                                            'accordant, agreeing, compatible, concordant, conformable, congruent, congruous, consistent, consonant, harmonious',
                                            'repugnance n. 厌恶; 不一致')]),
                              Word('repulse', "",
                                   [TestWay('vt',
                                            '(使)厌恶, 排斥',
                                            'to rebuff or reject with rudeness, coldness, or denial',
                                            ["The scenes of violence in the film may repulse some viewers. 电影中某些暴力场景可能会使观众反感。"],
                                            'disgust, nauseate, repel, revolt, sicken',
                                            'allure, attract, bewitch, captivate, charm, enchant, entice, fascinate, lure, seduce, tempt',
                                            'repulsion n. 排斥')])])

list21_unit6 = VocabularyList([Word('repute', "",
                                   [TestWay('n',
                                            '(尤指好的)名声, 名誉',
                                            'a good reputation',
                                            ["Before his national bestseller, he was a writer of little repute. 在他的畅销书出来之前, 他是个没什么名声的作家。"],
                                            'celebrity, fame, name, renown, reputation',
                                            'infamy, notoriety',
                                            'reputable adj. 有好名声的')]),
                              Word('requite', "",
                                   [TestWay('vt',
                                            '酬谢, 报答',
                                            'to make repayment or return for',
                                            ["requited her love with hatred 恩将仇报"],
                                            'indemnify, reciprocate, recompense, recoup, reimburse, remunerate, repay'),
                                    TestWay('vt',
                                            '报仇',
                                            'to punish in kind the wrongdoer responsible for',
                                            ["The future writer would later requite the abuse he suffered at the hands of his classmates by creating scathing portraits of them in his novels. 未来的作家会把在同学那受的委屈的帐算清的——他会在小说中把他们描绘成恶人。"],
                                            'avenge, redress, retaliate, revenge',
                                            'absolve, condone, forgive, pardon')]),
                              Word('requisite', "",
                                   [TestWay('n',
                                            '必需品',
                                            'something necessary, indispensable, or unavoidable',
                                            ["Calculus is a requisite for modern physics. 微积分是学习近代物理的必要知识。"],
                                            'condition, demand, necessity, need, requirement'),
                                    TestWay('adj',
                                            '必不可少的, 必备的',
                                            'essential, necessary',
                                            ["Oxygen is requisite for human to survive. 氧气是维持人类生命的必要条件。"],
                                            'critical, compulsory, imperative, indispensable, mandatory, necessary, obligatory, required, vital',
                                            'needless, unnecessary, dispensable, optional')]),
                              Word('rescind', "",
                                   [TestWay('vt',
                                            '废除, 取消',
                                            'to make void',
                                            ["The government refused to rescind the order of curfew. 政府拒绝撤销宵禁的决定。"],
                                            'abolish, abrogate, annul, cancel, invalidate, negate, null, nullify, recall, repeal, revoke, void',
                                            'establish, enact, continue, keep')]),
                              Word('reserved', "",
                                   [TestWay('adj',
                                            '内向的, 缄默的',
                                            'restrained in words and actions',
                                            ["too reserved to offer a spontaneous criticism 过于缄默而不愿意发表真实的看法"],
                                            'closemouthed, constrained, laconic, reticent, restrained, silent, taciturn',
                                            'communicative, expansive, talkative, garrulous, loquacious',
                                            'unreserved adj. 无保留的, 外向的')]),
                              Word('residue', "",
                                   [TestWay('n',
                                            '剩余物',
                                            'something that remains after a part is taken, separated, or designated',
                                            ["In the race of nature, there is no residue left for the late. 在大自然的竞争中, 总是早起的鸟儿才有虫吃。"],
                                            'debris, remainder, remnant',
                                            other_form = 'residual adj. 剩余的')]),
                              Word('resign', "",
                                   [TestWay('vt',
                                            '辞职, 放弃(职位)',
                                            "to give up one's job or office",
                                            ["resigned her position at the university 自动放弃她在大学的职位"],
                                            'abnegate, cede, relinquish, renounce, surrender, step down',
                                            'assume, inaugurate, usurp')]),
                              Word('resilience', "",
                                   [TestWay('n',
                                            '弹力',
                                            'the property of a material that enables it to resume its original shape or position after being bent, stretched, or compressed',
                                            synonyms = 'elasticity, flexibility, malleability, pliability',
                                            other_form = 'inelasticity n. 无弹性'),
                                    TestWay('n',
                                            '恢复能力',
                                            'the ability to recover quickly from illness, change, or misfortune',
                                            ["Her mental resilience helped her promptly walk out of the shadow of her father’s death. 她的精神恢复能力让她迅速地走出了父亲去世的阴影当中。"],
                                            'adaptability',
                                            other_form = 'resilient adj. 有弹性的; 能迅速恢复的')]),
                              Word('resolute', "",
                                   [TestWay('adj',
                                            '坚定的',
                                            'marked by firm determination',
                                            ["We are glad to have such a resolute ally. 我们很高兴能拥有这样一个坚定的盟友"],
                                            'bound, decided, faithful, resolved, unwavering',
                                            'faltering, hesitant, indecisive, irresolute, jittery, vacillating, wavering',
                                            'resolution n. 坚定的决心')]),
                              Word('resonant', "",
                                   [TestWay('adj',
                                            '(声音)洪亮的, 共鸣的',
                                            'strong and deep in tone',
                                            ["A deep resonant voice rang out. 传来了洪亮的声音。"],
                                            'consonant, orotund, plangent, resounding, reverberant, sonorous, vibrant',
                                            'faint, low, muffled, muted, smothered, soft, weak',
                                            'resonance n. 洪亮')])])

list21_unit7 = VocabularyList([Word('resourceful', "",
                                   [TestWay('adj',
                                            '有创造力的, 机智的',
                                            'able to act effectively or imaginatively, especially in difficult situations',
                                            ["a resourceful man capable of dealing with difficult situations 一个能巧妙解决困局的能人"],
                                            'able, adroit, competent, talented',
                                            other_form = 'resourcefulness n. 能解决困难的能力')]),
                              Word('respite', "",
                                   [TestWay('n',
                                            '间歇, 休息',
                                            'an interval of rest or relief',
                                            ["to toil without respite 埋头苦干", "In the middle of each semester there came a short respite. 在每个学期的期中, 会有一个短暂的休假。"],
                                            'break, lull, intermission, recess, pause, rest',
                                            'resumption, exertion, labor, toil, work')]),
                              Word('respire', "",
                                   [TestWay('vi',
                                            '呼吸',
                                            'to inhale and exhale air successively',
                                            ["unable to respire due to heart attack 因心脏病发作而无法呼吸"],
                                            'breathe, inhale',
                                            'smother, stifle, suffocate',
                                            'respiration n. 呼吸')]),
                              Word('resplendent', "",
                                   [TestWay('adj',
                                            '华丽辉煌的',
                                            'shining brilliantly',
                                            ["Geography teacher showed us a picture of the resplendent aurora borealis. 地理老师给我们展示了一张壮丽的北极光的照片"],
                                            'brilliant, glorious, gorgeous, grand, magnificent, splendid, sublime, superb',
                                            'dim, dull, lackluster',
                                            'resplendence n. 辉煌')]),
                              Word('responsive', "",
                                   [TestWay('adj',
                                            '敏感的',
                                            'quick to respond or react appropriately or sympathetically',
                                            ["Children are often the most responsive members of the audience. 儿童通常是观众中最为敏感的群体"],
                                            'prompt, sensible, sensitive, susceptible',
                                            'dispassionate, detached, indifferent',
                                            'responsiveness n. 敏感')]),
                              Word('restive', "",
                                   [TestWay('adj',
                                            '急躁的, 忧虑的',
                                            'marked by impatience or uneasiness',
                                            ["I spent a restive night worrying about the next day's exam. 我度过了忧虑的一晚, 担心明天的考试。"],
                                            'restless, nervy, uneasy, uptight',
                                            'imperturbable, phlegmatic'),
                                    TestWay('adj',
                                            '难以管束的',
                                            'stubbornly resisting control',
                                            ["Tired soldiers grew restive. 疲惫的士兵变得越来越难以管理。"],
                                            'balky, contumacious, defiant, insubordinate, intractable, obstreperous, obstinate, perverse, recalcitrant, refractory',
                                            'amenable, biddable, compliant, conformable, docile, obedient, ruly, submissive, tractable',
                                            'restiveness n. 不安, 躁动')]),
                              Word('restless', "",
                                   [TestWay('adj',
                                            '不平静的',
                                            'marked by or causing a lack of quiet, repose, or rest',
                                            ["The patient felt restless from pain. 病人因疼痛而无法平静。"],
                                            'agitating, anxious, distressful, disturbing, fraught, restive, perturbed, uneasy, unquiet, unsettled',
                                            'halcyon, peaceful, serene, tranquil')]),
                              Word('restrain', "",
                                   [TestWay('vt',
                                            '限制, 控制',
                                            'to limit, restrict, or keep under control',
                                            ["The old lady restrained the child from picking the flowers. 老妇人不准孩子们采摘花朵。"],
                                            'bridle, check, constrain, curb, inhibit, measure, prevent, refrain, withhold',
                                            'discharge, release',
                                            'restrained adj. 受限制的')]),
                              Word('resurgence', "",
                                   [TestWay('n',
                                            '复兴',
                                            'a restoration to use, acceptance, activity, or vigor',
                                            ["Let’s witness the resurgence of classical school. 让我们见证古典乐派的复兴"],
                                            'reanimation, rebirth, regeneration, rejuvenation, renewal, resurrection, resuscitation, revitalization',
                                            'decay, degradation, deterioration, downfall, ebb, fall',
                                            'resurgent adj. 正在复兴的')]),
                              Word('resuscitate', "",
                                   [TestWay('vt',
                                            '使复活, 使苏醒',
                                            'to restore consciousness, vigor, or life to',
                                            ["resuscitated by the kiss of the prince 因王子的吻而苏醒"],
                                            'reanimate, recharge, refresh, rejuvenate, rekindle, renew, resurrect, revitalize, revive, revivify',
                                            'faint',
                                            'resuscitation n. 复活, 复兴; resuscitated adj. 复活的')])])

list21_unit8 = VocabularyList([Word('retainer', "",
                                   [TestWay('n',
                                            '家仆',
                                            'a person attached or owing service to a household',
                                            ["Knights are dressed for battle by their retainers. 骑士们在上战场之前是由他们的家仆帮助着装打扮的"],
                                            'menial, servant',
                                            'lord, master')]),
                              Word('retaliate', "",
                                   [TestWay('vt',
                                            '报复, 反击',
                                            'to pay back(as an injury)in kind',
                                            ["We swear to retaliate for our losses. 我们发誓要以牙还牙。"],
                                            'avenge, redress, requite, revenge',
                                            'absolve, condone, forgive, pardon',
                                            'retaliation n. 报复')]),
                              Word('retard', "",
                                   [TestWay('vt',
                                            '减速, 延迟',
                                            'to cause to move or proceed slowly; delay or impede',
                                            ["Language barriers retarded their negotiating progress. 语言障碍让谈判进程受阻。"],
                                            'bog, brake, decelerate, delay, detain, hamper, impede, mire, slacken',
                                            'accelerate, catalyze, expedite, hasten, precipitate')]),
                              Word('retinue', "",
                                   [TestWay('n',
                                            '随行人员',
                                            'a group of retainers or attendants',
                                            ["The premier inspected the factory with his retinue. 总理与随同人员一起视察了工厂。"],
                                            'associates, entourage, followers, posse, retainers',
                                            'leader')]),
                              Word('reticent', "",
                                   [TestWay('adj',
                                            '沉默不语的',
                                            'inclined to be silent or uncommunicative in speech',
                                            ["He was reticent about his plans. 他对他的计划三缄其口。"],
                                            'closemouthed, constrained, laconic, reserved, restrained, silent, taciturn',
                                            'communicative, expansive, talkative, garrulous, loquacious'),
                                    TestWay('adj',
                                            '不愿意的',
                                            'slow to begin or proceed with a course of action because of doubts or uncertainty',
                                            ["Understandably, she's reticent about becoming involved with another religious sect. 不难理解, 她不愿意被牵扯另一个宗教派别之中。"],
                                            'cagey, disinclined, dubious, indisposed, loath, reluctant',
                                            'willing, disposed, inclined, eager')]),
                              Word('retort', "",
                                   [TestWay('n',
                                            '(尤指机智的)回应, 回答',
                                            'something spoken or written in reaction especially to a question, especially a quick, witty, or cutting reply',
                                            ["She responded to the heckler with a scathing but hilarious retort that instantly won over the audience. 面对故意起哄捣乱的人, 她那严厉但不失幽默的回答立刻得到了观众的肯定。"],
                                            'comeback, rejoinder, repartee, reply, response, return, riposte',
                                            'inquiry, query, question')]),
                              Word('retouch', "",
                                   [TestWay('v',
                                            '润饰, 改进',
                                            'to improve or change (a photographic negative or print)',
                                            ["She was retouching her painting before the deadline. 在截止日期到来之前, 她一直在润色她的画作。"],
                                            'ameliorate, enhance, furbish, meliorate, perfect, polish, refine, upgrade',
                                            'deteriorate, downgrade, worsen')]),
                              Word('retract', "",
                                   [TestWay('vt',
                                            '收回, 否认',
                                            'to take back',
                                            ["The newspaper had to retract its allegations against the mayor. 报纸不得不收回针对市长的谣言。"],
                                            'abjure, abnegate, disavow, forswear, recall, recant, renounce, repeal, repudiate, withdraw',
                                            'tender, adhere, stick',
                                            'retractable adj. 可收回的')]),
                              Word('retrench', "",
                                   [TestWay('vi',
                                            '削减开支',
                                            'to curtail expenses',
                                            ["Declining business forced the company to retrench. 衰减的业务迫使公司削减开支。"],
                                            'economize, reduce, cut down',
                                            'enlarge, expand',
                                            'retrenchment n. 削减开销')]),
                              Word('retribution', "",
                                   [TestWay('n',
                                            '报偿, 报应',
                                            'the dispensing or receiving of reward or punishment especially in the hereafter',
                                            ["The neighborhood is being torn apart by an endless cycle of gang violence and retribution. 这个社区正在被帮派间斗争和仇恨的恶性循环割裂。"],
                                            'avengement, payback, recompense, reparation, repayment, requital, retaliation, revenge, vengeance',
                                            'retributive n. 报应的')])])

list21_unit9 = VocabularyList([Word('retrograde', "",
                                   [TestWay('adj',
                                            '倒退的',
                                            'moving or tending backward',
                                            ["This is a retrograde step and you will regret it. 这是后退的一步, 你以后肯定会后悔的。"],
                                            'backward, receding, regressive, reversed, withdrawing',
                                            'progressive'),
                                    TestWay('v',
                                            '退步, 退化',
                                            'to decline to a worse condition',
                                            ["The Dark Ages is the period following the fall of the Roman Empire when Western civilization seriously retrograded. “黑暗时代”指的是罗马帝国崩溃之后, 西方文明严重退步的一个历史时期。"],
                                            'atrophy, crumble, decay, decline, degenerate, descend, deteriorate, ebb, regress, rot, sink, worsen',
                                            'ameliorate, improve, meliorate')]),
                              Word('retrospective', "",
                                   [TestWay('adj',
                                            '回顾的',
                                            'looking back on, contemplating, or directed to the past',
                                            ["a retrospective glance at my youth 朝我少年时代投去的回顾性一瞥"],
                                            'backward',
                                            'anticipatory, prospective')]),
                              Word('revelry', "",
                                   [TestWay('n',
                                            '狂欢, 喧闹的作乐',
                                            'noisy partying or merrymaking',
                                            ["They were exhausted after the night of revelry. 一夜狂欢后大家都筋疲力尽"],
                                            'conviviality, festivity, gaiety, jollity, merriment, rejoicing, revel, whoopee',
                                            'gloom, grief, melancholy, misery, mournfulness, sorrow, woe')]),
                              Word('revenge', "",
                                   [TestWay('n',
                                            '报复, 复仇',
                                            'an act or instance of retaliating in order to get even',
                                            ["Both sides were determined to get revenge for losses and showed little interest in ending the feud. 双方都下定决心要为失去的东西报仇, 对于结束他们之间的世仇毫无兴趣。", "The bombing was in revenge for the assassination of their leader. 此次轰炸是对暗杀他们领袖的报复行动。"],
                                            'avengement, payback, reprisal, requital, retaliation, retribution, vengeance',
                                            'forgiveness, pardon'),
                                    TestWay('vt',
                                            '复仇',
                                            'to avenge (as oneself) usually by retaliating in kind or degree',
                                            ["He finally revenged the death of his brother. 他终于为兄弟的死报了仇。"],
                                            'avenge, redress, requite, retaliate',
                                            'absolve, condone, forgive, pardon')]),
                              Word('revere', "",
                                   [TestWay('vt',
                                            '(尤指对神的)尊崇, 尊敬',
                                            'to offer honor or respect to (someone) as a divine power',
                                            ["He is revered for his valor. 他因为他的英勇而受到尊敬。‖ In some cultures people revere their ancestors, even leaving food offerings for them. 在一些文化当中, 人们非常敬重先人, 甚至将一些食物留下来供他们享用。"],
                                            'adore, deify, glorify, esteem, regard, respect, venerate, worship',
                                            'blaspheme, desecrate, profane, violate',
                                            'reverence n. 尊重; reverent adj. 恭敬地, 虔诚的')]),
                              Word('revise', "",
                                   [TestWay('vt',
                                            '更改, 修正',
                                            'to look over again in order to correct or improve',
                                            ["There are many problems involved in revising a dictionary. 修正字典会牵涉到诸多问题。‖With the snow, we'll need to revise our travel plans. 因为下雪了, 我们不得不更改旅游计划。"],
                                            'amend, correct, emend, polish, redraft, refine, rework, upgrade',
                                            'discard',
                                            'revision n. 修改')]),
                              Word('revive', "",
                                   [TestWay('vi',
                                            '恢复意识',
                                            'to return to consciousness or life, become flourishing again',
                                            ["successfully revived him with artificial respiration 用人工呼吸使成功他恢复意识"],
                                            'come around',
                                            'faint, black ou'),
                                    TestWay('v',
                                            '再获新生',
                                            'become active or flourishing again',
                                            ["Around midnight, I usually need to revive myself with a cup of strong coffee. 在午夜时分, 我需要一杯浓咖啡来提神。", "The success of the movie has revived her career. 这部电影的成功让他的事业焕发第二春。"],
                                            'reanimate, recharge, refresh, rejuvenate, rekindle, renew, resurrect, resuscitate, revitalize, revivify',
                                            'degenerate, deteriorate, worsen',
                                            'revival n. 复苏')]),
                              Word('revoke', "",
                                   [TestWay('vt',
                                            '撤回, 宣告无效',
                                            'to annul by recalling or taking back',
                                            ["to revoke a will 废除遗嘱"],
                                            'abolish, abrogate, annul, cancel, invalidate, negate, null, nullify, recall, repeal, revoke, void',
                                            'establish, enact, continue, keep',
                                            'revocation n. 撤销, 废除')]),
                              Word('revolt', "",
                                   [TestWay('vt',
                                            '使厌恶, 反感',
                                            'to fill with disgust or abhorrence',
                                            ["The smell of seafood revolts him. 他对海鲜的腥味十分反感。"],
                                            'disgust, nauseate, repel, repulse, sicken',
                                            'allure, attract, bewitch, captivate, charm, enchant, entice, fascinate, lure, seduce, tempt'),
                                    TestWay('vi',
                                            '反叛',
                                            'to renounce allegiance or subjection (as to a government)',
                                            ["The revolted against the dictator by burning his palace. 他们通过焚烧宫殿来对抗独裁者。"],
                                            'defy, insurrect, mutiny, oppose, rebel, resist',
                                            'obey, submit',
                                            'revolter n. 反叛者')]),
                              Word('ribald', "",
                                   [TestWay('adj',
                                            '举止、言语下流粗俗的',
                                            'characterized by or indulging in vulgar, lewd humor',
                                            ["entertained the guests with ribald jokes 用荤段子来取悦客人"],
                                            'bawdy, blue, coarse, crude, dirty, filthy, gross, indecent, nasty, obscene, pornographic, profane, vulgar',
                                            'decent, proper, seemly')])])

list21_unit10 = VocabularyList([Word('rickety', "",
                                   [TestWay('adj',
                                            '不稳的',
                                            'lacking stability or firmness',
                                            ["The rickety coalition may break at any moment. 脆弱的联盟随时都可能破裂。"],
                                            'insecure, precarious, shaky, unsound, unsteady, weak',
                                            '')]),
                              Word('rider', "",
                                   [TestWay('n',
                                            '骑马的人',
                                            'one that rides',
                                            synonyms = 'horseman, knight',
                                            antonyms = 'pedestrian, walker'),
                                    TestWay('n',
                                            '附件',
                                            'a clause appended to a legislative bill to secure a usually distinct object',
                                            synonyms = 'addendum, appendix, attachment, supplement')]),
                              Word('ridicule', "",
                                   [TestWay('vt',
                                            '嘲笑',
                                            'to make fun of',
                                            ["always ridiculed everything she said 总是嘲笑她说的话", "The term “big bang theory” was originally coined to ridicule the belief that the universe was created by a giant explosion. “大爆炸理论”期初是为了嘲笑一种观点而创造的, 这种观点认为宇宙源自一场巨大的爆炸。"],
                                            'deride, gibe, jape, jeer, lout, mock, taunt',
                                            'commend, praise',
                                            'ridiculous adj. 荒谬的')]),
                              Word('rife', "",
                                   [TestWay('adj',
                                            '丰富的, 普遍的',
                                            'possessing or covered with great numbers or amounts of something specified',
                                            ["a video game rife with violence and abuse 充满暴力与虐待的电子游戏"],
                                            'abounding, abundant, awash, flush, fraught, lousy, replete, swarming, teeming, thick, thronging',
                                            'deficient, incomplete, insufficient, short')]),
                              Word('rift', "",
                                   [TestWay('n',
                                            '离间',
                                            'a break in friendly relations',
                                            ["a rift between two once allied nations 两个往昔盟国的决裂"],
                                            'crack, fissure, fracture, schism',
                                            'reconciliation, rapprochement'),
                                    TestWay('vt',
                                            '使开裂',
                                            'to cause to split open or break',
                                            ["Hills were rifted by the earthquake. 地震使得山崩地裂"],
                                            'cleave, divide, rip, split, sunder, tear',
                                            'associate, coalesce, combine, conjugate, join, link')]),
                              Word('rile', "",
                                   [TestWay('vt',
                                            '刺激, 惹怒',
                                            'to make agitated and angry',
                                            ["The new work schedules riled the employees. 新的工作时间表激怒了员工"],
                                            'aggravate, annoy, enrage, exasperate, grate, inflame, infuriate, irritate, nettle, peeve, pique, provoke, roil',
                                            'allay, alleviate, assuage, ease, mitigate, mollify, palliate, relieve, soothe')]),
                              Word('ripen', "",
                                   [TestWay('v',
                                            '使成熟, 成熟',
                                            'to make or become ripe or riper',
                                            ["Age ripens a good wine. 时间酿出好酒"],
                                            'age, develop, grow, mature',
                                            'fade, flag, shrivel, wane, wilt, wither',
                                            'ripened adj. (酒、果实等)成熟的')]),
                              Word('riot', "",
                                   [TestWay('n',
                                            '喧闹, 暴乱',
                                            'public violence, tumult, or disorder',
                                            ["Special police units equipped with riot shields quickly arrived at the airport. 装备有防暴盾牌的特警们迅速抵达了飞机场。"],
                                            'clamor, commotion, disorder, ferment, tumult, turmoil, upheaval, uproar',
                                            'serenity, tranquility, order')]),
                              Word('rite', "",
                                   [TestWay('n',
                                            '惯例, 仪式',
                                            'a prescribed form or manner governing the words or actions for a ceremony',
                                            ["the marriage rites 婚礼仪式的章程"],
                                            'ceremony, form, observance, protocol, ritual, solemnity',
                                            'ritual n. 仪式')]),
                              Word('rive', "",
                                   [TestWay('vt',
                                            '撕开',
                                            'to wrench open or tear apart or to pieces',
                                            ["Lightning rived the tree. 闪电把树劈裂了"],
                                            'cleave, lacerate, render, ribbon, rip, rupture, shred, split, tatter, tear',
                                            'associate, coalesce, combine, conjoin, conjugate, connect, fuse, interfuse, join, link, unify',
                                            'riven adj. 被撕开的')])])

LIST21 = VocabularyList(list21_unit1.words+list21_unit2.words+list21_unit3.words+list21_unit4.words+list21_unit5.words+list21_unit6.words+list21_unit7.words+list21_unit8.words+list21_unit9.words+list21_unit10.words)
