#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list25_unit1 = VocabularyList([Word('sunder', "",
                                   [TestWay('vt',
                                            '分裂, 分离',
                                            'to break apart or in two',
                                            ["a city sundered by racial conflict 一个因种族冲突而分裂的城市"],
                                            'disassociate, disconnect, disjoin, disunite, divide, part, rend, rive, separate, sever, unyoke',
                                            'bond, connect, join, link, unify, unite, yoke',
                                            'asunder adv. 分开地, 分裂地')]),
                              Word('supercilious', "",
                                   [TestWay('adj',
                                            '高傲的, 傲慢的',
                                            'feeling or showing haughty disdain',
                                            ["The aristocrat reacted to their breach of etiquette with a supercilious smile. 贵族对破坏他们破坏礼节的行为报以傲慢的一笑。"],
                                            'arrogant, assumptive, bumptious, haughty, imperious, pompous, presumptuous, overbearing, superior',
                                            'humble, moderate, modest')]),
                              Word('superficial', "",
                                   [TestWay('adj',
                                            '表面的, 肤浅的',
                                            'lacking in depth, solidity, and comprehensiveness',
                                            ["The official’s superficial report on the situation provoked wide blame on the Internet. 官员对于情况敷衍般的描述激起了网络上的广泛谴责。"],
                                            'cursory, facile, perfunctory, shallow, sketchy, skin-deep',
                                            'profound 深刻的; comprehensive, exhaustive',
                                            'superficiality n. 表面现象')]),
                              Word('superfluous', "",
                                   [TestWay('adj',
                                            '多余的, 过剩的',
                                            'exceeding what is sufficient or necessary',
                                            ["a complicated algorithm that could filter all superfluous information 一个能滤除所有的多余信息的复杂算法"],
                                            'excessive, extra, redundant, surplus',
                                            'deficient, inadequate, insufficient, scanty, scarce, short, skimpy, sparse',
                                            'superfluity n. 多余, 过剩')]),
                              Word('superimpose', "",
                                   [TestWay('v',
                                            '添声加色, 使形象、某因素或性质更加清楚',
                                            'to add as a distinct feature, element, or quality',
                                            ["superimposed her own interpretation when she retold the story 她重复故事的时候, 加入了自己的解释"])]),
                              Word('supine', "",
                                   [TestWay('adj',
                                            '懒散的, 懒得动的、倦怠的、消极的或漠不关心的',
                                            'showing lethargy, passivity, or blameworthy indifference',
                                            ["a supine legislature that is afraid to take action 害怕采取行动的不作为的立法机关"],
                                            'inert, passive, dormant, torpid',
                                            'vigilant')]),
                              Word('supple', "",
                                   [TestWay('adj',
                                            '易弯曲的, 柔软的',
                                            'readily bent; pliant',
                                            ["supple limbs 柔软的四肢", "a supple mind 灵活的头脑"],
                                            'bendy, flexible, limber, lissome, lithe, pliable, pliant, lithesome',
                                            'inflexible, stiff, rigid',
                                            'suppleness n.柔软')]),
                              Word('supplant', "",
                                   [TestWay('vt',
                                            '排挤, 篡夺…的位置',
                                            'to usurp the place of, especially through intrigue or underhanded tactics',
                                            ["Old traditions were fading away and being supplanted by modern ways. 老传统逐渐式微, 被现代方式取代。"],
                                            'displace, displant, substitute, supersede, cut out')]),
                              Word('supplement', "",
                                   [TestWay('n./v',
                                            '增补, 补充',
                                            'something that serves to complete or make up for a deficiency in something else',
                                            ["recommends taking a vitamin C supplement to prevent colds 建议补充维生素C来预防感冒"],
                                            'addendum, addition, expansion, increment, proliferation, step-up')]),
                              Word('supplicate', "",
                                   [TestWay('v',
                                            '恳求, 乞求',
                                            'to make a request to (someone) in an earnest or urgent manner',
                                            ["God is not just someone to be supplicated in times of trouble. 我们不应该只在困难时候才向主祷告。"],
                                            'beseech, conjure, entreat, impetrate, implore, solicit, plead to, appeal to',
                                            'demand')])])

list25_unit2 = VocabularyList([Word('supposition', "",
                                   [TestWay('n',
                                            '猜想, 推测',
                                            'an opinion or judgment based on little or no evidence',
                                            ["It's pure supposition on your part that there's something illegal going on next door. 你说隔壁在进行非法勾当纯属猜测。"],
                                            'hypothesis, proposition, surmise,premise, presumption',
                                            'certainty')]),
                              Word('suppress', "",
                                   [TestWay('vt',
                                            '抑制(表情)',
                                            'to inhibit the expression of (an impulse, for example); check',
                                            ["suppress a smile 忍住笑容"],
                                            'repress, smother, stifle, choke back, hold back',
                                            'stimulate'),
                                    TestWay('v',
                                            '用暴力终止, 镇压',
                                            'to put a stop to (something) by the use of force',
                                            ["Nothing could suppress the rising tide of protest. 暴力也难以控制越来越激烈的游行示威活动。"],
                                            'clamp down on, crack down on, put down, quash, repress, silence, slap down, snuff out, squash, squelch, subdue')]),
                              Word('surcharge', "",
                                   [TestWay('v./n',
                                            '过高收费',
                                            'to charge (someone) too much for goods or services',
                                            ["The airline has added a $30 fuel surcharge on all international flights. 该航空公司对所有国际航线上涨了30美元的燃油税。"],
                                            'gouge, soak, sting')]),
                              Word('surfeit', "",
                                   [TestWay('v./n',
                                            '过量, 饮食过度',
                                            'to feed or supply to excess',
                                            ["He surfeited himself with chocolate. 他巧克力吃多了"],
                                            'overabundance, overage, overflow, plethora, redundancy, superfluity, surplus',
                                            'deficiency, deprivation, insufficient supply, famish, starve')]),
                              Word('surrender', "",
                                   [TestWay('vt',
                                            '交出, 放弃, 投降',
                                            'o give (something) over to the control or possession of another usually under duress',
                                            ["surrender a contractual right 放弃契约上规定的一项权利"],
                                            'abnegate, cede, relinquish, renounce, resign',
                                            'appropriate'),
                                    TestWay('v',
                                            '沉溺于',
                                            'to give (oneself) over to something especially unrestrainedly',
                                            ["surrendered himself to grief 沉湎于悲伤"],
                                            'deliver, give up, indulge, yield')]),
                              Word('surreptitious', "",
                                   [TestWay('adj',
                                            '偷偷摸摸的, 保密的',
                                            'undertaken or done so as to escape being observed or known by others',
                                            ["took a surreptitious glance at her knees 偷偷瞟了一下她的膝盖"],
                                            'backstairs, clandestine, covert, furtive, privy, underground, underhanded, behind-the-scenes',
                                            'barefaced, aboveboard, open, overt, public')]),
                              Word('susceptibility', "",
                                   [TestWay('n',
                                            '易受感染的性质或状态',
                                            'the quality or state of having little resistance to some outside agent',
                                            ["A weak immune system causes increased susceptibility to disease. 弱的免疫系统会增大患病的概率。"],
                                            'defenselessness, vulnerability, weakness',
                                            'immunity, invulnerability')]),
                              Word('suspend', "",
                                   [TestWay('vi',
                                            '暂停, 中止',
                                            'to bring to a formal close for a period of time',
                                            ["suspended the trial 暂停审判"],
                                            'prorogue, recess',
                                            'invoke'),
                                    TestWay('vt',
                                            '悬挂',
                                            'hang',
                                            ["suspended a banner proclaiming the town's “Heritage Days” from the archway 在拱门上方悬挂了一条庆祝“遗产日”的条幅"],
                                            antonyms = 'erect, let fall')]),
                              Word('suture', "",
                                   [TestWay('n./v.',
                                            '缝合',
                                            'the process of joining two surfaces or edges together along a line by or as if by sewing',
                                            ["The doctor cleaned, sutured, and bandaged the wound. 医生将伤口清洗、缝合、包扎。"],
                                            antonyms = 'incision, avulse')]),
                              Word('svelte', "",
                                   [TestWay('adj',
                                            '(女人)体态苗条的, 优雅的',
                                            'slender or graceful in figure or outline; slim',
                                            ["The svelte dancer seemed to float across the stage. 苗条的舞者看起来就像在舞台上漂浮。"],
                                            'bony, lean, skinny, slender, slim',
                                            'plump, corpulent, paunchy and awkward')])])

list25_unit3 = VocabularyList([Word('swagger', "",
                                   [TestWay('vi',
                                            '大摇大摆地走, 趾高气昂地走',
                                            'to conduct oneself in an arrogant or superciliously pompous manner',
                                            ["The young man confidently swaggered across the room. 年轻人高傲地在房间里走来走去。"],
                                            'prance, sashay, stalk'),
                                    TestWay('v',
                                            '自夸, 吹嘘',
                                            'boast, brag',
                                            ["I would swagger if I'd won first place in the bowling tournament. 如果我赢了保龄球锦标赛我肯定会自夸。"],
                                            'brag, vapor, vaunt, gasconade')]),
                              Word('swear', "",
                                   [TestWay('vi',
                                            '咒骂',
                                            'to use profane or obscene language: curse',
                                            ["no one is allowed to swear in this house 这个房间里禁止说脏话"],
                                            'blaspheme, curse, cuss',
                                            'accolade'),
                                    TestWay('v',
                                            '宣誓',
                                            'to promise or pledge with a solemn oath; vow',
                                            ["He swore his oath of allegiance to the queen. 他宣誓效忠女王"],
                                            'attest, depose, covenant, pledge, vow')]),
                              Word('sweltering', "",
                                   [TestWay('adj',
                                            '酷热的',
                                            'oppressively hot',
                                            ["The air conditioning was broken, and it was sweltering in the room. 空调坏了, 房间里酷热难耐。"],
                                            'boiling, scorching, searing, sultry, torrid, fiery',
                                            'algid, arctic, bone-chilling, freezing, frigid, frozen, glacial, ice-cold, iced, icy')]),
                              Word('swerve', "",
                                   [TestWay('vi',
                                            '突然改变方向',
                                            'to turn aside abruptly from a straight line or course',
                                            ["The car swerved sharply to avoid the squirrel in the road. 为了避开路中的松鼠, 汽车猛地转向。"],
                                            'detour, deviate, diverge, sheer, swing, veer',
                                            'maintain direction, straighten')]),
                              Word('swill', "",
                                   [TestWay('vt',
                                            '痛饮, 大口地吃',
                                            'to drink greedily, to eat greedily or to excess',
                                            ["Considering the way she swills carbonated drinks, she ought to own stock in Pepsi company. 鉴于她对碳酸饮料消费的贡献, 百事公司应该给她分点股份。"],
                                            'gulp, quaff, swig',
                                            'sip')]),
                              Word('swindle', "",
                                   [TestWay('vt',
                                            '欺骗, 骗取',
                                            'to cheat or defraud of money or property',
                                            ["Hundreds of people were swindled out of their savings 几百人都被骗去了存款。"],
                                            'bilk, con, hustle, fiddle, gyp, bunco, flimflam')]),
                              Word('sybarite', "",
                                   [TestWay('n',
                                            '沉于奢侈逸乐者, 酒色之徒',
                                            'a person devoted to pleasure and luxury; a voluptuary',
                                            ["The prince was remembered as a self-indulgent sybarite. 王子酒色之徒的名声远扬。"],
                                            'debauchee, decadent, hedonist, sensualist',
                                            'spartan, ascetic')]),
                              Word('sycophant', "",
                                   [TestWay('n',
                                            '马屁精',
                                            'a servile self-seeking flatterer',
                                            ["When her career was riding high, the self-deluded actress often mistook sycophants for true friends. 当她的事业如日中天之时, 该演员总是把一些马屁精误以为是真朋友。"],
                                            'fawner, flunky , lickspittle, toady, apple-polisher, bootlicker, brownnoser')]),
                              Word('syllabus', "",
                                   [TestWay('n',
                                            '提纲, 摘要: 课文、演讲或研究课题的要点的概要或提纲',
                                            'an outline or a summary of the main points of a text, lecture, or course of study',
                                            ["Have you got next year’s syllabus? 你拿到明年的教学大纲了吗？"])]),
                              Word('syllogism', "",
                                   [TestWay('',
                                            '由一般到个别的推理; 演绎',
                                            'reasoning from the general to the specific; deduction',
                                            ["The syllogism was at the core of traditional deductive reasoning, where facts are determined by combining existing statements, in contrast to inductive reasoning where facts are determined by repeated observations. 从一般到个别的推理是传统演绎推理的核心由结合现存状态所确定, 而归纳推理则由重复观测来确认。"],
                                            'syllogize v. 用三段论论证')])])

list25_unit4 = VocabularyList([Word('symbiosis', "",
                                   [TestWay('n',
                                            '共生关系',
                                            'the living together in more or less intimate association or close union of two dissimilar',
                                            ["The bird lives in symbiosis with the hippopotamus. 这种鸟和河马是共生关系。"],
                                            antonyms = 'unrelated growth')]),
                              Word('symmetry', "",
                                   [TestWay('n',
                                            '对称',
                                            'balanced proportions',
                                            ["The building has perfect symmetry. 这栋房子是完美的对称构造。"],
                                            'balance, coherence, consonance, proportion',
                                            'disproportion, asymmetry, discordance, disproportion, disunity, imbalance, incoherence, violence 不均衡, 混乱')]),
                              Word('synchronous', "",
                                   [TestWay('adj',
                                            '同时期的, 同相的',
                                            'having identical period and phase',
                                            ["The synchronous arrival of a baby sister and loss of a beloved grandmother strongly affected the girl. 妹妹的出生和奶奶的去世同时发生, 给小姑娘造成了巨大的影响"],
                                            'coetaneous, coeval, coexistent, concurrent, contemporaneous, simultaneous',
                                            'occurring at different times, noncontemporaneous, out-of-phase')]),
                              Word('synergic', "",
                                   [TestWay('adj',
                                            '合作的',
                                            'working together: cooperating',
                                            ["synergic muscles 协同肌肉"],
                                            antonyms = 'antagonistic')]),
                              Word('synonymous', "",
                                   [TestWay('adj',
                                            '同义的',
                                            'having the same or a similar meaning',
                                            ["Paris has always been synonymous with elegance, luxury and style. 巴黎在人们心中就是优雅、奢侈、时尚的同义词。"])]),
                              Word('synopsis', "",
                                   [TestWay('n',
                                            '摘要, 概要',
                                            'a brief outline or general view; an abstract or a summary.',
                                            ["Just give me a synopsis of the movie. 把电影的大致情节给我说说就行。"],
                                            'abstract, brief, digest, recapitulation, roundup, summarization, epitome')]),
                              Word('synthesis', "",
                                   [TestWay('n',
                                            '合成, 综合',
                                            'the combination of parts or elements so as to form a whole',
                                            ["a philosophy that is a kind of synthesis of several schools of Western and Eastern thought 哲学史东西方很多流派思想的综合"],
                                            'admixture, alloy, amalgamation, compound, conflation, fusion, meld',
                                            'analysis, take apart')]),
                              Word('tacit', "",
                                   [TestWay('adj',
                                            '暗示的',
                                            'implied or indicated (as by an act or by silence) but not actually expressed',
                                            ["tacit consent 默许"],
                                            'implied, unexpressed, unspoken, unvoiced, wordless',
                                            'explicit, express, expressed, spoken, stated, voiced')]),
                              Word('taciturn', "",
                                   [TestWay('adj',
                                            '沉默寡言的, 话少的',
                                            'temperamentally disinclined to talk',
                                            ["A taciturn man never initiates a conversation. 一个寡言的男人从不主动和人说话。"],
                                            'laconic, reserved, reticent, tight-lipped, uncommunicative',
                                            'garrulous, loquacious, glib, expansive, prolix, voluble')]),
                              Word('tackle', "",
                                   [TestWay('v',
                                            '着手处理',
                                            'to start work on energetically',
                                            ["Once I clean the kitchen, I think I'll tackle the bathroom. 等我把厨房收拾干净了, 就去收拾浴室。"],
                                            'dive into, wade in')])])

list25_unit5 = VocabularyList([Word('tact', "",
                                   [TestWay('n',
                                            '机敏, 精明, 不冒犯',
                                            'a keen sense of what to do or say in order to maintain good relations with others or avoid offense',
                                            ["She talked to her neighbor with supreme tact. 她和邻居说话语调十分圆滑。"],
                                            'diplomacy',
                                            'clumsiness, insensitivity, tactlessness')]),
                              Word('tactile', "",
                                   [TestWay('adj',
                                            '有触觉的, 能触知的',
                                            'perceptible by touch: tangible',
                                            ["The thick brushstrokes give the painting a tactile quality. 粘稠的笔触给了这幅画一种厚实的感觉。"])]),
                              Word('tactless', "",
                                   [TestWay('adj',
                                            '不机智的, 笨拙的',
                                            'bluntly inconsiderate or indiscreet',
                                            ["tactless comments 不明智的评论"],
                                            'graceless, ill-advised, imprudent, indelicate, injudicious, undiplomatic',
                                            'advisable, discreet, judicious, prudent, tactful, wise')]),
                              Word('talisman', "",
                                   [TestWay('n',
                                            '护身符',
                                            'something worn or kept to bring good luck or keep away evil',
                                            ["A pendant of white nephrite jade is often worn by Indians as a talisman to ward off heart disease. 印度人通常戴一串软玉项链防止心脏病发作。"],
                                            'amulet, fetish, mascot, mojo, periapt, phylactery')]),
                              Word('taint', "",
                                   [TestWay('vt',
                                            '(品质)污损',
                                            'to affect slightly with something morally bad or undesirable',
                                            ["A tendency toward conceitedness taints that athlete's status as a role model. 该运动员自负的倾向玷污了其行为模范的地位"],
                                            'blemish, darken, mar, spoil, tarnish, vitiate',
                                            'tainted 污损的 【反】pristine, unspoiled, wholesome, unadulterated 纯洁的, 健全的')]),
                              Word('tamper', "",
                                   [TestWay('vi',
                                            '恶意窜改, 损害',
                                            'to handle thoughtlessly, ignorantly, or mischievously',
                                            ["tamper with tradition 坏了规矩"],
                                            'diddle with, fiddle with, fool with, mess with'),
                                    TestWay('v',
                                            '玩弄',
                                            'to tinker with rashly or foolishly',
                                            ["Don't tamper with my feelings. 不要玩弄我的感情。"])]),
                              Word('tangent', "",
                                   [TestWay('n./adj',
                                            '离题(的), 不相关(的)',
                                            'diverging from an original purpose of course: irrelevant',
                                            ["tangent remarks 不相关的评论"],
                                            'excursive, digressive',
                                            'essential')]),
                              Word('tangible', "",
                                   [TestWay('adj',
                                            '可感知的',
                                            'capable of being perceived',
                                            synonyms = 'palpable, touchable',
                                            antonyms = 'impalpable, intangible, unable to perceive'),
                                    TestWay('adj',
                                            '确凿的, 真实的',
                                            'possible to be treated as fact; real or concrete',
                                            ["tangible evidence 确凿的证据"])]),
                              Word('tangy', "",
                                   [TestWay('adj',
                                            '刺激的',
                                            'having a powerfully stimulating odor or flavor',
                                            ["a tangy sauce with a strong aftertaste 味道很刺激的酱料, 回味无穷"],
                                            'pungent, strong',
                                            'bland, mild, smooth')]),
                              Word('tantalize', "",
                                   [TestWay('vt',
                                            '激起, 挑逗',
                                            'to excite (another) by exposing something desirable while keeping it out of reach',
                                            ["He was tantalized by the possibility of earning a lot of money quickly. 有人用迅速致富挑逗他。"],
                                            antonyms = 'comfort, console, solace, alleviate, assuage, relieve, satiate')])])

list25_unit6 = VocabularyList([Word('tantamount', "",
                                   [TestWay('adj',
                                            '等价的, 与…相等的',
                                            'equivalent in value, significance, or effect',
                                            ["a relationship tantamount to marriage 到了谈婚论嫁地步的关系"],
                                            antonyms = 'incommensurate')]),
                              Word('tantrum', "",
                                   [TestWay('n',
                                            '勃然大怒, 发脾气',
                                            'a fit of bad temper',
                                            ["had a tantrum 大发脾气"],
                                            'blowup, explosion, fit',
                                            'pacification')]),
                              Word('taper', "",
                                   [TestWay('vt',
                                            '(使)逐渐变细',
                                            'to become gradually narrower or thinner toward one end',
                                            ["taper to a point 逐渐变成为一点"],
                                            'abate, decline, diminish, dwindle, shrink, wane, drain away'),
                                    TestWay('v',
                                            '逐渐减少, 减弱',
                                            'to diminish or lessen gradually',
                                            ["The storm finally tapered off. 风暴逐渐平静了。"],
                                            synonyms = 'subside, die down, phase down, fall away, let up')]),
                              Word('tardy', "",
                                   [TestWay('adj',
                                            '缓慢的, 迟缓的',
                                            'moving slowly: sluggish',
                                            ["He was tardy to work. 他做事拖拖拉拉。"],
                                            'crawling, creeping, dallying, dawdling, dilatory, dragging, lagging, languid, sluggish',
                                            'bolting, brisk, fleet, flying, meteoric, rocketing, scooting, scudding, scurrying, swift, whirling'),
                                    TestWay('adj',
                                            '延后的, 迟的',
                                            'delayed beyond the expected or proper time',
                                            ["a tardy arrival 迟到"],
                                            'behind, belated, delinquent, overdue',
                                            'early, inopportune, precocious, premature, unseasonable, untimely')]),
                              Word('tarnish', "",
                                   [TestWay('vt',
                                            '玷污',
                                            'to affect slightly with something morally bad or undesirable',
                                            ["an arrest for shoplifting tarnished her reputation 因在商店行窃被捕玷污了她的声望"],
                                            'blemish, mar, stain, vitiate')]),
                              Word('tasty', "",
                                   [TestWay('adj',
                                            '美味的, 令人愉悦的',
                                            'giving pleasure or contentment to the mind or senses',
                                            ["the tasty prospect of getting his revenge 报仇成功的诱人前景"],
                                            'agreeable, delectable, delightful, satisfying, savory',
                                            'uninteresting, disagreeable, unpalatable, unpleasant, unwelcome')]),
                              Word('tatty', "",
                                   [TestWay('adj',
                                            '破旧的, 褴褛的',
                                            'somewhat worn, shabby, or dilapidated',
                                            ["a tatty shirt 破旧的衬衣"],
                                            'dilapidated, scruffy, seedy, sleazy, tatterdemalion, tatty, threadbare',
                                            'smart')]),
                              Word('taunt', "",
                                   [TestWay('vt',
                                            '嘲弄性质疑, 挑衅',
                                            'to reproach or challenge in a mocking or insulting manner: jeer at',
                                            ["The boys continually taunted each other. 男孩子们互相挑衅。"],
                                            'bait, hassle, haze, heckle, needle, ride')]),
                              Word('taut', "",
                                   [TestWay('adj',
                                            '紧绷的',
                                            'not loose or flabby',
                                            ["taut muscles 紧实的肌肉"],
                                            antonyms = 'lax, loose, slack'),
                                    TestWay('adj',
                                            '整洁的',
                                            'kept in proper order or condition, kept in trim shape; neat and tidy',
                                            ["a taunt ship 保养得不错的船"],
                                            'kempt, orderly, shipshape, trim')]),
                              Word('tawdry', "",
                                   [TestWay('adj',
                                            '俗丽的',
                                            'cheap and gaudy in appearance or quality; ignoble',
                                            ["a tawdry attempt to smear his opponent 企图污蔑对手的下三滥的手段"],
                                            'meretricious, gaudy, flashy, garish',
                                            'exquisite')])])

list25_unit7 = VocabularyList([Word('taxing', "",
                                   [TestWay('adj',
                                            '繁重的, 费力的',
                                            'requiring much time, effort, or careful attention',
                                            ["The journey proved to be very taxing. 旅途很艰辛。"],
                                            'arduous, burdensome, exacting, grueling, laborious, onerous, toilsome',
                                            'light, easy')]),
                              Word('tedious', "",
                                   [TestWay('adj',
                                            '冗长乏味的',
                                            'tiresome because of length or dullness: boring',
                                            ["a tedious public ceremony 冗长无聊的公开仪式"],
                                            'drab, dreary, jading, monotonous, stale, stodgy, stuffy, weary, drudging',
                                            'entertaining, absorbing, stimulating, engaging, engrossing, gripping, interesting, intriguing, involving, riveting')]),
                              Word('teeter', "",
                                   [TestWay('vi',
                                            '蹒跚, 不稳定的行走',
                                            'to move unsteadily: wobble',
                                            ["She teetered down the street in her high heels. 她穿着高跟鞋, 在街上摇摇欲坠。"],
                                            'careen, dodder, lurch, reel',
                                            'stabilize'),
                                    TestWay('v',
                                            '犹豫不决',
                                            'to show uncertainty about the right course of action',
                                            ["was teetering on the brink of making a decision about college"],
                                            'balance, dither, falter, hang back, scruple, shilly-shally, stagger, vacillate, waver, wobble',
                                            'dive in, plunge in')]),
                              Word('teetotalism', "",
                                   [TestWay('n',
                                            '禁酒',
                                            'the principle or practice of complete abstinence from alcoholic drinks',
                                            antonyms = 'intemperance')]),
                              Word('telling', "",
                                   [TestWay('adj',
                                            '有效的, 显著的',
                                            'effective, expressive',
                                            ["the most telling evidence 最有力的证据"],
                                            'compelling, conclusive, convincing, forceful, persuasive, satisfying',
                                            'inconclusive, indecisive, ineffective, uncompelling, unconvincing, unpersuasive')]),
                              Word('temerity', "",
                                   [TestWay('n',
                                            '鲁莽, 冒失',
                                            'foolhardy disregard of danger; recklessness',
                                            ["She was punished for his temerity. 她因冒失迟到了苦头。"],
                                            'audacity, brashness, presumption, presumptuousness',
                                            'circumspection, cautious approach, pusillanimity')]),
                              Word('temporize', "",
                                   [TestWay('v',
                                            '行动躲躲闪闪以争取时间、躲避争论等',
                                            'to act evasively in order to gain time, avoid argument, or postpone a decision',
                                            ["“Colonial officials... ordered to enforce unpopular enactments, tended to temporize, to find excuses for evasion”(J.H. Parry) “被命令来执行不受欢迎法案的殖民地官员们倾向于敷衍了事, 去寻找逃避的理由”(J.H.帕里)"])]),
                              Word('temperate', "",
                                   [TestWay('adj',
                                            '言行举止有分寸的',
                                            'avoiding extremes in behavior or expression',
                                            ["rather temperate in his appraisal of the movie, calling it good but not great 对于电影的赞赏很适度, 说其“还好”而不是“很棒”"],
                                            'immoderate, extreme, frivolous'),
                                    TestWay('adj',
                                            '有节制的',
                                            "given to or marked by restraint in the satisfaction of one's appetites",
                                            ["a soft-spoken, serious-minded person of temperate habits 一个说话温和、认真严肃的人, 兴趣爱好都很适度"],
                                            'abstentious, abstinent, continent, self-abnegating, self-denying, sober',
                                            'self-indulgent')]),
                              Word('tempestuous', "",
                                   [TestWay('adj',
                                            '突然且剧烈的变化',
                                            'marked by sudden or violent disturbance',
                                            ["In terms of social change, the 1960s are generally considered the most tempestuous decade in recent American history. 就社会变革来说, 20世纪60年代是近现代美国历史上最动荡的十年。"],
                                            'cataclysmal, tumultuous, turbulent',
                                            'serene')]),
                              Word('tenable', "",
                                   [TestWay('adj',
                                            '有据可依的, 无懈可击的',
                                            'capable of being held or defended; reasonable',
                                            ["a tenable theory 一个站得住脚的理论", "a tenable outpost 一个守得住的前哨"],
                                            'defendable, justifiable, maintainable, supportable, sustainable',
                                            'unjustified, unsound, specious, indefensible, fallacious')])])

list25_unit8 = VocabularyList([Word('tenacious', "",
                                   [TestWay('adj',
                                            '顽固的, 不屈不挠的',
                                            'persistent in maintaining something valued or habitual',
                                            ["a tenacious advocate of civil rights 公民权的坚定捍卫者"],
                                            'dogged, insistent, persevering, pertinacious',
                                            'negotiable, vacillated'),
                                    TestWay('adj',
                                            '粘着的',
                                            'tending to adhere to objects upon contact',
                                            ["You'll have enough time getting those tenacious gum off of your wool sweater. 你有足够的时候去把羊毛毛衣上面那块粘着的泡泡糖弄下来。"],
                                            'adherent, adhesive, clingy, glutinous, tacky, viscid',
                                            'nonadhesive')]),
                              Word('tendentious', "",
                                   [TestWay('adj',
                                            '有偏见的',
                                            'marked by a tendency in favor of a particular point of view: biased',
                                            ["He made some extremely tendentious remarks. 他有些评论颇具偏向性。"],
                                            'partial, distorting, subjective, biased',
                                            'unbiased, unprejudiced')]),
                              Word('tender', "",
                                   [TestWay('vt',
                                            '正式提出',
                                            'to offer formally',
                                            ["tender a letter of resignation 正式提交辞职信"],
                                            'extend, proffer, trot out',
                                            'withdraw'),
                                    TestWay('adj',
                                            '考虑周到的, 关心同情的',
                                            'having or marked by sympathy and consideration for others',
                                            ["an especially tender teacher who loves having kids with special educational needs in her class 特别无微不至的老师, 爱着那些需要特别教育的孩子们"],
                                            'beneficent, benevolent, benignant, compassionate, softhearted',
                                            'atrocious, barbarous, bestial, brutal, callous, cruel, fiendish, inhuman, insensate, sadistic, savage, truculent, uncompassionate, vicious')]),
                              Word('tenuous', "",
                                   [TestWay('adj',
                                            '没有实际内容的',
                                            'having little substance; flimsy',
                                            ["a tenuous argument 站不住脚的论点"],
                                            antonyms = 'substantial')]),
                              Word('tepid', "",
                                   [TestWay('adj',
                                            '不太热心的',
                                            'showing little or no interest or enthusiasm',
                                            ["a tepid response 冷漠的回应", "the tepid conservatism of the fifties 五十年代那种温和的保守主义"],
                                            'lukewarm, halfhearted, uneager, unenthusiastic',
                                            'ardent, ebullient, feverish, keen, passionate, wholehearted')]),
                              Word('terminology', "",
                                   [TestWay('n',
                                            '专业术语',
                                            'the special terms or expressions of a particular group or field',
                                            ["the terminology favored by sportscasters 体育节目转播员喜欢用的那些术语", "medical terminology that can be hard for the patient to understand 那些病人们难以理解的医学术语"],
                                            'argot, cant, dialect, jargon, jive, lingo, patois, patter, slang')]),
                              Word('terminus', "",
                                   [TestWay('n',
                                            '终点, 终点站',
                                            'the final point; the end',
                                            ["Stockholm is the terminus for the southbound train. 斯德哥尔摩是南向去的列车的终点站。"],
                                            'outset, sustain')]),
                              Word('terror', "",
                                   [TestWay('n',
                                            '极度恐惧',
                                            'a state of intense fear',
                                            ["Many civilians fled in terror. 很多黎民百姓极度恐慌逃难去了。"],
                                            'anxiety, dread, fearfulness, fright, horror, panic, trepidation')]),
                              Word('terse', "",
                                   [TestWay('adj',
                                            '简洁的, 简明的',
                                            'brief and to the point; effectively concise',
                                            ["dismissed me with a terse “no” 用一个简单的“不”把我打发了"],
                                            'compact, compendious, laconic, pithy, succinct',
                                            'circuitous, circumlocutory, diffuse, long-winded, prolix, rambling, verbose, windy, wordy')]),
                              Word('testimony', "",
                                   [TestWay('n',
                                            '证词, 声明',
                                            'firsthand authentication of a fact',
                                            ["The jury heard 10 days of testimony. 陪审团进行了10 天的听证。"],
                                            'attestation, confirmation, documentation, substantiation, testament, validation',
                                            'disproof')])])

list25_unit9 = VocabularyList([Word('testy', "",
                                   [TestWay('adj',
                                            '易怒的, 暴躁的',
                                            'easily annoyed: irritable',
                                            ["That coworker would be easier to get along with if she weren't so testy all the time. 如果那个同伴不是一直那么暴怒的话, 她还是挺好相处的"],
                                            'choleric, irascible, peevish, perverse, pettish, petulant',
                                            'affable, good humor, unable to irritate, imperturbable, patient')]),
                              Word('tether', "",
                                   [TestWay('vt',
                                            '(用绳, 铁链)拴系, 束缚',
                                            'to fasten or restrain by or as if by a tether',
                                            ["They tethered the horses in the shade. 他们把马摔在棚子里"],
                                            antonyms = 'detach, tear loose'),
                                    TestWay('n',
                                            '能力或忍耐力的极限',
                                            "the limit of one's strength or resources",
                                            ["drought-stricken farmers at the end of their tether 受干旱打击的农民忍无可忍"])]),
                              Word('theatrical', "",
                                   [TestWay('adj',
                                            '做作的, 夸张的, 矫揉造作的',
                                            'marked by exaggerated self-display and unnatural behavior',
                                            ["assumed a theatrical pose 摆出夸张的姿势"],
                                            'dramatic, histrionic, melodramatic, stagy',
                                            'natural, understated, reserved, restraint')]),
                              Word('therapeutic', "",
                                   [TestWay('adj',
                                            '治疗的',
                                            'of or relating to the treatment of disease or disorders by remedial agents or methods',
                                            ["Gentle exercise can be therapeutic for hospital patients. 适量的运动对病人恢复有好处。"],
                                            'curative, healing, officinal, remedial, restorative')]),
                              Word('thorny', "",
                                   [TestWay('adj',
                                            '多刺的',
                                            'full of thorns',
                                            ["Stay out of the thorny brambles unless you want a ton of scratches. 离那些荆棘丛远一点, 除非你想满身都是窟窿。"],
                                            antonyms = 'smooth'),
                                    TestWay('adj',
                                            '棘手的',
                                            'full of difficulties or controversial points : ticklish',
                                            ["a thorny problem 棘手的问题"],
                                            'catchy, delicate, knotty, prickly, ticklish')]),
                              Word('threadbare', "",
                                   [TestWay('adj',
                                            '陈腐的',
                                            'overused to the point of being worn out; hackneyed',
                                            ["a novel filled with nothing but threadbare clichés 一部满是陈词滥调的小说"],
                                            'banal, cliché, commonplace, hackney, shopworn, trite'),
                                    TestWay('adj',
                                            '贫穷的',
                                            'lacking money or material possessions',
                                            ["never knew that she had so many threadbare relatives until she won the lottery 赢了彩票之后才知道她有这么多穷亲戚"],
                                            'beggared, destitute, down-and-out, famished, impecunious, impoverished, indigent, necessitous, needful, pauperized, penniless, penurious, poverty-stricken, skint',
                                            'affluent, deep-pocketed, flush, opulent, silk-stocking, wealthy, well-heeled, well-off, well-to-do'),
                                    TestWay('adj',
                                            '破烂的',
                                            'worn or torn into or as if into rags',
                                            ["I loved that threadbare shirt, but after 10 years of wear, it was time to throw it away. 我很喜欢那件旧旧的衬衣, 但是已经穿了10 年了, 是该扔了。"],
                                            'frayed, raggedy, ratty, seedy, shabby, tattered, worn-out')]),
                              Word('throng', "",
                                   [TestWay('vi./n',
                                            '大量聚集',
                                            'to crowd together in great numbers',
                                            ["commuters thronging the MTR platform 持月票的乘客拥向地铁站"],
                                            'flock, mob, swarm')]),
                              Word('thwart', "",
                                   [TestWay('vt',
                                            '阻挠',
                                            'to oppose successfully',
                                            ["She did all she could to thwart his plans. 她竭尽所能阻挠他的计划。"],
                                            'baffle, balk, checkmate, discomfit',
                                            'advance, cultivate, encourage, forward, foster, further, nurture, promote, support, aid, bolster, abet, foment, facilitate')]),
                              Word('ticklish', "",
                                   [TestWay('adj',
                                            '易怒的',
                                            'easily offended or upset; touchy',
                                            ["ticklish about his baldness 大家一提起他的秃头, 他就暴怒"],
                                            'huffy, tetchy, thin-skinned',
                                            'imperturbable'),
                                    TestWay('adj',
                                            '棘手的, 对技巧要求高的',
                                            'requiring exceptional skill or caution in performance or handling',
                                            ["Trying to tell him that his zipper is down without embarrassing him will be a ticklish task. 如何体面得体地提醒他拉链没关好是一个技巧活儿。"],
                                            'catchy, delicate, difficult, dodgy, knotty, prickly, problematic, sensitive, spiny, sticky, thorny, touchy, tough, tricksy')]),
                              Word('tiff', "",
                                   [TestWay('n./v',
                                            '小争吵',
                                            'a petty quarrel',
                                            ["got into a little tiff about what color sheets to buy for their bed 对于买什么颜色的床单争吵"],
                                            'altercate, bicker, brabble, hassle, quarrel, quibble, row, scrap, spat, squabble')])])

list25_unit10 = VocabularyList([Word('tightfisted', "",
                                   [TestWay('adj',
                                            '吝啬的',
                                            'close-fisted; stingy',
                                            ["The company is pretty tightfisted when it comes to bonuses. 这个公司分红的时候很吝啬。"],
                                            'mean, miserly, parsimonious, penurious, sparing, stinting',
                                            'bounteous, bountiful, charitable, freehanded, generous, liberal, munificent, openhanded, unsparing, unstinting')]),
                              Word('timeworn', "",
                                   [TestWay('adj',
                                            '陈腐的',
                                            'hackneyed, stale',
                                            ["timeworn jokes 老掉牙的笑话"],
                                            'banal, cliché, commonplace, hackneyed, stereotyped, threadbare, trite',
                                            'fresh, new, novel, original, unclichéd, unhackneyed')]),
                              Word('timid', "",
                                   [TestWay('adj',
                                            '胆小的, 不自信的',
                                            'lacking in courage or self-confidence',
                                            ["He gave her a timid smile. 他给了她一个羞赧的微笑。"],
                                            'fainthearted, fearsome, scary, timorous, tremulous',
                                            'stalwart, adventurous, audacious, bold, daring, dashing, gutsy, venturous')]),
                              Word('timorous', "",
                                   [TestWay('adj',
                                            '胆小的',
                                            'of a timid disposition: fearful',
                                            ["be as timorous as a rabbit 像兔子一样胆小"],
                                            'timid, undaring, quailing, recoiling, scary, skittish',
                                            'stalwart, intrepid, adventurous, audacious, bold, daring, dashing, gutsy, venturous')]),
                              Word('tinge', "",
                                   [TestWay('vt',
                                            '给…着上少量的色彩',
                                            'to color with a slight shade or stain; tint',
                                            ["just slightly tinge the frosting with yellow food coloring to give it a lemony look 略微在霜糖表面加一点黄色色素, 有一点柠檬的感觉就可以了"],
                                            'dye, pigment, stain, tincture, tint',
                                            'suffuse, decolorize')]),
                              Word('tinker', "",
                                   [TestWay('vi',
                                            '乱修, 乱调整',
                                            'to handle thoughtlessly, ignorantly, or mischievously',
                                            ["tinkering with the engine 胡乱调整发动机"],
                                            'diddle with, fiddle with, fool with, mess with, toy with, twiddle with',
                                            'adjust, repair')]),
                              Word('tint', "",
                                   [TestWay('v',
                                            '涂浅色, 微染',
                                            'apply a usually slight or pale coloration to',
                                            ["tint with only one color 只用一种颜色染色"],
                                            'dye, pigment, stain, tincture, tinge',
                                            'suffuse, decolorize')]),
                              Word('tirade', "",
                                   [TestWay('n',
                                            '长篇抨击性演讲',
                                            'a long angry or violent speech, usually of a censorious or denunciatory nature; a diatribe',
                                            ["a tirade of angry protest 一个表达愤怒的抗议的长篇抨击性演讲"],
                                            'harangue, diatribe, jeremiad, philippic, rant',
                                            'eulogy, encomium, panegyric, tribute')]),
                              Word('toady', "",
                                   [TestWay('n./v',
                                            '马屁精, 拍马屁',
                                            'one who flatters in the hope of gaining favors',
                                            ["He criticized that I was a toady. 他批评说我是一个马屁精。"],
                                            'sycophant, groveler, flatterer')]),
                              Word('tonic', "",
                                   [TestWay('adj',
                                            '滋补的, 有益健康的',
                                            'producing or stimulating physical, mental, or emotional vigor; beneficial to the health of body or mind',
                                            ["tonic medicine 补药"],
                                            'medicinal, restorative, salubrious, salutary, salutiferous, sanative, wholesome',
                                            'insalubrious, noxious, unhealthful, unhealthy, unwholesome')])])

LIST25 = VocabularyList(list25_unit1.words+list25_unit2.words+list25_unit3.words+list25_unit4.words+list25_unit5.words+list25_unit6.words+list25_unit7.words+list25_unit8.words+list25_unit9.words+list25_unit10.words)
