#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form

list10_unit1 = VocabularyList([Word('falsehood', "",
                                   [TestWay('n',
                                            '谎言',
                                            'a statement known by its maker to be untrue and made in order to deceive',
                                            ["Truth always rise above falsehood, as oil rise above water. 油脂水面浮, 真理胜谎言"],
                                            ['deception', 'fable', 'lie', 'mendacity', 'prevarication', 'untruth'],
                                            ['truth', 'verity'])]),
                              Word('falter', "",
                                   [TestWay('vi',
                                            '蹒跚',
                                            'to walk unsteadily',
                                            synonyms = ['lurch', 'stagger', 'stumble', 'teeter', 'totter', 'wobble']),
                                    TestWay('vi',
                                            '犹豫, 踌躇',
                                            'to be unsteady in purpose or action, as from loss of courage or confidence',
                                            ["Mr. Garrison never once faltered in his demand that slavery be unconditionally abolished. 盖瑞森先生从不对他废除奴隶的要求存有任何的犹豫"],
                                            ['balance', 'halt', 'hesitate', 'vacillate', 'waver'],
                                            other_form = 'faltering adj. 犹豫的')]),
                              Word('fanatic', "",
                                   [TestWay('n',
                                            '狂热者',
                                            'a person marked or motivated by an extreme, unreasoning enthusiasm, as for a cause',
                                            ["a soccer fanatic 一个足球迷"],
                                            ['bigot', 'devotee', 'enthusiast', 'fiend', 'freak', 'maniac', 'partisan', 'zealot'],
                                            ['nonfan']),
                                    TestWay('adj',
                                            '狂热的; 盲信的',
                                            'marked by excessive enthusiasm and often intense uncritical devotion',
                                            ["They are fanatic about sadomasochism. 他们对SM十分狂热"],
                                            ['extreme', 'rabid', 'radical', 'revolutionary', 'ultra'],
                                            ['conservative', 'rational'],
                                            'fanatical adj. 狂热的; 盲信的')]),
                              Word('fantasy', "",
                                   [TestWay('n',
                                            '幻想',
                                            'imaginative fiction featuring especially strange settings and grotesque characters',
                                            ["indulge in a fantasy 沉迷于幻想"],
                                            ['chimera', 'conceit', 'daydream', 'delusion', 'dream', 'hallucination', 'illusion', 'vision'],
                                            ['actuality', 'fact', 'reality', 'truth']),
                                    TestWay('vt',
                                            '产生幻想',
                                            'to form a mental picture of',
                                            ["He regularly fantasies romantic encounters that he knows will never happen. 他会定期意淫一些永远不可能发生的浪漫邂逅"],
                                            ['dream', 'envisage', 'envision', 'fantasize', 'imagine', 'picture'],
                                            other_form = 'fantastic adj. 梦幻般的, 极好的')]),
                              Word('farce', "",
                                   [TestWay('n',
                                            '(带有嘲讽元素的)滑稽戏',
                                            'a light dramatic composition marked by broadly satirical comedy and improbable plot',
                                            synonyms = ['burlesque', 'caricature', 'parody', 'sham', 'travesty'],
                                            antonyms = ['serious play']),
                                    TestWay('n',
                                            '闹剧',
                                            'ridiculous or empty show',
                                            ["The enforcement of this law became a farce. 这条法律的执行过程成了一场闹剧"],
                                            ['joke', 'mockery', 'nonsense'],
                                            other_form = 'farcical adj. 荒谬的')]),
                              Word('fascinate', "",
                                   [TestWay('vt',
                                            '强列吸引, 使入迷',
                                            'to hold an intense interest or attraction for',
                                            ["toys that fascinate infants 吸引婴儿们的玩具"],
                                            ['allure', 'arrest', 'attract', 'bewitch', 'captivate', 'charm', 'enchant', 'enthrall', 'grip'],
                                            ['disgust', 'repel'],
                                            'fascinating adj. 引人入胜的')]),
                              Word('fast', "",
                                   [TestWay('n',
                                            '绝食; 斋戒',
                                            'an act of abstaining from food',
                                            ["fast to death 绝食而死"],
                                            ['hunger strike']),
                                    TestWay('adj',
                                            '快速的',
                                            'characterized by quick motion, operation, or effect',
                                            ["The fast pace of construction resulted in our new house being done ahead of schedule. 极快的施工使得我们的新房提前竣工"],
                                            ['brisk', 'expeditious', 'fleeting', 'hasty', 'quick', 'rapid', 'speedy', 'swift'],
                                            ['slow']),
                                    TestWay('adj',
                                            '忠诚的',
                                            "firm in one's allegiance to someone or something",
                                            ["The two girls soon became fast and inseparable friends. 这两个女孩子很快成为了忠于彼此的形影不离的好伙伴"],
                                            ['constant', 'dedicated', 'devoted', 'devout', 'loyal', 'pious'],
                                            ['disloyal', 'perfidious', 'treacherous']),
                                    TestWay('adj',
                                            '稳固的, 难以拆卸的',
                                            'firmly positioned in place and difficult to dislodge',
                                            ["The rusty, old screws are so fast in the fitting that there's no hope of getting them out. 这颗生锈的老铁钉已经钉得太死了, 根本不可能将其取出"],
                                            ['firm', 'frozen', 'lodged', 'secure', 'stable', 'staunch', 'strong', 'stuck'],
                                            ['loose', 'shaky', 'insecure'],
                                            'fasten v. 系紧')]),
                              Word('fastidious', "",
                                   [TestWay('adj',
                                            '挑剔的, 极仔细的, 追求完美的',
                                            'possessing or displaying careful, meticulous attention to detail',
                                            ["be fastidious about personal hygiene and appearance 极其注意个人卫生和外表"],
                                            ['demanding', 'exacting', 'fussy', 'hypercritical', 'squeamish'],
                                            ['undemanding', 'cursory', 'indiscriminate', 'uncritica'])]),
                              Word('fateful', "",
                                   [TestWay('adj',
                                            '意义重大的',
                                            'involving momentous consequences',
                                            ["make a fateful decision to declare war 做出了宣战的重大决定"],
                                            ['critical', 'crucial', 'important', 'momentous', 'significant'],
                                            ['inconsequential', 'insignificant', 'petty', 'paltry', 'trivial', 'unimportant']),
                                    TestWay('adj',
                                            '带来灾难的, 毁灭性的',
                                            'bringing death or disaster',
                                            ["a fateful journey 一趟致命的旅行"],
                                            ['calamitous', 'cataclysmic', 'catastrophic', 'deadly', 'destructive', 'disastrous', 'fatal', 'ruinous'])]),
                              Word('fathom', "",
                                   [TestWay('vt',
                                            '测量(深度)',
                                            'to measure the depth of (as a body of water) typically with a weighted line',
                                            ["The pilot had to continually fathom the river, which drought conditions had lowered to unprecedented levels. 舵手不得不时刻注意河水深度, 因为干旱已经使水深下降到了前所未有的程度"],
                                            ['plumb']),
                                    TestWay('vt',
                                            '彻底理解, 弄懂',
                                            'to penetrate and come to understand',
                                            ["unable to fathom the what he was talking about 无法弄懂他在说什么"],
                                            ['apprehend', 'cognize', 'comprehend', 'grasp', 'know', 'understand'],
                                            ['misunderstand'],
                                            'fathomable adj. 可测量的; 可知晓的')])])

list10_unit2 = VocabularyList([Word('fatigue', "",
                                   [TestWay('n',
                                            '疲惫',
                                            'weariness or exhaustion from labor, exertion, or stress',
                                            ["The day-long battle against the blaze left firefighters in a state of utter fatigue. 与大火一整天的斗争使得消防员们处于极度疲惫的状态"],
                                            ['collapse', 'exhaustion', 'lassitude', 'tiredness', 'weariness'],
                                            ['refreshment', 'rejuvenation', 'revitalization']),
                                    TestWay('n',
                                            '(让人厌倦的)苦差事',
                                            'something, such as tiring effort or activity, that causes weariness',
                                            ["Although he had joined the army for action and adventure, much of his day seemed to be devoted to mindless fatigues. 尽管当初参军是为了上战场冒险的, 但我生活的大部分时间似乎都耗费在了没意思的苦差上"],
                                            ['drudge', 'drudgery', 'grind', 'labor', 'sweat', 'toil', 'travail'],
                                            ['fun', 'play', 'sinecure'])]),
                              Word('fatuous', "",
                                   [TestWay('adj',
                                            '愚笨的',
                                            'complacently or inanely foolish',
                                            ["Emperor Yang in the Sui Dynasty is not only a rare fatuous tyrant but also an outstanding poet. 隋炀帝不仅仅是少有的昏暴之君, 在文学上还是一位杰出的诗人"],
                                            ['asinine', 'brainless', 'foolish', 'obtuse', 'silly', 'simple', 'stupid', 'unwitty', 'witless'],
                                            ['sagacious', 'sapient', 'judicious', 'prudent', 'sensible', 'wise'])]),
                              Word('faultfinder', "",
                                   [TestWay('n',
                                            '吹毛求疵的人',
                                            'one who is given to petty criticism and constant complaint',
                                            ["No sooner had we finished decorating the church than the parish faultfinder decided that she didn't like it. 我们一完成教堂的装修工作, 教区里挑剔的人就说她不喜欢"],
                                            ['carper', 'castigator', 'caviler', 'censurer', 'critic', 'disparager', 'hypercritic', 'nitpicker'])]),
                              Word('favorable', "",
                                   [TestWay('adj',
                                            '赞许的',
                                            'expressing approval',
                                            ["Favorable reviews for the movie were few. 关于电影的正面评价极少"],
                                            ['admiring', 'applauding', 'commendatory', 'complimentary', 'positive'],
                                            ['adverse', 'disapproving', 'negative']),
                                    TestWay('adj',
                                            '有利的',
                                            'tending to promote or facilitate',
                                            ["mild climate favorable to his health 有利于他健康的温和气候"],
                                            ['advantageous', 'benefic', 'beneficial', 'favoring', 'good', 'helpful', 'salutary'],
                                            ['unfavorable', 'disadvantageous', 'untoward', 'unpropitious'])]),
                              Word('fawn', "",
                                   [TestWay('vi',
                                            '阿谀奉承',
                                            'to seek favor or attention by flattery and obsequious behavior',
                                            ["fawn on one's superior 向上司谄媚"],
                                            ['cower', 'cringe', 'flatter', 'grovel', 'toady', 'truckle'],
                                            ['domineer'],
                                            'fawning adj. 阿谀奉承的, 讨好的')]),
                              Word('faze', "",
                                   [TestWay('vt',
                                            '打扰, 使尴尬',
                                            'to disturb the composure of: disconcert, dismay',
                                            ["Nothing can faze her. 没有什么可以使她气馁"],
                                            ['abash', 'annoy', 'bother', 'disconcert', 'dismay', 'disturb', 'discomfit', 'embarrass', 'fluster', 'rattle'],
                                            ['calm', 'lull'])]),
                              Word('feckless', "",
                                   [TestWay('adj',
                                            '无成果的, 没有价值的',
                                            'having no real worth or purpose',
                                            ["years of feckless negotiations 长达数年的毫无成果的谈判"],
                                            ['bootless', 'fruitless', 'futile', 'meaningless', 'purposeless', 'useless', 'worthless'],
                                            ['effective', 'effectual', 'efficacious']),
                                    TestWay('adj',
                                            '粗心不负责任的',
                                            'careless and irresponsible',
                                            ["The young man was feckless and irresponsible. 这个年轻人既粗心又没有责任感"],
                                            ['careless', 'heedless', 'inadvertent', 'irresponsible', 'slipshod', 'sloppy'],
                                            ['careful', 'cautious', 'circumspect', 'discreet', 'wary'])]),
                              Word('fecund', "",
                                   [TestWay('adj',
                                            '多产的, 肥沃的',
                                            'fruitful in offspring or vegetation',
                                            ["fecund black soil 肥沃的黑土地"],
                                            ['cornucopian', 'fertile', 'fruitful', 'lush', 'luxuriant', 'productive', 'prolific', 'rich'],
                                            ['barren', 'infertile', 'sterile'],
                                            'fecundity n. 多产')]),
                              Word('feeble', "",
                                   [TestWay('adj',
                                            '衰弱的',
                                            'markedly lacking in strength',
                                            ["The heartbeat was feeble and irregular. 心跳虚弱而不规则"],
                                            ['debilitated', 'effete', 'enervated', 'faint', 'fragile', 'frail', 'infirm', 'languid', 'sapped'],
                                            ['mighty', 'powerful', 'robust', 'stalwart', 'stout', 'strong'],
                                            'enfeeble vt. 使衰弱')]),
                              Word('feign', "",
                                   [TestWay('vt',
                                            '制造假象, 装出…的样子',
                                            'to give a false appearance of',
                                            ["I would never feign illness just to postpone a test. 我绝不会为了缓考而装病"],
                                            ['affect', 'assume', 'counterfeit', 'dissemble', 'pretend', 'profess', 'sham', 'simulate'],
                                            other_form = 'unfeigned adj. 没有伪装的, 真诚的')])])

list10_unit3 = VocabularyList([Word('fender', "",
                                   [TestWay('n',
                                            '缓冲装置',
                                            'a cushioning device, such as a bundle of rope or a piece of timber, used on the side of a vessel or dock to absorb impact or friction',
                                            ["a fender on the SUV 运动越野车的一个防护板"],
                                            ['buffer', 'bumper', 'cocoon', 'cushioning', 'pad'])]),
                              Word('feral', "",
                                   [TestWay('adj',
                                            '野生的',
                                            'not domesticated or cultivated',
                                            ["Animal experts discourage homeowners from trying to adopt feral animals as pets. 动物专家们不建议户主们将野生动物收养为宠物"],
                                            ['undomesticated', 'untamed', 'wild'],
                                            ['cultivated', 'domestic', 'tame']),
                                    TestWay('adj',
                                            '动物性的',
                                            'having or showing the nature and appetites of a lower animal',
                                            ["The movie reveals just how thin the veneer of civilization is and how feral we are at bottom. 这部电影展示了所谓文明只不过是薄薄的一层纱, 而内心深处我们仍然是野兽"],
                                            ['animalistic', 'beastly', 'brutal'],
                                            ['rational'])]),
                              Word('fertilize', "",
                                   [TestWay('vt',
                                            '使肥沃, 使多产',
                                            'to make fertile',
                                            ["Reading will fertilize vocabulary. 阅读丰富词汇"],
                                            ['enrich', 'manure'],
                                            ['deplete', 'drain', 'exhaust'],
                                            'fertilizer n. 化肥')]),
                              Word('fervid', "",
                                   [TestWay('adj',
                                            '酷热的',
                                            'having a notably high temperature',
                                            ["set out when the fervid heat subsides 当酷热消散之后才出发"],
                                            ['boiling', 'hot', 'scorching', 'searing', 'sultry', 'sweltering', 'torrid'],
                                            ['arctic', 'chilling', 'cold', 'freezing', 'frigid', 'frozen', 'glacial', 'icy']),
                                    TestWay('adj',
                                            '热情的',
                                            'marked by great passion or zeal',
                                            ["a fervid patriot 热情洋溢的爱国者"],
                                            ['ardent', 'fervent', 'impassioned', 'passionate', 'perfervid'],
                                            ['cold', 'cool', 'dispassionate', 'emotionless', 'impassive', 'unemotional'])]),
                              Word('fervor', "",
                                   [TestWay('n',
                                            '热情, 狂热',
                                            'great warmth and intensity of emotion',
                                            ["A blind patriotic fervor is called chauvinism. 盲目的爱国热情就被称为沙文主义"],
                                            ['ardor', 'enthusiasm', 'passion', 'zeal', 'zealotry'],
                                            ['apathy', 'indifference', 'impassiveness', 'unconcern'])]),
                              Word('fester', "",
                                   [TestWay('v',
                                            '感染溃烂, 腐烂',
                                            'to infect, inflame, or corrupt',
                                            ["A dirty wound will probably fester. 伤口弄脏了有可能会化脓"],
                                            ['corrupt', 'decompose', 'putrefy', 'rot', 'spoil'],
                                            ['heal', 'cure'])]),
                              Word('fetid', "",
                                   [TestWay('adj',
                                            '恶臭的',
                                            'having a heavy offensive smell',
                                            ["Ammonia has a fetid odor that sickened the people. 氨气有着令人作呕的气味"],
                                            ['foul', 'fusty', 'malodorous', 'noisome', 'reeking', 'smelly', 'stinky', 'strong'],
                                            ['ambrosial', 'aromatic', 'balmy', 'fragrant', 'redolent', 'scented'])]),
                              Word('fetter', "",
                                   [TestWay('n',
                                            '枷锁, 限制',
                                            "something that limits one's freedom of action or choice",
                                            ["a fetter that prevents us from trying something new 阻碍我们尝试新事物的枷锁"],
                                            ['circumscription', 'constraint', 'curb', 'limitation', 'restraint', 'stricture']),
                                    TestWay('v',
                                            '束缚',
                                            'to restrain from motion, action, or progress',
                                            ["be fettered by family responsibilities 被家庭责任所束缚"],
                                            ['chain', 'clog', 'enfetter', 'hamper', 'manacle', 'restrain', 'shackle', 'trammel'],
                                            ['enfranchise', 'free', 'liberate', 'unbind', 'unfetter', 'unshackle', 'facilitate'],
                                            'enfetter v. 束缚')]),
                              Word('fiasco', "",
                                   [TestWay('n',
                                            '大失败',
                                            'a complete failure',
                                            ["The Hitler's plot ended in a fiasco. 希特勒的阴谋最终以失败告终"],
                                            ['catastrophe', 'debacle', 'disaster', 'failure'],
                                            ['blockbuster', 'éclat', 'success'])]),
                              Word('fickle', "",
                                   [TestWay('adj',
                                            '易变的',
                                            'likely to change frequently, suddenly, or unexpectedly',
                                            ["a fickle lover 感情善变的情人"],
                                            ['capricious', 'fluid', 'mercurial', 'mutable', 'temperamental', 'volatile'],
                                            ['constant', 'immutable', 'invariable', 'stable', 'steady']),
                                    TestWay('adj',
                                            '不忠诚的',
                                            "not true in one's allegiance to someone or something",
                                            ["When the family's fortune disappeared, so did their fickle friends. 当这个家庭的财富消逝殆尽时, 他们的那些虚伪的朋友也无影无踪了"],
                                            ['disloyal', 'perfidious', 'recreant', 'traitorous', 'treacherous', 'unfaithful'],
                                            ['faithful', 'loyal'])])])

list10_unit4 = VocabularyList([Word('fictitious', "",
                                   [TestWay('adj',
                                            '虚构的',
                                            'not real and existing only in the imagination',
                                            ["His wartime exploits turned out to be entirely fictitious, as he had never even been in the military. 他吹嘘的战时英勇行为是彻底虚构的, 因为他根本就没有参过军"],
                                            ['chimerical', 'fabricated', 'fabulous', 'fictional', 'imagined', 'invented'],
                                            ['actual', 'existing', 'real'])]),
                              Word('fidelity', "",
                                   [TestWay('n',
                                            '忠诚',
                                            'the quality or state of being faithful',
                                            ["They have never wavered in their fidelity to the cause of liberation. 他们从不动摇对于解放事业的忠诚"],
                                            ['adherence', 'allegiance', 'commitment', 'devotion', 'faith', 'loyalty', 'piety'],
                                            ['disloyalty', 'infidelity', 'perfidy', 'treachery'],
                                            'infidel n. 异教徒')]),
                              Word('figurative', "",
                                   [TestWay('adj',
                                            '比喻的',
                                            'expressing one thing in terms normally denoting another with which it may be regarded as analogous',
                                            ["The word here is used in its figurative sense. 这个词在这里取它的比喻义"],
                                            ['extended', 'metaphorical'],
                                            ['literal'])]),
                              Word('figurine', "",
                                   [TestWay('n',
                                            '小雕塑',
                                            'a small statue',
                                            ["His collection of figurines includes toy soldiers from every war that America has fought. 他收藏的小雕塑包括了所有美国参与过的战争中的兵人模型"],
                                            ['figure', 'statuette'],
                                            ['colossus', '巨像'])]),
                              Word('filibuster', "",
                                   [TestWay('n./v',
                                            '拖延议事',
                                            'the use of obstructionist tactics, especially prolonged speechmaking, for the purpose of delaying legislative action',
                                            ["The Senator used a filibuster to stop the bill. 参议员拖延了草案的实施"],
                                            ['delay', 'hindrance', 'impediment', 'obstruction', 'postponement', 'procrastination'])]),
                              Word('filter', "",
                                   [TestWay('v',
                                            '过滤',
                                            'to pass through a filter',
                                            ["steep the tea and then filter it to get rid of the leaves 浸泡茶叶, 再将其过滤以去除废渣"],
                                            ['screen']),
                                    TestWay('v',
                                            '去除杂质',
                                            'to remove(usually visible) impurities from',
                                            ["After frying the chicken, we filtered the oil and kept it in the refrigerator to use again. 在炸完鸡肉之后, 我们将滤去了杂质的油保存起来以供日后使用"],
                                            ['clear', 'distill', 'garble', 'purify'],
                                            ['adulterate', 'contaminate'])]),
                              Word('finale', "",
                                   [TestWay('n',
                                            '终场, 结局',
                                            'the closing part, scene, or number in a public performance',
                                            ["Didier Drogba pulled one back for Chelsea in a finale. 德罗巴在终场结束时为切尔西扳回一球。"],
                                            ['close', 'coda', 'conclusion', 'end'],
                                            ['prologue', 'overture'])]),
                              Word('finesse', "",
                                   [TestWay('n',
                                            '娴熟技巧',
                                            'mental skill or quickness',
                                            ["The musician shows wonderful finesse. 那位音乐家展现出了非凡的技艺"],
                                            ['adeptness', 'adroitness', 'cleverness', 'dexterity', 'proficiency'],
                                            ['awkwardness', 'ineptitude', 'gaucherie', 'ungainliness']),
                                    TestWay('v',
                                            '精心策划',
                                            'to plan out usually with subtle skill or care',
                                            ["finesse the schedule 精心安排日程"],
                                            ['contrive', 'frame', 'machinate', 'maneuver', 'manipulate']),
                                    TestWay('v',
                                            '(巧妙地)躲避',
                                            'to get or keep away from (as a responsibility) through cleverness or trickery',
                                            ["He tried to finesse the blame for the foreign policy fiasco, even though he was secretary of state at the time. 他竭尽所能躲避因失败的对外政策而可能遭到的指责, 尽管他是时任国务卿"],
                                            ['avoid', 'dodge', 'eschew', 'evade', 'shun'],
                                            ['confront'])]),
                              Word('finicky', "",
                                   [TestWay('adj',
                                            '过分讲究的, 挑剔的',
                                            'extremely or excessively particular, exacting, or meticulous in taste or standards',
                                            ["have a reputation for being finicky eater 有着挑食的名声"],
                                            ['demanding', 'exacting', 'fastidious', 'fussy', 'nice', 'particular'],
                                            ['undemanding', 'unfussy'])]),
                              Word('flaccid', "",
                                   [TestWay('adj',
                                            '不结实的, 松弛的',
                                            'not firm or stiff; lacking normal or youthful firmness',
                                            ["flaccid muscles 松弛的肌肉"],
                                            ['droopy', 'floppy', 'lank', 'loose', 'slack', 'yielding'],
                                            ['stiff', 'sturdy', 'resilient'])])])

list10_unit5 = VocabularyList([Word('flag', "",
                                   [TestWay('n',
                                            '旗帜, 象征',
                                            'a piece of fabric that is used as a symbol (as of a nation) or as a signaling device',
                                            ["We respect the flag of our fathers. 我们尊敬父辈们的旗帜"],
                                            ['banner', 'ensign', 'pendant', 'pennant']),
                                    TestWay('v',
                                            '变得衰弱',
                                            'to become unsteady, feeble, or spiritless',
                                            ["We flagged as we neared the end of the long mountain trail. 当我们终于快到达漫长山路的终点时, 已经筋疲力尽"],
                                            ['decay', 'decline', 'deteriorate', 'emaciate', 'fade', 'fail', 'languish', 'sag', 'waste', 'wilt', 'wither'],
                                            ['thrive', 'revitalize', 'revive'],
                                            'unflagging adj. 坚持不懈的')]),
                              Word('flamboyant', "",
                                   [TestWay('adj',
                                            '艳丽夺目的, 炫耀的, 充满装饰的',
                                            'marked by or given to strikingly elaborate or colorful display or behavior; ornate',
                                            ["Las Vegas showgirls wearing flamboyant headdresses 打扮花哨的拉斯维加斯舞女"],
                                            ['flaring', 'florid', 'garish', 'ornate', 'ostentatious', 'showy'],
                                            ['natural', 'conservative', 'quiet', 'understated'],
                                            'flamboyance n. 炫目, 炫耀')]),
                              Word('flatter', "",
                                   [TestWay('vt',
                                            '拍马屁, 奉承, 讨好',
                                            'to praise excessively especially from motives of self-interest',
                                            ["Friends who flatter you to your face are not true friends. 当面拍你马屁的朋友都不是真正的朋友"],
                                            ['adulate', 'blandish', 'compliment', 'court', 'massage', 'overpraise', 'stroke', 'wheedle'],
                                            ['abuse', 'censure', 'criticize']),
                                    TestWay('vt',
                                            '自我感觉良好',
                                            'to think highly of (oneself)',
                                            ["Don't flatter yourself that no one has ever thought of that idea before.不要自欺欺人地认为别人没有考虑过那个想法"],
                                            ['pique', 'plume']),
                                    TestWay('vt',
                                            '使显得更漂亮',
                                            'to show off becomingly or advantageously',
                                            ["Orange flatters those with golden skin tones. 橙色让黄肤色的人显得更漂亮"],
                                            ['become', 'enhance', 'suit'],
                                            ['mar', 'spoil'],
                                            'flattering adj.令人满足的, 令人迷恋的')]),
                              Word('flaw', "",
                                   [TestWay('n',
                                            '瑕疵, 缺点',
                                            'an imperfection, often concealed, that impairs soundness',
                                            ["The absence of flaw in beauty is itself a flaw. 完美无瑕本身就是瑕疵"],
                                            ['blight', 'blotch', 'defect', 'fault', 'imperfection', 'mar', 'scar', 'spot']),
                                    TestWay('v',
                                            '降低, 破坏, 使不完美',
                                            'to reduce the soundness, effectiveness, or perfection of',
                                            ["That crack has flawed the vase to the extent that its value in the antiques market is greatly reduced. 那道裂缝让这个花瓶在古董市场上大大地掉价"],
                                            ['blemish', 'break', 'compromise', 'cripple', 'harm', 'hurt', 'impair', 'injure', 'spoil', 'vitiate'],
                                            ['fix', 'mend', 'repair', 'revamp'],
                                            'flawed adj. 有瑕疵的; flawless adj. 完美无瑕的')]),
                              Word('fledgling', "",
                                   [TestWay('n',
                                            '新手',
                                            'a person who is just starting out in a field of activity',
                                            ["At hockey he's still a fledgling and needs to work on his basic skating skills. 在冰球场上他还是一个菜鸟, 还需要在基本的滑冰技术上加强练习"],
                                            ['apprentice', 'beginner', 'freshman', 'neophyte', 'novice', 'tyro', 'recruit', 'rookie'],
                                            ['veteran'],
                                            'fledge v. 鸟类长羽毛')]),
                              Word('fleet', "",
                                   [TestWay('n',
                                            '舰队, 车队',
                                            'a group of vehicles traveling together or under one management',
                                            ["fleet of the Royal Navy 皇家海军的舰队"],
                                            ['armada', 'caravan', 'cavalcade', 'motorcade']),
                                    TestWay('adj',
                                            '迅速的',
                                            'moving, proceeding, or acting with great speed',
                                            ["He was fleet as a deer. 他如小鹿般敏捷"],
                                            ['brisk', 'expeditious', 'fast', 'hasty', 'nimble', 'quick', 'rapid', 'rattling', 'speedy', 'swift'],
                                            ['slow']),
                                    TestWay('vt',
                                            '快速通过',
                                            'to move or pass swiftly',
                                            ['dart', 'flit', 'hurry', 'hustle'],
                                            ['plod', '沉重而缓慢地走'],
                                            'fleeting adj. 稍纵即逝的')]),
                              Word('flexible', "",
                                   [TestWay('adj',
                                            '灵活的, 可变的',
                                            'capable of being readily changed',
                                            ["Our schedules are highly flexible. 我们的计划是非常灵活的"],
                                            ['adaptable', 'adjustable', 'alterable', 'changeable', 'elastic', 'fluid', 'malleable', 'modifiable', 'pliable', 'variable'],
                                            ['fixed', 'immutable', 'inflexible', 'invariable', 'stiff', 'rigid']),
                                    TestWay('adj',
                                            '易受影响的',
                                            '',
                                            ["Their boss was flexible and lenient. 他们的老板既好说话, 又很仁慈"],
                                            ['docile', 'manageable', 'tractable'],
                                            ['adamant', 'headstrong', 'intractable', 'mulish', 'recalcitrant', 'refractory', 'stubborn', 'obstinate'],
                                            'flexibility n. 灵活性')]),
                              Word('flinch', "",
                                   [TestWay('v',
                                            '畏缩; 退缩',
                                            'to draw back in fear, pain, or disgust',
                                            ["He met my gaze without flinching. 他毫不畏缩地与我对视"],
                                            ['cringe', 'quail', 'recoil', 'shrink', 'wince'],
                                            ['face', 'meet', 'confront'])]),
                              Word('flippancy', "",
                                   [TestWay('n',
                                            '轻率, 无礼',
                                            'unbecoming levity or pertness especially in respect to grave or sacred matters',
                                            ["The flippancy of your answer annoyed me. 你轻率的回答让我很恼火"],
                                            ['facetiousness', 'flightiness', 'frivolousness', 'frothiness', 'levity', 'silliness'],
                                            ['earnestness', 'gravity', 'seriousness', 'soberness', 'solemnity', 'solemnness'])]),
                              Word('flirt', "",
                                   [TestWay('v',
                                            '调情',
                                            'to behave amorously without serious intent',
                                            ["The waitress at that restaurant flirts with all single male customers. 这家餐厅的女服务员对所有的男性单身顾客都暗送秋波"],
                                            ['coquet', 'dally', 'frivol', 'toy', 'trifle']),
                                    TestWay('vi',
                                            '无规则地快速运动',
                                            'to make an irregular series of quick, sudden movements',
                                            ["lazily watched the butterflies flirting among the wildflowers 慵懒地看着蝴蝶在野花丛中乱舞"],
                                            ['dance', 'dart', 'fleet', 'flick', 'flit', 'flutter', 'hurry', 'rush', 'zip'])])])

list10_unit6 = VocabularyList([Word('flit', "",
                                   [TestWay('vi',
                                            '快速或突然地经过',
                                            'to pass quickly or abruptly from one place or condition to another',
                                            ["Memories of the evening flitted through her mind. 关于那一晚的记忆在她脑海中一掠而过。"],
                                            ['dance', 'dart', 'fleet', 'flick', 'flirt', 'flutter', 'hurry', 'rush', 'zip'],
                                            ['plod', '沉重缓慢地走'])]),
                              Word('flock', "",
                                   [TestWay('n',
                                            '人群, 兽',
                                            'a great number of persons or creatures massed together',
                                            ["a flock of ill-disposed reporters at the press conference 新闻发布会上一群不怀好意的记者"],
                                            ['army', 'drove', 'herd', 'legion']),
                                    TestWay('vi',
                                            '聚集, 集体行动',
                                            'to congregate or travel in a flock or crowd',
                                            ["Vacationers flocked to the towns along the shore in order to escape the August heat. 度假的人们一起涌向海岸, 以躲避八月里的热浪"],
                                            ['mob', 'swarm', 'throng'])]),
                              Word('florid', "",
                                   [TestWay('adj',
                                            '辞藻华丽的, 花哨的',
                                            'full of fine words and fancy expressions',
                                            ["gave a florid speech to attract attention 做了个辞藻华丽的演说以吸引眼球"],
                                            ['bombastic', 'flowery', 'grandiloquent', 'magniloquent', 'rhetorical']),
                                    TestWay('adj',
                                            '装饰华丽的',
                                            'elaborately and often excessively decorated',
                                            ["a florid architectural style 华丽的建筑风格"],
                                            ['baroque', 'bedizened', 'flamboyant', 'fussy', 'luscious', 'ornate'],
                                            ['austere', 'plain', 'severe', 'stark', 'unadorned'])]),
                              Word('flounder', "",
                                   [TestWay('vi',
                                            '笨拙地行动, 挣扎',
                                            'to proceed or act clumsily or ineffectually',
                                            ["flounder through the desert 步履蹒跚地穿越沙漠"],
                                            ['blunder', 'fumble', 'lumber', 'plod', 'struggle', 'trudge'],
                                            ['glide', 'slide', 'breeze', 'waltz'])]),
                              Word('flourish', "",
                                   [TestWay('vi',
                                            '茂盛; 繁荣',
                                            'to grow luxuriantly; to achieve success',
                                            ["The program will flourish once it receives adequate funding. 这个项目只要有足够的资金就能大获成功"],
                                            ['bloom', 'burgeon', 'prosper', 'thrive'],
                                            ['languish', 'wane', 'fail']),
                                    TestWay('vi',
                                            '装饰',
                                            'an embellishment or ornamentation',
                                            ["a bedroom with cute little flourishes 一间带有可爱小装饰的卧室", "Her writing style is simple and clear, without unnecessary flourishes. 她的文风很简单清新, 没有那些不必要的修饰"],
                                            ['adornment', 'decoration', 'embellishment', 'ornamentation'])]),
                              Word('flout', "",
                                   [TestWay('n./v',
                                            '嘲弄性的不理会, 蔑视',
                                            'to treat with contemptuous disregard',
                                            ["flout the academic norm by plagiarizing 通过抄袭来蔑视学术规范"],
                                            ['despise', 'disregard', 'gibe', 'sneer', 'taunt'],
                                            ['respect', 'revere', 'venerate'])]),
                              Word('fluctuate', "",
                                   [TestWay('vt',
                                            '波动, 无规则地变动',
                                            'to shift back and forth uncertainly',
                                            ["Stock prices fluctuate wildly.股票价格大幅波动‖Samples of ice cores collected from Antarctica suggested that the atmospheric concentration of carbon dioxide has been fluctuating periodically. 南极冰芯样本表明, 大气中的二氧化碳浓度存在周期性的涨落"],
                                            ['mutate', 'shift', 'swing', 'oscillate', 'vacillate', 'vary', 'waver'],
                                            ['stabilize', 'plateau'],
                                            'fluctuation n. 涨落, 波动')]),
                              Word('fluent', "",
                                   [TestWay('',
                                            '表达流利的',
                                            'able to express oneself clearly and well',
                                            ["a very fluent speaker who always communicates his points well 一个总能明确指出要点的流利演说家"],
                                            ['eloquent', 'silver-tongued', 'well-spoken'],
                                            ['inarticulate', 'ineloquent', 'unvocal']),
                                    TestWay('adj',
                                            '不费力的',
                                            'involving minimal difficulty or effort',
                                            ["a fluent performance of one of the oldest magic tricks in the book 一场毫不费力的魔术, 表演的是书本上最老的魔术之一"],
                                            ['effortless', 'facile', 'fluid', 'painless', 'ready', 'simple', 'smooth'],
                                            ['arduous', 'demanding', 'exacting', 'formidable', 'grueling', 'hard', 'laborious', 'murderous', 'rough', 'toilsome', 'tough'],
                                            'fluency n. 流畅, 流利')]),
                              Word('fluky', "",
                                   [TestWay('adj',
                                            '侥幸的',
                                            'coming or happening by good luck especially unexpectedly',
                                            ["a fluky coincidence that kept me safely at home when the blizzard hit 一个偶然的巧合让我在暴风雪来袭时安全地待在家里"],
                                            ['fortuitous', 'lucky', 'providential'],
                                            ['hapless', 'unfortunate', 'unlucky', 'ill-fated']),
                                    TestWay('adj',
                                            '偶然的',
                                            'happening by or depending on chance',
                                            synonyms = ['casual', 'chance', 'inadvertent', 'incidental', 'unintended', 'unintentional'],
                                            antonyms = ['calculated', 'deliberate', 'intended', 'intentional', 'planned', 'premeditated'],
                                            other_form = 'fluke n. 侥幸, 偶然')]),
                              Word('flush', "",
                                   [TestWay('adj',
                                            '(肤色)健康红润的',
                                            'having a healthy reddish skin tone',
                                            synonyms = ['blooming', 'florid', 'glowing', 'red', 'rosy', 'rubicund', 'sanguine'],
                                            antonyms = ['ashen', 'doughy', 'livid', 'pale', 'pallid', 'wan']),
                                    TestWay('adj',
                                            '富有的',
                                            'having goods, property, or money in abundance',
                                            ["She's very flush now that she has her inheritance. 自从继承了那份遗产, 她变得十分富有"],
                                            ['affluent', 'loaded', 'opulent', 'wealthy'],
                                            ['destitute', 'impoverished', 'indigent', 'needy', 'impecunious']),
                                    TestWay('adj',
                                            '大量的',
                                            'marked by abundance',
                                            ["a field flush with flowers 充满了鲜花的原野"],
                                            ['abounding', 'abundant', 'awash', 'fraught', 'lousy', 'replete', 'swarming', 'teeming', 'thronging'],
                                            ['inadequate', 'insufficient', 'scant', 'scarce', 'short']),
                                    TestWay('vi',
                                            '冲洗',
                                            'to pour liquid over or through in order to cleanse',
                                            ["flush a wound with iodine 用碘酒冲洗伤口"],
                                            ['irrigate', 'rinse', 'sluice', 'wash'])])])

list10_unit7 = VocabularyList([Word('fluster', "",
                                   [TestWay('v',
                                            '使慌乱',
                                            'to put into a state of agitated confusion',
                                            ["A GPA of 1.0 flusters him. 1.0的绩点让他很慌乱"],
                                            ['abash', 'confound', 'confuse', 'discomfit', 'disconcert', 'discountenance', 'faze', 'mortify', 'nonplus', 'rattle'],
                                            ['calm', 'quiet', 'settle', 'soothe', 'tranquilize'])]),
                              Word('foible', "",
                                   [TestWay('n',
                                            '小缺点',
                                            'a minor flaw or shortcoming in character or behavior',
                                            ["admired their teacher despite his foibles 尽管有些小缺点, 但还是很敬佩他们的老师"],
                                            ['demerit', 'dereliction', 'failing', 'fault', 'frailty', 'shortcoming', 'sin', 'vice', 'want', 'weakness'],
                                            ['merit', 'virtue'])]),
                              Word('foil', "",
                                   [TestWay('v',
                                            '挫败',
                                            'to prevent from being successful; defeat',
                                            ["foil her enemy by pulling some strings 通过一些关系和手段挫败了她的对手"],
                                            ['baffle', 'balk', 'beat', 'checkmate', 'discomfit', 'frustrate', 'thwart'],
                                            ['forward', 'foster', 'further', 'promote'])]),
                              Word('foment', "",
                                   [TestWay('',
                                            '助长, 煽动',
                                            'to promote the growth or development of',
                                            ["He was accused of fomenting violence. 他被指控煽动暴力行为"],
                                            ['abet', 'brew', 'ferment', 'incite', 'instigate', 'provoke', 'raise', 'stir'],
                                            ['quash', 'quell', 'quench', 'squash'])]),
                              Word('foolproof', "",
                                   [TestWay('adj',
                                            '十分简单以至于不会失败的',
                                            'so simple, plain, or reliable as to leave no opportunity for error, misuse, or failure',
                                            ["Anything foolproof is impossible and what truly counts is probability. 没有万无一失的事情, 真正的问题在于概率"],
                                            ['guaranteed', 'infallible', 'safe', 'unfailing', 'fail-safe'],
                                            ['fallible'])]),
                              Word('footloose', "",
                                   [TestWay('adj',
                                            '无拘无束的, 自由的',
                                            'having no attachments or ties; free to do as one pleases',
                                            ["After having been chained for so long, the suddenly footloose dog ran about the yard tirelessly. 这只长期被锁链束缚的小狗因为突然之间获得了自由, 在院子里不知疲倦地奔跑"],
                                            ['loose', 'unbound', 'unconfined', 'unfettered', 'unrestrained', 'untrammeled'],
                                            ['bound', 'confined', 'restrained', 'tied'])]),
                              Word('forbearance', "",
                                   [TestWay('n',
                                            '克制; 忍耐',
                                            'tolerance and restraint in the face of provocation; patience',
                                            ["reach the end of my forbearance 到了让我忍无可忍的地步"],
                                            ['patience', 'temperance', 'tolerance', 'toleration'],
                                            ['impatience']),
                                    TestWay('n',
                                            '友好仁慈的态度',
                                            'kind, gentle, or compassionate treatment especially towards someone who is undeserving of it',
                                            ["The judge showed forbearance, and gave the teenaged first offender a suspended sentence. 法官网开一面, 给了初犯的少年犯一个缓刑"],
                                            ['charity', 'clemency', 'leniency', 'mercifulness', 'quarter'],
                                            ['vindictiveness'])]),
                              Word('forebear', "",
                                   [TestWay('n',
                                            '祖先',
                                            'a person from whom one is descended; an ancestor',
                                            ["The son of Abrahamis traditionally considered to be the forebear of the Arabs. 亚伯拉罕之子传统上被认为是阿拉伯人的祖先"],
                                            ['ancestor', 'antecedent', 'asendant', 'father', 'grandfather', 'primogenitor', 'progenitor'],
                                            ['descendant', 'offspring'])]),
                              Word('forestall', "",
                                   [TestWay('vt',
                                            '预先阻止',
                                            'to delay, hinder, or prevent by taking precautionary measures beforehand',
                                            ["You can often forestall skidding on the ice simply by driving more slowly. 通常你只需慢点开车就可以防止车辆在冰面上失控打滑"],
                                            ['avert', 'deter', 'obviate', 'preclude', 'prevent'],
                                            ['abet', 'assist', 'facilitate', 'further', 'precipitate', 'promote'])]),
                              Word('foreword', "",
                                   [TestWay('n',
                                            '前言',
                                            'a preface or an introductory note, as for a book, especially by a person other than the author',
                                            ["The foreword of this book is co-written by Jason and Franklin. 这本书的序由Jason和Franklin共同写成"],
                                            ['beginning', 'introduction', 'overture', 'preamble', 'preface', 'prelude', 'prologue'],
                                            ['epilogue', 'coda', 'finale'])])])

list10_unit8 = VocabularyList([Word('forge', "",
                                   [TestWay('v',
                                            '伪造',
                                            'to make or imitate falsely especially with intent to defraud',
                                            ["The boy forged his father’s signature on his transcript. 小男孩在他的成绩单上伪造了父亲的签名"],
                                            ['coin', 'counterfeit', 'fabricate', 'fake']),
                                    TestWay('v',
                                            '锻造, 铸就',
                                            'to form (as metal) by or as if by heating and hammering',
                                            ["a real man forged by adversity 一个经磨难考验而成的纯爷们", "They agreed to forge closer economic and political ties. 他们就打造双边的紧密政治经济联系达成了共识"],
                                            ['build', 'construct', 'form', 'make', 'manufacture', 'mold', 'shapes'],
                                            other_form = 'forger n. 打铁匠')]),
                              Word('formidable', "",
                                   [TestWay('adj',
                                            '令人害怕的',
                                            'causing fear, dread, or apprehension',
                                            ["a nation that possesses formidable nuclear deterrence 一个拥有可怕核威慑力量的国家"],
                                            ['direful', 'dreadful', 'fearsome', 'forbidding', 'ghastly', 'horrible', 'intimidating', 'redoubtable', 'terrifying'],
                                            ['comforting']),
                                    TestWay('adj',
                                            '艰难的',
                                            'requiring considerable physical or mental effort',
                                            ["running a marathon is a formidable undertaking 跑马拉松是个困难的任务", "They have recently made a formidable decision. 他们最近做出了一个艰难的决定"],
                                            ['arduous', 'challenging', 'demanding', 'exacting', 'grueling', 'heavy', 'laborious', 'sweaty', 'toilsome', 'tough', 'strenuous'],
                                            ['easy', 'effortless', 'facile', 'mindless', 'simple'])]),
                              Word('forthright', "",
                                   [TestWay('adj',
                                            '直率的, 说话率真的',
                                            "free in expressing one's true feelings and opinions",
                                            ["her forthright way of dealing with people 她率真的为人处事方式"],
                                            ['candid', 'forthcoming', 'frank', 'honest', 'open', 'outspoken', 'straightforward'],
                                            ['dissembling']),
                                    TestWay('adj',
                                            '直接的, 不绕弯子的',
                                            'free from ambiguity or evasiveness: going straight to the point',
                                            ["was forthright in appraising the problem 直截了当地评价这个问题"],
                                            ['direct', 'plain', 'straight'],
                                            ['circuitous', 'indirect', 'roundabout'])]),
                              Word('fortify', "",
                                   [TestWay('vt',
                                            '加固, 鼓励',
                                            'to give physical strength, courage, or endurance to',
                                            ["This country will fortify the coastal areas. 这个国家要加强沿海地区的防御"],
                                            ['energize', 'harden', 'invigorate', 'reinforce', 'strengthen', 'toughen'],
                                            ['debilitate', 'enervate', 'enfeeble', 'vitiate', 'weaken']),
                                    TestWay('vt',
                                            '做好心理准备',
                                            'to prepare (oneself) mentally or emotionally',
                                            ["She fortified herself for the incoming tennis tournament with a series of confidence-boosting exercises. 她通过一系列练习赛来找自信, 为即将到来的网球锦标赛做好心理准备"],
                                            ['brace', 'forearm', 'gird', 'nerve', 'poise', 'ready', 'steel'])]),
                              Word('foster', "",
                                   [TestWay('vt',
                                            '促进, 鼓励',
                                            'to help the growth or development of',
                                            ["detect and foster artistic talent 发现并培养艺术天分"],
                                            ['advance', 'encourage', 'forward', 'further', 'incubate', 'promote'],
                                            ['discourage', 'frustrate', 'inhibit']),
                                    TestWay('vt',
                                            '培养',
                                            'to bring to maturity through care and education',
                                            ["a greathearted couple fostering two adopted children as well as their own 对两个养子像自己的孩子一样培养的好心夫妇"],
                                            ['breed', 'cultivate', 'nourish', 'nurse', 'nurture', 'raise', 'rear'])]),
                              Word('founder', "",
                                   [TestWay('n',
                                            '建立者',
                                            'one that founds or establishes',
                                            ["founders of the nation 开国者"],
                                            ['architect', 'author', 'creator', 'father', 'generator', 'initiator', 'originator', 'sire'],
                                            ['terminator']),
                                    TestWay('vi',
                                            '完败',
                                            'to fail utterly',
                                            ["The theater company foundered after its corporate funding dried up. 在其基金告罄之后, 这个戏剧公司彻底失败了"],
                                            ['collapse', 'flunk', 'miss', 'strike out', 'wash out'],
                                            ['succeed', 'work out']),
                                    TestWay('vi',
                                            '沉没',
                                            'to become submerged',
                                            ["The ship struck a reef and foundered. 船因触礁而沉没"],
                                            ['sink', 'submerge', 'submerse', 'go down'],
                                            ['float'])]),
                              Word('fracas', "",
                                   [TestWay('n',
                                            '争吵, 吵闹',
                                            'a physical dispute between opposing individuals or groups; a rough and often noisy fight usually involving several people',
                                            ["The police were called in to break up the fracas.警察奉命去制止骚乱"],
                                            ['battle', 'clash', 'combat', 'conflict', 'contest', 'hassle', 'skirmish', 'struggle', 'tussle'])]),
                              Word('fracture', "",
                                   [TestWay('n',
                                            '破裂',
                                            'the act or process of breaking',
                                            ["a sudden fracture of the established order 已建立起的秩序被突然打破"],
                                            ['breach', 'break', 'rupture', 'schism', 'split'],
                                            ['unity']),
                                    TestWay('v',
                                            '打碎, 破坏',
                                            'to cause to separate into pieces usually suddenly or forcibly',
                                            ["Their happiness was fractured by an unforeseen tragedy. 他们的幸福生活被突如其来的悲剧打破了"],
                                            ['disrupt', 'fragment', 'rive'],
                                            ['cement'])]),
                              Word('fragile', "",
                                   [TestWay('adj',
                                            '易碎的',
                                            'easily broken or destroyed',
                                            ["a fragile piece of glass 一块易碎的玻璃"],
                                            ['breakable', 'feeble', 'frail', 'friable', 'frangible', 'infirm', 'unsound', 'weak'],
                                            ['tough', 'durable']),
                                    TestWay('adj',
                                            '易受伤的, 脆弱的',
                                            'easily injured without careful handling',
                                            ["Babies are extremely fragile, so remember to care for them gently. 小孩子特别容易受伤, 所以要记得温柔地对待他们"],
                                            ['delicate', 'sensitive'],
                                            other_form = 'fragility n. 脆弱')]),
                              Word('frail', "",
                                   [TestWay('adj',
                                            '虚弱的',
                                            'physically weak',
                                            ["Working for three days without any sleep made him extremely frail. 连续三天的彻夜工作使他极为虚弱"],
                                            ['weak', 'effete', 'enervated', 'feeble', 'fragile', 'infirm', 'languid', 'unsubstantial'],
                                            ['robust', 'hale', 'sturdy']),
                                    TestWay('adj',
                                            '(意志)薄弱的',
                                            'easily led astray; morally weak',
                                            ["frail and pathetic humanity 容易误入歧途的可悲人性"],
                                            ['characterless', 'invertebrate', 'nerveless', 'spineless'],
                                            ['faithful', 'resolute']),
                                    TestWay('adj',
                                            '(希望)渺茫的',
                                            'slight, unsubstantial',
                                            ["a frail hope of success 成功的机会渺茫"],
                                            ['fragile', 'negligible', 'slight', 'small'],
                                            other_form = 'frailty n. 虚弱, (意志)脆弱')])])

list10_unit9 = VocabularyList([Word('fraudulent', "",
                                   [TestWay('adj',
                                            '欺诈的',
                                            'characterized by, based on, or done by fraud',
                                            ["a fraudulent interpretation of experimental data 对实验数据的欺骗性解释"],
                                            ['deceitful', 'deceptive', 'dishonest', 'duplicitous', 'guileful', 'underhanded'],
                                            ['reliable', 'trustworthy', 'authentic', 'honest', 'straight'],
                                            'fraudulence n. 欺骗')]),
                              Word('fraught', "",
                                   [TestWay('adj',
                                            '充满的',
                                            'full of or accompanied by something',
                                            ["an experience fraught with peril 充满危险的经历"],
                                            ['abounding', 'abundant', 'awash', 'flush', 'replete', 'thronging'],
                                            ['scarce']),
                                    TestWay('adj',
                                            '令人忧虑的',
                                            'causing or characterized by emotional distress or tension',
                                            ["a fraught relationship between the two neighboring countries 两邻国间令人担忧的关系"],
                                            ['uneasy', 'agitating', 'anxious', 'distressful', 'disturbing', 'restless', 'tense', 'unsettling', 'nail-biting'],
                                            ['calming', 'relaxing'])]),
                              Word('frenzy', "",
                                   [TestWay('n',
                                            '疯狂, 狂怒',
                                            'a violent mental or emotional agitation',
                                            ["She is subject to these frenzies several times a year. 她每年都要暴怒几次"],
                                            ['delirium', 'fever', 'furor', 'fury', 'hysteria', 'insanity', 'rage', 'rampage', 'uproar'],
                                            ['sanity'],
                                            'frenetic adj. 疯狂的')]),
                              Word('frequent', "",
                                   [TestWay('v',
                                            '时常拜访',
                                            'to pay frequent visits to; be in or at often',
                                            ["to frequent opera houses 时常造访歌剧院"],
                                            ['haunt', 'resort', 'visit'],
                                            ['avoid', 'shun']),
                                    TestWay('adj',
                                            '时常发生的, 重复再现的',
                                            'happening at short intervals; often repeated or occurring',
                                            ["He used to make frequent trips to Los Angeles 他从前经常前往洛杉矶旅行"],
                                            ['common', 'constant', 'everyday', 'habitual', 'periodical', 'repeated'],
                                            ['rare'],
                                            'frequency n. 频率; 频繁')]),
                              Word('fretful', "",
                                   [TestWay('adj',
                                            '易怒的, 烦躁的',
                                            'inclined to be vexed or troubled',
                                            ["Adolescence is the most fretful stages of human development. 青春期是人类发展过程中最恼人的阶段"],
                                            ['irritable', 'fractious', 'peevish', 'pettish', 'petulant'],
                                            ['easygoing'],
                                            'fret v. 使烦躁')]),
                              Word('friable', "",
                                   [TestWay('adj',
                                            '易碎的',
                                            'easily crumbled or pulverized',
                                            ["friable mineral rock 易碎的矿石"],
                                            ['crumbly', 'delicate', 'feeble', 'fragile', 'frail', 'infirm', 'weak'],
                                            ['sturdy', 'substantial'])]),
                              Word('friction', "",
                                   [TestWay('n',
                                            '摩擦',
                                            'the rubbing of one object or surface against another',
                                            ["lubricant that significantly reduces friction 能显著减少摩擦的润滑剂"],
                                            ['abrasion']),
                                    TestWay('n',
                                            '冲突, 不和',
                                            'the clashing between two persons or parties of opposed views',
                                            ["There is a friction between the professor and students. 教授和学生之间存在不和"],
                                            ['disagreement', 'conflict', 'contention', 'dissidence', 'schism', 'war'],
                                            ['accord', 'harmony', 'peace', 'concord'],
                                            'frictional adj. 产生摩擦的')]),
                              Word('frigid', "",
                                   [TestWay('adj',
                                            '严寒的',
                                            'extremely cold',
                                            ["an unusually frigid winter of Wuhan 武汉一个反常的寒冬"],
                                            ['cold', 'arctic', 'chilling', 'freezing', 'frosty', 'glacial'],
                                            ['roasting', 'scalding', 'scorching', 'searing', 'seething', 'sizzling', 'sultry', 'sweltering', 'torrid']),
                                    TestWay('adj',
                                            '冷漠的',
                                            'lacking warmth or ardor',
                                            ["a formal but frigid welcome 一个正式但冷漠的招呼"],
                                            ['indifferent', 'cold', 'emotionless', 'passionless', 'unresponsive'],
                                            ['ardent', 'amorous', 'cordial'],
                                            'frigidity n. 严寒; 冷漠')]),
                              Word('fringe', "",
                                   [TestWay('n',
                                            '边缘',
                                            'something that resembles such a border or edging',
                                            ["“Don’t act on the fringes of the law,” warns the customs officer. 海关人员警告说: “不要打法律的擦边球”"],
                                            ['border', 'boundary', 'circumference', 'edge', 'margin', 'perimeter', 'periphery', 'skirt'],
                                            ['center', 'core']),
                                    TestWay('v',
                                            '接壤',
                                            'to be adjacent to',
                                            synonyms = ['abut', 'border', 'neighbor', 'skirt', 'verge'])]),
                              Word('frivolous', "",
                                   [TestWay('adj',
                                            '轻浮的',
                                            'marked by unbecoming levity',
                                            ["a frivolous young woman 一个举止轻浮的年轻女子"],
                                            ['giddy', 'shallow', 'superficial'],
                                            ['earnest', 'sober', 'serious'],
                                            'frivolity n. 轻浮, 轻佻'),
                                    TestWay('adj',
                                            '不重要的',
                                            'of little weight or importance',
                                            ["The frivolous comment was soon forgotten. 那个不值一提的评论很快就被遗忘了"],
                                            ['trivial', 'flimsy', 'light', 'petty', 'trifling'],
                                            ['consequential', 'eventful', 'meaningful', 'momentous', 'weighty'])])])

list10_unit10 = VocabularyList([Word('frothy', "",
                                   [TestWay('adj',
                                            '用轻薄材料制作的',
                                            'made of light thin material',
                                            ["a frothy laptop made of carbon fiber and alloys 碳纤维以及合金制造的轻薄型笔记本电脑"],
                                            ['delicate', 'gossamer', 'light'],
                                            ['weighty', 'sturdy']),
                                    TestWay('adj',
                                            '(内容等)欢乐轻佻、不严肃的',
                                            'gaily frivolous or light in content or treatment',
                                            ["a frothy movie 一部有喜感的电影"],
                                            ['flighty', 'frivolous', 'puerile'],
                                            ['earnest', 'serious', 'sober'])]),
                              Word('frowsy', "",
                                   [TestWay('adj',
                                            '邋遢的',
                                            'having a slovenly or uncared-for appearance',
                                            ["frowsy hair 邋遢的头发"],
                                            ['slovenly', 'unkempt', 'untidy'],
                                            ['dapper', 'neat', 'tidy', 'spruce']),
                                    TestWay('adj',
                                            '味道难闻的',
                                            'having an unpleasant smell',
                                            ["The abandoned house was dank and frowsy and barely fit for human habitation. 这座废房子光线又暗, 气味又难闻, 几乎无法供人居住"],
                                            ['fetid', 'noisome', 'smelly', 'stinky'],
                                            ['ambrosial', 'aromatic', 'fragrant', 'redolent'])]),
                              Word('frugal', "",
                                   [TestWay('adj',
                                            '节约的',
                                            'characterized by or reflecting economy in the use of resources',
                                            ["be frugal in her expenditures 节约她的开销"],
                                            ['sparing', 'economical', 'provident', 'stingy'],
                                            ['extravagant', 'prodigal', 'sumptuous'],
                                            'frugality n. 节俭')]),
                              Word('frustrate', "",
                                   [TestWay('vt',
                                            '挫败, 阻挠',
                                            'to prevent from accomplishing a purpose or fulfilling a desire',
                                            ["frustrated their scheme in time 及时挫败了他们的阴谋"],
                                            ['ruin', 'baffle', 'balk', 'circumvent', 'foil', 'thwart'],
                                            ['abet', 'accomplish', 'fulfill']),
                                    TestWay('vt',
                                            '使沮丧',
                                            'to lessen the courage or confidence of',
                                            ["frustrated by his failure 为他的失败感到沮丧"],
                                            ['chill', 'daunt', 'dishearten', 'dismay', 'dispirit'],
                                            ['embolden', 'encourage', 'nerve', 'steel'],
                                            'frustration n. 沮丧; 阻挠; frustrated adj. 沮丧的')]),
                              Word('full-bodied', "",
                                   [TestWay('adj',
                                            '重要的',
                                            'having importance, significance, or meaningfulness',
                                            ["a full-bodied study of genetic engineering 一项基因工程的重要研究"],
                                            ['important', 'consequential', 'momentous', 'significant', 'weighty'],
                                            ['trivial']),
                                    TestWay('adj',
                                            '味道浓烈的',
                                            'having richness and intensity of flavor or aroma',
                                            ["full-bodied perfume in the cabin 车厢内浓郁的香水味"],
                                            ['strong', 'concentrated'],
                                            ['insipid'])]),
                              Word('fulminate', "",
                                   [TestWay('v',
                                            '大声斥责',
                                            'to issue a thunderous verbal attack or denunciation',
                                            ["fulminate the so-called curricular reform 痛斥所谓的课程改革"],
                                            ['criticize', 'blame', 'censure', 'condemn', 'denounce', 'denunciate', 'lambaste', 'reprehend', 'reprobate'],
                                            ['applaud', 'compliment', 'praise'],
                                            'fulmination n. 训斥')]),
                              Word('fumble', "",
                                   [TestWay('vt',
                                            '笨拙地做',
                                            'to make awkward attempts to do or find something',
                                            ["fumbled in his pocket for a coin 从口袋里笨拙地摸出一枚硬币"],
                                            ['botch', 'flounder', 'mess', 'stumble']),
                                    TestWay('n',
                                            '(无意识的)失误',
                                            'an unintentional departure from truth or accuracy',
                                            ["played the entire piano piece without a single fumble 完美地演绎了整首钢琴曲"],
                                            ['blunder', 'fault', 'gaffe', 'lapse', 'misstep', 'mistake'])]),
                              Word('furor', "",
                                   [TestWay('n',
                                            '喧闹, 激动, 狂热',
                                            'a state of intense excitement or ecstasy',
                                            ["The decision to raise tax has caused a great furor among the working class. 提高税收的决定引起了工人阶级的强烈反响"],
                                            ['delirium', 'frenzy', 'fever', 'fury', 'hysteria', 'outrage', 'rage', 'uproar', 'wrath'],
                                            ['serenity', 'tranquility', 'delight', 'pleasure'])]),
                              Word('furtive', "",
                                   [TestWay('adj',
                                            '鬼鬼祟祟的; 秘密的',
                                            'done by stealth',
                                            ["a furtive glance at her 朝她投去的隐秘一瞥"],
                                            ['secret', 'clandestine', 'covert', 'stealthy', 'surreptitious'],
                                            ['aboveboard', 'candid', 'forthright'])]),
                              Word('fury', "",
                                   [TestWay('n',
                                            '暴怒',
                                            'intense, disordered, and often destructive rage',
                                            ["The gods unleashed their fury on the offending mortal. 诸神将怒火降在了对那些对神明不敬的凡人身上"],
                                            ['anger', 'indignation', 'ire', 'mad', 'rage', 'wrath'],
                                            ['forbearance', 'delight', 'pleasure'],
                                            'furious adj. 狂暴的, 暴怒的')])])

LIST10 = VocabularyList(list10_unit1.words+list10_unit2.words+list10_unit3.words+list10_unit4.words+list10_unit5.words+list10_unit6.words+list10_unit7.words+list10_unit8.words+list10_unit9.words+list10_unit10.words)
