#!/usr/bin/env python
# -*- coding:utf-8 -*-
from word import VocabularyList, Word, TestWay

#part_of_speech, translation, definition, examples, synonyms, antonyms, other_form


list27_unit1 = VocabularyList([Word('veracious', "",
                                   [TestWay('adj',
                                            '诚实的, 说实话的',
                                            'being in the habit of telling the truth',
                                            ["a veracious witness 诚实的证人‖He has a reputation for being veracious, so people generally take his word for things. 他诚实的名声让其他人通常都相信他说的话"],
                                            'honest, truthful',
                                            'dishonest, lying, mendacious, prevaricating, untruthful'),
                                    TestWay('adj',
                                            '精确的, 准确的',
                                            'precise, accurate',
                                            ["a novel that presents a fairly veracious and unvarnished picture of the lives of affluent suburbanites 一部准确而不加修饰地描述郊区富人生活的小说"],
                                            'accurate, exact, precise, proper, right, true',
                                            'false, improper, inaccurate, incorrect, inexact, untrue, wrong',
                                            'veracity n. 诚实')]),
                              Word('verbatim', "",
                                   [TestWay('adv',
                                            '逐字地, 一字不差地',
                                            'in the exact words',
                                            ["You can't just copy the encyclopedia article verbatim for your report - that's plagiarism. 你不能一字不差地抄百科全书上的内容——这是剽窃。"],
                                            'ad verbum, directly, exactly, word for word',
                                            'inaccurately, inexactly',
                                            'verbalism n. 言辞, 单词')]),
                              Word('verbose', "",
                                   [TestWay('adj',
                                            '冗长的, 啰嗦的',
                                            'containing more words than necessary',
                                            ["a verbose orator 啰嗦的演讲者‖She has a verbose writing style. 她的文风很啰嗦"],
                                            'circuitous, circumlocutory, diffuse, garrulous, long-winded, prolix, rambling, verbose, windy',
                                            'brief, compact, concise, pithy, succinct, terse',
                                            'verbosity n. 冗长, 啰嗦')]),
                              Word('verdant', "",
                                   [TestWay('adj',
                                            '(因长满植物而)翠绿的, 郁郁葱葱的',
                                            'green with vegetation; covered with green growth',
                                            ["verdant fields 翠绿的田野"],
                                            'green, grown, leafy, luxuriant, overgrown',
                                            'barren, impoverished, infertile, leafless, sterile')]),
                              Word('verify', "",
                                   [TestWay('vt',
                                            '校验, 证实',
                                            'to determine or test the truth or accuracy of, as by comparison, investigation, or reference',
                                            ["We need to verify your passport. 我们需要校验阁下的护照。"],
                                            'attest, authenticate, certify, corroborate, substantiate, support, validate, vindicate',
                                            'disprove, rebut, refute',
                                            'verified adj. 经证实的; verification n. 证实')]),
                              Word('verisimilar', "",
                                   [TestWay('adj',
                                            '似乎真实的',
                                            'appearing to be true or real',
                                            ["a verisimilar tale 一个似乎为真的传奇"],
                                            'likely, plausible, probable',
                                            'implausible, incredible, unbelievable')]),
                              Word('veritable', "",
                                   [TestWay('adj',
                                            '真正的, 确实的',
                                            'being in fact the thing named and not false, unreal, or imaginary',
                                            ["a veritable manuscript 一份原稿"],
                                            'authentic, credible, genuine, real, true, unquestionable, bona fide',
                                            'bogus, counterfeit, fake, false, mock, phony, pseudo, sham, spurious')]),
                              Word('vernacular', "",
                                   [TestWay('n',
                                            '方言',
                                            'a nonstandard language or dialect of a place, region, or country',
                                            ["phrases that occur in the common vernacular 常见方言中的词组"],
                                            'argot, cant, dialect, jargon, lingo, slang'),
                                    TestWay('adj',
                                            '非正式的, 口头的',
                                            'used in or suitable for speech and not formal writing',
                                            ["writes essays in a very easy-to-read, vernacular style 用一种易懂的口头化风格写作conversational, informal, nonliterary, vulgar"],
                                            'conversational, informal, nonliterary, vulgar',
                                            'bookish, formal, learned, literary')]),
                              Word('versatile', "",
                                   [TestWay('adj',
                                            '多才多艺的, 全能的',
                                            'able to do many different kinds of things',
                                            ["We have found a versatile baseball player who can play any position. 我们发现了一个能打任何位置的全能型球员。"],
                                            'adaptable, all-around, ambidextrous, protean, universal',
                                            'limited'),
                                    TestWay('adj',
                                            '易改变的',
                                            'changing or fluctuating readily',
                                            ["a versatile disposition 多变的性格"],
                                            'capricious, changeable, fluid, inconstant, mercurial, skittish, temperamental, variable, volatile',
                                            'certain, changeless, constant, immutable, invariable, settled, stable, stationary, steady, unchangeable, unvarying')]),
                              Word('verse', "",
                                   [TestWay('vt',
                                            '使精通, 使熟悉',
                                            'to familiarize by close association, study, or experience',
                                            ["well versed in the theater 精通剧院‖While in prison, he versed himself in the rights of the incarcerated. 当他身处监狱时, 他通过自学熟悉了囚犯所享有的权利。"],
                                            'acquaint, familiarize, inform',
                                            'misinform, mislead'),
                                    TestWay('n',
                                            '诗歌',
                                            'a composition using rhythm and often rhyme to create a lyrical effect',
                                            ["composed a short verse for his father’s birthday 为他父亲的生日创作了一首小诗"],
                                            'ballad, lyric, poetry, song',
                                            'prose')])])

list27_unit2 = VocabularyList([Word('vertigo', "",
                                   [TestWay('n',
                                            '眩晕',
                                            'a dizzy confused state of mind',
                                            ["He had a dreadful attack of vertigo at the top of the tower. 他站在塔顶, 感到一阵令人窒息的眩晕。"],
                                            'dizziness, giddiness',
                                            'sobriety')]),
                              Word('verve', "",
                                   [TestWay('n',
                                            '活力, 热情',
                                            'vitality, liveliness',
                                            ["The instrumentalists played with skill and verve. 器乐表演者们有着高超的技巧与饱满的热情"],
                                            'animation, dynamism, energy, exuberance, liveliness, robustness, vibrancy, vigorousness, vim, vitality',
                                            'lethargy, listlessness, sluggishness, torpidity')]),
                              Word('vessel', "",
                                   [TestWay('n',
                                            '管',
                                            'a tube or canal (as an artery) in which a body fluid is contained and conveyed or circulated',
                                            ["blood vessel 血管"],
                                            'artery, vein'),
                                    TestWay('n',
                                            '船, 舰艇',
                                            'a watercraft bigger than a rowboat',
                                            ["the largest military vessel afloat 最大的军用舰艇"],
                                            'boat, cruiser, destroyer, ferry, ship, watercraft')]),
                              Word('vestige', "",
                                   [TestWay('n',
                                            '微小的遗迹, 小痕迹',
                                            'the smallest quantity or trace',
                                            ["A few strange words carved on a stone were the only vestige of the lost civilization. 石碑上刻着的几个奇怪的字符是这个失落文明的唯一的遗迹。‖the fossilized vestige of a dinosaur that traversed that muddy landscape millions of years ago 千万年横跨那块泥泞土壤的恐龙的化石碎片"],
                                            'echo, ghost, relic, remain, remnant, residual, shadow, trace',
                                            'vestigial adj. 残留的; 退化的')]),
                              Word('vestigial', "",
                                   [TestWay('adj',
                                            '退化的, 发育不全的',
                                            '(of certain organs or parts of organisms) having attained a simple structure and reduced size and function during the evolution of the species',
                                            ["snake that has vestigial limbs 拥有退化四肢的蛇"],
                                            'incomplete, rudimentary, undeveloped',
                                            'adult, full-blown, full-fledged, matured, ripe, ripened')]),
                              Word('veteran', "",
                                   [TestWay('n',
                                            '老兵, 有丰富经验的人',
                                            'one having knowledge or ability gained through long experience',
                                            ["As a veteran of overseas travel, she offered us solid advice about planning our trip. 作为一名资深的旅行家, 她给了我们提供了许多关于旅行规划的中肯建议"],
                                            'doyen, expert, master, maven, warhorse',
                                            'beginner, colt, fledgling, freshman, greenhorn, neophyte, novice, recruit, rookie, tenderfoot, tyro'),
                                    TestWay('adj',
                                            '经验丰富的, 资深的',
                                            'having or showing exceptional knowledge, experience, or skill in a field of endeavor',
                                            ["She is a veteran teacher who can mentor new teachers. 她的教师资历都老到可以教新教师了。"],
                                            'accomplished, adept, consummate, experienced, masterful, professed, skilled, versed, virtuoso',
                                            'amateur, inexperienced, inexpert, unprofessional, unseasoned, unskilled, unskillfull')]),
                              Word('veto', "",
                                   [TestWay('n./vt',
                                            '否决, 禁止',
                                            'to forbid or prohibit authoritatively',
                                            ["The President vetoed the bill. 总统否决了提案。", "We wanted to do a cross-country trip, but our parents vetoed it. 我们想来一次跨国旅行, 但是父母不肯批准。"],
                                            'blackball, decline, disallow, disapprove, kill, negative, refuse, reject',
                                            'accredit, approbate, authorize, clear, confirm, finalize, formalize, ratify, sanction, warrant')]),
                              Word('vex', "",
                                   [TestWay('vt',
                                            '使烦恼, 使恼怒',
                                            'to bring trouble, distress, or agitation to',
                                            ["vexed by her son's failure to clean his room 因为她儿子不清理房间而恼怒"],
                                            'aggravate, annoy, bother, exasperate, gall, grate, irk, nettle, peeve, rile',
                                            'appease, assuage, conciliate, mollify, placate, propitiate',
                                            'vexation n. 烦恼')]),
                              Word('viable', "",
                                   [TestWay('adj',
                                            '可行的',
                                            'capable of being done or carried out',
                                            ["a viable solution to the problem 解决问题的一个可行方案"],
                                            'achievable, attainable, doable, feasible, practicable, realizable, workable',
                                            'hopeless, impossible, impracticable, infeasible, unattainable, unviable, unworkable',
                                            'viability n. 可行性')]),
                              Word('vicarious', "",
                                   [TestWay('adj',
                                            '代理的, 取代的',
                                            'performed or suffered by one person as a substitute for another or to the benefit or advantage of another',
                                            ["use Internet as a vicarious form of social life 把互联网当作一种虚拟的社交生活"],
                                            'indirect, substitute, surrogate',
                                            'firsthand')])])

list27_unit3 = VocabularyList([Word('vicious', "",
                                   [TestWay('adj',
                                            '凶恶的, 恶毒的',
                                            'having or showing the desire to inflict severe pain and suffering on others',
                                            ["vicious slander 恶意的诽谤"],
                                            'atrocious, barbaric, barbarous, brutal, butcherly, fiendish, heartless, inhumane, sadistic, savage, truculent',
                                            'benign, benignant, compassionate, humane, kind, kindhearted, merciful, sympathetic'),
                                    TestWay('adj',
                                            '猛烈的',
                                            'marked by violence or ferocity',
                                            ["a vicious storm ripped through the region 在境内肆虐的强烈风暴"],
                                            'dreadful, excruciating, explosive, fearsome, ferocious, fierce, intensive, profound, vehement, violent',
                                            'light, moderate, soft',
                                            'viciousness n. 邪恶')]),
                              Word('vicissitude', "",
                                   [TestWay('n',
                                            '自然变化',
                                            'natural change or mutation visible in nature or in human affairs',
                                            ["vicissitude of daily life 日常生活的跌宕起伏"],
                                            'fluctuation, mutation, shift, variation',
                                            'uniformity',
                                            'vicissitudinous adj. 有变化的')]),
                              Word('victimize', "",
                                   [TestWay('vt',
                                            '使受骗',
                                            'to subject to deception or fraud',
                                            ["victimized by a confidence man with a slick story 被一个骗子用圆滑的故事欺骗"],
                                            'cheat, cozen, deceive, defraud, dupe, fool, hoax, swindle',
                                            'disabuse, disenchant, disillusion, undeceive')]),
                              Word('vigilant', "",
                                   [TestWay('adj',
                                            '警醒的, 警惕的',
                                            'alertly watchful especially to avoid danger',
                                            ["Police warned the public to be vigilant and report anything suspicious. 警方要求公众保持警惕, 并上报任何有嫌疑的人或事。", "When traveling through the city, tourists should be extra vigilant. 在这个城市旅行的游客应该保持格外的警惕。"],
                                            'alert, attentive, awake, cautious, observant, sharp, watchful',
                                            'careless, heedless, inattentive, unmindful, unthinking, unwary',
                                            'vigilance n. 警惕')]),
                              Word('vignette', "",
                                   [TestWay('n',
                                            '简介短文',
                                            'a vivid representation in words of someone or something',
                                            ["The general's memoirs are filled with revealing vignettes of some of the war’s most compelling personalities. 将军的回忆录里充满了短小的文章, 它们揭露了战争中最引人注意的人物。"],
                                            'definition, delineation, depiction, picture, portrait, portraiture, portrayal, rendering, sketch')]),
                              Word('vigorous', "",
                                   [TestWay('adj',
                                            '精力旺盛的',
                                            'having active strength of body or mind',
                                            ["He remains vigorous despite being over 80 years old. 尽管他已80高龄, 但仍活力不减"],
                                            'brisk, dynamic, energetic, lively, robust, spirited, vital',
                                            'dull, lethargic, listless, sluggish, torpid'),
                                    TestWay('adj',
                                            '强健的',
                                            'able to withstand hardship, strain, or exposure',
                                            ["vigorous and sturdy little sheep bred to live in mountainous regions 在山区喂养的健壮的小羊"],
                                            'hard, hardened, inured, rugged, stout, strong, sturdy, tough, toughened',
                                            'delicate, soft, tender, weak',
                                            'vigor n. 精力')]),
                              Word('vilify', "",
                                   [TestWay('vt',
                                            '诽谤, 辱骂',
                                            'to utter slanderous and abusive statements against',
                                            ["be vilified by the press because of her radical views 因为她激进的观点而被媒体抨击"],
                                            'asperse, blacken, calumniate, defame, libel, malign, smear, traduce',
                                            'acclaim, applaud, commend, praise',
                                            'vilification n. 辱骂')]),
                              Word('vim', "",
                                   [TestWay('n',
                                            '活力, 精力',
                                            'robust energy and enthusiasm',
                                            ["A little rest should give me back some of my vim. 稍事休息一会我应该就能回复些许精力"],
                                            'animation, bounce, dynamism, energy, liveliness, robustness, verve, vibrancy, vigorousness, vitality',
                                            'lethargy, listlessness, sluggishness, torpidity')]),
                              Word('vindicate', "",
                                   [TestWay('vt',
                                            '为…平反, 为…辩护, 使无罪',
                                            'to free from allegation or blame',
                                            ["The evidence would completely vindicate him. 这个证据将彻底证明他的清白。"],
                                            'absolve, acquit, exculpate, exonerate',
                                            'incriminate'),
                                    TestWay('vt',
                                            '证明, 证实',
                                            'to give evidence or testimony to the truth or factualness of',
                                            ["Recent discoveries have generally vindicated the physicist's theories. 近期的发现整体上证明了物理学家的理论。"],
                                            'attest, authenticate, certify, corroborate, substantiate, support, validate, verify',
                                            'disprove, rebut, refute')]),
                              Word('vindictive', "",
                                   [TestWay('adj',
                                            '复仇的(有寻仇倾向的)',
                                            'disposed to seek revenge',
                                            ["vindictive hatred for his brother 对他兄弟的仇恨"],
                                            'avenging, resentful, retaliatory, revengeful, vengeful',
                                            'forgiving, merciful, relenting')])])

list27_unit4 = VocabularyList([Word('virtuoso', "",
                                   [TestWay('n',
                                            '艺术鉴赏家, 专家',
                                            'a person with masterly skill or technique in the arts',
                                            ["a violin virtuoso 资深小提琴艺术家"],
                                            'adept, connoisseur, maestro, master, maven, proficient, wizard',
                                            'amateur, inexpert'),
                                    TestWay('adj',
                                            '经验丰富的, 技艺精湛的',
                                            'having or showing exceptional knowledge, experience, or skill in a field of endeavor',
                                            ["The American virtuoso cellist Lynn Harrell joins the orchestra as soloist in Shostakovich’s technically challenging Cello Concerto No 2. 来自美国的技艺精湛的大􁨀琴家林恩·哈雷尔作为独奏者加入了乐队, 共同演绎肖斯塔科维奇充满挑战的《第二大提琴协奏曲》。"],
                                            'accomplished, adept, consummate, experienced, masterful, professed, skilled, versed, veteran',
                                            'amateur, inexperienced, inexpert, unprofessional, unseasoned, unskilled, unskillful',
                                            'virtuosity n. 精湛技艺')]),
                              Word('virtuous', "",
                                   [TestWay('adj',
                                            '品德高尚的, 正直的',
                                            'having or showing virtue, especially moral excellence',
                                            ["Virtuous behavior is its own reward. 美德本身就是一种回报。", "She felt that she had made a virtuous decision by donating the money to charity. 她觉得把钱捐赠给慈善基金是一个高尚的决定。"],
                                            'decent, ethical, honest, honorable, moral, noble, righteous, straight, upright',
                                            'bad, evil, immoral, indecent, sinful, unethical, unrighteous, wicked, wrong')]),
                              Word('virulent', "",
                                   [TestWay('adj',
                                            '有毒的',
                                            'extremely poisonous or venomous',
                                            ["virulent bacteria 有毒的细菌"],
                                            'poisonous, toxic, venomous',
                                            'innocuous 无害的; healthy, salubrious, wholesome'),
                                    TestWay('adj',
                                            '凶残的',
                                            'marked by a rapid, severe, and destructive course',
                                            ["a virulent look on her face 面露凶色"],
                                            'cruel, malevolent, malicious, malignant, spiteful, vicious',
                                            'benevolent, benign, benignant, loving',
                                            'virulence n. 毒性, 恶毒')]),
                              Word('viscid', "",
                                   [TestWay('adj',
                                            '有粘性的',
                                            'having a glutinous consistency',
                                            ["viscid tree resin 粘性的树脂"],
                                            'adherent, adhesive, clingy, gluey, glutinous, tenacious, viscous',
                                            'slick')]),
                              Word('viscous', "",
                                   [TestWay('adj',
                                            '粘稠的, 粘的',
                                            'viscid; sticky',
                                            ["viscous syrup that takes forever to pour from a narrow-neck bottle 不知要花多久才能从窄口瓶中倒出来的粘稠糖浆"],
                                            'glutinous, syrup, viscid',
                                            'fluid, watery')]),
                              Word('visionary', "",
                                   [TestWay('adj',
                                            '空想的, 不切实际的',
                                            'having or marked by a tendency to be guided more by ideals than by reality',
                                            ["a visionary plan for a manned flight to Mars 一个构想中的载人火星计划"],
                                            'idealistic, imaginary, impractical, quixotic, romantic, utopian',
                                            'pragmatic'),
                                    TestWay('adj',
                                            '幻觉的',
                                            'not real and existing only in the imagination',
                                            ["claimed to have had visionary experiences of hell 宣称有过到达地狱的幻觉"],
                                            'chimerical, dreamy, fabulous, fantastic, illusory, phantom, unreal',
                                            'actual, existent, existing, real'),
                                    TestWay('adj',
                                            '有远见的',
                                            'having or marked by foresight and imagination',
                                            ["a visionary and legendary leader 一个有远见的传奇性领袖"],
                                            'farseeing, farsighted, forehanded, foreseeing, forethoughtful, prescient, proactive, provident',
                                            'improvident, myopic, shortsighted')]),
                              Word('vitality', "",
                                   [TestWay('n',
                                            '活力, 生命力',
                                            'physical or mental vigor especially when highly developed',
                                            ["Her vitality seemed to spread to everyone around her. 她的活力似乎能影响身边的每一个人"],
                                            'animation, bounce, dynamism, energy, liveliness, robustness, verve, vibrancy, vigorousness, vim',
                                            'lethargy, listlessness, sluggishness, torpidity',
                                            'vitalize vt. 激发, 使有活力')]),
                              Word('vitiate', "",
                                   [TestWay('v',
                                            '削弱, 损害',
                                            'to reduce the value or impair the quality of',
                                            ["Too many grammatical errors can vitiate the soundness of your writing, so double-check is recommended before submission. 太多的语法错误会削弱你论证的力度, 所以强烈建议交稿前检查几遍。"],
                                            'blemish, cripple, deface, degrade, deteriorate, flaw, harm, impair, mar, undermine',
                                            'doctor, fix, mend, patch, rebuild, recondition, reconstruct, renovate, repair, revamp'),
                                    TestWay('v',
                                            '(在道德、审美上)降低, 堕落',
                                            'to debase in moral or aesthetic status',
                                            ["Penchant for coarse language vitiates what is otherwise a refined literary style. 使用粗俗语言的倾向使得本该是一个高雅的文体变得不堪入目。"],
                                            'abase, cheapen, corrupt, debauch, demean, demoralize, deprave, pervert, profane, prostitute, subvert',
                                            'elevate, ennoble, uplift',
                                            'vitiated adj. 受损害的')]),
                              Word('vitriolic', "",
                                   [TestWay('adj',
                                            '(言辞)刻薄的',
                                            'bitterly scathing',
                                            ["vitriolic criticism 刻薄的批评"],
                                            'acerbic, acid, acrid, bitter, biting, caustic, corrosive, harsh, mordant, scalding, scathing, sharp, tart',
                                            'balmy, benign, bland, delicate, light, mellow, mild, nonabrasive, soft, soothing, tender',
                                            'vitriol n. 刻薄的话语')]),
                              Word('vituperate', "",
                                   [TestWay('vt',
                                            '谩骂, 责骂',
                                            'to abuse or censure severely or abusively',
                                            ["was vituperated for betraying his friends 因为背叛他的朋友而被责骂"],
                                            'abuse, assail, belabor, berate, castigate, excoriate, lambaste, reprimand, scold, rail, revile, upbraid',
                                            'admire, commend, laud, praise',
                                            'vituperative adj. 辱骂的')])])

list27_unit5 = VocabularyList([Word('vivacious', "",
                                   [TestWay('adj',
                                            '活泼的, 快活的',
                                            'lively in temper, conduct, or spirit',
                                            ["a vivacious girl who became a successful sales rep 一个成为了成功销售代表的活泼女孩"],
                                            'active, animated, bouncing, brisk, energetic, frisky, kinetic, mettlesome, spirited, sprightly, vital, zippy',
                                            'dead, inactive, inanimate, languid, languorous, leaden, lifeless, listless, spiritless, vapid',
                                            'vivacity n. 活力, 活泼')]),
                              Word('vociferous', "",
                                   [TestWay('adj',
                                            '喧哗的, 大叫大嚷的',
                                            'making, given to, or marked by noisy and vehement outcry',
                                            ["Vociferous opponents of the bill protested angrily outside the Congress. 议案的反对者在国会外愤怒地举行了声势浩大的抗议活动"],
                                            'blatant, boisterous, clamant, clamorous, obstreperous, strident, yowling',
                                            'reticent, taciturn, serene, tranquil')]),
                              Word('volatile', "",
                                   [TestWay('adj',
                                            '多变的',
                                            'characterized by or subject to rapid or unexpected change',
                                            ["a boss of volatile moods 一个性情多变的老板", "The stock market can be very volatile. 股市瞬息万变。"],
                                            'capricious, changeable, fluid, inconstant, mercurial, skittish, temperamental, variable, versatile',
                                            'certain, changeless, constant, immutable, invariable, settled, stable, stationary, steady, unchangeable, unvarying',
                                            'volatility n. 易变性, 易挥发性')]),
                              Word('volition', "",
                                   [TestWay('n',
                                            '意志, 自愿选择的行为',
                                            "the act or power of making one's own choices or decisions",
                                            ["beyond his volition or control 超出了他的意志和控制范围"],
                                            'choice, decision, discretion, will',
                                            'coercion, compulsion, constraint, duress, force, pressure')]),
                              Word('voluble', "",
                                   [TestWay('adj',
                                            '健谈的, 话多的',
                                            'characterized by ready or rapid speech',
                                            ["The voluble gadfly ruined the party. 聚会被那个话又多又让人讨厌的人破坏了。"],
                                            'chatty, eloquent, garrulous, glib, loquacious, talkative, vocative',
                                            'reticent, taciturn, laconic, reserved, succinct',
                                            'volubility n. 口若悬河')]),
                              Word('voluminous', "",
                                   [TestWay('adj',
                                            '卷数多的, 大量的, 庞大的',
                                            'having great volume, fullness, size, or number',
                                            ["trying to keep a track of voluminous academic database 尝试追踪数目庞大的学术数据库"],
                                            'colossal, considerable, elephantine, enormous, gargantuan, gigantic, mammoth, numerous, oversize',
                                            'scanty, scarce, dwarf, little, small, undersized')]),
                              Word('voluptuous', "",
                                   [TestWay('adj',
                                            '奢侈逸乐的, 沉溺酒色的',
                                            'given to or spent in enjoyments of luxury, pleasure, or sensual gratifications',
                                            ["They spent a long and voluptuous holiday in Venice. 他们在威尼斯度过了一个漫长而奢华的假期。"],
                                            'carnal, epicurean, luscious, lush, luxurious, indulgent, sensual, sensuous',
                                            'ascetic, spartan, self-denying',
                                            'voluptuary n. 酒色之徒')]),
                              Word('voracious', "",
                                   [TestWay('adj',
                                            '有很大食量的, 贪吃的',
                                            'having a huge appetite',
                                            ["He has a voracious appetite. 他的食量惊人。"],
                                            'edacious, esurient, gluttonous, swinish',
                                            'abstemious, abstentious'),
                                    TestWay('adj',
                                            '贪婪的, 如饥似渴的',
                                            'having or marked by an insatiable appetite for an activity or pursuit',
                                            ["a voracious reader who locked himself up in the study 一个把自己锁在书房的贪婪的读者"],
                                            'acquisitive, avid, covetous, grasping, greedy, hungry, rapacious, ravenous, thirsty',
                                            'apathetic, indifferent, uneager, unenthusiastic',
                                            'voracity n. 食欲, 贪婪')]),
                              Word('votary', "",
                                   [TestWay('n',
                                            '崇拜者, 信徒',
                                            'a person who is fervently devoted, as to a leader or ideal; a faithful follower',
                                            ["votaries of the religious leader 宗教领袖的追随者们"],
                                            'acolyte, adherent, devotee, disciple, fan, fanatic, partisan, pupil, zealot',
                                            'bellwether, leader, apostate, defector, renegade, traitor, turncoat')]),
                              Word('vouch', "",
                                   [TestWay('vt',
                                            '担保, 声称为真',
                                            'to declare (something) to be true or genuine; to give a guarantee',
                                            ["willing to vouch for her integrity 愿意担保她的人格"],
                                            'attest, avouch, guarantee, testify, warrant')])])

list27_unit6 = VocabularyList([Word('vulgar', "",
                                   [TestWay('adj',
                                            '粗俗的, 无教养的',
                                            'morally crude, undeveloped, or unregenerate',
                                            ["He is a vulgar man but his music is quite divine. 虽然他是一个粗俗的人, 但他的音乐却十分神圣。"],
                                            'bawdy, coarse, crass, crude, dirty, filthy, gross, lowbred, indecent, nasty, obscene, ribald, rude, uncouth',
                                            'civilized, cultivated, cultured, genteel, polished, refined, urbane, well-bred'),
                                    TestWay('adj',
                                            '口头的, 非正式的',
                                            'used in or suitable for speech and not formal writing',
                                            ["Latin was once the language of scholars, and English the vulgar language used by the common people. 很久以前拉丁语才是学术界的官方语言, 而英语是普通百姓所使用的。"],
                                            'conversational, informal, nonliterary, unliterary, vernacular',
                                            'bookish, formal, learned, literary')]),
                              Word('vulnerable', "",
                                   [TestWay('adj',
                                            '易受攻击的, 脆弱的',
                                            'open to attack or damage',
                                            ["The troops were deployed in a vulnerable position. 部队被部署在了一个容易遭受攻击的位置。", "The fort was undefended and vulnerable. 堡垒没有设防, 十分脆弱。"],
                                            'assailable, endangered, exposed, subject, susceptible',
                                            'guarded, protected, shielded, invincible, invulnerable',
                                            'vulnerability n. 弱点, 易受伤害')]),
                              Word('waddle', "",
                                   [TestWay('vi',
                                            '摇摇摆摆地走',
                                            'to walk with short steps that tilt the body from side to side',
                                            ["The duck waddled back into the water. 鸭子一摇一摆地回到了水中"],
                                            'careen, dodder, reel, teeter, totter',
                                            other_form = 'waddling adj. 摇摇摆摆的')]),
                              Word('waffle', "",
                                   [TestWay('vi',
                                            '胡扯',
                                            'to talk or write foolishly',
                                            ["This lecturer will waffle on for hours. 这个老师会胡说八道地扯几个小时。"],
                                            'babble, blather, drivel, gabble, prattle',
                                            'articulate')]),
                              Word('waft', "",
                                   [TestWay('vt',
                                            '飘荡, 漂浮',
                                            'to float easily and gently, as on the air',
                                            ["Heavenly aromas wafted from the kitchen. 令人欣悦的香气从厨房飘出。", "A feather wafted past us and settled on the grass. 一片羽毛飘过我们身边, 落在草地上。"],
                                            'buoy, drift, glide, hang, hover, raft',
                                            'flounder, sink, submerge')]),
                              Word('wag', "",
                                   [TestWay('n',
                                            '幽默诙谐的人',
                                            'a humorous or droll person',
                                            ["Some wag wrote a droll satire on the scandal. 一些有才的人就丑闻写了一个搞怪的讽刺。"],
                                            'comedian, comic, droll, humorist, joker, wit'),
                                    TestWay('vt',
                                            '摆动',
                                            'to move to and fro or up and down especially with quick jerky motions',
                                            ["The dog wagged its tail. 狗摆动着它的尾巴。"],
                                            'swish, switch, waggle')]),
                              Word('wan', "",
                                   [TestWay('adj',
                                            '苍白的, 病态的',
                                            'suggestive of poor health',
                                            ["She looks a little wan after all that tiring work. 在完成那些繁重的工作之后她看起来有些虚弱。"],
                                            'ashen, ashy, blanched, livid, lurid, sickly, pale, pallid',
                                            'blooming, florid, flush, full-blooded, glowing, red, rosy, rubicund, ruddy, sanguine')]),
                              Word('wanderlust', "",
                                   [TestWay('n',
                                            '旅行癖',
                                            'a very strong or irresistible impulse to travel',
                                            ["His wanderlust would not allow him to stay long in one spot. 他对旅行的渴望让他不可能在一处久待。"])]),
                              Word('wane', "",
                                   [TestWay('vi',
                                            '减少, 衰退, 降低',
                                            'to decrease in size, extent, or degree',
                                            ["In the evening the storm finally waned. 傍晚时分风暴终于减弱了。", "The moon waxes and then wanes. 月有阴晴圆缺"],
                                            'abate, decline, diminish, dwindle, ease, ebb, fall, lessen, lower, moderate, recede, shrink, subside, taper',
                                            'accumulate, balloon, burgeon, enlarge, escalate, expand, grow, increase, intensify, mushroom, rise, snowball, soar, wax',
                                            'waning adj. 衰退的, 减少的')]),
                              Word('want', "",
                                   [TestWay('n',
                                            '短缺',
                                            'the condition or quality of lacking something usual or necessary',
                                            ["There's a notable want of teachers in rural areas. 农村地区存在着值得注意的师资短缺问题"],
                                            'absence, dearth, deficiency, drought, famine, inadequacy, insufficiency, lack, paucity, scarcity, shortage',
                                            'abundance, adequacy, amplitude, opulence, plenitude, plenty, sufficiency, wealth'),
                                    TestWay('vt',
                                            '渴望',
                                            'to have a strong desire for',
                                            ["I want a new car so badly! 我太想要一辆新车了！", "She wanted more time to finish the test. 她希望能有更多的时间来完成考试。"],
                                            'ache, covet, crave, hunger, itch, long, lust, pine, repine, thirst, wish, yearn',
                                            'abhor, abominate, despise, detest, execrate, hate, loathe')])])

list27_unit7 = VocabularyList([Word('warmonger', "",
                                   [TestWay('n',
                                            '好战者',
                                            'one who urges or attempts to stir up war',
                                            ["Fortunately, the warmongers met with overwhelming opposition. 幸运的是, 好战者们碰到了巨大的阻力。"],
                                            'belligerent, hawk, jingoist, war hawk',
                                            'dove, pacifist')]),
                              Word('warp', "",
                                   [TestWay('vt',
                                            '使偏向',
                                            'to turn from a correct or proper course',
                                            synonyms = 'avert, deflect, divert, veer',
                                            antonyms = 'straighten'),
                                    TestWay('vt',
                                            '扭曲, 变形',
                                            'to twist (something) out of a natural or normal shape or condition',
                                            ["The heat caused the wood to warp. 高温使得木头变形了。"],
                                            'deform, misshape, screw, torture'),
                                    TestWay('vt',
                                            '曲解',
                                            'to change so much as to create a wrong impression or alter the meaning of',
                                            ["The faulty English translation really warps the meaning of the original Chinese text. 错误的英语翻译曲解了中文的原意。"],
                                            'distort, falsify, misinterpret, misrepresent, twist',
                                            'clarify, clear, explain, illuminate, illustrate',
                                            'warped adj. 弯曲的, 变形的')]),
                              Word('warrant', "",
                                   [TestWay('vt',
                                            '承诺',
                                            'to assume responsibility for the satisfactory quality or performance of',
                                            ["The computer company unconditionally warrants all of its products for one full year. 这个电脑公司对所有的产品提供为期一年的质量保证。"],
                                            'assure, avouch, guarantee, vouch'),
                                    TestWay('vt',
                                            '批准, 认可',
                                            'to give official acceptance of as satisfactory',
                                            ["The law warrants these measures. 法律允许这些措施。"],
                                            'approbate, authorize, clear, confirm, finalize, formalize, ratify, sanction',
                                            'decline, deny, disallow, disapprove, negative, reject, veto',
                                            'warranted adj. 有正当理由的; warranty n.保证, 承诺')]),
                              Word('wary', "",
                                   [TestWay('adj',
                                            '小心的, 机警的, 谨慎的',
                                            'marked by keen caution, cunning, and watchfulness',
                                            ["kept a wary eye out for signs of the enemy 对敌人出现的征兆保持警惕"],
                                            'alert, cautious, chary, circumspect, conservative, guarded, heedful, vigilant, watchful',
                                            'careless, heedless, incautious, unguarded, unmindful, unwary',
                                            'wariness n. 谨慎, 小心')]),
                              Word('wastrel', "",
                                   [TestWay('n',
                                            '肆意挥霍的人, 败家子',
                                            'one who expends resources foolishly and self-indulgently',
                                            ["He ended up being a wastrel and a drunkard. 他最后成了一个花天酒地的败家子。"],
                                            'fritterer, profligate, spender, spendthrift, squanderer, waster',
                                            'economizer, penny-pincher, hoarder, miser, niggard')]),
                              Word('watershed', "",
                                   [TestWay('n',
                                            '重要关头, 分水岭',
                                            'a crucial dividing point: turning point',
                                            ["a watershed moment in her life 她命运的分水岭"],
                                            'climax, corner, event, landmark, milestone')]),
                              Word('wax', "",
                                   [TestWay('vi',
                                            '月亮渐满',
                                            'to increase in phase or intensity, used chiefly of the moon, other satellites, and inferior planets',
                                            antonyms = 'wane'),
                                    TestWay('vt',
                                            '用蜡涂、处理或上光',
                                            'to coat (something) with a slippery substance in order to reduce friction',
                                            ["wax the floor 给地板打蜡"],
                                            'grease, oil, slick',
                                            'coarsen, rough, roughen'),
                                    TestWay('vi',
                                            '增大, 增强',
                                            'to increase in size, numbers, strength, prosperity, or intensity',
                                            ["The commitment of the young volunteers to the cause seems to wax. 青年志愿者们对于这项事业的投入似乎在增多。"],
                                            'accelerate, accumulate, appreciate, balloon, boom, burgeon, enlarge, escalate, expand, proliferate, rise',
                                            'contract, decrease, diminish, dwindle, lessen, recede',
                                            'waxing adj. 增加的waylay')]),
                              Word('waylay', "",
                                   [TestWay('vt',
                                            '埋伏, 伏击',
                                            'to lie in wait for or attack from ambush',
                                            ["Unsuspecting tourists are often waylaid by gangs. 不警惕的旅客们常常被犯罪团伙偷袭。", "We were waylaid by a group of protestors with rocks. 我们被一群示威者用石头偷袭了。"],
                                            'ambush, assault, lurk, surprise')]),
                              Word('welter', "",
                                   [TestWay('n',
                                            '混乱; 动乱',
                                            'a state of wild disorder',
                                            ["There was a welter of pushing and shoving. 到处是推搡和拥挤的混乱局面。", "The troop withdrawal would plunge the country into a welter of anarchy and endless civil war. 撤军会使得这个国家陷入无政府的动乱和无尽的内战中。"],
                                            'disturbance, furor, hurricane, pandemonium, turmoil, turmoil, uproar, whirl',
                                            'calm, peace, tranquility, order')]),
                              Word('wheedle', "",
                                   [TestWay('vt',
                                            '(用花言巧语)诱惑, 哄骗',
                                            'to persuade or attempt to persuade by flattery or guile',
                                            ["wheedled him into working for them 哄骗他为他们工作", "She pleaded and wheedled, but I wouldn't be swayed. 她软磨硬泡地求我, 但我仍不动摇。"],
                                            'adulate, blandish, cajole, coax',
                                            'coerce, compel, demand, force, oblige, require')])])

list27_unit8 = VocabularyList([Word('whet', "",
                                   [TestWay('vt',
                                            '磨快',
                                            'to sharpen by rubbing on or with something (as a stone)',
                                            ["whetted the dagger with the grindstone 用磨石把匕首磨锋利"],
                                            'edge, grind, hone, stone, strop',
                                            'blunt, dull')]),
                              Word('whiff', "",
                                   [TestWay('n',
                                            '微风',
                                            'a quick puff or slight gust especially of air, odor, gas, smoke, or spray',
                                            ["A whiff of fresh air reinvigorated him. 一股清新的空气让他恢复了活力。"],
                                            'breath, puff',
                                            'blast'),
                                    TestWay('n',
                                            '细微的信号, 略微痕迹',
                                            'an almost imperceptible sign of something',
                                            ["Even a whiff of appreciation for everything I've done for her would have been nice. 她哪怕是对我为她的付出流露出一丁点的感激之情也好啊。", "Humanity is unregenerable and hates the language of conformity, since conformity has a whiff of the inhuman about it. (Anthony Burgess) 人性是不能改造也无发统一的, 因为一致性本身带有一点点不人道的意味。(安东尼•伯吉斯)"],
                                            'flicker, glimmer, suggestion, touch, trace')]),
                              Word('whimsical', "",
                                   [TestWay('adj',
                                            '反复无常的',
                                            'prone to sudden illogical changes of mind, ideas, or actions',
                                            ["It’s hard to make plans with such a whimsical friend. 和这样一个反复无常的朋友做决定是很困难的。"],
                                            'capricious, fickle, freakish, mercurial, volatile',
                                            'resolute, unwavering',
                                            'whimsicality n. 反复无常')]),
                              Word('wholesome', "",
                                   [TestWay('adj',
                                            '有益身心健康的',
                                            'promoting mental, moral, or social health',
                                            ["trying to eat a more wholesome diet 尽可能有更健康的饮食习惯"],
                                            'healthy, restorative, salubrious, recuperative, tonic',
                                            'insalubrious, noxious, unhealthy, unwholesome',
                                            'wholesomeness n. 健康')]),
                              Word('wicked', "",
                                   [TestWay('adj',
                                            '邪恶的',
                                            'morally very bad',
                                            ["a wicked urge to steal just for the sake of stealing 纯粹为了偷盗而偷盗的邪恶冲动"],
                                            'dark, evil, immoral, iniquitous, nefarious, sinful, vicious, villainous',
                                            'decent, ethical, good, honest, honorable, moral, righteous, sublime, upright, virtuous',
                                            'wickedness n. 邪恶')]),
                              Word('wince', "",
                                   [TestWay('vi',
                                            '畏缩',
                                            'to shrink back involuntarily as from pain',
                                            ["winced at the horrible corpses 在令人恐惧的尸体面前畏缩"],
                                            'blench, cringe, quail, quiver, recoil, shrink, tremble',
                                            'confront, face, meet, challenge')]),
                              Word('windbag', "",
                                   [TestWay('n',
                                            '健谈的人',
                                            'an exhaustively talkative person',
                                            ["With a windbag like that, who needs a wind farm to meet our energy needs? 有了他这样一个多话的“吹风机”, 谁还要风力发电厂来满足电力需求呢？"],
                                            'babbler, conversationalist, gabbler, gasbag, prattler')]),
                              Word('windy', "",
                                   [TestWay('adj',
                                            '冗长的',
                                            'characterized by wearisome verbosity',
                                            ["a windy saleswoman who told us a lot more than we wanted to know about vacuum cleaners 一个啰嗦的女销售员, 一个劲地说着我们不想知道的关于吸尘器的细节"],
                                            'circuitous, circumlocutory, diffuse, garrulous, prolix, rambling, verbose',
                                            'compact, concise, crisp, pithy, succinct, terse')]),
                              Word('winsome', "",
                                   [TestWay('adj',
                                            '迷人的, 漂亮的',
                                            'generally pleasing and engaging often because of a childlike charm and innocence',
                                            ["fascinated by her winsome smile 为她动人一笑所倾倒"],
                                            'adorable, charming, disarming, enchanting, endearing, sweet, winning',
                                            'abhorrent, abominable, detestable, hateful, loathsome, odious',
                                            'winsomeness n. 迷人')]),
                              Word('wit', "",
                                   [TestWay('n',
                                            '机智, 智慧',
                                            'the natural ability to perceive and understand',
                                            ["lacked the wit to judge 缺乏判断的智慧"],
                                            'astuteness, brilliance, foxiness, intelligence, keenness, perspicacity, sagacity, sharpness, shrewdness',
                                            'brainlessness, dullness, fatuity, lunacy, silliness'),
                                    TestWay('n',
                                            '智者, 有智慧的人',
                                            'a person of exceptional intelligence',
                                            ["a man who fancied himself as a great wit 一个把自己想象成智慧的化身的男子"],
                                            'illuminati, pundit, sage, savant, scholar',
                                            'dolt, fool, idiot, simpleton',
                                            'witty adj. 有智慧的')])])

list27_unit9 = VocabularyList([Word('withdraw', "",
                                   [TestWay('vi',
                                            '撤退',
                                            'to take back or away',
                                            ["The army was forced to withdraw from the frontline. 部队被迫从前线撤回"],
                                            'recede, retreat, fall back',
                                            'advance, place, position, put',
                                            'withdrawal n. 撤退; withdrawn adj. 性格内向的, 离群的')]),
                              Word('wither', "",
                                   [TestWay('vi',
                                            '枯萎, 凋谢',
                                            'to become dry and sapless',
                                            ["Amaranth is a legendary flower that never withers. 传说中的Amaranth是一种永不凋谢的花。"],
                                            'dry, fade, shrivel, wane, wilt, wizen',
                                            'revive, bloom, flourish, prosper, thrive',
                                            'withering adj. 凋谢的, 凋亡的')]),
                              Word('withhold', "",
                                   [TestWay('vt',
                                            '扣压, 不给予',
                                            'to refrain from granting, giving, or allowing',
                                            ["withhold sensitive information 限制敏感信息的传播"],
                                            'decline, disallow, disapprove, detain, refuse, reject, reprobate, restrain, retain',
                                            'allow, concede, grant, permit')]),
                              Word('wizen', "",
                                   [TestWay('vt',
                                            '(使)凋谢, (使)枯萎',
                                            'to become dry, shrunken, and wrinkled often as a result of aging or of failing vitality',
                                            synonyms = 'dry, mummify, shrivel, wither',
                                            antonyms = 'revive, bloom, flourish, prosper, thrive'),
                                    TestWay('adj',
                                            '凋谢的, 枯萎的',
                                            'shriveled or dried up',
                                            synonyms = 'faded, withered',
                                            antonyms = 'blooming')]),
                              Word('wobble', "",
                                   [TestWay('vi',
                                            '摇晃, 颤抖',
                                            'to move or proceed with an irregular rocking or staggering motion or unsteadily and clumsily from side to side',
                                            ["The drunk stood up, wobbled for a moment, and fell forward. 醉汉站了起来, 晃动了一阵, 然后向前倒了下去"],
                                            'rock, totter',
                                            'stabilize'),
                                    TestWay('vi',
                                            '犹豫不决',
                                            'to show uncertainty about the right course of action',
                                            ["We cannot tolerate the government wobbling at this critical time. 我们不能容忍政府在这种关键时刻犹豫不决。"],
                                            'falter, stagger, teeter, vacillate, waver')]),
                              Word('worldly', "",
                                   [TestWay('adj',
                                            '世间的, 世俗的',
                                            'of this world rather than spiritual or religion affairs',
                                            ["preoccupied with worldly concerns 纠缠于世俗的忧虑", "It is time you woke up and focused your thoughts on more worldly matters. 现在你应该停止做梦然后把自己的精力集中在更现实的问题上了。"],
                                            'carnal, corporeal, material, mundane',
                                            'mental, spiritual, heavenly'),
                                    TestWay('adj',
                                            '老练的',
                                            'experienced in human affairs',
                                            ["My little sister was worldly and sophisticated, quite unlike me. 与我截然不同的是, 我的妹妹在为人处世方面非常老练。"],
                                            'cosmopolitan, sophisticated',
                                            'ingenuous, innocent, naïve, unsophisticated')]),
                              Word('worship', "",
                                   [TestWay('n',
                                            '崇拜, 敬仰',
                                            'extravagant respect to an object of esteem',
                                            ["the belief in swords and the worship of force 刀剑信仰与武力崇拜"],
                                            'adulation, adoration, deification, idolatry, reverence, veneration',
                                            'dislike, dismissal, disregard, hatred, loathing, scorn'),
                                    TestWay('v',
                                            '崇拜, 膜拜',
                                            'to offer honor or respect to (someone) as a divine power',
                                            ["The ancient Greeks worshipped many different gods. 古希腊人崇拜不同的神明。"],
                                            'adore, deify, glorify, revere, venerate',
                                            'blaspheme, desecrate, profane, violate')]),
                              Word('wrangle', "",
                                   [TestWay('n',
                                            '纷争, 争端',
                                            'an often noisy or angry expression of differing opinions',
                                            ["There was a bit of a wrangle over how much money to give the high school for its sports programs. 这个高中应该获得多少体育项目的拨款引起了一阵纷争。"],
                                            'altercation, controversy, disagreement, dispute, fight, imbroglio, quarrel, squabble',
                                            'harmony'),
                                    TestWay('v',
                                            '争吵',
                                            'to quarrel noisily or angrily',
                                            ["Local residents wrangled for hours about property taxes. 当地居民就房产税的问题争吵不休。"],
                                            'altercate, argue, bicker, controvert, hassle, quibble, spat, tiff',
                                            other_form = 'wrangler n. 争吵的人')]),
                              Word('wretched', "",
                                   [TestWay('adj',
                                            '极差的',
                                            'very poor in quality or ability',
                                            ["the wretched conditions of the refugee camp 难民营极恶劣的条件"],
                                            'bad, coarse, inferior, low-grade, mediocre, miserable, poor, rubbishy, terrible, trashy',
                                            'excellent, fine, first-class, first-rate, good, high-grade, superior'),
                                    TestWay('adj',
                                            '沮丧的',
                                            'deeply afflicted, dejected, or distressed in body or mind',
                                            ["She was wretched for weeks after breaking up with her boyfriend. 她与男友分手后郁闷了几个星期。"],
                                            'blue, crestfallen, dejected, doleful, dolorous, gloomy, melancholy, mournful, rueful, sorrowful, woeful',
                                            'blissful, buoyant, cheerful, delighted, glad, happy, joyful, jubilant',
                                            'wretchedness n. 沮丧')]),
                              Word('wry', "",
                                   [TestWay('adj',
                                            '扭曲的',
                                            'abnormally twisted or bent to one side',
                                            ["a wry smile 扭曲的笑容"],
                                            'bending, crooked, curving, devious',
                                            'common, normal, usual'),
                                    TestWay('adj',
                                            '坚持错误的',
                                            'stubborn in adherence to wrong opinion or principles',
                                            synonyms = 'headstrong, obstinate, pertinacious, perverse, stubborn, wrongheaded',
                                            antonyms = 'amenable, compliant, complying, flexible, pliable, pliant, relenting, yielding')])])

list27_unit10 = VocabularyList([Word('xenophobe', "",
                                   [TestWay('n',
                                            '仇视(或畏惧)外国人(或外国事物)者',
                                            'one unduly fearful of what is foreign and especially of people of foreign origin',
                                            ["But from what I know, no way could this thoroughly US-educated woman (from the age of 12) be a xenophobe. 但根据我的了解, 这个从12岁起就接受彻底的美国教育的女人不可能是抵触外国事物的人。"],
                                            antonyms = 'xenomania',
                                            other_form = 'xenophobia n. 仇外情绪')]),
                              Word('yoke', "",
                                   [TestWay('v',
                                            '连接',
                                            'to become joined or linked',
                                            ["yoked several ideas together to propose a novel theory 将几个想法结合起来提出一个全新的理论"],
                                            'chain, conjugate, hook, interconnect, join, link, unite',
                                            'disconnect, disjoin, dissever, disunite, separate, sunder, unchain, unlink, unyoke')]),
                              Word('yokel', "",
                                   [TestWay('n',
                                            '乡下人, 天真纯朴的人',
                                            'a naive or gullible inhabitant of a rural areaor small town',
                                            ["a lame comedy about the misadventures of yokels in the big city 描述乡下人在大都市中遭遇的不幸的劣质喜剧"],
                                            'bucolic, bumpkin, churl, provincial, rustic',
                                            'cosmopolitan, 云游四海的人')]),
                              Word('zeal', "",
                                   [TestWay('n',
                                            '热心, 热诚',
                                            'enthusiastic devotion to a cause, ideal, or goal and tireless diligence in its furtherance',
                                            ["preaches with fanatical zeal 带着狂热进行传教"],
                                            'ardor, devotion, enthusiasm, fervidness, fervor, passion',
                                            'apathy, indifference, nonchalance, torpor, unconcern',
                                            'zealous adj. 狂热的')]),
                              Word('zealot', "",
                                   [TestWay('n',
                                            '狂热者',
                                            'a zealous person; especially: a fanatical partisan',
                                            ["a religious zealot calling for another Crusade 呼唤下一场十字军东征的宗教狂热者"],
                                            'activist, crusader, fanatic, partisan, red hot',
                                            other_form = 'zealotry n. 狂热的行为')]),
                              Word('zenith', "",
                                   [TestWay('n',
                                            '最高点, 巅峰',
                                            'culminating point',
                                            ["at the zenith of his power 位极人臣"],
                                            'acme, apex, apogee, climax, crescendo, crest, peak, pinnacle, summit, top',
                                            'bottom, nadir')]),
                              Word('zesty', "",
                                   [TestWay('adj',
                                            '刺激的, 开胃的',
                                            'appealingly piquant or lively',
                                            ["a zesty sauce 味道刺激的酱汁"],
                                            'peppery, piquant, pungent, salty, savory, spicy, zingy',
                                            'bland, insipid, vapid, zestless')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')]),
                              Word('', "",
                                   [TestWay('',
                                            '',
                                            '',
                                            [""],
                                            '',
                                            '')])])

LIST27 = VocabularyList(list27_unit1.words+list27_unit2.words+list27_unit3.words+list27_unit4.words+list27_unit5.words+list27_unit6.words+list27_unit7.words+list27_unit8.words+list27_unit9.words+list27_unit10.words)
